### ISSUE TITLE
Secure wipe: Eraser (for Windows)

### ISSUE THREAD

**Issue by hshsb** [nylira/prism-break#1001]
Please see http://eraser.heidi.ie/

While I'm at it, I find www.portableapps.com a useful resource for Windows users concerned about security.

**Comment by yegortimoshenko** [comment]
Source code: https://sourceforge.net/p/eraser/code/HEAD/tree/trunk/eraser/

Hasn't been substantially updated since 2015. Also dangerous in that it perpetuates two myths:

* [that Gutmann algorithm is a good idea](http://vocaro.com/trevor/blog/2006/09/18/the-myth-of-the-gutmann-method/comment-page-1/), up to date, publicly, no one has been able to restore any data from the disk even after zeroing it out
* and that it's possible to completely erase data from SSD (it's not because SSD controller uses wear leveling and stops writing to certain bad blocks, that will indefinitely remain there and contain the original data)

So the only way to ensure that there's no data on SSD is to use encryption from the day it was bought, and to erase data from hard drive it is enough to just run `sudo dd if=/dev/zero of=/dev/sda bs=1m` or `format C: /fs:NTFS /p:1` if you're on Windows.

**Comment by yegortimoshenko** [comment]
Also, disk erasers are out of scope because PRISM Break only lists software for which proprietary alternatives spy, or leak data, or otherwise infringe upon privacy.
