### ISSUE TITLE
Remove all Windows related suggestions

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#1008]
As discussed in issue #998 I think it's wrong to suggest applications to windows users to help improve their privacy. Any tool you run on a so obviously compromised OS, doesn't give you any real benefit. Instead, it may even cause harm: remember the windows bot net which was running Tor... Tor developers said this was the most dangerous threat they had ever faced. Luckily the botnet wasn't meant to break Tor (check [this video](http://media.ccc.de/browse/congress/2013/30C3_-_5423_-_en_-_saal_1_-_201312272030_-_the_tor_network_-_jacob_-_arma.html) from minute 38 or 39 when they show the chart of "Directly connecting users"). Sure, the Tor project also has economic reasons not to piss off the whole windows userbase. We don't.

So:
- windows is compromised (not just compromised, but _obviously_ compromised)
- running security related programs on such a compromised OS is pointless
- people should be made aware that it's not going to improve their privacy, nor is it going to help against mass surveillance if you do anything on an MS windows computer
- we should not give windows users a false understanding of this situation, nor should we help them getting a false feeling of privacy... the only straight conclusion is to remove all windows related suggestions
- introducing people to FLOSS software means: explain to them first that they gotta change their OS.

**Comment by nodiscc** [comment]
Windows users are clearly a target audience for prism-break (no need for analytics). I agree that removing windows suggestions altogether will _not_ help those users to eventually switch to a Free OS. I think we really should improve the warning about Windows being insecure:


  * It should be more prominent (warning icon? `Even using the software tools we recommend here, your privacy may be compromised by Windows` in **bold**?)
  * Provide links to evidence showing that some surveillance tools affect Windows specifically, with details, and add them to the warning.

**Comment by yegortimoshenko** [comment]
I also would rather see this closed, because using free userland is a good thing and certainly mitigates a lot of risks, even if the underlying system has a backdoor. Removing Windows would mean reinforcing purity hierarchy and general "holier than thou" attitude.

Just to reiterate: most people reading this have Intel ME or AMD PSP on their CPU, and wireless connectivity chips with nonfree firmware (either on ROM or loaded by the kernel). Those all can be backdoored too, and Intel ME / AMD PSP are in particular the definition of a backdoor. While very problematic and worth fighting against, it would be ridiculous of us to require all visitors to buy a Librebooted ThinkPad X200, or otherwise be denied any recommendations.

Windows section already comes with a disclaimer that communicates our concerns about Windows as a platform (as agreed in this thread):

> Warning: Microsoft Windows is affected by PRISM. Even using the software tools we recommend here, your privacy may be compromised by Windows. The operating system of any device can unfortunately lever out any privacy protection that a program tries to offer you. The latter has to run in the confines of the OS after all. We strongly recommend replacing Windows with either Linux or BSD.

**Comment by yegortimoshenko** [comment]
This is also the consensus in this thread, so closing.
