### ISSUE TITLE
warn about keepass?

### ISSUE THREAD

**Issue by ThomasWaldmann** [nylira/prism-break#1036]
http://sourceforge.net/p/keepass/discussion/329220/thread/02383c83/

there could be a warning below the password manager section pointing out that while keepass advertises itself as open-source, there is no transparent development using a public code repository.

as this is pretty much the good and usual development practice for most open source projects, it is somehow strange that this is not done for keepass, especially since the project is security critical and depends on people trusting it (for good reasons).

note: I mean keepass, not keepassX (they are often confused, which makes this even more problematic)

**Comment by ThomasWaldmann** [comment]
Why is an issue called "warn about keypass" closed via a commit adding keypassX (which is a different software and HAS a repo, so this issue does not apply to it).

**Comment by vyp** [comment]
@ThomasWaldmann true but if you look at the commit message it links to Zegnat's comments as reasons. The logic is roughly:

- Zegnat said he would only add one if KeePass or KeePassX. The commit was adding KeePassX.
- This means now KeePass will not be added.
- And because of Zegnat's comment here, I felt that this issue could be closed.

You're right though that it's not 100% related, but when I was searching for relevant issues, I saw this and thought it would be *convenient* to also close this.

**Comment by vyp** [comment]
Also I agree with @hasufell, I don't believe this is really an issue or that it needs any note on the site either way.
