### ISSUE TITLE
Remove Lorea

### ISSUE THREAD

**Issue by Zegnat** [nylira/prism-break#1070]
The Lorea website is down and I can’t find any information about it elsewhere. Has it been discontinued?

(I am still in the process of settling in at home after my vacation, so pulls and updates are slowed down. A lot. Sorry.)

**Comment by vyp** [comment]
@Lorea

**Comment by vyp** [comment]
@Zegnat I get an untrusted connection to their website https://lorea.org/, what about you? Could it be that they only simply forgot to update their SSL certificate? Otherwise I found this page http://p2pfoundation.net/Lorea, which was last updated in 2012, but it is just a wiki and probably not official.

cc @caedesvvv (if you know anything about the status of Lorea).

**Comment by vyp** [comment]
Or should it be replaced with https://n-1.cc/?

**Comment by Zegnat** [comment]
It expired August 27. So if they forgot to reissue a free SSL cert for over a year, that is just negligence. I have never heard of https://n-1.cc/ . I am leaning more towards just removing it from PRISM Break than replacing it or trying to update it with possibly also outdated information.

**Comment by vyp** [comment]
As in apparently n-1 is a "seed" of lorea, the platform? According to #19.
