### ISSUE TITLE
Note that Thunderbird may leak email server's domain name to Mozilla

### ISSUE THREAD

**Issue by blurmonk** [nylira/prism-break#1092]
TB is considered safe or accepted to be that way. However that is not so much the case. For example when you add an email, the email address is sent back to Mozilla to get checked to get the settings for that email address and the server. While this sounds useful and benign, there is the otherside which is that Mozilla will know about all the email addresses you add to TB. And we do not know what Mozilla Corp does with that stash of data.  This feature was added later, I cant remember the version but it was not the case in the beginning. I realize it is helpful to users but they make it so that you cannot do this manually. It offers manual way to add email addresses but it is a bit convoluted. 

And the telemetry, pinging home etc are other TB features like its big brother FF has.

**Comment by JKAbrams** [comment]
While I use Thunderbird as my main email client and it does everything I need from an email client (although searching is a bit wired) this issue and others like it are really annoying. I use email from a domain that only I have mail on, so for me there is no distinction between sending the domain or sending the first part of the address. My personal view is that security (*security including privacy, that is*) should be by default as a general principle.
Perhaps this issue is not enough to remove Thunderbird (however if someone makes version of Thunderbird that has security by default, we should recommend that one instead).

**Here is my suggestion for these kind of nagging things that are annoying but:**
* **Add a antifeatures -list**. Adding a section with antifeatures on the application page, and if possible, as in this case, add workarounds for how to fix them. F-Droid has this kind of list for its applications and it is really good . Antifeatures that can be worked around can be orange while those without fixes available could be red.

For example, Firefox in fdroid is listed with these antifeatures (we could be a bit more explicit):
\* *This app promotes non-free add-ons.*
\* *This app tracks and reports your activity.*

**Comment by wifiextender** [comment]
No matter how hard you would customize it's settings and the addons, every new release will reset them.

http://wifiextender.github.io/post/thunderbird_strip_email_headers/

**Comment by hasufell** [comment]
> Since then mutt became my primary email client.

But this isn't a sane alternative for the masses (even those that are technically acute). Claws-mail just segfaults with huge mail databases and geary is still very new (and has a very specific focus).

**Comment by wifiextender** [comment]
Hello Julia,

There are plenty email clients, gui and/or non-gui: https://wiki.archlinux.org/index.php/List_of_Applications#Email_clients

**Comment by hasufell** [comment]
> There are plenty email clients, gui and/or non-gui:

they all suck.

**Comment by aleksandar-todorovic** [comment]
> they all suck.

I agree. Most of them are practically useless. And I have tried using plenty of them before I ended up returning to my good old Thunderbird.

Thunderbird is the best we got. We need to keep Thunderbird on the list. So lets just put a warning in the Security Notes and move on.

**Comment by wifiextender** [comment]
There are alternatives then there is a choice.

Use what suits you, once you let your guard down - you are down.

**Comment by hasufell** [comment]
> There are alternatives then there is a choice.
> 
> Use what suits you, once you let your guard down - you are down.

The issue brought up here is extremely minor and there are several ways to fix/work around it. A note is enough. Don't exaggerate. Prism-break has far more fundamental problems like not communicating properly that Windows and Mac are _always_ unsafe to use, no matter what security programs you use on top of them.

**Comment by aleksandar-todorovic** [comment]
Turns out that Mozilla knows the [number of users](https://blog.mozilla.org/thunderbird/2015/02/thunderbird-usage-continues-to-grow/) using Thunderbird and their country thanks to the Active Daily Installations (ADI). We might also put this into the Security Notes.

**Comment by yegortimoshenko** [comment]
See https://github.com/nylira/prism-break/issues/1092#issuecomment-50987849, we need to add a note about this. (Removing the only usable email client for something so minor is not an option.)
