### ISSUE TITLE
Request : add open source alternatives to Adobe Flash player

### ISSUE THREAD

**Issue by geplus** [nylira/prism-break#1095]
Hi everybody,
as you may know, Adobe flash plugin is still necessary for our web surfing in most cases, but it's pretty dangerous for our privacy.
There are some open-source alternatives:
- Gnash : is the most famous, an high priority project by Free Software Foundation http://gnashdev.org/
- Lightspark: another open source flash player replacement
  https://lightspark.github.io/
- Mozilla Shumway: Mozilla's html5 flash replacement plugin
  https://github.com/mozilla/shumway

Please note: this plugins are not as stable and full working as  Adobe flash plugin, despite this they are the only privacy-friendly alternatives to Adobe flash. Also, Libre GNU/Linux distros, as Parabola GNU/Linux, offers only open-source flash plugins in their repos

**Comment by vyp** [comment]
Adobe [EOL'd](https://blogs.adobe.com/conversations/2017/07/adobe-flash-update.html) Flash so this issue has become moot in my opinion.

**Comment by strugee** [comment]
@vyp it won't be gone until 2020 though, so maybe there's still value here?

I don't feel strongly enough to reopen or anything, though.

**Comment by vyp** [comment]
@strugee I felt that because of it there's most likely not going to be any new developments for alternative Flash players, but you're probably right anyway to keep this open for now. :sweat_smile:

**Comment by strugee** [comment]
@vyp looking at this again I think you may be right. Probably there won't be any new development on alternative players and AFAIK (could be wrong) the only one that supports reasonably modern Flash content is Shumway? So I don't think there's much value in keeping this open

**Comment by vyp** [comment]
@strugee Well shumway was discontinued a while ago, and it seems like gnash is well and truly dead (last release 2012). The only one that looks to be actively developed is lightspark. But this is definitely a dying area though, and I think that native browser plugins should really be a thing of the past, considering the security implications, so I'm quite hesitant with suggesting lightspark. So yeah we can close this in my opinion.

Flash is definitely still used on the web today, but I believe it's much much less used today than it was even just only 3 years ago when this issue was opened. If anyone wants to convince me otherwise, they're welcome to, but as we get closer to 2020, the case for a flash replacement being listed on prism break strongly gets weaker in my opinion. And I think instead of trying to make a case for a flash replacement, you should consider your need to use flash and see if you can replace it or use alternative options, simply because using flash is not sustainable or future proof anymore. And so eventually you're going to have to figure out how to live without flash anyway. :woman_shrugging:
