### ISSUE TITLE
LocalBox

### ISSUE THREAD

**Issue by helgafirer** [nylira/prism-break#1104]
Two new open source alternatives to commercial and proprietary file hosting / syncing:
1. Syncthing (http://syncthing.net/)
2. LocalBox (http://www.libbit.eu/en/producten-en/localbox)

**Comment by yegortimoshenko** [comment]
LocalBox has moved over to http://www.yourlocalbox.org/, source code is at https://github.com/yourlocalbox?tab=repositories. This is not a community project or effort, but driven by a company, nothing has not been updated since 1 March 2017. Syncthing is so much better that this seems pretty safe to close.

**Comment by strugee** [comment]
https://prism-break.org/en/all/#file-storage-sync is also somewhat overloaded already.
