### ISSUE TITLE
Browser recommendation: Lightning Browser

### ISSUE THREAD

**Issue by smlb** [nylira/prism-break#1116]
Lightning Browser is a FOSS browser avaible for Android:
- [Github Source Code](https://github.com/anthonycr/Lightning-Browser)
- [F-Droid Link - Alpha Version](https://f-droid.org/repository/browse/?fdfilter=lightning&fdid=acr.browser.lightning) (Mozilla Public License 2)
- [F-Droid Link - Stable Version](https://f-droid.org/repository/browse/?fdfilter=lightning&fdid=acr.browser.barebones) (Apache2 License)

Supports AdBlocking.

**Comment by yegortimoshenko** [comment]
Any particular reason to recommend it over Fennec (Firefox)?

> Lightning also works with Tor directly. So it is a good choice.

It's not enough to just send traffic through Tor, one should also be using some build of Tor Browser, otherwise traffic will be standing out and various deanonymizing attacks will be available (canvas fingerprinting, WebRTC, `<video>` tag, battery API, ...).
