### ISSUE TITLE
Adding AdAway

### ISSUE THREAD

**Issue by smlb** [nylira/prism-break#1117]
It's a FOSS app for AdBlocking that uses the well known /etc/hosts for adblocking.
- [F-Droid Link](https://f-droid.org/repository/browse/?fdfilter=adaway&fdid=org.adaway) (GPLv3)

AdAway uses downloaded (and added) lists of malicious sites.

**Comment by yegortimoshenko** [comment]
Should we recommend rooting phone? I don't think so.

Also, Fennec can be used with uBlock Origin, which blocks ads much more thoroughly than AdAway. The latter only makes sense if you want to use a non-recommended browser (AOSP Browser leaks device model in User-Agent, Chromium does that plus sends a lot of data to Google).

**Comment by beerisgood** [comment]
A alternative without Root is: DNS66 from F-Droid

**Comment by gerroon** [comment]
@ yegortimoshenko 

Actually rooting is a way to gain control of your phone otherwise Google is the sole administrator of your device on Android.

**Comment by yegortimoshenko** [comment]
> Actually rooting is a way to gain control of your phone otherwise Google is the sole administrator of your device on Android.

All you do by running apps as root is make sure that any vulnerability in that app can be used to gain total access over your phone, instead of being constrained to a sandbox. No SELinux policy would help with root access.

And you're free (and recommended) to install Android distribution that does not include Google's proprietary Play Services, such as LineageOS or Replicant. Just make sure to not flash GApps.

> Adaway makes it possible to block in app adds which also helps with personal information leaks.

You should not run apps that contain ads, whether with AdAway or without it. Host file based blacklist is much less flexible than e.g. AdBlock Plus compatible blacklists used in uBlock Origin, and probably fail to block many ad-related requests.

**Comment by yegortimoshenko** [comment]
@beerisgood: good find! And really clever use of Android VPN API, too. I have no problems with it getting listed, but perhaps it deserves a separate issue :-)

**Comment by Hillside502** [comment]
Beware of **fake**  DNS66 at:-
https://play.google.com/store/apps/details?id=com.junta.dns66.dnschanger

**Comment by strugee** [comment]
I'd like to close this since rooting is... unideal and this solution will be incomplete at best, as @yegortimoshenko pointed out. Someone can file a separate issue for DNS66; let's keep this issue on-topic please.
