### ISSUE TITLE
prism-break friendly pdf-reader

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1155]
Hi guys.

I'm looking for a prism-break firendly pdf-reader. As far as I can judge the situation, there is no recommended one. Any ideas? 

Links to discussions about this topic are very welcome. I've used my favorite search engine first. 

Thanks and have a nice weekend,

ge0ffreys.

**Comment by nodiscc** [comment]
I would also like a FOSS PDF reader in the list, at least for Windows. Adobe Reader has been a [common attack vector](http://www.cvedetails.com/product/15364/Adobe-Reader.html?vendor_id=53) in the past.

**Comment by alerque** [comment]
@nodiscc Attack vector for digital surveillance? Or for malware intrusion? Because PRISM-Break doesn't really keep track of what software is safer that others for the latter issue. Case in point: we don't list alternatives to Microsoft Word in spite of said behemoth having a long record of being swiss cheese and exploited on a regular basis. As far as PRISM-Break is concerned the active recommendation is to not let such programs talk to the network in any way, shape or form. In that case they become immune to the PRISM dragnet and therefore non concerns here.

If we get into recommending software on a basis of its impact on system integrity or ability to handle foreign data safely I wonder if we aren't opening up a bigger can of worms that we can reasonably handle.

**Comment by nodiscc** [comment]
Vector for malware.

>  Because PRISM-Break doesn't really keep track of what software is safer that others for the latter issue

I thought it did? @Zegnat is this project concerned with recommending reasonably secure FOSS alternatives to proprietary solutions?

**Comment by alerque** [comment]
@nodiscc The trouble I see is with you usage of the bare term "secure" with no context. There is more than one aspect to something being secure or not, and PRISM-Break is primarily focused on one piece of the puzzle. The project byline is "Privacy-aware recommendations to proprietary software.” Of course privacy-aware is all about security, but it's a different kind of security than the issue of malware resistance. Of course privacy breaches are often a secondary result of malware infestation, but that's a secondary concern rather than a primary one.

I would say that while we do want to avoid recommending software that has known security flaws of that sort, the _primary_ aspect that is being recommended is the suitability for use in an Internet environment without compromising privacy. Recommendations that are neither here nor there from a PRISM dragnet standpoint (and of course any other surveillance cousins it has still out there waiting for names) but are based on other security concerns would be better served by a venue that actually analyzed those aspects.

**Comment by nodiscc** [comment]
@alerque ok, I get your point. Recommending malware-resistant applications would probably be a huge undertaking, and outside the scope of PRISM Break. 

> There is more than one aspect to something being secure or not, and PRISM-Break is primarily focused on one piece of the puzzle.

It could be argued that a surveillance actor sitting on a code execution/data disclosure vulnerability on a very widespread piece of software (moreover, closed source) such as Reader would be in a great position to collect even more data. I understand the difference between "insecure" and "backdoored" though. After enough vulnerabilities have been found, effects would be the same though (except vulnerabilities expose the user to more than just the backdoor "owner")
