### ISSUE TITLE
Add audited tag to cryptocat

### ISSUE THREAD

**Issue by mpmks11** [nylira/prism-break#1163]
Cryptocat has been audited twice, so shouldn't we add the audited tag?

Audit 1: https://leastauthority.com/static/publications/LeastAuthority-Cryptocat-audit-report.pdf
Audit 2: https://isecpartners.github.io/publications/iSEC_Cryptocat_iOS.pdf

**Comment by hasufell** [comment]
> Both audits find significant problems

I'm looking at the first one now and it seems upstream is VERY active and trying to fix these things (some references are even in the paper, like when cryptocat disabled file transfers completely in 2.1.16).
* [Issue A. Disclosure of File Contents Due to Re-use Of Key and IV](https://github.com/cryptocat/cryptocat/issues/575) seems to be fixed
* [Issue B. Integrity Key and IV Reuse in File Transfer](https://github.com/cryptocat/cryptocat/issues/576) seems to be fixed
* [Issue C. Substitution of File Contents By Hijacking Entry in User Interface](https://github.com/cryptocat/cryptocat/issues/577) seems to be fixed
* [Issue D. File Name, Mimetype, and Size Lack Confidentiality](https://github.com/cryptocat/cryptocat/issues/578) closed as wontfix
* [Issue E. You Log Out, Attacker Logs in with the same Nickname, Your Friend Thinks The Attacker is You](https://github.com/cryptocat/cryptocat/issues/606) seems to be fixed
* [Issue F. Nicknames Can Be Invisibly Reassigned](https://github.com/cryptocat/cryptocat/issues/607) seems to be fixed
*[Issue G. Capture of Sent Messages by Nickname Change](https://github.com/cryptocat/cryptocat/issues/608) seems to be fixed

And the issue tracker has a clear history of security related issues: https://github.com/cryptocat/cryptocat/labels/security

**Comment by hasufell** [comment]
https://github.com/cryptocat/cryptocat/issues/701

**Comment by hasufell** [comment]
https://blog.crypto.cat/?s=isec

**Comment by Zegnat** [comment]
:+1: I think we can add an ‘audited’ tag without to many problems. Definitely no reason to remove cryptocat from the list again. Accepting pull requests, else I will do it tonight.

**Comment by yegortimoshenko** [comment]
I wonder if that's a good idea. "Audited" reads as an approval, and in this case audit results were mediocre at best. Maybe we should reconsider how this label is used.

**Comment by alerque** [comment]
I agree with @yegortimoshenko the usage of this tag needs to change across the board. I added issue #2026 to track this.
