### ISSUE TITLE
PGP and Smardcards

### ISSUE THREAD

**Issue by sedrubal** [nylira/prism-break#1164]
Hi,

I heard, it's good to use smardcards for pgp in order to improve security. Does prism break want to suggest them, too?
And does anyone know, where you can buy smardcards and reader?

**Comment by jneureuther** [comment]
Any other opinions on this topic?
Personally I think we would have to trust closed source hard-/software, if we use smart cards.
Are smart cards really a benefit in terms of security?

**Comment by lucaspetter** [comment]
The advantage is that keys never leave the smart card, so there's less concern about keys getting stolen. [This page](https://security.stackexchange.com/questions/38924/how-does-storing-gpg-ssh-private-keys-on-smart-cards-compare-to-plain-usb-drives) has some explanations about why smart cards may be safer than storing keys on a regular hard drive.

The [Debian wiki](https://wiki.debian.org/Smartcards) has info about smart cards, readers, and where to buy them. You can also get a card by donating to the [Free Software Foundation Europe](https://fsfe.org/fellowship/card.en.html).

It's good to use a smart card if you know how or if you might be targeted. But for thwarting mass, *untargeted* surveillance, they're unnecessary; regular keys on your hard drive are enough. For most people, it's already too hard to set up PGP, adding smart cards would just be another complicated barrier-to-entry and an expense.

**Comment by sedrubal** [comment]
but I think most smartcards and -devices are closed source, as jneureuther mentioned...

**Comment by lucaspetter** [comment]
The [Debian wiki](https://wiki.debian.org/Smartcards) addresses the issue of closed-source/nonfree smart cards:
> Smartcards have their own internal software and operating systems. This software is rarely free software within the principles of the Debian Free Software Guidelines - however, the software on the Debian system is completely free. By definition, a smartcard is a secure device and the software can not be changed at will. Some vendors provide binary (closed source) drivers for Linux, but it is not always necessary to use these drivers. In the best cases, it is possible to build working solutions without using any non-free or binary artifacts from the vendor, except for those in the card itself.

So yes, smart cards do run internal closed-source/nonfree software, but this isn't an issue because that software can't be easily changed and it doesn't connect to the Internet. Smart cards are designed to not let keys be read, but you can write new keys to them. The hardware isn't open/free, but that goes for nearly all hardware. Also, you don't always need to install closed-source/nonfree drivers on your computer, there are free/open alternatives.

If you don't trust smart cards to store your PGP keys, then why do you trust your hard drive to do this? Hard drives run closed-source/nonfree firmware too. Their firmware is known to be vulnerable to [persistent spyware](https://www.wired.com/2015/02/nsa-firmware-hacking/). If anything, smart cards provide greater security than hard drives.

The Debian developers are just as concerned about the openness/freedom of hardware and software, yet they recommend and support smart cards; if the Debian developers didn't trust smart cards, they wouldn't be recommending or supporting them. Similarly, if the Free Software Foundation Europe didn't trust smart cards, it wouldn't be spending money to [give them to all of its members](https://fsfe.org/fellowship/card.en.html).

To be clear, though, in my last post I was saying you probably shouldn't go recommending smart cards for *everyone*. There are people who actually need the key security that smart cards provide, and who are capable of using or learning to use them; for these people, smart cards are a good thing. Then there are people who can follow an easy guide like [Email Self-Defense](https://emailselfdefense.fsf.org/en/) to set up PGP, but who have no idea how to use the command line at all; for those people smart cards make PGP even more complicated than it already is.

**Comment by alerque** [comment]
@sedrubal what @lucaspetter explained is spot on. Yes its true that smart cards have proprietary bits on them, but then so does your hard drive, so does your motherboard and so do your USB sticks.    And you entrust your super sensitive content to them all the time.

Smart cards are a step up from the things you currently trust. The software you use to read and write to them can be completely open source and you get some physical protections of one way hardware gates as well as physical control over the container. The ability of malicious actors, especially malware on your computer to compromise your private keys is vastly reduced.

As far as PRISM-Break goes the fact that all the software on your machine is OS and no internet access is possibly involved should put their use squarely in the realm of recommendable especially for those situations where their use mitigates against other problems.

**Comment by sedrubal** [comment]
@lucaspetter and @alerque: Thank you. That's it, I wanted to know ;)

**Comment by lucaspetter** [comment]
For posting to Prism-Break, it could say something like this in the notes under the Email Encryption section:

> For advanced PGP users, [OpenPGP smart cards](https://wiki.debian.org/Smartcards) provide higher security for storing your private keys than regular hard drives. You can get one by donating to the [Free Software Foundation Europe](https://fsfe.org/fellowship/card.en.html).

**Comment by sedrubal** [comment]
:+1:

**Comment by yegortimoshenko** [comment]
GPG tokens are more sensitive than hard drives, because they expose a much higher-level API which is much more prone to backdoors. For example, while operating system may ensure that nothing non-encrypted ever touches the hard drive, there is no way to ensure that with a GPG token.

One is block storage, another exposes "sign/verify" and "encrypt/decrypt", and is supposed to safeguard the private key so that there is no way to extract it from the token.

It would be safe to presume that Yubikeys have a backdoor that allows full private key recovery, because proprietary firmware in this context means there is no realistic way to check that that's not the case.

There also may be vulnerabilities in such hardware: for example, YubiKey 4 was susceptible to [ROCA](https://keychest.net/roca) that allows to recover private key from the public key. Proprietary firmware makes identifying such issues harder.

**Comment by strugee** [comment]
Regardless of whether we think smart cards are secure or not, I don't think we should be recommending them based on UX concerns. As I have argued elsewhere, PGP is hard enough for most people. Anyone who really needs the security that smart cards provide - and has the expertise to properly use them - probably already knows about them.

**Comment by yegortimoshenko** [comment]
@strugee Funny to hear that while I'm busy reflashing firmware on a token via an external debugger :-) I totally concur.

**Comment by yegortimoshenko** [comment]
This is only about GPG tokens. Tokens that you mention usually implement U2F or TOTP, and are used for two-factor authentication. As far as I know, there has been no discussion about that yet!
