### ISSUE TITLE
DuckDuckGo and other centralised search engines and services are not free

### ISSUE THREAD

**Issue by KOLANICH** [nylira/prism-break#1168]
I suggest to move them to proprietary, and put [YaCy](http://yacy.net/en/index.html) to free.

**Comment by hasufell** [comment]
Unfortunately YaCy needs java and the way Oracle handles security issues has been critizied numerous times:
https://en.wikipedia.org/wiki/Java_security
https://en.wikipedia.org/wiki/Criticism_of_Java#Security
http://www.theregister.co.uk/2012/08/30/oracle_knew_about_flaws/

The severity of those exploits is pretty interesting... affecting facebook, twitter and whatnot.

**Comment by nodiscc** [comment]
[Searx](https://github.com/nylira/prism-break/issues/1102) is a good self-hostable search engine.

When it comes to using a search engine hosted by a third-party (it being open-source or not), you can only choose whether to trust the website owner/privacy policy. I'd prefer having startpage.com replace duckduckgo because they also claim to not track users, and are EU-based so they can not be [NSL](https://en.wikipedia.org/wiki/National_security_letter)'ed.

A public searx instance would be good to recommend, but again you should have trust in the website owners, and also hope their server holds the load.

**Comment by pickfire** [comment]
On 03/01/2015 02:51, Julian Ospald wrote:
> Unfortunately YaCy needs java and the way Oracle handles security
> issues has been critizied numerous times:
>  https://en.wikipedia.org/wiki/Java_security [1]
>  https://en.wikipedia.org/wiki/Criticism_of_Java#Security [2]
>  http://www.theregister.co.uk/2012/08/30/oracle_knew_about_flaws/ [3]
> 
> The severity of those exploits is pretty interesting... affecting
> facebook, twitter and whatnot.
> 
> --
> Reply to this email directly or view it on GitHub [4].
> 
> 	*
> 
> Links:
> ------
> [1] https://en.wikipedia.org/wiki/Java_security
> [2] https://en.wikipedia.org/wiki/Criticism_of_Java#Security
> [3] http://www.theregister.co.uk/2012/08/30/oracle_knew_about_flaws/
> [4] 
> https://github.com/nylira/prism-break/issues/1168#issuecomment-68551123
Weather if [duckduckgo](https://ddg.gg/) depends on your trust on them.

**Comment by strugee** [comment]
> Weather if [duckduckgo](https://ddg.gg/) depends on your trust on them.

What?

**Comment by GreenLunar** [comment]
>> Weather if [duckduckgo](https://ddg.gg/) depends on your trust on them.

> What?

Maybe @pickfire meant that we do not know what DDG does with data receives by users. See http://www.gnu.org/philosophy/who-does-that-server-really-serve.html

This also concerns to Tor nodes and any other server. See http://security.stackexchange.com/questions/79438/can-a-malicious-tor-exit-node-perform-a-https-man-in-the-middle-attack-to-see-mo and https://trac.torproject.org/projects/tor/ticket/8657

**Comment by yegortimoshenko** [comment]
Searx is fully free: #1123 

PRISM Break clearly conflates freedom and privacy here, even in that, we cannot trust centralized search engines like DDG or StartPage that they don't collect user data. With Searx, trust can be decentralized and placed on admin of each instance.

I think it's outright dangerous that DuckDuckGo and similar services are placed in "free" category, because they are not, they are just as proprietary as Google. One cannot make a copy, change it and run on their server. This is crucially important.

I suggest that #1123 is merged, and all other recommendations from web search category are removed, except perhaps YaCy (see #1877; not useful search results).
