### ISSUE TITLE
[new category] Backup Software: scheduled/automatic, remote/network

### ISSUE THREAD

**Issue by bobodod** [nylira/prism-break#1179]
In alphabetical order:
- Amanda
  - Linux, Mac OS X (from sources), Unix, and Windows
  - both [community](http://www.amanda.org/) and [commercial](http://www.baculasystems.com/) editions
    - [edition comparison](http://www.zmanda.com/Amanda-Enterprise-Amanda-Community-comparison.html)
- BackupPC
  - Linux and Windows
  - [community edition](http://backuppc.sourceforge.net/)
- Bacula
  - Linux, Mac OS X, Unix, and Windows
  - both [community](http://bacula.org/) and [commercial](http://www.baculasystems.com/) editions
    - commercial edition is closed source ([PDF of license](http://www.baculasystems.com/agreements/LICENSE.pdf))
    - some sourceless, but worrying [criticisms](http://www.bareos.org/en/faq/items/why_fork.html) of Bacula's new business model
  - forks
    - [Bareos](http://www.bareos.org/)
    - [BURP](http://burp.grke.org/)
- LBackup
  - Linux and Mac OS X
  - [community edition](http://www.lbackup.org/about)
- UrBackup
  - Android, Linux, Unix, and Windows
  - [community edition](http://www.urbackup.org/)

A [comparison of client/server backup software](http://wiki.bacula.org/doku.php?id=comparisons) from the Bacula wiki.

(This is not an exhaustive list and doesn't contain closed source software such as the [highly reviewed](http://thewirecutter.com/reviews/best-online-backup-service/) CrashPlan.)

**Comment by ThomasWaldmann** [comment]
While I am not sure all that software in the original post should be on prism-break (it's not a directory of all FOSS software), https://attic-backup.org/ really deserves a place on prism-break.

You can do backups to your own media or server (via ssh), *everything* is chunk-wise deduplicated, compressed, AES encrypted and HMACed on the client. The deduplication algorithm is way better than others (like rsync or obnam).

Since I found it 2w ago, I worked quite a lot with the code, including the crypto/authentication parts and all looked really well-done and clean.

**Comment by bobodod** [comment]
Looks like it's almost entirely cross-platform, too: https://github.com/jborg/attic/pull/68

**Comment by ThomasWaldmann** [comment]
Be careful, Windows stuff is not merged into main repo.
But for all POSIX platforms, I guess it should work rather OK.

**Comment by yegortimoshenko** [comment]
attic has not been updated since 2015, BackupPC has not been updated since early 2017 and is open core, Amanda is open core and we already better alternatives, Bacula is not very active and open core, LBackup has not been updated since 2016 and is open core, UrBackup is open core.

Please open one issue per project, and only recommend software that you personally would use.
