### ISSUE TITLE
New Category [Diary/Jornal]

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1180]
would be nice, some Diarys, like Rednotebook for example

**Comment by aleksandar-todorovic** [comment]
@Zegnat There are plenty of them that comes to my mind. Evernote, Google Keep and OneNote are probably the most popular out there. Every single one of them is (of course) proprietary.

**Comment by Zegnat** [comment]
Why wouldn’t you use OneNote? I have never seen my Microsoft Office Suite leak information over a network. I guess I was thinking more about software that is actually being catered as a diary, like [Day One](http://dayoneapp.com) versus the command-line [jrnl](https://maebert.github.io/jrnl/) that can act as an open-source Day One replacement. But again, Day One isn’t actually leaking any data.

PRISM Break is not a tool to help people find open-source alternatives for everything, there are other projects and wikis that try to be that. We are mostly focused on applications that are used for communication and tools that third parties can use to track the user.

It feels wrong to me to add a new category for journals because some applications like Evernote might be used to keep an online journal.

**Comment by vyp** [comment]
I think @aleksandar-todorovic may have meant the fact that all your notes and data are synced on their servers, especially considering that we already suggest not to use onedrive and google drive.

**Comment by Zegnat** [comment]
Yes, but this issue is about adding a category for diary and journal keeping software. Of course you could use any word processor for this, but should we have a category that just copies the contents of the productivity category then? And if you look at software that is especially built for diaries and journals, what proprietary software would you find that leaks data?

Those are the central questions. Does Evernote by itself creates a need for a journal section?

**Comment by aleksandar-todorovic** [comment]
I'm not using OneNote. The interface is just too complicated for me and I'm just using a simple text processor that supports Markdown. However, I do own OneNote as a part of my Office 365 license, and if I remember correctly, it syncs the data automatically to my OneDrive account without asking me to do so.

I don't think that we actually need a new category, I was just implying that the most popular note taking software (or whatever you want to call it) is proprietary.

In my opinion, if the user chooses to use those programs, he is probably aware that his diary/journal/notes will not remain private in any single way.
