### ISSUE TITLE
[browser addon] SmartReferer

### ISSUE THREAD

**Issue by nodiscc** [nylira/prism-break#1185]
Hi @nylira, this is a followup to a [discussion on RequestPolicy Continued](https://github.com/RequestPolicyContinued/requestpolicy/issues/396) (on which there is still work to do before it can be added to PRISM Break's list, see https://github.com/nylira/prism-break/issues/1153).

I'd like to see [SmartReferer](https://addons.mozilla.org/en-US/firefox/addon/smart-referer/) added to the browser addons list. It's a very simple addon that prevents sending _real_ HTTP referers, while minimizing breakage on websites (see the RP discussion). It requires no configuration.

Do you think it can be added?

**Comment by nodiscc** [comment]
@Zegnat @nylira @vyp @hasufell @strugee @alerque Friendly ping. Feedback welcome.

**Comment by Zegnat** [comment]
Much like Random Agent Spoofer (#1197) and Secret Agent (#965) I just can’t seem to get over my initial feeling that it doesn’t _really_ do anything other than giving you a false idea of gaining anonymity. I would love to change my opinion, but I still haven’t read anything that made me change my mind :disappointed:

**Comment by nodiscc** [comment]
I didn't imply this addon provided added anonymity; rather it prevents your browser from leaking the URL you are coming from to the target site of a link. Am I right?

**Comment by vyp** [comment]
Haven't used it, so I don't think I have any right to give a comment here on the addon. However, I agree with @nodiscc in that this is not about "attack vectors" per se but websites storing that information as an invasion of privacy ("which *is* more personal than my search keywords"), &rarr; building profiles etc.

But at the same time, I honestly don't think changing the referer has that great of an effect in the grand scheme of things (prove me wrong I guess), and we must be careful to make sure the prism break list (in each section) doesn't grow too much, because otherwise it just serves as extra confusion (which ones to use??) for our target audience.

If prism break still had that functionality to show "extras" or "more advanced options", I would say referer spoofing might have a place there though, explaining what exactly it does of course (like what referer means, and why this might be useful, since smart referer itself doesn't do that).

**Comment by mastercoms** [comment]
There are hidden config options in firefox for referrer control.
network.http.referer.XOriginPolicy: 0=always send, 1=send if base domains match, 2=send if hosts match
network.http.referer.spoofSource: false=real referer, true=spoof referer (use target URI as referer)
network.http.referer.trimmingPolicy: 0=send full URI, 1=scheme+host+port+path, 2=scheme+host+port

**Comment by nodiscc** [comment]
@mastercoms Yes these options spoof the referer in ways that break certain sites. SmartReferer has the advantage of not breaking _any_ sites when you set it to `Send the URL I'm going to as a referer`. 

Referers are still working as intended when staying on the same domain (which some sites rely on to work properly - `network.http.referer.spoofSource` does _not_ implement that), but the addon prevents leaking URIs when following cross-domain links (which `network.http.referer.spoofSource` also achieves)
