### ISSUE TITLE
Alpine Linux

### ISSUE THREAD

**Issue by Hardwiredorwell** [nylira/prism-break#1189]
Hello! 

What about adding http://alpinelinux.org/  to Operating systems?

**Comment by hasufell** [comment]
How are security vulnerabilities communicated to the user (as in: which versions are affected, how to fix, additional configuration changes? etc)?
Are there any tools to automatically check the vulnerability status of your system?

http://lists.alpinelinux.org/alpine-security/
http://forum.alpinelinux.org/forums/common-vulnerabilities-and-exposures

Maybe I didn't look hard enough, but the above links look pretty thin.

**Comment by ncopa** [comment]
There is a category dedicated security [issues](http://bugs.alpinelinux.org/projects/alpine/issues?utf8=✓&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=*&f%5B%5D=category_id&op%5Bcategory_id%5D=%3D&v%5Bcategory_id%5D%5B%5D=21&f%5B%5D=&c%5B%5D=project&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=updated_on&group_by=)

**Comment by ncopa** [comment]
>Popular distros sometimes have security flaws that go unnoticed. I'm betting this is even more the case for small projects. I'd definitely like to see a review and audit for Alpine Linux.

I suppose that goes both ways. It happens that alpine linux fixes security [issues](https://github.com/FreeRADIUS/freeradius-server/issues/767#issuecomment-54126778) that goes unnoticed for most other distros.

**Comment by nodiscc** [comment]
> It happens that alpine linux fixes security issues that goes unnoticed for most other distros.

@ncopa about that particular bug (https://github.com/FreeRADIUS/freeradius-server/issues/767#issuecomment-54126778), I see it's fixed in the freeradius source, so distros that maintain their packages will pick up the fix. In which distro/package version is this not fixed? Or is there another example?

**Comment by ncopa** [comment]
@nodiscc they didn't fix it in the 2.x.x stable tree so all distros using freeradius-2 (which is the current stable branch) should be vulnerable. That would mean all ubuntu versions (unless they have manually patched it but i doubt since there never was any CVE)

The exact issue:
https://github.com/FreeRADIUS/freeradius-server/blob/v2.x.x/src/modules/rlm_unix/rlm_unix.c#L96

getgrnam() and getpwnam() are non-threadsafe but they run in a thread and in certain configurations i will make your server crash.

This does not mean there are many of this kind, of course. Nor does it mean that Alpine is "well tested". I do believe that Alpine Linux provides a higher security standard than what is common though.

**Comment by ncopa** [comment]
> Nor does it mean that Alpine is "well tested"

On second thought, it actually could mean that Alpine is pretty "well tested" even if user base is relatively small.

Might also be worth to mention that Alpine fits pretty well on this system hardening recommendation:
https://stribika.github.io/2015/01/04/secure-secure-shell.html#system-hardening

**Comment by hasufell** [comment]
> I do believe that Alpine Linux provides a higher security standard than what is common though.

I don't think a single bug (and upstream says that's a configuration issue in the first place and documented as such) that you did not communicate to other major distros (why?) is a strong argument.

Things that matter for practical linux distribution security:
* user base (yes, definitely)
* developer base (couldn't find any information)
* dedicated security team (couldn't find any information)
* response time (didn't examine the security bug tracker yet)
* communication channels about security issues (including automated cli-tools which some major distros have)
* supporting software recommended on prism-break
* supporting advanced technologies like hardening
* being a source distro (or at least provide the possibility)
* the way the kernel is handled/updated (does it contain random downstream patches? Release cycle?)

And... there are already distros on the list that meet this criteria pretty well. So the question is what does Alpine Linux offer in addition, that others do not have (technology? Something revolutionary stuff like NixOS?).

**Comment by ncopa** [comment]
> (why?)

I reported it upstream, I spent time on providing a fix, based on their wishes. They rewrote their own patch (NIH syndrome?) with bugs. I reported the new bugs they introduced with suggestions to fix it.

I dont have time and energy to start discussion with distros that i don't even use. why should I? Haven't I done enough already?

> So the question is what does Alpine Linux offer in addition, that others do not have (technology? Something revolutionary stuff like NixOS?).

- significantly smaller foot print due to musl libc and busybox. Fewer lines, fewer holes.
- exploit mitigation. hardened kernel and toolchain by default (similar to what gentoo hardened provides)

**Comment by nodiscc** [comment]
> I dont have time and energy to start discussion with distros that i don't even use

@ncopa [makes sense](https://upload.wikimedia.org/wikipedia/commons/1/1b/Linux_Distribution_Timeline.svg). 

I think there needs to be a CVE for all "common" distros to automatically track a package that has security issues ([example](https://security-tracker.debian.org/) on debian).There will be more attemps to patch it, and it should mark the package as release-critical (removed from the next release unless fixed). But I think you'd have to file a CVE yes. What is the process (eg for your freeradius bug)?

_mind that this particular bug causes a crash, not information disclosure/code execution/nsa-in-your-network (on which the prism-break list focuses)_

Again, a security bug marked as **high** on debian/centos/fedora/gentoo/...'s tracker is more visible/helps more users/has more eyes on it than on the tracker for a distro which many people "don't even use" :) General distro fragmentation problem/question, which this bug is about; fragmentation harms security-focused software even more bad. 

> musl libc and busybox [...] hardened kernel and toolchain 

Is this possible to maintain for a "common" distro? I think you would just need to maintain 1) an installer for your derivative (eg with http://live.debian.net/devel/live-build/) 2) a repo for your hardened packages/kernels/config set (hardened config, package pinning...) Serious question.

More workforce/visibility, more testers/users of your work (which I think is the point of this project), more bug reports... and you can focus on maintaining only your changes. Or is this not possible?

**Comment by hasufell** [comment]
This is sort of OT and not really important for the decision of whether to include Alpine Linux, but I feel I have to respond:

> @ncopa makes sense.

I disagree, because some distro developers do that. Having communication channels to other distributions is always helpful in order to spread the word about certain issues. I've done that in the past (when it was non-trivial or I felt like it) and I don't understand why that shouldn't be possible.

If I feel that an upstream developer ignores a fundamental security vulnerability, I'd have that info communicated to at least 5 other distros where I happen to know a developer (wouldn't take more than a couple of minutes).

But I guess we need some sort of cross-distro communication platform for such matters (and some more).


Again: I'm not saying someone did something wrong here. But the line of argumentation was a bit weird (we found the security bug, you didn't).

**Comment by hasufell** [comment]
Alpine linux re-enabling SSLv2/weak ciphers suites [0] in openssl although openssl developers explicitly discourage it [1].

Looks like a workflow issue, lack of build machines or something.

[0] http://lists.alpinelinux.org/alpine-devel/5204.html
[1] https://openssl.org/news/secadv/20160301.txt

**Comment by ncopa** [comment]
@hasufell We don't break ABI in a stable branch. removing support for those weak cryptos would make everything break. (it actually did break stuff for us).

**Comment by hasufell** [comment]
@ncopa afaik every other major binary distro was able to solve that problem. If ABI breaks, you have to rebuild and revbump stuff.

**Comment by ncopa** [comment]
@hasufell really? http://pkgs.fedoraproject.org/cgit/rpms/openssl.git/commit/?id=8f6be98bf7b9e9015ad035f34b8414e82c7b68ca

**Comment by hasufell** [comment]
Looks like fedora did it wrong too then.

**Comment by ncopa** [comment]
Either that or you have no idea what you are talking about.

Can you give any example of a major binary distro who did it [right](https://bugzilla.redhat.com/show_bug.cgi?id=1313509#c8)? Don't say debian because they [didn't](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=22876#8).

**Comment by hasufell** [comment]
> Either that or you have no idea what you are talking about.

Hm, I've had 4 years of experience, so probably not.

> Can you give any example of a major binary distro who did it right? Don't say debian because they didn't.

I guess I was wrong there. Most major binary distros do it wrong. Is that a good argument for you to do the same?

If you can't ship a security update that requires reverse dependencies to be rebuilt quickly and properly, then you are doing something wrong.

**Comment by ncopa** [comment]
I'd say it is a good argument to avoid libraries that cannot do security upgrades without breaking the ABI.

**Comment by ncopa** [comment]
Seems like not even source based distros manages to do it "right":
https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-libs/openssl?id=15eb910faba4df68ce400a463db5c2a989279360

**Comment by hasufell** [comment]
> I'd say it is a good argument to avoid libraries that cannot do security upgrades without breaking the ABI.

Well yes, openssl maintainers are obviously amateurs and don't even know what an SONAME is.

> Seems like not even source based distros manages to do it "right":
> https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-libs/openssl?id=15eb910faba4df68ce400a463db5c2a989279360

Yes, that commit was wrong, although gentoo has mechanisms to trigger rebuilds even without an SONAME bump.

**Comment by hasufell** [comment]
Before more confusion arises, there are several way this could have been handled properly.
Source distros have it easy, they can:
* just tell the userbase to rebuild reverse-dependencies, possibly publishing a news item (most have a PM-side news system)
* rely on mechanisms like [SUBSLOTS](https://wiki.gentoo.org/wiki/Sub-slots_and_Slot-Operators) to work around broken SONAMES... however this requires that the input is not junk (as in: reverse deps definitions make use of that mechanism)
* revision-bump all reverse deps... this can be automated via scripts or can even reasonably be done by hand for core-packages in 1-3 hours... but that requires that packagers are not lazy

Binary distros can only rebuild all reverse deps and then publish them in one go. Everything else is a half-baked solution.

Or: just don't use openssl. If Alpine Linux cares that much about security, now is the time to realize that openssl maintainers are amateurs.

**Comment by yegortimoshenko** [comment]
Alpine Linux is not GNU/Linux (so we would have to rename the category), and busybox/musl userland is significantly more experimental and some software is not supported, e.g. I think there is still no JDK for Linux + musl on x86_64. (And proprietary Linux software is not supported at all.)
