### ISSUE TITLE
Firefox addon that disguises your browser

### ISSUE THREAD

**Issue by Raprp** [nylira/prism-break#1197]
I've been using Random Agent Spoofer addon for Firefox and it's really good. You can randomize your browser profile (not only the user agent header) in every request, X minutes or when you open a new browser instance.

Here is the URL to the girhub project: https://github.com/dillbyrne/random-agent-spoofer

PS: This plugin is not mine

**Comment by hasufell** [comment]
> The point is to make it look like the user is not spoofing and to not stand out. If your browser gets fingerprinted it is not your real browser and if it is set to change on a timer the browser becomes a moving target.

That makes sense IMO.

**Comment by RanceJustice** [comment]
I too feel that Random Agent Spoofer seems to be  amongst the best addons in this regard.   Of course, nothing is a panacea, but it can certainly an additional layer of obfuscation.   Thank you to the developer for making a more comprehensive implementation than most that have a simple, small group of user agents.   I find it can be used in "random" mode for maximum privacy (note this may not be "set it and forget it for non technical users, as some web pages may appear differently if you appear to be on a mobile browser  etc..), or you can set it for  specific spoof - this is originally what had me seeking it out, as I would set it to a Linux agent when making certain purchases  (ie HumbleBundle / Humble Store) to be sure they "counted" towards Linux as I wished.

**Comment by mastercoms** [comment]
https://www.eff.org/deeplinks/2010/01/primer-information-theory-and-privacy

**Comment by Zegnat** [comment]
@mastercoms, that is not at all what Panopticlick is about. They are about the uniqueness of your browser. The solution to that is *not* just spoofing.

If you are using a standard Firefox binary on a standard Windows installation you are better off not spoofing any browser data because your browser is already just like thousands of others, it is already not unique. (Something I wrote about in #965, as this is important for the there mentioned ‘random’ factor.)

This is also why the Tor Browser Bundle version of Firefox does not implement any kind of spoofing like this. The goal is to give all the browsers the same fingerprint, rather than trying to change the fingerprint all the time.

Random Agent Spoofer understands this and goes through great lengths to try and make the fingerprint as close to other existing browsers as possible. I am just not sure if this really adds a lot of protection against tracking or not, as there has been very little research into it. That is what is keeping me from merging it in. (If it really was **the** solution to the fingerprinting problem I would’ve merged it in at once.)

**Comment by hasufell** [comment]
> The goal is to give all the browsers the same fingerprint

Those are two different concepts. I haven't seen a good argument yet why the concept explained here is not good (and the concept of spoofing **IS** used by Tor, just not for the fingerprint which was a big mistake...). Also, can you give me research papers that say the concept of giving all browsers the same fingerprint works **practically** for the Tor network (that will be difficult)?

The only argument WOULD be to say "most Tor users have the same fingerprint, so using Random Agent Spoofer might cause harm to the Tor network".
That argument is:
* very far-fetched, because even if there are two distinguishable "groups" that either have unique fingerprints or have random fingerprints... it's still not obvious how you can practically use this data. So it's a very theoretical attack vector.
* not provable or disprovable, because no one (except NSA maybe) knows exactly how many people run the Tor browser bundle as the Tor developers suggest and how many use Tor differently, because you'd need a lot of data from inside the Tor network to know this

And... this plugin is NOT just for Tor. It's purpose is more general. You can use it just with plain firefox and there is no research needed to prove that this spoofing technique works and that it does disguise your true browser details.

**Comment by Zegnat** [comment]
Oh, I agree with most of that @hasufell. I was mostly writing in regard to Panopticlick as an argument. Panopticlick is aimed at exploiting *unique* fingerprints, something Tor tries to counter by trying to have everyone use the same browser and thus give the whole network the same fingerprint. (A good idea, IMHO.)

However, for the Tor project to get anywhere near to neutralising those risks they have to do [*a lot* of stuff](https://www.torproject.org/projects/torbrowser/design/#fingerprinting-defenses). My main concern with recommending a project like RAS is that people feel they get more protection than they are really getting. From @dillbyrne’s description it seems that RAS is actually covering most of the vulnerabilities the Tor project also found and listed on their wiki, but I haven’t gone through it with a fine-toothed comb.

The problem if RAS misses a few factors is that these add entropy to your fingerprint rapidly. Still hiding part of your browser information, but opening you up to a Panopticlick-like fingerprinting attack. Maybe you are spoofing to look like IE on Windows, but the fingerprinting code runs a mathematical javascript functions and the result clearly Firefox. Now you have an extremely unique fingerprint: IE on Windows with mathematical capability of Firefox on Gentoo. Oops. You may have been less unique if you hadn’t used RAS and just shown up as Firefox on Gentoo.

So yeah, that’s my main fear. Spoofing technology doesn’t seem to have caught up with fingerprinting technology yet, and I wouldn’t want to oversell spoofing. Not to say that I do not love the idea – I do! – but there are just [so many things](https://trac.torproject.org/projects/tor/query?status=!closed&keywords=~tbb-fingerprinting) that can be used to fingerprint the browser.

There are some things I definitely agree with. Hiding information is a good thing, especially when this information can lead to you. Hiding what fonts I have installed on my machine is something I really want my browser to do, hiding my OS and browser is something that has just too many edge-cases.

---

After writing this, I now seem to think RAS should be included simply for its option to protect against canvas attacks, font profiling, et al. Though I am still concerned about overselling spoofing capabilities. @dillbyrne, how would you describe the effectiveness of spoofing in these cases? Do you, as RAS developer, keep an eye on new fingerprinting technologies such as [described on the Tor tracker](https://trac.torproject.org/projects/tor/query?status=!closed&keywords=~tbb-fingerprinting)?

**Comment by hasufell** [comment]
> My main concern with recommending a project like RAS is that people feel they get more protection than they are really getting.

Prism-break is still recommending software for windows and mac users while it's widely known that both operating systems are fundamentally broken, insecure and have been cracked on a large scale for creating huge bot-networks (and neutralizing them too... for your convenience Microsoft can do that).

It's sort of applying double standards.

> but the fingerprinting code runs a mathematical javascript functions and the result clearly Firefox

Yes, that's important to know, but outside of the scope of addons. A note could make sense.

> Now you have an extremely unique fingerprint

Again, that's exactly the goal. The profile however switches in intervals you can specify like 5min. 

But you are right, what can happen here is that you are identified as a spoofer (the same goes for Tor). But in 5min you are a different spoofer... so I don't really see how that helps the "attacker". At worst... RAS doesn't help you (the same goes for Tor).

**Comment by dillbyrne** [comment]
Hello @Zegnat and others.

I try to keep up to date with the latest developments in the area. I have read many sources on the issue from whitepapers to blogs. Some of which are listed below

https://wiki.mozilla.org/Fingerprinting
https://www.torproject.org/projects/torbrowser/design/
http://www.chromium.org/Home/chromium-security/client-identification-mechanisms
https://www.eff.org/deeplinks/2010/01/primer-information-theory-and-privacy
https://panopticlick.eff.org/about.php
http://pet-portal.eu/files/articles/2011/fingerprinting/cross-browser_fingerprinting.pdf
https://panopticlick.eff.org/browser-uniqueness.pdf

I also test RAS against online tests some of which are

http://fingerprint.pet-portal.eu/
http://pgl.yoyo.org/http/browser-headers.php
http://lucb1e.com/rp/cookielesscookies/
www.browserleaks.com
http://browserspy.dk
http://ip-check.info/?lang=en
https://panopticlick.eff.org/


In terms of fingerprinting RAS and the tor browser each approach it differently. The Tor browser approach is to make all users share a common fingerprint where as RAS provides a set of specifically tailored  browser profiles using values from real browsers and devices each of which has their own fingerprint.

RAS initially started out as a profile switcher by design and more options have been and will be added over time. As it currently stands the profile switching code including header spoofing works really well. The script injection code is not as mature, it can cause a problem with the odd site here and there but for the most part it works fine. I plan to improve various aspects of the script injection code such as the date spoofing. 

I would recommend users using the Tor browser to not use RAS with it as the Tor browser was designed with the goal of blending in in mind so it is best to stick to that approach in that case. Also some of the features overlap. I read the tor browser design document and try to add features from that into RAS where I can. This is not to say they cannot be used together should a user wish to do so. 

RAS is well suited to your "normal" browser where advertisers and others are trying to siphon as much information from you as possible. [It presents real profiles so it does not look out of place including the correct header formats, pixel can color depth's, compatible screen resolutions](https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json)  and  it also provides option to disable the particularly harmful stuff such as the canvas. it works well with other useful plugins such as no script.

I have issues open for dealing with cookies and plugins as well as a host of improvements to current issues. 

I believe RAS is a good tool to help protect against fingerprinting but I realize there is nothing that will be 100% effective. It is a constantly changing landscape. 

If there is any other questions feel free to ask.

**Comment by vyp** [comment]
@Zegnat https://help.github.com/articles/closing-issues-via-commit-messages/. :+1:

**Comment by Zegnat** [comment]
I love how often that article talks about ‘closing issues’ and then doesn’t allow for the word ‘closing’. Note that I will probably forget what words trigger auto-closing in about 2 days, but thanks :wink:

**Comment by vyp** [comment]
No worries, you had just done it twice in a row, so I thought I'll let know just in case.
