### ISSUE TITLE
Yandex perhaps?

### ISSUE THREAD

**Issue by nerrve** [nylira/prism-break#1207]
I think its worth at least a mention, in the proprietary or free sections

**Comment by KOLANICH** [comment]
1 Yandex is a proprietary se.
2 Yandex is registered in Netherlands but it will obey the laws of Russian Federation because most of its users are from Russia.
3 [Yandex collects info and analyses it to target ads.](http://company.yandex.com/technologies/crypta.xml)
4 IMHO, yandex searches worse than Google (but some of its services are much batter then googles ones).

**Comment by Zegnat** [comment]
That’s why I said “it would go in the proprietary list”, and that’s the pull request I will accept.

**Comment by Zegnat** [comment]
As of eba821602e6b141eb3144107ae6143eb4e05fa78 Yandex (and some of its services) is listed in the proprietary column.
