### ISSUE TITLE
Cryptomator

### ISSUE THREAD

**Issue by theltalpha** [nylira/prism-break#1208]
http://cryptomator.org/

Free client-side AES encryption for your cloud files. Open source software: No backdoors, no registration.

Interesting?

**Comment by Maxiride** [comment]
I would like to bump up this ticket since Cryptomator evolved to a stable and more sophisticated service. iOS and Android app are also available.

Anyone interested in reviewing to add it to the database?

**Comment by Hillside502** [comment]
Android app still only Beta, otherwise:-

Cryptomator: Free Cloud Encryption for Dropbox & Others
https://cryptomator.org/

Cryptomator Reviews - AlternativeTo.net
https://alternativeto.net/software/cryptomator/reviews/

Cryptomator Beta – Android
https://play.google.com/store/apps/details?id=org.cryptomator.beta

**Comment by Hillside502** [comment]
Cryptomator Android now out of Beta

Cryptomator 1.0 for Android Release
https://cryptomator.org/blog/2017/10/17/android-1.0_en.html

**Comment by yegortimoshenko** [comment]
They use scrypt for key stretching (makes extremely hard to bruteforce even simple passphrases): https://cryptomator.org/security/architecture/

> Both [AES and MAC] keys are encrypted using RFC 3394 key wrapping with a KEK derived from the user's password using scrypt.
