### ISSUE TITLE
new documents proving truecrypt is the way to go

### ISSUE THREAD

**Issue by BigBroza** [nylira/prism-break#1212]
quite sad to see prism break is still doing this false statement

<i>2014-05-28: TrueCrypt currently has security issues and is not recommended.</i>

http://www.theverge.com/2014/12/28/7458159/encryption-standards-the-nsa-cant-crack-pgp-tor-otr-snowden

New documents reveal which encryption tools are causing troubles to the NSA, there are only a few of them, and truecrypt is in there.

So if prism break is really intending to break prism, maybe it's time to reinstate truecrypt as the recommended solution?

**Comment by BigBroza** [comment]
truecrypt developers received a national security letter, is what I'm saying

truecrypt has no security issue, it is one of the few reliable tools that can be used to protect your privacy

**Comment by psgs** [comment]
@BigBroza, As of the 1st of January 2015, it has been found that TrueCrypt received a national security letter, presumably in May 2014. As of such, it can be noted that United States governmental authorities have found interest in attempting to shut down TrueCrypt. Due to this fact, using TrueCrypt may bear additional security risks than using an encryption platform which was not found to be of particular interest to United States intelligence programs.

Furthermore, the following statement was declared on [TrueCrypt's sourceforge page](http://truecrypt.sourceforge.net/):
> WARNING: Using TrueCrypt is not secure as it may contain unfixed security issues

For these reasons, many users of encryption platforms consider TrueCrypt to be insecure, and potentially vulnerable to eavesdropping by certain parties.

More information regarding the declaration of TrueCrypt to be insecure can be found at:
* [ThreatPost](http://threatpost.com/of-truecrypt-and-warrant-canaries/106355)
* [The Guardian](http://www.theguardian.com/technology/2014/may/30/encryption-software-truecrypt-closes-doors)
* [TechDirt](https://www.techdirt.com/articles/20140528/14144527380/truecrypt-page-says-its-not-secure-all-development-stopped.shtml)

Thankyou!
psgs :palm_tree:

**Comment by BigBroza** [comment]
the very same page that had that warning also recommended alternatives that have known backdoors for the NSA, in other words, that warning can not be trusted

truecrypt has been thoroughly audited and no serious security issue was found

truecrypt is the most audited tool and one of the few tools that is a problem for the nsa, in other words, that's what everybody should use to protect their privacy

**Comment by psgs** [comment]
@BigBroza,

This issue has been thoroughly discussed in issues #995, #1003  and #1016.
Instead of creating a new issue every few months, I would strongly recommend that you continue discussion in issue #995, in order to ensure that discussion can be accessed from a central location, allowing readers to easily obtain a broad view of points relating to TrueCrypt security issues.

As stated by @Zegnat in issue #995:
> Administrative note: I have changed the title of this issue and labelled it for discussion. Please add all further discussion on reinstating TrueCrypt or substituting one of its forks here.

Furthermore, several reasons for adding a security notice to TrueCrypt on PrismBreak were listed in issue #995, including the following:
> It seems TrueCrypt was not pulled back because of current security issues, but because future issues would no longer be patched. The team no longer wanted to work on it. “We worked hard on this for 10 years, nothing lasts forever.” ([source](https://twitter.com/stevebarnhart/status/472200478345150464).)

Thankyou!
psgs :palm_tree:

**Comment by rwzy** [comment]
> the very same page that had that warning also recommended alternatives that have known backdoors for the NSA, in other words, that warning can not be trusted

That does not mean that we can also just assume truecrypt is therefore safe.

**Comment by rwzy** [comment]
Also, if you watched @ioerror's c3:

> I really wonder if someone could figure out why truecrypt shut down. That would be really interesting.

Should be noted that he didn't recommend it when talking about OTR and gpg, but only talked about truecrypt at the questions section at the end when asked a relevant question.

**Comment by mva1985** [comment]
Steve Gibson from grc.com says that truecrypt is fine.  I would think Veracrypt would be a viable alternative if you didn't want to trust truecrypt.

**Comment by strugee** [comment]
> @BigBroza, As of the 1st of January 2015, it has been found that TrueCrypt received a national security letter, presumably in May 2014.

Citation needed.

**Comment by strugee** [comment]
Excuse me, I shouldn't have said that. Let's continue discussion in #995.

**Comment by psgs** [comment]
Hello @strugee,

In my comment regarding a National Security Letter being sent to TrueCrypt, I included a few references at the bottom of the comment. I'm quite sorry if they didn't appear obvious. I've added a quick note to the top sentence so that it doesn't happen again.

Thankyou,
psgs

**Comment by Zegnat** [comment]
Like @psgs and @strugee have said, please take this up in #995. New comments such as from Jake’s CCC session would be appreciated in that issue to keep things centralised.

I do agree with @BigBroza that the current warning is flawed. In fact, I have stated [back in June](https://github.com/nylira/prism-break/issues/995#issuecomment-45764040) that I am open for better worded explanations. I have been too preoccupied with my studies and life in general to be actively contributing here outside of the issue tracker, but I will definitely merge pull-requests that meet the community’s standard if anyone wishes to add a better one-liner.

Closing this. Please go to #995.

**Comment by alerque** [comment]
@psgs Your three reference articles are all dated in May of last year and include nothing but _speculation_ about a possible NSL. Nothing I read there backs up your statement that as on Jan 2015 it is known that TrueCrypt received a NSL. If there is really such knowledge, a link to the source would be relevant to the ongoing discussion on issue #995. Please add it there is such a thing exists. Otherwise I don't see how old speculation changes the status of the active discussion.
