### ISSUE TITLE
Add Bookie - bookmark your web

### ISSUE THREAD

**Issue by GreenLunar** [nylira/prism-break#1215]
Python based delicious.com replacement
https://github.com/bookieio/Bookie
https://bookie.io/
http://bmark.us/
@mitechie

**Comment by Zegnat** [comment]
Bookie has come up before in #496 so I am closing this issue and you may add arguments for its inclusion there. There is also #1055 on Firefox Sync.

Mostly none of this is included because it is hard to say what proprietary applications it would be replacing, but if you can come up with a good reasoning and category it will certainly be considered for inclusion.

**Comment by Zegnat** [comment]
PRISM Break suggests alternatives for “media publishing”, mainly to encourage people to self-host rather than depend on platforms like YouTube for everything. Wikis have previously been rejected from being listed because there are very few proprietary wikis and also because users specifically turn to them to publish things.

If something is about “publishing/sharing” there is little reason for PRISM Break to list it. If you chose to make things public it would be easy enough to find Bookie or Shaarli. If there is any reason to believe your local bookmarks are being analysed by external parties, that is when PRISM Break comes in.

**Comment by GreenLunar** [comment]
@Zegnat
These free bookmarks managers are more honest, in the sense that statistics and popularity is not forged, and are truly private when user wants links to be private.  I do not want G or Y to know what some certain personal (private) references I have.

@nodiscc
Thank you for posting a link to Shaarli.

**Comment by nodiscc** [comment]
@Zegnat 

> PRISM Break suggests alternatives for “media publishing”, mainly to encourage people to self-host rather than depend on platforms like YouTube for everything

This is the reason suggesting a FOSS, self-hostable [Social Bookmarking](https://en.wikipedia.org/wiki/Social_bookmarking) service like Shaarli or Bookie, 1) to avoid lock-in to proprietary bookmarking services like delicious or pinterest 2) to prevent complete analysis of your bookmarks/clicks/post habits by a proprietary service.

Same could be said for photo hosting (picasa, flickr...), rss reading (feedly -> tt-rss)...

Would you be ok to add a section for self-hostable web apps? Should I open another issue for this?
