### ISSUE TITLE
[Cellular] SnoopSnitch

### ISSUE THREAD

**Issue by Zegnat** [nylira/prism-break#1219]
[**SnoopSnitch**](https://opensource.srlabs.de/projects/snoopsnitch) by [SRLabs](https://srlabs.de/)
- [Source](https://opensource.srlabs.de/projects/snoopsnitch/repository/revisions/master/show)
- [GPLv3](https://opensource.srlabs.de/projects/snoopsnitch/repository/revisions/master/entry/COPYING)

---

As seen on [Schneier on Security](https://www.schneier.com/blog/archives/2015/01/surveillance_de.html) and installable through [F-Droid](https://f-droid.org/repository/browse/?fdid=de.srlabs.snoopsnitch).

This seems to be an [Android IMSI-Catcher Detector](https://prism-break.org/en/projects/android-imsi-catcher-detector-aimsicd/) alternative. I am unsure about the pros/cons on either, but maybe @SecUpwN could comment on that? Should we list both? Or only one of them?

**Comment by vyp** [comment]
Snoopsnitch is good, surpised it isn't on already. I don't have experience with android imsi-catcher detector though.

**Comment by SecUpwN** [comment]
Thank you for actually providing me the honor to take part in that decision, @Zegnat.

I am honest with you when I say that I have some strange flavour in my mouth when thinking and talking about SnoopSnitch: First of all, our team and me has been in touch with SRLabs long before they crafted their App (since they did a great and noticeable job on CatcherCatcher) and actually invited them to take part in our development, which started back [in 2012 on XDA](https://forum.xda-developers.com/showthread.php?t=1422969). Apart from their unresponsiveness and not willing to contribute to our already existing truly open source project, it seems they don't really care much about the community or privacy activists out there, but rather craft their own stuff. That alone has some strange flavor for me, but that is just my personal opinion. I still like those guys and am still interested in them joining our taskforce, hence we are also so friendly and open to list them in our [Similar Projects](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Similar-Projects).

The real concerns with SnoopSnitch itself: Apart from the fact that the source code is downloadable:
* Is it *really* open source as in "open development for everyone"? 

Since it (optionally) **connects to servers stationed within the US**:
* *How* to check if the App is really not connecting to those servers, even if the option is not checked? 
* *What* is happening with the data on those servers?
* *Where* is that data stored and how is the data secured?
* *How long* will the submitted (radio) data be stored?

Again, I can just state my own concerns here and those might seem biased, you really **should** check the source code for yourself and make your own assumptions. Not sure how many activists will use SnoopSnitch or have problems with it, but personally, I'd prefer a truly open project, in all steps of development, truly using Open Source Tools, Servers and transparency for all data storage. One more point: Since SnoopSnitch is also available on GooglePlay, they **must** also agree to the legal [Terms of Google Play](https://play.google.com/intl/en_us/about/play-terms.html), hence they can also pull that App from your device via *GTalkService* using [REMOVE_ASSET](https://jon.oberheide.org/blog/2010/06/28/a-peek-inside-the-gtalkservice-connection/), if they want to. We are having a strong stand [against GooglePlay](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/FAQ#q-why-wont-you-upload-your-app-to-the-google-play-store), for obvious reasons. Decide for yourself if SnoopSnitch shall be added to your great website, please.

Anything to add to what I just said, @E3V3A or @He3556?

**Comment by Cathryne** [comment]
Just for completeness sake: the 31c3 talk in which this tool was introduced: http://media.ccc.de/browse/congress/2014/31c3_-_6122_-_en_-_saal_1_-_201412271830_-_mobile_self-defense_-_karsten_nohl.html
