### ISSUE TITLE
ChatSecure

### ISSUE THREAD

**Issue by trollyadvanced** [nylira/prism-break#1223]
Hi, I have three questions about ChatSecure:
Is the groupchat only Client-Server-encrypted?
Has ChatSecure a asynchronous communication?
  -> Is the asynchronous communication encrypted?

https://de.wikipedia.org/wiki/Liste_von_mobilen_Instant-Messengern

Sorry for my bad english;)

THX

**Comment by Zegnat** [comment]
PRISM Break is not really the place for support questions, you could instead [ask ChatSecure](https://chatsecure.org/support/).

* I do believe ChatSecure is just as asynchronous as any other messaging app. It uses XMPP which is (or was) used as the back-end for Facebook messages as well. So anything Facebook messages can do, ChatSecure can do.

* One-on-one chats are encrypted using OTR.

* Group chats are not encrypted (as far as I know) because OTR doesn’t have a formal multiuser encryption scheme.
