### ISSUE TITLE
Consider adding AeroFS

### ISSUE THREAD

**Issue by sandstrom** [nylira/prism-break#1224]
It think AeroFS is worthy of mention in the file sharing category. Everything is cleverly encrypted on the clients, so they have no ability to read data. They are a commercial entity though, and their software is proprietary.

More broadly, I think it's worth mentioning commercial alternatives as long as they adhere to strict requirements on privacy, encryption etc. By encouraging good commercial companies, other firms will be more inclined to improve privacy and encryption in their products.

https://www.aerofs.com/

(I've got no affiliation with AeroFS)

**Comment by vyp** [comment]
You'll have to excuse my stupidity here, but I'm not quite sure exactly how it works just by reading their website. (Unfortunately, I couldn't watch the video since it requires flash.)

> Your files are never stored on AeroFS servers.

So what are AeroFS servers used for then? Nothing? Why mention it then?

So it seems to be a dropbox-like application that's designed to be used on a personal server. Zero chance I'd give a proprietary application that handles file sharing to handle my own data, and I don't think the prism break project leaders would either.

If you do use it, how do you ensure that "they have no ability to read data" when it's proprietary? (Not rhetorical, perhaps there is a way?)

But I wouldn't be opposed to adding it under the proprietary (and to be avoided) section under File Storage & Sync.

**Comment by Zegnat** [comment]
Let me comment on the thing you mentioned last, because people still seem to ask about this every so often:

> I think it's worth mentioning commercial alternatives as long as they adhere to strict requirements on privacy, encryption etc. By encouraging good commercial companies, other firms will be more inclined to improve privacy and encryption in their products.

**We agree!**

So why do we keep on talking about ‘Free’ software? Because we aren’t talking about <i>gratis</i>, the free meaning you do not have to pay for it. We are only talking about <i>libre</i>, the freedom to do things with the software you have. You might have heard the expression ‘[free as in free speech, not as in free beer](http://english.stackexchange.com/a/10299)’. That is the definition that the Free Software Foundation set out. In fact, not only does the GNU GPL allow you to sell your software, they encourage people to:

> Actually, we <i>[The Free Software Foundation]</i> encourage people who redistribute free software to charge as much as they wish or can. If this seems surprising to you, [please read on](https://www.gnu.org/philosophy/selling.html).

PRISM Break has several discussions going on about the inclusion of back-up services. Off-site back-ups are a safety win, but unless you have some serious funds this means you will have to rely on a (probably commercial) third party. This should not be a problem if your back-ups are properly encrypted before going over the wire to them.

So how do you, the end user, know if something is properly encrypted? You should be able to 1) look at the code that is used to encrypt your data, and 2) verify you are running the code you have just inspected. This is why we need encryption tools to be free software. (Extra reading: [Higgins on demanding ‘not just open-source’, but ‘free software’](http://parkerhiggins.net/2014/03/our-encryption-tools-must-be-free-software-not-just-open-source/).)

Is proprietary software less safe than open-source software? Not by definition. (If you really want to read more about this, I recommend [Wheeler’s <i>Is Open Source Good for Security?</i>](http://www.dwheeler.com/secure-programs/Secure-Programs-HOWTO/open-source-security.html).) Can you do the above 2 things with proprietary software? No.

---

The above applies to all proprietary security software. To AeroFS specifically the problem would be like @vyp states: you can’t verify their encryption, using them would be 100% trust based. Therefore it will never qualify for PRISM Break.

I am going to close this issue, and bookmark the URL to this comment so I do not have to ever rewrite the whole argument again :smiley:

**Comment by sandstrom** [comment]
@Zegnat That's a valid argument.

I'll expand my thoughts. Take Linux, it has made systems more secure (and better in other ways too). It's open source, but I don't think it would have it's current position without a bunch of companies making money on it.

I think your website is great! But you may further your goals if you'd find a way to encourage companies to “do the right thing”. Possibly by highlight those that build security and privacy into their products.

Although it cannot be verified it seems pretty obvious that's what AeroFS is doing (at least relative some of it's competitors, I still agree that it would be better if you could inspect the source).

Another example is WhatsApp's recent encryption efforts[1], which similarly cannot be verified. But it seems apparent that they want to increase security and privacy for their users.

I don't know though! Perhaps you should limit the scope to only open source projects, to keep the lines clear. But there may also be a middle ground, where you do both (perhaps a sister project/domain).

[1] https://whispersystems.org/blog/whatsapp/

**Comment by vyp** [comment]
> It's open source, but I don't think it would have it's current position without a bunch of companies making money on it.

I don't see your point here? Again, as @Zegnat said, free software can be commercial too. (If anything, it's more of a plus point *for* linux/floss software, which is prism break obviously isn't against.)

> But you may further your goals if you'd find a way to encourage companies to “do the right thing”. Possibly by highlight those that build security and privacy into their products.

> Although it cannot be verified it seems pretty obvious that's what AeroFS is doing

Except, AeroFs is *not* doing the right thing. Sorry to sound so harsh and close minded, but the simple matter of fact that you do not trust what you cannot read [1]. Think about that for a second, why should proprietary software even *be* an option for security minded folks?

Security wise, there is no reason for it to be proprietary. Yes, maybe business wise there is. But what does that say? It says that really, the company does not care about security. Of course, every company by definition is in it for the money, but it is possible to care about security too while principally caring about money. And any company releasing proprietary software as a 'secure' product does not really (deep down) care about the security, even though it *seems* as though they do via their website/marketing.

What I mean by deep down, is that of course they care about security at a basic level so as that it does not hurt their business. But after that, probably not so much. Yes e2ee is great, but what is doing that e2ee encryption? Wouldn't it be very easy for the proprietary program to subvert the keys?

Perhaps AeroFS is genuine and they really do care, but from a users point of view, why should *we* have to trust them when they could just make it free software? Either they *don't really* care, or they genuinely don't understand that free software is practically a requirement for true security in software (which is unlikely). But it does not make a difference from our point of view.

That's why I therefore think there cannot unfortunately be any middle ground here. And, you would also be severely under estimating NSA's (and other 3/4 letter agencies) reach here, meaning nothing should be left to *chance*, or in other words, we should seek to control as much as we can. Limiting to only free software is something that we can, and in the 'post-Snowden' era, we not only should, but we must do, and the link below should help to somewhat explain that a bit further.

[1]: https://www.youtube.com/watch?v=aOcpDsDSWY0#t=1789

**Comment by Zegnat** [comment]
> I think your website is great! But you may further your goals if you’d find a way to encourage companies to “do the right thing”. Possibly by highlight those that build security and privacy into their products.

We try to do that. Mozilla and EFF are organisations we respect a lot, they open-source their software and look at other places for their income.

Another interesting example is the Kolab groupware that is being promoted by PRISM Break. You can pay Kolab Systems AG (mykolab.com) to host it for you, we even recommend MyKolab on PRISM Break. For enterprises Kolab Systems AG develops a special version that comes with 5 years support (probably comparable to Firefox ESR, Ubuntu LTS, etc), which they also charge for.

AeroFS is already offering an enterprise solution, so the real (subjective…) “right thing” to do might have been to open source their file synchronisation software completely and then have a special supported package for enterprises. There might be countless of reasons why they decided not to do this (or haven’t yet considered it) and they are free to try and make money of their work however they want. But PRISM Break will not accept proprietary software, even when it accepts commercial software.

**Comment by sandstrom** [comment]
I agree with everything you say, I prefer open-source for security/privacy/encryption. But I also thing there is a continuum among closed-source.

You probably know him well already, but if you read up on Moxie you'd find that he cares about privacy. Still, for some reason he spent time building encryption into *closed-source* WhatsApp[1]. Why did he do that? Or the EFF scorecard[2], why include closed-source? Shouldn't they only support open-source?

[1] https://whispersystems.org/blog/whatsapp/
[2] https://www.eff.org/secure-messaging-scorecard

**Comment by vyp** [comment]
The most likely reason is money. Good questions, and I'm not questioning whether or not he cares, obviously, but even then it doesn't make a difference to prism break why he did it.

EFF scorecard includes proprietary software for comparison, simply because people use it and therefore it's helpful to tell them that there's security related flaws in the applications they use. (I.e. "Is the code open to independent review?" would be the column where users of such proprietary applications would see the weakness.)

**Comment by hasufell** [comment]
Software is like drugs.

If it's closed source, then they don't tell you anything about the active substances, as in: what is inside. Sure, you still know how the drug affects you on a daily basis, but one day you mix it with soda and it blows up your brain.

Ofc you can go to a chemist and ask him to disassemble and analyze the stuff. That's tedious and doesn't necessarily yield all information, e.g. about the manufacturing process.

If you really want to you can also do blackbox tests and make your cat take the drug.

However, in the end... you don't really know what it is and what it does, so you cannot trust it... and especially not the guy in the park who sold you that crap. ;)

**Comment by Zegnat** [comment]
> Another example is WhatsApp's recent encryption efforts[1], which similarly cannot be verified. But it seems apparent that they want to increase security and privacy for their users.

They are helping the general public enormously by adding encryption to WhatsApp! Kudos! And if WhatsApp is not ordered (or does not comply with requests) to add backdoors in their proprietary application that would be great. But we will never know for sure, because we can’t check it. And not knowing for sure is not something a human rights activist will want to do.

If I see a WhatsApp APK that has been signed by Open Whisper Systems I might say that my trust in Open Whisper Systems to package a secure application outweighs the fact that the application is closed-source, but just WhatsApp from the Play Store? Nope.

>  Or the EFF scorecard, why include closed-source? Shouldn’t they only support open-source?

In a way, they ‘only support open-source’. The only way to get all checkmarks is if the code is ‘open to independent review’. They are also very clear on [their inclusion guidelines](https://www.eff.org/secure-messaging-scorecard#about):

> We chose technologies that have a large user base--and thus a great deal of sensitive user communications--in addition to smaller companies that are pioneering advanced security practices.

What with proprietary software still winning over open-source when it comes to ease of use and installation it is not weird for the scorecard to include software that most security-minded people will avoid like a plague. (AIM? Really?)

I personally do not put a lot of value in the scorecard because of some (IMHO) odd choices made by the EFF when compiling it. One such is the checkmark for audits. The audit does not have to be made public in whole or in part, not even the results have to be published. The audit can even be done by an internal team (e.g. that’s what Snapchat did to get the checkmark).

For now, don’t use the scorecard to chose what messaging software you use. Instead hope for it to do what it was made to do:

> <i>[…]</i> serve as a race-to-the-top, spurring innovation around strong crypto for digital communications.
