### ISSUE TITLE
Remove Ghostery

### ISSUE THREAD

**Issue by farukuzun** [nylira/prism-break#1225]
Hello,

Can you remove Ghostery mention please?
An addon which is sending your data to its' servers[0] shouldn't be listed or mentioned here, even you can opt out from it. 
https://github.com/nylira/prism-break/blob/690eace93ccf72f3f071a9ac0d5102e61df2f5fc/source/locales/en.json#L121

[0]: https://addons.mozilla.org/en-US/firefox/addon/ghostery/privacy/

Also you can check out following links. 

http://lifehacker.com/ad-blocking-extension-ghostery-actually-sells-data-to-a-514417864
http://www.businessinsider.com/evidon-sells-ghostery-data-to-advertisers-2013-6
http://venturebeat.com/2012/07/31/ghostery-a-web-tracking-blocker-that-actually-helps-the-ad-industry/
http://www.technologyreview.com/news/516156/a-popular-ad-blocker-also-helps-the-ad-industry/

**Comment by hasufell** [comment]
I don't think we should remove it. We should move it to the *Proprietary* section instead where it belongs.

**Comment by esponapule** [comment]
agreed, move it to the Proprietary section.

**Comment by nodiscc** [comment]
Ghostery is also not Free/Libre Software: https://addons.mozilla.org/en-US/firefox/addon/ghostery/license/5.4.1

**Comment by Zegnat** [comment]
As of 6095a596d9db5fa3549188018e24f0781205adfb Ghostery has been moved to the proprietary column and been removed from the notes. Previously it was recommended as back-up because they were pretty lax with their source, more in a [source-available](https://en.wikipedia.org/wiki/Open-source_software#Open-source_vs._source-available) sort of way. But as of now I can’t find anything about their source or their blocking database on the website so that argument is moot.
