### ISSUE TITLE
Firefox is planning to curb user freedom regarding add-ons.

### ISSUE THREAD

**Issue by vyp** [nylira/prism-break#1235]
http://blog.rubbingalcoholic.com/post/110743007958/mozillas-mandatory-add-on-review-considered

> Yesterday Mozilla announced they will soon require all Firefox add-ons to go through AMO review and code signing, even self-hosted add-ons outside of Mozilla’s Add-ons site. Mozilla reasons that this change will improve the security and performance of Firefox add-ons, and prevent malicious add-ons from being distributed. Unfortunately, mandatory review does nothing to address the underlying security problems that plague add-ons in the Firefox browser; it needlessly inconveniences (and possibly endangers) both developers and users, and ultimately violates the core principles set forth in the Mozilla manifesto and the definition of Free Software.

So because it "violates the core principles set forth in [...] the definition of Free Software", and because prism break is about listing free software alternatives to proprietary software, should firefox be removed when/if this happens? Or should it stay, because this ultimately this increases security (or does it?), even though it impedes on freedom, and prism break is about improving your software security? 

Is this even an issue, does it really impede on freedom? (I think so, but do others have opposing views as to why not?)

I think we should start discussion at least, or is this irrelevant/not of concern for now?

**Comment by vyp** [comment]
https://www.reddit.com/r/linux/comments/2vkrvv/mozillas_mandatory_addon_review_considered/coipeub

Relevant because, although sandboxed, the drm module (eme) is still a proprietary black box, and hence still a massive risk to security, and this change may be facilitating that form of malicious control.

Of course, firefox is still "open source", meaning one can hack away around this. But even then, this issue is about the official firefox itself, and whether we should remove it, since it's already there. (If a fork does appear, great, we could add it to the site.)

**Comment by Zegnat** [comment]
Interesting (and weird) step for Mozilla to take. Note that I think he is stretching it very thin when saying that this violates any Free Software principles. There is no rule that software needs to offer a way to be extendible. Being open-source takes care of that. If Mozilla wants to screen add-ons before publishing them they aren’t violating anything, I can still take the source and make my modifications straight to it.

This will harm users though. The blog post writes Mozilla will give no option to install add-ons that aren’t signed, not even Apple’s GateKeeper on Mac OS X does that.

I am a little split on the DRM discussion. On one hand I have nothing against DRM because software developers should have the freedom to implement whatever they want, be it encryption protocols to keep the government out or protocols to keep a viewer out of the raw video stream. On the other hand having proprietary blobs injected into software I use because some corporation X demands it there to offer me their services… that’s just weird.

Note that I am not on-top of the news around their DRM implementation, but how I understood it the EME implementation is basically just a spec’ed version of NPAPI. Basically an API for other parties to drop plugins into. The actual binary blob that handles the DRM was to be shipped by Adobe, separate from Firefox core. This meant that Firefox itself could stay 100% open-source and free software. (This may or may not have changed since [the original blog post](https://hacks.mozilla.org/2014/05/reconciling-mozillas-mission-and-w3c-eme/).)

Maybe @hasufell can link us to a page about how a source distribution like Gentoo will be handling this.

Also, do we know what the Tor project is going to do about this in their fork?

If Mozilla pushes this through it might be time to reconsider recommending Firefox. This will probably mean switching to one of the forks by a strictly free OS.

**Comment by vyp** [comment]
> Interesting (and weird) step for Mozilla to take. Note that I think he is stretching it very thin when saying that this violates any Free Software principles. There is no rule that software needs to offer a way to be extendible. Being open-source takes care of that. If Mozilla wants to screen add-ons before publishing them they aren’t violating anything, I can still take the source and make my modifications straight to it.

This is a good point.

> I am a little split on the DRM discussion. On one hand I have nothing against DRM because software developers should have the freedom to implement whatever they want, be it encryption protocols to keep the government out or protocols to keep a viewer out of the raw video stream. On the other hand having proprietary blobs injected into software I use because some corporation X demands it there to offer me their services… that’s just weird.

I guess you could make a similar statement to the issue at hand about mozilla "curbing" user freedom for firefox addons. Firefox is still "open source", but this is sort of like what rms would call an "anti-feature". Although a drm implementatino can still be free software, it's still drm.

I agree though that the definition of free software should not attempt to rule what people can or cannot do with free software, because it could easily be manipulated or twisted in a legal context to prevent people from adding legitimate functionality to their software, if not now, then maybe in the future, which might be quite different than we are familiar with today.

> (This may or may not have changed since the original blog post.)

Last I checked, it hasn't. Although last I checked would be a couple of months ago.

> Also, do we know what the Tor project is going to do about this in their fork?

There hasn't been any official annoucement, at least for now. However doesn't the tor project already strongly discourage the use of *any* addons when using the tor browser bundle? Because if that's the case, I can understandably see them continue to use mozilla's official firefox as their base for the tbb.

**Comment by vyp** [comment]
Also, I can't imagine such a massive change just gets decided on a whim, and Mozilla just announces it one day on their addons blog... and yet, this is the first I'm hearing about it thanks to someone who made a blog post about what this is really about.

Does anyone know if this 'decision process' is available to read in public on the interent somewhere? Or maybe places for where to look, if they do make these decisions in public? I made a brief attempt of a search through bugzilla but either that wasn't good enough (which is likely), but I think more likely is that this sort of thing would not be the right place to discuss on bugzilla (being an issue tracker)?

**Comment by nodiscc** [comment]
This is disappointing news (Mozilla requiring extensions to be signed with _only_ their own certificate), but I guess prism-break should wait. It's not in FF yet, and there's still a possibility of Mozilla backpedalling on this. There's also a good chance that Linux distributions maintainers will patch this out (so this restriction would only really aply to Windows users). Note that this change may contradict point 5. on https://www.mozilla.org/en-US/about/manifesto/

Other comments on https://www.reddit.com/r/linux/comments/2vkrvv/mozillas_mandatory_addon_review_considered/ are also interesting. Official discussion channels are comments on https://blog.mozilla.org/addons/2015/02/10/extension-signing-safer-experience/ and https://groups.google.com/forum/#!forum/mozilla.addons.user-experience.

**Comment by vyp** [comment]
> There's also a good chance that Linux distributions maintainers will patch this out (so this restriction would only really aply to Windows users).

Well even then, we'll have to consider removing firefox as a recommendation for windows users at least. However, while I think there could a good chance that debian patches this, some distributions may not have the resources to be patching firefox. And some distributions, like arch, also have policies to specifically *not* patch packages (keeping it 'vanilla').

Also, Jeff Lyon (@rubbingalcoholic), who wrote the original blog post I linked to in the op, has just recently posted a proposal to opt out from this: https://groups.google.com/forum/#!topic/mozilla.addons.user-experience/rO5jUfqsh-E. I think the proposal solves this issue, but do you guys see anything wrong with it?

I still think this a tough decision though, because this will still most likely 'improve' web security for the average firefox user, and prism break is all about that, and yet, I'm arguing it should be removed (if mozilla decides to go ahead with this). As in, I'm expecting at least some will argue that security is more important than freedom in this case, and hence firefox should not be removed. But on the other hand, @Zegnat outlines why freedom is also important in software security in #833:

- https://github.com/nylira/prism-break/issues/883#issuecomment-36020944
- https://github.com/nylira/prism-break/issues/883#issuecomment-36038985
- https://github.com/nylira/prism-break/issues/883#issuecomment-36124079
- https://github.com/nylira/prism-break/issues/883#issuecomment-36136391

which I think should be considered too. Although, as @Zegnat says, firefox is still free software, and there's no free software requirement for needing to offer *technical features* (extensibility in this case), I still think many of the points raised in those comments can be applied here. (Because remember, prism break also has a web browser addons section: https://prism-break.org/en/all/#web-browser-addons.)

**Comment by rubbingalcoholic** [comment]
@vyp My proposal is basically DRM to opt-out from worse DRM. Mozilla is still playing gatekeeper, in a way. I feel in my heart like it's an acceptable compromise, but I would understand if others disagree.

**Comment by vyp** [comment]
> My proposal is basically DRM [...]

It might be, but the user *can* still be control no? That is why this I created the issue, because if one central authority has the final say on what you can run (ironically, as an 'extension' software on that same authority's program), then it's not freedom, which *can* (easily) have consequences for security. At least, it's not freedom for that 'part' of the program anyway. But, as demonstrated by the existence of the web-browser-addons section on prism break, that part of the program can also be useful/important in its security.

I agree that it's not ideal, but at least with the proposal, users can run their own addons even if mozilla says no, which is not the case currently as long as this goes through.

**Comment by strugee** [comment]
> Does anyone know if this 'decision process' is available to read in public on the internet somewhere? Or maybe places for where to look, if they do make these decisions in public? I made a brief attempt of a search through bugzilla but either that wasn't good enough (which is likely), but I think more likely is that this sort of thing would not be the right place to discuss on bugzilla (being an issue tracker)?

These kinds of decisions get made on mailing lists at lists.mozilla.org and mail.mozilla.org (these are split across domains for technical reasons).

Also, I'd just like to point out that we trust Mozilla a hell of a lot more than many other organizations. E.g. Apple has a similar system with Gatekeeper, but I'd trust them way, way less than Mozilla to do the Right Thing™ and let stuff through. I'm not saying that this is a reason to drop the issue, I'm just saying that we should keep it in mind.

**Comment by vyp** [comment]
Oh I forgot to mention, Jorge Villalobos (@jvillalobos), the one who posted the firefox addons blogs post, has actually mentioned that he's not completely opposed to the idea of *somehow* having this as a user config option, even though it currently seems as though he does not. He says this in one of the more recent google group threads (which @nodiscc linked to) about extension signing. It seems as though the decision isn't final yet and there could still be more official discussion (he said something about bringing that point up the next time they "meet at the table", if I remember correctly).

I also forgot to include the fact that he also says there's a **third** way to install addons (in an official build) without requiring signing. But for whatever reason, that has not been mentioned yet, but will be disclosed in the near future (apparently), so that could also be the answer here.

@strugee I agree, of course. Mozilla has given so much to the world... However, with gatekeeper, you can still install unsigned apps (and of course, this is what this whole issue is about):

> If an app is unsigned, Gatekeeper blocks the app from being installed and warns you that it did not come from an identified developer. If you’re sure the app is safe, you can manually override Gatekeeper by Control-clicking the app and choosing to open it.

From: https://www.apple.com/au/osx/what-is/security/ under the gatekeeper section.

**Comment by Zegnat** [comment]
@vyp: wow, who knew I’ve said so many smart things on previous issues discussing Free Software definitions. Hahaha!

I have once again updated the title to make it clear that this is not something that is currently implemented in Firefox.

Chrome has previously implemented something like this, where they only allowed extensions to install from the Play Store. But that was easily circumvented by users, simply dragging a downloaded extension to Chrome would install it. As long as something equally simple becomes available for Firefox I don’t think there will be major problems either way.

> However doesn't the tor project already strongly discourage the use of any addons when using the tor browser bundle?

On some level, so does PRISM Break. Any add-on that isn’t vetted and doesn’t have its source code publicly available is simply not safe to give as much control as a Firefox add-on has. PRISM Break recommends a small number of add-ons that are considered safe to use, if you use any additional add-ons it will be hard to guarantee you get the same level of anonymity. (Maybe we should add some warning about that as a note…)

**Comment by vyp** [comment]
Bringing up chrome is a good idea, I was going to ask about chrome too but looks like that's another thing I forgot. What does chrome do regarding this? Isn't it the case that every extension has to be installed through the chrome store? But, I think you can also enable a chrome flag to bypass this? I tried to search, but I can't find anything about my last question. (I'm not that familiar with chrome/chromium since I don't use it.)

When you say dragging onto chrome, is that an official method? (I guess it must be, since it would be easy to prevent.)

> if you use any additional add-ons it will be hard to guarantee you get the same level of anonymity. (Maybe we should add some warning about that as a note…)

I agree about the warning note, considering that addons are not sandboxed (and supposedly have full permissions/privelages?). Especially since prism break only lists security-related addons, whereas the average firefox user (or at least a significant minority) will probably look to install all kinds of other types of addons (mozilla promotes it too).

**Comment by rubbingalcoholic** [comment]
@vyp (sorry I'm kind of lurking on this discussion since you mentioned me :) you can manually install unsigned Chrome extensions by dragging and dropping their .crx files into the Chrome extensions list. You can also enable "developer mode" (a checkbox on that same screen), which allows you to load an unbundled extension directly off your hard drive.

One thing worth mentioning is, due to the sandboxing concerns I brought up, it's dangerous to run anonymity add-ons like Cryptocat or Mailvelope in FIrefox _if you have other add-ons installed._ The AMO review process is not as stringent compared to the penetration testing and code review the main browser gets, and malicious add-ons (carefully packaged to look mundane) can steal crypto keys or spy on privacy add-ons. I believe Mozilla does not message this to users, and it's a grave concern to users who value privacy. Security / privacy add-ons should have a special warning on them.

@zegnat I've been thinking on your comment that I was stretching pretty thin on the definition of Free Software, and I think you're correct and I may be mistaken, at least by "the letter of the law." I was referring to [the definition of Free Software](https://www.gnu.org/philosophy/free-sw.html) on GNU's site. Namely: `The freedom to run the program as you wish, for any purpose (freedom 0).`

I think it boils down more to "the spirit of the law" and a philosophical discussion. They elaborate: 

> The freedom to run the program as you wish means that you are not forbidden or stopped from doing so. It has nothing to do with what functionality the program has, or whether it is useful for what you want to do.

In particular, the program is not forbidden from offering an extension mechanism and locking down what extensions can run on it. However, is this really in keeping with the intent of Free Software? They also say:

> The freedom to run the program means the freedom for any kind of person or organization to use it on any kind of computer system, for any kind of overall job and purpose, without being required to communicate about it with the developer or any other specific entity. In this freedom, it is the user's purpose that matters, not the developer's purpose; you as a user are free to run the program for your purposes...

This certainly confounds the issue. By employing a DRM mechanism, you are forced to communicate about your use of the program to the developer. And for the developer to restrict what functionality the program offers, based upon your communication with them, they are enforcing their own purpose, not your purpose, upon your use of the program.

Maybe a good analogy would be an open source operating system called DRMos that, as packaged, only allows for the execution of signed code. The developers could say that because it's open source, and a compiler flag exists to build it without DRM, that it's still Free Software. But I think a lot of people would say that, as packaged, it is not free. Only by compiling it yourself can it be free.

I liken Firefox to an operating system, because that's what it is. Environments like Firefox OS and Chrome OS prove that the web really is becoming a pervasive system for not only providing access to information, but for applications and code execution. By providing the capability of executing code (add-ons), is it reasonable to expect them to inherit Freedom 0 and apply Free Software principles to that capability?

Do you think it would be worth asking Free Software Foundation for clarification on this confusion?

**Comment by strugee** [comment]
> (I think gatekeeper, and mac os x in general, is still proprietary though am I right?

Yes.

As I said above, I'm not claiming that that's the be-all, end-all of this discussion.

**Comment by strugee** [comment]
> I agree about the warning note, considering that addons are not sandboxed (and supposedly have full permissions/privelages?).

Yes, addons in Firefox execute with chrome privileges, which basically means that there's no distinction between addon code and browser code. They both have the same privileges and execute in the same context.

**Comment by vyp** [comment]
Here's a fairly obvious argument for *keeping* firefox which I just thought of. What about the user who just uses firefox with only addons that are approved by Mozilla (and who doesn't develop addons herself)? Obviously, the fact that Mozilla has such power is wrong, but is that a problem for this user? The only thing it changes for the user is improved security, no?

Also, judging by the comments in the mailing lists, this change seems to be mainly for protecting windows users only (a windows specific issue), but is that the case? I can understand why it's more significant for windows users, but does it mean gnu linux is at no risk of malicious addons right now (before the mandatory extension signing)?

**Comment by vyp** [comment]
> By providing the capability of executing code (add-ons), is it reasonable to expect them to inherit Freedom 0 and apply Free Software principles to that capability?

I agree with in that firefox (or browsers of today in general) are *like* an 'operating system' because they have to handle so many things and provide so much functionality. But free software with drm is still free software imo. You brought up freedom 0, but I think it's important to note firefox addons are not exactly part of the original program itself, so I don't think using drm to block addon use in some cases would stop making it free software.

I did say "it's not freedom for that 'part' of the program" above, and I still stand by it because the web browser addons section of the site I feel is important, but firefox could just have easily decided to never include addon functionality in the first place anyway.

> Do you think it would be worth asking Free Software Foundation for clarification on this confusion?

IANAL, so if you want to, go ahead. Maybe my reasoning might be flawed, or there's something I missed, so clarification would probably help.

**Comment by Zegnat** [comment]
@rubbingalcoholic, you are welcome to lurk, we are going a bit off-topic anyway. It may be worth asking the FSF for a comment, but I think I might be able to point you at some counter points they have already written.

The FSF has already made your Freedom 0 argument moot, I am afraid. The Free Software Definition was especially updated to elaborate on Freedom 0 in version 1.134 ([`diff`](http://web.cvs.savannah.gnu.org/viewvc/www/philosophy/free-sw.html?root=www&r1=1.133&r2=1.134)), emphasis mine:

> The freedom to run the program as you wish means that you are not forbidden or stopped from doing so. **It has nothing to do with what functionality the program has**, or whether it is useful for what you want to do.

If we accept GPL as a guideline to what FSF defines as the obligations of Free Software, and accept Stallman’s interpretations in non-legalese (that is a language, right?), there is another article outlining how any vendor is free to add or remove features including DRM. From [Why Upgrade to GPLv3](https://www.gnu.org/licenses/rms-why-gplv3.html), again emphasis mine:

> GPLv3 ensures you are free to remove the handcuffs. It doesn’t forbid DRM, or any kind of feature. It places **no limits on the substantive functionality you can add to a program, or remove from it**. Rather, it makes sure that you are just as free to remove nasty features as the distributor of your copy was to add them.

There is also a bit of a problem with how you would phrase the question if you want them to clarify the confusion. It would probably go something like this:

> Is an author [Mozilla] allowed to limit the use [by requiring their involvement] of a feature [add-ons] when doing so would make it harder for the user to run the Program [Firefox] the way they were used to?

If you were to ask me this question my answer would be yes. Why wouldn’t I, the author, be allowed to switch a feature to be disabled by default? Or only have it behind a command line flag? (Ever tried explaining Firefox’s `-ProfileManager` to a non-techie?) Or only trigger after you enter the Konami code?

Neither is Mozilla placing any burden on people who want to modify Firefox. The licence isn’t changing. They are only making it harder to modify Firefox by proxy, making it harder only to use add-ons to modify the way Firefox works. We would hardly argue them becoming less-Free Software if they were to create a new sandboxed add-on API, even though it would definitely break add-ons and give you less control over the browser’s internal workings.

Loads of interesting points being raised here regarding Free Software and people’s perception thereof :smile:

**Comment by hasufell** [comment]
> can link us to a page about how a source distribution like Gentoo will be handling this

I expect this will be a configure switch. If not, it can probably be made one. And in that case, users will be able to choose whether they want it or not. I don't expect that this will require a real fork.

**Comment by Zegnat** [comment]
According to [Paul Ducklin over at the Naked Security blog](https://nakedsecurity.sophos.com/2015/02/17/firefox-to-get-a-walled-garden-for-browser-extensions-mozilla-to-be-sole-arbiter/):

> In fact, Mozilla says that there will be no way, neither via command line nor through configuration options, to suppress signature checking.

**Comment by vyp** [comment]
There's still a bit of discussion going on but unfortunately it seems as though this is going to happen: https://groups.google.com/d/msg/mozilla.addons.user-experience/slaKs943n4c/pN8Fn7Biac8J. I.e. some bs like: "It doesn't matter what you propose, we don't care about your freedom (or even convenience for that matter), we're going to do this even if it doesn't help security that much."

So what should prism break do? Remove firefox completely? Recommend an unbranded version of firefox (which supposedly would not have these restrictions) instead? Keep firefox but have a warning about this? Some combination of those, or neither of those?

Imo, I'm not *so sure* yet (even though I created the issue), but I'm leaning towards keep firefox but have a warning because of what @Zegnat said above:

> On some level, so does PRISM Break. Any add-on that isn’t vetted and doesn’t have its source code publicly available is simply not safe to give as much control as a Firefox add-on has. PRISM Break recommends a small number of add-ons that are considered safe to use, if you use any additional add-ons it will be hard to guarantee you get the same level of anonymity. (Maybe we should add some warning about that as a note…)

Don't get me wrong though, I am very much **hating** mozilla for this, but that might not be so relevant to prism break.

**Comment by wifiextender** [comment]
@vyp https://www.gnu.org/software/gnuzilla/

**Comment by hasufell** [comment]
> You are wrong about the patching

No. He is correct.

It's about _distribution policies_, not about whether it is possible to patch things or whether there are trivial patches somewhere (which will always be needed). It's about reporting bugs upstream and not just randomly patching things downstream like debian.

**Comment by vyp** [comment]
@wifiextender Sorry I didn't see the edit. Of course it's possible to use the ABS to patch it yourself, but that's besides the point. (And in any case, anyone on any system should be able to build their own firefox if they wish.) The majority of our audience however will probably not do that though (even if they are to become Arch users). And so I meant, because of [arch's philosophy](https://wiki.archlinux.org/index.php/The_Arch_Way#Simplicity), most Arch users will likely get something similar to the official Firefox from Mozilla. It would take an unofficial Firefox fork (or more likely a maintained patched version) to get something else for most users on such distros.

The issue isn't verifying a compiled program either. That's a very valid issue of course (and a lot of work is being done on that over [at Debian](https://wiki.debian.org/ReproducibleBuilds)), but point was that most users will end up using the Firefox package from the main (Arch) repos. Or any other distro that will not patch Firefox for that matter.

(Does anyone know if anyone from Debian has said anything about this? I haven't found anything other than [this](http://comments.gmane.org/gmane.linux.debian.devel.mozilla/20232) and [this](http://forums.debian.net/viewtopic.php?f=20&t=120409).)

With regards to prism break however. The logic I currently see is that, assuming a user only uses addons as recommended by prism break, and assuming these addons are signed (so that they can be installed as Mozilla now requires), does this actually change anything for the worse (related to security) for this user? Because if not, why remove Firefox from the list, right?

Was that the right question to ask? How many addons do you guys use that's not listed on prism break, if you use Firefox (and if you're willing to say of course)? I know I use 2 which are not listed.

**Comment by wifiextender** [comment]
The binary packages that are distributed are (mostly) patched, [ABS] (https://wiki.archlinux.org/index.php/Arch_Build_System) is not just for the end users.

This is not Debian where the packages are well tested and delayed with 4+ months and patched multiple times. In arch you'll get the latest software in matter of minutes when new version is released, that is why arch is NOT recommended as production/server distro, because all the bugs that the newer software is released with aren't yet reported.

I used to be Chromium user right in the years when chrome store was distributing malware applications and I remember that they banned all ad blockers for almost whole year, their explanation was kinda silly that the ad blockers was breaking their browser or something like that, and it seems they are doing it [again] (http://techcrunch.com/2013/03/14/adblock-plusresponds-to-google-play-bar/). And it seems their malware scanning software isn't yet capable to combat the malware distribution in their own store either.

Why the self-signing 'feature' in firefox won't work. Because black-hat guy or spyware can steal the addon developer signature and distribute infected addons, representing the infected addons as 'genuine'. At the end the infected users will blame the real addon developer that he/she/it was the reason that caused their pc to be infected, which will put the addon developer off from further development and distribution - long story short, ruined career.
