### ISSUE TITLE
[Password Managers] KeePassX

### ISSUE THREAD

**Issue by kafran** [nylira/prism-break#1237]
[**KeePassX**](https://www.keepassx.org) by the [KeePassX Team](http://sourceforge.net/p/keepassx/_members/)

* [Source](https://github.com/keepassx/keepassx)
* [GPLv2 or GPLv3](https://github.com/keepassx/keepassx/blob/master/COPYING)

---

KeePassX for password manager.

**Comment by Serpens** [comment]
KeePass should also be mentioned, as it is licensed under GNU GPL. I'm not sure about plugins, they look like they can have any license.

**Comment by Zegnat** [comment]
This seems to be a very popular password manager, and has been discussed a couple of times. See #1036 and #1046. (#520 is older and closed but also contains some discussion w.r.t. KeePass and KeePassX.)

For PRISM Breaks quality over quantity policy I would rather only merge a pull request for either KeePass or KeePassX, not both. Though I’m not sure which one would be preferred.

**Comment by nylira** [comment]
I suggest KeePassX over KeePass. X officially supports far more platforms.

On Sat, Feb 21, 2015 at 11:02 PM, Martijn van der Ven <
notifications@github.com> wrote:

> This seems to be a very popular password manager, and has been discussed a
> couple of times. See #1036
> <https://github.com/nylira/prism-break/issues/1036> and #1046
> <https://github.com/nylira/prism-break/issues/1046>. (#520
> <https://github.com/nylira/prism-break/issues/520> is older and closed
> but also contains some discussion w.r.t. KeePass and KeePassX.)
>
> For PRISM Breaks quality over quantity policy I would rather only merge a
> pull request for either KeePass or KeePassX, not both. Though I’m not sure
> which one would be preferred.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nylira/prism-break/issues/1237#issuecomment-75375311>.
>



-- 
Peng Zhong

Interface Designer
http://nylira.com

**Comment by alerque** [comment]
I would also say KeePassX is the one too add, but the project is suffering from a languishing development cycle. I have [adamantly defended the recommendation of it even with the alpha label](http://softwarerecs.stackexchange.com/a/1311/429) but the situation is getting worse, not better. More Alphas have been released, but not quickly and issues are starting to pile up in the bug tracker. Code contributions that are broadly supported by users or necessary to compile against modern libraries are languishing. There have been multiple suggestions of an fork since the developer is so slow to respond, but nothing has gotten organized.

Of the two options I do think KeePassX is the one I would recommend over KeePass (especially on Linux) but I'm also not in a crazy hurry to see Alpha versions being listed here. And in case you ask, I don't think recommending the previous stable version is much of a solution as it's very dated and of limited use. People getting started with a password manager should no be encouraged to paint themselves into a corner out of the gate.

**Comment by kafran** [comment]
Do you know an other password manager? I like KeePassX because the database, others software support it, even on smartphone. I got the habit to generate my password through the password manager. I don't even know my passwords anymore >.< so I need mobile support to have my bank account password in the pocket when I need to withdraw money rsrsrsrs.

**Comment by annonman** [comment]
I'm a big fan of KeepassX.  Offers several Linux Ports.

**Comment by RanceJustice** [comment]
I think the best option here would be to suggest KeePass 2.x (ie the version found at keepass.info) for Win/OSX/Linux, and KeePass2Android on AndroidOS. There can be a note in the category contents mentioning KeePassX if necessar, but I don't think it should be the primary focus for a number of reasons.

KeePassX was originally developed to provide compatibility with the KeePass 1.x series. If a user goes to KeePassX and downloads the latest non-Alpha version, they will be limited to only using 1.x series databases and features. Now, this did start to change with the slow development of KeePassX 2.0 Alpha series, having finally provided early support for the modern database function, but it seems cumbersome to have to explain this all to users through suggestions.  Even users of the Alpha, slower to develop though it may be, will have a limited suite of features compared to the KeePass 2.x branch.  

Overall, I feel that the KeePass 2.x branch (www.keepass.info) is the best option. It is updated with some regularity and is probably the most full-featured FLOSS password manager around. GPL licensed, it is cross platform  and easy to install. Most Linux distributions have a version ready in their repositories as well.  The KeePass 2.x branch uses the modern .kdbx  format, which has a number of benefits and better compatibility than the old 1.x .kdb database, which is what the release versions of KeePassX support alone.   The keepass.info website has comprehensive help and info, including comparisons between  the 1.x branch and 2.x branch, and even lists third party tools (including a link to KeePassX).  It really goes above and beyond to explain many features, how  they provide additional security.    KeePass is known for its comprehensive plug-in architecture, which can lead to all sorts of new functionality that will increase privacy and security.    Furthermore, it is simply easier to explain to users, regardless of (desktop) OS, to simply download the latest KeePass 2.x or later version, rather than having to explain all the differences between KeepassX's  Release vs Alpha, how that can interface with databases belonging to KeePass 1.x or 2.x etc.   

In the past I've seen some objections to Keepass  over the use of .NET/Mono in the 2.x branch and a development process that may not be as open as some would like. However, these seem to be philosophical differences not pure security issues, and thus have the potential to undermine Prism-Break's mission as I understand it. This is a clear case of "Perfect is the enemy of good".   I don't see Mono as an issue  - even prior to .NET being open sourced, KeePass was tested and meant to work with Mono itself, which is a FLOSS implementation and a a library that is included even in Gnome.   The main developers, may not have a public GIT or whatnot, but  the license is GPL and all the code is provided, along with multiple hashes/pgp keys etc.. for your confirmation. 

As I understanding it, Prism Break's mission is to make users aware of more privacy and security conscious software choices.  Looking over the tracker, sometimes I've gotten the feeling that there are some who are focusing so much on the ideal,  philosophical and otherwise (or more outlandish hypotheticals than most users are going to come in contact regarding), that it undermines providing good, USABLE alternatives to the most common "bad" software.   For instance, I've seen some who suggest "Anyone who is using Windows or OSX just don't care about security/privacy. They're compromised, the NSA has all your data. So what's the point of suggesting any programs that run on Windows/OSX"     Would it be best if all users used a FLOSS operating system, in terms of privacy/security? Sure.  However, this isn't realistic and it doesn't mean that they couldn't make better choices for their software that would still help.   Not everyone is going up against a state-level actor that is specifically targeting them;  there are plenty of helpful changes a user can make that aren't going to dissuade the NSA TAO,but will keep corporate interests from mining more data  about them, impeding blackhats,  as well as counteracting dragnet surveillance.       Many of us are long time FLOSS users, and  we've seen time and time again that expecting most users to give up many features, ease of use etc... and transition to something obtuse, simply because it is more libre/open/private/secure, doesn't work well.    Greatest successes are those like Firefox, who bring functionality and ease of use alongside these benefits.    Today we have more opportunities than ever to help users transition to a better class of products, but  we cannot do so by being closed minded or nitpicking insisting on an all-or-nothing approach.   Having some core baselines are great (ie We only suggest Free and Open Source software, for obvious reasons), but if pressed to hardlines (such as objecting to linux distros that allow the option of non-free software, even though these typically have more features/support especially for drivers etc.. something more philosophical than truly a real security issue. Is it possible that binary blob is a vulnerability? Sure, but its up to the user to enable support for it and decide for themselves to take that risk...which ultimately ends up to being a relatively low one, most of the time) that's doing more damage than good.   Ultimately, we shouldn't let perfection, philosophical or otherwise be an impediment  toward  improvement. 

So yes... having made use of varying KeePass  family options over the years on different OSes (Win, Linux, Android),  I think that suggesting KeePass 2.x+ should be the prime focal point for desktop users - it offers more and better features and less confusion over versions, alphas etc...than KeePassX.    For Android, I suggest "Keepass2Android".  It is FOSS unlike some other apps, and supports the widest range of features including 2.x style databases . For those who don't want to get it via GooglePlay, the author has a development homepage - https://keepass2android.codeplex.com/  as well, for your sideloading pleasure.     I don't have any experience with iOS,  but perhaps one of the builds listed on the KeePass download page could provide a similar experience to KeePass2Android in terms of being FOSS, .kdbx compatible, and having similar features - but I'll leave that to someone who spends time on Apple platforms.   So yes, ultimately I think KeePass should have a place here on PrismBreak as it has the potential to protect privacy and security, while allowing a comfort level/usability that will encourage adopting better practices.
