### ISSUE TITLE
[Password Managers] Master Password

### ISSUE THREAD

**Issue by Dovaa** [nylira/prism-break#1238]
[**Master Password**](http://masterpasswordapp.com/) by [Lyndir](http://lyndir.com/) (Maarten Billemont)
- [Source](https://github.com/Lyndir/MasterPassword)
- [GPLv3](https://github.com/Lyndir/MasterPassword/blob/master/LICENSE)

---

just that, is like a password manager but not at all
[http://masterpasswordapp.com/](http://masterpasswordapp.com/)

**Comment by Zegnat** [comment]
These have been around for a long time, I remember using [PasswordMaker](http://passwordmaker.org) back in the day. But I always found usability to be a bit poor. Maybe this app will change that, do you have any experience using it?

**Comment by vyp** [comment]
I apologise for being off-topic, but I think this is the first time I'm reading about this method (believe it or not). Which got me curious, why haven't I heard of this before, are there any 'gotchas' or other 'catches' with this method that's not being mentioned? As in, why isn't this more popular? @Zegnat do you still use something like this, or if not, why did you switch away?

**Comment by Zegnat** [comment]
As I stated, I always found usability a problem with these tools. Even with ones like PasswordMaker that integrate relatively well with browsers. That is probably why they haven’t been able to catch on with the greater public. Because these tools do not keep any information stored locally automatically filling in forms or keeping usernames associated with passwords is out of the question for them.

I am currently using a password “vault” because:

1. It stores more than just passwords. I use it to store security question answers and email addresses belonging to the accounts as well. And most importantly: to store usernames that go with the passwords.
2. I have it set up to give me actual random (or as random as possible) 50 symbols long passwords.

---

The “gotcha” is that passwords are not random. They are created by an algorithm. In most (all?) cases they use one-way hash functions to generate a password that looks like gibberish but is based on the input string consisting of your ‘master password’ and an account/site identifier.

In the simplest example, with the master password `password` my GitHub password would be:

```
   md5 ( master + identifier )
== md5 ( "password" + "github.com" )
== a549e4c1d822d8044b655359d0e0b39f
```

Of course the algorithms will take the raw bytes output from the hashing function and transform it into a string that incorporates symbols etc. to protect from other and simpler password cracking.

Because passwords aren’t randomly generated, once I obtain your master password I can generate all the passwords you have generated (or will generate in the future). If the algorithm truly was just an md5 product, someone who obtains my GitHub password could look for `master` in `md5 ( master + "github.com" )` and when they find it automatically generate passwords for all other sites I visit.

Master Password seems to be using HMAC-SHA-256 in the following way (this is from reading [their spec](http://masterpasswordapp.com/algorithm.html), I haven’t inspected their code):

```
   hmac-sha256 ( master, "com.lyndir.masterpassword" + identifier length + identifier + counter )
== hmac-sha256 ( "password", "com.lyndir.masterpassword" + "10" + "github.com" + "1" )
== d5f6b38c122d83be9611e6d870db2abacc02b1f3915d5796d189384fb941d6de
```

(Note that Master Password isn’t using my master password there, but an scrypt hash of my master password together with some other strings.)

**Comment by Dovaa** [comment]
oh thank you for add more info xP
I must confess that sometimes i forget my usernames, so i try to use the same user when i use this method :P

**Comment by vyp** [comment]
Wow thank you for the detailed response @Zegnat, much clearer now! I don't think it can be truly random can it, because then you wouldn't be able to generate the same password a second time right?

**Comment by alerque** [comment]
For discussion cross reference purposes, [I previously commented on deterministic password management schemes here](https://github.com/nylira/prism-break/issues/1623#issuecomment-264387768).
