### ISSUE TITLE
Add Peerio

### ISSUE THREAD

**Issue by jzakiya** [nylira/prism-break#1243]
From the creator of Cryptocat and MiniLock comes now Peerio.

Beta, but Open Source Software and security audited. 

https://www.peerio.com/

**Comment by annonman** [comment]
I believe Peerio shows promise.  But as it is still in beta, I say it needs time to mature.

**Comment by jzakiya** [comment]
I see you list Tox, which is also beta, which you do list, as experimental.

I just learned about Peerio through an email I received a couple of days
ago, inviting me to a technical discussion Happy Hour this Wednesday (March
11) sponsored by Peerio, here where I live. I started looking into it and
it does seem promising, on its face.

The most important thing going for it, from my perspective, is its
creator's pedigree, of Cryptocat (which I use) and miniLock.  He has a
track record of conforming to the philosophy of open source software, has
used that to accept and correct mistakes in Crypotocat, and submits his
code for security audits (which has passed).

I've installed the Peerio beta for Chrome, but haven't had a chance to play
with it yet.

But I'm definitely going to keep an eye on it and think prism-break should
too.
I thought maybe a listing, with similar caveats to Tox, would be
appropriate.

Jabari

**Comment by nodiscc** [comment]
Don't mean to interfere, but

1. Peerio is only available for proprietary OSs and browsers (windows, osx, chrome)
2. The claim of trusting the software because the lead dev has a good track record is not really appropriate since Cryptocat had huge gaping security flaws for years (it's the one discussed [here](https://news.ycombinator.com/item?id=7518761). The author had repeatedly claimed that his software could be used by people that expected strong privacy, which was pain wrong. Most of the flaws seem to be fixed by now, bu this argument doesn't hold.

The tech looks interesting but the absence of a GNU/Linux client is a no-go for me regarding inclusion in prism-break.

**Comment by vyp** [comment]
> I see you list Tox, which is also beta, which you do list, as experimental.

Tox was also initially rejected when first mentioned on prism break due to it's alpha status. But prism break did keep watch of it and finally added it nearly a year later once it became 'somewhat' mature, even though it was still experimental. (#466, #891) Personally, I would have still waited more, but I think there was high demand for skype replacement options.

My point is that Peerio is less than 2 months old (judging by the earliest commit on github), so prism break should *at the least*, wait for now, just to see it further develop. Probably for at least a month or two... do you disagree?

---

Also either way, I also completely agree with @nodiscc here. Maybe it's okay to list options for proprietary systems (although tbh I don't think that anymore either), but that should only be the case when those options are also available on the recommended free systems.

As an example, if prism break suggests moving away from Windows to GNU linux, but still recommends Windows only applications, not only does that create a double standard, but it gives Windows visitors a reason to *stay* on Windows, because switching to GNU linux will mean that appliation will not be available there. For that reason, it should be prism break's responsibility to make sure that all their recommended programs work on (at least one) recommended platform(s).

**Comment by jzakiya** [comment]
Actually Peerio runs in any Chrome family (Chromium, Slimjet, etc) browser,
so it runs on any Linux distro which includes them.  Like I said, I've
installed it within Slimjet (which I use over Chrome) but haven't gotten
around to playing with it yet.

I know Peerio is currently VERY young, but I just wanted to alert you to it
to track.
I also use Cryptocat, so I have a good feeling whenever it reaches 'stable'
it will have been sufficiently peer reviewed and audited, as has been done
with its creator's other projects.

Thanks,

**Comment by vyp** [comment]
> I know Peerio is currently VERY young, but I just wanted to alert you to it to track.

Well in that case I agree with that. However, chromium is explicity not recommended by prism break either. See #169. So @nodiscc's point still stands in my opinion.

**Comment by hasufell** [comment]
> Peerio is only available for proprietary OSs and browsers (windows, osx, chrome)

Agree, that's a no-go.

> The claim of trusting the software because the lead dev has a good track record is not really appropriate since Cryptocat had huge gaping security flaws for years (some of them discussed here, there and in many other places. any group chat message that has taken place using Cryptocat between September 2012 and April 19, 2013 can be decrypted). The author had repeatedly claimed that his software could be used by people that expected strong privacy, which was plain wrong. Most of the flaws seem to be fixed by now, but this argument doesn't hold.

I disagree partly. I can name a lot of applications and libraries everyone uses which either have never been properly audited or had security vulnerabilities for years (including xserver, zlib and libpng which are used by literally any linux distro... at least xserver got an audit a year ago or so, revealing security bugs that are 10+ years old).

Cryptocat upstream has reacted to the audits and that's the important part. And as such, it has gained trust in the opensource community.

In that sense.... a known author IS a plus. But it's not enough for an argument.

**Comment by jzakiya** [comment]
Just to be technically correct and accurate, Peerio does not run "only" run on proprietary browsers and OSs.

The Chromium Project is not proprietary, it is a long established Open Source Software project.
http://www.chromium.org/

Slimjet is based on the Chromium browser codebase.
http://www.slimjet.com/en/
http://www.slimjet.com/en/faq.php
http://www.slimjet.com/en/aboutus.htm

**Comment by mastercoms** [comment]
But Chromium is not accepted on prism break. We shouldn't recommend software that doesn't work on our recommended software,  If we recommend Peerio, and someone wants to use it, they will have to use Chromium instead of Firefox, which is recommended, and the user ends up with less security than before.

**Comment by Zegnat** [comment]
Chromium-based browsers have been discussed a couple of times here on PRISM Break. It is not rejected because it is a proprietary engine but because it was found lacking as a privacy tool. People wrote in showing how Chromium is “calling home” to Google servers to do several checks in the background (checking if you have an internet connection, checking if DNS is working properly, etc). As far as I know nobody around here has done a full go-through of the source code to see if any of those calls leak identifiable information, but until there is a clear answer to that PRISM Break will stay on the safe side and not recommend any Chromium-based browsers.

@jzakiya, if you have reason to believe Slimjet has forked Chromium/Blink and taken away all such calls in the background please do open a separate ticket for Slimjet pointing that out and it might become the first Chromium browser on PRISM Break. Their FAQ just says they run the ‘the same engine used by Google Chrome’ so I doubt that, which means Slimjet is making background connections to Google servers as well.

To clear up the beta argument: Tox was accepted not because it was watched for over a year and matured enough (though that was definitely part of it) but also because PRISM Break (that is, @nylira) approved the addition of an ‘Experimental’ tag. Now that there is a precedent for this tag other experimental but promising software can definitely be added without having to wait some arbitrary time period.

I am closing this issue, without cross-platform support outside of Blink/Chrome/-ium I don’t see how Peerio in its current state competes with other software already on the list.

**Comment by juanda-097** [comment]
Now peerio accept Linux, Mac android and iOS https://github.com/PeerioTechnologies/

_Enviado desde mi Motorola XT1650 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
