### ISSUE TITLE
[Mail Servers] Mail-in-a-Box

### ISSUE THREAD

**Issue by ceyhanmolla** [nylira/prism-break#1249]
Make deploying a good mail server easy.
Promote decentralization, innovation, and privacy on the web.
Have automated, auditable, and idempotent system configuration.
Not build a mail server that the NSA cannot hack.
Not make something endlessly customizable by power users.

Mail-in-a-Box is dedicated to the public domain using CC0.

https://mailinabox.email/

**Comment by Zegnat** [comment]
> Not be a mail server that the NSA cannot hack.

You may want to read that sentence again, as it runs with a double negative. What it is saying is that they are not trying to be NSA-proof at all. I am not saying this is a problem – many open-source solutions can counter the NSA by default – but it may become an issue down the line when Mail-in-a-Box is asked to implement security features.

On the other hand, it seems to be a perfectly fine base tool to use. Just as valid as the currently recommended solutions. Any server administrators want to comment on this?

**Comment by ceyhanmolla** [comment]
This project was inspired in part by the "NSA-proof your email in 2 hours" blog post by Drew Crawford, Sovereign by Alex Payne, and conversations with @shevski, @konklone, and @GregElin.

Mail-in-a-Box is similar to iRedMail and Modoboa.

Mail-in-a-Box is based on Postfix, Dovecot, Z-Push, Roundcube, ownCloud, Spamassassin, Postgrey, Nginx, @konklone’s nginx config, and more.

**Comment by Zegnat** [comment]
I know, I just read that myself :wink: My only gripe was with the double negative on the security front. I don’t understand why they felt that was a necessary goal to have.

PRISM Break recommends iRedMail, Postfix, etc. already. Mail-in-a-Box seems to be a “win” in that anybody should be able to set it up. But I’d still want some people more informed with server administration to comment on it.

**Comment by JoshData** [comment]
Hi, I'm the author of Mail-in-a-Box. Just to clarify, that bullet (not build... not...) was added because a lot of early criticism was that the box did not prevent every possible sort of potential attack (physical compromise, side-channel, traffic analysis, etc.). The goal with that statement was to clarify that success for the project is making a good system (secure, of course) not an impenetrable system (impossible), and that the threat models I'll consider will be balanced against other project goals.

Am happy to answer other questions. Thanks for considering adding the project.

**Comment by Zegnat** [comment]
Thanks for dropping in @JoshData! I realise we should get better at including project author’s, I should have directly aimed my questions at you rather than @ceyhanmolla.

I totally understand why you would add such a point to stop the constant criticisms on security. On the other hand, it is exactly what we are talking about here. I don’t think we require Riseup-in-a-Box (though I guess we would like to) for including a project here, but overall we do like some sort of stated security goal.

Most of us here agree that we are not trying to fight things like physical compromise. Not outside of “use full drive encryption”. And we definitely don’t expect an email solution we recommend to come with all that build-in.

If you have some time to spare, could you tell us how you think Mail-in-a-Box compares to [the email servers PRISM Break currently recommends](https://prism-break.org/en/subcategories/servers-mail-servers/)? E.g. are there certain security measure you take and they do not?

Like I stated earlier, I am not an active server administrator so I can’t honestly judge your product for inclusion. But we already have a baseline set in those products, and I would think Mail-in-a-Box certainly matches them in security? If it does I would be happy to add it to the list and possibly get you some more exposure.

**Comment by JoshData** [comment]
It would be a pretty serious research project to figure out what it is the other projects do and don't do. (That's one of the reasons why I started Mail-in-a-Box.) Frankly I think the only way to answer that question is to get the main developers of each of the projects into a room for an hour to discuss (which would be amazing, actually).

Just to give you a sense that I've thought about security - As far as I've seen, Mail-in-a-Box is the only project to help users set up [DANE](http://tools.ietf.org/html/rfc6698), which provides guaranteed encryption between MTAs that support it (vs. opportunistic, which is common).

**Comment by wifiextender** [comment]
The python files are written by someone with less than 6 months of experience with the language. I saw attempts to mix python 2 formatting specifiers in python 3, opening files for reading and/or writing without context manager. Some of them was opened with context manager, but it wasn't clear was that a binary or text file. They wasn't written with performance and compatibility in mind either.

I would not run such horrible code on any of my systems. I mean it literary - horrible code.

The python files needs writing from scratch, as they posses serious threat right now.

**Comment by JoshData** [comment]
If the tone of this thread is going to be pedantic and deriding, I'm going to unwatch the thread and move on.... You all can email me if you have any substantive questions.

**Comment by konklone** [comment]
I'm pretty disappointed at how this thread played out. You summoned @JoshData to the thread, asked him to do work evaluating his security model with his spare time, and then summarily insulted his open source work (also done in his spare time) and dismissed it as needing to be rewritten from scratch.

If that's the kind of behavior the Prism Break project tolerates, then don't bother CCing me on any threads here either.

**Comment by Zegnat** [comment]
@JoshData:

> It would be a pretty serious research project to figure out what it is the other projects do and don’t do. <i>[…]</i>
> 
> Just to give you a sense that I've thought about security - As far as I've seen, Mail-in-a-Box is the only project to help users set up DANE, which provides guaranteed encryption between MTAs that support it (vs. opportunistic, which is common).

I understand that’s a huge project, and really I wasn’t fishing for a full-scale audit. You telling me Mail-in-a-Box helps people set-up DANE and others you have seen do not is the kind of comparison I was looking for. Like I said, I am not a server administrator, so anything deeper is outside my scope anyway.

DANE (or RFC 6698) isn’t mentioned as [an IndiMail feature](http://en.wikipedia.org/wiki/User:Mbhangui/IndiMail#Features) and as far as I can find iRedMail is [not planning](http://en.wikipedia.org/wiki/User:Mbhangui/IndiMail#Features) to support it in the immediate future either. In comparison I would say Mail-in-a-Box wins there.

@wifiextender:

> I would not run such horrible code on any of my systems. I mean it literary - horrible code.

Are any of the things you have mentioned security issues? If not, does it matter? I don’t think we have taken code quality into account, ever, on PRISM Break. And I think it might be a slippery slope to do that, as there exist so many different styles that get fought over already.

@konklone:

> You summoned @JoshData to the thread, asked him to do work evaluating his security model with his spare time, and then summarily insulted his open source work (also done in his spare time) and dismissed it as needing to be rewritten from scratch.

This “you” is three different people, and I am not sure how I feel about being rolled into that one collective person. In the last two years I have written with plenty of developers both here and over email, and I don’t think I have ever been uncordial. Whenever there have been misunderstandings I have always offered an apology and I have an open invitation standing to anyone to come share a drink with me and talk it out if ever they are in the neighbourhood.

As we love to include as many people as possible on our discussions, I can only hope you do not actually dismiss complete open-source projects whenever a blunt or offensive comment is made on a public mailing list.

> If that’s the kind of behavior the Prism Break project tolerates, then don’t bother CCing me on any threads here either.

I don’t think the PRISM Break ever set any sort of code of conduct. Maybe it needs to? I don’t think it ever came up with never more than maybe 10 people actively hanging around the issue tracker. I’d love to hear your thoughts on that in either a new issue or over email!

**Comment by wifiextender** [comment]
@Zegnat I couldn't be more polite as the self believing that "I've done this correctly" is the most used thinking by everyone that has just started to use some programming language, including me in the past.

It is relatively easy to overlook or you don't know that your lack of knowledge will put everyone else in trouble.

Even I commited really [bad mistake](https://github.com/wifiextender/pdf2img-c/issues/4) in my second C gui program. That is why we should hire people that have done enough programming in the particular language, so they can do their best to write proven and reliable code.

@JoshData I did not wanted to hurt your feelings, I am thankful for your time and effort regarding your constant work in the project, but it is time to call some friend or hire someone that knows the particular language.

**Comment by JoshData** [comment]
@wifiextender If you've found a security vulnerability, file an issue or submit a PR. Please don't @-message me just to tell me you don't like it. If you want to debate with this project's maintainers over whether to include Mail-in-a-Box in prism-break, please do so without me.

(And, again, if any project maintainers have any substantive questions for me, feel free to reach out.)

**Comment by hasufell** [comment]
> That is why we should hire people that have done enough programming in the particular language, so they can do their best to write proven and reliable code.

Sorry for OT, but this is not sufficient to solve these fundamental problems in programming. It is also an effort of language design and language education. C basically opens all gates of all possible bugs you can remotely think of (and those you can't even think of, but find during a long gdb session). Just hiring experienced people and increasing the bus-factor (lead programmer gets hit by a bus... now you are screwed) isn't going to improve our overall situation. They all make mistakes, some less, some more. And yes, there are languages that eliminate certain _classes_ of bugs completely (python is not part of those), but people are not educated to use them.

The second thing we need is the opensource community. Instead of ranting about specific pieces of code here, you should just go ahead and do an _actual_ review, not just broad statements. That is far more helpful. If the developers prove to be uncollaborative (that happens), then you have every right to rant about it.

> I would not run such horrible code on any of my systems.

I can guarantee you that you run much much worse things on your computer right now. You just don't know it.

**Comment by wifiextender** [comment]
>I can guarantee you that you run much much worse things on your computer right now. You just don't know it.

I do my job to preview and test the source code before that.

For sure I would not rely on a code written by newbie that has no idea what could possibly happen by his/hers lack of knowledge. For crucial projects we should **always** put the right people to do the actual coding, others are free to contribute as well.

No experience = total disaster, and I have just reported the most basic mistakes commited by the people involved in their project, because of their lack in the python language.

I just can't close my eyes when I see horrible code, and more especially a code that is used in a program meant to **protect** you.

Call me rant or whatever you like, but for sure you wouldn't run such programs either when you know what lies beneath the particular program/project.

>Just hiring experienced people and increasing the bus-factor (lead programmer gets hit by a bus... now you are screwed)

Then all employers that have hired people contributed to the kernel development are wrong, they could hire someone that has just read 1 book how to program. Nowadays if you contribute to the kernel development and you are unemployed the chance to be hired is pretty high - guess why.

**Comment by hasufell** [comment]
> Call me rant or whatever you like, but for sure you wouldn't run such programs either when you know what lies beneath the particular program/project.

It is simply not productive behavior.

> Then all employers that have hired people contributed to the kernel development are wrong

No, you didn't read the whole sentence.

**Comment by nodiscc** [comment]
Sorry for the wall of text, I've tried to keep it readable.

> I do my job to preview and test the source code before that.

Are you implying that you read the code of all software running on your computer? Also I see you still haven't reported an issue about best coding practices on the mailinabox bug tracker, so I take your advice with a grain of salt.

So, back to mailinabox, from a server administration perspective (I have no clue about the coding practices/experience being good or bad): I think mailinabox does too many things:

> Mail-in-a-Box turns a fresh Ubuntu 14.04 LTS 64-bit machine into a working mail server, including SMTP (postfix), IMAP (dovecot), Exchange ActiveSync (z-push), webmail (Roundcube), spam filtering (spamassassin), greylisting (postgrey), CardDAV/CalDAV (ownCloud), DNS, SPF, DKIM (OpenDKIM), DMARC, DNSSEC, DANE TLSA, SSHFP, and basic system services like a firewall, intrusion protection, and setting the system clock.

There are already self-hosting oriented distros on prism-break. Mailinabox mixes a webserver setup/administration toolchain, firewalling, mail relaying, scripts and config files... It's also designed around Ubuntu server, which is excluded from prism break on purpose. I wouldn't set this up on my machine because it doesn't use the distro's packaging tools and configuration routines (does not use `dpkg-divert`, does not have basic package automatic upgrade facilities...) and simply mixes up too many things. What would be acceptable IMHO, are **separate and complementary tools**:

 * Setup scripts for a mail server on an already-running box. iRedMail does just this.
 * Standard install procedures through secure channels (`curl -s https://mailinabox.email/bootstrap.sh | sudo bash` seriously?)
 * A set of configuration files for standard, packaged, stable server software, using _documented_ configuration settings, with rollback possibilities. Bonus points for using well tested configuration management tools (ansible, saltstack,~~puppet, chef~~). Do not do this from a hand-crafted python script in any case (Well I do it on my server, but it just doesn't scale and I wouldn't recommend it for large scale deployment).
 * A simplified configuration/administration frontend to manage your mail server (Mailinabox seems to have one, but I can't find the documentation for it)
 * A more customizable setup/install procedure. Why would most users install an Exchange ActiveSync service as part of a simple mail server setup procedure? Why increase the attack surface by default?
 * A separate frontend for webserver configuration: install and upgrade apps, manage apache/nginx common configuration settings. (currently the same frontend/script seems to be used to manage the mail setup **and** owncloud/roundcube. Or not? Can't find the docs... Anyway why restrict this tool to a these 2 web apps? What if I want to use mailpile instead of roundcube?)
 * Separate scripts/administration frontends for other tools.
 * **Or** self-contain this in a distro installer you can run in a VM and don't let it touch your host OS configuration.

Hope this is isn't too confuse. The principle behind Mailinabox seems fine (key-in-hand mail server), but I think the project scope is too broad (or too focused on a very particular setup) for being recommended on prism-break in it's current form. A repo with documented config files would be more helpful and cleaner (check https://github.com/ioerror/duraconf/tree/master/configs)

PS: On a side note, maintaining a mail server is very time consuming, it rarely works well, and the underlying protocols are 30-year old duct-taped mess. Unreliable delivery because of spam filtering, ISP inbound SMTP blocking, only supports ASCII. encodes everything in base 64. HTML support is broken in clients, so it sends 2 copies of the message, public/unencrypted by default; with GPG: no confidentiality in to: from: subject: headers, complex key management, centralized PKI, PKI vulnerable to sybil attacks...... On the contrary setting up XMPP takes about 3 minutes on any box. Install a package, edit a configuration file, add a firewall rule, done. Saying this as prism-break focuses on quality, not quantity. Achieving quality and privacy-respecting communication through email is very hard, and maybe you should focus on future-proof technologies.

PS2: Someone (@hasufell I think it was you) here one day told me that unpackaged software should not be a blocker for inclusion. I think that _server-side_ software that's unpackaged and doesn't use standard distributor/config management tools is very risky. No `curl | sudo bash` and bumblebee-installer-rm-rf-/ surprises in server software please.

**Comment by strugee** [comment]
tl;dr: DANE doesn't work in practice, and Mail-in-a-Box seems like it's going in good directions but needs to mature.

> Just to give you a sense that I've thought about security - As far as I've seen, Mail-in-a-Box is the only project to help users set up DANE, which provides guaranteed encryption between MTAs that support it (vs. opportunistic, which is common).

Just to comment on this specific example, there's a reason DANE hasn't been widely adopted. The problem with DANE is that it relies on the DNS, which is (essentially) centralized and trivially subverted. Now, I know you're about to say that DNSSEC is there to authenticate DANE records (as well as SSHFP records), but DNSSEC isn't a panacea, either. DNSSEC just takes PKI, which sucks in the browser, and makes it suck even worse in DNS. Why? Because the organization responsible for running (and thus DNSSEC-signing) the .com TLD is Verisign, AKA one of the root CAs commonly distributed with browsers.

Ultimately, the problem with the DNS and any security mechanism based on the DNS is this: the DNS security model is not well understood. The browser security model is better understood. Yes, PKI is probably the most dismal widely-used security system on the planet. But at least we understand it. DANE is a fantastic idea, but all it does in practice is take all the suck of PKI and add some confusion to it. :/

That all being said, @JoshData, you've done some great work, and just about everything else on your list (sans Exchange support and maybe one other thing) is something that's absolutely required for a mail server. I'm going to side with @nodiscc on this one and say that we shouldn't recommend Mail-in-a-Box, simply because it seems like Josh hasn't quite nailed down all the moving parts. However, he's made some excellent progress on an almost impossible task (as someone who runs a mail server, I can tell you @nodiscc is right; email standards are badshit _insane_), so I think that we should definitely keep an eye on Mail-in-a-Box and see if we want to include it later.

**Comment by JoshData** [comment]
FFS, what do I have to do to get you all to stop @-mentioning me to complain that you don't like my approach? Every time you @-mention me I get re-subscribed to this thread. If you don't like my approach, go build a better system. If you see a problem, go submit an issue or pull request. Till then, I really am getting tired of receiving github notifications about all of your fantasy lands of perfect software. Once again, please leave me out of this.

> The browser security model is better understood.

Like everything else on this thread, that is a complete fantasy. Who the hell understands revocation lists, certificate stapling, and certificate transparency? Maybe prism-break should drop Firefox until they stop leaking browsing history through OCSP! (I'm sure you know what I'm talking about, @strugee, our resident PKI expert on this thread.)

If you can't keep me out of this thread, I respectfully request that Mail-in-a-Box *not* be included in prism-break so that this issue can be closed.

**Comment by vyp** [comment]
If not already clear, this thread is not leading anywhere. @Zegnat or @nylira should close this to stop wasting everyone's time.

**Comment by wifiextender** [comment]
>Are you implying that you read the code of all software running on your computer

If know the programming langauge it goes thru reviewing process, and if don't know it goes only thru the testing framework.

>Also I see you still haven't reported an issue about best coding practices on the mailinabox bug tracker

Read a lot books (20+ books), accept advices from others, make sure that you tried everything possible before you do a search engine query to solve your program issue(s),  and remember that practice makes perfection.

There is new ssl bug that will be solved in next 3 days. I guess it could be the heartbleeded equivalent. Will migrate my repositories to SSH instead SSL.

**Comment by konklone** [comment]
Yes, this thread should be locked. And the project leaders should strongly consider speaking with @wifiextender off-thread about his impact on community engagement.

**Comment by Draxler** [comment]
Prism-Break should introduced and inforced rulse of cunduct asap. This is NOT the way people should comment other people's work as @wifiextender does at Prism-Break. This thread shouldn't be closed just because some people slunders other peoples work. This thread deserves to be reopened and continue disquession about this project and delete all the neccery (off-Topic) comments. Prism-Break  should infroced the rules when unexcaptable cunduct is taking place and block such user to use certain topic after one warning and bad behavor doesn't stop there. Here we have developer who's join this thread just to answer some qustions but instead he's get attacked. Prison-break should protect devs so they wouldn't have hard time comming here and answer some qustions about their project.

**Comment by Dostoi** [comment]
+1

**Comment by wifiextender** [comment]
I know that the truth is hard for accepting, but didn't expected to see so many angry people. People, do you live in a delusion ?

@Draxler @konklone did I lied about something ?

We are all on the same side, and we should be honest to each other. Don't cover your eyes when you see something wrong, otherwise it might impact someone else.

**Comment by Zegnat** [comment]
Locking this issue. If anyone wants to discuss anything other than Mail-in-a-Box, open a new issue.
