### ISSUE TITLE
[ Operating Systems ] Trisquel GNU/Linux

### ISSUE THREAD

**Issue by ceyhanmolla** [nylira/prism-break#1253]
Trisquel GNU/Linux is a 100% free operating system. It comes with a complete selection of programs that can be easily extended using a graphical installer. There are several editions available, including the "mini" edition for netbooks and old computers and the network based installer for custom and server installations.

http://trisquel.info/

**Comment by Zegnat** [comment]
Thanks for your interest! Closing this as a duplicate, please see:

1. #789, adding Trisquel, sparked by #536, which was not accepted after no security reasons could be provided.
2. #1064 about adding FSF listed “entirely free” distributions. Instead of copying in such a long list into PRISM-Break we are linking to their list. Trisquel is on there.

If you have new arguments for Trisquel, please add them to #789.
