### ISSUE TITLE
Consider Lucida personal assistant

### ISSUE THREAD

**Issue by hfa2010** [nylira/prism-break#1278]
As an alternative to Googe Now and Siri, you should add Sirius.
Sirius Git: https://github.com/jhauswald/sirius

**Comment by vyp** [comment]
And Cortana.

**Comment by mastercoms** [comment]
And Amazon Echo

**Comment by Zegnat** [comment]
It looks like Sirius uses only open-source systems, though I may have missed a licence file somewhere, so that looks fine. It says it currently requires to be run on Ubuntu though. We do not recommend people use Ubuntu, so unless Sirius can easily be installed on one of the operating systems recommended on PRISM Break I do not think it should be included.

**Comment by hasufell** [comment]
> It says it currently requires to be run on Ubuntu though.

Yes, it says that, but they are wrong about their own prerequisites, afais, because there are no ubuntu-exclusive dependencies. They just lack a proper build system.

Check
https://github.com/jhauswald/sirius/blob/master/.travis.yml
https://github.com/jhauswald/sirius/blob/master/travis-scripts/suite_deps.sh
https://github.com/jhauswald/sirius/blob/master/sirius-application/get-dependencies.sh

But I'm currently too lazy to try to package it. Looks like it needs some work.

**Comment by strugee** [comment]
> And Cortana.

File a new issue.

> And Amazon Echo

Ditto for this.

**Comment by Zegnat** [comment]
> They just lack a proper build system. <i>[…]</i> Looks like it needs some work.

I think we should hold off until packagers have taken a look and brought it to the platforms we recommend. How do others feel about this?

@strugee, those don’t need new issues. Both of them are proprietary solutions that will be added to the proprietary column **if** we decide to add an “Intelligent Assistant” category with Sirius.

**Comment by vyp** [comment]
If what Julian says is correct, there could be the possibility of *unofficial* packages for systems we do recommend. So the question would be, would such unofficial packages be acceptable?

**Comment by vyp** [comment]
@Zegnat Btw, there is a license file: https://github.com/jhauswald/sirius/blob/master/LICENSE. But not sure if that's what you were referring to?

**Comment by Zegnat** [comment]
> So the question would be, would such unofficial packages be acceptable?

I would say yes. It isn’t really about software being included in official package managers, it is more about software being able to be installed on the platforms we recommend. I think – but haven’t checked – we are already recommending some tools you would have to install from source without package managers, that’s not the problem. But there has to be some sort of supported way to do so, rather than having to go and figure out all dependencies by yourself.

> Btw, there is a license file <i>[…]</i> But not sure if that's what you were referring to?

They have bundled a lot of stuff in that one repository. That BSD licence only applies to the core Sirius code as it came out of the University of Michigan. There is also some ‘[borrowed](https://github.com/jhauswald/sirius/blob/master/sirius-web/static/recorder.js)’ [code](https://github.com/jhauswald/sirius/blob/master/sirius-web/static/recorderWorker.js) from [an MIT licensed project](https://github.com/mattdiamond/Recorderjs#license-mit) (for which I am unsure they give enough credit, but they may have done heavy customisations…), and all these other licences:

* Copyright (c) 2011 Yoshimasa Tsuruoka [[1]](https://github.com/jhauswald/sirius/blob/master/sirius-suite/crf/baseline/LICENSE), [[2]](https://github.com/jhauswald/sirius/blob/master/sirius-suite/crf/pthread/LICENSE)
* Huge [COPYING file](https://github.com/jhauswald/sirius/blob/master/sirius-suite/gmm/COPYING) that seems to cover “Kaldi v1.0”, “JAMA: A Java Matrix Package”, “code published in Malvar, H., ‘Signal processing with lapped transforms,’ Artech House, Inc., 1992”, and “the OpenFST Library v1.2.7”.
* Copyright (c) 2004-2013 Sergey Lyubka `<valenok@gmail.com>`<br>
  Copyright (c) 2013 Cesanta Software Limited [[1]](https://github.com/jhauswald/sirius/blob/master/sirius-suite/regex/LICENSE)
* Copyright (c) 1995-2014 Mort Bay Consulting Pty. Ltd. [[1]](https://github.com/jhauswald/sirius/blob/master/sirius-application/speech-recognition/sphinx/LICENSE)
* Kaldi’s [COPYING](https://github.com/jhauswald/sirius/blob/master/sirius-application/speech-recognition/kaldi/COPYING) (again.)

If you thought the whole repository was covered by the very generous BSD type licence you were sadly mistaken. All of them seem to be OSI approved so the project can call it self open source, but I could’ve easily missed a copyright header in some file.

**Comment by vyp** [comment]
> If you thought the whole repository was covered by the very generous BSD type licence you were sadly mistaken.

Yeah I was actually going to go try and build it and report back, but I realised how massive it could all be. So it's quite obvious that there might be licensing issues in there somewhere (especially considering the liense file I linked has "For Sirius software"). And I only have laptops (with maximum 4 gb ram), no proper machine with lots of ram to build things with, so I'm not going to try.

**Comment by Zegnat** [comment]
Like I said, I haven’t seen any licensing conflicts apart maybe from the RecorderJS MIT licence not being included. Licensing shouldn’t actually be a problems with packaging. I don’t want it to seem like I think otherwise.

Only thing stopping this is operating system support.

**Comment by wifiextender** [comment]
Hello,

I really wanted to write archlinux installation instructions, but it turns out that the kaldi servers throttle the download of http://kaldi-asr.org/downloads/build/5/trunk/egs/fisher_english/s5/exp/nnet2_online/nnet_a_gpu_online/archive.tar.gz and http://kaldi-asr.org/downloads/build/2/sandbox/online/egs/fisher_english/s5/exp/tri5a/graph/archive.tar.gz down to 30kb/s , which means 10+ hours to complete... lol

Will list the packages which you have to install in archlinux:

``` base base-devel tesseract-data-eng tesseract leptonica vlc ffmpeg faac texi2html yasm subversion sox swig boost boost-libs python2-pip cmake lame jack opencore-amr sdl libva libvdpau libtheora libvorbis libxfixes xvidcore protobuf protobuf-c opencv  ```

from aur: ``` atlas  ```

Then from the "cheese shop" install ``` (sudo) pip2 install wtforms Flask requests pickledb ```

**sirius-master/sirius-application/get-kaldi.sh** will try to execute  **sirius-master/sirius-application/speech-recognition/kaldi/scripts/prepare.sh**, but it is not executable, to make it executable exchange the file permissions with ``` chmod +x the_file ``` or if you don't want to make it executable then use sed ``` sed -i 's@./prepare.sh@bash\ prepare.sh@g' sirius-master/sirius-application/speech-recognition/kaldi/scripts/prepare.sh ```

You don't have to install **zip** and **unzip**, python and zlib are/will be installed by default in almost all gnu/linux distributions, so you can borrow my compression functions instead https://github.com/wifiextender/compression_maniac/blob/master/compress_extract.zsh

Cheers

**Comment by Zegnat** [comment]
@wifiextender, I think that is something more fitting for the [jhauswald/sirius](https://github.com/jhauswald/sirius) issue tracker than here.

**Comment by hfa2010** [comment]
Any news on this matter? The Project now is called Lucida and apparently diverged (was forked from) from the previous project.

**Comment by yegortimoshenko** [comment]
Given that the previous project is not maintained anymore, and fork is the successor, it would make sense to repurpose this issue into one for Lucida.

Source code: https://github.com/claritylab/lucida

**Comment by alerque** [comment]
See also #1889 for a proposal of adding Mycroft and #898 for some discussion about the category in general.
