### ISSUE TITLE
Encryptr evaluated?

### ISSUE THREAD

**Issue by jzakiya** [nylira/prism-break#1283]
Has Encryptr zero-knowledge password manager been evaluated?

http://www.linuxandubuntu.com/home/encryptr-zero-knowledge-system-based-password-manager-for-linux

https://encryptr.org/
https://crypton.io/

**Comment by Zegnat** [comment]
Crypton seems to take audits seriously and has already [been audited twice](https://crypton.io/docs/security/audits.html). In [the March 2014 audit (PDF)](http://www.leviathansecurity.com/wp-content/uploads/Crypton_2014_pentest_Final_Report.pdf) Leviathan Security describes Crypton as “pre-alpha” and found 12 critical easy to exploit vulnerabilities in the part they analysed. Couldn’t find a quick list of how much of that has been fixed, there probably exists one but I am short on time at the moment.

I’ve done some really – REALLY – quick and simple testing of Encryptr. It looks like everything is only stored remotely, when I blocked Encryptr in my firewall I could not longer access the 1 note I saved. If for some reason you can’t trust your own hard drive you have bigger problems. There also doesn’t seem to be a way to configure a different remote server, something we have always required on PRISM Break because we advertise self hosting as much as you can.

I personally do not think Encryptr is ready. But maybe someone with more disposable time would like to take a look.

**Comment by wifiextender** [comment]
Hello guys,

The newly discovered CPU cache attack that works on intel cpu's with L3 cache should be considered as it can be triggered by any javascript in users browsers (ads for example), please read http://www.theregister.co.uk/2015/04/21/cache_creeps_can_spy_on_web_histories_for_80_of_net_users/

Cheers

**Comment by yegortimoshenko** [comment]
Source code: https://github.com/SpiderOak/Encryptr

**Comment by yegortimoshenko** [comment]
I support @Zegnat in that remotely storing password database is not OK.

**Comment by yegortimoshenko** [comment]
Labeling as "waiting for objections" because this requires server to grant password access, even if it's zero-knowledge.
