### ISSUE TITLE
Our recommended software 'phones home'

### ISSUE THREAD

**Issue by mastercoms** [nylira/prism-break#1288]
https://mailman.stanford.edu/pipermail/liberationtech/2015-April/015236.html

For firefox's Google reporting, this is easy by adding a **stressed** note about the malware blocking. However, for the Mozilla reporting, we would have to recommend Cyberfox for Windows, and Iceweasel for Linux instead of showing Firefox.

For NoScript, I have no idea.

**Comment by wifiextender** [comment]
Hello mastercoms,

What Carlo wrote does not hold true:

>I was told it even lets Google have the cookie it uses to
identify you, so even if you use Tor, the five eyes immediately
know it is you. I didn't bother to check however.

Whenever you start the Tor bundle (browser mostly) you are presented with window that let you choose how to connect to the Tor network **before** the browser is opened. It is likely that Carlo has no idea how Tor works or what 'circuits' , 'layers', 'nodes', 'relays' mean or what the Tor logo represents.

Can he elaborate more on how an exit node will be able to tie **your real** ip whenever you use the Tor bundle ?

Spoiler alert:
http://www.thefreedictionary.com/distinctive

Cheers

**Comment by mastercoms** [comment]
Cookies can be used to identify a user across multiple Tor identities. He is talking about improperly configured Tor browser configurations. Of course, the Tor Browser Bundle would not be vulnerable to this.

**Comment by wifiextender** [comment]
Hello mastercoms,

>He is talking about improperly configured Tor browser configurations

I have re-read the whole mail one more time and could not find any such information. [That's](https://github.com/wifiextender/dwm-fork/blob/master/config.h#L76) how I'm starting Tor every single time and at every half hour there is script that 'shreds' the files and relaunchs Tor again. No configuration or whatsoever is reused - ever.

Cheers

**Comment by Zegnat** [comment]
I believe we have previously discussed improper use of Tor and said that PRISM Break will not waist time on it. If you are not using the Tor Browser Bundle and are leaking possibly identifying cookies that is not a software problem.

The Google cookie has also been discussed previously, and should be sandboxed in Firefox. Even if you are logged into Google in your current browsing session, the cookie sent along to the safe browsing API holds no information about that. (#804 & [Bugzilla@Mozilla #368255](https://bugzilla.mozilla.org/show_bug.cgi?id=368255).)

PRISM Break has recommended de-branded Firefox builds, but it never really became clear if they had any privacy wins over the actual Firefox. Or if it was even worth foregoing Firefox’ regular patches just because you don’t want to let Mozilla know you are using their product. If anyone can make a real case showing that de-branded forks 1) stay up-to-date with the main security patches and 2) make a considerable effort to modify Firefox to become more privacy conscious then it will definitely be included on PRISM Break again.

Really the only thing I took away from this was that we should take a good look at the add-ons we recommend and see if those leak user data in some way. Since all of them are open-source, we can open issues on their respective trackers to try and get them to change. That would make for a much more healthy open-source community than a slightly vague email on a mailing list.

**Comment by wifiextender** [comment]
Hello Martijn,

The wiki link which I posted yesterday contained information regarding other evil cookies such as [Evercookie](https://en.wikipedia.org/wiki/Evercookie) that are way more dangerous than the standard one, here is a [test](http://samy.pl/evercookie/) page, and here is the [source code](https://github.com/samyk/evercookie) of it.

>For NoScript, I have no idea.

https://www.gnu.org/software/librejs/

Cheers

**Comment by Zegnat** [comment]
I know about evercookies, my reply was more to the linked email than anything else.

LibreJS is no replacement for NoScript AFAIK, they have completely different reasons to exist. In fact, Evercookie claims to be open-source and would not be blocked by LibreJS if they added the correct header.

I think I will close this, as the linked mailing list thread seems to contain a lot of FUD. If anyone has a concrete argument to replace Firefox or NoScript, please open new issues for those!

**Comment by wifiextender** [comment]
Hello Martijn,

My cookie reference was towards both discussions, the mail list and the one that has taken place here earlier.

>the linked mailing list thread seems to contain a lot of FUD.

Read the replies and I guarantee you that they will make your day.

>LibreJS is no replacement for NoScript AFAIK, they have completely different reasons to exist. 
And I didn't recommended it as [replacement](https://www.fsf.org/news/announcing-js-labels) [either](http://www.gnu.org/philosophy/javascript-trap.html) :}

Cheers
