### ISSUE TITLE
uBlock Origin

### ISSUE THREAD

**Issue by mastercoms** [nylira/prism-break#1291]
https://github.com/gorhill/uBlock
https://www.youtube.com/watch?v=_D1TpddtVUA
https://github.com/gorhill/uBlock/issues/38#issuecomment-91871802
www.reddit.com/r/firefox/comments/31kk9x/ublock_creator_requests_old_project_to_be_renamed/

I don't know what to make of this, but the best we can do is list both uBlock and uBlock Origin.

EDIT: uBlock Origin seems like the better choice, especially when you consider privacy

**Comment by vyp** [comment]
My vote is to replace ublock with ublock origin. Listing both of them only serves to add confusion than to help. Also see https://www.reddit.com/r/programming/comments/33sl39/maintainership_transfer_of_ublock_post_mortem/

**Comment by Zegnat** [comment]
Really the most important link in all this is [the post mortem](https://github.com/gorhill/uBlock/wiki/Maintainership-transfer-of-uBlock%3A-post-mortem) by @gorhill, instead of (sorry) random reddit users. We can all move on.

That said it was originally gorhill’s uBlock featured on the site and I see no problem doing so again, given that gorhill will not abandon it. Really all PRISM Break cares about in this situation is that the project is open-source and supported, there is nothing in our rules that excludes forks.

My understanding is that the core functions are pretty much identical for both add-ons, so the discussion would be which one is easiest to use. Has anyone compared the two that way? We shouldn’t chose which one of the two to recommend based on politics, it is about the end-user.

**Comment by wifiextender** [comment]
Hello guys,

The commits in both projects reval that gorhil is doing pretty much all the heavy lifting including fixing some of the issues filed in chris's ublock, and Chris is still unsure what to do and is fixing only a small part of the bugs and most of the time is updating the **readme.md** file.

I thought Chris will take his shit together and the things will improve, sadly I was wrong.

Cheers

**Comment by Zegnat** [comment]
There is actually a lot other things going on. For instance, @chrisaljoudi (Chris) pushed some fixes back to @gorhill’s (Raymond’s) fork for whatever reason: gorhill/uBlock#154. And Raymond apparently decided to keep Chris’ repository as the actual main and will push fixes upstream: [gorhill/uBlock#148](https://github.com/gorhill/uBlock/issues/148#issuecomment-97017899).

So if we recommend the main repository it should get both new features by Chris and bug fixes by Raymond. If we recommend the uBlock Origin fork it will only be Raymond’s bug fixes, as he isn’t planning to add new features (for now).

**Comment by mastercoms** [comment]
Chris has removed power user features.

**Comment by gorhill** [comment]
> @chrisaljoudi pushed some fixes back to @gorhill’s fork

Most of these fixes were for Safari, which my fork does not support.

> he isn’t planning to add new features

I don't consider adding new features regularly as a sign of software being properly maintained. There is no such thing as infinite amount of features for a given software. At some point a near-plateau is reached where stability takes priority over "must-add-features." All the features I've added to uBlock I believed were needed, and that mindset has not changed. I do plan to work on it as I see fit, mostly improving on what already exists. It's pretty much the state of uBlock for botn brtanches if you look closely.

> Chris has removed power user features.

I actually consider these features beneficial for less advanced users -- they are available to all users, no need to check _"Advanced users"_. In my opinion this is a big removal, as some of these improve protecting users, especially _Strict blocking_.

**Comment by RanceJustice** [comment]
Thank you for all your hard work, gorhill.  I personally use your Origin branch and feel it best meets my needs; its progression since the fork is great to see, and I hope you continue to work on it as long as you feel you gain some enjoyment from doing so. For what its worth, the community appreciates it greatly.   

I think that sites like Prism-Break and PrivacyTools.io should definitely  list uBlock Origin, covering both variants at least in comment. I'd go as far as say that uBlock Origin should be the "primary" suggestion.

**Comment by rodneyrod** [comment]
@gorhill any chance of getting @Deathamns working again on something uBlock related in the future?

There wasn't anything official listed in his reasoning of leaving the project, and I think that it's both negative for the project and greater uBlock* community if either he doesn't come back, or if there isn't a proper reasoning for his departure out there.

**Comment by mastercoms** [comment]
It doesn't seem like the main uBlock fork is even being maintained.

https://github.com/chrisaljoudi/uBlock/releases vs https://github.com/gorhill/uBlock/releases

**Comment by mastercoms** [comment]
I say we use uBlock Origin since it seems to be focused on privacy and protecting users, while uBlock is just trying to be another adblocker. uBlock Origin has added many privacy enhancing features, and has added many privacy centric filters, in addition to the ones uBlock provides.

**Comment by gjallarhorn** [comment]
Here's a list of some of the privacy enhancing features @mastercoms is talking about:

[Block browser pre-fetching](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-pre-fetching)
[Block hyperlink auditing/beacon](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-hyperlink-auditingbeacon)
[Per-site switch to disable remote fonts](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#no-remote-fonts)
[Prevent local IP address leak through WebRTC](http://www.ghacks.net/2015/07/02/you-can-block-webrtc-from-leaking-your-ip-now-in-ublock-origin/)

**Comment by mastercoms** [comment]
@Zegnat not all uBlock Origin stuff has been pushed to main, just some important fixes to unbreak websites.

**Comment by Zegnat** [comment]
Yeah, it seems the situation has changed a lot, with uBlock Origin implementing the new features rather than the other way around. With this I have no complaints to recommending Origin over the main one.
