### ISSUE TITLE
Sugestion: add gpg4usb

### ISSUE THREAD

**Issue by N-siege** [nylira/prism-break#1295]
Hello to everyone,

I suggest the gpg4usb. The gpg4usb is a portable software, open-source, which makes it easy to create, manipulate, write, encrypt and decrypt GPG messages. Compatible with Windows and Linux.

Being portable, it would enable both the program and its data (the keys) can be stored in a container EncFS in other encryption software, or even the discontinued TrueCrypt.

Official site: http://www.gpg4usb.org/
Source Code: https://github.com/gpg4usb/gpg4usb

I hope this become useful.

**Comment by Datenschutz** [comment]
Would really love to see gpg4usb, it was updated to GnuPG 1.4.20 last year too.

**Comment by strugee** [comment]
Couple of notes:

1. gpg4usb is not free software (it includes an image which is CC BY-NC-SA, according to the README)
2. The fact that they're on GnuPG 1.x is not terribly comforting to me. 1.x is considered legacy now (though still maintained AFAIK), and 2.x is the "stable" version. Not a deal-breaker, but still.
3. The Email Encryption section already has a fair number of projects in it... not sure if we should be adding to that list. Although to be fair for any given user only a couple will be relevant since they're almost all basically packaging of GPG for different systems.
4. In general I'd like us to deemphasize GPG. Not sure adding to this section is the best idea.

**Comment by yegortimoshenko** [comment]
I agree with @strugee (other than I don't think we should de-emphasize GPG).

Also, see #1054 and #1126.
