### ISSUE TITLE
Script for translations

### ISSUE THREAD

**Issue by P3lUZa** [nylira/prism-break#1296]
I think there is no way of adding the code in all other languages. I mean, if I edit english and I want to put the new code in all other languages.

So, I share what I did:

```
$ cd source/db/
$ sed -i '$ d' *.json
$ sed -i '$ d' *.json
$ echo ' ### HERE THE CODE FROM   }'    TO   ]   ### ' | tee -a *.json
```

That makes the trick, but someone with better bash skill may short it, or maybe there is already an easy way :S

**Comment by vyp** [comment]
This is a bit late, but I think the easiest way would be to use your editors macro capability. As in, you open all the `source/db/*.json` files in your editor, and then tell to it to simply copy paste the relevant section to all the other files. This way it's much more dynamic, easier, quicker than a script because perhaps you might also want to delete a project. Or maybe you want to copy all the description sections from an old but similar project into a new project so that you don't lose translations etc etc... all should be simple with spontaneously defined macros.

But if you really want a script, you should use a json parser because the files are all valid json files and that's probably the easier (and likely more correct) way than to use regular expressions.

**Comment by strugee** [comment]
Irrelevant now that #1627 has landed.
