### ISSUE TITLE
Should we keep Bitmessage ?

### ISSUE THREAD

**Issue by wifiextender** [nylira/prism-break#1297]
Hello everyone,

Just came here to express my overall experience with bitmessage and how the things went from good to silencing people using encrypted emails or using words like 'Classified' in their email subject.

I became BM user almost a year ago https://github.com/nylira/prism-break/issues/461#issuecomment-44200057 , and just few weeks ago I contacted tails-bugs@boum.org using GPG and my email subject was ['Classified'](http://www.cs.princeton.edu/~felten/testimony-2013-10-02.pdf); read the testimony to learn why.

Right after this email my account became **read-only**, others can send me emails but whenever I try to send an email, even those in cleartext are no longer delivered to the recipient.

Few days ago went to register another BM account and saw that there was no longer option to register an account without existing email address, and they have removed the ability to create new aliases. wifiextender@bitmessage.ch is alias and not my account name.

I might became their target long time ago because when I [exchanged](https://github.com/nylira/prism-break/issues/1093#issuecomment-51970792) Thunderbird with Mutt, I was able to access folders on my account that I did not knew before. In these folders I saw all of my inbox, outgoing and draft emails. Thought it was the Thunderbird fault (because TB was struggling from the very same issue like the recently discovered one in [Claws](https://tails.boum.org/security/claws_mail_leaks_plaintext_to_imap/index.en.html)) and didn't paid any attention and simply deleted the folder. There was 2MB inbox limit at the time, but the folders alone was more than 30MB in size.

Back to the BM registering page:

>Monitoring means, that all your sent messages wont get removed from the server, when you delete them.
I can only send messages to 50 people per day

Just fills the missing pixels from the overall picture. I've never exceeded that limit, even before this announcement. I'm not sure why the things went so wrong with Bitmessage and why they silent people like me, ordinary citizens that [care](http://arstechnica.com/security/2015/02/how-omnipotent-hackers-tied-to-the-nsa-hid-for-14-years-and-were-found-at-last/) about their [privacy](http://leaksource.info/2013/12/30/nsas-ant-division-catalog-of-exploits-for-nearly-every-major-software-hardware-firmware/) and use encryption tools. This wasn't my first GPG encrypted email either, but definitely the last one.

I am fully aware that there are some kind of data retention laws in Europe that was announced **this year**, but it still doesn't make any sense why BM will keep a copies of my emails in hidden folders, way before the announcement of this law.

Just to clarify, I tried to get in touch (twice) with the admins to sort this out, but they never replied to my emails. Wanted to know if this was a cache bug https://github.com/nylira/prism-break/issues/772 or they have explicitly configured their email server like that.

I would go even further to suggest their removal.

Cheers

**Comment by jax21es** [comment]
I agree with that.

**Comment by terrorist96** [comment]
Please edit your title to reflect bitmessage.ch, not bitmessage the python client. But that sounds pretty shady of them to do that..

**Comment by wifiextender** [comment]
>Please edit your title to reflect bitmessage.ch, not bitmessage the python client.

[Email Alternative](https://prism-break.org/en/projects/bitmessage/) , submit a pull request to fix this upstream.

What is worrisome that one [young](http://www.washingtonpost.com/local/crime/northern-va-teen-admits-running-pro-islamic-state-twitter-and-helping-man-join-terrorist-group/2015/06/11/1d0cb33e-0eef-11e5-9726-49d6fa26a8c6_story.html) person [posted](https://alkhilafaharidat.wordpress.com/2014/08/20/remaining-anonymous-online/) in his blog some kind of encryption introduction that was meant to aid some group, see the post date and bitmessage mention.

Connect the dots.

Cheers

**Comment by terrorist96** [comment]
I think it's obvious that bitmessage.ch was served with a National Security Letter, it is very off putting. I don't think the python client is compromised though.

**Comment by wifiextender** [comment]
I tend to disagree with editing the title as they have 2 domains. The wikipedia and forum are served from the .org domain, while the email gateway is served from the .ch domain.

Whatever the user prefers, the GUI client, web based email access or external email client, the final result will be always the same as all of them utilize the Bitmessage protocol.

Should I bookmark their page whenever they exchange their TLD to reflect the changes here ASAP ?

Cheers

**Comment by terrorist96** [comment]
bitmessage.ch isn't officially affiliated with the python client as far as I know.
Sure, please do. I'm interested

**Comment by wifiextender** [comment]
It was a [rhetorical](https://en.wikipedia.org/wiki/Rhetorical_question) question. Let's focus why should keep [instead](https://github.com/bitchan/meta/wiki/Bitmessage-overview-%282015%29).

Cheers

**Comment by JeremyRand** [comment]
PyBitmessage (the software that forms the reference implementation of the Bitmessage protocol) is by Atheros (Jonathan Warren) and is at bitmessage.org.  Atheros is also the founder of the Bitmessage project, although last I checked he isn't active anymore (several forks of PyBitmessage are still maintained by other people; MailChuck's fork seems commonly referenced but I have no idea if it's any good).  Bitmessage.ch is a third-party service run by AyrA, and has never had any affiliation whatsoever with the Bitmessage project.  They are totally different things, by different developers, and conflating them doesn't help end users.

**Comment by alerque** [comment]
I'm confused why this issue is still open. The issue being reported is in regard to a private provider that we don't recommend anyway. There doesn't seem to even be an issue raised about the protocol we are recommending.

The only thing I could see adding is a warning note about that particular provider, but I don't see anything here that merits removal of the protocol.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I agree with @alerque , this issue seems to be based on an assumption
that bitmessage.ch is affiliated with or the same thing as Bitmessage,
which is a false assumption.  I could maybe see a benefit in warning
people to avoid bitmessage.ch since apparently there are some people
who erroneously assume they're related, but no objection has been
raised to Bitmessage in this thread, and that's what is currently
recommended.  So yes, I would support closing this issue.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWvFyuAAoJEAHN/EbZ1y06E0cP/jHoJm/Clnv5VLb9ZFKvMnM3
TB8G+t/8/7ljeJb6lyJeWZhsoLi4+0mCgMItupj11O6PGtiUYdF6kjBrZ8uHjyq7
/8hlS6rPiGOqT9spm0MoUeRnyEaUshTEZxPZruM2hbNKBlnyOUxHAJsWcdx1fcf8
xk2wn9i22BXRg5mnsdvczOsJsv2PkLdATh0/naKZyj9wOdH4nGvyHI/wC0nWXcDs
9ABpYV6BbmFYJl//qEwqh+e4/nzowLE6xkGcey7ZCOb7z8XkSvT7ugnSRqMmzhCN
PRO1PtyYc0tqYdOalK5QmDnQvw/GRF/Hiubl9eDHw2oqi7pV7o+FAK4vN/Uq1mbE
he9ugZ4YvO1i4UIwq63T9zeeopygNbQeoKFktuUBvTHZZ5rXcrzJFdsu+mA8JIem
3l/CYLXBdbVvN3sZ/MNvT8Ur6WaA2VLiHV1A4Y3PrJjdwYDstPgjoGIz5BvPZhts
5dfYbCY8hKsw7BvUfCmQbRXTVULq0xJMVx7le71t0TMiYTxD/SC1w2AAIJL11Vrr
yp3cnSwryObwAo3aZ/wF3YfTfyqpuZHRdyQNwMmo5cKnpD7OJFwiACh5m2tDD4y+
L2LMggQpgGt02eH3s8rQxXnLqmB/RVdoiHtgWFneelCEdSTu5f6U+gU6SGYqz/lH
q8ITZc2plAb8TsOr21wN
=g9Jh
-----END PGP SIGNATURE-----
