### ISSUE TITLE
RequestPolicy is incompaible with Firefox 38.0.1

### ISSUE THREAD

**Issue by kristinegood** [nylira/prism-break#1299]
First of all, thank you for maintaining prism-break. I have been slowing replacing proprietary solutions I've used for years with better, privacy-centered, open-sourced one. 

I just updated my Firefox browser and RquestPolicy will not work now. Since it's no longer maintained, is it time to find an alternative?

I found these so far:

[uMatrix](https://github.com/gorhill/uMatrix)

[policeman](https://github.com/futpib/policeman)

[RequestPolicyContinued](https://github.com/RequestPolicyContinued/requestpolicy/)

**Comment by passiflora** [comment]
uMatrix's GitHub page says "Definitely for advanced users." right from start...

from github's graphs RequestPolicyContinued appears to be much more active than policeman

**Comment by Zegnat** [comment]
RequestPolicyContinued was planned to replace it, see #1153. The problem back then was that it did not actually have all functions implemented. You would have taken a step back in functionality quite a lot. Not sure what the state of it is now, but if the old RequestPolicy really no longer works we may not have a choice.

**Comment by nodiscc** [comment]
Hi @Zegnat I help maintaining the [RequestPolicyContinued Github project](https://github.com/RequestPolicyContinued/requestpolicy/) (though @myrdd is doing all the heavy work), so feel free to ask any question.

The current most important problem with RequestPolicyContinued is that it's unable to import custom rule sets from legacy 0.5x versions, and users may not want to lose their rules during the transition. Support for importing old rules will likely be [part of the next release](https://github.com/RequestPolicyContinued/requestpolicy/issues/354#issuecomment-103240962).

The old [context menu entry is gone](https://github.com/RequestPolicyContinued/requestpolicy/issues/353) and has been replaced with a toolbar button/menu, which is an important UI change. It provides the same functionality as the legacy 0.5 menu, except:

There is no support for [strictness](https://github.com/RequestPolicyContinued/requestpolicy/issues/474) in the menu, although you can decide in the prefs if you want domain-level or subdomain-level strictness in the menu actions. This is a global setting though.

The addon has it's share of [bugs](https://github.com/RequestPolicyContinued/requestpolicy/labels/bug), some of which are common with the 0.5x version. Moving the codebase to the 1.x branch (beta version originally available on requestpolicy.com) allowed to get rid of some [legacy version bugs](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=label%3A0.5.x+is%3Aclosed)

I'll get some time to [finish/rework the website](https://github.com/RequestPolicyContinued/requestpolicy/issues/445) next week; it's currently [a bit confusing and incomplete](https://requestpolicycontinued.github.io/) so I suggest you wait until then.

**Comment by Zegnat** [comment]
@nodiscc, give us a nudge when you get the new website up!

I think strictness was the main thing I missed in this version, and if I recall correctly it was what made me say it felt incomplete in the first place. That might just be indicative of my personal usage.

**Comment by myrdd** [comment]
Very well summarized @nodiscc, thank you! Also thanks for *@*notifying me!

@Zegnat I agree with you! IMO Strictness is a very important feature, and I'm missing it as well! I'll try to implement that as soon as possible, but that still means it'll be several weeks as my time is limited.

> I just updated my Firefox browser and RquestPolicy will not work now.

I think it should be possible to have RP 0.5.x installed, see https://github.com/RequestPolicyContinued/requestpolicy/issues/543#issuecomment-100685167. Tell me if I'm wrong, i.e. if it's *not* possible.

----------------

There's one more thing to mention: in fact RequestPolicy should work without any problems. The reason why it's marked as "incompatible with Fx38+" is:

 1. RP isn't maintained anymore and
 2. RP has some problems when [E10s](https://wiki.mozilla.org/Electrolysis) is enabled. E10s is slowly being introduced to Firefox.

Those two reasons led the AMO team to mark RP as incompatible. FYI, the discussion took place at [Mozilla Bug 1077185](https://bugzilla.mozilla.org/show_bug.cgi?id=1077185).

**Comment by Zegnat** [comment]
@myrdd:

> RP has some problems when [E10s](https://wiki.mozilla.org/Electrolysis) is enabled. E10s is slowly being introduced to Firefox.

If I understand the Mozilla wiki pages right, Firefox will not turn on Electrolysis at least until and including version 41. And Firefox version 41 will not be released until 2015-09-22. So why are add-ons being marked as incompatible so many months in advance? Are other add-ons being pulled from AMO as well?

PRISM Break does not require add-ons to be available from AMO. Maybe it would be possible for the RPC website to offer a download of the old RP 0.5 for those who want to keep using it? @nodiscc? Then we can update PRISM Break to link to RPC take AMO out of it completely.

**Comment by myrdd** [comment]
> Firefox will not turn on Electrolysis at least until and including version 41. And Firefox version 41 will not be released until 2015-09-22.

That's correct. But still, the *Release* brach is not the only important one. On the Mozilla Bug they were talking also about Aurora and Beta. If I understand correctly this means, the closer E10s gets to *Release*, the more likely they will mark it as incompatible.

We're currently at Aurora 40 and Beta 39. This means E10s is now available on Aurora.

> So why are add-ons being marked as incompatible so many months in advance?

Jorge Villalobos [wrote in November 2014](https://bugzilla.mozilla.org/show_bug.cgi?id=1077185#c4): *„I marked the existing versions of RequestPolicy as incompatible and also removed the add-on from the featured list, since I don't want to give too much exposure to an add-on that appears to be abandoned.“*

I can understand this policy. However, I've [asked them](https://bugzilla.mozilla.org/show_bug.cgi?id=1077185#c11) to push back the „incompatibility“ to a later version of Firefox. There hasn't been any response, therefore I decided to wait.

> Are other add-ons being pulled from AMO as well?

There are [many addons](https://bugzilla.mozilla.org/buglist.cgi?f1=blocked&order=Importance&o1=anywords&resolution=---&query_format=advanced&v1=905436&component=Extension%20Compatibility) which are blocking the [*e10s add-ons tracking bug*](https://bugzilla.mozilla.org/show_bug.cgi?id=905436). Any of those could have the same problem (not maintained anymore).

> Maybe it would be possible for the RPC website to offer a download of the old RP 0.5 for those who want to keep using it?

That could only be a temporary solution, because Fx40 will introduce mandatory [Extension Signing](https://wiki.mozilla.org/Addons/Extension_Signing). Fx40 will be released on 2015-08-11.
More in detail: Extension Signing means that *all* addons need to be checked by AMO's system. And as I don't have access to the extension ID of *lecacy RP* (which is `requestpolicy@requestpolicy.com`), I'm not allowed to get RP 0.5.x signed.

So if we want to have longer support of RP 0.5, we have those options:

 1. convince the AMO team
 2. get access to the extension ID of *legacy RP*, which is in the hands of justin (creator of RP). I've [tried that already](https://github.com/RequestPolicyContinued/requestpolicy/issues/525#issuecomment-66659238).
 3. fork RP 0.5.x, change its extension ID and upload it to AMO. – I'm not sure whether changing the extension ID is easy enough – I'd like to have as few effort as possible..

**Comment by gorhill** [comment]
@passiflora 

> uMatrix's GitHub page says "Definitely for advanced users." right from start...

I also consider RequestPolicy and Policeman for advanced users, i.e. these add-ons will break web sites. Required warning because of many users installing it and being frustrated that many web sites broke.

**Comment by myrdd** [comment]
I agree with @gorhill, not only uMatrix is for advanced users. However, to me it seems easier to learn RP than uMatrix.

By the way @gorhill, maybe we could consider working together? I don't know yet *how*, but it would probably nice to have a common background api?

-----------

@Zegnat I've now uploaded RPC with a new extension ID to AMO. Let's see what the reviewers say, because RP and RPC **should not** be enabled at the same time. Both use the same pref branches etc.

AMO Link: https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/
Dev branch at: https://github.com/RequestPolicyContinued/requestpolicy/tree/dev-0.5

**Comment by nodiscc** [comment]
@Zegnat the new website is up http://requestpolicycontinued.github.io/, with some bugs https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/issues/

**Comment by Zegnat** [comment]
800a30d mentions uMatrix as a more advanced alternative to Request Policy. 7424bdf updates Request Policy links to the new Continued project. I think I am going with that for now.

**Comment by myrdd** [comment]
@Zegnat FYI, on https://github.com/RequestPolicyContinued/requestpolicy/issues/692 we pointed out some differences between RequestPolicy and uMatrix. One significant difference is that uMatrix doesn't have the concept of "other origins".
