### ISSUE TITLE
no encryption of instant messages in linphone 

### ISSUE THREAD

**Issue by real-or-random** [nylira/prism-break#1302]
It seems that chats are not (end-to-end) encrypted in linphone:
https://lists.gnu.org/archive/html/linphone-users/2013-07/msg00021.html
I cannot tell for sure whether this has changed, because I do not use the current version. The website does not indicate that chats are encrypted.

I think this should be noted somewhere. Currently, linphone is described as "Encrypted voice and video __chat__ client for multiple platforms.". Furthermore, it is in the "Instant Messaging" category, not only in the "Video & Voice" category.

**Comment by juanito003** [comment]
I confirm, text messages (chat) are not encrypted. But the main purpose of using Linphone is not for chat, it's for voice.
When installing linphone on Android (and iOS), even voice chat are not encrypted by default. You should manually activate the ZRTP encryption for calls:
Settings -> Network -> Media encryption. Clic **ZRTP**.

![nsmail3](https://cloud.githubusercontent.com/assets/487038/7705024/197eebaa-fe42-11e4-9f60-d701e69e1b4a.png)

And keep in mind that for encrypted voice with ZRTP, the metadata for the calls (date, time and login) are not encrypted.

For chat you should use another app. I would recommand **[kontalk](http://kontalk.org)** :-)
I know it's 2015 and we don't yet have a unified FOSS app to do chat, voice and video end to end encrypted. Maybe Tox will solve this, maybe we have to wait some more time... until it happen (sad).
Let me know if such a system exist because I'm not aware of any.

**Comment by real-or-random** [comment]
As a cryptographer, I find that sad, too. But that's not the issue.

My point is actually that prism break is misleading here, because it gives you the impression that chat is encrypted.

**Comment by juanito003** [comment]
Yes of course, Linphone and CSipSimple should **only** appear in the section **Video & Voice**.
They should be removed from the section Instant Messaging. I found it weird to see them in this section.
Anyway they are apps to do voice calls, not text chat.

**Comment by Zegnat** [comment]
Nice catch. I simply do not use smartphones for communication that way, so I would never have caught this. Accepting pull requests.

**Comment by juanito003** [comment]
By the way, in the note for **Video & Voice** section below this text:

>Get a free Sip-account for Jitsi and/or CSipSimple with The Guardian Project’s Ostel service.

We could also add:
Get a free Sip-account  with [Linphone Free Sip service](http://www.linphone.org/free-sip-service.html)

This Sip-account with linphone can then be configured in Jitsi and CSipSimple.

By the way, I am very disapointed with CSipSimple, I uninstalled it and replaced it with linphone. Why? Because in the current version on [f-droid 1.02.03-2459](https://f-droid.org/repository/browse/?fdfilter=CSipSimple&fdid=com.csipsimple), the build doesn't include SILK (Skype) support nor OPUS codec. I don't know why they did that but the previous version did support the SILK codec. Linphone now support and use by default OPUS codec with 48kHz for voice quality wich is very good.
