### ISSUE TITLE
Icecat

### ISSUE THREAD

**Issue by szymon1051** [nylira/prism-break#1310]
http://directory.fsf.org/wiki/GNU_IceCat

**Comment by hasufell** [comment]
So they remove trademarked artwork while being considerably slower with security updates? Sound like a silly trade-off.

**Comment by vyp** [comment]
> considerably slower with security updates

?

**Comment by hasufell** [comment]
I was drunk yesterday, so sorry.

**Comment by vyp** [comment]
Haha what. No I meant like if you have sources on how you mean, not saying you're wrong, but that I would like to know about it too. But if not, it's all good.

**Comment by nodiscc** [comment]
I also would like to know more about IceCat. The page says

> The GNU Project keeps IceCat in synchronization with upstream development of Firefox while removing all trademarked artwork [..]

but the download section says

> Download version 31.6.0 (stable) released on 3 April 2015 

But the release version Mozilla Firefox is 38.x. Is this seriously maintained? (serious question) There have been quite a few changes since 31.x (aside new features, there are security and bug fixes). Did those get backported?

Are there binary releases of IceCat for non-free operating systems?

<sup>As I/other people said in https://github.com/nylira/prism-break/issues/1307, https://github.com/nylira/prism-break/issues/1235, https://github.com/nylira/prism-break/issues/1254, https://github.com/nylira/prism-break/issues/1184, https://github.com/nylira/prism-break/issues/1091, I think it would be better to provide a preconfigured/properly patched version of the latest Firefox release instead of replacing it with low-maintenance forks.</sup>

**Comment by vyp** [comment]
@nodiscc Icecat targets the extended support release of Firefox, so even though the latest ESR version is 38, it was "only" released a few weeks ago, so in my opinion it's understandable that Icecat is still on 31 (the previous ESR version). But it needs a new update soon.

The question though is whether *prism break* finds that acceptable.

> Are there binary releases of IceCat for non-free operating systems?

Not that *I* know of (but I don't know very much). In fact, I'm not even sure if there are binary releases for non-*gnu linux* systems. However, I don't think that should hold it back from being listed on at least the GNU/Linux page.

**Comment by vyp** [comment]
Also of note would be the "privacy protection features" listed here: http://www.gnu.org/software/gnuzilla/. It's a little bit different but if I understand correctly it's still just a GNU 'repackaging' of Firefox, much like Iceweasel by Debian.

**Comment by vyp** [comment]
As of 31.5.0 (current is 31.6.0), they *seem* to support binary releases for:

* Windows Vista or newer
* MacOS 10.4 or newer
* Android 2.3 or newer
* GNU/Linux with glibc 2.15 or newer (Debian Testing, Ubuntu Precise).
  - Binaries for Trisquel, Parabola and Fedora will be provided by the distros as usual.

"Seem" because I haven't tried any apart from the Debian and Parabola ones (which were available before as usual).

**Comment by vyp** [comment]
Oh I should clarify my position regarding this issue. I also agree with @nodiscc in that I'd prefer listing an up to date Firefox instead of an ESR one. I don't think #1307 is actually problematic anymore, however, I've been meaning to do some reading on it myself before closing the issue just in case. It's just that I haven't had any time to do so lately (and still will not for at least a few more days). This also goes for #1235, which was also opened by me. If the project maintainers don't want to wait and have chosen for themselves, feel free to close before I (probably will) do.

**Comment by vyp** [comment]
Just tried the android version of Icecat, it works.

**Comment by Zegnat** [comment]
@nodiscc:
> > Download version 31.6.0 (stable) released on 3 April 2015
> 
> But the release version Mozilla Firefox is 38.x. Is this seriously maintained? (serious question) 

@vyp:

>  Icecat targets the extended support release of Firefox, so even though the latest ESR version is 38, it was "only" released a few weeks ago, so in my opinion it's understandable that Icecat is still on 31 (the previous ESR version).

31.6.0 (ESR) was released [March 31, 2015](https://www.mozilla.org/en-US/firefox/31.6.0/releasenotes/). IceCat released theirs on April 3. That’s really quickly. However, Mozilla released 31.7.0 (ESR) on [May 12](https://www.mozilla.org/en-US/firefox/31.7.0/releasenotes/) with additional security patches and to mark the end-of-life for the 31 branch. [Simultaneously](https://www.mozilla.org/en-US/firefox/38.0/releasenotes/) they released 38.0 (ESR).

The current ESR is 38.0.1 from [May 14](https://www.mozilla.org/en-US/firefox/38.0.1/releasenotes/).

IceCat has had over 2 weeks to update to either 31.7.0 or the new 38 branch. They haven’t. This seems to suggest they aren’t always on top of updates even though the previous 3-days-update showed otherwise.

Personally I don’t think PRISM Break recommending ESR is a problem. The Tor Browser Bundle is based on it too IIRC. The real problem is when security patches to ESR do not land in forks in a timely fashion.

Besides this, should we recommend IceCat even if Mozilla is going to offer unbranded versions themselves? (As quickly discussed in #1307.) I don’t seem to see anything about IceCat being more private or secure, other than it going out of its way to recommend Gnu compliant add-ons.

**Comment by mastercoms** [comment]
LibreJS is not very good and breaks a lot of websites.

SpyBlock is just AdblockPlus with preinstalled filters and a slightly different config.

The fingerprinting countermeasures are pixel tracking blocking, which can already be done with uBlock, and only using system fonts.

**Comment by theltalpha** [comment]
> Besides this, should we recommend IceCat even if Mozilla is going to offer unbranded versions themselves? (As quickly discussed in #1307.) I don’t seem to see anything about IceCat being more private or secure, other than it going out of its way to recommend Gnu compliant add-ons.

Definitely it should be recommended. IceCat is not a mere rebranding of Firefox, it has also important privacy improvements. From the 31.2.0 (first release of the current maintainer) release notes:

DoNotTrack header enabled.
 Reporting features disabled (Avoids send data to mozilla's partners 
   about crashes or security related events).
 Disabled "Social API" that brings integration with Facebook.
 Disabled "Safe browsing", which asks Google if websites are safe 
   before browsing them.
 Disabled access to the clipboard from JS.
 Don't recommend online services for IRC.

**Comment by nodiscc** [comment]
@theltalpha all improvements you cited really are options in the configuration file:

 * DoNotTrack header enabled ` user_pref("privacy.donottrackheader.enabled",			true);` 
 * Reporting features disabled `user_pref("datareporting.healthreport.uploadEnabled", false);`
 * Disabled "Safe browsing", which asks Google if websites are safe `browser.safebrowsing.enabled`, `browser.safebrowsing.malware.enabled`
 * Disabled access to the clipboard from JS. `dom.event.clipboardevents.enabled`

"Social API" is an [open standard](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API) and is also used by FOSS tools (eg. [Shaarli](https://github.com/shaarli/shaarli/)). The default available providers list just happens to be https://activations.cdn.mozilla.net/, which lists Facebook as a provider.

**Comment by karme** [comment]
imho firefox (and more frustrating looks like debian's iceweasel, too?)
accumulated way too many insane defaults, to be really recommended.

We really need a browser with sane privacy defaults.

another area to watch out:
ocsp

**Comment by nodiscc** [comment]
> accumulated way too many insane defaults, to be really recommended. 

I wish prism break would not throw an excellent browser away because of bad configuration defaults. Some other software projects recommended by p-b do not have an ideal default config either. https://github.com/pyllyukko/user.js/ does most of the work, it just needs an easy installation process.

So far the only "dubious" feature that has no workaround is the requirement for addons to be signed by Mozilla (the only workaround is to install an unbranded firefox with that feature patched out).

Please make it easy to install sane defaults, not low-workforce forks or less good browsers (at least Iceweasel releases are in sync with upstream).

**Comment by vyp** [comment]
Again, I agree with @nodiscc.

**Comment by Zegnat** [comment]
> Please make it easy to install sane defaults, not low-workforce forks or less good browsers (at least Iceweasel releases are in sync with upstream).

Did you mean to say IceCat, or are we talking IceWeasel now? Is IceWeasel closer to Firefox releases than IceCat is? (Just trying to keep things on track here.)

**Comment by P3lUZa** [comment]
Two very different things, Iceweasel is build from the original source of firefox, basically it is firefox without trademarks - it even has the firefox sync utility for the mozilla servers and the mozilla add-ons market -.

In the other hand, GNU Icecat is a patched version of firefox which removes non-free javascript, removes the mozilla add-ons market and uses its own - composed of pure free software addons -.  and adds several other free plugins

**Comment by mastercoms** [comment]
It comes preloaded with LibreJS, which can be downloaded, and a few about:config tweaks. The addons market change doesn't really matter. Really, there is nothing exclusive on Icecat.

**Comment by vyp** [comment]
@P3lUZa I think Zegnat knows that, he was just asking nodiscc to clarify if he mixed them up, which I do not think nodiscc did.

**Comment by Zegnat** [comment]
Like @vyp said, I am well aware of IceCat / IceWeasel and was only asking because @nodiscc suddenly mentioned the latter in a discussion that was all about the former. My question also still stands, as neither [the Debian wiki](https://wiki.debian.org/Iceweasel) or [their Mozilla Team site](http://mozilla.debian.net) mentions a release schedule.

**Comment by nodiscc** [comment]
I was just comparing Icecat and Iceweasel schedules. The latest Mozilla Firefox release usually appears (as Iceweasel) in the debian repos (http://mozilla.debian.net/) 1-3 days after the official release. Icecat does not seem to be able to keep up with releases, even bugfix/security releases.

**Comment by theltalpha** [comment]
> @theltalpha all improvements you cited really are options in the configuration file:

And how many users downloading Firefox do you think will change these options after installing Firefox? In so far, IceCat is already an improvement in comparism to Firefox.

So far, IceCat has been quite quick following the releases of Firefox. Only exemption was now version 31.7.0, which in the meantime has already been released. The maintainer of IceCat was in the process of moving to another home, which was the reason for delay, so I think we can presume in the future the IceCat releases will follow the Firefox releases as quickly as in the past.

Really, I cannot understand the sudden challenge of IceCat.

**Comment by Zegnat** [comment]
> I was just comparing Icecat and Iceweasel schedules. The latest Mozilla Firefox release usually appears (as Iceweasel) in the debian repos (http://mozilla.debian.net/) 1-3 days after the official release.

Is Iceweasel available outside of Debian? I am not sure how helpful it would be to recommend an unbranded firefox for a single platform on PRISM Break…

> Really, I cannot understand the sudden challenge of IceCat.

There is no sudden challenge, just a long standing one. For as long as PRISM Break has been around people have been writing in asking about different browsers or complaining about the ones that are recommended. I have always (and consistently) said that I do not know of any Firefox forks that were able to keep up with Mozilla’s release schedule, nobody ever showed me otherwise.

If someone had opened an issue that showed how IceCat (or any other fork) kept up with security updates in a timely fashion and added something else in form of security and privacy I would have instantly accepted a pull request.

Overall I am happy we are no longer showing 10 browsers and I would rather not _add_ one. If we can _replace_ Firefox with a more private fork however that would be great.

**Comment by theltalpha** [comment]
Oh, I didn't notice IceCat is not listed or even mentioned any more on PRISM Break. Fortunatelly it still was when I was looking for a suitable web browser about one year ago ...

**Comment by Zegnat** [comment]
> Oh, I didn’t notice IceCat is not listed or even mentioned any more on PRISM Break.

I think it was removed around the same time as some operating systems got removed. PRISM Break was starting to recommend so many different alternatives that we ended up recommending between recommendations. I also seem to recall back then IceCat wasn’t keeping up with the release schedule, but honestly not sure about that.

**Comment by vyp** [comment]
> Is Iceweasel available outside of Debian?

Don't know the full answer but fwiw there's an AUR package: https://aur.archlinux.org/packages/iceweasel/

**Comment by vyp** [comment]
I'm not sure if it's a simple repackaging of a debian package or if the PKGBUILD builds from the source code entirely (although of course there is a build function so it might be the latter). So I guess in theory iceweasel should work for gnu linux systems. However the question is whether the distributions we recommend have done the work to package it (esp a binary), because I wouldn't expect the average prism break visitor to build such a large program.

**Comment by vyp** [comment]
So this is still *really* late and I'm not denying that, but for what it's worth, there is a v38 release now for icecat: https://savannah.gnu.org/forum/forum.php?forum_id=8376. The reason I'm noting it here is because there's been talk of icecat recently and whether or not it's dying/dead. And if that is to be the case, this issue should be closed. But now that there's a new release, this should probably be kept open just to keep tabs on it. Maybe sometime in the future Mozilla will continue to lose their way, making it difficult to use Firefox proper in a privacy conscious way, and maybe by then Icecat will show stable development activity, making it a potentially viable option to recommend. Or maybe not, maybe this is the last Icecat release after which it will die.

**Comment by vyp** [comment]
I'm going to close this for the reasons @Zegnat outlined above. At time of writing, it's been 2 weeks since the latest security related fixes for Firefox ESR, and Icecat has unfortunately not kept up with these security updates. Not to mention the major Icecat version is v38, whereas the latest Firefox ESR major version is v45 (which was released over 3 months ago).

Icecat would have been a good addition in my opinion as having the features that @theltalpha listed by default for a browser is definitely an improvement, but it seems like lately the release cycle frequency is insufficient for Prism Break purposes. Of course, this can be re-evaluated again in the future if Icecat update times improve.
