### ISSUE TITLE
Iridium Browser

### ISSUE THREAD

**Issue by mastercoms** [nylira/prism-break#1311]
https://iridiumbrowser.de/

Chromium based browser. Supposedly secure, though I haven't checked it out thoroughly enough.

Source available at https://downloads.iridiumbrowser.de/source/
Git repo available at https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/

Misc dev files, including diff at https://build.netitwork.net/package/show/iridium/iridium-browser

**Comment by tristan-k** [comment]
For further reading see this [comments](https://news.ycombinator.com/item?id=9482689)

**Comment by vyp** [comment]
@tristan-k Is that supposed to be an argument for or against, if at all?

**Comment by tristan-k** [comment]
@vyp I'm just pointing to some information, which might be useful for forming an opinion. 

I also stumbled over a set of patches for chromium which promise to `focus on privacy by disabling data transmission to google`. You can read more about it [here](https://bbs.archlinux.org/viewtopic.php?id=198763). It originates from a [Archlinux AUR](https://aur4.archlinux.org/packages/inox/) but the pachtes are availabe to [download](https://aur4.archlinux.org/cgit/aur.git/snapshot/inox.tar.gz). I created a thread at [askubuntu](https://askubuntu.com/questions/647137/inox-browser-build-and-patch-chromium-from-source).

**Comment by vyp** [comment]
@tristan-k No worries, because the general feeling of that thread (I feel) is negative, hence why I asked.

Inox is also a good find. About building for ubuntu, are familiar with arch linux PKGBUILDS, because the PKGBUILD for inox can be a starting point, even though it's very involved.

**Comment by tristan-k** [comment]
@vyp I also noticed that vibe. No, I'm not. I really would like to learn more about all the Archlinux stuff, but I haven't got the time for it.

**Comment by vyp** [comment]
@tristan-k I can't help much because the PKGBUILD is doing a lot of things. But in general a pkgbuild is just bash script syntax. Mostly 3 main parts, the metadata variables at the top, the `build` function, the `package` function. On arch linux the command `makepkg` looks for a PKGBUILD file and runs it as a bash script but also automatically runs the `build` and `package` functions.

Inox's pkgbuild also has a `prepare` function, which is probably run before `build`. I think the main part you would be interested in for building for ubuntu would be the "Apply Inox patches" section. Also take note of the variables used. Some variables (such as `srcdir`) are implicit ones defined by the `makepkg` command (I think), so you might need to figure out what to replace that with.

Lastly, you might already know this, but you don't have to download the tarball, but can just `git clone https://aur4.archlinux.org/inox.git/`. Note that this does not download chromium with it. If you look in the `source` variable in the pkgbuild, there's a list of filenames, which you get when cloning as mentioned above. But there's also two urls (chromium itself from google, and something else). These are downloaded by `makepkg` prior to running any of the functions defined in the pkgbuild.

Don't rely on my information though, I'm definitely no expert. If you find the time, consult the [arch wiki](https://wiki.archlinux.org/index.php/PKGBUILD) instead for a better understanding.

**Comment by hasufell** [comment]
made one for gentoo https://github.com/hasufell/prism-overlay/tree/master/www-client/inox

I am not 100% sure what compile-time configuration these patches expect, so I just added the diff of the PKGBUILDs which is basically

```
    -Denable_webrtc=0
    -Denable_google_now=0
    -Denable_remoting=0
    -Dsafe_browsing_mode=0
    -Denable_rlz=0
    -Denable_hangout_services_extension=0
    -Dbranding=Chromium
    -Dgoogle_chrome_build=0
    -Denable_web_speech=1
    -Denable_wifi_bootstrapping=0
    -Denable_speech_input=0
    -Denable_pre_sync_backup=0
    -Denable_print_preview=0
```

**Comment by wilfried18** [comment]
Iridium not disponible archlinux

**Comment by Kamaluk** [comment]
Iridium doesn't call google on Mac!

**Comment by strugee** [comment]
@Kamaluk how do you know that it doesn't phone home to Google? Are you sure that it will never do that, under any circumstances? Are you sure it will never do that on any platform?

It's not on PRISM Break because no one has researched it in-depth enough to consider it.

**Comment by hasufell** [comment]
> how do you know that it doesn't phone home to Google?

counter-question: how do you know firefox doesn't phone home to Mozilla? As in: are there actual audits or is this "just" community consensus that firefox is secure enough? Remember that torbrowser applies a _massive_ patchset to firefox and is practically a fork already.

Doing some extensive network monitoring would be a start to catch unobfuscated home-phoning.

Also, I think we shouldn't magnify firefox as the bastion of web browser security and more seriously consider alternatives like [inox](https://github.com/gcarq/inox-patchset) or [ungoogled-chromium](https://github.com/nylira/prism-break/issues/1516) for inclusion. I stopped using firefox a year ago or so, because of various usability and performance issues and those things matter too.

**Comment by strugee** [comment]
@hasufell not sure that this issue is the right venue fur this discussion, but since you asked: generally speaking I think we trust Firefox because Mozilla documents all the cases where it connects to the network and how to disable those cases: https://support.mozilla.org/en-US/kb/how-stop-firefox-making-automatic-connections

I also just generally trust Mozilla to only phone home when necessary and in a privacy-preserving way a lot more than I trust Google for the same thing.

**Comment by hasufell** [comment]
Well, you asked

> how do you know that it doesn't phone home to Google?

and your following answer is not a good argument for the same question wrt firefox:

> I think we trust Firefox because Mozilla documents all the cases where it connects to the network

Who has verified it?

IMO, the trust grounds for firefox are more or less the same as with projects like inox/iridum-browser: We suspect there are people caring about privacy, but we haven't done an actual in-depth review. Tor is practically a full fork and can't hold as an argument.

Feature-wise (adblocker, ublock origin, ...) chromium forks offer the same functionality as firefox.

**Comment by hasufell** [comment]
The security report from Menlo on [State of the Web 2016](https://www.menlosecurity.com/hubfs/pdfs/Menlo%20State%20of%20the%20Web%202016%20Dec12.pdf?t=1481642038948) suggests users to

> Use the Chrome browser – Amongst browsers,
Google Chrome has a higher degree of focus
on security, and more importantly, contains an
implementation of Flash that is highly restrictive

Ofc, that suggestion should be adjusted to "Use a hacked Chrome browser like Inox/ungoogled chromium...".

I think that's another argument pro listing one of these.
