### ISSUE TITLE
Add Signal

### ISSUE THREAD

**Issue by Schweineschwarte** [nylira/prism-break#1314]
What's with the open source programm „TextSecure“? It's an alternative for WhatsApp and it's opensource (GPLv3). It encrypt messages as standard and features forward secrecy and deniability guarantees.

Furthermore, it gives an audit about Textsecure from the Ruhr University Bochum with the result: "Furthermore, we formally prove that—if our mitigation is applied—TEXTSECURE’s push messaging can indeed achieve the goals of authenticity and confidentiality."

https://en.wikipedia.org/wiki/TextSecure
https://github.com/WhisperSystems/TextSecure
https://www.whispersystems.org/blog/advanced-ratcheting/
https://eprint.iacr.org/2014/904.pdf

**Comment by mastercoms** [comment]
Duplicate of #896

**Comment by juanito003** [comment]
**Long story to read about TextSecure:**
[Secure Texting and why FSFE cares](https://blogs.fsfe.org/h2/2014/06/25/secure-texting-and-why-fsfe-cares/)
[Secure Texting Part II](https://blogs.fsfe.org/h2/2015/02/23/secure-texting-part-ii/)

**Short story to read about TextSecure:**
*We knew that TextSecure depended on Google Play Services last year, but we were hoping that this was a temporary problem, as virtually every other messaging app in existence has a fallback mode for delivery that does not require proprietary (Google) components. Unfortunately we were wrong: nearly a year later the development of a websocket based version of TextSecure has stalled. Lead developers at WhisperSystems have stated repeatedly that it is not important to them, and the many requests, tests and code contributions from external people did not result in the situation now being any better than it was a year ago.*

*Furthermore WhisperSystems has repeatedly demanded other people not distribute modified and unmodified versions of their software. While I believe that WhisperSystems is sincere about security, they seem to have no problem with the security implications of proprietary software, sharing meta-data with Google (by means of Google Push) and now working for WhatsApp / Facebook. This is all a sad example for a project that does license its code under Free licenses, but that otherwise is between uninterested and hostile towards community involvement and the Free Software landscape.*

#1333 to read about the new fork of TextSecure called SMSSecure.

**Comment by mattdale77** [comment]
Tectsecure is now Signal on both iOS and on Android. Is the iOS version any better as it obviously doesn't rely on Google play services. Now that they've finished the migration to Signal perhaps they would give more weight to getting away from Google play services on Android

**Comment by strugee** [comment]
@mattdale77 The iOS version is way, way worse than the Android version, because you're running it on a proprietary operating system that has the exact same class of problems as Google Play Services, just with a different name.

As for them migrating away from Google Play Services, I doubt it. Moxie has made it very clear in the past that he doesn't care in the slightest about software freedom, and I highly doubt he's going to start now.

**Comment by alerque** [comment]
@strugee That's a little unfair. There is a difference between not caring in the slightest (which makes it sound like he's adverse to OSS in general) and giving priority to pragmatic considerations. Maybe Moxie's architecture choices don't align with PRISM-Break's objectives—I wish they did—but lets not make it sound like he's an enemy in this equation.

**Comment by strugee** [comment]
@alerque Good point. I still have serious reservations about how Moxie deals with the free software community, but I certainly don't have the whole story and I can't know exactly how he feels. I take it back.

That being said, the point still stands: we both know Moxie isn't going to get rid of Google Cloud Messaging anytime soon.

**Comment by juanito003** [comment]
Just for reference to this thread we can read Moxie's point of view about F-droid and Google here, 
https://github.com/WhisperSystems/Signal-Android/issues/127

I think the only current solution left is to build the Signal android app from the source. Did someone already tried? Is it working on a cyanogenmod device without gapps?

I'm gona try myself when I found some time.

**Comment by mattdale77** [comment]
It's good to see his point of view on it and it is fairly understandable.
He's set out some fair goals for F Droid for it to be viable.

I've also been in another case that the server end is already web socket
capable but needs a push architecture that scales as well as google cloud
services in order to migrate. It's a shame but I can understand trying to
keep the app reliable for everyone.

**Comment by juanito003** [comment]
**Here directly from the FAQ:**
http://support.whispersystems.org/hc/en-us/articles/213190817-Why-do-I-need-Google-Play-installed-to-use-Signal-

I would be interrested if someone writes a blog post to explain how to build successfully for android 4.4
Just to let you know, I tried to build from the source (BUILD FAILED). It seems many ressource are missing. I am not an android dev, I know others will figure it out.

**Comment by 1337sup3rh4x0r** [comment]
A websocket Version that is on fdroid can be found here: https://github.com/JavaJens/TextSecure

**Comment by phiche** [comment]
What is the point of this whole project? Is it to inform people about better, more secure means of communication than what Apple/Google/et al. offer by default, or what?

**Comment by strugee** [comment]
It occurs to me that we could possibly list Signal if we recommend users use an alternate GCM implementation. For example microG* seems to provide this: https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation

In that case, how would people feel about listing Signal? Note that the GCM payload contains only a wakeup notification; data is retrieved directly from the OpenWhisperSystems servers. That means that essentially the only metadata leaked to Google is when someone texts you or calls you in Signal - not who it was, what it said, etc. That's not _nothing_, but it seems acceptable to me (especially given that e.g. SMSSecure leaks _far_ more metadata than that). IIRC (without re-reading the several long threads on this subject) the main problem we had was Google Play Services' on-device tracking of e.g. location - this would solve that problem.

 \[*]: I just picked microG at random - it's alpha software and we'd have to discuss, research alternatives, etc.

**Comment by alerque** [comment]
@strugee This was discussed somewhere (I can't remember where) and as I recall there was some unsettled agreement that could work, but there was another blocker in the call component of Signal not being licensed the same open way the messaging component is. If we did list it it would also have to come with a big caveat about anonyminty because of the phone number uid thing. I'm not sticktly opposed per se (I use Signal myself) but it would be a dodgy recomendation on a few levels.

**Comment by strugee** [comment]
@alerque OK, that's good to know. IIRC the last major discussion we had was in the TextSecure/Redphone days, so someone should check if Signal has the same licensing issues.

**Comment by strugee** [comment]
Also relevant: WhisperSystems/Signal-Android#5975

**Comment by rZsnWwM5** [comment]
I think Signal can now be added to Prism-Break since it's officially Google-free. So far, the main reason for why Signal hasn't been added to Prism-Break has been the Android client's dependency on Google Play Services. Before February 20, people had to have Google Play or microG on their phone for Signal to be fully functional, and before March 13, people had to compile the app themselves if they wanted to install it on a device that didn't include Google Play. Signal is no longer dependent on the GCM push messaging framework, and the Android client can now officially be downloaded and installed from outside of the Google Play Store: https://signal.org/android/apk/

The discussion about Signal's voice calling component's backend not being open source is now obsolete, because Signal has completed the transition from RedPhone to WebRTC. Signal's backend is now fully open source: https://github.com/whispersystems

**Comment by mimi89999** [comment]
@rZsnWwm5
I am not convinced.

1. Signal can't be distributed over F-Droid (the recommended place for getting apps).

2. The app contains the lib for GMS and it is proprietary, so the entire app is against GNU's free software definition.

3. Signal services are centralized and Signal relies on phone numbers


Until those issues are discussed, I am completely against adding Signal to prism break recommended software.

**Comment by hasufell** [comment]
> Signal can't be distributed over F-Droid (the recommended place for getting apps).

Imo, only a show-stopper if you can't download apk files manually, which it seems you can. F-Droid isn't particularly reliable anyway and some software there is extremely outdated just because they can't manage to fix their automatic build server.

> The app contains the lib for GMS and it is proprietary, so the entire app is against GNU's free software definition.

Can you elaborate? Also see https://www.gnu.org/licenses/gpl-faq.en.html#SystemLibraryException

> Signal services are centralized and Signal relies on phone numbers

Wrt centralized: important, but the goal isn't anonymity anyway, is it? We're recommending other stuff that a) at least advertises centralized servers (e.g. Conversations) or b) is at best semi-decentralized anyway (E-Mail). So the question is if we consider that a show-stopper argument.

Wrt phone numbers: Don't Silence and Kontalk also rely on phone numbers? We recommend them too.

I'm not advocating for Signal here, I'm just trying to get more information/consensus.

**Comment by mimi89999** [comment]
> Imo, only a show-stopper if you can't download apk files manually, which it seems you can.

Yes, but updates have to be installed manually by visiting the website on every new release

> just because they [F-Droid] can't manage to fix their automatic build server.

I don't know about any issue with that. If releases are properly tagged (in git), everything is automatic.

> Can you elaborate? Also see https://www.gnu.org/licenses/gpl-faq.en.html#SystemLibraryException

Sure. 🙂
> PRISM Break follows the GNU/FSF definition of Free Software

From your README. Since the app does contain proprietary GMS libs, it makes it non-free. We can't really say it is a system library because Replicant doesn't have gapps like a lot of other ROMs.

As for being centralized, yes email is semi centralized and Riot and Conversations are recommending their servers, but one can choose a server or even host his own and talk to people on other servers. In Signal, it is impossible.

**Comment by strugee** [comment]
> Imo, only a show-stopper if you can't download apk files manually, which it seems you can. F-Droid isn't particularly reliable anyway and some software there is extremely outdated just because they can't manage to fix their automatic build server.

Not that I've looked thoroughly, but anecdotally I haven't seen any F-Droid apps that are out-of-date because F-Droid wasn't building new versions. I _have_, however, seen apps that are out-of-date simply because upstream is abandoned. It's also worth noting that, should Signal ever be distributed over F-Droid, it'll probably be kept up-to-date since Signal is such a high-profile project.

> Wrt phone numbers: Don't Silence and Kontalk also rely on phone numbers? We recommend them too.

:thumbsup: was going to say the same thing. We could add a note, I suppose...

> From your README. Since the app does contain proprietary GMS libs, it makes it non-free. We can't really say it is a system library because Replicant doesn't have gapps like a lot of other ROMs.

But Replicant is semi-unusable without Google Play Services. It's big enough and standard enough in Android that I think it would qualify as a Major Component. That would make the library bundled with Signal a System Library. (See https://github.com/WhisperSystems/Signal-Android/blob/3d28db3453628e0c2bdb8faee48ade8c50c11b24/LICENSE#L123 for the definitions of these terms, bearing in mind that I'm obviously not a lawyer.)

That being said, we may want to reject Signal over licensing issues even if it _technically_ is completely free software.

> As for being centralized, yes email is semi centralized and Riot and Conversations are recommending their servers, but one can choose a server or even host his own and talk to people on other servers. In Signal, it is impossible.

I'm with you in theory. But Signal provides such a good experience, and the network effect is so strong, that to me it's worth it.

**Comment by alerque** [comment]
> ... we may want to reject Signal over licensing issues even if it technically is completely free software.

Nope. At this point I think we're doing the world a dis-favor by not listing Signal. Yes there are  points that are less than ideal (user ID being phone number and authentication via SMS being the stand out one to me) but the nit picks about licensing and distribution are down to the level of trivial and should not be blockers. If we had a rating system it would get bad marks in some areas but compared to the _other_ compromises people have to choose from it's getting to the point of silly that we aren't listing it.

**Comment by strugee** [comment]
Sorry, let me clarify what I meant by that remark. I was pointing out that we _could_ make that argument and we should have that discussion. But I personally would agree with you that it's not worth it and we should go ahead and list Signal.

**Comment by hasufell** [comment]
> Yes, but updates have to be installed manually by visiting the website on every new release

Again: is that a show-stopper? If you're lucky you get one F-droid build and then none for 6+ months, because it didn't build? ;)

I'm not saying it's not bad, but F-Droid doesn't magically solve those problem. Only Google Play is actually reliable, which we don't want to use.

So how do we go about this?

> I don't know about any issue with that. If releases are properly tagged (in git), everything is automatic.

You mean like outdated VLC? 
https://f-droid.org/forums/topic/vlc-outdated/
https://gitlab.com/fdroid/fdroidserver/issues/224

As you can see from this (and other threads), this is a problem with their build setup using ancient debian versions. And this isn't the only app with that problem, just the one that was the most annoying to me.

They also seem unable to build [zom](https://f-droid.org/wiki/page/im.zom.messenger).

Also remember the Firefox situation... it's at version 50.1.0, probably vulnerable as f*ck and F-Droid suggests you to either manually download stable releases every time or use half-broken development versions that auto-update. Soo...

> As for being centralized, yes email is semi centralized and Riot and Conversations are recommending their servers, but one can choose a server or even host his own and talk to people on other servers. In Signal, it is impossible.

Well the server is opensource? https://github.com/WhisperSystems/Signal-Server
But as I understand it, you'd be cut off from the rest of the network though, so it's not like jabber.

Again: is this a show-stopper? Decentralizing is clearly not within their scope and I'd argue any system that does not have a strong focus on P2P and decentralization doesn't make mass surveillance of certain metadata particularly difficult (including jabber and e-mail and lots of other stuff we recommend). This seems more to be about data-channel security. Is that a reason to not list it?

Also stumbled over https://blog.grobox.de/2016/is-signal-a-threat-to-free-software/

**Comment by Hillside502** [comment]
> If you're lucky you get one F-droid build **and then none for 6+ months**

Correct!

> Only Google Play is actually reliable

Correct, unfortunately!

**Comment by mimi89999** [comment]
@hasufell 
> They also seem unable to build Zom.
The build was manually disable waiting for the other side to provide F-Droid a way of verifying builds (for reproducible builds).

> Also remember the Firefox situation... it's at version 50.1.0, probably vulnerable as f*ck and F-Droid suggests you to either manually download stable releases every time or use half-broken development versions that auto-update. Soo...

Firefox doesn't meet the policy so it has to be removed. There are alternatives like Icecat, Fennec F-Droid and Orfox. If one wants vanilla Firefox, he has to get it from somewhere else.

As for VLC, building it is very difficult and hard to automate. It's not the standard gradle build that works very well...

**Comment by hasufell** [comment]
> If one wants vanilla Firefox, he has to get it from somewhere else.

Same for signal.

**Comment by mimi89999** [comment]
@hasufell 
>>If one wants vanilla Firefox, he has to get it from somewhere else.

>Same for Signal.

There are 2 good forks of Firefox in F-Droid. One is Icecat and one is Fennec F-Droid. I am using Fennec and it is very good and always up to date.

As for Signal, I made a fork called LibreSignal that met F-Droid criteria and I was maintaining it, but Moxie didn't like it, so I had to leave it.

So that is not the same.

**Comment by hasufell** [comment]
A quick look on prism-break stuff I use(d) or find interesting on android:
* latest Riot doesn't build https://f-droid.org/wiki/page/im.vector.alpha#0.6.9
* linphone is badly outdated and doesn't build since quite some time: https://f-droid.org/wiki/page/org.linphone#3.2.4-fdroid
* I2P is slightly outdated
* latest stable NextCloud version doesn't build https://f-droid.org/wiki/page/com.nextcloud.client
* firefox: outdated, probably vulnerable, still not removed
* git-annex isn't even on f-droid (probably others as well? didn't check all recommendations)
* zom doesn't build at all, but isn't recommended currently

To close up this almost derailed sub-discussion: I don't think we should care too much about F-Droid as a requirement for inclusion. A more detailed note about the implications of not using up2date Google Play might make sense, so users know the drawbacks when using a) F-Droid or b) manually downloading apks.

**Comment by mattdale77** [comment]
I like and use Fennec but it is hardly up to date with the current firefox.
I'm on 48 and I believe the current version of firefox is 52.0.1 which
makes it 9 months behind the current version. Pretty sure it could be kept
closer to the main version.

**Comment by hasufell** [comment]
And [IceCatMobile](https://directory.fsf.org/wiki/IceCatMobile) is based on an old Firefox ESR with a note "Antifeature: Update needed" on the website :P

**Comment by mimi89999** [comment]
@mattdale77 Latest version of Fennec in F-Droid is 52. You need to have the archive repo enabled because Fennec is in the archive repo.

**Comment by mattdale77** [comment]
Thanks for letting me know that. I obviously misunderstood the purpose of
the archive repository. Why is Fennec not in the main repo?

**Comment by hasufell** [comment]
@mimi89999 According to your own post https://github.com/nylira/prism-break/issues/1661#issuecomment-288369657 it seems the linphone version [F-Droid ships](https://f-droid.org/wiki/page/org.linphone) is vulnerable?

https://www.sufficientlysecure.org/2017/03/15/zrtp.html

> We found a security vulnerability in Linphone (CVE-2016-6271) that has been responsibly disclosed on 07/05/2016 to Belledonne Communications and fixed in Linphone 3.2.0.

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-6271

**Comment by mimi89999** [comment]
@hasufell It can't be updated because it looks like source of one lib is missing.

**Comment by hasufell** [comment]
> It can't be updated because it looks like source of one lib is missing.

What lib would that be? Are you saying this is again not an F-Droid build server messup?

**Comment by mimi89999** [comment]
@hasufell 
> Latest Riot doesn't build https://f-droid.org/wiki/page/im.vector.alpha#0.6.9

Built

**Comment by strugee** [comment]
That's nice, but it doesn't solve the systemic issues with F-Droid: updates are often delayed and occasionally non-existant; F-Droid doesn't properly communicate that fact to users, even if they're shipping apps with known security vulnerabilities; and the quality of apps in F-Droid is often low.

Given the above, plus the fact that "packaged in xyz" isn't a requirement on the desktop and we should have the same standard on Android, I think F-Droid inclusion is moot in this discussion.

Given that Signal can now be used without installing gapps, and the only significant drawback is the centralized architecture, I think the usability win is worth including this. Marking as accepting PRs.

**Comment by mimi89999** [comment]
That's only one of the issues I mentioned.

**Comment by hasufell** [comment]
> That's only one of the issues I mentioned.

The only remaining issue is the proprietary GMS lib. It has been suggested that people use [microg](https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation). The question is, would that even work, when the GMS lib is bundled? I don't really know how things are architectured/packaged there.

**Comment by mattdale77** [comment]
Is the library actually used or is it just bundled as a legacy? If it's never called is its inclusion a hurdle?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Regarding F-Droid, it should be noted that F-Droid can refer to both a
client and a server component.  It is, to my knowledge, entirely
feasible for the Signal folks to run their own F-Droid repo, which
would seem to bypass all of the issues mentioned about the main
F-Droid repo lacking updates.  In fact, this is exactly how Orfox is
distributed: Guardian Project runs their own F-Droid repo.

Given that manually installing APK's puts users at risk of not getting
updates, maybe we should at least consider the question of whether
Signal should distribute their APK's via an F-Droid repo?

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJY3OgQAAoJELPy0WV4bWVwe9gQANKunBVL62RBoQGgZUQX4cNE
GSuCeBogPjgTfxYvRGgkNaMKk+RKsRoU3JIU+XIcHpomScEfrkLucpENwInsL8sT
hotCV0lQfVt7+5lzAsxrx0NYfReKvWq0VvJV1gi9GuHaW/n6N9kEReNWae3yFdxS
lpTBb/v+nJYMdSvNOMcm4VX9J9rIlQwrxxtmeW3MXnabx50v0RUVfDGGdARcb68L
d+ja657fCTxw8c/qcoEn/Ekzp53fWsj343/b3WjkeG+7J+4QQw3SmKTMmGD5e8Sr
Ry5t4baEcX42zKMh09Mw22iKEmFNSQ3TWbaTTpAXwS5vMVImhs72Rj87pg8C+DWK
s22dzYe2CYqYxYWHXoGDS0Gou4avXpAZoVjsUEqU9vnAYP2BpikrM0YhH0uQ8Use
aBA9HTw3oYdTH8lZXHKUXCxPQ/VJ5BKh0MLa2pwn/L6r0MHj8vXMTzdYJ5XWgHN4
7HSAV6N8g40YJ/RY2yhhVolc1VyOlsqbGi3EP3WDo344vqnN8NcCrGMkj6qaiJDR
8kWFi8Qu23lf5fbUtnGeNFbjBsV1XotEo3QznHaU7lRZBXaOi/IztfOYTFLWxcEP
iwy01hpgIMLt///J9IZv5BTy7/VN5+OCn2HNGltw7VDU3Vn1lC0cmlbTTJARHAFA
KPk2n7QOEO2yCS6riYzQ
=ug5L
-----END PGP SIGNATURE-----

**Comment by hasufell** [comment]
> maybe we should at least consider the question of whether
> Signal should distribute their APK's via an F-Droid repo?

That's something you have to discuss on their issue tracker, not on this one.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Julian Ospald:
>> maybe we should at least consider the question of whether Signal
>> should distribute their APK's via an F-Droid repo?
> 
> That's something you have to discuss on their issue tracker, not on
> this one.

My understanding is that this was proposed years ago and the Signal
folks decided not to.  I'm not sure whether that's changed, but it
seems to be relevant to whether it should be recommended on PRISM
Break.  (Not saying that it should change the result of the
discussion, only that it seems to be worth taking into consideration
along with the other factors.)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJY3O8SAAoJELPy0WV4bWVwMrMQAJK+sGXQNZfKRZ9dbI66Ctx5
69kvq4xYAvoCXyPo0lqmIctnw5iSOZQIE7fihsa/05M2yaZhhYRedKd8TVuW+xS+
XyHRxRDRxOo9gwU+nVOdF6bTLmAD99x3Zi+zhNRACSpFh0A4Dfqkb00/hWPsJlNo
cI9P1AQVefclG2x8KiZqlGnvUOvMJmvyNR8BmJ3hrAeEzf1VKLjoltzjvLN8zzzq
vfcn0KyQedDis8F6sMAMkjOM69qVnDe7xI5T203WJ3wh1LayaZdLVfNEqlCqGBpG
i+8DB0MnCHzUc0lWmX3S6v27BrDRhGHWYrELyBlQhUrkZjzdeL4j3RWemWppz0/s
HxjkUP8LlEe+jEWYvIGRncuKBDL7fhdITdPXKsldhnp4Ro/yUGdCNDKBpVrqqP/z
+cM54if5jBEPcrQT2FZMFm2nDxu5CB1SfNbu5Ezyq0PaQuk+JGS0Q8fwtxSoYDp1
5orzh1Z67nzwU6gIh0LF5VtK73OGpH3DjHxCBUPAWTOB3gxOl/QcQ6/bt0Aiv9u4
tiUJrUSKKSJHqxfFZP+d3tEfrUUMD8idymgBTV1Iw5ruVS5jVkiTq95XrChBm6MH
uo5BZjowPJO/rgOMWtyljQfIcQYELJ4giNp9JOucDsLkm5Pmh/Xz2y8IY4Ulee6t
S9rJ5+P4nQWi3+0kvL7+
=iQ4T
-----END PGP SIGNATURE-----

**Comment by hasufell** [comment]
> I'm not sure whether that's changed, but it
> seems to be relevant to whether it should be recommended on PRISM
> Break.

We're running in circles. We've already established that "is packaged on F-Droid" is not a requirement. That is as arbitrary as saying "must be packaged on Debian" on desktop systems.

In addition, afais there's an auto-update in-place or coming anyway https://github.com/WhisperSystems/Signal-Android/commit/9b8719e2d56a098502475bb5b2295c7a376d4caa

**Comment by strugee** [comment]
Removing "accepting PRs" until we talk about the bit about the GMS library being included (which I forgot about when I wrote https://github.com/nylira/prism-break/issues/1314#issuecomment-289873948; sorry).

That being said: let's stop debating the F-Droid aspect. That won't be a criterion for inclusion, so let's stop wasting time discussing it.

**Comment by d75f37f758** [comment]
What's the status here?
Signal Messenger is available without Google components and they are providing an official apk on their webpage, so nobody needs Google Play to install and use it.

See also #1672.

**Comment by strugee** [comment]
@d75f37f758 read this issue. The problem is that, last we checked, Signal is _not_ available without a bundled Google library, even if that library isn't actually used. If you have a reference that shows otherwise, please feel free to show us.

**Comment by jinformatique** [comment]
@strugee I disagree. You can have a working Signal app without gapps by downloading the .apk in the danger zone on this page:
https://signal.org/android/apk/

**Comment by strugee** [comment]
@jinformatique when I said "bundled Google library" I meant bundled _in the apk itself_.

**Comment by AliKarpuzoglu** [comment]
Signal is no longer using Google play services

**Comment by strugee** [comment]
@AliKarpuzoglu please read https://github.com/nylira/prism-break/issues/1314#issuecomment-315648723.

**Comment by anthologist** [comment]
Imho if Signal has not to be included as long as it relies on GCM, this issue should be closed.

**Comment by strugee** [comment]
Signal doesn't "rely" on GCM any more per se.

What needs to happen here is for someone to check into https://github.com/nylira/prism-break/issues/1314#issuecomment-315648723 to see if it's actually true.

**Comment by Hillside502** [comment]
> The safest and easiest way to install Signal for Android is through the Google Play Store.

https://signal.org/android/apk/

Signal is effectively discouraging apk downloads!

**Comment by strugee** [comment]
@Hillside502 yeah, I have no problems with that. For people who already have Google Play, i.e. most people, downloading it through the Play Store is much easier. And probably safer, since then updates are automatic.

**Comment by Zegnat** [comment]
> Signal is effectively discouraging apk downloads!

As discussed in #1915, it’s neither unsafe nor unacceptable for applications to prefer a specific point of distribution. And as mentioned in #1924 there is some developer signing going on with the Play Store that may add some minor security over just a bare APK download.

**Comment by yegortimoshenko** [comment]
Signal doesn't have any proprietary code bundled into the APK. I've unpacked it and here is the listing: https://gist.github.com/yegortimoshenko/ecf1750f63e1e34f8d63a31888e868e5

Let's mark this as "help wanted", Signal is really user-friendly, secure and overdue ;-)

**Comment by quantumpacket** [comment]
Does signal still require a phone number as identification?

**Comment by yegortimoshenko** [comment]
Yes, so XMPP + OMEMO is preferable. That said, we list Kontalk, which uses XMPP and identifies via a phone number, so it's not a criterion for inclusion, at least not one that has been established yet.

**Comment by yegortimoshenko** [comment]
Notably, Signal identification doesn't require a SMS-capable phone, being able to receive calls works, so with some effort it's possible to get a relatively anonymous Signal account, but then, Signal doesn't support Orbot (unlike Conversations).

**Comment by RafalBabinicz** [comment]
@yegortimoshenko your listing shows binaries (*.dex). Signal’s source code also shows¹ that WS bundle Google blobs into APK and apktool decoding also shows them. GoogleCloudMessaging is in that APK.

¹ https://github.com/signalapp/Signal-Android/blob/4.19.0/build.gradle#L68-L70

**Comment by yegortimoshenko** [comment]
You're right. I've opened `classes2.dex` in a text editor and it has references to GoogleCloudMessaging. I am not familiar with Android packaging and thought that blobs would be clearly separated from the package itself, sorry.

Then let's close this, based on our inclusion policy. Either way, would be glad to have this resolved.

**Comment by anthologist** [comment]
Thanks @RafalBabinicz , that's what I was saying some post above.
As long as we don't accept apps with GCM, this issue should be considered closed imho.
XMPP + OMEMO is much better.

**Comment by yegortimoshenko** [comment]
I'd tend to agree with that software should not be accepted if it contains proprietary blobs.

While seemingly Signal is free software, freedoms are constrained by the fact that Moxie forces forks to not use Signal's servers: https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217231557

And I'd argue, so much so that for all realistic intents and purposes it makes Signal proprietary with source code availability. For example, I'd be willing to remove those dependencies from Signal and contribute my fork to F-Droid, but it won't ever be accepted because of upstream's opinion. So there is no realistic way to distribute a fully free version, or actually any version different from Moxie's whatosever.

**Comment by Hillside502** [comment]
> I understand that Signal has very good UX

Except for the fixed height (4 lines) in the Compose window.

**Comment by yegortimoshenko** [comment]
Closing based on FLOSS inclusion policy :-(

**Comment by alerque** [comment]
I'm sorry I'm a month behind here and working through a backlog, but I would actually like to register an objection to this one and ask that the issue be re-opened for now. Compared to other less than ideal licensing situations we have allowed this one has become relatively small. And I seriously think we're doing a dis-service by not listing it here. Having some caveat messages might be in order, but I think we're hurting people more than helping them by not listing it.

**Comment by yegortimoshenko** [comment]
OK, but I believe that aggressive upstream policy towards alternative distribution channels such as F-Droid, and realistically inability to make a custom build and distribute it ruins it. Also, the fact that it's centralized doesn't help.

**Comment by alerque** [comment]
Thanks for re-opening. I'll try to work on a more complete case for why I still think we should list this, but I appreciate having the issue kept open for now.

And I do agree those issues make me grumpy too (I've even personally corresponded with Moxie and whined over them), but I don't think they are necessarily blockers here. If they were –and by similar logic– then I would also say we have to remove all Windows, Mac, and iOS applications from our lists. We have a history of making compromises and recommending things out of pragmatic expediency so people actually their hands on something they can use. Obviously that isn't the _only_ principle we go by and we have to draw the line somewhere (source code availability being one of them) but I don't think the current issues that make you and me both grumpy actually cross any of our lines in the sand.

**Comment by mattdale77** [comment]
Why was this reopened for good reason then closed again without further discussion? 

On 16 June 2018 12:46:56 BST, Yegor Timoshenko <notifications@github.com> wrote:
>Closed #1314.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nylira/prism-break/issues/1314#event-1684627281

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yegortimoshenko** [comment]
@mattdale77 See #2011. This particular issue has been moved to https://gitlab.com/prism-break/prism-break/issues/1314.
