### ISSUE TITLE
Can we consider to remove Firefox from the suggested browser?

### ISSUE THREAD

**Issue by geplus** [nylira/prism-break#1335]
Hi, 
Firefox will integrate Pocket by default:
http://www.guruslodge.com/threads/pocket-now-the-default-read-it-later-app-in-firefox.49277/
https://getpocket.com/blog/2015/06/pocket-is-now-built-into-firefox/
https://blog.mozilla.org/blog/2015/06/02/firefox-puts-you-in-control-of-your-online-life/

and Poket is actually not reccommended by Prism-Break:
https://prism-break.org/en/categories/gnu-linux/#bookmark-sync

So, it seems a non-sense suggest Firefox, that integrate a proprietary sevice by default, a service that you can't remove from tha browser, but only disable it.
I think we could consider to remove Firefox from the suggested browser's list.

**Comment by vyp** [comment]
https://github.com/nylira/prism-break/issues/1091#issuecomment-109037920

In fact, I believe it already has (in stable)? Assuming it can be disabled, I think #1254 is the best way. However, I'm not completely opposed to removing in favour of something like #1310 if it has to come that.  Pocket was recently added to prism break, hence the this overlap.

**Comment by Zegnat** [comment]
[My comment](https://github.com/nylira/prism-break/issues/1091#issuecomment-109037920) as linked by @vyp still holds up. This change by Mozilla doesn’t seem to leak any extra private information about you to anyone.

As far as I can tell Mozilla has only integrated the Pocket add-on UI elements as a native feature of the Firefox browser. That is it. The button (and thus the Pocket service) doesn’t even work for you unless you separately log-in to it:

![Screenshot of Mozilla Firefox 38.0.5 showing the Pocket pop-over.](https://cloud.githubusercontent.com/assets/490579/8061734/9f92f598-0ecc-11e5-9898-600e6cdfb82f.png)

If you are really concerned about [feature creep](https://en.wikipedia.org/wiki/Feature_creep) then this is bad, but from a privacy point-of-view I don’t belief anything has changed.

Some of us are concerned about where Mozilla is heading, especially with regards to alternative income channels such as ads and forcing add-ons to be signed by them. These are privacy and security concerns. However, finding another full-feature and open-source browser has proven difficult. That’s what #1310 is about.

**Comment by vyp** [comment]
Ah yes a point to note would be that the pocket integration stuff is "just" Pocket API wrapper things (which itself isn't proprietary), so disabling or just not logging into it should be okay. Of course, I put "just" in quotes because it still is unacceptable feature creep as Zegnat says. You should be able to remove the ui pocket button by just dragging it off through the normal ui editing interface. Or just set `browser.pocket.enabled` to `false`.

**Comment by strugee** [comment]
> Of course, I put "just" in quotes because it still is unacceptable feature creep as Zegnat says.

AFAICT @Zegnat wasn't claiming that the button was unacceptable.

**Comment by vyp** [comment]
bad, unacceptable, all the same innit?

**Comment by strugee** [comment]
It's a matter of extremity.

**Comment by flosse** [comment]
I think we just have to wait a bit for the next great 3rd-party feature that will ship with FF...
So hopefully the next feature will include real privacy issues so that we can remove it from the list ;-)

(BTW: http://dustri.org/b/firefox-youre-supposed-to-be-in-my-pocket-not-the-other-way-around.html)
