### ISSUE TITLE
Iceweasel - mozilla in debian

### ISSUE THREAD

**Issue by szymon1051** [nylira/prism-break#1336]
http://en.wikipedia.org/wiki/Mozilla_Corporation_software_rebranded_by_the_Debian_project
Add note to mozilla firefox?

**Comment by Zegnat** [comment]
We used to have un-/rebranded versions on PRISM Break, but dropped them in favour of just the stable Firefox build. They didn’t add any extra privacy but did introduce the risk of lagging behind on security patches.

Because of some recent moves by Mozilla, we are discussing swapping out Firefox with IceCat / IceWeasel, but only if we can make a proper case for it. Please add to #1310 if you have any arguments.

Closing this in favour of #1310.
