### ISSUE TITLE
ZeroNet and Maidsafe

### ISSUE THREAD

**Issue by terrorist96** [nylira/prism-break#1341]
https://github.com/HelloZeroNet/ZeroNet (also http://zeronet.io)
http://maidsafe.net/

**Comment by terrorist96** [comment]
"Put it on Github," he says. I put it on Github. Meanwhile, there's PRs that have been sitting around for months. :neutral_face:

**Comment by Zegnat** [comment]
PRISM Break collects a lot of issues and PRs mostly because people are very bad at showing why their preferred software is actually secure. Instead they just link to a website (like you have done) and thus it becomes a waiting game ’til someone has time to actually study the software.

**Comment by terrorist96** [comment]
Even if I were to go through the trouble of making a detailed PR, chances are it'll just stay pending like the numerous others sitting around for months. So why go through the trouble?

**Comment by vyp** [comment]
> showing why their preferred software is actually secure

That doesn't necessarily mean a PR. Just information posted as a comment here:

- Why your suggestions are better than anything already listed (or if it does something anything else already listed does not).
- The cryptography they do (if relevant).
- Direct links to the source code and licenses.

If you can get a project maintainer to agree with you about listing it, the rest is relatively straightforward.

I can't talk for anyone else, but the "Pull requests are prioritized over issues" point in the readme comes from a time when the website was in its infancy and the rate of suggestions popping up was a lot greater than it is today. But these days, it does seem more like one should make a case first for their inclusion before going through the time to make a PR.

Also, I personally dismissed ZeroNet at a glance because it's talking about using bittorrent *and* tor...

**Comment by terrorist96** [comment]
ZeroNet is basically an open source version of Bittorrent Sync, which isn't recommended on the site because it's not open source. Ergo proxy ZeroNet is qualified to be on the list. I linked to its github page so it's right there to look at.

As for Maidsafe, it's nowhere near completion, so I can understand leaving it off, but it does look promising.

**Comment by vyp** [comment]
I don't know if I'd place it directly under "File Storage & Sync" though, it would be confusing to visitors because ZeroNet is talking about a distributed network and it doesn't really go into talking file synchronisation capabilities at all from what I can see? Whereas we already have syncthing as a more "dedicated" bittorrent sync replacement.

**Comment by terrorist96** [comment]
You didn't look at my edit

**Comment by vyp** [comment]
> You didn't look at my edit

Didn't see it.

They seem to roll their own crypto? Is that correct? Because if so, that, and the fact that it's an extremely new project means I do not think it should be listed on prism break for now. I think we should at least wait more on it. I also have an issue with the fact that they continually recommend to use tor with their network which already uses the bittorrent protocol, am I correct with this concern?

**Comment by terrorist96** [comment]
They claim to use Bitcoin crypto (SHA256) as far as I know. I don't know much else about it other than I've tested it and it works great, no major hiccups. I'm not a dev/programmer so you probably know more about this than I.

**Comment by vyp** [comment]
They use some python bitcoin libraries https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Crypt/CryptBitcoin.py, but I'd still hold off listing it because it only started development around the start of the year. Despite the great number of projects listed, prism break is still about quality > quantity and I'm not sure if a Maelstrom replacement is in high demand, or would be that useful, at the moment.

**Comment by terrorist96** [comment]
> I'm not sure if a Maelstrom replacement is in high demand, or would be that useful, at the moment.

It will be when they start censoring more and more sites like they are in the UK. ;)

**Comment by vyp** [comment]
Ah right I do understand. I do support bypassing censorship. I will keep an eye on it but I don't see much reason for it now because tor can be used to bypass such censorship already, whereas ZeroNet is about accessing *ZeroNet sites specifically*, correct? Which means that it will have to start getting more popular to be useful I presume? (That's not to say it won't happen of course.)

I guess your argument would be that listing it on prism break would help with that popularity, I agree but I'm still not sure on where prism break would stand recommending quite a new project. Perhaps @Zegnat or @nylira can weigh in here?

**Comment by terrorist96** [comment]
It also facilitates accessing .bit sites too, I believe.

**Comment by beerhall** [comment]
Maybe it's time to reconsider ZeroNet.

**Comment by RiQuY** [comment]
Any updates?
