### ISSUE TITLE
Recommendation free social networking engine „Elgg“

### ISSUE THREAD

**Issue by Pasley70** [nylira/prism-break#1344]
Elgg is an award-winning social networking engine, delivering the building blocks that enable businesses, schools, universities and associations to create their own fully-featured social networks and applications.

https://www.elgg.org

Thank you to add to selection Social Networks

**Comment by vyp** [comment]
@Pasley70 was Elgg previously known as "Lorea"?

**Comment by Pasley70** [comment]
@vyp "Lorea" was a project, not a software. See https://en.wikipedia.org/wiki/Elgg_(software)

**Comment by vyp** [comment]
@Pasley70 Thanks. I asked because Lorea was actually recommended on Prism Break before. In fact, Lorea was only taken down a few days ago, see #1070. I was trying to find out more about it but could not find much. I remember I somehow ended up at Elgg, but I could not find a link between Elgg and Lorea and concluded that they were unrelated. Yes, my "research" was not that comprehensive.

Elgg describes itself as a "social networking engine". However, I'm assuming the prism break project maintainers would want to list something that their visitors can use/sign up for, or could self-host, or even potentially use in a p2p manner. I'm not sure what benefit there will be by *directly* listing the software that provides "the core components you need to build out socially aware applications".

So do you know of another "Lorea" that is still active today? My logic is that such a network, if it exists, will have a chance at getting onto prism break because it also uses Elgg like Lorea did.

**Comment by Pasley70** [comment]
I think you can compare Elgg with friendica. Perhaps listing Elgg on this platform ist interesting for people who would host their own special-interest-communities for a specific group of people.

**Comment by strugee** [comment]
@Pasley70 I disagree. Friendica is a complete product that you can actually run on your own server. Elgg, AFAICT, is not.

**Comment by Pasley70** [comment]
@strugee https://www.elgg.org/requirements.php

**Comment by strugee** [comment]
@Pasley70 OK, I may have misunderstood their website, which made it sound like a bunch of libraries.

I should mention that the page you linked to did not lead me to that conclusion. Libraries have requirements too, you know. In the future, it would be helpful if you could link to something more substantive. Thanks!

@vyp from http://learn.elgg.org/en/stable/index.html, it seems like Elgg actually can be installed as a full application. However, seems like it's only used for "private social networks", e.g. internal to some organization. [Support for federation][1] seemed to be weak to begin with and has since stalled out. Given that, I don't see why we should list Elgg when we have networks on the list that actually federate.

 [1]: https://community.elgg.org/search?q=federation&search_type=tags

**Comment by Pasley70** [comment]
Hi @strugee please excuse the cryptic link - I just wanted to show that Elgg itself can be self-hosted.

Thanx for your interesting feedback!

I understand your view that Elgg does not really fit here. The point "Federation is not very well supported" is comprehensible.

Elgg is also not an "out of the box network" (install and connect instantly). Elgg offers the opportunity to host an own network.

It could, however, an alternative to cloud services that need to be paid and on whose you have no control over the data. In this way i compare Elgg more with "ownCloud" or other owned services which where you are responsible for hosting and operation - to give other people the opportunity to participate.

Again - I understand your point! Also Elgg is in a "grey zone" that might not really fit the section "Social Networks" on Prism Break.

**Comment by strugee** [comment]
@Pasley70:

> Hi @strugee please excuse the cryptic link - I just wanted to show that Elgg itself can be self-hosted.

Yes, and I'm giving you feedback that your link didn't really demonstrate that very well. Next time :)

So, feedback from other contributors? Are we all on the same page that there isn't a compelling reason to add Elgg?

**Comment by vyp** [comment]
@Pasley70:

@strugee brings up an good point about federation. Sometimes it's tricky to tell
whether federation is of much benefit, especially with regard to mass
surveillance.

For example, with GNU mediagoblin, which is listed, last I checked it does not
support federation. And these days, media hosting and social interactivity
features often go hand in hand (facebook is the place to post all your
pictures/video, not just to communicate/talk).

But because self-hosting is much preferred to using a web-service, especially
when considering mass surveillance -- score one server/service/company and you
got them all, federation becomes vitally important. There will be no way you
will be able to compete against the big companies with infinite resources.
Perhaps federation will not give such an opportunity either, but it gives it a
theoretical chance at least, it scales.

Perhaps mediagoblin gets a pass because it's more focused on the media hosting
part, and it makes it easy to do so, and because, last I checked (few months
ago), they were actively working on the federation part.

@strugee has shown that Elgg has not been working on federation though.
Following some of the results on the federation search page he linked to
resulted in some dead links.

The other point that @strugee brought up was about Elgg being only used for
private social networks. I think if a particular company or business or whatever
wants to use a free software private social network, that's great for them, but
I don't see much relevance to preventing mass surveillance here. Because the
whole point of a private social network is so that it does not leak or give up
anything (at the discretion of whoever is controlling it), so even a private
social network powered by proprietary software should not be a problem, with
regards to mass surveillance.

You could perhaps compare a private social network to meshnets (or similar such
things), but I still think it's different in that meshnets are p2p, meaning they
can essentially *federate*, not like federated social networks as I talked about
above, but in the sense that it can still connect/scale as long as there are
nodes in the area. A private social network is however *supposed* to be always
closed off, even be closed off from the internet if you will (i.e. intranet).

So my vote is leaning towards rejecting Elgg at this moment.

Still, it raises the question, I don't think Lorea was able to federate if it
was using Elgg correct? But it was still listed, so rejecting Elgg for the
reasons I said above seem to be a contradiction. But I was not involved in the
decision to include Lorea, so I still stand by what I just said. But are any of
the social networks already listed unable to federate? (It seems like they all
can.)

One of the criteria prism break also seems to care about is not listing
something unless it can do *better* than something already listed which already
does its job (the quality over quantity rule in the README). Even if Lorea
*was* listed previously, I do not see what Elgg can offer that something already
listed cannot.

**Comment by jdalsem** [comment]
Elgg is not limited to private networks. It can also be used for (semi) public websites. There is enough access control (bundled in core, or available as plugins) to allow various levels of access. Also for account federation there is the very up to date SAML plugin https://github.com/ColdTrick/simplesaml.

I think based on the feature set of Elgg it can deliver more (and other) features then the already listed social network tools. Thus it deserves to be on the list would be my opinion.

Maybe one of the core developers (/cc @ewinslow) can add to this discussion.

**Comment by ewinslow** [comment]
Hey, all,

Please forgive our poor marketing :(. I can see how you'd get the impression that Elgg is just a bunch of libraries. You can definitely run Elgg as a self-hosted app out of the box, but much more value comes when you build custom stuff on top of it using the plugin + theming APIs. I suppose the closest parallel is WordPress (works out of box, but basically you will want to install/write plugins to get it to do just what you want for your particular use-case).

I'm not sure where the "private networks only" idea came from. The linked documentation explicitly lists open networks, interest-based networks, and other non-private use-cases. To see several examples of what kind of public networks use Elgg you can view https://community.elgg.org/showcase.

You're mostly correct about content federation. It's not a use-case the Elgg core team supports, though as @jdalsem mentioned there is certainly the possibility of plugins that support those needs.

I'm not familiar enough with the existing options to say whether Elgg can do more/better than them, so I won't try to comment there for now.
