### ISSUE TITLE
 Firefox & Suggested Tiles: can we still consider Firefox "safe"?

### ISSUE THREAD

**Issue by geplus** [nylira/prism-break#1355]
Hi everybody,
In the last year I became very dubious about the direction marked by Firefox.

The last bad news about Firefox are the "suggested web tiles", that look at your browser's history to show you targeted web ads:
http://www.engadget.com/2015/05/21/firefox-suggested-tiles/
http://techcrunch.com/2015/05/21/mozilla-will-soon-launch-sponsored-suggested-tiles-based-on-your-browsing-history/
This seems in my opinion, similar to Ubuntu's Amazon ads. We have only the promise by Mozilla that the brower will not track you.
After this, after DRM, after Poket etc., I'm not sure that Firefox is still safe enough.

**Comment by quantumpacket** [comment]
I honestly have the same opinion...as I post from Firefox. :P

So from the article, correct me if I am wrong. Mozilla will be an intermediary between the advertiser and the user. So what URLs will they be collecting? We know many URLs contain things like usernames and other PII. Is it wise to trust that history with Mozilla, and how do they determine which ones are passed onto the advertiser? What do the aggregate reports consist of? This just sounds like a foot in the door adware/spyware setup ripe for expansion and current/future abuse.

**Comment by Zegnat** [comment]
This is not “the last bad news”. In fact, it has been discussed several times already: #1184, #1307.

Since then there are a couple of things I didn’t know yet and know now, e.g. having Do-Not-Track turned on (as you should have) [will disable the whole Tiles experience](https://support.mozilla.org/en-US/kb/how-do-tiles-work-firefox#w_does-do-not-track-dnt-work-with-tiles).

As far as the whole browser history thing, more information has become available since my answer in #1184. It looks like <b>your browser history is yours and never leaves your PC</b>.

[[1]](https://support.mozilla.org/en-US/kb/how-do-tiles-work-firefox#w_what-data-is-being-collected-and-why):
> To deliver Tiles, Firefox fetches all possible Tiles and determines for itself what Tiles to display.

[[2]](https://www.mozilla.org/en-US/about/partnerships/contentservices/tiles/):
> Mozilla Suggested Tiles offer sponsored placement in a designated interest category. The browser makes these suggestions based on categories of sites that the user has already shown an interest in. 

[[3]](https://www.mozilla.org/en-US/about/partnerships/contentservices/faq/):
> For Suggested Tiles, we know whether users are interested in your market category by matching a list of defined URLs (domains, or subdomains) with their most frequently and recently visited URLs in Firefox. In this way, we are able to preserve users’ anonymity while providing a high level of confidence about their interest in different site categories.

From [the TechCrunch article](http://techcrunch.com/2015/05/21/mozilla-will-soon-launch-sponsored-suggested-tiles-based-on-your-browsing-history/) we even know [the list of domains](http://mxr.mozilla.org/mozilla-central/source/browser/modules/DirectoryLinksProvider.jsm#67) Firefox will match to specific categories.

All together it seems like Firefox talks to the Mozilla servers and downloads a list of (all) possible Tiles at once. Say you have visited a lot of websites that are on Firefox’ list as “auto parts”, Firefox will then select some Tiles that are tagged as such and displays those to you.

There is still a little information send to Mozilla, because Mozilla gets to know what Tiles are displayed by your browser. So they will get to know that for your IP an “auto parts” Tile was displayed. This doesn’t tell them any exact information about your browsing, just could in theory flag your interests. As IPs are removed after 7 days there is no long-term storage to build a profile of your interest though.

I haven’t had much time lately to put into research, but I would ask everyone to read the Mozilla resources I have taken these quotes from. There are FAQ items that answer almost everything, including what “aggregate reports consist of” as asked by @quantumpacket.

**Comment by GreenLunar** [comment]
> We have only the promise by Mozilla that the brower will not track you.

I do remember very early statements by Mozilla developers, especially in 2005, about how JavaScript is catastrophic to user privacy, but, eventually, Mozilla literally has promoted JavaScript with the phrase *Promote JS* (I must point out, that JavaScript presentation they have made - Promote JS - was outstanding); though only years later, animated CSS has arrived.

Mozilla is a for-profit corporation, not for-privacy, for-user, for-human etc.

Profit at any cost.  Freedom does not count.

**Comment by alerque** [comment]
@GreenLunar You are completely conflating issues and actors here. At the time Moz devs made that statement Javascript _was_ catastrophic to privacy and security because it was being allowed to run with no borders: advertisement code was running in the same scope as web app code as browser ui elements as other web pages! Any bad actor could inject code that would execute in an environments not belonging to them. That changed. Browsers (Firefox included) implemented boundaries so that code from domains could only execute in a scope limited to other code from those domains. They separated host system stuff privileged APIs from the reaches of untrusted code coming off the web. Most of them sandbox tabs in separate interpreters. With those sort of changes in place of course they can promote it with no contradiction. In many cases it's now safer to run Javascript that native apps! You make it sound like there is some grand conspiracy or hypocrisy in play without taking into account how technology has changed.

And most importantly, all of that is irrelevant to this issue! This issue is about the behavior of the browser and whether the interaction of the browser with Mozilla services and advertising poses a risk to users of being caught in a surveillance drag net. In light of that issue your post is basically just FUD. It doesn't shed any light on the parts that matter here: the open source browser and its interaction with hosted services. Remember Mozilla has both a non profit foundation and a corporation. There are lots of factors at play and different motivations, but your accusation of "profit at any cost" is clearly nonsense as it glosses over all the different pieces involved. Mozilla clearly has historically had and furthered many other ends besides profit even if some wings are angling for that, and even for-profit-companies can still put out open source code that furthers the ends of privacy seeking individuals.

**Comment by GreenLunar** [comment]
> **You make it sound like there is some grand conspiracy or hypocrisy in play** without taking into account how technology has changed.

This is really what I am aiming to.  Mozilla is a corporation with hundred of millions of $, and I think they could have find safer alternatives for JavaScript, that would also work on slower hardware.  Either way, we get to have unsafe or inefficient web browsers for no good reason, these trends are not to my likings,

> In light of that issue your post is basically just FUD.

It might be so, but a rich corporation such as Mozilla, which has more resources than any open source (p.s. Mozilla popular products are neither open source nor free software) project, does not offer efficiency not strive to divide components of its web browser, instead its products are All-in-One, that alone is suspicious to me.

Since the release of Firefox 3 they have provided its users with a bookmark manager that  allows to use tags, yet they did not offer a separate application to handle `places.sqlite`, also new `cookies.sqlite` that can not be used with external download manager and other new and exclusice ways to manage information.

Do they want us to be depended on their extensions to custom my file downloading needs?
Do they want us to rely on them by providing `places.sqlite` which will grow and grow and consequently short the lifespan of my hard drive?

Mozilla, a billion $ corporation, has even deprecated RSS http://camendesign.com/blog/rss_is_dying (whhhhhhhhhhyyyyyyyyyyyy? are they out of budget?????????), could not they, at least, make the RSS icon appear inside of address-bar, as it used to, when RSS button is located to the right of the address-bar (**is Mozilla poor, so it has no resources to do such simple task??**), similarly to what they did with combining Reload/Stop buttons to one when they were near each other on toolbar, before they have incorporated them into address-bar.

They do not want RSS because their boyfriends of big media are not interested in RSS http://www.newsome.org/2011/01/why-big-media-wants-to-kill-rss-and-why-we-shouldnt-let-it/

Do you remember the project Ubiquity https://mozillalabs.com/blog/2008/08/introducing-ubiquity/
Even though getting popularity that only increased and having over a thousand scripts for it, Mozilla has drop it, several months after its public announcement of it, they falsely claimed for incompatibility with some API of their web browsers (THIS IS SIMPLY NOT TRUE!).

They have recently even added support for DRM, as you might know, because their boyfriends asked so.

They cooperate with big media companies instead of opposing them by initiating a campaign that says *you can't expect not to have contents that made available (e.g. as CD) for read by digital and electronic equipment (e.g. Computer) not to be spread*; it is like someone would want to get fee for every minute person watches a woman with a red dress, but she is outside in public so such will can not be enforced and to solve it, that someone puts bandage to cover the eyes of people in public.

Mozilla is not good.

**Comment by Inoki** [comment]
I too think, that after this move Mozilla is working more against than for the user and should no longer be recommended.

They preach privacy, but invite advertising into the browser. Why are we even having this discussion? It is enough to put Firefox on the blacklist.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i hate all the things mozilla keeps doing but its possible to disable everything bad and make it a good browser. i have yet to try a good firefox fork without unfixable flaws which is good for general browsing and other activites too. firefox needs to be tweaked a lot but then its pretty good. there are sites popping up on the net with guides on how to improve firefox's security and privacy and make other improvements. there should just be one unified and easy solution which should be bundled with firefox recommendations. none of the forks are really that great. customizing normal firefox leads to better results i think

**Comment by berrythesoftwarecodeprogrammar** [comment]
and i dont think there are any good non-firefox based browsers lol

**Comment by nodiscc** [comment]
> guides on how to improve firefox's security and privacy 

https://github.com/pyllyukko/user.js/

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah thats one of the things i was referring to

**Comment by berrythesoftwarecodeprogrammar** [comment]
this looks like a project worth watching
https://gngr.info/
https://github.com/uprootlabs/gngr
https://gngr.info/doc/introduction.html
https://github.com/uprootlabs/gngr/wiki

**Comment by vyp** [comment]
@berrythesoftwarecodeprogrammar Still looks like fairly early stages. But nevertheless definitely seems like a project to watch at the least. Good find, and thanks for mentioning it here! :smile:

**Comment by GreenLunar** [comment]
@berrythesoftwarecodeprogrammar thank you for notifying us about gngr.
