### ISSUE TITLE
Add big warning box if useragent contains "Windows"

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1380]
WIndows 10, known as "NSA Spyware OS", must not used in public.

**Comment by strugee** [comment]
As far as I know we can't do this in an elegant way due to the way @nylira hosts https://prism-break.org/ (static files via Nginx).

**Comment by mastercoms** [comment]
We can get the agent using JavaScript and add an alert to the document if it has Windows.

**Comment by Zegnat** [comment]
PRISM-Break made a conscious effort not to have any JavaScript, and I personally like it that way.

The [Windows page of PRISM-Break](https://prism-break.org/en/categories/windows/) has a fairly clear warning informing users how their Operating System can turn any other program used for security moot. If you think this note is lacking in information or needs to be more strongly worded do feel free to give that a try.

Microsoft specifically working together with the NSA (as your ‘NSA Spyware OS’ comment might suggest) is unfounded. Several smart people – that I personally trust – have even said Microsoft’s BitLocker is just fine to use. This includes [Bruce Schneier](https://www.schneier.com/blog/archives/2015/06/encrypting_wind.html). PRISM Break is all about verifiability and will only recommend open-source projects, but the fact trusted security experts say they entrust their harddrives to BitLocker at this time is telling of steps Microsoft is taking forwards.

What can be said of Windows 10 is that it likes to share information about you with Microsoft. I have heard that all of this can be turned off during installation. If that is not true we could definitely add a warning about that, but otherwise I see no difference between this and Ubuntu’s old upload-all-their-searches thing. Both can be disabled, and we never added banners all over the web saying Ubuntu ‘must not [be] used in public’.

**Comment by vyp** [comment]
> but the fact trusted security experts say they entrust their harddrives to BitLocker at this time is telling of steps Microsoft is taking forwards.

Being a bit nitpicky and a bit off-topic, but I think it's more black and white honestly. If the program's source code cannot be (publicly) studied and independently built from source, then no step forward has been taken, even if those whom I already "trust" says it has been.

It should be all about "not having to trust anyone" from *my* point of view with free/open source software.

But of course there is a limit to that, assuming I am not a cryptographer who's really good at math (and even then). If I am a non-technical user, I can't just study the source code myself, so making it publicly visible or not seems to make little difference to me. But still, the key difference would be that I would be able to sleep easier at night *knowing* that it *is* publicly visible for others, who are clever enough, to "audit" it.

You don't get that with a program with which all you get is a binary to run. Perhaps you could make sure you turn off network access completely everytime you run the program, but even then, what if it starts a daemon that starts at boot and waits for the next network access (i.e. intentionally malicious)? I'm not saying this is actually the case, I'm saying we can't see what *exactly is* the case, almost like they've "got something to hide".

This is also complicated by the fact that the program itself in this case (Bitlocker) has to run on a proprietary (or perhaps better described as "secret") operating system. So even if you were able to trust the program somehow, it still has to interface with your hardware through other "secret" software, which you have no guarantee of how it exactly behaves.

Yes, that would be going into "tinfoil hat" area. But I feel I can justify that now post the Snowden leaks. Maybe you and others still disagree with me, but that's just how I see it.

**Comment by Zegnat** [comment]
@vyp, oh, I agree completely. Which is why I tucked in that line about how PRISM Break will always stick firmly to open source. I just wanted to point it out to illustrate that broad blanket statements against ‘WIndows 10, known as “NSA Spyware OS”’ make for huge unfounded FUD. And that’s basically my vote against adding a ‘big warning box’.

**Comment by lukeroge** [comment]
And besides... if there is "NSA spyware" in Windows 10, it's probably in Windows 8 and any other versions two. Such is the fun with closed source software!

**Comment by juanito003** [comment]
>WIndows 10, known as “NSA Spyware OS”’ make for huge unfounded FUD

 I guess you didn't read this article:
**Vista 10 (Windows 10) Has NSA Back Doors and Front Doors**
http://techrights.org/2015/07/25/back-doors-and-front-doors/

**Comment by alerque** [comment]
@juanito003 That article is neither good journalism nor good technical analysis. It is the quintessential spreading of FUD. That's exactly what we _don't_ need to be doing.

Don't get me wrong. Windows is neither secure nor trustworthy in any meaningful way and its usage should be ruled out as a matter of course for anybody that cares about breaking away from PRISM related issues. Yet that doesn't give us an excuse to feed into the FUD machinery.

**Comment by tunguyen6** [comment]
I think we should advice users who have to use Windows 8/10 to turn off all features that collects their information. There are the so-called Express settings during installation of Windows 8/10, we can choose Customize settings instead, there we can turn them off. In Windows 10 there are a number of them in Settings > Privacy. There are other settings including SmartScreen and Page prediction in Microsoft Edge. Of course Windows can't be trust, but having these turned off is better than nothing.

**Comment by Zegnat** [comment]
I agree with @tunguyen6 that there might be some value on adding something about Windows’ current (very mobile-like) way of sharing data by default to the note on [the Windows page](https://prism-break.org/en/categories/windows/).

**Comment by espress0** [comment]
@Zegnat
>  I have heard that all of this can be turned off during installation.

Yeah... MS still want your information!

http://www.extremetech.com/computing/212160-windows-10-still-phones-home-even-when-ordered-not-to-do-so

**Comment by tunguyen6** [comment]
@espress0 
> Yeah... MS still want your information!

So I think the better solution now is blocking tracking servers with HOSTS file. For that purpose there is this project: https://github.com/10se1ucgo/DisableWinTracking.

**Comment by espress0** [comment]
@tunguyen6

No, HOSTS file is not a 100% perfect solution. Some of executable file from Microsoft bypass HOSTS
file(1).
Sometimes, they use IPv4 IP address to connect to their servers(so, AcrylicDNS and HOSTS can't
block them).


---

And yet another Win10 incident. Poor kid. Learn Linux and dump windows into trash.
Thanks Microsoft, I never upgrade to any OS later than windows 7.

http://www.independent.co.uk/life-style/gadgets-and-tech/news/windows-10-automatically-sends-parents-detailed-dossier-of-their-childrens-internet-history-and-computer-use-10472226.html

“This weekend we upgraded my 14-year-old son's laptop from Windows 8 to Windows 10,”
“Today I got a creepy-ass email from Microsoft titled 'Weekly activity report for [my kid]',
including
which websites he's visited,
how many hours per day he's used it,
and how many minutes he used each of his favorite apps.”

**Comment by Zegnat** [comment]
A lot of this latest Windows fuzz is because people don’t read.

Yes, it seems that Microsoft is “helping” parents by turning the activity reports on by default. But for them to work the parent must already have set-up Microsoft accounts for their kids and linked it together as a family account. I have no idea if family accounts give you some hidden benefit other than creeping on your kids, but really, are you telling me you set all of that up because you want to stay out of your kids live?

If people would just have read about the “family” service, and check what settings are on by default, none of this would ever have been an issue. But people just blindly tick boxes and agree to things, and then complain when they ended up with a service they didn't want.

These incidents would have easily been prevented if we didn’t have a TL;DR-attitude towards software and services. (And now I feel dirty for defending Microsoft, but I do honestly feel it is discrediting to them for everyone to say this is something they did.)

**Comment by espress0** [comment]
Oops... I deleted my previous comment by mistake...

HOSTS file can't prevent Windows connection perfectly. The news below is true; I tested it by myself.
http://www.infoworld.com/article/2641599/security/microsoft-hosts-file-bypass-issue.html

The best solution:
Dump Win10.

Good solution:
1. Install AcrylicDNS and watch DNS log. Block Microsoft FQDNs.
2. Install Peerblock. This is not about P2P/BT. PB is about blocking multiple IPs fast&easy. Subscribe Microsoft IP list.
3. Open "gpedit.msc", and disable Error reporting and other reporting system.

Bad solution:
Being a puppet/slave of Microsucks XD

**Comment by yegortimoshenko** [comment]
We have committed to no JavaScript, also not clear why Windows should be singled out (2/3 of listed platforms are proprietary). Platform-specific pages (like https://prism-break.org/en/categories/windows/) already have a disclaimer, so that shouldn't be any worse than a popup.
