### ISSUE TITLE
Add Data erasure category

### ISSUE THREAD

**Issue by tunguyen6** [nylira/prism-break#1381]
Hi, I'm new here. I think we shoud have a category for secure data deletion solutions.
From Wikipedia: https://en.wikipedia.org/wiki/Data_erasure.
I would like to suggest [Eraser](http://sourceforge.net/projects/eraser/) and [Darik's Boot and Nuke](http://sourceforge.net/projects/dban/).
Thanks.

**Comment by lucaspetter** [comment]
Good idea :+1: 

For Macs, there's already the `srm` terminal program built-in for securely deleting files and it defaults to the Gutmann 35-pass erase method. [Permanent Eraser](http://www.edenwaith.com/products/permanent%20eraser/) is a nice GUI app that is [free software](https://github.com/edenwaith/Permanent-Eraser), which also uses Gutmann for emptying the trash can.

For GNU/Linux, `shred` is part of GNU coreutils, so it comes with nearly all distributions; eg. `shred -un 35 file.txt` to securely delete a file. BleachBit (which is already in prism-break under the Disk Encryption category) is a GUI alternative and it has a lot more cleaning options.

An important thing to mention is that data is easy to erase on magnetic drive media, but hard to erase on flash media like SSDs, SD cards, or USB flash drives because of [wear leveling](http://arstechnica.com/security/2011/03/ask-ars-how-can-i-safely-erase-the-data-from-my-ssd-drive/). Even if you run a shredding program to delete a file on a flash-based drive, the file may still be there. One solution is to encrypt the whole drive before putting sensitive files on it.

**Comment by yegortimoshenko** [comment]
Out of scope, also it's a myth that one needs to rewrite one file 35 times in order for it to be secure. If you use an SSD, you can never be sure that you've removed every block of it, and if it's a hard drive, just zeroing it out (or on safer side, using /dev/urandom) will do just fine.

See https://github.com/nylira/prism-break/issues/1001#issuecomment-372800135.

From [Wikipedia](https://en.wikipedia.org/wiki/Gutmann_method):

> Most of the patterns in the Gutmann method were designed for older MFM/RLL encoded disks. Gutmann himself has noted that more modern drives no longer use these older encoding techniques, making parts of the method irrelevant. He said "In the time since this paper was published, some people have treated the 35-pass overwrite technique described in it more as a kind of voodoo incantation to banish evil spirits than the result of a technical analysis of drive encoding techniques".

Also see [Data remanence - Feasibility of recovering overwritten data](https://en.wikipedia.org/wiki/Data_remanence#Feasibility_of_recovering_overwritten_data).
