### ISSUE TITLE
Is Steam a threat?

### ISSUE THREAD

**Issue by amarildojr** [nylira/prism-break#1386]
I'm running 99.99% GNU software, with Arch Linux, and I'm trying to decide wether to ditch Steam or not. 
>(If anyone is wondering, I don't use Firefox, but Iceweasel from Parabola's repo, which is way more secure and privacy friendly than vanilla Firefox or even Debian's Iceweasel).

I really don't think Steam is 100% safe; but also, I don't know if it has a big Kernel integration or how it handles the network stack thingies, so I can't decide to stop using it or not.
Also, I'm using the hardened GRSec+Pax Kernel and I use the FOSS AMD drivers (cause they are far superior than Catalyst), and the only mitigation I must disable for Steam and it's games is MProtect. (pax flags "PEmRS").

Invading a well secured Linux machine is close to impossible, but what about when Steam is installed? Should backdoors be considered on Steam?
I'd love to see what you guys have to say.

Regards,
Amarildo

**Comment by hasufell** [comment]
> Should backdoors be considered on Steam?

Absolutely, you could even download viruses via steam cloud (it is known that cheat programmers abuse the steam cloud to distribute their sold cheats).

Also, I have to remind you that prism-breaks is not just about your personal security, but primarily about preventing _mass surveillance_. This is very well possible since steam is highly centralized and is known to already process a lot of data in order to determine what you might want to buy next.

It is a reasonable target platform for agencies that want to collect more data.

GOG seems like an alternative (also: no DRM) and the GOG client will stay optional, so you are not running all your games through a huge blackbox system that wants to connect to the internet at all times.

The best way is to have a real containerized environment for playing proprietary games and never run them with full user privileges on your main desktop.

**Comment by amarildojr** [comment]
>Absolutely

Exactly how? I think there are enough Linux experts who use Steam and constantly check for suspicious behavior. Shouldn't something already have shown up?

Also, Steam doesn't execute as root.

**Comment by hasufell** [comment]
> Shouldn't something already have shown up?

No, why would a backdoor present itself?

**Comment by amarildojr** [comment]
>No, why would a backdoor present itself?

Is there a way of -not- presenting itself once it doesn't run as root and probably doesn't have the ability to do many kernel syscalls?

**Comment by hasufell** [comment]
> Is there a way of -not- presenting itself once it doesn't run as root and probably doesn't have the ability to do many kernel syscalls?

That does not make sense. The backdoor shows up when it's used. Otherwise you have to decompile the binaries/libraries and look for yourself. No one has done that, I am pretty sure.

Also, whether it's run as root (ofc it's not, lol) is irrelevant for data mining and compromising your user data and privacy.

The main point is that valve does do data mining for sure and no one really knows what happens with that data, how much is collected and so on. One reason (but not the only one) for that is that the client is proprietary, and ofc the service as well.

also, almost unrelated, but fun fact: https://github.com/ValveSoftware/steam-for-linux/issues/3671

**Comment by amarildojr** [comment]
>That does not make sense. The backdoor shows up when it's used. Otherwise you have to decompile the binaries/libraries and look for yourself. No one has done that, I am pretty sure.

Of course someone did :D Not to all binaries or libraries, but I'm sure someone decompiled a few of them.

>Also, whether it's run as root (ofc it's not, lol) is irrelevant for data mining and compromising your user data and privacy.

That wasn't my point, actually. My poing was for a backdoor, not data privacy (which obviously can be compromised by non-root processes).

**Comment by hasufell** [comment]
> Of course someone did :D Not to all binaries or libraries, but I'm sure someone decompiled a few of them.

wishful thinking, any reference?

> That wasn't my point, actually. My poing was for a backdoor,

err? So user privlige backdoors are ok and we should not care? wat?

**Comment by amarildojr** [comment]
>wishful thinking, any reference?

No.

>err? So user privilege backdoors are ok and we should not care? wat?

That's not what I said.

We SHOULD care for backdoors, and we should care for data privacy. What I meant was that a software doesn't have to be a backdoor to hurt user privacy.

**Comment by hasufell** [comment]
> We SHOULD care for backdoors, and we should care for data privacy.

In that case, either get rid of steam or run it in a dedicated environment which doesn't hold any data that you care about. As we don't know what the code does, it is fully untrusted.

**Comment by amarildojr** [comment]
That's exactly what I was thinking. I just have to figure out a safe way to do it.

**Comment by Zegnat** [comment]
I think I am going to close this now. No matter how you look at it, Steam is closed source and could potentially leak identifiable information. It is currently listed as a proprietary platform on PRISM Break, and it will likely stay there.

The first example I thought of were simply computer configurations. Steam and/or closed-source games would love to know the computer configurations they are running on: what processor, graphics card, how much RAM, etc. Even if you change browsers and IP addresses all the time, that information is likely to stay the same, and if it is unique enough could be used to track you.

This wouldn’t even be a back-door, it would be a real feature for gaming software, but still a leak of identifiable information that we shouldn’t be comfortable with. And that’s really also the only type of leaks PRISM Break as a project cares about.

---

Personally I do not play online multi-player games, I use Steam in offline mode 99% of the time and have blocked its outgoing connections in my firewall. I *feel* pretty secure about that.

**Comment by amarildojr** [comment]
OK, no problem.

I don't use Steam, I'm very paranoid with these kinds of situation. If I was going to use it, it would probably be on a different computer, running on top of firejail with "--seccomp --private" flags.

>It is currently listed as a proprietary platform on PRISM Break, and it will likely stay there.

Sure :) I don't want that to change.

>Personally I do not play online multi-player games, I use Steam in offline mode 99% of the time and have blocked its outgoing connections in my firewall. I feel pretty secure about that.

That is a very interesting approach.
