### ISSUE TITLE
Protonmail is now opensource, should it be included?

### ISSUE THREAD

**Issue by erm** [nylira/prism-break#1412]
I noticed the last few times it was suggested to be added it was rejected due to not having any source code available. Is there any reason not to include it now?

https://github.com/ProtonMail/WebClient
https://blog.protonmail.ch/protonmail-open-source/'

EDIT: I just double-checked and realised only the frontend web client code has been open-sourced but not the backend, so I may have been mistaken in thinking it should now qualify for inclusion.

**Comment by alerque** [comment]
This is a reply in comments from a ProtonMail admin in the blog post you linked to:

> The security risks of open sourcing the back-end code is too high. It would let an attacker know how our infrastructure is set up or let spammers get insight into how to circumvent our anti-spam measures.

I don't think this is going to work on PRISM-Break yet because there is still really no assurance that the system is private. Having the front end open sourced is a huge step in a good direction and may make this a better choice for many situations, but even if the message contents are encrypted client side and can show to be secure there is still a lot of private meta data being pumped through their backend and we still have no way to verify how it's being done and no guarantee that it's secure from surveillance.

**Comment by Zegnat** [comment]
See #1383, ProtonMail actually had their web client visible there too. I wrote down some concerns about email services like this in that issue, feel free to add any insights you have into how ProtonMail handles security so we can give an informed opinion. I am sad to say that because of time constrains I mostly looked into Tutanota and only shallowly into ProtonMail.

**Comment by yegortimoshenko** [comment]
Merged into #1383.
