### ISSUE TITLE
Add Aptoide AppStore

### ISSUE THREAD

**Issue by maverick74** [nylira/prism-break#1414]
I suppose Aptoide is also a candidate to Android AppStores

http://www.aptoide.com/

**Comment by vyp** [comment]
I don't because aptoide hosts a lot of software that are specifically not recommended by prism break. But maybe there's an option to choose your own repositories? In which case, prism break could tell visitors to use a particular repository only, or something. But then the problem is that we don't who is really controlling this repository or how it really works (whether they can inject malicious patches into the apps), but F-droid we know this.

**Comment by strugee** [comment]
@vyp FYI, F-Droid was forked from Aptoide.

**Comment by vyp** [comment]
Yeah I know.

**Comment by vyp** [comment]
I was talking about the "stores" thing in aptoide.

**Comment by strugee** [comment]
@vyp ah, OK. Just wasn't sure. :)

**Comment by Zegnat** [comment]
I guess the idea is that Aptoide as an open-source store might be worth recommending over the Google and Amazon, but the apps people can install through it still wouldn’t be recommended? I am not sure if I see much use for it that way. I guess it is a way for people to install proprietary applications without needing a Google account? Not sure how we can best made that clear on the site.

**Comment by yegortimoshenko** [comment]
We already list F-Droid which is an Aptoide fork that only lists free software, which is a big improvement over Aptoide. I call this to be labeled as "waiting for objections".

**Comment by Hillside502** [comment]
Only the Android app is open-source --- not the backend.

Aptoide (HTTPS)
https://www.aptoide.com/

Source
https://github.com/Aptoide

**Comment by beerisgood** [comment]
F-Droid with the Yalp app from F-Droid is fine.
Please no other untrusted sources
