### ISSUE TITLE
Add Tizen OS and Sailfish OS

### ISSUE THREAD

**Issue by maverick74** [nylira/prism-break#1415]
Add Tizen OS and Sailfish OS?

**Comment by alerque** [comment]
Sailfish is a duplicate of #902. Tizen is even less of an option as [mentioned here](https://github.com/nylira/prism-break/issues/193#issuecomment-20263848). This is easily confirmed on [Wikipedia](https://en.wikipedia.org/wiki/Tizen) which has references to back this up:

> Its SDK is built on top of open source components, but the entire SDK has been published under a non-open-source Samsung license.

@maverick74 It seems like you did not search the issue tracker at all before throwing out a bunch of names. Please search next time before suggesting something as there has been a ton of discussion already. We're not aiming to create a directory of all alternative software; in order to be recommended on PRISM-Break a solution has to be relevant to a specific problem and meet specific qualitfications

**Comment by maverick74** [comment]
@alerque , Yes, as i was reading all the replies i was thinking the exact same thing... I should have searched better before trying to make contributions (I was in kind of a hurry and just made a very very quick search in some cases - in others i thought the projects were too new to anyone already suggested them (ring, for ex...)). I owe you (and everyone else) an apology. It won't fix anything, but I'm REALLY sorry for making you waste important time.

**Comment by maverick74** [comment]
Ups... sorry... i don't know if it was to be closed...

**Comment by vyp** [comment]
@maverick74 It is fine. :smiley:

If I recall correctly, I now know that Sailfish OS actually has a lot of their stack as free software, except for the UI (the touch interface). This situation may have also improved in the time that I last checked (I think they were talking about open sourcing more things, but my memory is hazy and may be wrong).

Although the UI is one of Sailfish OS's major selling points, if a third party free software UI is made that works with the rest of Sailfish OS, it theoretically should be good enough to consider. Of course, that's probably just a theoretical proposition for now (unless someone has already done it). And I wouldn't really recommend a proprietary UI because simply too many opportunities to catch user input/eavesdrop on what the user is doing/typing.

As for Tizen, it still has the same issues as I saw from two years ago (which Caleb linked). From its [wikipedia article](https://en.wikipedia.org/wiki/Tizen#Licensing_model) (emphasis mine):

> The operating system consists of many open source components. A number of components internally developed by Samsung (e.g., **boot animation, calendar, task manager, music player applications**) are, however, released under the Flora License, essentially a BSD- or Apache-style license except granting patents to "Tizen Certified Platform" only.

> Flora is not approved by the Open Source Initiative.[33] Therefore, it is unclear[citation needed] whether developers can legally use the native application framework and its graphical components to make GPL applications. Source code access is guaranteed however.

> Its SDK is built on top of open source components,[34] but the entire SDK has been published under a non-open-source Samsung license.

So basically:

1. Their "flora" license has not been OSI approved, nor FSF approved, the latter is which Prism Break primarily cares about. Freedom is paramount for software that hopes to have an effect on mass surveillance. Sort of frustrating because it's similar to the Apache License, with slight modifications which make it "likely not compatible with requirements of the Open Source Initiative" (https://en.wikipedia.org/wiki/Flora_License#Grant_of_Patent_License).

2. SDK is proprietary, which probably isn't as big of an issue as 1, especially to prism break, but still an unfavourable point.

So yes I think you can close this. :+1:

**Comment by alerque** [comment]
Thanks for the extra input @vyp. The only thing I would tweak from what you said is that the SDK being proprietary is a really big deal. Not being in control of and having open source vetting of the libraries and complier used means that virtually any app for the platform (even apps that would otherwise be open source and/or trustworthy must suddenly be suspect. A text-book example of this issue is illustrated by the recent [XcodeGhost staffu](https://threatpost.com/xcodeghost-malware-stirring-up-more-trouble/114778/). If you can't trust your toolkit you're bankrupt.

**Comment by vyp** [comment]
@alerque Actually yes, you raise a pretty good point. This is actually the first I am hearing of this XcodeGhost vulnerability! It's sort of ironic that I was nearly dismissing the importance of a free SDK because the article talks about what the Sandia National Labs researchers did *three* years ago regarding attacking OS X/iOS via the Apple SDKs. And Snowden had documents about that from the June 2013 revelations too... So good catch. Thanks.

**Comment by yegortimoshenko** [comment]
More proprietary than Android.

**Comment by yegortimoshenko** [comment]
We already have a fully free operating system for phones, Android. The only issue left is to get hardware manufacturers to open up their proprietary blobs. Both Tizen and Sailfish are a major step backwards, we'd again have to fight the operating system vendors to open SDK, user interface, etc.

**Comment by yegortimoshenko** [comment]
Closing based on "only FOSS" policy.
