### ISSUE TITLE
Add Telepathy to IM section

### ISSUE THREAD

**Issue by maverick74** [nylira/prism-break#1417]
Telepathy is also a good addition to the IM section

https://userbase.kde.org/Telepathy

**Comment by alerque** [comment]
The IM section has a tendency to get out of hand. Remember we are not trying to be an index or directory than lists all possible alternatives, we're just trying to recommend a few best-in-class suggestions for each category.

Telepathy has been discussed before in #939. At the time it didn't support OTR or PGP. That issue was closed [with the remark](https://github.com/nylira/prism-break/issues/939#issuecomment-62295653) that if that situation changed then somebody could put together a PR for review. As far as I can see looking over the feature list it has not changed. Ergo it does not stand a chance of being recommended for the same reasons Miranda is not (see discussion in #1405).

I think this can be closed until such a time as Telepathy specifically focuses on security and privacy and has something to bring to the table that is at least on par with if not an improvement over the other currently recommended solutions.

**Comment by jemadux** [comment]
telepathy supports now otr but not gpg

**Comment by alerque** [comment]
@jemadux Okay. Source please? Also needed for this discussion are:

* what advantages Telepathy brings to the table over other suggested platforms
* how concerns that meta data leaks to the proprietary services being used are addressed.

Even if it supports OTR so the contents of your chats are private, because it connects to a ton of proprietary platforms I don't see how it can help but leak data that should be private about your communications. See again the link to 1405 in regard to the same issue with Miranda.

**Comment by jemadux** [comment]
http://blog.davidedmundson.co.uk/blog/ktp_0.9

**Comment by yegortimoshenko** [comment]
Source code: https://github.com/TelepathyIM

Against inclusion based on architectural similarity to Pidgin that was recently removed, and the fact that our IM category is already overcrowded and IMO needs to be cleaned up.

**Comment by strugee** [comment]
Yeah, the IM section is huge. Honestly Telepathy isn't even really a "client" anyway, it's a framework to connect pieces like clients and service backends together.

**Comment by yegortimoshenko** [comment]
Agreed.
