### ISSUE TITLE
Guardianproject's Orfox

### ISSUE THREAD

**Issue by lockheadcannoniera** [nylira/prism-break#1418]
"In the summer of 2014

we announced that the results of work by Amogh Pradeep (https://github.com/amoghbl1), our 2014 Google Summer of Code student, has proven we could build Firefox for Android with some of the settings and configurations from the Tor Browser desktop software. We called this app Orfox, in homage to Orbot and our current Orweb browser. This was a good first step, but we were doing the build on Mozilla’s Firefox code repository, and then retrofitting pieces from Tor Browser’s code, which wasn’t the right way to do things, honestly.

This summer (2015!), with fantastic continued effort by Amogh, we have switched to building the Orfox mobile app directly from the Tor Browser code repository, successfully working through any mobile OS incompatibilities in the security hardening patches added by the Tor Browser team. We also had the additional task of reviewing the Android application code in Firefox, that is not part of Tor Browser, in order to modify and patch it to work inline with the Tor Browser requirements and design document.

...

You can access the current Orfox release by installing the F-Droid app and subscribing to our F-Droid Alpha Channel at by clicking on the following link on your phone: https://dev.guardianproject.info/debug/info.guardianproject.orfox/fdroid/repo "

https://guardianproject.info/2015/06/30/orfox-aspiring-to-bring-tor-browser-to-android/

**Comment by hasufell** [comment]
Orweb is superseded by Orfox. This should be fixed

https://guardianproject.info/apps/orweb/

**Comment by strugee** [comment]
Agreed.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Orfox does not work on Replicant, because Firefox for Android requires
GPU acceleration (it crashes without it), and Replicant doesn't
include the GPU blobs.  This is an unfortunate conflict, since Orfox
definitely has better anonymity features, but you need potentially
dangerous GPU blobs to use it.

My understanding is that the Replicant folks are currently working on
improved software graphics emulation that can emulate Firefox
properly, but I'm not sure what the ETA on that is.  I can check on
the Replicant forum to see if there's news on this front if you'd
like.  (I haven't checked in a few months, maybe there's progress I
don't know of.)

Until there is a resolution to this, I'd suggest listing both Orweb
and Orfox, perhaps with a brief note explaining that Orfox doesn't
work with Replicant, that there aren't any good solutions ready yet,
and that people who seriously need optimal privacy right now shouldn't
be doing web browsing on phones.  (I wish there were something more
positive to tell people....)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYjtc2AAoJELPy0WV4bWVwm3YQAJwCUZVu7KcsuosAEBWOl2Hl
ia4Hs7UMu9lPUcu1xPcKYZ+dylt7NM7WhZMPqXXW8248HUluVPDIIIRnzrZ7jXsp
Ve1TjCZX2c3ou9tHpVbHTPOuoQYyw25PLR1fejRDkrc6MlHVjTSiW2/Re89aM1rq
rKLPzzhqATHSG+ETOlM3YGWNRIg5epD9mFLGoy5XgczdUs4FrL3gUGrCfNA38lf6
9SLmJB2aI7Lg7lsZNrLIwlinnNdvJBUAokIzOFBEsvBfwOWenkt8x+MwUK8JvJ9n
6OGwwhAGH3VPq4ZKminOIb7567xseTEcezmlvoCV6GqNfA1N2lFPFRK/l9c01Mj4
R1bvs4I6RslPmui+QaXdSMimBrUQs5P5NaN7KzR84xLG4tYpy80xp0y1XVrsOpkv
j30Yb6asv5UVoyGrglUlx9zdOo3gNLE1+ttFpHBQrlr0ytQV+4EVvvseSJBSQPZe
3eh+vHJgxr2/ntFPLFzlYoSqJO8Uq+GGsIQcnqdEHBHPXamnfpRIr9M7ky138sMJ
j3igeq+JhAtgJBpuU4o40MF8skEcteaCgazPmUu7Qfx3LZ9s2qv+DPCODV55bJKi
wRk/4CoBh3fgj9LnM/jKDtuQrbqf7WUB9ttrsxYeOcObDnlJi78pMwBAU9DOx3US
EAYGqDVb82FE524TOOrP
=swFA
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
@JeremyRand that's good to know, thanks. If you do ask, ask about the state of the 6.0 betas since we'll be recommending them soon IIRC (can't be bothered to fine the issue since I'm on mobile).

I'd prefer to mention Orbot in the Orfox notes, though, instead of keeping it as a first-class project. Something like: "if Orfox crashes on your device because of GPU problems, either use the older, less private Orweb instead, or simply don't browse the web on your mobile device."

**Comment by hasufell** [comment]
> can't be bothered to fine the issue since I'm on mobile

https://github.com/nylira/prism-break/issues/1600

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> @JeremyRand that's good to know, thanks. If you do ask, ask about 
> the state of the 6.0 betas since we'll be recommending them soon 
> IIRC (can't be bothered to fine the issue since I'm on mobile).
> 
> I'd prefer to mention Orbot in the Orfox notes, though, instead of 
> keeping it as a first-class project. Something like: "if Orfox 
> crashes on your device because of GPU problems, either use the 
> older, less private Orweb instead, or simply don't browse the web 
> on your mobile device."

I'm very happy to discover upon looking at the forum that 2 new
alpha/beta releases of Replicant 6.0 came out in the past month.  Among
other things, they add support for the Galaxy S2 (previously only the
Galaxy S3 was supported by 6.0), add a bunch of security/privacy fixes,
and include the optional ability to work with Firefox-based browsers.
Wolfgang says that the more compatible software GPU emulation is too
slow at this point to be enabled by default, but he gives instructions
to enable it.

Galaxy S3: https://redmine.replicant.us/boards/21/topics/12057

Galaxy S2: https://redmine.replicant.us/boards/21/topics/14009

Experimental support for Galaxy S3 LTE (modem won't work, but otherwise
is hoped to be comparable to the standard S3):
https://redmine.replicant.us/boards/27/topics/2175?r=14006#message-14006

So, I revise my prior recommendation: assuming that the new 6.0 release
works as described with Orfox (I have not yet installed it to try), I'd
suggest removing Orweb as a recommendation, and inserting a note about
Orfox saying that Replicant users should follow Wolfgang's instructions
"Enabling llvmpipe as software renderer".

Also note that the built-in WebView in these builds is still 1.5 years
old (because newer WebView versions crash unless the slower software GPU
emulation is used, and Wolfgang isn't yet comfortable forcing all users
to use that slower mode), so it might also be useful to insert a note
saying that browsers that use the default WebView (meaning anything
except Firefox-based browsers and maybe Chromium) are likely to have
exploitable security bugs and therefore should not be used with
Replicant.

Very very encouraging.

-----BEGIN PGP SIGNATURE-----

iQIbBAEBCgAGBQJYjysBAAoJELPy0WV4bWVwH8kP92rCp/FAZLz0YPOWwsjGzhhF
sbUqZeUj1/Q1/OTLUMA6EYgI8oSlms3BS7HdkEtDs4o/PPmLIGKbd7yzL0+1z0p5
gMcqZW9NU90Rzt0aJDwLPi7B/1UAizzuPrrLDfeyzJ+VVoIhaCtlPjCGid0rOqw2
m1s6YyGCHL6uUeYzm9oiZ/Q7OaxSbepsdzYUtk8+YOrpo0IfMSQ70KRuWNcjChSC
lclH5Ba1XlYyGNPc2FRxuSvv9ZRc3MthvdpG0z8nLkuABTzBLFGVerVoxpuCm1bj
jArQL5cSQPyhPWgna/Mvp4UCpJgkwGj2+ynYOLo30Uo7GJPA3HxN1bgO0cr5E99X
cD2WlNgfG3KRrZ/djTXe5TS/btQkBxxLXGEopqjg7dnv02bvXqD71+tC3MaCwPNS
BWBbS04GLq68MDZZ2F8QE+hHaBQPcghVjiWjuVisdtXv0GuIgauf9sNqKHFYJbjq
fdZ8hHhrFWBJB81KeLMeR8yxUsQbUP9OYIcfdEBi11QSmxmEnVKcOVWrsszbYpcz
fRaL9SKwvlN+Flqebn75on+1He5frLv/xd/J03VDWDhuOqArDQZpcr6TlXOgMNEC
vuH5Na53d3Wu1j0d+6MxkkxNQxUGyrlUMBYDVRxfl1bmizk5JZ7bntSKy8h+FKk9
AnCmVx2kM9HIOWgc8y4=
=edhI
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
Looks like the consensus here is "remove Orweb; add Orfox with a note about using Orweb on Replicant."

**Comment by strugee** [comment]
Actually, given the discussion in #1746, I think we probably shouldn't recommend Orweb at all? It's unmaintained and seems kinda busted/sketchy.

**Comment by anthologist** [comment]
Seriously, why is Orweb still listed there?
Also Orfox is sadly outdated and poorly maintained, I pinged GuardianProject guys some months ago but it looks like they are unable to manage a development of a webbrowser.
I think that shouldn't be listed too.
