### ISSUE TITLE
New category "Link shortener"

### ISSUE THREAD

**Issue by nidico** [nylira/prism-break#1436]
Replace proprietary link shortener such as bitly.com with self-hosted, free software altertives such as [Yourls](https://yourls.org/) or [Polr](http://polr.me/). I don't have an overview of available tools though, neither proprietary nor free.

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted#url-shorteners

**Comment by Zegnat** [comment]
I am going to close this because I really don’t think it is PRISM Break’s place to say what link shorteners people should use. I don’t know of any reason to think I would be endangering my own privacy if I shorten links, the problem would be more in clicking them, but then we should be recommending URL expanding browser add-ons. And even that is a fringe case.

Want to be safe? Do not shorten links. The people you give the links to will also be happy if they can see where they are being sent.

If someone can make a privacy oriented case here, sure, but I think it is easier to just not use this.

**Comment by hasufell** [comment]
well, if you use non-persistent link-shorteners that expire after a few days or so, then you are semi-anonymizing the links (e.g. to wikileaks) you are sending others over non-encrypted channels
