### ISSUE TITLE
Privatoria

### ISSUE THREAD

**Issue by ceyhanmolla** [nylira/prism-break#1437]
Privatoria is your secure and confidential Internet

```
Secure VPN and Anonymous Proxy, that enable you to surf anonymously, change your IP, unblock sites, etc.
Anonymous E-mail, Secure Chat and Secure Call and Video Call for secure communications
Secure data transfer via FTP and Secure Data and Message Storage
```

Privatoria’s list of services includes secure solutions for business and internet security for individuals.

The company was founded in 2013. Privatoria’s team has 10-year experience in IT, especially in Internet security.

Privatoria’s services have a patent for utility model No.85414 “Confidential data transmission method” of 25.11.2013.

Privatoria is a service that allows a truly anonymous communication on the Internet. Our mission is to uphold the right for privacy, which is guaranteed by the Universal Declaration of Human Rights.

https://privatoria.net/

**Comment by alerque** [comment]
I don't see how this is a useful proposal for inclusion on PRISM-Break. VPN's are useful, but how a proprietary (patented) VPN system has anything to bring to the table that would warrant us recommending this over open solutions to the same problem. This isn't a directory to advertise VPN services and having to trust a provider on faith that they are honoring their privacy policy is sub-optimal when you could be using a system that doesn't require any trust in a third party because technologically it leaves them out of the loop anyway.

**Comment by strugee** [comment]
@alerque somewhat touched on this, but it's also [against PRISM Break's policy][1] to include non-free systems.

 [1]: https://github.com/nylira/prism-break#project-inclusion-guidelines

**Comment by strugee** [comment]
Closing the above comments. Plus, especially given the somewhat ridiculous list of protocols they use at the bottom of the page (which sounds fancy but actually tells us nothing about the protocol), I'm kind of suspicious of their VPN's crypto. Generally first rule of crypto is to not invent it yourself which they seem to have done.
