### ISSUE TITLE
Re-add TrueCrypt and add VeraCrypt to disk encryption tools

### ISSUE THREAD

**Issue by Exoyds** [nylira/prism-break#1442]
TrueCrypt has actually been audited and the second most recent version (7.1a) is quite safe to use. Also VeraCrypt is a fork of TrueCrypt with improved security.

**Comment by alerque** [comment]
Did you do _any_ research before posting this? There are other issues open for discussion on this as well as background discussion before those. Unless you have something to add that hasn't been brought up this is a duplicate and should be closed so that discussion continues where it's already in progress or resolved.

TrueCrypt: active: #995, background: #638, #659, #949, #986, #996, #1003, #1016, #1212, #1213, 
VeraCrypt: active: #1273, background: #1398
