### ISSUE TITLE
Fennec FDroid archived

### ISSUE THREAD

**Issue by IDKwhattoputhere** [nylira/prism-break#1443]
https://prism-break.org/en/projects/fennec-fdroid

https://f-droid.org/forums/topic/where-has-fennec-f-droid-gone/

:(

**Comment by vyp** [comment]
And looks like firefox will also be dropped: https://f-droid.org/repository/browse/?fdfilter=firefox&fdid=org.mozilla.firefox

There are still a few non-fdroid options though as it says on that page. In case the page also goes down, copy pasted:

> DEPRECATION NOTICE

> Note that this package will soon be dropped from the F-Droid repo. Please consider using one of the following options for continued update support:

> Manually download updates from [Mozilla](https://ftp.mozilla.org/pub/mozilla.org/mobile/releases/latest/android-api-11/multi/)
> [FFUpdater](https://f-droid.org/repository/browse/?fdid=de.marmaro.krt.ffupdater) - external updater for Firefox
> [Firefox Aurora/Developer Edition](https://www.mozilla.org/en-US/firefox/channel/#developer) - bleeding edge Firefox with automatic updates
> [OrFox](https://f-droid.org/repository/browse/?fdid=info.guardianproject.orfox) - based on the TOR Browser bundle of Firefox, get it from the [Guardian Project Alpha Channel](https://dev.guardianproject.info/debug/info.guardianproject.orfox/fdroid/repo)

I guess either suggesting the FFUpdater app or just pointing visitors to the Mozilla's ftp server directly (because FFUpdater is alpha) maybe the best way to go?

And perhaps OrFox could be a future addition regardless? (I believe it's supposed to be just like Orweb, but using Firefox's Gecko layout engine instead of webview. I'm not sure if that means Orweb is being discontinued.)

Btw Fennec was dropped apparently because they were having difficulties building it, I'm not sure if that means Firefox/Fennec (for android) should be removed from prism break altogether.

**Comment by IDKwhattoputhere** [comment]
There are updates being released for Fennec F-Droid again but only on the F-Droid archive. Not sure what to make of that. Also IceCatMobile is available on the F-Droid archive and is receiving updates too.
