### ISSUE TITLE
img.bi Not work

### ISSUE THREAD

**Issue by ceyhanmolla** [nylira/prism-break#1449]
img.bi Not work . Please remove.

https://prism-break.org/en/projects/imgbi/

**Comment by vyp** [comment]
@komachi Is the site just down?

**Comment by Zegnat** [comment]
Looks like it is down, no news on if it will be back any time soon. Cf. imgbi/img.bi#53.

I guess we should set-up some time limit for PRISM Break. Maybe take it off the site at 21st December, 1 month after the first mention of them going down?

**Comment by vyp** [comment]
I suppose that's reasonable. I also think it should be re-added if the issue is fixed *after* it's taken off, do you?

**Comment by Zegnat** [comment]
I see no problem with that, we do not have that many image hosts in the web service category that it would be redundant. Unless in the time it is offline someone comes with a better solution to replace it, of course.

**Comment by vyp** [comment]
Cool, agreed.

**Comment by strugee** [comment]
We could run our JSON through something that strips comments. That would allow us to keep the data, but commented out. Or add a "disabled" key. (Does this already exist? I can't remember.)

**Comment by alerque** [comment]
There is also `git revert`. Nuke the data, commit, and then at some point in the future if you want to restore it just revert the commit.

**Comment by Zegnat** [comment]
> We could run our JSON through something that strips comments.

True. There are some JSON dialects that specifically support comments. There are also tool that will strip comments, and some recommend simply pushing the files through a JavaScript minimiser. Lots of options.

> Or add a "disabled" key. (Does this already exist? I can't remember.)

We don’t have that. And temporarily hiding something is something you do not want to have to do often anyway, introducing that as an option isn’t the best idea going forward IMHO.

> There is also `git revert`. Nuke the data, commit, and then at some point in the future if you want to restore it just revert the commit.

I have to wonder if this will not just give merging conflicts leading to it not being any easier than the other methods. PRISM Break has had merging problems enough, most of them caused by having all data in a single file.

I have been thinking about trying a different storage solution than one big JSON file. Maybe a single file per project. This way adding and removing projects will never conflict with other projects. It would also become easier to see which projects have had translations added and which still need work. But I need more time for such a refactoring. Maybe over Christmas.

**Comment by nylira** [comment]
I'm thinking of rebuilding the site with Rails and Postgres. It won't be as
to rehost but we'll be able to update it much easier, enable search,
rankings, up votes, reviews, comments, etc.

Just have to figure out a good way to allow wiki-style editing.

On Tuesday, December 8, 2015, Martijn van der Ven <notifications@github.com>
wrote:

> We could run our JSON through something that strips comments.
>
> True. There are some JSON dialects that specifically support comments.
> There are also tool that will strip comments, and some recommend simply
> pushing the files through a JavaScript minimiser. Lots of options.
>
> Or add a "disabled" key. (Does this already exist? I can't remember.)
>
> We don’t have that. And temporarily hiding something is something you do
> not want to have to do often anyway, introducing that as an option isn’t
> the best idea going forward IMHO.
>
> There is also git revert. Nuke the data, commit, and then at some point
> in the future if you want to restore it just revert the commit.
>
> I have to wonder if this will not just give merging conflicts leading to
> it not being any easier than the other methods. PRISM Break has had merging
> problems enough, most of them caused by having all data in a single file.
>
> I have been thinking about trying a different storage solution than one
> big JSON file. Maybe a single file per project. This way adding and
> removing projects will never conflict with other projects. It would also
> become easier to see which projects have had translations added and which
> still need work. But I need more time for such a refactoring. Maybe over
> Christmas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nylira/prism-break/issues/1449#issuecomment-162553298>
> .
>


-- 
Peng Zhong
Interaction Designer & Developer

Designer at http://nylira.com
Curator at https://prism-break.org
GitHub: https://github.com/nylira
LinkedIn: https://www.linkedin.com/in/nylira

**Comment by k3d3** [comment]
Why not use Up1? It's open source, faster, more efficient (uploaded files are 100% size of the original, not 125%) and has smaller URLs while still being secure. It's also more popular on GitHub.
