### ISSUE TITLE
Spideroak Kloak

### ISSUE THREAD

**Issue by kevinSuttle** [nylira/prism-break#1457]
Zero knowledge social network https://spideroak.com/solutions/kloak

**Comment by juanito003** [comment]
To figure in the Prism-break list, programs need to be Free and Open Source Software and respect the [Four Freedoms](https://en.wikipedia.org/wiki/Free_software):
Freedom 0: The freedom to run the program for any purpose.
Freedom 1: The freedom to study how the program works, and change it to make it do what you wish.
Freedom 2: The freedom to redistribute copies so you can help your neighbor.
Freedom 3: The freedom to improve the program, and release your improvements (and modified versions in general) to the public, so that the whole community benefits.


Spideroak Kloak and other Spideroak solutions are services that run on servers you don't control.
It's your choice to use it, but we won't recommend it on prism-break.
