### ISSUE TITLE
Should prism-break recommend TOX?

### ISSUE THREAD

**Issue by mimi89999** [nylira/prism-break#1468]
Please read this: https://markwinter.me/my-time-tox/

**Comment by vyp** [comment]
I read this the time it was posted. I was also aware of all the drama when it was happening. But it looks like tox has moved past that now. I believe the official antox is at https://github.com/subliun/Antox now.

I don't think this is grounds to remove recommending tox now. See https://blog.tox.chat/2015/07/current-situation-3/. So the tox development team has dissociated itself from the tox foundation as a result. And #1361 already fixed all the relevant links as a result to this.

**Comment by Zegnat** [comment]
We usually recommend OTR as the tested protocol, Tox is already only included as experimental. The actual drama was handled and we went with the Tox Project (rather than the Foundation) for our links afterwards (as @vyp) mentions.

As far as I know nobody has turned up any serious problems with their protocol, all the problems were with management. As such, I don’t really see a reason to remove it from the list after accepting it earlier.

If you have any reason to believe the version of Tox we link to has problems, please reopen and provide a source. Until then, I am closing this.
