### ISSUE TITLE
Unbubble.eu complaint

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1470]
Aside from the ads that sometimes appear on the right side (headed "Products" but redirect through a advertising company (tracking.s24.com)) they also redirect some results which are from "Fastbot" through fastbot.de. This is problematic in two ways:
1. Fastbot.de doesn't really have a privacy policy.
2. Fastbot.de is vulnurable to the POODLE attack.

Some time ago they also had search results which were indistinguishable from regular results but redirected through ZANOX AG's servers (aka disguised ads). I don't see those anymore though.

They also redirect all clicks on search results through derefer.unbubble.eu (probably to avoid referer tracking) which doesn't use SSL. I don't know if this or any of these problems are a huge deal though.

**Comment by Zegnat** [comment]
Have you contacted them about the Fastbot redirects? That sounds like a bug.
I think @Unbubble has been here on the issue list. See if they have an answer.

**Comment by Unbubble** [comment]
Thank you @IDKwhattoputhere and also @Zegnat for forwarding the complaint. The intermediate redirection is a requirement imposed by Fastbot. That's a very capable search engine subjected to German data protection acts, according to the website imprint and location of that company. We've verified they're using German servers and use no tracking techniques (cookies, tracking scripts) on their website. They even run their own anonymization proxies. From this whole picture we believe they are trustworthy enough to pass dereferred traffic through their redirection and that way support their funding. It's for sure a trade-off...

This kind of redirection by the way allows ad-funded services to draw a revenue share from e-commerce websites or ad networkds. All hosted search engines at prism-break.org rely on such kind of revenue direct or indirect. Most of them frankly would stop operating immediately without the funding. That's capitalism.

About the POODLE vulnerability of Fastbot: How high would you estimate the risk? Since neither of our services collects personal data and there is no login and little sensitive data to spy on at all, it doesn't seem to be the kind of attack vector blackhats would be interested in in the first place. I'll however forward the complaint. If you can prove or explain why this is a highly critical issue in our situation, I'd remove fastbot until they fix it.

**Comment by IDKwhattoputhere** [comment]
So no bug.
Germany is certainly not the best country for hosting but I guess that's another discussion.
> (cookies, tracking scripts)

Not needed to track users if they redirect clicks on search results. Even server logs are enough to track a lot.
> that way support their funding

Why do they require the redirection? How does it support their funding?
> All hosted search engines at prism-break.org rely on such kind of revenue direct or indirect.

True, but the others clearly mark ads as such. You however call the ads "Products" or similar. In the past (at least I can't seem to find this anymore) you also redirected completely legit looking results through Zanox servers. Very shady and you can't tell me Zanox wasn't tracking the users.

> neither of our services collects personal data

It still stands that fastbot.de doesn't disclose which information is being collected and how it is used.

> I'll however forward the complaint.

Not necessary. I already did this a few days ago but with no response yet.

It is a privacy and in a way also a security risk. Encrypting everything and doing so in a state-of-the-art way is important especially when on untrusted networks. An attacker (e.g. an ISP, someone on an open wifi or when using Tor a Tor node) can modify any unencrypted content or break weak or vulnerable encryption and inject e.g. Javascript to install malware. That's why you should also start using HSTS like the other search engines on prism-break.org and start using TLS on derefer.unbubble.eu too.
It's also not a good way of managing these things to let vulnerabilities like this exist no matter how low the risk level.

BTW: Fastbot also offers a toolbar which is getting high detection rates on Virustotal (https://www.virustotal.com/file/4a1abc9e55c847285b1748be93559b6cc1dd805f9e262a4e4eaead3a9a78ebeb/analysis/).

**Comment by Unbubble** [comment]
@IDKwhattoputhere 
> Germany is certainly not the best country for hosting but I guess that's another discussion.

Most of your posting is another discussion. The biggest Google alternative recommended by Prism-Break is a US venture capital start-up hosted at another huge US company (will you find out the name?). How could anything be less alarming in the age of the PATRIOT Act.

> Even server logs are enough to track a lot.

Server logs in Germany store incomplete IP addresses. That's a legal requirement enforced by their webhosting company.

> It still stands that fastbot.de doesn't disclose which information is being collected and how it is used.

What information are you talking about? There is neither a login nor do they use client side tracking. Fastbot clearly states to adhere to the German law. IP addresses will be truncated. They use local infrastructure. This is a religious discussion...

**Comment by IDKwhattoputhere** [comment]
> Most of your posting is another discussion.

No, it really isn't.
Of course you wouldn't respond to any of the other points I made and just dismiss all I said as religious. I'm not going to repeat myself too much here because you're just going to ignore it anyways. Maybe I just hit a nerve.

DDG at least marks their ads as such and doesn't maliciously redirect legit looking results through advertising companies. They also have a hidden service. And if that's not enough there's for example Startpage or Metager.

And the PATRIOT Act really is only alarming if you're afraid of certain agencies.
But since you apparently are: Germany has the BND who is also trying to get into the Five Eyes, so there's that. Data retention laws are being pushed all the time but gladly they haven't succeeded yet (except for the stuff they pushed in October which isn't affecting websites).

> What information are you talking about?

There certainly needs to be some kind of information they collect or why else would they require the redirection? Again, you're ignoring the questions you don't want to answer.

**Comment by Zegnat** [comment]
As I haven’t seen any weird or hidden ads on Unbubble the times I have tried the service I will not comment on that. I will now, after sleeping on this issue, comment on the other stuff.

> > What information are you talking about?
> 
> There certainly needs to be some kind of information they collect or why else would they require the redirection?

It is totally unclear if Fastbot collects server logs or any other sort of analytics. They don’t seem to have any sort of privacy policy – which I think is the main issue @IDKwhattoputhere is having – where they specify what information they are or are not tracking. All they have is a single terse paragraph on their [Impressum](https://www.fastbot.de/impressum.html).

In fact, that one paragraph says they get to share whatever information they collect with “partners”. Still without specifying what they are collecting or who their partners are. Emphasis mine:

> Sämtliche auf dieser Website erhobenen persönlichen Daten werden ausschließlich zu Ihrer individuellen Betreuung, der Übersendung von Produktinformationen, der Unterbreitung von Angeboten oder der Auftragsabwicklung gespeichert, verarbeitet und **ggf. an unsere Partnerunternehmen weitergegeben**.

If Fastbot requires Unbubble to send everyone through their own servers, this is probably because they are tracking something. Without information from them, we just don’t know what that something is.

> About the POODLE vulnerability of Fastbot: How high would you estimate the risk? Since neither of our services collects personal data and there is no login and little sensitive data to spy on at all, it doesn't seem to be the kind of attack vector blackhats would be interested in in the first place.

I suspect the POODLE vulnerability is pretty neglect-able. If I recall correctly (POODLE is a 2014 bug, so excuse me if I’m hazy on the subject) it has never been trivial to execute this attack and it really only helps for decrypting session data, of which there shouldn’t be any when I am just visiting their redirect domain.

> Encrypting everything and doing so in a state-of-the-art way is important especially when on untrusted networks. An attacker (e.g. an ISP, someone on an open wifi or when using Tor a Tor node) can modify any unencrypted content or break weak or vulnerable encryption and inject e.g. Javascript to install malware. That's why you should also start using HSTS like the other search engines on prism-break.org and start using TLS on derefer.unbubble.eu too.

This, however, is true. Especially derefer.unbubble.eu not being protected with TLS could pose a security risk. Even when an attacker cannot MITM my search requests, they still get to track what links I click and possibly redirect me to completely different websites.

If you do not wish to purchase yet another certificate, putting the dereferer under the same domain works just as well (e.g. `https://unbubble.eu/deref?url=https://prism-break.org/`). Then you can focus on getting the highest possible [SSL Labs rating](https://www.ssllabs.com/ssltest/analyze.html?d=unbubble.eu&latest) just for the one domain, e.g. by looking into HSTS and HPKP.

(Although you seem to have a wildcard certificate, so I am not sure why it is not implemented on `derefer.unbubble.eu`…)

To sum up:

1. Sending your users through a third-party redirect (Fastbot) that lacks a privacy policy is not a good idea.
3. Sending your users through a non-encrypted redirect (Unbubble’s dereferer) is opening the process up to MITM attacks and is just plain bad.
2. Wether a third-party (Fastbot) is susceptible to POODLE is of very low risk.

**Comment by Unbubble** [comment]
@IDKwhattoputhere 

US companies can be sentenced in secret trials to collect whatever data the government or agencies want. See the lavabit case. So the question is, who do you trust? This tends to be an irrational discussion. After Snowden revelations many users moved from Google (US) to DDG (US) which can't be more ironic. They've understood nothing. To make this clear, using Tor, VPN providers etc. may heal this, but most users don't.

> there's for example Startpage or Metager

The latter includes Fastbot in the same way as we do. The former redirects users through Googles tracking gateway. It's all the same when leaving the private search environment.

> There certainly needs to be some kind of information they collect or why else would they require the redirection?

They add their referral ID to certain results, receiving a revenue share that way. I've described the concept above and I'd provide an example to @Zegnat in private if required, because it's not my matter to publicly discuss their service and funding method.

> BTW: Fastbot also offers a toolbar which is getting high detection rates on Virustotal 

I actually didn't want to comment on third party software. Thus the late answer. The Fastbot toolbar (which we btw do not promote in any way) is recognized by Virustotal as "generic" or "searchit". Frankly spoken: Many toolbars were abusive in the past and so Virustotal in this case recognizes an unknown toolbar and estimates it could be malicious.

@Zegnat 

> It is totally unclear if Fastbot collects server logs

This is always a question of trust. What, if I ask them to add a sentence: "Fastbot doesn't collect any personal data." - would this heal any doubt? The only quite reliable knowledge about Fastbot is: They mustn't collect complete IP addresses as that's forbidden by law. They don't use tracking pixels, cookies, analytics code on their website. They use servers located in Germany. They encrypt the connection and POODLE ist a non-trivial MITM attack.

> Especially derefer.unbubble.eu not being protected with TLS

This is intentionally, since the HTTPS->HTTP step is usefull under some constellations to remove the HTTP referrer reliably and thus hide the query string. Perhaps it's time to revise this concept, but the attack vector still seems to be less critical.

All this leads me to the question, if the expectation is realistic for a search engine. We can never create a completely secure environment, protecting reliably against governments, malware, e-commerce tracking and other kinds of "attacks". Isn't that the actual reason why prism-break was startet? It's listing pieces of software and websites that help creating a sufficient environment for specific use-cases and needs...

Perhaps users should be informed, that non-tracking websites still inhere the risk of MITM, malware or tracking of user-behavior off-site. This is always the case, for each and every private search engine. Reliable solutions can be VPN, Tor, Adblockers etc.

**Comment by Unbubble** [comment]
topical related issue: https://github.com/nylira/prism-break/issues/1168

**Comment by IDKwhattoputhere** [comment]
I don't know why you're focusing on whether Germany is better for hosting than the US or not. I never said it wasn't. I only said it's certainly not the best option.

> The latter includes Fastbot in the same way as we do.

Apparently they do which is problematic.

> The former redirects users through Googles tracking gateway.

What exactly is that supposed to mean?

> They add their referral ID to certain results, receiving a revenue share that way.

How exactly is this done? DDG does it for eBay and Amazon by using rover.ebay.com and by adding a referral tag to Amazon URLs which seems like the only unproblematic solution to me. You also seem to do this on regular non-fastbot results without telling this anywhere on your site. You even claim that your affiliations have no impact on organic search results which is not true since you modify regular search results' URLs. I guess however that the sections "Sponsors" and "Products" are marked as ads obviously enough(?)

> (which we btw do not promote in any way)

You trust the website which distributes this software (whether it's adware or another kind of malware or harmless).

> if the expectation is realistic for a search engine

If others can do certain things better than why can't you?

I have three main problems here:
- You refuse to comment on the Zanox situation. Even if you don't redirect through them anymore you abused the users' trust and you should make a statement on that. You also need to make it obvious on your site that regular search results are still being modified in certain ways.
- Fastbot's complete lack of transparency on basically their whole service.
- Fastbot's operators don't seem to care enough about the service to fix a vulnerability which has been discovered over a year ago. Metager even fixed those issues on metager2.de (which was used to test experimental features) which noone uses anymore and which very few people ever used to begin with.
https://www.ssllabs.com/ssltest/analyze.html?d=metager2.de     
Grade circa a year ago (as far as I remember): C     
Grade now: A

**Comment by Unbubble** [comment]
@IDKwhattoputhere 

> You refuse to comment on the Zanox situation.

Above I've already told you a lot. Perhaps one more explanatory note. As soon as users jump off our website by clicking the search results of websites participating in advertising networks, they will be tracked on the (external) landing page. Nobody asks us or the users, if that's fine. It's just reality for users not protected by adblockers, VPNs or stuff. The idea is to turn the tables and make e-commerce websites at least pay our bill. That's what you saw. There is no additional privacy risk, because users clicking those links would be tracked anyway. And before you ask. We can't know all of those websites, so we can't remove them reliably from our search results. We just make the best out of it and try to convert omnipresent tracking somehow into a privacy enhancement.

> DDG does it for eBay and Amazon by using rover.ebay.com and by adding a referral tag to Amazon URLs which seems like the only unproblematic solution to me.

So in regards of privacy you trust global US-based marketplaces more than ageing and ambitious European search engines. That's purely arbitrary. Note their server location, their code, their history and so on. Dig a bit into their redirects. Look at their search results to understand, why some meta-searchers are fine with the trade-off.

**Comment by Zegnat** [comment]
> <i>[Fastbox]</i> add their referral ID to certain results, receiving a revenue share that way.

This is an interesting use of a redirector, and I guess I can see how that would work. However, it could also potentially be illegal. I am not sure of the situation in Germany, but both the FCC (U.S.) and ASA (U.K.) require affiliate URLs to be properly disclosed.

DuckDuckGo discloses their affiliate links [in their privacy policy](https://duckduckgo.com/privacy#s4). You, Unbubble, [discloses this](https://www.unbubble.eu/info/terms#sponsoring), which @IDKwhattoputhere seems to have missed. (Under ASA rulings, disclosure in the privacy policy might not be enough, but I personally don’t mind.) But you do not disclose it for Fastbox, and Fastbox does not disclose it anywhere when I visit them either.

Also, take the following sentence in your current policy:

> Technology like this will be used only in cases where target websites are already affiliated with such advertising networks and/or already track user behavior - even without our cooperation.

This would not cover the Fastbox redirect at all. The target website is in all likelihood not “already affiliated with” Fastbox. I found a t-online link, and I doubt they are affiliated with Fastbox. Instead you redirect every Fastbox result through Fastbox, which is purely a deal between Unbubble and Fastbox, and as a deal fairly hidden and not at all in favour of your users. Especially because your users have no reason to trust Fastbox…

> This is always a question of trust. What, if I ask them to add a sentence: "Fastbot doesn't collect any personal data." - would this heal any doubt?

Yes. I have discussed this before: always require a website to publish a privacy policy. Why? Because you can then hold them responsible and sue them. Especially under EU (and strong-consumer rights legislation such as Germany’s) having a company promise you something turns breaking such a promise into a liability for them.

Instead of a privacy policy we have 1 paragraph on Fastbot’s Impressum that tells me they get to store, use, and possible share with partners, any personal data they might be collecting. And they never tell me what they are and are not collecting. Sure they have to comply with German law and truncate my IP (which is NOT the same as being forbidden to log anything, truncated IPs can still be used to find country of origin and ISP) but other than that they are free to do a lot of things.

So, yes, if they add a privacy policy that says they will not store IP address (not even truncated), that would already go a long way. This is what DuckDuckGo says:

> When you access DuckDuckGo (or any Web site), your Web browser automatically sends information about your computer, e.g. your User agent and IP address.
> Because this information could be used to link you to your searches, we do not log (store) it at all. This is a very unusual practice, but we feel it is an important step to protect your privacy.

This is what Unbubble says:

> Unbubble does not collect, use or transmit any personal information. In particular, no user data will be combined into profiles or shared with third parties.

This is what Fastbot says:

> Sämtliche auf dieser Website erhobenen persönlichen Daten werden ausschließlich zu Ihrer individuellen Betreuung, der Übersendung von Produktinformationen, der Unterbreitung von Angeboten oder der Auftragsabwicklung gespeichert, verarbeitet und ggf. an unsere Partnerunternehmen weitergegeben.

That is a completely different kind of policy. Especially from a legal standpoint. Fastbot is extremely opaque.

> This is intentionally, since the HTTPS->HTTP step is usefull under some constellations to remove the HTTP referrer reliably and thus hide the query string. Perhaps it's time to revise this concept, but the attack vector still seems to be less critical.

The attack vector is pretty big there, as you are specifically introducing a point to target with MITM. I could set-up an MITM on your dereferer domain specifically to catch people going to a bank site, and redirect them to a fake version. If your dereferer is under HTTPS (or even under your actual domain name) I would have to MITM an encrypted connection, which is much harder.

You are currently setting up your users to be attacked at a place under your own control: your dereferer service. This is different from your “we can’t control what happens when people have left our page”.

I would be interested in hearing why you decided to go with the HTTPS→HTTP step though. As I have never read anything about this being necessary. You can find my contact information on my GitHub profile. If I can help you figure out the most secure way to hide HTTP referer information, I would be happy to put some time into that.

> All this leads me to the question, if the expectation is realistic for a search engine. We can never create a completely secure environment, protecting reliably against governments, malware, e-commerce tracking and other kinds of "attacks".

You, as a search engine, can be expected to give an unbiased search result (which we assume you do, as a meta search engine) and then send your users on to the websites you found for them. Adding undisclosed affiliate links or third-party redirects under your direct control is not expected by your users. I don’t think any of that is unreasonable?

Of course you are not at all responsible for a toolbar released by Fastbox, just when you want to use Fastbox as one of your many sources. Neither are you responsible for a linked website containing ads.

> > <i>[Metager]</i> includes Fastbot in the same way as we do.
> 
> Apparently they do which is problematic.

Yes, if we make Fastbot an issue that would also disqualify Metager from the list. I think @D3nshi previously acted as spokesperson for them, maybe we should get him in on this too? (Ping!)

**Comment by IDKwhattoputhere** [comment]
@Unbubble 
> It's just reality for users not protected by adblockers, VPNs or stuff.

Users who take their privacy seriously will already use those solutions. They can't however use your service and protect themselves since you use redirection which can only be avoided by not using your service.
Therefore
> There is no additional privacy risk, because users clicking those links would be tracked anyway.

is also not true. You also let the users get tracked by additional services which the user would have never been tracked by if they used another search engine. I also don't get your attitude here. Are you saying that the users' privacy is going to be violated anyways so why shouldn't you make a buck off it? That's a strong anti-privacy stance which in my opinion clearly disqualifies you from PRISM Break.

> Note their server location, their code, their history and so on.

This discussion is still about the flaws of your search engine and not DDG's.

Sadly still no stance on many of the points I made before.

@Zegnat 
> Of course you are not at all responsible for a toolbar released by Fastbox, just when you want to use Fastbox as one of your many sources.

They are not responsible but I don't think it's advisable to affiliate yourself and redirect your users through a service that distributes malware (if it is in fact that).

**Comment by Unbubble** [comment]
@Zegnat 
Thanks for offering assistance! IIRC the RFCs define not to leak the exact URL between HTTPS and HTTP links. Our research has shown this is valid for redirects in all popular web browsers. Meanwhile we started using some HTML for the same purpose, so perhaps we can switch that part of the search engine to HTTPS short-term without exposing queries to third party. It needs some testing.

About the other topics we'll now proceed with internal discussion. I hope that's okay and also hope to return with some results soon.

**Comment by Unbubble** [comment]
So, as a result we've published some changes today to make things clearer and more secure. The dereferrer now gets called via HTTPS while still hiding search details from third party. Information and layout all over the website have been updated to make things clearer. We'll get in touch with @Zegnat privately about the other concern, since it's not primarily about our website, but about an appreciated partner of us and we don't want to discuss this in public.
