### ISSUE TITLE
Will Ubuntu/Derivatives be considered again after the 16.04 update?

### ISSUE THREAD

**Issue by 1029chris** [nylira/prism-break#1471]
Since Ubuntu 16.04 is disabling it's spyware by default on it's upcoming version 16.04, will Ubuntu or its derivatives be considered then?
I'd argue that Linux Mint, and the other Ubuntu derivative should be considered again after 16.04, because they provide good security through encryption. They provide an easy way for beginners to encrypt their systems. I don't think Ubuntu's packages outside of Unity contain any spyware myself. Trisquel is based on Ubuntu, and is endorsed by FSF/GNU. The FSF/GNU is arguably more concerned about free software than us, and they endorse Trisquel. Issue #642 claims that Linux Mint connects to many different domains, and it does. Because Linux Mint automatically checks for updates, so Mint connecting to so many domains would be expected.
I think this list needs a true beginners distribution. Not even Fedora is a true beginners distribution. Will the tech illiterate looking at this list try something difficult, or just keep running Windows/OSX?
Proof: http://www.pcworld.com/article/3015021/linux/ubuntu-1604-lts-wont-send-local-searches-over-the-web-by-default.html

**Comment by hasufell** [comment]
> I don't think Ubuntu's packages outside of Unity contain any spyware myself.

That's your opinion. It's a question of trust though. Do you believe someone who has lied to you once?

> The FSF/GNU is arguably more concerned about free software than us

Exactly. They primarily care about license stuff, not security, so they have a completely different focus.

**Comment by 1029chris** [comment]
Do we have any actual evidence that Ubuntu's packages spy on us? What about Arch, do we have any evidence that Arch doesn't spy on us? Yes, Ubuntu included a "spyware" feature, but they made sure you could turn it off. I do agree that having it on by default (Or having it in the first place) was a horrible move, but they've realised their mistake. This web search feature of Ubuntu also sucked, because Ubuntu went out of their way to make sure there was at least some privacy to it. Rather than directly contacting Amazon/other sites, they sent the search info through their servers first in order to make the info anonymous. That made the search feature pretty bad, but Ubuntu kept it that way because they wanted some privacy for their users. I know that it doesn't provide full privacy, but this at least showed Ubuntu's intentions. But in the end, Ubuntu remains open source, just like the other distros. I still think that Ubuntu itself shouldn't be considered, because the feature will be available to turn on. But I think that Ubuntu's derivatives (Mint, Elementary, Xubuntu, etc) should be looked at once again, because the adoption of secure operating systems by tech illiterate people is important. Those distros do not include the spyware at all.

The GNU Project wrote about the Ubuntu search feature here: https://www.gnu.org/philosophy/ubuntu-spyware.en.html
I think this demonstrates that they do in fact care about security. Yet, they support the use some of Ubuntu's packages and repos.

**Comment by hasufell** [comment]
> What about Arch, do we have any evidence that Arch doesn't spy on us?

There was no such incident in arch linux yet. It's a community distro by users.

There are enough distros out there to not walk the thin line that is called Ubuntu.

**Comment by vyp** [comment]
> but they've realised their mistake.

How so? Just making it opt-in in 16.04 is not enough (as you point out). But even if they remove it outright, the damage is already done. There's *no actual reason* to trust them *again*, especially when we already have so many other options to choose from.

That's not to say they couldn't possibly turn a new leaf (i.e. cut out recommending proprietary programs altogether and explicitly promote the teaching of privacy/security related topics such as encryption) in the future despite the damage.

---

Of course the FSF care about security. In fact, for any project to be taken seriously as secure and usable software these days, it *has* to be free software first and foremost. So free software takes us that far, but it's possible to have malicious free software. So @hasufell's point is that the FSF is happy to promote things as longs as it's 100% free software, meaning the problem is that the FSF does not go beyond that to analyse free software to see if it is malware or not. (Of course, they likely do not have the resources to do so, I'm not blaming them.)

So just because the FSF recommends Trisquel, does not necessarily mean that it *should* be recommended from a privacy/security perspective. Yes, Trisquel does not use Unity, but that's where the distinction ends. Apart from cutting out nonfree software (which is a *really good* thing btw), Trisquel basically *is* Ubuntu because it uses Ubuntu's repositories. And so who's to say they (i.e. Ubuntu) don't maliciously patch say Libreoffice for monetarily motivated purposes? (They are indeed a company, i.e. financially driven. Nothing necessarily wrong with that, but given that they have already betrayed trust, and that they *do have* financial incentives to continue doing so, it makes it more of a risk in my opinion.)

Debian for example is actually doing something about this with their reproducible builds project. With which users can, to a certain extent, have a guarantee that this binary they are running corresponds to this source code. So why not similarly also distrust other non-source distributions such as Fedora and Arch? It's really the same situation, we have no real way of being sure. But it's a matter of trust, reputation and community (because for example, these distributions are not as financially driven like Ubuntu is). They haven't had any such incidents like this. (In fact, if the Unity incident never happened, there's a good chance I think that Trisquel would still be recommended today on Prism Break.) Arch for example even has a reputation of providing vanilla non-patched packages unlike a lot of other non-source distributions. (That's not to say they can't blow that reputation in the future of course.)

**Comment by 1029chris** [comment]
> And so who's to say they (i.e. Ubuntu) don't maliciously patch say Libreoffice for monetarily motivated purposes?
> There's no actual reason to trust them again, especially when we already have so many other options to choose from.

Isn't that a bit of a leap, however? The Unity dash was a horrible idea, yes. But how did they implement it? Through open source software. They allowed you to turn it off. I talked about this. But saying since Ubuntu tried to make money in an open way that attempted to preserve some privacy equals that they'll do it in a secret evil way is a huge leap. If Ubuntu really was spying on us, we'd have figured it out by now. Users were able to figure out the many ways that Windows 10 spies on its users, quite easily with Wireshark and other tools.
I know there are many alternatives to Ubuntu, but which alternatives are as user friendly? Which allow the tech illiterate to easily encrypt their hard drives, and easily run a system with little to no maintenance required? Certainly not Fedora or openSUSE. Those distros would be fine in the hands of people who are already a little bit about technology, but it's still not enough. Fedora/openSUSE are more enterprise distros. Ubuntu and its derivatives are meant for the user's desktop. I still don't want Ubuntu itself on the list, but something like Mint, Elementary, or Trisquel is needed.

**Comment by vyp** [comment]
> But saying since Ubuntu tried to make money in an open way that attempted to preserve some privacy equals that they'll do it in a secret evil way is a huge leap.

Yes I agree I gave a harsh stance to Ubuntu, and with no evidence too. But I still don't see why they should be trusted? Allowing to turn it off is good, but that should be an assumed very minimum option to give. Because *not* allowing to turn it off would be much much worse. Similarly, implementing it as free software should also be a minimum, taken for granted. But the main thing here is that it was implemented as opt-out, not opt-in. It would have been so much better if it was opt-in. It's a huge source of distrust to make it opt-out, even if they did it 'openly', because it signifies their intentions are not aligned enough with the ideals of security and privacy. Because they know that the majority of their non-technical users will not specifically opt-out of it. So this means they are okay with taking advantage of their users. (I don't think this is a huge leap.)

> Fedora/openSUSE are more enterprise distros. Ubuntu and its derivatives are meant for the user's desktop.

How so? I think Fedora and openSUSE are fine as a "user's desktop". Do you just mean the Unity interface vs Gnome/KDE? Because I really don't think Gnome/KDE is too difficult to use for the average non-technical user compared to Unity. So perhaps you mean other things?

I'm just saying I prefer to not recommend Ubuntu because we already have other options which I feel are much more trustworthy and still user friendly enough (which I guess is where you disagree with me). But this is just my opinion, not necessarily the opinion of Prism Break's.

**Comment by 1029chris** [comment]
> I think Fedora and openSUSE are fine as a "user's desktop".

They are great distros, I use Fedora on my laptop actually. But they are not true beginners distros. I'm not talking about the Desktop Environments. Fedora requires a lot to be done from the command line. When I say tech illiterate, I'm think of my parents. They barley know how to navigate their computer. I guarantee you they'd get confused by the Fedora/openSUSE installer. "What's a partition?" "What's LVM mean?" Do you get what I mean? The ubiquity installer that Ubuntu and its derivatives use is very easy, and written with language that anyone could understand. The software updater doesn't need you to ever touch the terminal, and new software is installed easily. When the next version of the OS comes out, it'll notify you and tell you to how to upgrade, including the risks involved and such. It's easy! Not complicated at all. The terminal never has to be used, ever. My parents could easily use Mint, Elementary, and even Ubuntu. Fedora/openSUSE would be confusing and strange. Especially Fedora at first, because Gnome can be confusing ("Where's the minimize button?" "Where's the start button?"). We shouldn't encourage difficult things onto people like that, they would give up and go back to Windows.

>  It would have been so much better if it was opt-in. It's a huge source of distrust to make it opt-out, even if they did it 'openly', because it signifies their intentions are not aligned enough with the ideals of security and privacy. Because they know that the majority of their non-technical users will not specifically opt-out of it.

I agree, that's why Ubuntu itself should not be recommended. But let's not forget that it was all contained within Unity, and that they are making it opt-in now. I mentioned before as well that they attempted to maintain some privacy.

Distro's like Mint, Elementary, and Trisquel are community driven. If you know another distro that is as easy as the ones I've mentioned, then please tell me.

**Comment by hasufell** [comment]
> If you know another distro that is as easy as the ones I've mentioned, then please tell me.

[LMDE](http://www.linuxmint.com/download_lmde.php), but it was removed due to [lack of focused development(]https://github.com/nylira/prism-break/issues/805).

**Comment by 1029chris** [comment]
> LMDE, but it was removed due to lack of focused development.

Is LMDE 2 any different?

**Comment by mvdkleijn** [comment]
I've read this and the earlier discussion on Ubuntu (and derivatives) entirely. While I agree with some sentiments like people should stop using Ubuntu itself... I also believe prism break is not doing this correctly.

If you are really concerned about trust, security and transparency, those qualifications apply not only to the distros you may or may not recommend but also to yourselves.

In this particular case of the distros, that trust, transparency and security requires you to earn it:

1. Create a clear, published (on the site) list of points against which a distro is judged.

2. Each point should be documented as to why its in the list.

3. Changes to said list should be transparent and documented.

4. Each distro should be rated against the list with a weighted points system and not be excluded.

5. A generic "if a distro has X points or more you can use it" statement should be made. This might be split into recommendations for beginners and "advanced" users. The weights will allow youbto highlight points that are particularly important.
6. Distros that are not tested should get a generic disclaimer like "we did not test this distro so we cannot make and recommendations for or against it"

If you do that, I have more reasons to take your recommendations seriously. Until then, you can't really give anyone serious advice on this....

**Comment by hasufell** [comment]
I've given such lists in other threads before, but I'll try to sum up what comes to my mind right now. These are not ordered in any way:
* **popularity**: yes, this is important, because it means there are eyes on it, people use it, test it and there's some pressure on the development to not screw up. It also implicitly affects other points.
* **manpower**: IMO, almost the most important point... a distro stands and falls with the number and quality of contributors. This also implicitly affects a lot of other points.
* **security**: How does the distro handle published security vulnerabilities? This affects a number of things: how does it deal with them internally, how does it communicate them to the user (a mailing list is a must, but not enough), what tools does it provide to keep systems up2date wrt security (tools to check if a system is affected?) Does it provide any additional technology that might improve the users security?
* **freshness/availability of packages**: how up2date are the packages? This is nost just important for usability, but also affects security. If the distro lacks behind (like debian), it must do security backports in order to not lose points here. Also, does it even provide the software recommended on prism-break?
* **choice**: For example, does the distro make efforts to offer choice to the user by trying to support libressl, mbedtls or others? If a distro is diverse in offering such security relevant choices and can still reasonably maintain them, then that's a big plus.
* **trust**: this is about the behavior of the distro community, its collaborators and also the internal structure. A distro doesn't need to be entirely community driven in order to qualify here, but the workflow, interaction with users, openness and participation in the open-source world is important. In addition, have there been any incidents that may indicate that the distro is untrustworthy in any way?
* **source vs binary**:  Is it a binary or source distro (or does it at least offer the choice to run it as a source distro)? This is important, because binary based distribution has generally more trust/security problems.
* **licensing**: affects the licensing of packages and all related code (e.g. of the package manager). Must be open-source licensed.
* **usability**: is the distro user-friendly? Can beginners use it? How easy is it to install and maintain?

Also, I don't think it makes sense to create a scoreboard for these. People should just go through the list when they want to add/remove a distro.

**Comment by 1029chris** [comment]
I just wanted to say that the latest version of Ubuntu does not have Amazon ads and data leaks by default anymore, so the warning should probably be changed.
