### ISSUE TITLE
Remove BlachBit from “Disk Encryption” category.

### ISSUE THREAD

**Issue by theReviser** [nylira/prism-break#1494]
the software "BleachBit"  is not an encryption-programm. BleachBit hasn't any function to encrypt. It's a tool to clean browser-history etc.
It should be removed as soon as possible.

Generally "diskcryptor" and "dm-crypt" should also be removed, because they are not clearly secure. They haven't been audited, like truecrypt. And if truecrypt or veracrypt is not sufficiently secure for being recommended (due to several "geniuses" here....), diskcryptor and dm-crypt are less secure then ever and should also be removed as soon as possible.

**Comment by Kamaluk** [comment]
I don't see the link between the truecrypt and diskcryptor or dm-crypt. Can u point that one out?

**Comment by theReviser** [comment]
Repeat: diskcryptor and dm-crypt have not been audited >> No audit = not secure >> Prism-break = only secure Software >> not secure = not in Prism-Break.

**Comment by alerque** [comment]
You're confused. Let me also point out that `audited != secure`. It just means there is some record of more qualified eyes having reviewed something, but crazy big issues turn up in previously audited software all the time and sometimes unaudited software proves to be much more robust. And no, PRISM-Break does not have a hard requirement on seeing audits for all software we list. It's nice and in some cases is a big factor in deciding whether to include something, but it isn't the magic bullet you're making it out to be. A lot of it here has to do with the expertise of our "local" experts perusing issues here and how comfortable they are with a project.

Now you might be right that the categorization is off. I would just say that you should re-focus your issue report on that point and/or any specific security issues we should be aware of rather than ranting about audits.

**Comment by anthologist** [comment]
-Veracrypt has not been audited, doesn't matter if it's based on truecrypt
-Truecrypt audit missed some vulns that were found some time later
-Calling people "geniuses" doesn't help you in any way

Also the only audited listed there, encfs, has an audit that says it has vulnerabilities.

**Comment by patheticcockroach** [comment]
@anthologist "Veracrypt has not been audited"
=> Diskcryptor hasn't been either, yet is included. Why not simply add both and mention they both haven't been audited? Adding one and not the other make it seem like there is a good reason to do so (maybe there is, I don't know, but then I think it would be worth mentioning it rather than just ignoring it)

+ what @theReviser said about BleachBit: it's a good program, but just not a fit for the "disk encryption" section (particularly as the first item on the list!)

**Comment by anthologist** [comment]
@patheticcockroach I was just replying to OP that seemed to consider Veracrypt audited, I'm not against its inclusion.
I agree about Bleachbit.

**Comment by Zegnat** [comment]
Bleachbit shouldn’t be there. Everyone is right about that. Going to mark this as waiting for a PR and change the title to be more clear.

The following is my personal opinion on the other “issues” discussed:

* My main reason for supporting the removal of TrueCrypt has always been that the developers asked for that to happen. It is just annoying to [go against a developers wishes](https://www.jwz.org/blog/2016/04/i-would-like-debian-to-stop-shipping-xscreensaver/). Full-disk encryption with LUKS, possibly through dm-crypt, is a very good and secure alternative. And if I am not mistaken, LUKS as a encryption algorithm has been audited.
* My main reason for not supporting the addition of VeraCrypt has always been that they have not complied with the TrueCrypt licence, and can thus be said to be appropriating the other developers’ work. Note that even the people behind the TrueCrypt audit [want to review the licence](http://istruecryptauditedyet.com), but this still hasn’t happened yet. As PRISM Break would like to stick to the truly <i>libre</i> software, this disqualifies VeraCrypt.
