### ISSUE TITLE
how about email sigaint.org?

### ISSUE THREAD

**Issue by outsinre** [nylira/prism-break#1501]
Does it worth a try? How about its security?

**Comment by Zegnat** [comment]
I am not sure if there is any sort of benefit to using a Tor-based email service. My gut feeling is no. So it really doesn’t add anything to your privacy.

**Comment by hasufell** [comment]
> I am not sure if there is any sort of benefit to using a Tor-based email service. My gut feeling is no. So it really doesn’t add anything to your privacy.

The main problem of E-Mails is the inter-MTA communication, which is based on the SMTP protocol without any guarantee of encrypted transactions at all, see the following quote from [RFC 3207](https://tools.ietf.org/html/rfc3207#page-6)
> If the TLS negotiation fails or if the client receives a 454 response, the client has to decide what to
> do next.  There are three main choices: go ahead with the rest of the SMTP session, retry TLS at
> a later time, or give up and return the mail to the sender.

Even if it's encrypted, it's trivial to gather enough meta-data to analyze relationships between communicators.

Adding anonymization to the MTA communication process is something I've actually studied a little bit and onion routing like methods (whether that involves Tor is a different story) seem to be the only useful solution, apart from abandoning the SMTP protocol and using things like [Dark Internet Mail Environment](https://darkmail.info/downloads/dark-internet-mail-environment-march-2015.pdf), which is still [WIP](https://github.com/lavabit/libdime).

Because of that, I don't really know what you mean with "My gut feeling is no". It depends on what sigaint.org is actually doing. I was not able to find specification information.

**Comment by Zegnat** [comment]
> Because of that, I don't really know what you mean with "My gut feeling is no". It depends on what sigaint.org is actually doing. I was not able to find specification information.

Neither was I, but from some cursory reading of blogs it seemed like they are like any other email service provider, except they are available (only) through Tor. Which would mean that the whole email-side of things gets no extra protection (assuming most email traffic is between sigaint and non-Tor mail servers). Therefore, a gut feeling :wink: 

Maybe if @outsinre has some more information they could let us know. Else I am just going to close this issue in a few days time. I don’t mind referring to /r/privacy’s list for all these private email providers.

**Comment by yegortimoshenko** [comment]
SIGAINT has [infamously vanished](https://en.wikipedia.org/wiki/SIGAINT), safe to close.
