### ISSUE TITLE
add Coyim

### ISSUE THREAD

**Issue by tbds** [nylira/prism-break#1511]
CoyIM is a new chat client for the Jabber/XMPP protocol. On the surface, CoyIM looks a lot like other chat clients such as Pidgin, Adium and Gajim. However, under the hood, things are a bit different. The most important guiding principle for CoyIM is to create a program that is safe and secure by default - no settings to change, no plugins to install, no computer configuration to change. We want CoyIM to make it easy to be safe whatever your threat model is - even for the most high risk people on the planet.

The client is written in Go Language and has built in support for Tor, OTR and TLS by default.

Note that the client is under active development. There have been no security audits of the code, and you should currently not use this for anything sensitive.

from the [coy.im](https://coy.im/)

**Comment by alerque** [comment]
Prism-BREAK is a list of software we recommend for _use_ in keeping people out of drag net style surveillance. Your own statement above conflicts with this mission:

> you should currently not use this for anything sensitive

If you don't recommend people use it yet, then it's not time to consider adding a Prism-BREAK recommendation.

**Comment by Zegnat** [comment]
A modern XMPP client would surely be welcomed, but I am with @alerque on this. A bit too young. We also make a habit of listening to developers, so when developers say it is not ready for day-to-day use that's a big no.

Closing.

**Comment by JeremyRand** [comment]
> A modern XMPP client would surely be welcomed, but I am with
> @alerque on this. A bit too young. We also make a habit of
> listening to developers, so when developers say it is not ready
> for day-to-day use that's a big no.
>
> Closing.

It's worth noting that PRISM-Break does recommend some software that
has a similar warning.  For example, Whonix carries the following
warning:

> Whonix is experimental software by means of concept and design. Do
> not rely on it for strong anonymity.

I think it's entirely plausible that the warning in CoyIM is simply
intended to warn people, for ethical and legal reasons, that *nothing*
is completely safe, and not stating that CoyIM is *less safe* than
(insert other XMPP client here).

Might it be worth inquiring with the CoyIM devs about whether they
consider CoyIM to be less safe, safer, or similar safety to the other
XMPP clients recommended by PRISM-Break?

**Comment by hasufell** [comment]
We recommend Tox, which doesn't even have a proper stable release and is used in a few pretty unprofessional ways (e.g. hardcoding tox nodes in the source code of tox clients), so I don't think this should be a show-stopper.

> The client is written in Go Language

How do you ensure memory safety? Static code analysis? What security practices do you apply (coding rules, security architecture, threat modelling via DFD analysis, ...)?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Julian Ospald:
>> The client is written in Go Language
> 
> How do you ensure memory safety? Static code analysis?

Code written in Go is generally much better on memory safety than code
written in C/C++.  PRISM-Break currently recommends several IM
projects that are in C/C++, including Pidgin, which is notorious for
memory safety problems.  So from this particular standpoint, I think
it is likely that CoyIM exceeds the standards of PRISM-Break.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYUyngAAoJELPy0WV4bWVw93YQANZwwy3n9JEcxF85meTb2wji
js1FUN6Jfgbqa9FRfr5Okpl8+dPVKFl1YD6T/Vome+HVNf0YaQYLq/UQaC3D/onU
40ZDRmIixZ6ZfdINoJkl77YnvCz2SQupAcou3qrqZN1RWpWZ0eSsq4xPodrN76mb
9N69BCj4r4Mgz7G7QqwOVevO2CISB1jW/JBmWImyN4wtHuKZz7nU4JIcztR1OySC
CGkR8vX9QF8d1cfYExvBFodzl8/Y1sFdSP5f7dybtiM9dMd3tjd3ZKZjdZobYpKv
XE8x56zLadaTQ/MhG3cdsios3tGij0FoBXkEaWvLssraYAZggu3dxKAeb19DqqaE
nljhw6j06YttOvlXtC256dVnoNoCDidEv7ldPu4bMxUAL7VYN78cWM2TYaxg24aa
YcWxg2SHO07C5n12ifmgEh9xHmEIWC0xcqytxJLciip+WdwKSLFEPlwMnjlVOc2U
DoAR0P1EQXfO/R/GzUd4IWlZILfZ41BnqFQFjP5nTq273H6EDmK8mFrKvr4/TzrM
uiIL6QaRuvr+wDTuQP+G38Ev4PRUO1GFRoUl6dTfDEeO+HSX+EnFi0gKCkpUNh7o
wVug7vd9m8dVfQRZoLJdFd49BZEeIvGQuIPCH/+jmWdbZRzUA63iBnXJ/pb/PwNY
RJQyN1d38a8k202OITWL
=ghov
-----END PGP SIGNATURE-----

**Comment by hasufell** [comment]
> Code written in Go is generally much better on memory safety than code
> written in C/C++

Go is more or less uninteresting in terms of [Language-based security](http://www.cs.cornell.edu/~kozen/papers/lbs.pdf). You can achieve similar memory safety with static analysis and various libraries in C/C++ (and that is actually done in industry). I'm not advocating against inclusion, I was just wondering if you apply actual security methodology beyond that.

> So from this particular standpoint, I think
> it is likely that CoyIM exceeds the standards of PRISM-Break.

Maybe, maybe not. Focus on security is definitely a plus, but so far I don't see how it exceeds regular projects in terms of methodology and technology.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Julian Ospald:
>> Code written in Go is generally much better on memory safety than
>> code written in C/C++
> 
> Go is more or less uninteresting in terms of [Language-based
> security](http://www.cs.cornell.edu/~kozen/papers/lbs.pdf). You can
> achieve similar memory safety with static analysis and various
> libraries in C/C++ (and that is actually done in industry). I'm not
> advocating against inclusion, I was just wondering if you apply
> actual security methodology beyond that.

Hopefully this isn't off-topic, but any chance you could cite the
static analysis techniques and libraries that you say achieve Go-like
memory safety in C/C++?  (I'm partially asking in the context of this
thread, and also asking out of curiosity since I maintain some C/C++
code and am always looking to improve my security / code quality.)

>> So from this particular standpoint, I think it is likely that
>> CoyIM exceeds the standards of PRISM-Break.
> 
> Maybe, maybe not. Focus on security is definitely a plus, but so
> far I don't see how it exceeds regular projects in terms of
> methodology and technology.

Regardless of whether C/C++ code *can* be memory-safe, Pidgin is
notorious for memory safety problems and is still recommended on
PRISM-Break.  So from the standpoint of memory safety, I think it is
uncontroversial to say that CoyIM (or any Go-based codebase) exceeds
the standards of PRISM-Break (unless Pidgin is removed).  That, of
course, does not imply that CoyIM meets all the other PRISM-Break
criteria that are not related to memory safety.

In terms of other ways that CoyIM appears to exceed the standards of
PRISM-Break, its usage of Tor stream isolation out of the box exceeds
that of Pidgin, which requires nontrivial configuration in order to
use Tor stream isolation.  (I would not be surprised if there are
other IM clients recommended by PRISM-Break that don't support Tor
stream isolation at all, but I haven't checked this recently.  Last
time I looked, I believe Tox did not support Tor stream isolation at
all.  I could be mistaken on this.)

(Also, just in case there's any misconception, I have no affiliation
with the CoyIM project, and in fact I have never used CoyIM.  My
evaluation of CoyIM is solely based on their public documentation.)
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYVNfqAAoJELPy0WV4bWVwX8MQAKJYryFVDx7MHzOfnQlFd/Tq
eOoLAXhyqPy+qDbGqMWs/GSBKyrfswMBKOecp6JTDOGrCQRk7r2yFobM52J0OTck
EgwohorVTckLE7oMjU6ucHFw3fq8jFe/6GV3wRlaxy8svmiDLy0DbT6cJ6PuYVAD
QzbDiEqoWMv1aRr/pCEZOfkrXkr3EQskGb477vgHuwucGHVlTdAun/+CqRV/Nyac
3bWN2UNOCALmLztXK9RsEnE2bvcH3UDFjDDwnuPnOfHsaHYO70yNN5eODWRzKfBz
9scL+YdCga4+pZXlpnavlvf3VySNpVH1QvnG4suhKoBMXh0PGje3YG0VXx7UaHB6
iJYfYnvMHMQpe3NOCN3Jw/3F32qVYdvnmuQQ7KMgShZV1rfjPIoVcqwa/G69rjll
78XsI2vZ8PdgKGC0SACGsWT7g/cS9yqkz22dK5nmwV6sPL8QcZLJatFnREomspx1
EAAQEzKGHGaZMsulJefixcQtmEIVde5vkqapve5sQq1oNQB85ch708CPJWNCz4eX
44MdCjMlYzD714BifUQIpoLgQeA/rVuhYlvNqbu1z09vm1wFcvhIj9twPC62HGLX
M7H9Jqu/LGG53/U/S+A1oRK48zaNYSPGiB00vU0CdwQncSxCA7Xb+BuSFUss6p7j
iaqqeUcSmgGvlvpC4BoO
=Uxr9
-----END PGP SIGNATURE-----

**Comment by alerque** [comment]
Allow me to suggest that this discussion is on the verge of derailing. It won't take much to keep it on track but I suggest there is a distinction to be made here between two ways of comparing apps.

This site is a collaborative effort in which an assortment of people throw out ideas, a much more limited set review those to the best of our knowledge, and an even smaller set at some point make a judgment call about whether to include it or not. As such the  quality of these suggestions are bounded be at least two major factors: the knowledge level and number of participants in the discussion, and also the date and current state of privacy technologies and knowledge about surveillance.

Additionally (not relevant to this particular discussion but good to note in general), not all categories are treated equally. Sometimes we recommend what we think the best option is in a category even if, relative to other categories, the quality of that product may be inferior.

So back to two types of comparisons:

1. **Not constructive comparison:** ”You recommend product X which has problems in Y and Z. Therefore those issues must not  be part of your standards. Therefore anything without those particular issues must merit a recommendation.” — It just doesn't work like that. Something being on the list does not _define_ our standards and should not be used as a benchmark for inclusion. The question is not whether some other product with flaws was allowed in but whether users would be better off having a different product recommended to them or not. This sort of comparison tends to devolve into a fight between products. In the example at hand are  we arguing about whether to ditch Pidgin or add CoyIM? While the former may be a valid point, that should be dealt with in it's own discussion thread.

1. **Constructive comparison:** “Product X is the currently available best choice in its category. It exceeds the other candidates in areas Y and Z  that are directly related to privacy and security in relation to mass surveillance and pragmatically doesn't have any major deficiencies that would hinder it being useful.” — Of course we don't like in an idyllic world and it's never this cut and dry, but suggestions for software inclusion should focus on how that product would be the best choice for some use case in the category. In the case at hand, is CoyIM the _best in class_ option for some use case?

And just for the record I'm not bringing this up because I'm a _Pidgin_ fanboy. Personally I think we should drop that recommendation. It's been on the site since 2013 (3baaf87) and there was a time that journalists could use it to good effect with an OTR plugin, but today there are better options, it is just too hard to setup, and frankly I think it's outlived its usefulness. We aren't doing any favors by sending people that direction.

**Comment by hasufell** [comment]
I don't think we derailed in any way, it just got a little bit more technical than usual, since I had the impression that CoyIM applies security methodology, beyond what you usually observe in opensource projects.
That seems not the case so far (at least from what I gather in this thread, I might rather have to ask upstream), but that's not a minus in any way. That was out of curiousity and definitely relevant.

> could cite the
> static analysis techniques and libraries that you say achieve Go-like
> memory safety in C/C++

A lot of them are proprietary static analysis tools (on the lower end there is SonarQube which is opensource, but the C/C++ rule set is not) or model-based code generators that produce safe language subsets, where even the compiler is fully certified. There are also garbage collectors for C/C++ and various libraries that _assist_ in memory safety (which means you still need coding rules that define what to use and what to not use and statically check them).

**Comment by alerque** [comment]
I wasn't objecting to the technical talk about memory safety and static analysis. Knock yourselves out! My only objection was to using Pidgin as if it was a benchmark for what "PRISM-Break's standards" are in any way. It was literally introduced in the initial commit to this repository. And more generally, using any other entries as precedent is probably not a good idea. Comparing a project to the rest of its field so we recommend the best available option is  one thing, but using "it's at least as good as this other (possibly evil) thing you recommend" is not a good argument. That was where this looked in danger of derailing.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Caleb Maclennan:
> I wasn't objecting to the technical talk about memory safety and
> static analysis. Knock yourselves out! My only objection was to
> using Pidgin as if it was a benchmark for what "PRISM-Break's
> standards" are in any way. It was literally introduced in the
> initial commit to this repository. And more generally, using any
> other entries as precedent is probably not a good idea. Comparing a
> project to the rest of its field so we recommend the best available
> option is  one thing, but using "it's at least as good as this
> other (possibly evil) thing you recommend" is not a good argument.
> That was where this looked in danger of derailing.

Hope I didn't give any incorrect impressions about what I (intended
to) say.  I do think that CoyIM is superior to Pidgin in the specific
areas of memory safety and Tor stream isolation, but I do not argue
that those specific differences, on their own, mean that CoyIM should
be on PRISM-Break.  I only intended to argue that on the specific
criteria of memory safety and Tor stream isolation, it is probably
superior to many of the current PRISM-Break recommendations.  It is
very possible that there are other criteria on which it is inferior to
competition; I am not qualified to comment on that (at least not
without doing substantially more research than I have done so far).

The comparison to Pidgin wasn't specifically intended to say that
Pidgin is crap and should be removed.  (I wouldn't mind seeing Pidgin
removed, but that's its own issue.)  I actually use Pidgin
specifically because it can be configured to use Tor stream isolation
safely (although the usability is crap in that department).  I haven't
switched away from Pidgin, despite its memory safety track record,
because the alternatives that I'm aware of (other than CoyIM) do not
support Tor stream isolation at all.  For that reason, I think that if
CoyIM doesn't have any other showstopper issues (of which I am
unsure), then accepting CoyIM to PRISM-Break may make it easier to
remove Pidgin, since Pidgin is currently one of the best options
recommended by PRISM-Break for users who need Tor stream isolation.
And given Pidgin's memory safety track record, I think that making it
easier to remove Pidgin is a reasonable motivation for accepting a
project that doesn't have any other significant showstoppers.  (Maybe
I'm unaware of another PRISM-Break recommendation for instant
messaging that does handle Tor stream isolation properly?  I admit I
haven't carefully studied all of them.)

Hope that clarifies where I'm coming from... apologies if I misled
anyone about what my logic was.

Cheers.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYVci3AAoJELPy0WV4bWVwBPMQAKT4YrdGbZjyefvLY9+J3Bft
8I/XsIe8BI9Rp2gR0ylIK4nzt2hgUl5VnmSY0Ea5CvFfHCxbGG1X3gIExyzaVg8Z
Vf+z4yy6/JQa/2eq8NeBrXfzt8quwkX5nnNJeE3ZTI1JRI8RnqAiK3tIYLlaKyWu
W9cDudpZudN7jcoH/O5lWxERCbyy4ZLALjkCp2qpVjJoIw+J0VK92RhDPRR8Vtxo
wS1CbyEE5fy6b2fcP3jFp08r5vRBgAzvleq2Ns3B/qBUG7uSqPeu3/RaJJzP07e/
0VUh86TiFj1Bd4l/EGzyuBtA9FkGvBf2VRQD81rODRxgwmNCc4u9fN7YgrscM0Bj
t3t7JgB0ixJjqCABh0vY4pEUjacYignyhHOas3WFuap/cMaK427OJp6siFP0Uk1N
XCumimr2ZRElrcM/fmoN1//TmVlD/dcsWzZNjT2Qjqpn+v3HeaPq7UPshXV1kKe2
GMQPR5MwIKQEiAvqf6gcXD7QypegSxdmuXn3xOqqLnarXacjPzmhVd93PN0jqoyx
yfATcAOn9GsqX7lTJX6ibQMvqsqReqfNmUGbsOmD2OzPKiXFfKLxYZ20fMYnhBQ9
TVBlu/tRnaJwUO3Av/cZ1fkYv1MC2tbMzF9mVEjPYs8zY38ZCXn3dNqWHHIgjdfB
9ck1g294Ws6B3J0pqwIk
=VTk3
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Julian Ospald:
>> could cite the static analysis techniques and libraries that you
>> say achieve Go-like memory safety in C/C++
> 
> A lot of them are proprietary static analysis tools (on the lower
> end there is SonarQube which is opensource, but the C/C++ rule set
> is not) or model-based code generators that produce safe language
> subsets, where even the compiler is fully certified. There are also
> garbage collectors for C/C++ and various libraries that _assist_ in
> memory safety (which means you still need coding rules that define
> what to use and what to not use and statically check them).

Ah, interesting.  Proprietary tools aren't particularly useful for me,
but that's good to know that they exist.  Thanks.  :)
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYXScyAAoJELPy0WV4bWVwGm4QALq+QB4zYhFptiuBpM8VksRG
audwsYXeFQnlCMJSmNossWnLZ7orzBjzZQLRqQY9OrhCela9oz1l+MuXcrCipi/i
uajqdcQkQAyQLg//gke0NTXRFimj7fHXAkOQQPA1qIc6qpXKtG9BwHCkVMIjv7Zh
B2kNfL5rkxkjYC5w5u4h4uWqnzALCvCFvUKjvi9p+OkjR/Np7GssRqdthWBLZkjE
E7sRLDR+Mnv6ERCBplM2amFv3GHNcZRObeNIoxXKrYxW9sMFaO9uLPnR9ebCAU5u
svt/+PMiieMb7aZH0fLh5gDzBtt0FDKN3HkeiVVttMm/iVBzcaPuLuDfsOZvH3hO
MvhORsm/yzJQEJpyuypufEAgjQzTir2YBHuPZ/udHnriGUExgakr21yBc65zJpaA
utSQXsBiFBz+czn4bOKMrdkHv1eLBn2ZhC5IA9C0E2pUcd2G0duEvfi60g1cHmuI
oVf+y09g2RJ5siAzSevo4Z/xfChw//UPFbNGHuzqw0ELvVJGfFD248kA+w1yAlII
iBBbqG1xYarwRXYm3nkBDtlrBXdhjWNxlguFvbQUF/12nxiEOAbyFnjlm+UNmmn/
Egl1NJA0W7t8z67ezyP6zEiPu3Qe0yTb2PgCK7lg7jUQ/gnzI1ESIy84OHiMUDXA
VdUJMZpqXf5xoRhd/piq
=NVBd
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Adding another data point: CoyIM supports using a Unix domain socket
to connect to Tor; see
https://coy.im/coyim/update/2016/03/23/release-notes-0.3.html for the
changelog where this was added.

This improves privacy/security by allowing sandboxes such as AppArmor
to prevent CoyIM from making network connections that bypass Tor.  See
https://tor.stackexchange.com/questions/14356/tbb-nightly-hardened-provi
des-no-tcp-socks-proxy-only-unix-domain-socket-is-th
and the linked Tor Trac tickets for more info on this Tor feature.

As far as I can tell from Googling, Gajim doesn't look like it
supports this.  Tor Messenger also doesn't look like it supports this,
unless it has support that was inherited from Tor Browser but not
documented.  I'm not sure about the current XMPP recommendations
besides Gajim.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJY9EIwAAoJELPy0WV4bWVwHvoQANoLiXpKrmpDW/eae/aPIuRO
/EdaU9D5N4PityMkNxSHcU0F4b7k7y5lZQqdJh1IhuBzVIfES4PvTdBYAA/zTjFh
VGcC2+0XByT/3mbsFmT0PRJ7nJb9HYEbot3AUB2E4px8zyat/gSzyqoN4DLY0GCK
fJw3oQldXteizK2JKxfs1ElxngEGW0TvAOtuzKKr+kCVkhtuu6k7LGLdOcLad6/8
gsaHaga/xsLnTFwLdLL11g81RZKc1vh7Q6+3q2V+BlhIXYJa1vJlrOoLDqM+aRQC
P6mIxkCb3l71+mi37U5rf4lb3Zte8PShUAqtIA9iSt3lrXnH5UxSyPD7EnWmDBZy
AbGEYc1l7hpWtQRBaFWd8rxnPD3k19Dm3/nM9rCv45XpfUBA3j8fJTeEZNz3HU+x
HhtsaN4+fDB3nHB4WurAcUyr4+s4xKSQ49u+14a0zbt8jSQNWzzgUtUAhUU90c2c
MktRcnyC4SWPag2ayFH+bItlxv9xK0w8y/yLK63XLPY+F2rlSRElztki8LF4h3XA
cIkolBqT6qj61kdLUVbs6U933nwIgLFxcaOyY3+0TH1nCBk2uPA9LhB/l6Tx9Bjy
1FSmTWjzrq3HTHaq136FMEGvvB6d1FoL9KPnRPI144iXMhmlYqFR+/WJ2RhInpPE
YL2fGXejapIomDZ/oMZF
=Ojho
-----END PGP SIGNATURE-----
