### ISSUE TITLE
Lima - Personal cloud solution

### ISSUE THREAD

**Issue by Maxiride** [nylira/prism-break#1515]
I've recently discovered [Lima](https://meetlima.com/index.php?lang=en) which allows you to plug in any hard disk, plug the lima device in the router and then voilà! The HDD is now online and reachable with the Lima apps.

Could it be worth adding it to the Cloud Services list?

**Comment by alerque** [comment]
As interesting a gizmo as that is, the none of  the client software seems to be open source, which means its pushing data all over your network and potentially the internet without you having any way to verify how it's encrypted or how your privacy is preserved. Even if it turns out they are doing a good job of that in the apps, this is not a candidate for PRISM-Break because it is not open source.

**Comment by merlinnusr** [comment]
Lima need be more open to be trusty.

**Comment by Zegnat** [comment]
Closing for reasons already stated.
