### ISSUE TITLE
VPN Comparison Chart

### ISSUE THREAD

**Issue by TuxedoJacob** [nylira/prism-break#1520]
Hey, I made a VPN Comparison Chart recently (no affiliate BS or anything, sad that I have to specify that). It may come in handy in some shape or form for your project.  Big fan of your project!

https://docs.google.com/spreadsheets/d/1FJTvWT5RHFSYuEoFVpAeQjuQPU4BVzbOigT0xebxTOw/edit?usp=sharing

**Comment by alerque** [comment]
This doesn't really belong in PRISM-Break's issue tracker. As interesting as it might be to some of our users, VPN service provider recommendations are outside the scope of this project and this issue tracker isn't really the place to do promotion. Since this issue isn't about the current PRISM-Break site, nor is there an action point for us to discuss I suggest this issue be closed.

**Comment by Zegnat** [comment]
I don't agree with @alerque. Much like the r/Privacy email list, I would not mind linking to this in the note text for VPN Accounts. That would definitely match PRISM Break's current stance on external resources.

**Comment by ThatOnePrivacyGuy** [comment]
I'm okay with whatever is decided, just giving the team a chance to see it and pass it along if they want.

**Comment by merlinnusr** [comment]
I like this idea . I dont know why only add the RISEUP vpn ,this is not the best VPN of the world WTF Why not add the best VPN in the list (The more private VPN )

**Comment by Zegnat** [comment]
> I don’t know why only add the Riseup VPN, this is not the best VPN of the world <i>[…]</i>
> Why not add the best VPN in the list?

The problem with service providers is that you cannot look behind the scenes. The “logging” column in the spreadsheet is basically hearsay, and it all boils down to trust. “Jurisdiction” is also not as clear-cut as displayed there because many VPN services provide servers in several different countries. So what would you like us to base a decision on?

We decided to put trust in Riseup and A/I because of their long history as supporters of activists and of being protective of all data.

If you want to find a “best VPN” through that list, you are welcome to, but don’t be surprised when we aren’t unanimously going to proclaim a single one the best.

**Comment by ThatOnePrivacyGuy** [comment]
To clarify, I'm not recommending including the entire list of VPNs, but maybe it could serve to help the PRISM-Break team narrow down the field to ones they trust based on the criteria I include (with some additional vetting).  It's just a resource I thought might help.  If you don't think so, that's fine.  I appreciate your efforts and thought I might be able to contribute.

**Comment by annonman** [comment]
I have issue with VPN providers claiming they don't 'log' connections.  People have been burned before by these services.  Ne mechanism exists to put their claims to the test.

**Comment by proxifier** [comment]
> No mechanism exists to put their claims to the test. 

Simple. If the criminal use their service, and never get caught, and the authority post a open news, it's true.

https://torrentfreak.com/vpn-providers-no-logging-claims-tested-in-fbi-case-160312/
https://fried.com/news/fbi-case-proves-pias-no-logs-claim/

> I have issue with VPN providers claiming they don't 'log' connections
Try PIA then. My friend using it and he recommend it to me.
I use Riseup's free VPN, but if you want paid solution(and trust like above 2 link), go to PIA.

**Comment by proxifier** [comment]
just fyi, from personal experience;
bunch of liars

ibVPN
HotspotShield
TorVPN (caution: NOT TOR)
StrongVPN

**Comment by Atavic** [comment]
Most VPN Services are Terrible: https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa

**Comment by yegortimoshenko** [comment]
I would be against linking non-reputable VPN services, and that includes most services. The only services that I think worth considering are those that do not actively promote proprietary clients, do not track users on site, do not log, do not require identification, and gratis or payable in Bitcoin, and have good reputation.

These are criteria met by all currently suggested services. Quite a few VPN providers on this list do not meet any one of these criteria. I only know two VPN providers that make the cut: Mullvad and IPredator. If someone knows some other provider, let me know.
