### ISSUE TITLE
Add One-file memopad

### ISSUE THREAD

**Issue by nirayaki** [nylira/prism-break#1550]
https://github.com/mintmpd/mintmemopad/wiki

All codes are open source, and it's using AES to encrypt/decrypt all data including URL parameters.

**Comment by Zegnat** [comment]
That's possibly some of the least transparent code I have ever seen. I pity whoever wants to go and audit this. I also doubt if this adds anything that [Up1](https://prism-break.org/en/projects/up1/) does not already offer, Up1 also uses [AES encryption for notes](https://github.com/Upload/Up1#how-it-works).

**Comment by fastcopy** [comment]
The good:
+ Easy to manage: only one file and one database file. Nothing more.
+ Portability: I tried it with PHP's built-in web server on my USB drive.
+ Configurations are definded by define(); easy to spot/edit.
+ WTFPL with author's message: "edit what you like!".
+ Nothing to complain(bug) at this moment of my test.

The bad:
- Indent. Comments. However, these can be ignored if you can think this code is "minified".

Conclusion:
If you can read PHP code, this web application is a go.
I'm trying to include one-time key(Google Auth) to login page, in order to use this app for my internal coropration network.

**Comment by fastcopy** [comment]
By the way, the title should be
Add "mint Memopad OSE"

**Comment by strugee** [comment]
I think we should probably close given @Zegnat's comment. I can confirm the code is _really_ hard to read.

**Comment by vyp** [comment]
Agreed.
