### ISSUE TITLE
ownCloud Fork

### ISSUE THREAD

**Issue by Maxqia** [nylira/prism-break#1551]
Nextcloud Forked from ownCloud, can you consider adding something to acknowledge this?

**Comment by Zegnat** [comment]
Does this fork add anything in the security and privacy department?

**Comment by mastercoms** [comment]
If I understand correctly, many ownCloud devs moved to nextCloud because of some org dispute. So I don't think ownCloud will be updated as much, if at all.

Also, nextCloud provides some enterprise features in ownCloud for free.

**Comment by strugee** [comment]
Not sure about privacy, but FWIW NextCloud has promised to disclose all security problems to ownCloud upstream.

IIRC recently this happened and ownCloud had a really slow response compared to NextCloud, but don't quote me on that.

**Comment by alerque** [comment]
As far as PRISM-Break goes, I think following and recommending the Nextcloud fork would be preferable. One of the issues with ownCloud is that they run _both_ an Open Source project and closed source enterprise edition. Some features including some user management options are proprietary. One of the major shifts in the new fork is focusing strictly on the OSS edition and making all features open. Given that a huge chunk of the original developers are behind the fork and the stated goals of the project are even more in line with our objectives than they already were, I suggest PRISM-Break adopts Nextcloud as our primary recommendation and perhaps mentions ownCloud as an alternative implementation.

**Comment by RanceJustice** [comment]
From what I see so far, I too suggest NextCloud ( the name of the new fork) is worth tracking and perhaps replacing OwnCloud itself as a suggested service.  If nothing else, user should be made aware of its existence in a comment until a final judgment can be made. 

Alerque articulated many of the reasons that NextCloud seems preferable all ready, but I should mention that its promising to see that NextCloud has rolled out everything OSS as they promised and are willing to takeover/provide support for all corporate OwnCloud contracts for free, updating/migrating them to NextCloud.   Overall, it seems like a better platform,  developed by the original OwnCloud developers/founders, and will probably progress faster towards better features, including for privacy and security.

**Comment by fortinux** [comment]
NextCloud has 

> the original OwnCloud developers/founders

as @RanceJustice said.

**Comment by Guillaume99** [comment]
Nextcloud also had an open source videochat app (spreed.ME, see https://nextcloud.com/webrtc/) which Owncloud does not have ...

**Comment by rafaelrpinto** [comment]
The new Nextcloud 11 release added more security features that are not available on owncloud:    

https://nextcloud.com/blog/nextcloud-11-sets-new-standard-for-security-and-scalability/

> This release includes Two factor authentication support for Universal 2nd Factor (Yubikey and compatible) and Time-based One-Time Password (Google Authenticator and compatible)
> - Support for Kerberos authentication
> - Password confirmation for sensitive actions
> - HTTPS by default for federation
> - Password reset logic auto-invalidates after changing mail address
> - Improved brute force protection on more endpoints
> - CSP 3.0 protection and Same-site Cookies Support improvements
> - App specific tokens can be forbidden file system access
> - Our Collabora Online integration app has several security hardenings
> - Our new app store automatically checks apps and enforces signatures 

I've been using nextcloud since they launched and never had a problem. +1 for recommending them over owncloud.

**Comment by tcitworld** [comment]
Any news ?

**Comment by alerque** [comment]
@tcitworld I'm not sure what "news" you expect. In seems like the discussion is pretty much settled, but somebody has to actually make the changes. If you'd like to volunteer and write up all the necessary bits to contribute this change that would be great.

**Comment by strugee** [comment]
Marking as accepting PRs primarily because Nextcloud does not suffer from ownCloud's "open core" problem - something we've rejected projects for in the past, IIRC. Also, while Nextcloud doesn't have any groundbreaking security/privacy advantages over ownCloud, it _does_ have a small smattering of meaningful improvements, which is nice.

**Comment by strugee** [comment]
And to be clear, I would take a patch removing ownCloud from the list and replacing it wholesale with Nextcloud. Preferably the notes section would have a brief 1-2 sentence explanation of why Nextcloud is preferred over ownCloud. Something like:

> Nextcloud originated as a fork of ownCloud; it's preferred because ownCloud has an "open core" model and lacks some security features that Nextcloud has.

**Comment by RanceJustice** [comment]
I'd volunteer the time to do so, but to avoid potential rejections, could you please direct me to instructions on how to create a viable PR in this context,  info for doing so to PrismBreak's  standard etc?  For instance, are you looking for simply the blurb and icon so that the primary web developers can add it to the page and publish, or are you looking for someone to code it/add it to the page as well? I've never contributed a PR on Github before and my own experience with version control systems  is years out of practice, so it seems prudent to look before I leap.

**Comment by strugee** [comment]
@RanceJustice ideally contributors would add it to the page. All that's required is editing some JSON - see https://github.com/nylira/prism-break/blob/master/CONTRIBUTING.md, although you can ignore the bit about doing the same for other language files - that's out of date and should be removed.
