### ISSUE TITLE
Attention: Riseup's email is unstable!

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1554]
I am a Riseup user who register a few years ago.
I was using only Riseup mail - until now.

If you are Riseup user, DO NOT CHANGE YOUR USERNAME from "My Settings" section.
YOU WILL BE SCREWED LIKE ME. You can not login your account anymore.
(Take a look at support tickets. Many, many people complain about "can't log in" there.)

Now I have to find other email provider, A/I perhaps.

---

@nylira. PLEASE, for everyone's sake incl. me, DO NOT ADD RISEUP to email section!
This issue starts many months ago. Many tickets are posted, only a few are resolved.

If you are not using RISEUP, I warn you, stay away.

**Comment by fastcopy** [comment]
My tickets are already posted a few days ago. Check it(but don't repost it here please?).

**Comment by amarildojr** [comment]
Can anyone else confirm? Because I'm also a riseup user and never had problems changingg the username. And when I do, I temporarely transfer all me credentials (e.g. Steam) to autistici.

**Comment by Zegnat** [comment]
> Can anyone else confirm?

I can’t confirm. So far I have never had any problems with Riseup.

**Comment by GitHubHatesTor** [comment]
568810
	
31/Dec/2016
	
Can't send email w/ Thunderbird: authentication error
	
tangri@riseup.net
	
active
	
medium
	
mail
	
en
		
2
	
161223
	
31/Dec/2016
	
All Received Mail Auto Forwards to my nonRU account
	
MidwifeMadison@riseup.net
	
new
	
medium
	
mail
	
en
		
1
	
530577
	
31/Dec/2016
	
Host 199.254.238.53 is inaccessible from host 85.143.213.44
	
demfloro@demfloro.ru
	
active
	
medium
	
general
	
en
	
micah
	
5
	
542334
	
31/Dec/2016
	
My mail account was hacked that is relating to my modem/router as well.
	
mynameis_human@riseup.net
	
new
	
medium
	
mail
	
en
		
1
	
225266
	
31/Dec/2016
	
Email list doesn´t receive my email because of "content violation"
	
leska@posteo.de
	
new
	
medium
	
lists
	
en
		
1
	
604941
	
30/Dec/2016
	
I cannot add members to this newly created list
	
freedomnetwork@riseup.net
	
new
	
medium
	
lists
	
en
		
1
	
741088
	
30/Dec/2016
	
Account
	
vladimirthedog@protonmail.com
	
new
	
medium
	
general
	
en
		
1
	
974445
	
30/Dec/2016
	
Wanting to Join
	
cyrus_murray@protonmail.com
	
new
	
medium
	
mail
	
en
		
1
	
111777
	
30/Dec/2016
	
R.I.P Riseup.net - Canary is dead, this service was compromised
	
liberland
	
new
	
medium
	
feedback
	
en
		
1
	
781449
	
29/Dec/2016
	
email
	
laugm2008@hotmail.com
	
active
	
medium
	
mail
	
en
	
guido
	
3
	
389786
	
29/Dec/2016
	
Our list owner is deceased and took her password to the grave with her
	
jayhubbell@comcast.net
	
active
	
medium
	
lists
	
en
	
taggart
	
5
	
731324
	
29/Dec/2016
	
Mail problem
	
daviddouthitt3@gmail.com
	
active
	
medium
	
general
	
en
	
taggart
	
3
	
664899
	
29/Dec/2016
	
All messages are suddenly being returned as "undelivered".
	
adamizer@riseup.net
	
active
	
medium
	
mail
	
en
	
taggart
	
3
	
754477
	
27/Dec/2016
	
I have only a invites codes....
	
mella45@posteo.net
	
new
	
medium
	
mail
	
en
		
1
	
428023
	
27/Dec/2016
	
user name and Setup Account
	
nevadasmith@subliminalqt.com
	
active
	
medium
	
mail
	
en
	
guido
	
3
	
848146
	
26/Dec/2016
	
I really want an email account
	
2skinnytires82@gmail.com
	
new
	
medium
	
general
	
en
		
1
	
882816
	
26/Dec/2016
	
can't post to list
	
janetjordan@fastmail.fm
	
active
	
medium
	
lists
	
en
	
guido
	
3
	
667329
	
26/Dec/2016
	
Emails from masked email service aren't coming through
	
peacechicken@riseup.net
	
active
	
medium
	
mail
	
en
	
guido
	
2
	
922999
	
26/Dec/2016
	
Not able to write a message
	
litovsk@riseup.net
	
active
	
medium
	
mail
	
en
	
guido
	
3
	
729428
	
26/Dec/2016
	
Rejected message
	
fbatzler@gmail.com
	
new
	
medium
	
lists
	
en
		
1
	
648190
	
26/Dec/2016
	
Mail service
	
laura.mora110@gmail.com
	
new
	
medium
	
general
	
en
		
1
	
726126
	
26/Dec/2016
	
Bitmask VPN install ubuntu
	
s13ph3n
	
new
	
medium
	
general
	
en
		
1
	
720423
	
25/Dec/2016
	
Unable to connect to riseup.net black VPN for several days.
	
jaybird
	
new
	
medium
	
VPN
	
en
		
1
	
181611
	
24/Dec/2016
	
Messages posted are being rejected
	
meisenscher@gmail.com
	
active
	
medium
	
lists
	
en
	
guido
	
5
	
974571
	
24/Dec/2016
	
Email account
	
bis465@gmail.com
	
active
	
medium
	
mail
	
en
	
guido
	
2
	
788073
	
23/Dec/2016
	
I DID Have an Account
	
symkha@riseup.net
	
new
	
medium
	
mail
	
en
		
1
	
265674
	
23/Dec/2016
	
Account
	
symkha@gmail.com
	
active
	
medium
	
mail
	
en
	
guido
	
3
	
397079
	
23/Dec/2016
	
multiple lines deleted from list
	
angecrossley@gmail.com
	
active
	
medium
	
lists
	
en
	
taggart
	
3
	
302914
	
23/Dec/2016
	
starting a e-mail account
	
artinfarkt@hotmail.com
	
new
	
medium
	
mail
	
en
		
1
	
506456
	
22/Dec/2016
	
codes
	
rmear2001@yahoo.com
	
active
	
medium
	
general
	
en
	
guido
	
3

**Comment by GitHubHatesTor** [comment]
285009
	
22/Dec/2016
	
Changing a proxy identity into independent address
	
bogoodness@riseup.net
	
active
	
medium
	
mail
	
en
	
guido
	
2
	
175546
	
22/Dec/2016
	
New Email request my name UnicornHunterbo
	
notavailible@yahoo.co.uk
	
active
	
medium
	
mail
	
en
	
guido
	
2
	
105597
	
22/Dec/2016
	
cant access email account ! hellllllllllp !
	
automatickafka
	
active
	
medium
	
mail
	
en
	
guido
	
2
	
989242
	
22/Dec/2016
	
Unable to confirm a Wordpress email
	
angela15@riseup.net
	
active
	
medium
	
mail
	
en
	
guido
	
2
	
364535
	
22/Dec/2016
	
2FA
	
colinklett@riseup.net
	
active
	
medium
	
general
	
en
	
guido
	
2
	
808020
	
19/Dec/2016
	
Quarterly Update
	
ruddy.m.turnstone
	
new
	
medium
	
general
	
en
		
1
	
759274
	
19/Dec/2016
	
Quarterly Update
	
ruddy.m.turnstone
	
new
	
medium
	
general
	
en
		
1
	
663276
	
19/Dec/2016
	
I can't send emails from my iPhone, but I can from a computer.
	
sujsokol
	
active
	
medium
	
mail
	
en
	
taggart
	
7
	
451866
	
17/Dec/2016
	
listserve failure
	
scottmc@riseup.net
	
new
	
medium
	
general
	
en
		
1
	
480840
	
17/Dec/2016
	
Trying to connect riseup with Outlook with secure connection
	
salsadetomate@riseup.net
	
new
	
medium
	
general
	
en
		
1
	
127289
	
16/Dec/2016
	
Cannot access Help Tickets (for a friend)
	
boskote
	
active
	
medium
	
general
	
en
	
taggart
	
3
	
312538
	
16/Dec/2016
	
Pad password protected
	
bastioccy
	
new
	
medium
	
Etherpad
	
en
		
1
	
157301
	
16/Dec/2016
	
Emptied my trash accidentally
	
cooperb@riseup.net
	
new
	
medium
	
mail
	
en
		
1
	
162340
	
16/Dec/2016
	
business
	
karlis.k
	
new
	
medium
	
mail
	
en
		
1
	
695717
	
16/Dec/2016
	
Account Creation
	
carmichael0905@gmail.com
	
new
	
medium
	
general
	
en
		
1
	
359968
	
16/Dec/2016
	
Account Creation
	
j.carmichael@alumni.ubc.ca
	
new
	
medium
	
general
	
en
		
1
	
874625
	
16/Dec/2016
	
forgotten password
	
especifista@riseup.net
	
new
	
medium
	
mail
	
en
		
1
	
131441
	
15/Dec/2016
	
Invitation codes
	
Pascal.hagemeijer3@gmail.com
	
active
	
medium
	
mail
	
en
		
2
	
976638
	
15/Dec/2016
	
List Creation problem
	
andy.mager@gmail.com
	
active
	
medium
	
lists
	
en
		
3
	
890175
	
15/Dec/2016
	
My account has been disabled
	
terastrong@gmail.com
	
active
	
medium
	
mail
	
en
	
taggart
	
4
	
311187
	
15/Dec/2016
	
Want to open an email account but don't know any riseup users
	
pbsinnc@yahoo.com
	
active
	
medium
	
general
	
en
		
2
	
208354
	
15/Dec/2016
	
Creating a new Riseup.net account.
	
williamsc@bell.net
	
new
	
medium
	
general
	
en
		
1
	
601215
	
14/Dec/2016
	
Spam Settings
	
mikewiz50
	
new
	
medium
	
mail
	
en
		
1
	
439718
	
14/Dec/2016
	
Quota problem - not receiving SOMEe-mails?
	
raasnap
	
new
	
medium
	
mail
	
en
		
1
	
557201
	
14/Dec/2016
	
Importing a Google Groups?
	
robert@orzanna.de
	
active
	
medium
	
lists
	
en
	
taggart
	
3
	
680759
	
14/Dec/2016
	
Need two codes
	
meliuchuanli@gmail.com
	
new
	
medium
	
mail
	
en
		
1
	
231327
	
14/Dec/2016
	
Where to start ?
	
efrinumeric@gmail.com
	
new
	
medium
	
mail
	
en
		
1
	
669416
	
14/Dec/2016
	
space and account limits in crabgrass
	
nonunadimeno@gmail.com
	
active
	
medium
	
Crabgrass
	
en
	
azul
	
2
	
692193
	
14/Dec/2016
	
2nd riseup email address?
	
mushbanana
	
active
	
medium
	
mail
	
en
	
taggart
	
5
	
851373
	
13/Dec/2016
	
Erroneous Mailbox full message!1
	
danamaria
	
active
	
medium
	
mail
	
en
	
taggart
	
3

**Comment by GitHubHatesTor** [comment]
As you can see, many people lost access to the account but they never got any help.
More can be posted upon request

**Comment by GitHubHatesTor** [comment]
For more information, log in to https://user.riseup.net/ and see tickets

**Comment by GitHubHatesTor** [comment]
At least these people have a problem;

1976pianoman@gmail.com
22cyberecho51@riseup.net
2skinnytires82@gmail.com
4cc0un75@riseup.net
a-teammedics@riseup.net
aaronmtl@riseup.net
abelgp@riseup.net
adamizer@riseup.net
afa-jonkoping@riseup.net
agonzalez@riseup.net
ailsa@mail.com
ajnelson@riseup.net
alex.gerzabek@gmx.at
alex.prichard@riseup.net
alex@bifso.org
alexandre.humbert@riseup.net
ana_higueras@hotmail.com
andrewtjeffers@gmail.com
andy.mager@gmail.com
angecrossley@gmail.com
angela15@riseup.net
anna.dupleix@riseup.net
arievanleyen@gmail.com
arnorosenfeld@gmail.com
artinfarkt@hotmail.com
arunisaac@systemreboot.net
barsamian@riseup.net
bastaberlin@riseup.net
bean@riseup.net
Beni@riseup.net
benjamin.desurmont36@gmail.com
bennettpatriciajean@gmail.com
bernice.gray@sa.gov.au
bettertogether@riseup.net
bevin.protas@gmail.com
Bianchi@riseup.net
bigtreesmail@riseup.net
bis465@gmail.com
blackandpinkseattle@gmail.com
blacklodgebob@protonmail.com
bmpana@live.com
bogoodness@riseup.net
bombo@riseup.net
boratx990@hotmail.com
borddeleau@riseup.net
borjay@umich.edu
bowen.song@protonmail.com
bowman.benjamin@gmail.com
bparsons12@gmail.com
brett.jayms@gmail.com
Brianwoodgate@yahoo.com
brt@brucetaub.net
burlingtonantifacistleague@gmail.com
bwebster@riseup.net
calico1184@gmail.com
cannon.mike.r@gmail.com
caraxa@gmx.com
carl@supervacuo.com
carmichael0905@gmail.com
Catalyst8@riseup.net
cbrosig@posteo.de
celestialintelligences@riseup.net
cfen2013@uni.sydney.edu.au
charactr@frontiernet.net
christadaring@gmail.com
citizynware@riseup.net
cl.mader@laposte.net
claire@caat.org.uk
cntleon@gmail.com
colinklett@riseup.net
CongresodelosPueblos-Londres@hotmail.com
cooperb@riseup.net
coperthought@riseup.net
creacionesanairda@yahoo.com
createwilderness@riseup.net
crisbh@riseup.net
cschaffer.cs@gmail.com
cvar@peak.org
cyrus_murray@protonmail.com
d6moff@yahoo.co.uk
damien.courousse@riseup.net
dannywmitchell2@hotmail.com
dave.kimble@riseup.net
daviddouthitt3@gmail.com
DavidvGoliath@gmail.com
dazer@riseup.net
deeppoitics@riseup.net
demetriuslp@gmail.com
demfloro@demfloro.ru
der-kater@riseup.net
derekt@riseup.net
dielind@gmx.de
dinero1976@riseup.net
Dinero1976@riseup.net
diogenesquest@gmail.com
doctordac@yahoo.com
dominic.bellone@gmail.com
dropboxintel@gmail.com
dwright@riseup.net
eazytech@riseup.net
edcyano@riseup.net
efrinumeric@gmail.com
eml013947@riseup.net
especifista@riseup.net
evolution@riseup.net
fbatzler@gmail.com
fbp@igc.org
femgeobonn@riseup.net
filhadovento@riseup.net
fossilfreeberlin@riseup.net
fraetyr@gmx.de
fredegus@algonet.se
freedomnetwork@riseup.net
freelab@riseup.net
frouel@riseup.net
gabriel@erlikon.ch
gardencat721@yahoo.com
gautham.gg@protonmail.com
gitta-smile@gmx.de
gratienne@riseup.net
gretchen@riseup.net
guido@zajonz.de
Handala@riseup.net
hannes_winter@ymail.com
heaphyd28@riseup.net
holditgade@riseup.net
humanmosssalmonid@gmail.com
hypnoxic@riseup.net
info@jayonline.co.uk
intell@riseup.net
irenearts@riseup.net
Iron5@gmx.de
ivonney@accionecologica.org
j.carmichael@alumni.ubc.ca
jacjawayne@yahoo.fr
janetjordan@fastmail.fm
jasonmoomjy@gmail.com
jayhubbell@comcast.net
jazz42@riseup.net
jbrett@shaw.ca
jg73@free.fr
jglez@riseup.net
jimkennedy@riseup.net
JohnBrisler@riseup.net
johnsheridan1944@gmail.com
jokkmok@mail.ru
jorgejesus@aeaag.pt
jourdain.martin@gmail.com
jvandevere@comcast.net
k1.mohtadi@gmail.com
kariit@riseup.net
kentveganfestival@riseup.net
klarname@riseup.net
l.bender222@hotmail.com
labruixe@riseup.net
lance.mccold@gmail.com
laugm2008@hotmail.com
laura.mora110@gmail.com
leska@posteo.de
lifeonmars@riseup.net
linden.miller@gmail.com
litovsk@riseup.net
lkanthony@comcast.net
lo.schlumpf@gmx.ch
localbuyer37@riseup.net
louisaradice@riseup.net
lovelessleapord@tutanota.com
ltg4263@gmail.com
luca.andreolli@msn.com
m.hannoschoeck@posteo.de
makingmuffins@riseup.net
mallen1@nycap.rr.com
manfred.tidow@mailbox.org
markbihan@gmx.fr
marlene@riseup.net
martinezlibrary@gmail.com
martinique@riseup.net
martyrose57@riseup.net
marxdulesen@riseup.net
matthewpclancy@gmail.com
maxpower@riseup.net
mblavende@gmail.com
meisenscher@gmail.com
meliuchuanli@gmail.com
mella45@posteo.net
MidwifeMadison@riseup.net
mike.middleton@valley1031.org
mikeywinggames@protonmail.com
mimi.lukas@gmail.com
minky@riseup.net
minorcalyxa@gmail.com
miriam.pjater@gmx.de
montereypinegreen@gmail.com
mt@riseup.net
mynameis_human@riseup.net
n9iu7pk@posteo.net
nevadasmith@subliminalqt.com
nimeni@riseup.net
nizetta@riseup.net
noblebaker@gmail.com
none@none.com
NoNeed@Lols.com
nonunadimeno@gmail.com
notavailible@yahoo.co.uk
nouvellesarmes@riseup.net
nouvelr@riseup.net
obiomah@tutanota.com
oceankayak@aol.com
olmopero@hotmail.it
optiontrader@riseup.net
orschiro@gmail.com
ouesttrans@gmail.com
Pascal.hagemeijer3@gmail.com
pascal.hagemeijer3@gmail.com
paul@ohrie.de
paulinabholistic@gmail.com
pbsinnc@yahoo.com
pdoria@verizon.net
peace5942@gmail.com
peacechicken@riseup.net
peter@sustainlv.org
petervankoughnett@gmail.com
petetridish@riseup.net
petroberto@gmail.com
pfgoroc@riseup.net
photoenthusiast518@gmail.com
picard.isabelle@hotmail.com
pikatcharos@riseup.net
pilgi@riseup.net
plus@place.com
pmnews@kboo.org
ptawdirector@zoho.com
q.trepe@icloud.com
quiliro@riseup.net
rabiaxrisa@riseup.net
rastalibabaa@gmail.com
ratzeburger@riseup.net
rebelrocker@riseup.net
reetika@riseup.net
reshzen@anche.no
rfovetz@riseup.net
ricj@ricj.org
riseup@jediron.com
riseup@pokemail.net
riseuphelp@maildrop.cc
rmear2001@yahoo.com
rms@gnu.org
robert.maerz@hotmail.com
robert@orzanna.de
rock_dove@riseup.net
rogue@riseup.net
rrose@pobox.com
rsmith338@riseup.net
rushtoqueue@riseup.net
salsadetomate@riseup.net
samba-resistance-jena@riseup.net
samuel.martinsa@gmail.com
sanctioner@riseup.net
sapo.pt@riseup.net
saskiaf@riseup.net
savitprabhu@riseup.net
saz@riseup.net
scarleton@riseup.net
scottmc@riseup.net
sdact500@gmail.com
semartin@riseup.net
shannoncunningham@riseup.net
shanti.manzano@gmail.com
shlurek@riseup.net
sia2016@riseup.net
sibiuaner@riseup.net
siouxzy@riseup.net
skya@espiv.net
stefan.sohst@gmail.com
subfires@riseup.net
sukuwc@riseup.net
sunnryze@riseup.net
superrippel@gmail.com
symkha@gmail.com
symkha@riseup.net
tangri@riseup.net
tapirinsurrection@riseup.net
taylor.colleen.0313@gmail.com
teammaren@riseup.net
temohl@riseup.net
terastrong@gmail.com
theano2@aol.com
Thersitesderboese@riseup.net
thgalaxys4@gmail.com
thorz.kruse@gmail.com
thruhiker2002@riseup.net
tico@raapid.net
timofeypnin5@gmail.com
tokktokk@riseup.net
tomroucoux@riseup.net
toxicm1st@sigaint.org
traceless@keemail.me
trekkiejonny@gmail.com
trivelin@free.fr
tsiros@riseup.net
tugba.tue@googlemail.com
tuttavista@zeromail.org
umpteenth@riseup.net
undwartenwir@hmamail.com
upprorsbladet@riseup.net
uwe.drieschner@riseup.net
vegnature-al@lists.riseup.net
vladimirthedog@protonmail.com
vogelnest@riseup.net
webmaster@valreep.org
wilblake@protonmail.com
wildheartlaughing@gmail.com
williamsc@bell.net
wsypost@posteo.net
xicanavegan@hotmail.com
xpro@riseup.net
ying-sun@leftroots.net
yk@freedomtrainers.org
z3rg1i@gmail.com
zboo@riseup.net
zopeck@riseup.net

**Comment by alerque** [comment]
@ghost That copy/paste formatting with one work per line and most of the words being irrelevant to this issue is profoundly un-useful and just makes it hard to find if there is any real discussion in here. Please edit that down to something we can actually use to  figure out if there is something we should be doing.

Also dropping a long list of personal email addresses that aren't yours is decidedly **anti privacy** which defeats the goals of this project. If those people want to put their addresses somewhere that's their right, but you should leave them where you found them. Please delete that post or edit it bock to just say N users have registered complaints.

**Comment by strugee** [comment]
I've just removed the long comments that @alerque mentioned, as they were bordering on doxxing (not to mention supremely unhelpful).

Let me be perfectly be clear: **this behavior is a violation of PRISM Break's [Code of Conduct][1] and is unacceptable in this issue tracker**. Anyone who continues to violate PRISM Break's Code of Conduct will be **reported to GitHub Support and I will lock this issue**. Obviously that makes it a PITA for everyone else who has legitimate contributions to make, so I'd rather not do that. But I'll do so (and figure out a way for everyone else to say stuff), if necessary.

 [1]: https://github.com/nylira/prism-break/blob/0f724d4f59688392b3c0f360761475afc7848025/CONTRIBUTING.md#code-of-conduct

**Comment by yegortimoshenko** [comment]
I can't confirm this.

**Comment by yegortimoshenko** [comment]
Not reproducible anymore.
