### ISSUE TITLE
poor score on observatory.mozilla.org

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#1570]
https://observatory.mozilla.org/analyze.html?host=prism-break.org

Also note the various 3rd party reports on that site, linking them here for convenience (omitting ssllabs, since the score is A+ already):
- https://tls.imirhil.fr/https/prism-break.org
- https://securityheaders.io/?followRedirects=on&hide=on&q=prism-break.org
- https://hstspreload.appspot.com/?domain=prism-break.org

The security headers need improvement and the DES cipher suite should be removed.

**Comment by Kewjoe** [comment]
I'm surprised there hasn't been more discussion about this. For a site that values security and privacy, it's a bit funny that the site itself is not set up in that manner.

**Comment by alerque** [comment]
@Kewjoe Largely because the issues listed are unimportant. The fact that SSL-labs gives it an A+ should tell you something.

* The only issue in the first report is that the non-canonical www subdomain wasn't secured the same way. See #1626.
* The key-pinning might be something to consider, but it also has drawbacks. It isn't a clear win. That site showing a red-X doesn't really tell the whole story. The other issues about headers listed are mostly irrelevant because PRISM-Break's entire site is static content. If we had login forms or other things that had to be secured against eavesdropping on input that might be a different story, but we don't have any of those kind of features (on purpose) so those are false-alarms.
* DES cipher already removed.

The headers things could be fixes, and we probably should, but the main thing that will do is net us a green check mark.

**Comment by Kewjoe** [comment]
@alerque Ah, i didn't recheck the scores. I had assumed that since no one responded that nothing had changed. Fair enough. Maybe this issue should be closed then?

**Comment by alerque** [comment]
No, it should be left open until all the issues are either dealt with or we explicitly agree to eschew them.

**Comment by hasufell** [comment]
> If we had login forms or other things that had to be secured against eavesdropping on input that might be a different story, but we don't have any of those kind of features (on purpose) so those are false-alarms.

That point applies to SSL as well.

And yes, I don't consider any of those points relevant for privacy, not even SSL. They know you visit prism-break anyway, they just don't know what you specifically looked at (and they don't care).

This is rather an image thing.
