### ISSUE TITLE
Dolphin Browser? 

### ISSUE THREAD

**Issue by rrkk** [nylira/prism-break#1578]
I just found this site, so I apologize beforehand if I'm doing this wrong. But seeing as I just found the site, I didn't know if the Dolphin Browser had been mentioned at all. 

What's your take on it? Do you think it's a safe browser to use? 

If it's not, what would a good alternative for Firefox be just so I have options to choose from? I am still looking into Tor, but as a newb, it's a bit overwhelming.

**Comment by jinformatique** [comment]
Hi, could you give us a link to check it out? Is it an app only or also for desktop?

First of all to recommend a software here on prism-break, you should look if the software is free and open source and respect the 4 freedom.

Freedom 0: The freedom to run the program for any purpose.
Freedom 1: The freedom to study how the program works, and change it to make it do what you wish.
Freedom 2: The freedom to redistribute and make copies so you can help your neighbor.
Freedom 3: The freedom to improve the program, and release your improvements (and modified versions in general) to the public, so that the whole community benefits.
https://en.wikipedia.org/wiki/Free_software

To help you, you can look on the website if there is a way to get the source code from dolphin browser. If not, then it's not possible to recommend it here.

**Comment by Zegnat** [comment]
The Dolphin Browser (just for mobile, @jinformatique) isn’t open source, so there is no way for anyone to say if it is “a safe browser to use”. That is also why it will not be included on PRISM Break.

There are very few open-source browsers for mobile apart from Firefox. Several browsing applications for Android will use the operating system’s own WebKit view, which may or may not be open-source depending on what Android ROM you are using. Chromium would be an open-source alternative, but last I checked you would need to compile it yourself. And even then you are left with a few issues where Chromium could be phoning home to Google.

Sorry to have to disappoint you with  lack of options, but so far we just haven’t found any.
