### ISSUE TITLE
Is private tunnel safe? And Is signal - p.m. safe?

### ISSUE THREAD

**Issue by kekelemek** [nylira/prism-break#1591]
Is private tunnel safe?

**Comment by kekelemek** [comment]
And is private tunnel open source? İs signal private messenger safe? Please answer me.

**Comment by strugee** [comment]
"Private tunnel" is pretty generic - please state exactly what you're talking about.

Re: Signal, please search for duplicates (and in the future, only mention one piece of software per issue so we can track things more easily - thanks!)

**Comment by kekelemek** [comment]
This: https://www.privatetunnel.com/home/?referral=OPENVPN   (openvpn service)

**Comment by strugee** [comment]
Offhand, I couldn't find any explanation of their data retention policies, etc. (although I didn't read the privacy policy, which it might be in). So that's somewhat concerning. However, it's run by the same people who develop OpenVPN, so I'd tend to trust it at least somewhat because of that.

Please note, though, that the above is only after ~5 minutes of research and shouldn't be treated as advice. Someone would have to actually spend some time looking into Private Tunnel to make a proper recommendation (and I don't have that time).

**Comment by kekelemek** [comment]
Secure VPN can you suggest a program/programs?

**Comment by strugee** [comment]
@kekelemek https://prism-break.org/en/all/#vpn-servers
