### ISSUE TITLE
Recommend Replicant 6.0 beta

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1600]
**Edit 2017-01-08**: if you're here to send a PR, see https://github.com/nylira/prism-break/issues/1600#issuecomment-271122798

---

I think we should look into removing Replicant. (Note that I said look into - I haven't done all the research to know if this is a smart idea!)

I'd seriously question Replicant's ability to respond appropriately to security issues. They're several versions of Android behind and it's unclear if the work to upgrade it is even going anywhere since the last announcement about it was quite a while ago: https://blog.replicant.us/2016/08/replicant-6-early-work-upstream-work-and-f-droid-issue/ (note also the TLS problems with that link)

Generally it seems critically understaffed to me. Note that we've disqualified projects for similar reasons in the past, e.g. Icecat (#1310) and Trisquel (#536, though its Ubuntu base was was also a factor mentioned in other issues)

Again, not necessarily saying we _have_ to do this. But we should at least look into it.

**Comment by Zegnat** [comment]
> note also the TLS problems with that link

You probably don't accept cacert.org's root certificate on your machine then. That seems to be the issue on my work PC, at least.

I do agree that it looks like Replicant is stuck on 4.2 with very little roadmap to 6+ at the moment. Does anyone know if they have actively backported security fixes to their 4.2?

**Comment by hasufell** [comment]
We'd basically remove the only useful alternative to proprietary mobile device OSes. Then you could as well remove the whole category.

**Comment by vyp** [comment]
There's CopperheadOS from #1524. But it only currently supports 3 nexus devices.

**Comment by hasufell** [comment]
> There's CopperheadOS

which probably has even less developers than Replicant, or does it?

**Comment by strugee** [comment]
@Zegnat on my tablet with Firefox Nightly I get SEC_ERROR_CERT_SIGNATURE_ALGORITHM_DISABLED. Re: security fixes, I don't know. We should investigate.

@hasufell I hear you, but at the same time we can't reasonably recommend known-vulnerable software (if that's what Replicant turns out to be). As for CopperheadOS, I think it's only one guy but he does it full-time as part of a security company. Seems pretty dedicated, see for example https://www.reddit.com/r/Android/comments/52422a/copperheados_pushing_nougat_update_to_nexus_6p/d7hd45k/

**Comment by hasufell** [comment]
> we can't reasonably recommend known-vulnerable software (if that's what Replicant turns out to be)

give some proper reference to that then, instead of guessing

> As for CopperheadOS, I think it's only one guy but he does it full-time as part of a security company

IMO, that's a no-go. It practically means there is no community around it whatsoever and no peer-review or anything remotely like that.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> They're several versions of Android behind and it's unclear if the 
> work to upgrade it is even going anywhere since the last 
> announcement about it was quite a while ago

I was curious, so I quickly glanced at the Git repos of Wolfgang
Wiedmeyer (the lead developer of Replicant 6.0) to see if there were
recent commits.  I did indeed find several relevant repos that appear
to have recent development:

https://code.fossencdi.org/device_samsung_i9300.git/?h=replicant-6.0-mai
nline

https://code.fossencdi.org/device_samsung_smdk4412-common.git/?h=replica
nt-6.0-mainline

https://code.fossencdi.org/kernel_i9300_mainline.git/

Wolfgang's most recent publicly-pushed commits in those repos are from
October 26.

This was an informal and quick evaluation, but it does at least appear
that development is occurring.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYKIeQAAoJELPy0WV4bWVwZ9UP/2jWzUgOaOLGIrws7I5Eeu9n
x0aOA4oIjT/tw3IFc9Pwv308MBAjx366MSAVFJrg2ceprhc0t5PWQhbwmrzO6jL8
P1FCCIcRKsOQ+6ip5KZSSYO3I/tMeI1yYKWbGPo8jXLnP2/vJ3hKHDAwuaQqNMHI
HoafDhbr86APk1mN0j2M/HVV/7Qli50PIK0Msu/w0FYKV3MgJy/HM16y4lUb0pem
q6HqZpGke2yza+g/RheBQ6iQE8CB42dhjAWTL5/1KUCZk3WDhR52YXEF+mgnSGP7
bP/oAH5+hhkCR7x5/twGaH3t9R5LjsTcSE+rJKrT88Vr94ce9q//g4RxFcL4V1Py
5lWEcfJVgjcqSvAGczRsQjeTkF62F+XIYWbLcS9X4sgzqoI/qSE60NumQzBZLvpD
zGr5CTNCWiChb1m3BcXs8yXcPiNpMdD/mph71zjCXsUhCiWHBp3pobF1STKKJTF6
6LebUK5xYvhd4XZW2altalQZhW730QuI0N7kaBXunM6HYAqQrcH4bH5iLmPDGir3
WLmpxFtHW4cxQXXE2aCa3A8camnMsWkmDASgtzCsGF45hm7iS/GQQA7WivgO89No
Uj0hPmHUujVGAniukDRroC9d7Np3MVHfgCmRbZrHaQkoLycYFCVz/qvY7hqNoICT
0LVEqVKKmh4xx+FBPNpx
=K1vR
-----END PGP SIGNATURE-----

**Comment by WadeLovell** [comment]
Great. Then let's leave them on the list for now and also give Wolfgang Wiedmeyer the opportunity to reply if we decide to reopen the subject in the future.

**Comment by strugee** [comment]
@JeremyRand that's good to hear, though I'm still concerned with the fact that there hasn't been a release yet. However that does look good on the security front. I still need to find time to look into Replicant's track record... I seem to recall them not having a great response time, but I can't remember where that's from and I certainly could be wrong.

@hasufell let's move this discussion to the issue for Copperhead inclusion.

**Comment by strugee** [comment]
Update: in [this Twitter thread][1] the CopperheadOS guy points out that even if Replicant backports security patches, that doesn't change the fact that the overall security architecture of Android has vastly improved since the KitKat days. Notable changes since 4.4 ([source][2]) include SELinux in enforcing mode for all domains and runtime permissions, along with (presumably) lots and lots of small improvements.

It also doesn't change the fact that Replicant doesn't have the manpower to audit the code themselves, so they rely on Google to find and disclose security issues. The more changes made to Android that Replicant isn't able to keep up with, the more code they're maintaining that isn't scrutinized by Google anymore. (Or to put it another way, a lot of the code in Replicant has been changed, so Google won't necessarily care about/be looking for vulnerabilities in the now-obsolete code that Replicant ships.)

 [1]: https://twitter.com/CopperheadOS/status/800508156631654400
 [2]: https://en.wikipedia.org/wiki/Android_version_history#Android_4.4_KitKat_.28API_level_19.29

**Comment by strugee** [comment]
> The best solution would probably be to remove all mobile OS suggestions, tell people that all free alternatives suck and that mobile phones are extremely privacy-breaking, no matter how hard you try (and I don't even mean NSA-grade surveillance, anyone can track random ppl via mobile with relatively low effort).

I agree with you in principal, but in practice I think this is too extreme. PRISM Break is designed to appeal to a mass audience and the reality is that no one's going to give up their smartphone. So while you're completely correct, I still think the best course of action is to recommend alternatives.

I still think CopperheadOS is a great candidate for inclusion, barring the licensing problems. In the web search engine section we have licensing exceptions because the alternatives list would suck too much if we stuck to our principals - maybe we should do the same for mobile OS's and include Copperhead.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> @JeremyRand that's good to hear, though I'm still concerned with
> the fact that there hasn't been a release yet. However that does
> look good on the security front. I still need to find time to look
> into Replicant's track record... I seem to recall them not having a
> great response time, but I can't remember where that's from and I
> certainly could be wrong.

By far the vast majority of the work on Replicant appears to be on the
6.0 branch.  On the downside, that means that (as far as I'm aware)
not much is being backported to the old 4.2 branch.  On the upside,
I've been running the latest released 6.0 beta binary from Wolfgang,
which has much better security associated with the newer upstream
Android (including SELinux enforcement), for about 1.5 weeks, and I've
encountered no significant issues.

I had exactly 1 OS crash in the past 1.5 weeks (which I suspect was
due to an app triggering a rare bug in the software graphics
renderer), and a couple of UI nits (e.g. occasionally the graphics on
the software keyboard would fail to refresh properly in one specific
app while the app was using lots of CPU).  Other than those minor
issues (which frankly are par for the course with lots of the software
on PRISM-Break), 6.0's most recent released beta is totally usable for
me; I have had zero temptation to use 4.2.  (Judging by the comments
on the Replicant forum thread, it appears that I'm not an outlier on
that.)

My impression from reading the forum (though I could be totally
mistaken) is that one of the reasons Replicant 6.0 isn't considered
stable yet is because they're not happy with the number of blobs in
the upstream build toolchain and dependencies that are difficult to
build from source.  I'd be surprised if Copperhead isn't worse on that
front.  (Is dealing with that even a priority for Copperhead?)

Given that the 6.0 beta is probably more secure than the 4.2 stable,
perhaps PRISM-Break might consider continuing to recommend Replicant
as an option, but adding a note that the 6.0 beta is recommended
rather than the 4.2 stable (with a link to the forum thread that has
Wolfgang's binaries)?

(Wolfgang would, of course, be far better placed to comment on the
above than I am.)
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYMm8mAAoJELPy0WV4bWVwYEAP+wYhQKPBwRf0Pr1NZaJoNsyy
omW367jnRdNqGVAIfCvClqdVtNikGmCowcB/w9dEFvTv3ouCaVTRuTFqK2wX9Ngl
yEiL06OLQtRoOhLUTONZxpMjsvtntQsoP/AGtl0CzidvowW8AjeIZk4UVpxa8t3f
382qubKMg7TlaWk+bvN5ljZZDgkpM01FR1Mj25I8+bnslLjnOLz5v/00n/bl4O0y
wCyvVEHASBac3a12l/taV3cxHnS7XVl2knzKzsd0AnihwRWiGdWZDN+L9Mx2e1bo
/MnOvu72lR/gOWd9XIaKhvzIixwPQfo1F2TArOa8Gi79eRUwJFNAcwl7DMC0d5kh
JtUcMBT9Jyzmm+PVqsUkC+cfRzNqaz9Ug+/KzuxePnoPqSajN4+irWTIuNlYsSHJ
/rcw/4iOVwFsQ7xwMg4lVRl8eAuIK52mx8aGlLxFvjrI4Rdpk6xRlohM4kJTbCan
nh94+zoS4cqau9Q5A+GtisZCF7bLhDUs93+EIct1d8dEPJOpiHnGqvgQuReJQir6
nVw2XY7ygFmyl51BhM6nR9WZuVX9P1XVD2TjSbcrtCrElMYAWLV6gdru79aHLann
x9t7RQrXvTElas0vuKEFQg7gg6EZkrmIIb1cjf9teyTCiaeFJVDq9JN4+pEHFoOQ
4+/jJLjqGnhGCl4R3IwI
=J+8e
-----END PGP SIGNATURE-----

**Comment by fedor1113** [comment]
Hello!
I also think that it would be wrong to discard Replicant - as it is indeed the most libre mobile OS out there - removing it completely would mean leaving users without any libre OS (Cyanogenmod and Copperhead are full of binary blobs). Of course, I think that it would

**Comment by fedor1113** [comment]
Oops, sorry - accidentally pressed the comment button. In my opinion, it would be reasonable to add some kind of notice stating that the OS is not based on the latest Android version and that it would be reasonable to try their beta - as the current stable release might be prone to bugs etc.

**Comment by strugee** [comment]
I'd feel _much_ more comfortable if we recommend the 6.0 beta.

**Comment by mimi89999** [comment]
@strugee @Zegnat It looks like not all Linux kernel and Android security patches were backported to Replicant 4.2, so that version would be vulnerable to several known vulnerabilities. Also interesting: http://redmine.replicant.us/projects/replicant/boards/39

I really love the idea of a fully free Android ROM and I fully support Replicant, but in that case I think, that it is not a good idea to recommend it.

**Comment by strugee** [comment]
@mimi89999 where did you hear about the patches that didn't get backported? That's useful information that makes the case for recommending the beta even stronger.

Speaking of which - any objections to recommending the 6.0 beta instead of 4.2 stable?

**Comment by hasufell** [comment]
just a sidenote: the linux kernel team doesn't make a whole lot of difference between bug fix and security fix (and don't advertise them as security fix, even if they know they are)

Quote from Greg KH

> Can you judge which bug fixes are security ones, and which are not?  And
> do so for 100+ patches a week?  52 weeks a year?  Great, please do so,
> as no one has ever been able to do this (others have tried.)

> Hint, the line between a bugfix and a security fix is not always
> obvious, or even known at all.

This effectively means that you want to roll with the latest release always, because that imposes the maximum amount of research for a potential attacker. And it also means that "backporting security kernel fixes" is a rather fuzzy thing to say.

**Comment by mimi89999** [comment]
@strugee 
http://ftp.osuosl.org/pub/replicant/images/replicant-4.2/0004/metadata/date.txt
2015-09-01 -- Release date of Replicant-4.2/0004, latest stable version of Replicant

https://redmine.replicant.us/boards/21/topics/12057
replicant-6.0 build date: 25.3.16

https://source.android.com/security/bulletin/index.html
Several critical and high severity vulnerabilities were discovered in Android and the kernel. All versions of Replicant would be vulnerable...

**Comment by strugee** [comment]
Marking as accepting PRs because we all seem too agree that recommending the 6.0 beta is at least better than the current 4.2 stable.

Given the information pointed out by @mimi89999 (which I haven't looked at yet) we should probably revisit removing Replicant entirely, however that doesn't mean we shouldn't make a meaningful step in the right direction since we've already all agreed on it.

**Comment by mimi89999** [comment]
@strugee 
Do we really want to recommend a ROM, that is vulnerable to several known critical vulnerabilities like CVE-2017-0381 and that is only available for one device, that stopped being sold some time ago... (Only Tehnoetic is selling new rebranded S3 AFAIK...)

**Comment by mimi89999** [comment]
I suggest recommending OMNI instead of Replicant or removing the category at least until Lineage OS starts shipping official builds.

**Comment by hasufell** [comment]
> Lineage OS

So, do we know if they don't ship proprietary drivers and firmwares?

**Comment by alerque** [comment]
@hasufell I doubt it will be firmware blob free, but then nothing on Android is. Unless we want to push 100% open hardware we might have to draw the line somewhere. And that would apply to _any_ of the Android ROMs. Some have gratuitous amounts, others have  bare minimum required to make various hardware go.

In any case if there is anything specific about Lineage to be said lets do it on #1662. This is the Replicant beta vs. old release vs. not at all issue. The not at all might apply to both, but Lineage should be discussed on its own merits and preferably under one issue ;-)

**Comment by mimi89999** [comment]
@hasufell I am sure, they will (without them the device won't be usable), but some GNU/Linux distros, that prism-break is recommending also have non-free blobs.

**Comment by hasufell** [comment]
> I am sure, they will

I think that is wrong. That's why replicant doesn't support a lot of devices and those devices they support have limited functionality.

also see http://redmine.replicant.us/boards/33/topics/1041

> 2. That's what we do: we write free software replacements for the proprietary parts that CyanogenMod ships with. When we don't succeed, the corresponding hardware feature doesn't work with Replicant (for instance, there is no free software for the GPS chips in the phones we support, so there is no GPS support with Replicant so far). Note that Replicant is not about open source but rather about free software.

**Comment by mimi89999** [comment]
@hasufell 
Replying to:

>>Lineage OS

>So, do we know if they don't ship proprietary drivers and firmwares?

**Comment by hasufell** [comment]
Ah ok, so that makes it unrecommendable to me. And I also don't see where broad generalizations like "nothing on Android is <blob-free>", which appear wrong to me, get us.



> Unless we want to push 100% open hardware we might have to draw the line somewhere.

That was discusses before. Open hardware is not in the scope of prism-break, free software is. The line we have to draw is pretty simple. The line is exactly there: __free software__. And that __especially_ includes drivers and firmware, because they control your damn device.

**Comment by mimi89999** [comment]
@hasufell 
> The line is exactly there: free software. And that _especially includes drivers and firmware, because they control your damn device.

Then remove Arch Linux, OpenSUSE, etc.

**Comment by hasufell** [comment]
> Then remove Arch Linux, OpenSUSE, etc.

I'm not sure you listened:

> You are referring to the kernel, which can be deblobbed on all linux distros

**Comment by mimi89999** [comment]
They can be deblobed, but it is not how the kernels are installed by default or in the repos... The installer can also install non-free firmware... Also, the repos contain non-free programs.

**Comment by strugee** [comment]
@mimi89999:

> They can be deblobed, but it is not how the kernels are installed by default or in the repos...

So file a new issue. You're derailing this discussion.

> Do we really want to recommend a ROM, that is vulnerable to several known critical vulnerabilities

As I just said, we should probably revisit removing Replicant entirely. However, we're all agreed that the beta is at least better than the stable version, so we should at least make that change in the interim while we decide whether to remove it completely.

**Comment by strugee** [comment]
@hasufell I hear you, but the reason we recommend only free software is because the user has control. If there are security vulnerabilities, the fact that it's free software doesn't matter because the adversary can seize control.

**Comment by hasufell** [comment]
@strugee Did I say something different? Firmware/driver blobs are not free software and they are not exactly a trivial part of your OS.

**Comment by strugee** [comment]
> Firmware/driver blobs are not free software and they are not exactly a trivial part of your OS.

@hasufell of course. The point I was making is that recommending free software with known major security problems is just as bad as recommending proprietary software.

**Comment by yegortimoshenko** [comment]
I've recently bought Samsung S3 specifically to install Replicant on it, and unfortunately it doesn't work at all. Barring poor performance due to no GPU acceleration, Samsung phones running Replicant currently can't utilize the modem (i.e. no outgoing calls, SMS, or internet connectivity) with a modern SIM card: https://redmine.replicant.us/issues/1783

That said, all other Android distributions currently include non-free code that runs on CPU. The situation is really bad for software freedom on phones. I think that currently the best recommendation would be LineageOS on phones with relatively few blobs running on main CPU and good modem isolation, but it's very likely that those blobs contain backdoors.

**Comment by yegortimoshenko** [comment]
I've bought Samsung Galaxy S2 and Replicant works on it somewhat better, even usable.

**Comment by yegortimoshenko** [comment]
Closing as Replicant now doesn't refer to Replicant 6 as beta. Also see #1969.
