### ISSUE TITLE
is autistici.org mail + k-9 or thunderbird enough? 

### ISSUE THREAD

**Issue by laprasx** [nylira/prism-break#1605]
Also do I have to encrypt with systems like pgp (or another system)? Does Autistici mail encrypt itself? I did not get it.

**Comment by Zegnat** [comment]
No. Email is (hugely simplified) just a protocol for moving text files around. You depend on the people moving it around for you (your provider, e.g. Autistici) and on a stable client that instructs the people doing the moving (e.g. Thunderbird). But then you are still moving around text files, so you want to encrypt them. Nobody else can encrypt them for you.

Please see the [notes section on Email Clients](https://prism-break.org/en/subcategories/gnu-linux-email-clients/) for a few guides on the matter.

Closing because PRISM Break’s issue tracker isn’t a good place to ask for help.
