### ISSUE TITLE
VeraCrypt secure to use now?

### ISSUE THREAD

**Issue by Mattel88** [nylira/prism-break#1612]
I've recently used VeraCrypt. 

There is an audit available on ostif.

https://ostif.org/the-veracrypt-audit-results/

Most of the security holes have been updated. Is it viable now?

**Comment by Mattel88** [comment]
No info?

**Comment by strugee** [comment]
@Mattel88 everyone here is a volunteer. The fact that no one's responded means that no one's had time to vet VeraCrypt thoroughly enough to make a recommendation.

**Comment by Mattel88** [comment]
I'm sorry then. You can close this.

**Comment by alerque** [comment]
@Mattel88 You missunderstand. We don't close issues just because we don't have time to deal with them that second. They stay open until they are resolved — but the thing that needs resolving is whether or not to include in on PRISM-Break. This isn't a user support forum that  we're responding to your needs, it's a place to discuss what things we are or are not recommending. That happens at whatever pace it happens at.

That being said this can be closed because it is a duplicate of #1273. There are also a number of other places this came up, for example #995 and #1398. Please search the issue tracker before making suggestions to make sure there isn't a discussion already in progress.

**Comment by Kewjoe** [comment]
I've added a summary and link to the audit report in #1273

**Comment by tailslover** [comment]
Using it since it begun. I must say this software is stable than DiskEncrypt(which you endorsing in prism-break website). Why not add this software?

**Comment by strugee** [comment]
Closing as a duplicate of #1273
