### ISSUE TITLE
Project MetaGer

### ISSUE THREAD

**Issue by sumacarsten** [nylira/prism-break#1621]
Something is wrong and something is missing there:
1.) Since the 29th of August 2013 an english version of MetaGer is available (and spanish is coming soon). 
2.) MetaGer's source code was released on Gitlab (https://gitlab.metager3.de/open-source/MetaGer) at the 16th of August 2016.
3.) We support both english and german. The link is: **https://metager.de/** for the main page. You may reach other languages, the help pages and all other items from there. It would be better to have these links in the MetaGer project than the mixed ones you have.

**Comment by Zegnat** [comment]
What are you saying exactly is wrong here?

1. We know there is an English version, we link to it. We chose to link to the English version explicitly (and not the homepage) because it doesn't look like MetaGer detects the user's preferred language. We preferred sending our international audience to the English home page instead of a German one.
2. This is definitely an omission. Feel free to send in a pull request to add it to the project's listing.
3. See 1.

**Comment by sumacarsten** [comment]
Okay, you are right, I will give a pull request. Then the Wikipedia link is left: there is an english one: https://en.wikipedia.org/wiki/MetaGer

Thanks, Carsten

**Comment by Zegnat** [comment]
Hmm, I thought the decision was made to use localised Wikipedia articles and only use English Wikipedia as a fallback. I even remember writing a little script for that. But I can't find it right now.

Are we using the wrong localised Wikipedia somewhere?
