### ISSUE TITLE
Somebody likes Telegram!

### ISSUE THREAD

**Issue by jzakiya** [nylira/prism-break#1647]
**The ‘app of choice’ for jihadists: ISIS seizes on Internet tool to promote terror.**

https://www.washingtonpost.com/world/national-security/the-app-of-choice-for-jihadists-isis-seizes-on-internet-tool-to-promote-terror/2016/12/23/a8c348c0-c861-11e6-85b5-76616a33048d_story.html?utm_term=.75e036b10939

**Comment by strugee** [comment]
Uh... not sure what you're wanting us to do here?

See also #727, #1075.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> Uh... not sure what you're wanting us to do here?
> 
> See also #727, #1075.

I assume that this issue is intended as humor rather than a request to
modify PRISM-Break's recommendations.  I actually did chuckle at it.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYX3VFAAoJELPy0WV4bWVwjX4P/2K/z3Z1BVtLTNU6v+4RBMdy
HOUGVr/UPHqbxUGItyac/11FvhBcByyo497x2VrUVan4vZUWA+DHZCPRwtCsk36Z
5MPR20FqLZMOUGLINoH52+hD/O7gnQt7RvZpjbPxrIK9jF5nZ4l5BK4odMBew+0M
d/YSEFp5trrB4UkgD84QdqN9IIVUzersiUpykrZW9+uDJExoPZ9jSCbxCPBXcr0/
GHH4DLz+z9x6vd3429O6+lyFiG3I/cXDbHPeQKioebf1VCp6XBqbY5H1tQU3scS/
nJa5NSiRq/MdFJ4rI5hjiDTO/WyOyYS+/mOmZ/3gm0qW6wdnskB86/R8vJ6i1zTz
XW+kuq8xj1GlruPTl194PCPVmGxbVGq9UxgEhyIr7+hyXqnxjc6gtX0cJExE2uGb
v174wNqmDwheAcPe+toFcsT1w3VpjiAjPH4whX0cvUg4UvlgrOzjJN4aZL15dui8
Bq1od4RXag2P3W/263KQpqyQGZEuuNJZYE1siMC+MShDN2P2ukflL/iXzX2UvCcv
NWgWBGFCUozW6gXNPqaT/5Zv0MDPAkdXrqwYMpOdBAeKv+y2owfoSXZtQVJWYFaj
kUIRe0e9yEYb4L9hd0d3UZiObSAjHRVibH48XgUIUkXtm3eMX9OITyvbAy0FgFdZ
mnkJ5U+Rh4GXLsZ6qVtr
=oZMz
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
Closing as OP hasn't clarified what they're trying to communicate, so there's nothing to do here.
