### ISSUE TITLE
Manjaro

### ISSUE THREAD

**Issue by justjoshy** [nylira/prism-break#1650]
Hi there. 
I am considering the switch and leave windows behind. I read your OS-section. I understand the ubuntu struggle but i wondered about Manjaro. Does it have similar "problems". I am fairly good with windows and do not want an OS wich just gives me the basic options but i am completely new to linux and console. Hands I am looking for a distro wich does most/all with gui, but does not leave the ability of choice behind. Right now i am looking into suse and fedora. But i find Manjaro with a roling release extremly intresting.
Any advice would be apreciated. 
Have a good new years start!

**Comment by geplus** [comment]
Manjaro Linux is a Arch Linux based operating system, withits own repositories (that contain lots of packages not avaible in Arch Linux), based on 3 branches (unstable, testing and stable, each one with its update frequency).
Great community, that give audience and helps even the newbies.
Lots of guides, a great wiki; the possibility to use openrc instead systemd.
I use it since november 2013 , I'm very satisfied with it and I recomend it of course.

I think it could be considered as free as Arch Linux or Opensuse. Otherwise, take a look on Opensuse Tumbleweed, the rolling version of Opensuse.

**Comment by hasufell** [comment]
see https://github.com/nylira/prism-break/issues/820 where it was rejected, because of slower security updates

It seems that has been improved though http://allanmcrae.com/2015/02/improvements-on-manjaro-security-updates/

However, the OS section is already kind of overloaded, so new additions should really make a major difference (like QubesOS), not just be another flavor.

**Comment by strugee** [comment]
Any objections to closing this? Even if we decided that Manjaro's security is OK I don't see a compelling reason to add it to the OS list which as @hasufell mentions is already overloaded

**Comment by alerque** [comment]
No objection. Manjaro and Antegros should probably both be considered again at some point in the future to see if they hold anything over plain Arch in the security department. At this time either of them are probably better for end users convenience wise but since they are downstream on core components its better to stick with plain Arch from a purely security point of view.

**Comment by geplus** [comment]
@arleque consider that the unstable branch of Manjaro Linux has mostly daily updates, and it only delays about 24 hours compared to Arch Linux

**Comment by justjoshy** [comment]
Thank you all esp geplus for the guidance. I'll start geting to know linux with manjaro and will hopefully be fit for pure arch soon. Have a good new year.

**Comment by strugee** [comment]
@geplus does Manjaro unstable actually offer anything over pure Arch? Seems like kind of a contradiction to me...

**Comment by coreyreichle** [comment]
Ease of installation, by and alrge is what Manjaro offers over pure Arch.  The calamares installer, for example, simplified dm-luks usage.

**Comment by hasufell** [comment]
> Ease of installation, by and alrge is what Manjaro offers over pure Arch.

Arch is not in the list anymore. The current reasoning about OS inclusion is outlined more specifically in this discussion: https://github.com/nylira/prism-break/issues/1709
