### ISSUE TITLE
Remove Pidgin

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1653]
> [libpurple is] a flock of zerodays flying in formation.

-Jacob Appelbaum

We should probably get rid of Pidgin. The UI sucks, libpurple looks like Swiss cheese, and it's generally just hard to set up. Plus there are better options nowadays.

Originally suggested in https://github.com/nylira/prism-break/issues/1511#issuecomment-267753159.

**Comment by alerque** [comment]
Yup. Time was when using an OTR plugin in Pidgin on top of some other messaging platform was the best option available. Then TOR got added to the mix and it _could_ be used even more privately. But getting the setup anywhere close to right to maintain privacy and security is so hard that it cannot be reasonably expected from anybody looking on PRISM-Break. If they do want to use it they are going to need a handbook and some sandboxing know-how. The aging swiss-cheese code base doesn't help either.

I agree its time to take this recommendation off the table. Current users don't needs to panic if they really have it setup right, but new visitors looking for secure messaging should be pointed to other options.

**Comment by hasufell** [comment]
So the only alternative seems to be Gajim then, which I'd argue is not really more advanced than pidgin (e.g. also storing password in plaintext).

An overview of the alternatives on prism-break:

* profanity is console based, bad usability
* Kontalk is java-based
* Jitsi is java-based
* psi+ looks weird an unprofessional when I look at the repos
* the rest of the instant messaging recommendations are not a replacement for pidgin

Where are the "better options" now? Telegram (despite being open source) is not recommended on prism-break.

**Comment by strugee** [comment]
Tor Messenger springs to mind. Coyim has been brought up too.

Tor Messenger isn't on the site yet, but it probably should be. There's an open issue about it but I can't be bothered to find it as I'm on mobile and GitHub mobile has no search (i.e. GitHub mobile sucks).

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Is there an alternative to Pidgin that supports stream isolation,
supports OTR, and is packaged in Debian (including OTR support)?
AFAICT Gajim doesn't have OTR packaged in Debian, and Tor Messenger
doesn't support stream isolation.  CoyIM meets those criteria but
isn't on PRISM-Break at this time.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYcUWQAAoJELPy0WV4bWVwHA8QAMU369AcjtGt4Gg3s39g/M4z
PLPyWINpuqw/IiJB/BOHtTBIlgqodLb8oOUO7z5Iww+ULzMoUnbOKaJsaPUMIa4m
9hMYx6/Za74V19Iy7BgDxwXdvxjmdVr2k2l2+GxRIpjQtmrZSLci6rnu19QCfZ6U
+OZuYMYugeHm/AwEm6hAgYdYTyj8Odai99BQ2qFFo/UeprHMLUZsU0KdRIrKBBZH
3QvcKvXo9z+ITZzA8lmvcHOL2AZmnfAqHGKiFdre5mNPlMKCJYiX6oIOukhz8xh4
L4IEYO+B4RR+rupsBSCW+YUpUCsedoq9zFV4x0LzWks9NvhraUqlox1W1m4JTr7c
BDInKKwJeczobxBYCgex0GqhrbahsGAllrE40qMxFA7putPwPE6RFdx2xUSt41NX
0q6beEW+gfvVVdLQiw+xd/LaxICzfFk26V8mgNGEccYUcOBAC1KWuGPpzJYc25Dp
NGD8ljY5Wh5smOyPICVORzo/i+GPV4QozCsHX4GtskCywveYOjy3ml4aKiEobvD3
nS4i255Qb9nyXhiRGTb2NvL3444dLBnqg85Ikfn/QgoultS+2UVYOrPs4tmDJLTo
cR26oCLaFlDN0+JlQLKZAUKx+kIau3AE7fCoP1ZrkGYniRNOvK9LjO7/tvjs3P95
Xcjali3au69igkk+7DwY
=MA0g
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
@JeremyRand I'm not sure what you mean by "stream isolation".

**Comment by alerque** [comment]
Just a note that "packaged in Debian" is not a criteria we evaluate directly for PRISM-Break. Of course it's nice when good software is readily available and it might be one of your criteria for your own usage, but it isn't a deciding factor for this evaluation.

**Comment by strugee** [comment]
@JeremyRand ping? What do you mean by "stream isolation"?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> @JeremyRand ping? What do you mean by "stream isolation"?

Sorry, missed your reply earlier.  Stream isolation is a Tor feature
that forces traffic associated with different identities to go over
different Tor circuits.  In Tor Browser, the identity is the domain
name in the URL bar (so if you visit 2 websites in Tor Browser, they
go over different Tor circuits, which prevents exit nodes or the
website owners from knowing that the visits were from the same
person).  For IM, usually the identity would be an XMPP account.

Tor stream isolation is invoked by using the username/password
authentication fields of SOCKS5.  Pidgin works fine here, since it can
use different SOCKS authentication for different accounts.  However,
Tor Messenger doesn't support SOCKS authentication, so it's easy for
an exit relay or your XMPP server to know that all of your XMPP
accounts are owned by the same person.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYdqT5AAoJELPy0WV4bWVwY0MQAIdwTds7AaGE7UdgJ3LUYecy
T43DN5Nub25YoAMNPUNqPjUORctFGGzKgFRixB4dK2GieCNFq4nlhsf3CwdDDqSd
E/pRGodXZd6o3iAuqTjLStJfb/D7gmAc9PXBwUgo/jRq7Z+r0Df73685wRQ8wqNL
wITbzsv7K/LflgPxRxSAEpHDNz+meuzsUXSPyZA9K+0yjh0U10GnOBz5MhlT5Buz
KpPC9Y6v7Qi+Tezj1OVVlVcPU0Ykh705TbuBiEBKIZpkfwlYs2w7p2rgMo+pu6hP
HtiMcxEkYqam07CcjJQXpzGm6RlVUDKY3Dpez+5wGr+CQBKAD1w3pU/LlW1B/PeM
9p91+BCBp2+TR8jU5o29ZZ2m3N5NMBQObMWCoeR9oSnYVQ2wnwMXZisLBtQBc/vV
105tY8s97SYGIgPx8+ZZOey8MhmRZNxzdZmzjBWcK6fi9QSdjEymTKYRilW2OxII
O2qkPAq0G2+MSf3z8g0mPHKOwPubvGcujGRxcoUztQjWBMd+njvo83AbPe4h3TL5
X0OpfZ8KgDYbHOVjfBF83QBpB6mY5Bk1sFb/rbsRFT9zCEvmTsYrJbsn0a1Q0Yn9
/Hj8q0a2M2GaI6zdCmbx77XrKVM8owy/Zs5hfpMntgubS1BQdZnPmuE008mV7YfP
VbFWm60WlUXB35CSnM/5
=TPVw
-----END PGP SIGNATURE-----

**Comment by Atavic** [comment]
Once [OMEMO](https://github.com/twstrike/coyim/issues/421) is implemented, _coyim_ will be even more interesting.

**Comment by strugee** [comment]
@Atavic it's unclear whether the coyim folks will even implement OMEMO: twstrike/coyim#233

**Comment by strugee** [comment]
Okay, here's a proposal. The only thing keeping Pidgin on the list is stream isolation, right? Can we just remove it and then add a note saying that if you want that, you'll need to use Pidgin to set it up yourself?

**Comment by moparisthebest** [comment]
What's wrong with gajim again?  Someone above said it stores passwords in plain text which a gajim dev said was never true on linux (uses keyring) and hasn't been true on windows for awhile either (uses windows keyring there now).

Also that seems to imply that java-based is a bad thing, because segfaults and buffer overflows are preferable or?

**Comment by strugee** [comment]
I personally don't really have an issue with Gajim, especially if the allegation about storing things in plaintext is incorrect. Even if it isn't AFAIK it's still better than Pidgin since it's Java. But that's a separate issue.

Marking as accepting PRs given my comment above - let's remove Pidgin and replace it with a note about steam isolation.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> Okay, here's a proposal. The only thing keeping Pidgin on the list
> is stream isolation, right? Can we just remove it and then add a
> note saying that if you want that, you'll need to use Pidgin to set
> it up yourself?

I very briefly tested Gajim recently and it looks like it supports
stream isolation (although setting it up is similarly annoying to
Pidgin).  I haven't audited that the feature works *correctly*, but it
seems to be present from what I can gather.

Pidgin does have the advantage over Gajim that Pidgin's OTR plugin is
available in Debian's package repos; Gajim's OTR plugin is not
packaged in Debian.  With OMEMO gaining steam this may not be a huge
issue though.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYzhTVAAoJELPy0WV4bWVwb4cQAIYDahLfpnlVHBA3ER/bYjAc
HaAttnQJznky0AjzOhlJX+zkywp+CEuI8b5UQ5rN4wrZeexgWbrjo9oScC8e8BZS
60RqwPd5FO0rtKG1Xc9gmZoxK0AsHKzCdDxzu5bki5nBlpPQB0Bgr0Q4JrRDblic
Rcwx1FsC33JoRPUYxic9mOM+2MOXaiLe5U70p9dLiKyPB5PGLc57eZOSxls2d9gy
ucQnYMQ8QMC9L0+mGuLBFSXVOHKVdADHMG4BlhMhDriElW+GY8OmyiH8mR73LVY6
Pz2sac13fdg09JeWG81OC80n+834qj9M18B6rxrj3EFWl4FTntpV/xp9fAih3fPd
0aKdYI5KFVCmgmjsbZqBpc7CS/uQaI5Mm0p7ZslXha1w+dxG/Rwa47zZFmQ7KJ1T
J7GqhUt6WxE4Liq48f8uF+TkXO3K6LJQRa8oY+xTNOVTqi+U1SJ1gOe40n1Y72V8
UJBXxuqR5Xto/bJgw8G7d1H0f5qvVIgMmoK3Kek4TsysVoLv2hWCfqHEij1PhMJc
mVd0SvPdhu2/BtwFfhLp1pBM/0t1a/8UAbp6riXK0cskb2opFHcps6nU2mlBaOff
q3VFOz/zgbljiMabibUk1AY1PY/gaEvqJpjuEM3s/X4yVnxfqG5krsIQ0zMyrQvG
7UUneid0Ccx55wDgtvLD
=QBmx
-----END PGP SIGNATURE-----
