### ISSUE TITLE
Clean out old non-localized projects (dead-simple contribution opportunity!)

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1656]
Now that #1627 has landed, we need to go through and clean out all the old English content in localized JSON files. **This is a dead-simple way to contribute to PRISM Break** so if you've wanted to contribute in the past but weren't sure how, here's your chance!

Here's what you do:

1. Run `git pull` and `npm install` (if you haven't already)
2. Run e.g. `make localize_es | grep -v Missing` to find old data in the Spanish localization. You can look at different languages by replacing `es` in the previous command with a different language code.
3. Remove the duplicate data the script mentions
4. Commit and send a PR!

If you can, it's not a bad idea to manually scan through files looking for English data after you've removed all the stuff the script found automatically. This is because while working on this functionality I found a couple unlocalized entries that had gotten out of sync with the English version, and so weren't picked up by the deduplication logic.

Alternatively, if someone wants to hack the deduplication logic to just remove duplicate entries, that'd be awesome too.

**Comment by alerque** [comment]
This could easily be automated. Walk through the language JSON files looking at strings, see of that string was in the same place in the English JSON file at any point in the git history and delete it if so. My previous question about `jq` actually had this in mind for a make target that would scrub the un-done localizations that have outdated English strings.

Another similar data walk would be to review localized strings that have changed since the English string was last updated and show a diff between the English at the time of localization vs. the current English to make it easy for translators to update.

**Comment by strugee** [comment]
@alerque like I said, of anyone wants to automate this, that'd be fantastic.
