### ISSUE TITLE
Consider Lineage OS Android distribution

### ISSUE THREAD

**Issue by alerque** [nylira/prism-break#1662]
[Lineage OS](http://lineageos.org/) is a community fork of CyanogenMod (which we used to recommend but removed as of #1588 per discussions in #654, #726, and #1005) that seems to have the support of a lot of the original community and developers that were disenfranchised by the commercial direction taken by Cyanogen Inc. The [repositories](https://github.com/lineageos) are looking good and it seems like this lives up to the previous standards we held Cyanogen too before the commercialization hit. It's trajectory seems quite promising.

I'm not sure yet whether we should recommend it, but certainly we should be keeping an eye on it and considering the pros and cons of recommending it in light of the return to open source roots. 

See also tangentially related discussions at #1600 for Replicant,  #1524 for Copperhead, and #903 for OMNIrom.

**Comment by hasufell** [comment]
Drivers and firmware are supposedly not free software, so not recommendable, unless you want to give easy backdoors to your enemies, which means it's totally useless in terms of prism-break. I guess some people have to re-check the snowden documents or some of the CCC talks to see why this matters.

**Comment by Francewhoa** [comment]
For those not familiar with what happen with CyanogenMod. CyanogenMod went commercial. In other words, Cyanogen Inc. tried to monetized the open source community project CyanogenMod. Sounds like Cyanogen Inc. were serving money first instead of serving the community first ;) As a result the community forked CyanogenMod to LineageOS at https://github.com/lineageos and http://lineageos.org Which is fully community-owned. And without strings attached to any corporations :) So really free of corporate interference.

On 23 December 2016, Cyanogen Inc. announced that they were shutting down the infrastructure behind CyanogenMod. This was shortly followed by news that the main CyanogenMod project would migrate, renaming itself as "LineageOS". On December 24 2016, Head of Developer Relations and community forum administrator Abhisek Devkota, a Cyanogen "core team" member, wrote that the community had lost its "last remaining advocate" within the company and its voice in Cyanogen Inc. and its software's future. He stated that while "that this most recent action from [Cyanogen Inc.] is definitely a death blow for CyanogenMod", the community had already begun taking the steps needed to fork the project under a new name, and aimed to return to its grassroots origins while retaining professional approaches adopted during the Cyanogen Inc. era. Due to the negative connotations attached to Cyanogen Inc's conduct, as well as the scope for legal dispute, the forked project decided not to use the existing brand names "Cyanogen" or "CyanogenMod", which in any case belonged to the company.

Homepage http://lineageos.org/ 

Read more https://en.wikipedia.org/wiki/LineageOS 

Related post https://web.archive.org/web/20161225144318/https://www.cyanogenmod.org/blog/a-fork-in-the-road

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Lineage OS's website doesn't appear to have TLS configured properly,
which is concerning.  I assume this will be fixed before they actually
issue a release -- if it is not, then it's more concerning.

(This is also an issue for Replicant last I checked.)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYi7hCAAoJELPy0WV4bWVwIr4QAJGr+i7kl0wy/36+dpwalNEX
6PaSBc+RjOr/2rLXwkuOYlYXet1F09S8wiyTiRWV/jpz5bEB/3pS1QmvBG6r/Jgm
XsyuJNd0rfjoc6uVXDE2NO3KkFtdTZIqRDm/nDbl8RQ0CIM5PerYWGpRYmIqNXRx
FZNO1TMYx8MShibvrwW0q0wnpMOROozM4JYII9d6o0ME9bwDu8oPqeGklnPf//TL
qsQfCAhu6HXoQjYwSRDSgYgKME//YL/2bi8fb8Gl/wpjkg+Id+Z6CyH/j1tvVj2J
mLS9jofNdcCI0ueOePNqUR5x16ZQnkNB5rUzPt+c12oFaQPeUTp0M8+MH6KIPcba
BK0lPfcYGQcPzypibB4k3Tb3NSzDGlpGrh1ny77k4z0nLNDSFNX8XJGz1imfGkEI
dZn0vcSLJ/MZHuSh/1Eh3B+krjLWzf/G696iq6KAYNuLpD2iBpawbBEOMnN0UP9D
c4k9op15To4KZISWLY9nVJB8wm+yY6ZbfkwVen1DUtVqejnhXrGRb2UQMEpqIzyE
tf7aujem+xsD6BH0l/u2fezPzKsJrJtmKS4Xzmj3e9KQzSasFTwtiEhQ+8uE+77F
szD1bE/ze7WgtqJRLNNqU62yRn6gnNwF+ilXujlAtTcR8OnSJAGIOlePNfg9nAcf
R0/ALbJDJ5C/GU9AtYFe
=LzOr
-----END PGP SIGNATURE-----

**Comment by Hillside502** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=lineageos.org&s=192.30.252.154&ignoreMismatch=on&latest

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

LineageOS has downloads posted now.  Although the download site has
TLS enabled without errors, the download site only provides MD5
hashes.  They say at the bottom of the site that to verify the
downloads with better certainty than MD5, you should verify
signatures... except the instructions they link to don't have TLS, and
it's completely non-obvious how to verify the signatures without the
instructions (e.g. they're not standard PGP detached signatures).

Granted, these are nightly builds rather than official releases... but
it's still concerning, since I suspect a lot of people will be tempted
to install those nightly builds even though they're not easily
verifiable.

(I don't claim that LineageOS is worse than Replicant on this point;
they're not.)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYqQ3ZAAoJELPy0WV4bWVwUnQP/0kryVo6A1ORKE+dT9/Nw9OU
/mEG8kAeLGNq/1MJsdHexijPasl5325pY8qadxLenwH8RLeK53U+DtST8UCDNlfY
5xyunRiPZw+zX54njjNKNoSJ+LpIFA6rMu7TvOKr0RMbGidOW96KUtCThJ6lQZUN
F9jmENG3Rne/0la7+9y6+I73hm1ZtnbPpn4M1Lyia58M0MqFeKmxLXghNoMv6z1C
HuJRSUvFk30vk+ko/P/ICn7iIWjo7cwPkC0hYEYWHFWWBLQ6J9IQTfvnwX3FYTNa
rzyWlMvieHt5SFW4NhMCe+XE9he4t5/SeKZuB1DhMnhLX5AFdv8b/HJ24SxN8/XZ
eEkFu0/onHQbHOTC+++RMmmfrV6Z+R6qw4YtVomNMwyZKda/Q0bxATRUVOKLE/I8
FdwTeXS/peTa2QhsH+bg0a49wNDnRzu2ywVUc4BPy4fqha5cTlN+PCXy/LC9ioMF
MjP6GSQDWVnJcBI7TQynA9bFlRGQBAlmuvQnpZ1Npig1zC0lnNedsVY1QmXBZvIe
lONQGGq+ioBr4/ArFNid9UI3reBtBdLmLzBupmKl6r/gXH7pMO55JISrkjxTZTsX
Y66zZ37HkVCuUA/f+9zBm+82zOCidVyteqzce0S+UVQsCdNzgMRXKo2UFhBAFEF4
kzE8CBnGtzmg2S5zRqdI
=1tny
-----END PGP SIGNATURE-----

**Comment by mimi89999** [comment]
Maybe we can ignore the issue with drivers and firmware because LOS is much better than most stock ROMs that contain tracking and are late with security updates by half a year.

**Comment by Hillside502** [comment]
No change in their website security --- still an **untrusted** certificate!
https://www.ssllabs.com/ssltest/analyze.html?d=lineageos.org&s=192.30.252.154&ignoreMismatch=on

**Comment by mimi89999** [comment]
The downloads website has a trusted certificate. I think it's what really matters. On top of that, the zips are signed.

**Comment by Hillside502** [comment]
@mimi89999 
lineageos.org is using a certificate bearing the subject *.github.com

In other words, they're using someone (Github) else's cert --- amateurish in the extreme!

Please take a look at the Qualys report link above.

**Comment by mimi89999** [comment]
It's a Github page, that's why. That is not important. Somebody can check that the page is correct by visiting the corresponding repo.

What is important are downloads and the page has HTTPS, so it's good.

**Comment by Hillside502** [comment]
@mimi89999 
You're right about it being Github hosted:-
https://iplookup.flagfox.net/?ip=192.30.253.113&host=github.com

but it's amateurish nonetheless!

**Comment by mimi89999** [comment]
It's saving money when you are limit...

**Comment by Hillside502** [comment]
@mimi89999 
Let's Encrypt - Free SSL/TLS Certificates
https://letsencrypt.org/

**Comment by mimi89999** [comment]
So deploy a LE cert on a GH page... 😐

**Comment by Hillside502** [comment]
@mimi89999 
By some strange coincidence ;-) https has been dropped, solving? the problem

LineageOS – LineageOS Android Distribution
http://lineageos.org/

**Comment by mimi89999** [comment]
@Hillside502 What would HTTPS protect on that website?

**Comment by Hillside502** [comment]
@mimi89999 
Deprecating Non-Secure HTTP | Mozilla Security Blog
https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/

Marking HTTP As Non-Secure - The Chromium Projects
https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure

**Comment by mimi89999** [comment]
@Hillside502 That doesn't quite answer my question. What is at risk in that case?

**Comment by Hillside502** [comment]
Not my job to say --- just to point you in the right direction.

**Comment by mimi89999** [comment]
@Hillside502 I think that you misunderstood what HTTPS is doing and what it is useful for.

**Comment by Hillside502** [comment]
How about:-
Opt out of global data surveillance programs like PRISM, XKeyscore, and Tempora - PRISM Break - PRISM Break
https://prism-break.org

Why is that HTTPS?

**Comment by mimi89999** [comment]
@Hillside502 You don't have HSTS preloading. It's useless if somebody is visiting that website for the first time.

**Comment by Hillside502** [comment]
You?

**Comment by mimi89999** [comment]
No. 😂

The risk of not having HTTPS on prism-break is that a bad party will change the content of the website to recommend backdoored software.

The risk on not having HTTPS on lineageos.org is that somebody is sent to a download page hosting backdoored versions of LOS. If somebody has downloaded lineageos before, he rather knows where the download page is.

**Comment by Hillside502** [comment]
You've answered your own question!

**Comment by mimi89999** [comment]
In my opinion that's worth a security note, but it's not a reason for not including it on prism-break.

**Comment by strugee** [comment]
@mimi89999 preloading is tracked in #1664 but we need @nylira to do it.

It'd be nice if the LineageOS page was HTTPS. But not a show-stopper, IMO. I also see no point in arguing over whether having a cert that's valid for `*.github.io` is "amateurish" - there are legitimate reasons to use GitHub Pages over something else, and I don't think it's our place to question that since if you're using GitHub Pages it's not like you can control what cert gets used. The only thing that's of concern to us is whether or not missing/broken HTTPS compromises security to the point where we can't recommend LineageOS.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> It'd be nice if the LineageOS page was HTTPS. But not a
> show-stopper, IMO. I also see no point in arguing over whether
> having a cert that's valid for `*.github.io` is "amateurish" -
> there are legitimate reasons to use GitHub Pages over something
> else, and I don't think it's our place to question that since if
> you're using GitHub Pages it's not like you can control what cert
> gets used. The only thing that's of concern to us is whether or not
> missing/broken HTTPS compromises security to the point where we
> can't recommend LineageOS.

Note that the Replicant website also shows a TLS certificate error.
While I strongly wish that PRISM-Break could automatically reject all
projects that don't have TLS on their website, I do not think we are
at that point yet.  (But please keep pestering the project devs who
don't have TLS yet -- they need to be pressured into fixing their
security.)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJY1L2CAAoJELPy0WV4bWVweD8P/0apT8py9cIZ789YFIJ/3aq5
xjGRp5YvrdAi7ybLOeawRr5FO1vt1mg4p5VKsbzxjfkaO9J/xBRBGPLUYtWzOih3
bdcxZdH+2qk8YKrY3R682Ez2Gxw3SY91FjwzpMV+UcxNu0ziRChLc4AS7wj/MtIU
l33NZ5b913gk1/pQBcD3jyqsNNzpiaCTI+4/3p4SstIbww19oJw1jd8xtAzoFlT9
2irbrl1hEXlDq1H3eyVrNaKTOtiXxXpi1JDCN4cUTTVf7/NXWr3DgYyM8OhxkEli
BnQDi2kmi71Y0I7XLx7zVdsuh7UYbbc8CO3HDKLPRvoeNbZuHXdfImH7LXn5d0k3
CQ/JwnoL9KMRoG0PruD7/jrueW9fJlVoMJbLelaJeYcwNZUka8DPf69BJ2Do9OMi
40HyPVAKQcxqbK/PqbGAkyHoGfhZpyW34k0Xyn/7ZMEtAtkPDiDKsAA86qqVcgKg
deSxQo1DcgTZe51hP/n+niCI0jM4VzDyNxVoGI3IUxsfw8/Wkui/HbUa/LCrKRlk
bt8sLLwGaj0SDtTXiAWa6lee+xo4CURR4y3PNH+ZLwLsY62fXnAo+Gl28wL15uJ0
9N59KLuJ9nSBTRBbLBx6pfrqcaI6cP/4fx4aFShlwQOcylFGj++2rd4gy52rf2w5
tRuE+eh4vFSrkeNhDtPH
=Ejy7
-----END PGP SIGNATURE-----

**Comment by mimi89999** [comment]
@strugee 
> The only thing that's of concern to us is whether or not missing/broken HTTPS compromises security to the point where we can't recommend LineageOS.

I would say that no.


Is there any other issue?

**Comment by hasufell** [comment]
> Maybe we can ignore the issue with drivers and firmware because LOS is much better than most stock ROMs that contain tracking and are late with security updates by half a year.

Why would we make that compromise exactly? I don't agree that this is a strong argument. Are we recommending the "least worst option" now? Like in politics?

There are cases where there __can't__ be trust. Not having control over your driver/firmware is one of them and a pretty big one. And those are natural targets for mass surveillance. So this matters to us.

If there's no reasonable choice to something, we should reflect that reality, instead of trying to look for the next thing that isn't the worst.

**Comment by mimi89999** [comment]
@hasufell I agree with you, but if one doesn't have a Samsung Galaxy S2 or S3 (AFAIK the only place to get them is Tehnoetic), prism-break doesn't have an OS for him. On the other hand, Lineage OS is much better than most stock ROMs, that have blotware, spyware, etc. preinstalled and that have security updates from 6 month ago...

Considering all that, I would add Lineage OS leaving the driver/firmware issue because it's more a hardware issue...

**Comment by hasufell** [comment]
> prism-break doesn't have an OS for him

Yes, and? That's the reality. Security on mobile is hard. Suggesting it isn't is wrong and lying.

> Considering all that, I would add Lineage OS leaving the driver/firmware issue because it's more a hardware issue...

Driver/firmware is __software__ and again: a natural target for mass surveillance. Why would we ignore that?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Michel Le Bihan:
> @hasufell I agree with you, but if one doesn't have a Samsung
> Galaxy S2 or S3 (AFAIK the only place to get them is Tehnoetic),

Galaxy S3 i9300's (the ones that work with Replicant) are readily
available via eBay and Amazon.  I've bought one from eBay and one from
Amazon without trouble.  (I recommend Tehnoetic if it's feasible,
since they support Replicant, but users who cannot buy from Tehnoetic
have plenty of other options.)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJY4G1KAAoJELPy0WV4bWVw0VwQAIDzAR3j/WpVIZkEkJey0tDx
skxqluqYkTgXJHJwx6HqQdCLviP1JB87cBTKfEvXrRuglFJohPix3QWe6s8CGDBb
xa8DaNCFs4DoYkQJZgsEeqiXnYGhRyUH3D9PiLpCUun70RSAMHlI2ZkqyA1lIcrE
fJZpV1k9J/VhMYnsrJ3oYAO5J1zWgnAwmwLEY9g6U4pPlrK79t6VU8w2zAsaBxMv
5PQg2k8+RSd6SjWFzt0bBhzz8kEb68Nnwrk3N5NqlPwan0QxLqYGycxSUUN8W6bL
qfl97aBX4C8Ov9sKe2CfGBNiedXcybClnlJVZ8452ZM7jiKZ6zsB9DEeSZWyz4m2
gDiuDdBimpBDy9ap9/fjVHm7hNg4gIIXUIJNMomttBx/v/EvAXSip6sFZtnLtJQk
3J1xcu57tmszjvFFw+WrY9vLTFSFAUX0EufohPBtSw+NNRK1G5zcxPRxW+lVY1va
NFUwHEePN6kU1ZZykgU2/JV+inRkjKyA+UbS9htKvzuXcDbx9xSVHPffOU70ugNC
8oKgCyhUcKZgcDZGXjacBlLtz7OBFSxN8w/SX23i40/xMPMawr7FJHT9dYnjOK3L
5UllfcKvhqtoapufFPJchTsMhkJhP9wmYytAygoslmpcyDMjj6f7zy2p/b1safx8
0bHxeTQdjIf4SrKfA3av
=ioOL
-----END PGP SIGNATURE-----

**Comment by yegortimoshenko** [comment]
Another problem is that kernels that LineageOS ships are not very well-patched security-wise, I couldn't find one that ships Spectre/Meltdown mitigations for example.

**Comment by strugee** [comment]
Addressing https://github.com/nylira/prism-break/issues/1662#issuecomment-290144324, I wonder if adding LineageOS to a note would be good here. I don't want to fully recommend something insecure but it does seem like we should be helping to steer people away from stock ROMs.

**Comment by yegortimoshenko** [comment]
LineageOS certainly has the widest reach and a good step towards the right cause, especially given that kernels that most Android devices on this world run are probably in a state worse than ones that are shipped in LineageOS. Also, LineageOS has the latest AOSP patches. I think it's all net positive and we're not doing anyone a good favour recommending something that doesn't actually work (Replicant).

**Comment by quantumpacket** [comment]
@yegortimoshenko correct me if I am wrong, but wouldn't any device that has January security patches or newer be protected/mitigated? LineageOS is currently patched for February for the 15.1 (Oreo) builds, newer nightly is probably patched for March.

https://source.android.com/security/bulletin/2018-01-01

**Comment by yegortimoshenko** [comment]
That doesn't include kernel patches and blob/firmware patches.

Here are kernel vulnerabilities: https://cve.lineageos.org/kernels

**Comment by anthologist** [comment]
Just to clarify and avoid possible misleading informations, as they say [here](https://cve.lineageos.org/) "tracker needs to be manually updated". I just checked some unpatched issues for my device, and the code was actually already patched. They should be more active updating their tracking system...
