### ISSUE TITLE
Some GNU/Linux distros aren't 100% FREE

### ISSUE THREAD

**Issue by mimi89999** [nylira/prism-break#1663]
As I said in #1600 some GNU/Linux distributions, that you recommend aren't 100% free like Arch or OpenSUSE. Their kernel is blobed, the installer can install non-free firmware and non-free software is allowed and present in their repos.

> That was discusses before. Open hardware is not in the scope of prism-break, free software is. The line we have to draw is pretty simple. The line is exactly there: free software. And that especially includes drivers and firmware, because they control your damn device.

To be consistent with this, we should stop recommending them.

Also, it is not about the kernel can/can't be deblobed, but rather with what a user ends up after passing all the installation steps.

**Comment by alerque** [comment]
Hey @mimi89999 could I ask that you edit/comment this to clarify what _your_ actual recommendation is? At face value you seem to be recommending one thing here, but reading in context with other things you've recently suggested (e.g. comments on #1600) this seems to be a double parody of some kind. Given that you were advocating for _inclusion_ of systems with the same issue, this could potentially be read the opposite way. Given  the potential for reading two ways, suggest a more direct approach. Could I ask that you state what _your_ recommendation is for dealing with this issue and comment on what _you_ think PRISM-Break's approach should be to OS firmware blobs in general and why? Don't quote bits of other conversations or use "well if that then not this" structures,  just let us know what your take on this would be. It will be a lot easier to discuss from that as a starting point without trying to decipher what your actual goal may or may not be. Thanks.

**Comment by strugee** [comment]
@alerque I believe @mimi89999 originally had one opinion which wasn't consistent with PRISM Break's threat model. When said model was pointed out to them, they accepted that (i.e. changed their opinion) and then noticed an inconsistency in the site and filed this issue.

@mimi89999, is that correct?

**Comment by hasufell** [comment]
This was discusses ~2 years ago already, but I'm too lazy to search the archives. Long story short:

* A distro allowing the user to install proprietary software does __not__ conflict with the goals of prism-break... distro packagers have an obligation to their users and not all of them care about privacy in the same way. So while the basis of a healthy distro is always free software, it is very natural to, for example, allow installing the proprietary nvidia-driver, otherwise distro devs are crippling the distro for everyone else. That doesn't make sense. What makes sense is this: privacy aware users must have a simple way of banning non-free software from their system. This is fairly easy in e.g. [Gentoo](https://wiki.gentoo.org/wiki//etc/portage/make.conf#ACCEPT_LICENSE). Distros that make this thing hard should indeed not be recommended.
* The kernel not being deblobbed by default (there are good reasons for that btw.) is a usability issue and may be used to argue that one distro should be included in favor of another. But it doesn't make sense to remove OSes from the list just because of that. That's like saying "distro xy does not have Tor pre-installed, remove it".

**Comment by mimi89999** [comment]
@strugee Right. Am I the only one to notice a conflict in @hasufell 's view because then one can also remove non-free parts from CM...

**Comment by hasufell** [comment]
There is no conflict, you are just not listening.

**Comment by hasufell** [comment]
> then one can also remove non-free parts from CM...

Lol, exactly not... please tell me how.

**Comment by mimi89999** [comment]
@hasufell freecyngn for apps, you can manually remove proprietary fw and drivers...

**Comment by hasufell** [comment]
No, [freecyngn](https://github.com/nvllsvm/freecyngn) just removes proprietary google libraries. The source code is a trivial 20-liner [shell script](https://github.com/nvllsvm/freecyngn/blob/master/20-freecyngn.sh).

This is unrelated to proprietary fw and drivers. Can we be serious now?

**Comment by mimi89999** [comment]
What is the difference between the proprietary drivers and FW that come with CM and those, that get automatically installed by the installer of one of those distros (if one has HW that needs them)?

**Comment by hasufell** [comment]
> What is the difference between the proprietary drivers and FW that come with CM and those, that get automatically installed by the installer of one of those distros

You can easily deblob the latter (there are scripts for that, which are __NOT__ trivial, check the [source](http://linux-libre.fsfla.org/pub/linux-libre/releases/4.9.1-gnu/)... it's not just kernel specific, it's also version specific). In addition, there is a _huge_ difference in the state of mobile device hardware and desktop system hardware, which defines the usefulness of deblobbing. Without a major effort like Replicant is doing, "deblobbing" breaks your whole mobile device experience and probably even renders it unbootable and that's also why there are no such deblobbing scripts for android, afaik.

So, instead of spreading misinformation, start to gather some.

**Comment by mimi89999** [comment]
I was thinking not about blobs, but about drivers and FW that are in a package (not distributed with the kernel itself)

**Comment by hasufell** [comment]
I don't see where your questions are going, nor this thread.

**Comment by strugee** [comment]
@mimi89999 this:

> I was thinking not about blobs, but about drivers and FW that are in a package (not distributed with the kernel itself)

makes no sense. Blobs ~= firmware. And IIRC most of them are distributed with the upstream kernel; if a distro puts them in a separate package, it's because they did extra work to separate it out. And as @hasufell said, deblobbing on mobile will probably render your device unbootable. It doesn't matter how blobs are packaged, where they come from, whether they're called firmware instead, etc. Your device won't boot.

You need to do some more research and then come back here and read this thread again.

**Comment by strugee** [comment]
FYI if you choose to search for this stuff you should understand that "blobs" is short for "binary blobs"

**Comment by hasufell** [comment]
Thinking about it, I think we should rework the OS section a bit (the comments specifically):

1. remove all/most distro-specific comments (e.g. "Debian is...\<blah\>"), because it's too verbose
2. add a more explicit note about kernel deblobbing and why it matters

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

One thing to keep in mind is that, in many cases, blobs that run on
the CPU in ring 0 (e.g. kernel drivers) are extremely dangerous, while
blobs that run on peripherals (e.g. WiFi firmwares) are much less
dangerous because they have less opportunity to cause significant
harm.  Other factors also come into play, such as "Is the peripheral
isolated via IOMMU?" and "Is the peripheral expected to have access to
unencrypted private data?"

Most Linux kernel distributions do not contain CPU blobs by default
(e.g. you need to take extra explicit steps to install the Nvidia
driver in Fedora).  However, it is much more common for Linux kernel
distributions to include peripheral firmware blobs (e.g. WiFi
firmwares are included by default in Fedora).

I'm not advocating any specific policy for what types of blobs are
acceptable, but I think it would be a mistake to consider all blobs to
be of a similar threat for PRISM-Break purposes.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYetZAAAoJELPy0WV4bWVwJZYP+wafDtpSFsshLmsys7rKA5Yg
AGuO1TcUXD75eEfW5vb05Oc+WFHtvyw24subom4Y1Gvp8f9H5x8ICLJSJGR9r2rX
8m8Cej0WSitxlatZoSzUTQVsackcnUeNHvITiWhh/9eub79pi/YVW+5uLCVhoHjx
N1Mvs9hUh1qVp3HB3tvKC5nwBkKsFVR83mJTVoWFXdWdsbmDf7UI/VW4lVq1HRLW
W8SRR21eQ+8lEl9U6YeeWjgVRb+YnoqnY6381UYi0toYu2OqxPO9ClzQtQQkbluC
SZAZ3ztprckZlMuesYic/5MZEaJLSnI8YLRW2alMLnBrxIG3zqurW9uZFC3D2z3S
CopI/bTDmZ7s0v5m4Yt4yy5pT8kCr/ciVO3DFdr0ikhSQLcHlEfzO4OL/HU81Rye
uHi4CUWQmrYRMxZRmQSQ7CAWri1JDkbX8a+c7AkCVuNYWT63mfXEdUZ3dgYNbBIY
hVlpkRexHtgrfK38qNWWJSkQr4j9k5qGGaX62f4VxNpiLi6W3VrAIQTvLEBXUjR6
60wfrdma9GZHX8t+qnpPJ/C225Wl/Bm0Xf4WLAhk7ZRIsJw38y3Erp8dNi6eqaC7
5st+VDzp7om5oGkZulbbczB0WIz5Z5p7Hh4UHhnREfnMPF3vwGhs4gqmP+C9eed9
S5UZLb9M5zhBX/EX9b/r
=QXxZ
-----END PGP SIGNATURE-----

**Comment by hasufell** [comment]
> for what types of blobs are acceptable

None. There's no useful categorization of "danger" here.

> while blobs that run on peripherals (e.g. WiFi firmwares) are much less dangerous

I have no idea how you can arrive to that conclusion. Wifi blobs are, for mobile phones, probably one of the most obvious backdoor spots. The kernel is not designed to run untrusted firmware, not at all.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Julian Ospald:
>> while blobs that run on peripherals (e.g. WiFi firmwares) are
>> much less dangerous
> 
> I have no idea how you can arrive to that conclusion. Wifi blobs
> are, for mobile phones, probably one of the most obvious backdoor
> spots. The kernel is not designed to run untrusted firmware, not at
> all.

WiFi firmware blobs often don't have access to the system's RAM and
other peripherals, whereas blobs running on the main CPU can trivially
access system RAM and arbitrary peripherals.

That's not to say that they can't do any harm, but their ability to do
harm is limited compared to what blobs that run on the CPU can do.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYgFUyAAoJELPy0WV4bWVwAEMP/RHCeuCLVNSszsmBNKHPIrz6
y/mAexE7GU2mODmNBiY+NolGLiV+pAOucCFbAY+8AYVeUikuc3blqjMbAT6twWco
g3gpofNrblqkrcW2hLMWUjBKPg6qOO5z/HfMmCLZahf95MoSQNYJFH6V+klCHOd6
BP6PD8VTBGPg6QjujZuHWaKvQYOTo7iaP725KLgESpXMs4tcYiASajp8EmOvKrRi
YWzRKiyPp5oNI3zcVxwZtKiZxUGJjJ58JrNKOPICj3Ec3uTr8dA6YG4qWUNrtI0m
6SkDfsI3et29kO4fiEqqYxZBIyvzYl+GvsSxqtVEwDXBtxCXfzdmUtovka5RbFvt
5VY2W/SCoTadkhsafS9izyTD7ou1CUYwsMnWvKeSKbM9nNOD4yB1tPHxuWyXQqTH
fDxzA7olMeDQfRJ209vOAISRD1GQ8/9lHTFjM41WM4q2hS9DPAzfkm04JvdCwJIr
l3I5LTWTuX0L/EBaAA5mb0AyZP0OkEhZ725h/HzDGreWlP9uYT8Uog+pABjo3AA9
yAEItV9pdyfzNGSru27UuNf8YksZJVGz31LY3TRQThGPX6sECQxvm92JF/ZnIQIW
McjBKbGaJ9/vxcjLfnBpU9XV3IfgTDqc1tTwwM0JjNPlbIrSZq/YoYKHMqjlMehx
ccorFt/3YbvmlSnFNuzk
=6Nk5
-----END PGP SIGNATURE-----

**Comment by hasufell** [comment]
> WiFi firmware blobs often don't have access to the system's RAM

That's more guesswork based on an architectural design choice. If science of hacking has taught as anything (see [langsec](http://www.langsec.org/)), then it's that these assumptions are more often wrong than right and things have to be treated as _untrusted_ input. This is not the case here.

It's easier to prove that something is broken than that a turing-complete, programmable "weird machine" with multiple layers of protocols, input, state and whatnot behaves in some specific way. This situation is bad enough. It gets exponentially worse if we don't even understand parts of the weird machine (apart from the input itself). To the point that I'd definitely not make any assessments about what it can do and what it cannot.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Julian Ospald:
>> WiFi firmware blobs often don't have access to the system's RAM
> 
> That's more guesswork based on an architectural design choice. If
> science of hacking has taught as anything (see
> [langsec](http://www.langsec.org/)), then it's that these
> assumptions are more often wrong than right and things have to be
> treated as _untrusted_ input. This is not the case here.
> 
> It's easier to prove that something is broken than that a
> turing-complete, programmable "weird machine" with multiple layers
> of protocols, input, state and whatnot behaves in some specific
> way. This situation is bad enough. It gets exponentially worse if
> we don't even understand parts of the weird machine (apart from the
> input itself). To the point that I'd definitely not make any
> assessments about what it can do and what it cannot.

It certainly is difficult to be sure, and a lot of factors come into
play (e.g. without an IOMMU, there's a lot more potential for damage).
 But I think your point doesn't change my assessment that kernel-mode
blobs running on the CPU are definitely highly dangerous, while blobs
running on peripheral firmware are less certain to be highly
dangerous.  It's definitely better to have no blobs whatsoever.  But
in the world we live in, many users aren't likely to give up all blobs
(e.g. using Linux-Libre), but are a lot more likely to give up CPU
blobs (e.g. using Linux).

I'm not sure what the best way to convey this to visitors is.  But
removing all OS's that have any firmware blobs means scrapping a lot
of OS's, even things like Qubes.  To the point that the result might
be that users decide it's not worth the usability hassle and decide to
stay on Windows or MacOS, which is probably the worst possible outcome.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYib8aAAoJELPy0WV4bWVwlbQQAMcGdCIkE3ilpBve/MhS1wJB
N5WmnhLnFOV3z+JkrCP0nOxLslsf1VfzZrho1MZblOIuPP3EZJFpwrmH4OQbxtVs
Xt2SmP3s//rGxXqWpSTj7BbnpwTZ9KpEd9ojoWgNKnOYpQqXDC6g65cGszrorFEE
1kc+qsBFdmqezGfYiab0TCmChXDoMnSr4hvlyNABdG4kULnko20Ov+JA0jsLYnfy
P/k0r0JMlk2tPrVyaS8WanIwjeSLinIoDWvQGIz4ggMnCpCGGE/j3NnXzz6Q2Xd9
m8mn3rI/xScgWdBO8g9GQjhVtx0zkJGKeKqzhENzA9u+V9qQ8wYnilre1fbo2VCA
ajw6M++iYXDBuGqq/mDoY+gGEaTxx1NmzOHXlGEWA8d8fmUqdHaeDHMzwhEPnOfj
+7gv4jQiGNFY2II/pKnMEnQ1hroNEGmH07UHGEdKgn9qnSTBJ/lXlBZ+u6eMgU30
yR8AwusgLw6WRsBSnZ0LdFqC1i5xQOImW3apOQZRw8dSUOF0fh6GzhymxziZ2avQ
vG3AWMUP2KztcbucwxfrTUhxtCHlRP1wPWiWMqhLON2fwOlZXNkpLuCZ+fVIaNi3
dOTFkpldEBP9uPpnKrDpDr6fxGFpIVKWsbaJrPkPcfpxEGCTUhOvPXWX2PnH1Abi
bIU6bfPCHrRsYG+ySb4A
=pLJO
-----END PGP SIGNATURE-----

**Comment by hasufell** [comment]
> But
> removing all OS's that have any firmware blobs means scrapping a lot
> of OS's, even things like Qubes.

That was not my proposal at all and I don't think it makes sense. See my above comments. Playing down threats and non-freedom based on fuzzy guesswork of attack vectors is really not the job of prism-break. Nor do I believe it is practical for this purpose.

Threat/Risk modelling is done in software development as a method to prioritize and identify potential problems. It's not used as a method to actually assess threats on a technical level, because our systems are far too complex for this to be remotely useful.

And there is enough research (also on hardware level) that shows how concepts and (security) assumptions are simply broken by hackers.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Julian Ospald:
>> But removing all OS's that have any firmware blobs means
>> scrapping a lot of OS's, even things like Qubes.
> 
> That was not my proposal at all and I don't think it makes sense.
> See my above comments.

I may have failed to follow your comments' context; apologies.  If I
understand correctly, you're proposing adding information to
PRISM-Break about deblobbing distros that have blobs by default?  If
so, that certainly sounds fine to me.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYkD3nAAoJELPy0WV4bWVwAPsP/277+5Y0H/9b8vz6qtHZIkW5
kqSRn83ORyLueIutK0bepZ3ott2fbUwIz2hCZy09JcuSuA+f5V7PIlIPnUY2zK0G
IBF8bAemGm5A1Qh7SqIGew7iisCS9jskFE54wa163dF3wCtkRVkB61SYP9qaON6c
wh1x26OCIzNKFFD9cWghIX41/RJo53k8HMfudVsf3F8P4BHxOkK9YiV3J5YpPsrH
ki278Xdpmi8DZa6Pd4uyaltyvmWtEpcZTtCeB0LcYDko8S3KXQj6cg+0j027f+fG
LksUfZKlwxQqL2KoF6NpGRlBB5NnrO7jXMBajYQ8r1GIXYOghlAWIjYshxD/f5AM
HX7djCqzs0AeZKXDqysLF+0yNLhB0YMEcunuKPdi4NTb/ItvAIVgMOiFY7oLDQC6
xBxvQm5Zc3uZfzHiHD9L9FCzkdgHlWLpS+hiTUpgNQ4DF/aIFxuS6lWyYuzC+Svj
DQqX6iFm8V9XvfKulG5lFt25V+SFokcTMyWq4/nUJZ1QB/O4SgVUoWl0+ZUReorP
VvsjVxYk55t+tEWmVQdSjzftFtS1aLgTq7XRWKC9VWik8KjiWg2/3Bwyo3YQ80h6
ck0uxoHnVXNuMgP1jojsZKI0KTRGvuFBLZQ9JWcBzTmBr7q1O6xMZ7OIVBB1uii9
gOmIjD+hAZRmYQ+Ar4lx
=SWvn
-----END PGP SIGNATURE-----

**Comment by mimi89999** [comment]
I would remove all those distros.
Recommended software should be good as is, without the need of modifying and recompiling some parts...

**Comment by alerque** [comment]
@mimi89999 That makes sense if you were recommending a note taking application, but not an operating system. OSes are ecosystems and Linux distros in particular are called _distributions_ because they are just large collections of other bits of software rolled up in a way that works together. As such picking and choosing what parts you use, making config modifications, or choosing to use proprietary drivers or not is something that goes with the territory. There might be other reasons to drop a bunch of distros, but that by itself isn't enough.

Deblobbing a distro that is part of a more developed ecosystem can be a lot less work than trying to get a distro to work that comes deblobbed but doesn't have anything else going for it.

**Comment by Atavic** [comment]
The actual list on the site, under gnu-linux OSes, is almost perfect to me:
just add **Trisquel** GNU/Linux, that's a 100% free operating system.

**Comment by mimi89999** [comment]
@Atavic Trisquel has outdated software in their repos.

**Comment by Atavic** [comment]
Parabola GNU/Linux-libre?

**Comment by strugee** [comment]
@Atavic Parabola is already on the site and Trisquel has already been rejected. Thanks for contributing, but please search for previous issues and check the site before.

**Comment by Atavic** [comment]
Yes, sorry, my fault.

**Comment by yegortimoshenko** [comment]
While firmware loaded by the kernel can be replaced (for example, see OpenFWWF), firmware pre-flashed on a ROM can't be replaced *by user* (but probably can be by manufacturer). In both cases, firmware might be the same, and identically non-free, the way it's uploaded does not change anything.

The reason why we're seeing more hardware that requires firmware is to reduce costs by not having to solder ROM chip onto device.

I would like all hardware and software to be free, and looking forward to RISC-V future as much as the next person, but for the time being, having a proprietary firmware on chip is just as bad, and firmware on ROM can be just as malicious. Unless chip is 100% free hardware, it can't be proven that it is non-reflashable, and more often than not, it's probably is reflashable, it's just the way to reflash it is being kept secret.

And most convenient available hardware as of today is highly proprietary.

I think most people here value contributions made by GNU, but we should also be vigilant and not trust anyone blindly. If someone can argue how not having blobs in the kernel empowers the user, I'd be very interested.
