### ISSUE TITLE
Sandstorm

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1669]
We should probably look into listing Sandstorm: https://sandstorm.io/

Sandstorm makes self-hosting web applications as easy as installing an app from a mobile app store. It's licensed Apache 2.0 and though I haven't looked recently, their security model is generally pretty damn good.

**Comment by Hillside502** [comment]
Also, it is recently out of Beta.

**Comment by hasufell** [comment]
Looks pretty cool, I'll probably test it on my server this week.

**Comment by strugee** [comment]
@hasufell did you get a chance to try it out? Any objections to adding this to the site?

**Comment by hasufell** [comment]
I'll try to do it this weekend

**Comment by strugee** [comment]
:thumbsup: only takes ~5 minutes to install and configure FWIW

**Comment by hasufell** [comment]
I do that in docker containers and I am picky about the details. I don't do stuff like `curl https://install.sandstorm.io | bash`

**Comment by strugee** [comment]
@hasufell me either. I personally do `curl https://install.sandstorm.io > sandstorm-install; less sandstorm-install` and then do `bash sandstorm-install`.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hillside502:
> Also, it is recently out of Beta.

I see this at
https://docs.sandstorm.io/en/latest/using/security-practices/ :

> Beta Notice: As of this writing (April 2016), Sandstorm is in
> beta. Key features allowing a user to easily grant an application
> access to external resources are still in development. In order to
> make Sandstorm more useful to early adopters, we have temporarily
> opened some intentional holes in our confinement model. For
> example, we have allowed outgoing HTTP to arbitrary servers in
> order to permit the TinyTiny RSS app to fetch RSS feeds, and we
> have allowed incoming and outgoing SMTP (with certain restrictions)
> to allow email clients to work. These holes will be closed as soon
> as the Powerbox UI and drivers make them obsolete, but in the
> meantime Sandstorm does not yet implement true confinement.

Should I infer from your comment that this feature is now implemented
since Sandstorm is out of beta?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYjtzAAAoJELPy0WV4bWVwSsYQAN0pAp0ZZ7+/+lN1pJ2yhkGV
qFDBLIp0OWV24UgMsVcK1FeYfv9EA9iBG/sKMXKGLHXBWpBYELrS19HGvKD19pGt
8iBdFUEbdB04YT0sw4XEIfcN+yUONi3iGP4+RR20vtr54GPHkABD8aZdcOcXyRmT
BJqukYMiE6Muy84FnARU1RLT584fJZOsiRXQNKfEfra0z59EoqB79IAhHtFTs9Fk
4shLmy9pAHD7TMpuD7IjJSUvsvusXyApCAHbnOKkWOy0fQJVosIFh66vGrUJj04e
TBtE444pR82l1cleUW+83B1BtR4ABUvo1Fx7ymiD5rr88yyJvaYMt7/hKD7GFPyt
jv79GpxEbX3s8+EVWA5POo2aTgQ6/sxLtOuFF6ygm0wKwGvU9NRuyf8SDb3Ycb5K
f/x56aNRWRO5ngJNQv3oH6NgXC2h5MDeqtJg8gg7D3lyI5pxS0m5bS0MnmaRqpxH
KNaFpiVqAyPMbdT4lBp3wGae/k6JEhXqCBO63ExNFi8heYTdwrW9Lph8Vprvnc/P
rwFIIu33VTpwY2fb+32DOxDA0YH4e26GE7v6NEpRPZ4PHvQUxoH0ribud6qpyyaw
Dv50pV9udRKYSoNyn71z7elA3FuY65PwcA3Ra0qRYP1ZVqzSxjLP5MoH8+QMvti4
UKU7SG7r1TuD3jtnDBND
=WPeb
-----END PGP SIGNATURE-----

**Comment by Hillside502** [comment]
@JeremyRand 
With hindsight, it's the Sandstorm Oasis Hosting service that emerged from beta on 2016-11-27:-
https://sandstorm.io/news/2016-11-17-oasis-emerging-from-beta

I'm not sure about the status (beta or otherwise) of the Sandstorm project as a whole.

**Comment by kentonv** [comment]
Sorry for confusion about beta status. The various "out of beta" announcements are mostly positioned to communicate to enterprise customers that the platform is ready to purchase and use now. From an engineering perspective, there's still lots and lots to do to make the platform "complete".

The Powerbox UI now exists, but we have not yet used it to replace the temporary work-arounds that predated it.

**Comment by strugee** [comment]
That being said I don't think that Sandstorm being in beta is a reason not to list this... even with the workarounds, the security model is still a vast improvement. As is the ease-of-use benefits.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> That being said I don't think that Sandstorm being in beta is a
> reason not to list this... even with the workarounds, the security
> model is still a vast improvement. As is the ease-of-use benefits.

Agreed, the security seems to be better than the status quo.

I notice that it looks like a lot of the apps are fairly outdated
compared to their upstreams.  It's unclear to me whether this is a
problem.  Thoughts on this?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYj/wpAAoJELPy0WV4bWVwjPAP/3BDJXXnUWBWALB/9BDagQlO
1rkS5iuYEIhVhkVhNZ4BOT9FrbD1Gwn1L5EiYHr7rTTVshEOVzFu6Nkc0Oi/ETGh
Vvz1xdheDU33oSqJqO2XK569O9RYgEbvl8G8cdYON6UK0dHf17yYRizAPXC/fSy2
3U1MiG1KLxR/Q/XggYLvp4VAjs98Yk9LaEqRvMR7cnjng6WRmz44CA0e0RlMIfyZ
ViCTulQ0LRUfXa8nys1xbWcumOzweILZkkiv1p6Z2t+fzZyOWcYl0UKSPMQOHDZq
MpbceCkRPU6j6QM1ftsDG+SKxaRXX5qU40mX3bUK9PyXcjgisyWA7ZlD1N7W293F
K3hH8ThAVj1kfsxYW6ea/kj5bTqRr+HJi/8htjEvy+0sYw95r162XgNpCGJEx5oq
uMnqAARABDO5gePAFt4/OOPjXkA5IL3b0DZiAZACQS20TXKojHhsD/p/tDo7E4e+
iQD7YrZKhFLXOu9pjSN8X98HVXHTvclv6/KYRIddRmUj6TuoQ4O1nNa1gYqjg7Hh
kSoGkIFQNnVm3KYwOuz1aZiejZzXsPYMmuFYu1LpouUVGz66OhXTkot2+rymcq9o
pIPmE8XKa0srG+VJkfRzdnvsPGOPkX6QUazl5tZRvJvsk/hfSR2VWqdpzjVdfwlW
M9e+gSDwwv2FIQBCLCZA
=4kHs
-----END PGP SIGNATURE-----

**Comment by Hillside502** [comment]
@JeremyRand 

> ...looks like a lot of the apps are fairly outdated
compared to their upstreams.

Yes, compared to the similar Cloudron
https://cloudron.io/

**Comment by kentonv** [comment]
Most app packages on the Sandstorm app market are maintained by the community, hence the frequency of updates varies widely. The top apps -- Etherpad, Wekan, Rocket.Chat, and Davros -- are updated often, but some of the packages further down the list could use some love.

Note that Sandstorm's security model mitigates most application security bug (see [Sandstorm security non-events](https://docs.sandstorm.io/en/latest/using/security-non-events/)), which solves arguably the biggest problem with outdated apps.

**Comment by hasufell** [comment]
https://docs.sandstorm.io/en/latest/install/#option-6-using-sandstorm-within-docker

Requires `--privileged` for docker containers. What the hell.

**Comment by kentonv** [comment]
@hasufell Yes, because Sandstorm itself is a container engine, but Docker blocks the containerization system calls inside of containers by default, because they've been known to have security bugs in the past. Sorry, there's no way around this. Generally I recommend running Sandstorm on a bare VM rather than in a Docker container since double-containerization is sort of weird.

**Comment by hasufell** [comment]
> Yes, because Sandstorm itself is a container engine, but Docker blocks the containerization system calls inside of containers by default

You can whitelist system calls in docker, see https://github.com/docker/docker/blob/9539c0a4022857f7d317894e24a0694f4b62bbaf/docs/security/seccomp.md
I don't think `--privileged` should appear _anywhere_, except for very special cases (and then "you know what you are doing" applies).

**Comment by kentonv** [comment]
@hasufell I'd be happy to accept a patch narrowing down our Dockerfile to whitelist the specific system calls needed.

**Comment by Hillside502** [comment]
Sandstorm is returning to its community roots - Sandstorm Blog
https://sandstorm.io/news/2017-02-06-sandstorm-returning-to-community-roots

**Comment by strugee** [comment]
@Hillside502 yes. I don't see how that's relevant to the current discussion, though.

**Comment by Hillside502** [comment]
Just for interest, such as their welcoming input from the wider community.

**Comment by Hillside502** [comment]
#1683

**Comment by Hillside502** [comment]
With regards to the similarity with Cloudron, Cloudron's dev @nebulade has just submitted #1683 

Personally, I'd love for @kentonv and @nebulade to share with us a comparison between their respective systems.

**Comment by nebulade** [comment]
@Hillside502 Cloudron is a self-hosting platform for installing web apps. It uses docker in the backend. The focus is on a turnkey web app installation where auth, certs, dns, email configuration, backups etc are all automatically taken care of when installing an app. For example, [git.cloudron.io](https://git.cloudron.io) and [chat.cloudron.io](https://chat.cloudron.io) are both public facing Cloudron apps (you can try a demo at https://my-demo.cloudron.me to get a better idea). 

Differently put, it automates all the things which you as a self-hoster are probably already doing today.

**Comment by strugee** [comment]
@nebulade yes, Sandstorm is similar. I think @Hillside502 was looking for someone to get into the weeds and provide a detailed _comparison_ between the two systems.

**Comment by kentonv** [comment]
The biggest fundamental difference is that Sandstorm is pioneering an idea called "fine-grained containerization": https://sandstorm.io/how-it-works

This is a big rethink of the way server infrastructure is done, with some huge advantages (see the link), but also some huge technical challenges to get working. Ultimately this allows Sandstorm to provide a more integrated experience, mitigate most application security vulnerabilities, automatically scale apps to large numbers of users, start and stop apps as-needed to save resources, automatically implement access control policies needed for things like HIPAA compliance without the developer needing to know anything about it, etc. The down side is that there's a lot of work to do to make it work really well, since it's a new and different way of doing things. Apps also need some modification to work inside Sandstorm, e.g. to delete the app's existing access control mechanism and rely on Sandstorm instead.

Cloudron takes a more conservative approach, by "just" running apps as monolithic multi-tenant servers in Docker containers -- the way most existing apps were designed to be run. This means it is less work to support Cloudron, and there's less engineering work to do in the platform itself, so they are able to deliver a high-quality experience with less overall engineering. However, all the "magic" provided by fine-grained containerization won't happen in this design. Application security vulnerabilities are not easily mitigated, every app has to implement its own access control (with no one implementing things like HIPAA), apps trying to serve a single user probably waste resources, scalability remains a challenge that each app must solve, etc.

**Comment by Hillside502** [comment]
Thanks for that Kenton @kentonv 
In particular, the second paragraph.  Cloudron seems to have a more turnkey approach, but I guess that for this PRISM Break issue, containerization is the main focus.

**Comment by strugee** [comment]
Assuming Cloudron is accepted, I think it'd be okay to list both of them since this category is nonexistant ATM (so we wouldn't be piling onto an already overloaded category) and both seem to have distinct advantages and disadvantages.

**Comment by Hillside502** [comment]
Just for interest:-
Sandstorm gets a security review - Sandstorm Blog
https://sandstorm.io/news/2017-03-02-security-review

**Comment by strugee** [comment]
Barring any last-minute concerns, I'm going to mark this as accepting PRs given that Sandstorm:

1. Meets the inclusion guidelines
2. Is easier to use than manually installing webapps
3. Is more secure than even the norm for competent sysadmins (which PRISM Break users aren't necessarily)
4. Has been audited

If folks have objections, now is the time to speak up.

**Comment by vyp** [comment]
@strugee friendly ping to add label! :smile:

**Comment by strugee** [comment]
@vyp whoops! Thanks lol :D

**Comment by Hillside502** [comment]
@nebulade @kentonv 

Cloudron - Application Status
https://cloudron.io/appstatus.html

New & Updated - Sandstorm App Market
https://apps.sandstorm.io/genre/New%2520%2526%2520Updated

A comparison of the two, now favours Cloudron by a long chalk --- Sandstorm is now on a par with F-Droid for out-of-date apps.

Personally, any concerns about Cloudron running **only** on an Ubuntu platform is moot --- compared to the update state of Sandstorm!

**Comment by strugee** [comment]
@Hillside502 I only just saw this comment, sorry, but I don't think that outdated apps are actually a big problem with Sandstorm because its security model makes most vulnerabilities non-events.

**Comment by Hillside502** [comment]
> its security model makes **most** vulnerabilities non-events

But which vulnerabilities?

Out-of-date apps are a bad sign per se.

**Comment by strugee** [comment]
@Hillside502 vulnerabilities in the packaged apps. See https://docs.sandstorm.io/en/latest/using/security-non-events/

Vulnerabilities in Sandstorm itself are a bigger problem, but the Sandstorm platform is actively maintained.

**Comment by Hillside502** [comment]
Above, I should have linked to:-

Cloudron - Application Status
https://cloudron.io/appstatus.html

Sandstorm App Market
https://apps.sandstorm.io/

Looking at the apps common to both Sandstorm and Cloudron, Sandstorm's are nearly all out-of-date --- **some by 2 years**

This is an absolute joke, if it wasn't a serious matter!

Sandstorm has fallen by the wayside, whereas Cloudron leaps ahead.

The Ubuntu Server issue is an ideologically purist red herring.  Cloudron is the way to go!

**Comment by strugee** [comment]
@Hillside502 did you not listen to what I explained?

**Comment by yegortimoshenko** [comment]
@Hillside502 proposes Cloudron as a better maintained alternative, security is not the only valid concern with badly maintained packages, there is also lack of bug fixes, new features, etc. I don't know anything about how the two compare.
