### ISSUE TITLE
Remove Conversations

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#1680]
https://github.com/siacs/Conversations/issues/2277

enough said. Upstream is incompetent.

**Comment by alerque** [comment]
Ouch, that's actually pretty serious. And I'd agree we shouldn't be listing it here until it's undergone some auditing for similar issues.

**Comment by hasufell** [comment]
To expand on this a little more:

1. conversations.im does it's own thing wrt sending files, which (I think... didn't check all XEPs) isn't standard for XMPP
2. it's counter-intuitive and most users probably won't realize what is going on
3. their possibly private files end up on a server they have _zero_ control over
4. those files are __publicly accessible__ and the only thing restricting access to them is the knowledge of the URL, which can be retrieved with various browser based attacks
5. upstream doesn't care, so we must assume they have no proper model of privacy and security

**Comment by Hillside502** [comment]
@hasufell 
Superb analysis!

**Comment by strugee** [comment]
@hasufell this is 100% standard XMPP. https://xmpp.org/extensions/xep-0363.html

I also don't see an attack, unless the upload server doesn't use TLS in which case you're screwed anyway. I'd be happy to be corrected, though.

**Comment by hasufell** [comment]
@strugee nice catch. I guess this isn't the only file-transfer XEP though... my server doesn't do it. And I'd argue it's the most insecure and centralized method. One has no control over the files ending up on the server

**Comment by hasufell** [comment]
> I also don't see an attack

If you view the url in your web browser, because your client (like mine) doesn't interpret the url automatically, the whole browser attack surface on history including javascript, timing attacks and so on is at the attackers disposal. TLS only helps you against direct MITM attacks.

In addition: the files are __stored__ (not just transferred) on a server you have no control over. That alone is an attack surface (e.g. that server being hacked).

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Presumably AES encryption, even when enabled, doesn't hide the file
size from the upload server.  And the file size is easily sufficient
entropy to fingerprint when a user has uploaded a given file, at least
enough to trigger targeted surveillance if not an actual search warrant.

Am I missing something that makes such an attack infeasible?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYmG9AAAoJELPy0WV4bWVwt9sP/3fCoSQ5qTOLnmB4sqs7r7mU
dZrbKf5GLP5Li9wJXTOJrPKb6/06ODCn4s09lgN+v0UgnLbpdx1hfZwLVDTJC5Hm
tuXEvEH6MJLdP9PKbqdlenUqHpANl2vy5vTf0r6/GC/uzL3w2iQS+vc13P1JOQbi
L39wG9gPVJnywMPWlDsBrKnrKtqfwGa2vqymAS9CxlE1EXBPjg1oYTZ81rt3/o6L
daupFPxJn/JXOwOflcVsADSfrvaTvtL2p7BHPaiP33kXa/CeKewVVSdzPGalcVv2
YQ/yG6j1SjpXUmqKEo2414WGGFIM4NHFOn2nCsoIhbmdBDSQ5saApTR4KGPoYVy7
43pf3DEIcjzBJ9MEzLC2lUjVyHFFiV3lYxGvgwcVr5BTYbuaiR7tZDmVXpHiVR9C
H7akTl7yD/eCbgl01/ObO+7U8VNDPDdiIYko/6JgWEDGr5zemhc1kZbiSqMVHarO
bsRlR0YQE90I3v8w7Dd7xsgH2pfHP6ydrlukTt9+xY/itHXkXR8vljS3j19LqbrO
6r098ifxtGS9fSzoa91btEvJEJNTl/M2Yqmvc7yqpH5D35C2tmYBk/KeNXbrFAJ0
+gmw7e2UBZjeW2BPc3JOf7qubDrUSA3ZB6YAFJXu0Gwq2gDOpLdeAXusiYzW4+/Z
gQaXCQcC/hYVpm0XLBAW
=3PDu
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
@hasufell yeah, I had to explicitly enable this on my ejabberd. (mod_http_upload, IIRC.)

I believe the impetus for this was async file transfers. Previous methods required the recipient to be actively connected to their server. Also, again IIRC, Jingle File Transfers don't work in MUCs.

Agreed that storage on the server is additional attack surface. However I don't get your point about browser attack surface - who is the attacker in this scenario? The server operator, trying to compromise the machine through a security vulnerability?

**Comment by strugee** [comment]
@JeremyRand not sure I understand your description. Are you worried about a publically known file (i.e. a file whose size is known to the whole internet) being transferred and then fingerprinted? I don't think it's useful to consider that case as most file transfer protocols, including legacy Jingle File Transfer, will have that problem.

**Comment by hasufell** [comment]
> However I don't get your point about browser attack surface - who is the attacker in this scenario

I don't understand your question. There have been lots attacks on browser history with varying precision, via java-applets, javascript, CSS snooping and even scriptless DNS timing attacks (which probably only reveal the domain though). The point is: you're now relying on the _browser_ of the user so that your privacy is not compromised. That's a security assumption and a bad one.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> @JeremyRand not sure I understand your description. Are you worried
> about a publically known file (i.e. a file whose size is known to
> the whole internet) being transferred and then fingerprinted? I
> don't think it's useful to consider that case as most file transfer
> protocols, including legacy Jingle File Transfer, will have that
> problem.

I'm considering either (1) a publicly known file, or (2) the same file
being sent by or to multiple people (which will reveal social graph
metadata since it suggests that those various people either know each
other or are the same person).

It's true that most file transfer protocols are fingerprintable to
some extent, but giving that metadata to an external server adds an
extra trusted party who can do that fingerprinting; usually it would
only be people who directly observe network traffic at the time that
the traffic is transmitted, while the server could do this measurement
retroactively.  Also I suspect that file transfer protocols have
enough noise in how they behave that it's at least slightly harder to
fingerprint the file by sniffing their traffic compared to just
looking at the encrypted file on the server.  Still probably doable
for a motivated attacker, but it seems like a bad idea to make the
attack cheaper / more accurate.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYmIIBAAoJELPy0WV4bWVwY5EP/3ntnUKzpV7Z9fIz+oWc4aCc
9nI6JxDE2rKXTd9A49MnA/ILdAjMtm4ymQsl9oFR2o6PF5UCfMQWFRaNxRUSXMgd
H9f1ORnMICXdp3FgIgkVNJlazjqfErMdypzUn2elg08VGUm8+ODO/L2eFRWaD9MC
e0bRW6YRVLmblJBDQlaK4+CVqKNRLmCLEaFqi2FIC8PK7bamrUcXta05yLl8nodQ
QO/+jsWbiLM4MLBf/Yqwcgo5GRhBsYiD/o0OCZ1Gu3Wg5BIlDfhDPSrReK9JEGAV
NGTC74nnfCxa6cSh1Yqq6UL4r8Mc4zGL+6Ur07v8Aj8ElCNDqYAXRGqQ99NcLg+F
DMuSHG6due6LyjP1JTgqQ1LeZo5dvRWJ9d7DcHGef4v6PmBdBt8X/30aJPDtK412
B59ycsJwfeEUNQkcnBJmV26T/MpoCxENGfVuta9MzTL91ky3LVZWVo1PIVj5AK5n
Ty7NM9VWD0CkRdg9jF3rjoBquqGWSu46cOM/tG+y8hlZcpyeM3Ij3Oec9m5dS5nS
fG0bDTN9iwRsnFAU5C9lisF8F0bQyCeartirhOanef+7A6hY7wS2PErT56VKkG2A
i8POaRxOVyTOvfCrsC6l0eqFB8ktnlrHgUiJ9qQqHC/j+di1PRFtdgkza/q2FFBD
adqpxmUjYhoX2cQpTvia
=iI7E
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
@hasufell okay, so IIUC you're worried about a malicious domain being able to get the browser to leak history?

@JeremyRand okay, that makes sense. I will however point out that the social graph only leaks when the file is retrieved (same as legacy Jingle transfer). Also Jingle transfers are sometimes (always?) routed through the server so I'm not convinced the "new external server that can snoop" problem is a compelling design flaw in the HTTP File Upload design.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Alex Jordan:
> Also Jingle transfers are sometimes (always?) routed through the
> server so I'm not convinced the "new external server that can
> snoop" problem is a compelling design flaw in the HTTP File Upload
> design.

Good point.  I do, however, think it's easier to snoop with a server
that stores the data for a while, compared to a server that just
routes data between endpoints but doesn't have a need to store it.

All that said, I'm not going to defend the (apparently broken)
security model of Jingle either.  If I were designing something for
this use case, I'd probably either use OnionShare or something very
similar to it.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYmIobAAoJELPy0WV4bWVwh8gP/iv6pzR0XrDMwGEYs5tqsMyi
IcmYWlr27/Pz3vqI/xC/8UvFSrdUqJZxZypgHSkcy5AKYJGRiTwwq0UIl6dupPS+
1vHgtb50JykmSnYxxgb1BlWiOUBGDfSPcmeW6cHZpGRS6IKJ570GHK9hscdVBdFk
K0n4Qx3/ZtSeWsoONB00Rk+wGI7hyQrQQFmFejq5z50qkY8E7NjlW4YKj1jkfQZ0
6iPVeLBDdTiNRVBckCnPyNCs+h/ecNHRm+Vd45WJF42XLyCWDA97VqIjupGjq8vQ
lYoBnMhBFqcUz7nPNpPX0b8OSrqrNV0hQ0Xc9Kz4DzGhe3w2RPE3zK/HgHh1g7gv
lxSyrpuazXN76ALVpBr519R6Teqyt8g4ZHrxTd6hhE5lolGpYNHdiU7wQvqsAk8i
cxDUAoCt3AGdEalFwD3abLmK68J15OAhUHd1RtNl8DC8Kzo+ZBNQ0U7ljDVXPEW/
UMRFBeWIoveRKylv0xNhbmFxtdwBiA7qMkwERcb2iAgfdAIK3sPqB2ArIhkxgMh1
KElQKMDwuGjHlvgI6QHzzpRvKaPS1Y7NBxXTvWQmjIwm93vyeARhM2+WQ32xzqHL
qrRKyUa02WJJRw+d4tQA5i5hMq9NsK1h+Fh7u3t76zc59fh8oowvRjdW2+Kdz+t0
4SLm3uKhunbBple46AJg
=PoTw
-----END PGP SIGNATURE-----

**Comment by mimi89999** [comment]
The issues you invented aren't real issues. What you are saying is true for any non-e2e encrypted service. If one cares about privacy, one should use OMEMO!

**Comment by moparisthebest** [comment]
This is the same thinking as topics like this:

https://productforums.google.com/forum/#!topic/photos/OqaaIaqgntA

The only incompetent one here is @hasufell for not realizing that long random URLs are the same as long random passwords, and in fact better as most people don't use long random passwords.

And as has been stated above, if you want your files end to end encrypted, maybe flip the end to end encryption checkbox in conversations? 🙄

**Comment by iNPUTmice** [comment]
OP either has very little to no knowledge about XMPP or is a payed troll.

The way Conversations (and many other XMPP nowadays) treat files is completely comparable to how XMPP treats any form of message. Messages will end up on servers. XMPP is not P2P. That's why you either run your own server or use E2EE.

**Comment by Hillside502** [comment]
@iNPUTmice 
What an infantile attitude --- not to mention literacy level --- "payed"!

**Comment by alerque** [comment]
@mimi89999 Nobody is saying anything against using encryption. At least myself and the guys from PRISM-Break in this thread are all coming at this with the assumption that the conversation messaging itself is E2E. If that wasn't the case this whole thing would be moot because there would be a more obvious attack surface.

The problem here is not the messages being transmitted inside the messaging AP it's the data  being passed around OUTSIDE of the app in another channel. That data is not E2E, it's plain data. The issue here is that the sending user inputs some file in a conversation that is E2E that then gets passed around in another back channel that isn't subject to the same encryption, and the receiving end is given a link to retrieve that data not only out of channel but out of software—they are punted to their system default browser to load a publicly accessible resource that is not encrypted the same way as the conversation they just left.

Privacy is only as strong as the weakest link, and in this case the conversation encryption and client is not the problem. The unsecured resource that can be loaded out of channel is. That the resource link is to a SSL domain does little to mitigate the problem. It stops some wire level snooping on the actual data, but it does reveal a good deal of meta data that just the E2E conversation wouldn't have been giving away. But the real problem is the browser—it should never be assumed that the user's browser is a trusted end-point and when you send them out of channel to retrieve a resource that was sent by the far-end in-channel the expectation would be that they also receive it in-channel (in which case the total privacy/security metric would be the conversation client & server). In this scenario you're dragging their system default browser and a different set of connection parameters into the mix.

Honestly the completely dismissive attitude here, lack of engagement with reported problems, and general defensiveness before the problem is even understood has been quite a bit of a turn off. If you all want this project to be taken seriously rather than completely dismissed, at the very least making the effort to engage concerns that get raised and—if  it comes down to a deliberate trade-off—being honest about the choices made and their pros and cons rather than trying to deny that there is any issue would be a good place to start. It may bet that given the usage goals fixing this problem is not on the project's road map, but acknowledging the limitation rather than trying to excuse it would go a lot farther.

**Comment by moparisthebest** [comment]
@alerque You misunderstand *what* is being 'passed around OUTSIDE the app'.  If e2e is enabled, it's simply an aes-256-gcm encrypted blob.

Also how do you define this as 'outside the app'?  Whether it goes through the user's XMPP server protected by TLS or the user's HTTPS server protected by TLS (when both are ran by the same person, on the same server), what's the difference?  None is the correct answer.

**Comment by iNPUTmice** [comment]
> Honestly the completely dismissive attitude here, lack of engagement with reported problems, and general defensiveness before the problem is even understood has been quite a bit of a turn off. If you all want this project to be taken seriously rather than completely dismissed, at the very least making the effort to engage concerns that get raised and—if it comes down to a deliberate trade-off—being honest about the choices made and their pros and cons rather than trying to deny that there is any issue would be a good place to start.

You don't know anything about the Conversations community and it's developers. Your allegations that HTTP file transfer hasn't been considered very, very carefully is completely false.
The first security considerations on using HTTP upload have been discussed again and again ever since the first PR that originally introduced that feature into Conversations over two years ago: https://github.com/siacs/Conversations/pull/428 

Furthermore the security considerations in the HTTP Upload XEP have been very carefully written.
Conversations itself will never display the actual URL. Exporting the URL to a browser is discouraged by the UX.

> Honestly the completely dismissive attitude here, lack of engagement with reported problems

You can not expect someone to explain the same thing over and over again. Reading through past issues or even getting a working knowledge of XMPP would have answered all of OP’s questions.

> defensiveness before the problem is even understood

The claim that the Conversations developers haven't understood the problem is completely untrue.

**Comment by thundergreen** [comment]
I only say : PAYED!

**Comment by strb** [comment]
> Honestly the completely dismissive attitude here, lack of engagement with reported problems, and general defensiveness before the problem is even understood has been quite a bit of a turn off.

Honestly the completely dismissive attitude here ("upstream is incompetent") and general offensiveness ("Conversations breaks users privacy and security") before the technology is even understood (e.g. with E2E enabled, even external payloads *are* encrypted) is qute a bit of a turn off.

You might want to reconsider the way you approach other projects, because this reads to me like you guys decided almost immediately that the Conversations contributors are idiots who don't understand anything, rather than maybe questioning your own assumptions and preconceived notions. Maybe give people the benefit of the doubt if you want to engage them, rather than accusing people of incompetence when it might just be that you have some significant gaps in your understanding of the technologies involved.

**Comment by hasufell** [comment]
@iNPUTmice 

> OP either has very little to no knowledge about XMPP or is a paid troll.
> 

You are right, I don't know all possible XEPs and drafts out there and my own jabber server doesn't implement XEP-0363, but that confusion was already resolved.

> The way Conversations (and many other XMPP nowadays) treat files is completely comparable to how XMPP treats any type of message. Messages will end up on servers. XMPP is not P2P. That's why you either run your own server or use E2EE.

That is wrong. And you are completely misunderstanding the attack pattern. This is not about P2P, this is about __storing__ (not __transferring__) files on a remote server. This is not about "the remote server is bad", this is mainly about browser attack surface, which is getting mixed into the game.

I don't need a browser for XMPP message communication, do I? See the difference?

And now... when a web service (conversations.im) advertises security and __privacy__ but stores loads of user data on their servers without you having any control about the deletion etc... does that make any sense?

@strb  

> Honestly the completely dismissive attitude here ("upstream is incompetent") and general offensiveness ("Conversations breaks users privacy and security") before the technology is even understood (e.g. with E2E enabled, even external payloads are encrypted) is quite a bit of a turn off.

Can you point out what was not understood, except that the broken technology is part of a XEP? Haven't seen a single counter-argument to the presented attack vector. And upstream insta-closing the issue without any serious note about the concerns, which are still technically correct, wasn't particularly nice attitude either.

**Comment by iNPUTmice** [comment]
Text messages are also stored on the server and not just transfered. If you
don't like that either use your own server or use E2EE. Or don't use xmpp.

You have not been able to present a valid attack vector. So an argument on
how that attack vector can be circumvented can not be made.

**Comment by hasufell** [comment]
> You have not been able to present a valid attack vector.

Sure I have... an image upload is passed to a non-conversations client as a plain URL without any note about the implications of opening it. Opening it in your browser can reveal the URL to an attacker depending on your browsers vulnerabilities and sites you are visiting.

**Comment by strb** [comment]
It's been said multiple times already, but you never addressed this point, so I'm not sure if you missed it or feel it doesn't matter, but if you have E2E enabled, the files that are stored on the server are encrypted. If you don't, then there can't really be any expectation of privacy anyway. It's the same as text messages, they also end up in server-side archives.

All I've heard about possible attacks from your side is vague FUD about browser histories, which doesn't really convince me that you have a concrete scenario in mind. If you do, please share it so we have something we can talk about.

**Comment by mimi89999** [comment]
@hasufell Show us a POC.

**Comment by hasufell** [comment]
> the files that are stored on the server are encrypted

doesn't matter when they are publicly accessible via a URL

**Comment by strb** [comment]
> doesn't matter when they are publicly accessible via a URL

So you don't understand, okay. I'll explain then. Here's how it works. The files that you receive when you download them from the server are encrypted. You need a key to decrypt them. The server does not do this for you. Yes, other people can obtain the ciphertext. Now what?

**Comment by mimi89999** [comment]
@hasufell Good luck to decrypt the file without the AES key.

**Comment by hasufell** [comment]
> The files that you receive when you download them from the server are encrypted.

Erm... I can access the URL via any machine and browser. There's no authentication involved.

**Comment by mimi89999** [comment]
@hasufell Open a conversation in Conversations, press on the padlock, choose OMEMO and upload a file. Then see the URL in your other client and try to download a file with your browser and then to open it.

**Comment by strb** [comment]
> Erm... I can access the URL via any machine and browser. There's no authentication involved.

Nobody ever said anything about authentication. I will repeat. Yes, you can download the file. But the file is encrypted. You only get the ciphertext. You still have not addressed this fact.

Note that this is only true for e2e encrypted conversations, e.g. using OMEMO. You may have observed different behavior (i.e. unencrypted files shared via HTTP Upload) in plain text sessions, which is irrelevant to the matter at hand.

**Comment by mimi89999** [comment]
@hasufell
> And upstream insta-closing the issue without any serious note about the concerns, which are still technically correct, wasn't particularly nice attitude either.

The issue is closed, but not locked. You are free to ask any questions under that issue or in the Conversations support MUC.

**Comment by moparisthebest** [comment]
@hasufell 
> Erm... I can access the URL via any machine and browser. There's no authentication involved.

And that is where you are misunderstanding, the 'authentication' is the long random URL, so if I can guess 128 characters to get your URL, I can certainly guess the 16 characters of your password to take over your whole account and access all your past and future history.  What's the problem again?

**Comment by hasufell** [comment]
> Note that this is only true for e2e encrypted conversations, e.g. using OMEMO.

Now I understand. It is __only__ true for OMEMO.

**Comment by moparisthebest** [comment]
@hasufell Not only true for OMEMO, same thing happens on OTR conversations, and with PGP conversations the file is encrypted with PGP before upload.

**Comment by hasufell** [comment]
> same thing happens on OTR conversations

You don't get a working URL when using OTR on a non-Conversations client.

**Comment by moparisthebest** [comment]
Define 'working' ?  You do get a URL the same as OMEMO don't you?  Which works if you use a tool like [this](https://github.com/iNPUTmice/ImageDownloader) or [this](https://github.com/moparisthebest/ImageDownloader) to download/decrypt it.  Only needed for clients that don't support this scheme, gajim/conversations do.

**Comment by strb** [comment]
> With OTR, I just get garbage.

What do you mean by garbage? The message itself doesn't display properly? Or the URL points to something that doesn't display properly?

**Comment by hasufell** [comment]
> Or the URL points to something that doesn't display properly?

`?FILETRANSFERv1:a0016032a09dc653d1d4799320b0ad<omitting the rest>`

**Comment by strb** [comment]
>> Or the URL points to something that doesn't display properly?
> ?FILETRANSFERv1:a0016032a09dc653d1d4799320b0ad<omitting the rest>

Ah, you're right. There was a change a while ago to just not use HTTP Upload at all in OTR sessions, as there is no benefit to using them due to the synchronous nature of OTR. 

Sorry for the confusion about this, OTR isn't really used anymore by most Conversations users, so I guess we forgot that this was changed.

**Comment by mimi89999** [comment]
> Now I understand.

Not a thank you, not a sorry. How much time did InputMICE and others spend explaining that... :disappointed:

**Comment by iNPUTmice** [comment]
To any outsider coming to this thread you need to understand that @hasufell and probably @alerque are paid trolls who are trying to bind valuable resources by having pointless discussions with bogus arguments.
Please read the [Security Considerations in the HTTP Upload XEP](http://xmpp.org/extensions/xep-0363.html#security) and the [security audit of OMEMO and its implementation](https://conversations.im/omemo/). It might also help to read the privacy policies of various XMPP providers. [Example 1](https://account.conversations.im/privacy/), [Example 2](https://jabber.at/p/privacy/).

Don't get irritated by them throwing around random security terms like *CSS snooping*. Those just sound smart but don't apply here.

**Comment by Hillside502** [comment]
@iNPUTmice 

> ...are paid trolls

Childish little twat!

**Comment by hasufell** [comment]
@mimi89999 I was about to say something, but then I changed my mind.

**Comment by thundergreen** [comment]
@hasufell Qhy do you attack a xmpp client when 1. using your OWN server 2. You don't trust 3. U obvioulsy don't get the point between an URL and the content of its file. What is the matter of your encouiraged hunt here ? You might want to put all your energy in implementing Audio and Video Support for Conversationsm and take a good part in the XMPP community instead of giving childish comments based on nothing than guesses. So! Excuse yourself, make an effort and help changing / developing / enhancing / the maybe only mobile XMPP client which has been developed since WhatsApp. And zeah! WA is just a clone of XMPP. Nighty night Kinners und hört auf zu streiten :)

**Comment by mimi89999** [comment]
Whatever... Let's just stop that nice exchange...

@hasufell Are there any other 'issues' with Conversations or can this issue be closed?

**Comment by hasufell** [comment]
@thundergreen 

> 3. U obvioulsy don't get the point between an URL and the content of its file.

Sorry, that's not what the confusion was about and there __was__ confusion. 

The reason this thing became a non-issue isn't even (as you might think) that the files are encrypted, but that the use case of entering the URL into the browser is not an actual use case (at least for OMEMO) since you need one of the linked tools to manually decrypt the file (Still doable by a 3rd party if you have the url... but now the chances the url is leaked is pretty minor. However: __all you need is the url. Nothing else.__ And that was the inital point.).

I'm not sure how you can arrive to the above conclusion if you've actually read the concerns that were brought up.

@mimi89999 no, I think the situation is clear now, although I still think it's suboptimal... it's nothing one can blame the Conversations client or the conversations.im service for. Except that those implications are __not__ obvious to the user (even for non-OMEMO/OTR/PGP conversations). And that one might want to opt-out of that (even without OMEMO/OTR/PGP).

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Travis Burtrum:
> @alerque You misunderstand *what* is being 'passed around OUTSIDE
> the app'.  If e2e is enabled, it's simply an aes-256-gcm encrypted
> blob.

Hi Travis,

AFAICT You haven't addressed my concerns about metadata leaks due to
the file size.  Is the AES encrypted blob padded in order to mitigate
this?

Cheers.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYmWxDAAoJELPy0WV4bWVw42UQAM6pns+XD4CGFX6Q/BpTUvW6
Whd7fWJ6EjxAxlzAK0ZQfvUJJNH8C/8oFMR3KI8pk8a0c5e9E3URVAc4De1lhCwz
U64o132ELzei8lkME8NQsHv71Nye7AkAndQK1wJnL8RvU3dXgIqeeMzKLGIilLCC
mzuE0NPml3O8dWkMAZK9W1QjuQ6/eQTI/U4APQBafrxCxSDAaQ6c3e51KS/uw+F7
gck7fGhh2GC1HeiUEpklMH1YTHiqhZ0eyUvX3NlOLzkwd4TZ2fyJu/JRUC6aVDDG
uqLzVWirgxR/grYGioSWG6l0qGD4B4Oe+pV1+TtddcMoojI0JqgcZLcqubWBSUEZ
DC/HCMqXCUz+WqBLkzskjWZhRdeA/GwCxf0NBbbKUffrnKV9/RcWbOYw215POf5Z
8Tp7uHNuqNa6kLeCcQAWdFQnnDGy5oLIRiBb8up3M4G2jHneTxOA0A3ykyw5xNQ9
tFnnCFncqq290uE+Kq5JIV8X5KxeMzXynZz08B1qj+1tA2c+Bd4AdvmUEyGXfKeB
6TXH79q9yr9/JoTIi1usM6cyKN+s7Vqy8Fw8Hi9clQsS+p0n2cYH3U47ONRZShLs
nEsRaClQs3nnaIl8GyuqZeBiQ8K6QucRAapdJglwcB0HP1SYdH44u6N/2697pD89
mUTbftgVPp0NnVZAgVW3
=cii1
-----END PGP SIGNATURE-----

**Comment by alerque** [comment]
> ... you need to understand that @hasufell and probably @alerque are paid trolls who are trying to bind valuable resources by having pointless discussions with bogus arguments.

Really? This is how you want to approach outside feedback @iNPUTmice? Insta-closure of issues dismissing topics without so much as a link or mention that something is by design and then accusing people you don't even know of being paid trolls?

I don't know what hasufell does for a living but I work as a freelance programmer, often doing network security related consulting. I don't get paid for my contributions to open source projects, much less for any time wasted with projects that don't want to be helped. You can check my online profile, perhaps my Github account and prior involvement in such discussions, [my Twitter](https://twitter.com/CalebMaclennan), my activities on [Stack Exchange](http://stackexchange.com/users/120635/caleb), etc. and determine that I am  not know for trolling.

**Comment by mimi89999** [comment]
@JeremyRand Do you propose to grow all files to 100mb or so to hide original file size?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Michel Le Bihan:
> @JeremyRand Do you propose to grow all files to 100mb or so to hide
> original file size?

I can't imagine why you think I suggested 100 MB.  There's obviously a
tradeoff here; 1-byte precision is a lot of entropy.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYmZTAAAoJELPy0WV4bWVwzFkP/izpfJ8/n/oWK94p9Ri7iN8m
oFqRVXCy6hZbZ1TQEi3yS9c47l8nOlsswzJZMq//DN0+FI/2loMe6JVLP5WLjgaq
yeRGMawvKwVIAjYSqQ2JJ2UD2Gqw8GdZaPaNbPayhK+IXFByJOebYV9zH0znm9h5
bk8fDx+gI/OjkDhTRw5uq4O/Ahn9dGDi5mjc+Q21PE/mClMvaTHuIyzq08qcQMbb
X0eGmtK/i5UjeEWYNnjHmacs4F5DdCeUdFh8FWtzCJ7V9rh4bLJrLOGRRRqdPbt7
PBODCyF5L4ISmwaz26iLRKexNxAkZR9s2mXqm90blVx1ehUCGVxX1+L745xI62aZ
61E1zjDNcfFQdwkErfM3n7N52C1v9FFG/JthK1lbsJloA/ZY+WCE5ppOaKFqFnfs
vpEL1bun84C9qQwlaQRhqr9v5wG16EHM6336oUnnaTV9m3669f/6PGM2S+PLmDWp
R8ibcP99ekvtT14uZKHsGY9SLAFNp95bbqclpLvVPvMyxNy7W1m9mCTqoGAOimBw
cXTebn6UZYwKwMviqgh7Guaj+9S3sF3WfhlWfsc+QLyGNlm9NCnBX5T6SRsMnnPb
lPg8pI3Ub16dvTxczWzp/2gEeZ0FoRo42q/DXETiwPjhyMlZkv69esEIbQ//Dmmp
7022qTVyJ1ye4xZhownL
=aDWd
-----END PGP SIGNATURE-----

**Comment by iNPUTmice** [comment]
> Really? This is how you want to approach outside feedback @iNPUTmice?

@alerque here is the problem. @hasufell did not ask a question! He was not trying to engage with the community to get more information! Instead he imitatively jumped to conclusions and made bogus statements about the security of Conversations. He was also the first one to claim that we are incompetent.

It's a completely different if someone comes to us asking about the URL’s they received from a Conversations users and what they mean or if they are just spreading FUD like: "This means Conversations breaks users privacy and security."

We welcome feedback. But we don't engage with trolls.

**Comment by strugee** [comment]
Hey, all. Glad to see that the confusion here got ironed out, eventually.

Without calling folks out specifically, I'd like to remind everyone of a few things:

1. We're all on the same team. Both the PRISM Break folks and the Conversations people want to see private communication become easy and widespread. Even if we disagree or misunderstand things, we want the same thing.
I see hostility from _both_ sides here, and if - instead of jumping to conclusions - everyone can just take a step back and remember that text-based communication can be misinterpreted that'd be better for everyone. Try to give people the benefit of the doubt, when possible. (Again, I'm talking to people on _both_ sides.)
2. Not sure how much this means, but I can vouch for @hasufell and @alerque - they've consistently been solid contributors to PRISM Break, and are not trolls. You can check my GitHub history to verify that I have a history of decent behavior, and I've spent time in the Conversations MUC working on some Easy XMPP stuff too, if the Conversations people remember (can't blame y'all if you don't).
3. Personal attacks are a violation of PRISM Break's [Code of Conduct][1] and are not acceptable. Attacking things like spelling derails the conversation and doesn't contribute anything to help us reach technical consensus. (Related to this I've removed a particularly offensive gendered slur.)

Thanks, and I'd welcome everyone here to contribute/continue contributing to PRISM Break.

 [1]: http://todogroup.org/opencodeofconduct/#PRISM-Break/abuse@prism-break.org
