### ISSUE TITLE
Column/section for rejected projects

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1686]
I've been thinking for a while that it may be useful to include a column or section for prominent rejected projects that could link to the GitHub issue describing what's wrong with them. Obviously we wouldn't list _all_ rejected projects there, just important ones that we especially want people to avoid. For example, Ubuntu would be there since it's really popular, and Telegram would be there because it's quite popular and their "inventing their own crypto" problem is pretty egregious.

**Comment by alerque** [comment]
This is amusing because yesterday I popped open a new issue tab specifically to propose just this. Yes, I think we need something like this.

Obviously listing all _not_ recommended projects would be impractical, but there are certain things people expect to see and don't that aren't exactly proprietary but don't make the cut either. This would cut down on the number of useless issues we get and make the things we do recommend more meaningful rather than just looking like we're overlooking a bunch of "obvious" software.

This factors into what were were talking about the other day with grading different aspects of each recommendation. Basically this "column" or set of listings is the set that got an **F** for one reason or another.

**Comment by strugee** [comment]
@alerque hah! That's hilarious :D
Cutting down on duplicates is definitely something I was thinking of WRT this. I also worry that people don't realize that the fact that something isn't on PRISM Break means that they shouldn't use it, so they say "well, it's not in the proprietary column," shrug, and use it anyway. (Research shows that people don't notice the absence of indicators.)

**Comment by strugee** [comment]
I think it would look good if we just put these in the same column as proprietary projects. Like so:

![Screenshot of the "Bookmark Sync" section with a grey "Rejected" bar and a couple fake rejected projects under the proprietary bookmark sync product listings](https://cloud.githubusercontent.com/assets/911174/22861071/b8377bce-f0dd-11e6-8ff8-ef0f010f998c.png)

**Comment by Felicis** [comment]
Any updates since February?
