### ISSUE TITLE
Improving project categorization on the site

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1687]
Over in #1672 we were discussing different ways to improve the way that we present recommendations on the site - I'm opening a new issue since I think that discussion is highly related but not equivalent to the "Android suggestions kinda suck" discussion. I won't repeat the suggestions here; just read https://github.com/nylira/prism-break/issues/1672#issuecomment-275694293 and https://github.com/nylira/prism-break/issues/1672#issuecomment-275769841.

I'd love for us to make a decision on this soon, if possible. Then someone can start working on implementing the design.

So, thoughts? Do we think we have the manpower to implement a grading system? (I personally don't think so.) What about the "low"/"medium"/"high" idea? Alternately if anyone has any other ideas they think would improve things, please speak up :)

**Comment by alerque** [comment]
In some ways a grading system that broke the score down into categories would almost be _easier_ to maintain that our current pass/fail system with extensive banter about whether to include something or not. We disagree a lot less on individual data points (has it passed an external audit, is the client open-source, is the server open source, does it use good crypto primitives or roll own, is the UI good, is privacy enabled by default, etc.) than we do on what the sum of those data points _mean_.

**Comment by Atavic** [comment]
High: any Libre or GPL project.
Medium: Firefox for example, as it needs user intervention.
Low: dukgo.com IM as both License and Source Code are unavailable.

**Comment by alerque** [comment]
@Atavic Actually I think that kind or rating system would be just as hard as our current all-or-nothing affair. In fact I think it would stir up more drama and politics surrounding the projects than it would shed light on what people should use.

The sort of graded rating I'm thinking of would have to be broken down into categories to be useful. A "medium" grade doesn't tell anybody more about whether a product is useful for threat model they are evaluating than our current system. On the other hand a "high" in encryption but a "medium" in privacy because of a meta data leak would actually say something useful.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I often find myself looking through the websites of projects listed on
PRISM-Break, to figure out which ones are best for my threat model.  A
categorized rating would make this easier.

> (has it passed an external audit, is the client open-source, is the
> server open source, does it use good crypto primitives or roll own,
> is the UI good, is privacy enabled by default, etc.)

Also worth including: is Tor stream isolation supported, are the
builds reproducible.  (I realize you weren't attempting to give a
complete list, just thought I'd throw in two that I frequently look
for.)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYzbp9AAoJELPy0WV4bWVwvcsP/iiH5nRZmUAQWya9Yi5AsmWU
RW9YjSDi9tofucN5EgdMSqQmsBolJRSOZqqDCqauwuleG9wDqA/X7SDaWedxjIqq
ktjEyOZbz3Rn1PCLWFiGGcOBIpC1nycs0DcWw/x063WUq+hMooejx/idrMrLn3bp
mcSmirRu+Qin7N8ItTjEoF+9Y7dyY2LQC1R6KlyT8C0TADFDv9FruR1oXnbj96ls
hjN0+YFIp/qq65erfDzVe57VEBvhfU9Rzb64TKfPGahWWeRFrx1sCX/Q6pqhASk3
jUKGCH0r+XFJ5x6VMaVUwEzZ3cnY3CSGRtgPcYogXhPXFyUGAoT6Wf5MaGupACgY
Vnp52C9FLUBBPrc0puBBZZhs1xDbiARvFEwGPIsqOLgx5l1XDSqPGigjW20BtlKt
baJQBSwc0B4uJMMx5ygywAAXhM78qOiR9hOJKvBqGxsSzZ+Kbq8c86mSgJVC6CsF
5B6YnxDkKxGUiB7b+YxMcLfAvIlTjBr0KN3i+basi9Q44WOm+I2zRtutkRl7pKG7
eXkurKLQ/63PAGpRcNdI83U9TNf0jar9dZBzBtBEB57CvKPvn0Wy7urHCh0Gejiq
tU/5KrnsprgjCAkGAkUpr5MrYj4Yc74VvKTOakRsJGM4vtKReKSGnW0XeyPm0VMJ
MRcZx2e0iUfQvefXG1GO
=pDta
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
Ugh, this dropped off my radar somehow. Sorry.

Thinking about this more I think @alerque is right - maintaining a grading system would be more work, but would take much less time since most grades are pretty uncontroversial. I'd still like to try out the high/medium/low approach however, with the caveat that that rating will slow things down.

So, here's my proposal: let's try the grading system proposal for now. That shouldn't be super hard to do, given that most decisions are relatively uncontroversial. After we've had that in place for a while we can revisit the high/medium/low approach and evaluate if we have time, whether it's even necessary, etc., as well as evaluating whether the grading system is improving things, how the workload is, etc.

Thoughts?

**Comment by yegortimoshenko** [comment]
I'm against a grading system, it would necessarily cause a lot of conflict in the project because grade is much more subjective than inclusion of the software. 

Additionally, there are no people in the project that can knowingly grade security/privacy aspects of most of software on the list, especially self-hosted software.

It also might reduce quality of the suggestions significantly, if we lower inclusion criteria significantly to include a lot of "low" items. That would decrease the value of having a list immensely.

Also, scores don't really tell anything. If some application leaks metadata, we should say about it in notes. I agree we should improve notes, and tell about leaks and potential attack vectors and so on. That would be much more useful.

Also, scores would create an impression that we make apple-to-apple comparison in the same category, i.e. that high grade software is better than medium grade software, even though our categories are very loose and include non-orthogonal products that are not direct replacements of each other. For example, applying this system would probably cause Qubes to have a high grade and Debian a medium grade.

I would like to change context a little bit: I can't imagine myself suggesting some software or service to a friend, telling them "I suggest F-Droid with a low grade, I suggest Tor Browser with a high grade, I suggest Firefox with a medium grade". If there are specific concerns, I would tell them in detail what they are.

**Comment by alerque** [comment]
@yegortimoshenko I agree pretty much across the board with your objection points, just not your conclusion. Maybe we are envisioning something quite as far what a "grading system" even is. I wouldn't see this as a score card with a final grade shown for each item (as in your final example in a different context) but more like an expansion of the badge system we already have that would help people evaluate recommendations against their threat model.  This might even look more like a list of pros and cons where the end user is still expected to make the final evaluation after seeing all the relevant points. 

Examples might include things like (but not exactly):

* ✔  Multiple 3rd party security audits with no serious issues.
* ✔  Avoids most state censorship issues using domain fronting. 
* ✔  Deterministic build system makes installed software easier to verify.
* ✘ Requires rooted Android device.
* ✘ Relies on discovery server hosted in the US.
