### ISSUE TITLE
Add Sware Iron

### ISSUE THREAD

**Issue by eloydegen** [nylira/prism-break#169]
Some people would probably prefer a Chrome based browsed, because of the plug-ins or the performance.

**Comment by mastercoms** [comment]
#1311 Iridium browser.

Also, just as a note, Chromium downloads a binary blob unconditionally: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786909. Just another obstacle to getting it on prism break.

**Comment by mastercoms** [comment]
The binary blob no longer automatically downloads.

**Comment by msx** [comment]
Hi all,
PaleMoon should definitely be on the list; project's lead as well its community are though defenders of privacy and surfing freedom -- they even decided to *not* include WebRTC because the privacy issues and potential security issues involved.

**Comment by alerque** [comment]
@msx This issue is for discussion of Sware Iron, not Palemoon. Please see issue #1385 and review the discussion to date and then comment there if you have something to add.

**Comment by gothmog123** [comment]
Brave browser? It's chromium based.

**Comment by alerque** [comment]
@gothmog123 Brave is a good potential candidate for PRISM-Break, but this issue is not the place for it. A new issue should be opened with that suggestion and some background on the project and why it's an appropriate recommendation. In the mean time this issue was about Sware Iron and should be left alone unless something changes in regard to that project.

**Comment by aznakh** [comment]
Hello,

I am rather new to this. Are the default KDE browsers, konqueror and rekonq, safe for my privacy, and should they be added to prism-break ?

Thanks

**Comment by alsk23** [comment]
@aznakh Please see the comment *exactly* above yours. Don't discuss other browsers in this thread.

**Comment by awilfox** [comment]
I'd like to note that no extension can block QUIC requests from Chromium, at least the last time I audited it.  Since Google is migrating a lot of their privacy-busting requests to QUIC it's probably not ever going to be secure to use Chromium-based browsers.

If it helps: last I checked, RLZ tracking is present in binary builds of Chromium, but not enabled by default in source builds.  This is why most forks probably won't have it.

**Comment by yegortimoshenko** [comment]
This has been moved over to https://gitlab.com/prism-break/prism-break/issues/169.

**Comment by Hillside502** [comment]
QUIC - Wikipedia
https://en.wikipedia.org/wiki/QUIC

RLZ - Wikipedia
https://en.wikipedia.org/wiki/Google_Chrome#User_tracking

**Comment by alerque** [comment]
@Hillside502 and @awilfox lets keep discussion on this at one place. The canonical location for issue discussion is now Gitlab. Can we please lock this issue?

**Comment by awilfox** [comment]
I followed a link from the site to this issue, but I haven't said anything since the move was noted.  I don't need to be @'d.
