### ISSUE TITLE
Clean up OS section

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#1709]
IMO, the OS section is overloaded which makes it harder to recommend more interesting approaches that are actually security relevant like https://github.com/nylira/prism-break/issues/1703

I'd suggest to:
1. remove all esoteric occurences that are hard to maintain or just not fit for regular users
2. focus on large distros, not small forks that play around with a few packages and licenses
3. keep one big rpm-distro and one deb-distro and one *BSD

For example, __remove__ the following:
* Fedora and CentOS (keep OpenSUSE instead)
* gNewSense (it's debian anyway)
* OpenBSD and NetBSD (not fit for regular users, FreeBSD is more appropriate there)
* DragonFly BSD (we have FreeBSD already)
* Parabola and ArchLinux (I don't see how those are security relevant and they're not one of the really big distros)
* Gentoo (big and active, but not fit for regular users)
* Scientific Linux (small distro afaik, security relevance?)

Then there are weird things like SME Server and Yunohost. Misconfigured (aka preconfigured) servers should probably not be recommended?

I also feel server-specific stuff like AntiPrism and ArkOS are a little bit misplaced. I'd rather add another section _Operating Systems (Servers)_ like for live and mobile systems.

**Comment by strugee** [comment]
In general I'm very much :thumbsup: on this. Some specific questions follow.

> Fedora and CentOS (keep OpenSUSE instead)

AFAIK Fedora has a stronger commitment to software freedom than OpenSUSE, though admittedly I haven't checked in a long while. Is that not correct?

> gNewSense (it's debian anyway)

I agree it doesn't make sense to list both gNewSense _and_ Debian, but I'm not sure how I feel about leaving Debian as-is since we don't have a note or anything about disabling contrib and non-free

> OpenBSD and NetBSD (not fit for regular users, FreeBSD is more appropriate there)

OpenBSD seems to have _some_ value as an operating system for people who need security that goes above and beyond the rest of the list, so I vote to keep that. NetBSD and DragonflyBSD don't seem to be there for any particular reason, though.

> Then there are weird things like SME Server and Yunohost. Misconfigured (aka preconfigured) servers should probably not be recommended?

This probably merits a longer discussion - can you file a new issue?

:thumbsup: on the "server OS" bit. It might make sense to move CentOS in that section too, and add Debian, as more "traditional" server systems (as opposed to "managed" systems like ArkOS).

**Comment by hasufell** [comment]
> AFAIK Fedora has a stronger commitment to software freedom than OpenSUSE, though admittedly I haven't checked in a long while. Is that not correct?

I don't know about that. Picking OpenSUSE is rather a subjective feeling about professionality and community strength. I think both are equally recommendable.

> OpenBSD seems to have some value as an operating system for people who need security that goes above and beyond the rest of the list, so I vote to keep that. NetBSD and DragonflyBSD don't seem to be there for any particular reason, though.

I highly doubt that people stumble across OpenBSD over prism-break (and even less that being the reason they really try it and don't just stop at the complicated installation stage). It's not an OS for the masses. And as I've said before, I don't buy the "we do code-review on our packages". The OpenSSL desaster hit OpenBSD as well, so where was the code review there? They started code review __after__ the heartbleed incident. So to me, this is just a very conservative *BSD system with low usability for regular users. Everyone else using it knows what they are doing.

My reasoning is similar for Gentoo. Not your regular thing and low usability.

However, I can understand that people __expect__ OpenBSD to be listed on a site like prism-break. But... we're not about completeness, are we? We want to pick the best one suited. FreeBSD has, for a *BSD, pretty high usability and probably the largest community.

But I don't have a very strong opinion on it, I just think it's a waste of a "slot".

> on the "server OS" bit. It might make sense to move CentOS in that section too, and add Debian, as more "traditional" server systems (as opposed to "managed" systems like ArkOS).

I feel like double-listing distros on the server section isn't that useful. Every major linux distro can (and is) used as a server system, including OpenSUSE, Fedora, Gentoo, ...
My idea about this section was rather specially-tailored stuff in addition to regular linux distros. Not 100% sure myself if that makes sense, but I feel the current list is a bit confusing and the `Server` tag too (because it pretty much applies to all of them).

**Comment by strugee** [comment]
General note:

So there hasn't been any activity on this issue in a while. Seems like there are some things still unresolved but there are definitely some action items that we generally agree on and can take care of.

Therefore, marking as accepting PRs to remove any of the following:

* CentOS
* gNewSense
* NetBSD
* DragonFly BSD
* Parabola
* ArchLinux
* Gentoo
* Scientific Linux

---

Specific responses:

(Sorry for the delay in responding to this.)

> I feel like double-listing distros on the server section isn't that useful. Every major linux distro can (and is) used as a server system, including OpenSUSE, Fedora, Gentoo, ...

Sure, but some people won't look at the "operating systems" section, they'll just jump straight to the servers section. Or be linked directly there.

> I don't know about that. Picking OpenSUSE is rather a subjective feeling about professionality and community strength. I think both are equally recommendable.

Looks like openSUSE ships proprietary software in official repos: https://en.opensuse.org/Package_repositories#Official_Repositories

Fedora on the other hand forbids all proprietary packages with the exception of firmware: https://fedoraproject.org/wiki/Forbidden_items

Objections to removing openSUSE instead of Fedora?

**Comment by hasufell** [comment]
> Looks like openSUSE ships proprietary software in official repos: https://en.opensuse.org/Package_repositories#Official_Repositories

Where's the difference to debian? The repositories are strictly separated and users can run a free software system just like the can run a non-free software system.

**Comment by strugee** [comment]
> Where's the difference to debian? The repositories are strictly separated and users can run a free software system just like the can run a non-free software system.

My impression is that we're listing Debian instead of gNewSense because Debian has a much bigger community and is much more well-known. To me openSUSE and Fedora fit that criteria equally, so it makes sense that we'd then pick the one that doesn't ship proprietary stuff in their repos.

**Comment by hasufell** [comment]
> To me openSUSE and Fedora fit that criteria equally, so it makes sense that we'd then pick the one that doesn't ship proprietary stuff in their repos

I disagree on your reasoning. It sounds a little bit like handholding and could even be considered a disadvantage in terms of adoptions for users who are not "there" (no proprietary drivers/apps) yet.

I myself don't think a good distro consists only of opensource software, but makes using opensource software __exclusively__ very easy. So to me community strength, CI, quality and professionalism are more important than "oh, they ship proprietary software in repositories you can easily disable".

But I don't see a point in over-arguing this.

**Comment by strugee** [comment]
> I disagree on your reasoning. It sounds a little bit like handholding and could even be considered a disadvantage in terms of adoptions for users who are not "there" (no proprietary drivers/apps) yet.

Okay, so you're saying using a distribution that ships proprietary software makes it easier to "transition"?

I can definitely see that argument and I'd support that. If we're going down this road though, we should revisit the inclusion criteria to make this reasoning clear.

**Comment by hasufell** [comment]
> Okay, so you're saying using a distribution that ships proprietary software makes it easier to "transition"?

In a sense yes. But I rather have a problem with preferring one distro over another based on the existence of proprietary software in their repositories. That's an argument I've only heard from hardcore "free software" people who argue that it's unethical to make proprietary software easy to use and think it should be made hard or impossible.

The important bit is if a user can run an opensource system easily, there are different approaches to that:
* there is no proprietary software in the repositories
* there is proprietary software in strictly separated repositories, which you can disable
* proprietary software is mixed into the repositories, but you can tell the PM based on e.g. a LICENSE variable what to allow (see gentoo)

All are fine and none is to be preferred imo, but at least one should apply.

**Comment by strugee** [comment]
Gotcha. I can get behind that. I still think we should reflect that in the inclusion criteria. Not sure what the best way to do that is, though, without opening ourselves up to people trying to push through things that really shouldn't be there.

**Comment by vyp** [comment]
> AFAIK Fedora has a stronger commitment to software freedom than OpenSUSE, though admittedly I haven't checked in a long while. Is that not correct?

In my understanding they do. :+1: (though I also haven't checked in a long while)

I mostly agree with @hasufell's statements about how easy it is to access nonfree software shouldn't really be a preference point for one distro over another as long as it can be disabled/avoided in some form. But I'm still more comfortable with recommending fedora over opensuse because of it's "stronger commitment to software freedom" and community. Though again I haven't used either distro in years so times may have changed. /2c

@hasufell Thanks for opening this issue though, much needed in my opinion! :+1:

**Comment by hasufell** [comment]
We have a comment for debian saying

**Comment by vyp** [comment]
Good catch @hasufell :+1:, opened #1800.

**Comment by yegortimoshenko** [comment]
> OpenBSD and NetBSD (not fit for regular users, FreeBSD is more appropriate there)

This is not true, OpenBSD is much more usable than FreeBSD. You should try to install both on a ThinkPad and see which one properly works out of the box. Also, unlike FreeBSD, OpenBSD is very friendly to our cause.

**Comment by strugee** [comment]
File a new bug.

**Comment by yegortimoshenko** [comment]
No need: OpenBSD is still listed on PRISM Break. But if someone rediscovers this bug and proposes to remove OpenBSD, they would perhaps consider my comment on that.
