### ISSUE TITLE
FYI: Comodo FW prior to version 6 in Vault 7 leaks.

### ISSUE THREAD

**Issue by Atavic** [nylira/prism-break#1715]
Wikileaks released CIA Vault 7 internal pages, one interesting page is
[Comodo 6.X Gaping Hole of DOOM](https://wikileaks.org/ciav7p1/cms/page_5341272.html):

>Comodo literally catches everything until you tell it not to, including standard windows services ...at least, that's what happens on Comodo 5.X. 
Comodo 6.X doesn't catch nearly as much stuff.  Comodo's user base, paranoids that they are, has apparently caught wind of this and lots of them haven't upgraded to 6.X.

I can't see any software firewall listed on prism break.

**Comment by strugee** [comment]
What is Comodo? I only know Comodo the CA.

Sounds like it's a Windows antivirus?

**Comment by Hillside502** [comment]
Comodo Internet Security - Wikipedia, the free encyclopedia
https://en.wikipedia.org/wiki/Comodo_Internet_Security

Vault 7 - Wikipedia, the free encyclopedia
https://en.wikipedia.org/wiki/Vault_7

+"vault 7" +comodo --- DuckDuckGo
https://duckduckgo.com/

**Comment by Atavic** [comment]
Comodo Firewall component (ver. 5.X), you can extract it from the huge CIS install with 7zip.

**Comment by Zegnat** [comment]
PRISM Break doesn’t include antivirus or firewall solutions because generally they are offline applications and do not distribute personal identifiable information about you (unless you opt-in to some sort of analytics sharing scheme). In other words, they aren’t really part of the threat model PRISM Break is targeting.

As far as newsworthiness goes, this is interesting, but it doesn’t actually contain anything that requires a PRISM Break update, as far as I have seen.

**Comment by hrsyvg** [comment]
Should I tell you that antivirus programs are safe from here? (Avg, avira, bitdefender, etc.)

**Comment by Atavic** [comment]
@Zegnat Most AV solutions include a lot of shared info that goes well beyond needed data like file hashes. Most of the recent antivirus have some 'cloud' integration.

**Comment by hrsyvg** [comment]
So should not I use it? If so, which ones do you recommend?

**Comment by Atavic** [comment]
Go to [Wilders Security](https://www.wilderssecurity.com/categories/security-products.30/) for discussions about it.

**Comment by strugee** [comment]
PRISM Break does not recommend an antivirus because if you use our recommendations for Linux distributions properly, you mostly shouldn't _need_ an antivirus.

In addition to that because you shouldn't really need an antivirus there aren't a lot of antivirus projects for Linux. Mostly just ClamAV. We're not going to recommend an antivirus that runs only on Windows.
