### ISSUE TITLE
Add Mailcow

### ISSUE THREAD

**Issue by ignitedPotato** [nylira/prism-break#1734]
Fully featured mail server comparable to iRedMail: https://github.com/mailcow/mailcow-dockerized

**Comment by strugee** [comment]
Project has no license which is an automatic disqualifier.

Filed mailcow/mailcow-dockerized#289 about this issue. I'm closing this to keep our issue tracker tidy but if that's resolved, I'll reopen.

**Comment by Hillside502** [comment]
#https://github.com/mailcow/mailcow-dockerized/issues/289#issuecomment-302329000

**Comment by andryyy** [comment]
Sorry, I was about to add it and just referred to the license of the "standard mailcow" when asked.

Background: I prefer having a list of licenses used by the software mailcow installs, as mailcow is just an installer (kind of) with a web UI. I don't really care about what you do with mailcow, as long as you keep sharing your changes with the community.

**Comment by Braintelligence** [comment]
@strugee Thanks for considering :) More people should evaluate using their own mail server. 👍

**Comment by hasufell** [comment]
> Thanks for considering :) More people should evaluate using their own mail server.

Running a potentially misconfigured and vulnerable mail server without understanding the underlying technology/software can be more dangerous than using a properly centralized hosted one. I think we should be more wary about such solutions. A mail server is not an app you install. You have to know some stuff about it, including how to react to attacks. The convenience of these dockerized things may also give a wrong feeling to regular users about how difficult it is to do things correctly.

These dockerized things are great for server admins who know postfix, dovecot, nginx and so on and want to automate or abstract away some of their work. Recommending this to regular users though is definitely wrong in my opinion.

**Comment by Braintelligence** [comment]
It's one thing setting up everything from scratch without any knowledge and another thing running an app that was preconfigured by people with knowledge and having a place to discuss issues IMO. Using a centralized solution can be vulnerable to hackers, too, but even moreso to governmental requests of your mails for example. 

Just remember what happened to Lavabit.

**Comment by hasufell** [comment]
> and another thing running an app that was preconfigured by people with knowledge and having a place to discuss issues IMO

That's exactly the problem. The guy hosting the server has to have that knowledge too. That also includes basic knowledge about the protocols, common problems and so on. An apperized mail server doesn't help with that, nor does it encourage to achieve that knowledge.

**Comment by Braintelligence** [comment]
Yeah you truly have to have at least basic knowledge of how to set up a generic server and have an idea of how mail and web related protocols work. It is a help for people who aren't experts in setting up dovecot/rspamd/clamav/sogo etc. though. Especially because of the preconfiguration by experienced devs. 

Blindly following install instructions without reading up on what you're doing will give you a false feeling of comfort or safety. I'm with you on that point.

**Comment by andryyy** [comment]
"Running a potentially misconfigured and vulnerable mail server without understanding the underlying technology/software can be more dangerous than using a properly centralized hosted one. I think we should be more wary about such solutions. A mail server is not an app you install."

I'm curious why people still think this way. Mail server == potential spam machine. 

Misconfiguration is potentially dangerous for _every single server software_.

Docker makes many things more complicated for regular users, but we profit from the same software base on all machines. It is not to make it appear more simple (or whatever you meant).

Postfix has a lot of mechanisms to prevent open relays nowadays. You actually need to mess with a lot of parameters to create a spam machine. I think it is more dangerous to run outdated software on a public machine. 
But that's whatever is stuck to some people's minds: complicated and dangerous. This is just wrong.

I don't want to say everyone should run their own mail server! Don't get me wrong. There is a lot of basic knowledge you should have before booting a mailcow. But it is by far easier and not even remotely as dangerous as you want it to be.

A lot of people install mailcow on machines in networks with bad reputation. Or they don't know how to setup a correct DKIM record in their DNS. 
These are the real concerns. And the worst thing to happen is, that their mail will be rejected/flagged.

I am fine with whatever your decision will be. Just don't patronize solutions like mailcow. Or call it "anything but open" (I still don't get this anyway).
It may not fit on your list, but it is not satanic and evil. mailcow loves you.

**Comment by hasufell** [comment]
> Misconfiguration is potentially dangerous for every single server software.

Exactly my point. I wasn't limiting this to mailcow, nor did I patronize anything, nor did I say docker is bad. But "apperizing" server software for an incompetent audience IS dangerous. Which is why I'm not sure I'd recommend e.g. docker to anyone who doesn't already know what it is. And docker has downsides too (a lot), so it's not a silver bullet.

> I think it is more dangerous to run outdated software on a public machine.

Docker alone doesn't implement a sane configuration or update workflow. That's something people still have to do by themselves. My experience is that people barely touch running containers as long as they run, because they also don't know how to fix issues after an image update. And those things happen.

> But that's whatever is stuck to some people's minds: complicated and dangerous. This is just wrong.

I was referring to the mindset of "hey, I can install a mail server like an app, but I have no idea what it actually does". This is why I'd rather avoid recommending pre-configured stuff like that and just tell people to read up on the technology.

> But it is by far easier and not even remotely as dangerous as you want it to be.

I disagree. P2P systems like pybitmessage might be more appropriate for the masses.

> Just don't patronize solutions like mailcow. Or call it "anything but open" (I still don't get this anyway).

At least I did not do any of those things. I use a dockerized mail-server myself.

**Comment by andryyy** [comment]
I just today checked prism-break.org and can confirm this may not be the correct project for it.

If you are fine I will add a link to prism-break.org on mailcow.email, that's some good work you are doing.

**Comment by ignitedPotato** [comment]
What about iRedMail, IndiMail and Kolab in the [Mail Server category](https://prism-break.org/en/all/#mail-servers) then? I think Mailcow would fit just right.

PRISM-Breaks readme also states "Ease of use, stability, and performance matter."

I see that there are problems with letting inexperienced users host their own complex mail server but I think as long as they keep an eye on it and update it once in a while it's still a massive improvement over common services like gmail. PRISM-Break should at least offer Mailcow so users can figure out for themselves if they're able and willing to use it.

**Comment by hasufell** [comment]
> it's still a massive improvement over common services like gmail

That's an unfair argument. No one compared this with gmail. You may compare it with Kolab or Posteo. Administering a server isn't something you learn by skimming through prism-break and then trying to use an even more complex container system on top in order to run a mail-server that consists of 12 containers. That's a huge technology stack. And it starts by learning docker (which is not as trivial as you may think).

I'd really prefer for prism-break not to become a list of docker images.

**Comment by Braintelligence** [comment]
Well, if Kolab is listed there I see no reason to not include mailcow. In fact I wonder how Kolab made it into the list after the points being made here. 

I've set up both and Kolab is so badly documented and hard to maintain and to update for "casual" admins IMO, that mailcow really has the advantage in terms of safety through easy updates and a great community IMO.

**Comment by andryyy** [comment]
"I'd really prefer for prism-break not to become a list of docker images."

That's just wrong. mailcow is not a Docker image. I don't think you get what mailcow really is. :-/ It runs applications inside containers to have the same base of software on every mailcow instance. This is not about Docker images. mailcow isn't even "a Docker image". It bundles multiple applications to a mail server. Just like, guess what, iRedMail etc.

**Comment by Braintelligence** [comment]
>That's a huge technology stack

It was easier and faster for me to read up on docker, docker-compose and rancher to have a basic grasp of what I'm doing there than setting up Kolab step by step after their installation guide. 

The time it took to update Kolab three versions upwards was so immense because of no documented update path and missing software packages not available on their servers anymore, that it took me longer to fix all bugs by trying to update myself directly than to read and understand a lot of mailcow's code AND update mailcow. I did both, I experienced both from installation over usage and problems up to PITAs and their solution. 

Maybe it's just me, but comparing Kolab and mailcow and saying the latter is not trivial to maintain for inexperienced users while the first one is or is more easier to maintain to me is just bullocks.

**Comment by hasufell** [comment]
> That's just wrong. mailcow is not a Docker image. I don't think you get what mailcow really is

You misread what I said really. Please read carefully.

**Comment by hasufell** [comment]
> Well, if Kolab is listed there I see no reason to not include mailcow. In fact I wonder how Kolab made it into the list after the points being made here.

I have no particular experience with Kolab and I have voiced concern about ALL pre-configured server stuff in other threads. So I don't agree or disagree on that.

**Comment by strugee** [comment]
Reopening since there's a license now :)

It appears to me that the only big problem with Mailcow is the fact that it's preconfigured. I'm not really sure how I feel about that, to be honest. I see good points on both sides.

@Braintelligence if Kolab really is that problematic, I would definitely encourage you to file an issue. FWIW that recommendation is quite old, IIRC.

**Comment by andryyy** [comment]
"I'd really prefer for prism-break not to become a list of docker images."

You said this.

There is a bunch of servers listed there (not only mail). All of these have potential to be dangerous. Some of them hat serious issues in the past.

And preconfigured Docker is not an argument. 12 containers is not a huge stack. It is just 12 programs. You should know that Docker is not a virtual environment. It is intended to be one app per container. 

Didn't you say that you have a Docker mail stack up and running? In a single container then? That would be totally against what Docker is made for. But I actually don't know your stack, so...

As long as there is Kolab and iRedMail, there is no reason to not add mailcow. And an outdated mind like "mail servers are dangerous" is just.. well.. 

But it is up to strugee after all. I would love to see mailcow listed. ;)

**Comment by hasufell** [comment]
> You said this.

Yes and you misinterpreted.

> There is a bunch of servers listed there (not only mail). All of these have potential to be dangerous. Some of them hat serious issues in the past.

That's orthogonal to the point I made.

> And preconfigured Docker is not an argument.

It is. I've explained that here.

> 12 containers is not a huge stack. It is just 12 programs.

The argument was not so much about the amount of containers. It's about all the programs + docker + docker-compose. And the fact that it includes a lot more functionality than just a plain mail server with postfix and dovecot. I didn't say that's bad, I just said that's a huge technology stack... and it is.

> You should know that Docker is not a virtual environment.

You are coming off as arrogant now.

> Didn't you say that you have a Docker mail stack up and running? In a single container then? That would be totally against what Docker is made for. But I actually don't know your stack, so...

Uhm. Whatever.

**Comment by andryyy** [comment]
Don't know how one can misinterpret what you are literally saying.

Don't want to sound arrogant, though, sorry. ;)

**Comment by hasufell** [comment]
> Don't know how one can misinterpret what you are literally saying.

Ok, one more time for you

`I'd really prefer for prism-break not to become a list of docker images.` != `mailcow is one docker image`

Got it?

**Comment by andryyy** [comment]
So it is multiple Docker images? You need multiple apps for a mail server. I hope you know that. I still hope you don't force a mail server in a single container. But do whatever you want, you seem to know best. ;) I don't argue with you anymore, I don't see that going anywhere.

**Comment by ignitedPotato** [comment]
Let's keep it constructive guys.. 

> It appears to me that the only big problem with Mailcow is the fact that it's preconfigured.
Don't we have the same issue with iRedMail and everything in the "Mail Server" category? The iRedMail website e.g. states: "Our product does all the major tasks for you."

I think there are only two possible solutions here:
1. We add Mailcow
2. We remove the whole "Mail Server" category

**Comment by hasufell** [comment]
@andryyy your trolling and arrogant behavior is really annyoing. I didn't say _anything_ negative about mailcow, yet you go into defensive mode and read stuff into what I said that is not there and then go into smart ass mode. I was actually considering to check out the mailcow stack, but I doubt I will want to contribute there.

> We remove the whole "Mail Server" category

Depends. If it's a __service__ that provides you with limited configuration on top then that's a different thing. If it's something you have to setup and maintain yourself, then I vote for removing those.

We've made a lot of (partly weird) decisions in the past based on the perceived/expected audience of prism-break. I had a lot of problems with this policy (remember the "remove all windows suggestions" thread). But now that we have this policy, we should follow it consistently. And based on my experience in the docker community, it is very common to fire up stuff people have really zero knowledge about.

**Comment by andryyy** [comment]
@hasufell, I asked you to stop, you just became very aggressive. ¯\_(ツ)_/¯

@strugee I will check back once in a while about your decision. Added a link to support your project. With or without mailcow.

Btw: iRedMail even offers a dockerized solution. But my intention is _not_ to have anything removed. I eeven prefer stopping this discussion, keep mailcow out and iRedMail and Kolab in.

**Comment by hasufell** [comment]
> I asked you to stop, you just became very aggressive

No you didn't. And I didn't become aggressive. I'm just telling you that you are acting emotional and thus have derailed the discussion while ignoring the technical arguments about the problem we are having here, which is not about mailcow itself. You are projecting things, because you don't understand the prism-break project and the concerns I am voicing.

**Comment by ignitedPotato** [comment]
**Moving on**, back to topic:
I vote for keeping everything in the Mail Server category and also for adding Mailcow. I host a Mailcow instance myself without in depth knowledge about **all** different parts. I'm well aware that this is a risk but I enjoy being able to host a complete mail server stack without the hassle of reading **everything** up.

I agree that no one should blindly fire up docker images but Mailcow is a well documented and well structured set of images. You won't get it running until you learn how to configure your DNS, too so at least some experience is needed.

**Comment by hasufell** [comment]
> I vote for keeping everything in the Mail Server category and also for adding Mailcow.

Then I vote for the opposite.

Instead we should focus on usable P2P solutions that replace e-mail instead of telling users to maintain a complicated stack of software on a server. Decentralizing E-Mail is a flawed idea. It's too late and there is no anonymity anyway.

**Comment by ignitedPotato** [comment]
I agree that it would be great if anonymous P2P solutions replaced email in the future. But what about now? PRISM-break shouldn't be a platform that only offers utopian solutions.

Also decentralization is one of the key ideas behind email:
> An important feature of SMTP is its capability to relay mail across
   transport service environments.

([RFC 821](https://tools.ietf.org/html/rfc821#section-1))

You're right, it is too late. I don't think that email will vanish that fast. That's why we need to at least try to own our data which can be achieved by hosting our own mail servers. But that's just my opinion.

**Comment by hasufell** [comment]
> I agree that it would be great if anonymous P2P solutions replaced email in the future.

There are already solutions like PyBitmessage. Not sure if freemail inside the freenet is still a thing. But that's far from being utopian.

> Also decentralization is one of the key ideas behind email:

How is that decentralization? It was never designed as a decentralized system where every user runs his own mail server. And it was never designed for anonymity. It's moving into quite the opposite direction, because of spam.

> That's why we need to at least try to own our data which can be achieved by hosting our own mail servers.

That's rather irrelevant for fighting mass surveillance, because they don't care about your E-mail data. If they need the data from a specific person, they will get it anyway. But that's not mass surveillance.

**Comment by andryyy** [comment]
So we should remove mail servers, because there are more secure alternatives? Let's tell everyone to stop using email. :) That will not work. 

Prism break does the correct thing imo right now: listing self-hosted solutions you are in control of. mailcow even offers a way to discard unencrypted connections before DATA. Needless to say you are in full control of ciphers used to communicate with remote MTAs. An encrypted maildir to store your data on remote sites is about to come soon, too. In fact it is already implemented but not active.

I think a self-hosted solution is a huge (!) improvement for privacy. As long as prism break does not tell users to stop using protocol x in favor for protocol y, I am totally for keeping mail servers and adding mailcow. 

You may want to add a warning to the whole section, though. Maybe to all servers listed here. Not only mail.

**Comment by ignitedPotato** [comment]
> There are already solutions like PyBitmessage. Not sure if freemail inside the freenet is still a thing. But that's far from being utopian.

I know that and I know those tools are being used but not by a great margin. That's why I wrote "utopian". It would be great if everyone used those tools but I don't think that's going to happen in the near future.

> How is that decentralization?

I can't see how it is anything but decentralization. SMTP is **designed to** support as many mail servers as there can be. This is literally one of the first things you can read in the RFC.

I have to agree with @andryyy here. Even though we can't fully solve mass surveillance with Mailcow and other self-hosted solutions it still is a huge improvement.

**Comment by hasufell** [comment]
> Let's tell everyone to stop using email. :) That will not work.

Why not? If a technology is inappropriate for fighting mass surveillance (that's what prism-break is about, not just "security") then it should not be recommended, otherwise it's almost a lie.

**Comment by ignitedPotato** [comment]
Yes we totally should recommend secure and anonymous alternatives! But also think about those people who won't let go of email just because one site recommends them to. We should offer better alternatives there, too I think. Even if the improvement is not that big.

**Comment by hasufell** [comment]
> I can't see how it is anything but decentralization. SMTP is designed to support as many mail servers as there can be. This is literally one of the first things you can read in the RFC.

I know the RFC. What I'm saying is that the technology stack of modern E-Mail systems was not designed with full decentralization in mind, although the protocol allows it. Usability is part of decentralization. That's what P2P systems try to solve. You can't even misconfigure them. And you are not maintaining anything.

> But also think about those people who won't let go of email

Tell them the truth then.

**Comment by ignitedPotato** [comment]
I fully agree that P2P systems are better in any way, we are on the same page here. I also agree with you that we should tell users about it and recommend P2P software instead of email.

Still, that doesn't mean we shouldn't list self-hosted email servers. Email is used now and will be used in the future. I think we should offer suitable alternatives which still support the "wrong" protocols but offer a huge privacy bonus.

I mean if we were serious with this we would have to remove all kinds of other software, too like XMPP clients and servers, SIP clients and servers, .....

**Comment by hasufell** [comment]
> Still, that doesn't mean we shouldn't list self-hosted email servers.

That depends on the kind of users we are assuming. In other threads the prism-break community seemed to suggest that we are primarily targeting an inexperienced audience that gets into "first contact" with the mass surveillance problematic, therefore, windows suggestions should not be removed they argued.

If we are talking about that audience, then you definitely DO NOT want them to run something like mailcow. Tell them to use P2P or a a privacy aware mail service. That's as good as it gets for them.

If we are talking about power users, then I don't even know if they want something pre-configured. Maybe they do, maybe they don't.

The problem I have with this pre-configured server-apps in contrast to just having "postfix" on the list is that it gives a false feeling of being fit for regular, inexperienced users. It isn't.

Another alternative would be to have an "expert" checkbox or something to hide some of the more sophisticated things that are definitely not for regular users. That would also allow to solve things like #1709 differently (e.g. you don't want to recommend OpenBSD to someone who has been a windows user for 2 decades).

**Comment by ignitedPotato** [comment]
I really like your idea of an "expert" checkbox which - already implemented - would make the decision of whether to add Mailcow or not much easier now.

I don't want to presume to decide who we want to appeal more. Judging from the current selection of projects in PRISM-break we try to appeal both inexperienced and experienced audiences. This is why I don't see why we shouldn't add Mailcow now. We can still make it an "expert" project once the separation is implemented and have a discussion about that in a separate issue.

**Comment by andryyy** [comment]
"If we are talking about that audience, then you definitely DO NOT want them to run something like mailcow."

I aggree.

"Another alternative would be to have an "expert" checkbox or something to hide some of the more sophisticated things that are definitely not for regular users."

Good idea. But it's not easy to separate everything by expert or beginner. That would raise a lot of discussion. Or hide server software by default? Don't know. Like that Firefox checkbox "I will be careful". ;)

**Comment by andryyy** [comment]
BTW: Just checked the other solutions. They do completely configure your mail server . Where is the difference? They even say that on their websites. :) "Like hosting your own Gmail". Hm.

And: Adding just Postfix (which is only the MTA) is by far more dangerous. It is hard to create an open relay nowadays, but a beginner will not end up with a secure MTA by just installing Postfix. Maybe it was just an example, I don't know.

**Comment by hasufell** [comment]
> Adding just Postfix (which is only the MTA) is by far more dangerous.

Not at all. In order to get a raw postfix up and running properly you will end up reading a lot of manpages, documentation and tutorials.

**Comment by andryyy** [comment]
Well, if you assume users will configure a best-practice and safe configuration after reading man pages and tutorials (never use tutorials if you are serious about a good configuration)... Some may end up with a safe configuration, others with a total mess.

How it comes you recommend reading tutorials and manually setting up Postfix (which is not easy at all), when you are so scared about open relays? I wouldn't do this.

What if I told you there is mailcow, to setup a safe base configuration? :) Or iRedMail etc. I'm sure these things setup a safe environment.

**Comment by Braintelligence** [comment]
I don't know how it's like today but when I set up Kolab about 1-2 years ago it didn't support DKIM right out of the box. You had to set this up the oldschool way, there was no script and no documentation on how to achieve this. 

Even Webmin had DKIM support out of the box. This was only one of the PITAs with Kolab.

**Comment by hasufell** [comment]
> How it comes you recommend reading tutorials and manually setting up Postfix (which is not easy at all), when you are so scared about open relays? I wouldn't do this.

You didn't really get any of what I said. Preconfigured convenience things like docker (images) lower the bar of "getting into" server administration to a point where completely clueless users end up doing very very weird shit. This is what you see every day in `#docker`. Every day. Because they only care about the abstraction layer (docker) and getting things running, but not about what it is actually doing.

I am saying those should __neither__ use docker __nor__ manually configure a postfix server (and pretty much all of them would fail on the latter). Docker is not for inexperienced users who want to manage a server like their android phone. It's (apart from other use cases) for server administrators who want to abstract out deployment and other things. Suggesting otherwise is dangerous.

**Comment by Atavic** [comment]
mailcow-dockerized isn't a mail server, it's 12 containers and 6 disk volumes on a bridged network. Of these containers, the most user friendly is ClamAV, while asking newbies to handle BIND is something that escapes me.

I'm totally with @hasufell on this.

**Comment by andryyy** [comment]
So you want to remove iRedMail for installing multiple applications (1 application == 1  container), too? :)

Multiple Docker volumes provide a very easy way to use different kinds of volume drivers for each "category of data". It is also much easier to separate and organize data this way. I don't see any reason to not make use of this feature.

There even is a "Why bind" section to explain it is used for DANE validation and for DNS RBL lookups (public resolvers are blocked or heavily rate limited). You don't host a DNS server, don't worry. It is maintenance free. ;)

We could remove bind and let users query via Google DNS or other public resolvers. They would not be able to query DNS "blacklists" or validate TLSA records.

I see you guys have some good points. Don't be mad or angry about me for defending mailcow.
For further concerns let me know...

**Comment by tailslover** [comment]
"We could remove bind and let users query via Google DNS"

Use Tor DNS!! (Tor's "DNSPort")
