### ISSUE TITLE
Don't use Mailvelope in Firefox

### ISSUE THREAD

**Issue by richardlang** [nylira/prism-break#1743]
https://posteo.de/blog/sicherheitswarnung-f%C3%BCr-nutzer-von-mailvelope-mit-firefox

**Comment by Zegnat** [comment]
Summary: looks like add-ons aren’t running fully compartmentalised so they are able to access each other. This means non-Mailvelope add-ons might gain access to your private key in Mailvelope.

According to this there is nothing add-on authors can do to fix it, as it is a browser bug. To me this suggests all add-ons that need to keep secrets are vulnerable. On the other hand: if you only install trusted add-ons you are still as safe as ever.

This is the weird double-standard with add-ons. Sure you could have installed a malicious add-on that steals your Mailvelope secret key. You could just as easily have installed a malicious add-on that broadcasts your entire browser history or scrapes every email you read. The real warning is not that your add-ons have access to your private key (which is obvious because Mailvelope needs access), but that add-ons need to be 100% trusted or not installed at all.

**Comment by richardlang** [comment]
This is supposedly to be fixed with Firefox 57. I was just wondering, are add-ons in Thunderbird fully compartmentalised?

**Comment by Atavic** [comment]
You can use a specific profile for Mailvelope for Firefox. It's listed as Option 2 in the article.

**Comment by Zegnat** [comment]
@richardlang:

> I was just wondering, are add-ons in Thunderbird fully compartmentalised?

Unless someone who has taken a good look at the source code (not me) tells you any different, I would assume that they are **not**.

The best way to look at this is to assume every add-on integrates 100% with the application and has full access to all other parts of the application. If you run a single add-on that you do not trust, your entire application should be seen as compromised.

**Comment by richardlang** [comment]
@Zegnat 
> Unless someone who has taken a good look at the source code (not me) tells you any different, I would >assume that they are not.
>
>The best way to look at this is to assume every add-on integrates 100% with the application and has full >access to all other parts of the application. If you run a single add-on that you do not trust, your entire >application should be seen as compromised.

Thanks!

**Comment by strugee** [comment]
I'm going to go ahead and close this to keep our issue tracker clean. There's not a whole lot we can do about this at PRISM Break, and Firefox 57 will ship without support for legacy (non-WebExtension) addons, which will fix this problem. So a solution is on the horizon. Thanks all.
