### ISSUE TITLE
Consider removing F-Droid

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1748]
As discussed in #1746, F-Droid currently offers apps like "OpenVPN for Android" or "Linphone" which are up-to-date elsewhere but not in F-Droid store. Furthermore, F-Droid allows one to install apps like "Orweb", "Orfox" (Guardian repo) or "IceCatMobile" which are not maintained at the moment and contain critical and publicy known security vulnerabilities (the same goes for OpenVPN/Linphone).

Privacy-conscious people are in danger of installing vulnerable apps and render their mobile device insecure. As a consequence, they are using insecure devices while having the feeling that they are "more private" because Google cannot track them. F-Droid users currently have to install apps like ApkTrack or Yalp only to notice that many apps are outdated in F-Droid or they simply ignore the problem.

So, we should discuss if the inclusion of F-Droid makes sense at this stage.

**Comment by quantumpacket** [comment]
As much as I agree with the shortfalls and the potential dangers of installing outdated packages through F-Droid, ultimately the latest package being available *anywhere* is going to fall into the hands of the maintainer be it a 3rd party or the app's developers.

We even have the same issue with repositories for desktop environments. Take for example Tox for Debian systems, which its maintainer who is on the Tox team hasn't updated the repos for months, yet people still think they are getting the latest version. If the end user is not being proactive in making sure that pre-compiled security/privacy based apps they use are indeed current, then they probably don't care about security/privacy as much as they think they do.

I'd hate to remove the only alternative to Google Play Store because of that. I would rather suggest in the notes section there be a prominent warning that apps may not be current, and even suggest ApkTrack as a way to help manage that. I'm sure I'll be in the minority on this as a compromise for a solution.

**Comment by bezcitu** [comment]
@quantumpacket 
There are indeed packages which are not updated by their maintainers outside of F-Droid's reach (like IceCatMobile, Orfox). But there are also packages like Linphone or OpenVPN for Android which are up-to-date virtually everywhere unless on F-Droid.

It is questionable if most people accept that they have to install F-Droid and an additional monitoring app to note if they have the current app versions. And there is the next problem: Besides, one has to update apps manually which may result in another developer signing key and ultimately in a complete reconfiguration of the affected apps.

**Comment by hasufell** [comment]
> We even have the same issue with repositories for desktop environments.

No, we don't in proper distros. If a package is not updated by an upstream maintainer __after__ a vulnerability is discovered, it will be removed/masked and the problem communicated to the user (most probably via the package manager directly).

> I'd hate to remove the only alternative to Google Play Store because of that.

Well, at this point we can safely say that you will most probably install a lot of vulnerable apps if you are using F-Droid and as such, your phone is compromised. When using Google Play Store the chance of outdated apps is LESS, because they don't have broken build servers like F-Droid.

Just _knowing_ that there is a newer version, but not available in F-Droid repos, doesn't really solve much.

I really dislike that prism-break keeps recommending wrong things just because "there is no better alternative". If there is no better alternative for running a compromised phone, just say so and stop giving the impression users can currently do something reasonable about it.

**Comment by quantumpacket** [comment]
> No, we don't in proper distros. If a package is not updated by an upstream maintainer after a vulnerability is discovered, it will be removed/masked and the problem communicated to the user (most probably via the package manager directly).

Do package managers do this for repositories hosted by a 3rd party? Seems like a lot of ifs that someone is monitoring the countless 3rd party repositories an end-user could add to their system. What about versions that are no longer supported? They may not have known vulnerabilities, but that too is something that should no be installed.

> Well, at this point we can safely say that you will most probably install a lot of vulnerable apps if you are using F-Droid and as such, your phone is compromised. When using Google Play Store the chance of outdated apps is LESS, because they don't have broken build servers like F-Droid.

Did I say I keep the outdated versions? No, I compile the latest version if I find they are no longer updating it, and if the app is worth the effort to do so. That's the great thing about them being opensource. Don't assume so much.

**Comment by hasufell** [comment]
> Do package managers do this for repositories hosted by a 3rd party?

Depends on the distro. For some that is fairly easy and can be done independently. Also, why are we talking about 3rd party repos? That's not even the main problem we have with F-Droid.

> Seems like a lot of ifs that someone is monitoring the countless 3rd party repositories an end-user could add to their system.

I don't understand. Usually, you shouldn't add random 3rd party repos in a proper distro and usually that's not really necessary either.

> What about versions that are no longer supported? They may not have known vulnerabilities, but that too is something that should no be installed.

Then the distro packagers will make sure you cannot install them. I don't understand your problem.

> Did I say I keep the outdated versions? No, I compile the latest version if I find they are no longer updating it, and if the app is worth the effort to do so.

So you are moving outside of the comfort zone and what we can safely assume is not what most users will be doing or even be capable of.

> Don't assume so much.

I assume nothing. I am just saying that your picture about desktop distros is not very accurate. They don't have those same problems.

F-Droid really is not a "distro". It's just an infrastructure that tries to automated builds. That's a huge difference.

**Comment by Atavic** [comment]
The issue is about Android OS and not just F-Droid. New versions of the OS are released by a group with Google as the main actor. The users have to wait for their vendors to eventually make the new versions available to update the OS.

F-Droid has shortfalls, but also the OS should be considered with the same shortfalls, so I  suggest to add an explanation of this issue in the Android page and add some firewalling tool, as [AFwall](https://github.com/ukanth/afwall) on top of that page.

**Comment by hasufell** [comment]
@Atavic yes, the situation is even worse and I consider _any_ kind of phone pretty much compromised (not by being specifically targeted, but by class-breaks). How does a firewall help there?

**Comment by Atavic** [comment]
Granular control on applications, minisize data usage, etc. Look @ the [wiki](https://github.com/ukanth/afwall/wiki/Apps-leak-private-user-data-during-boot).

**Comment by hasufell** [comment]
> Granular control on applications, minimize data usage, etc.

Erm, how does that help with the privacy problem that you are running a google-driven OS and vulnerable apps?

**Comment by Atavic** [comment]
You can - at least - reduce the problem but definitely not solve it.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

0ri0n:
> I'd hate to remove the only alternative to Google Play Store 
> because of that. I would rather suggest in the notes section there 
> be a prominent warning that apps may not be current, and even 
> suggest ApkTrack as a way to help manage that. I'm sure I'll be in 
> the minority on this as a compromise for a solution.

I think a prominent warning about F-Droid and a mention of ApkTrack
would be preferable to removing F-Droid.

Note that ApkTrack doesn't seem to support Tor, so you'd probably be
leaking to 3rd parties what apps you have installed.  I'm not sure how
this compares to the privacy implications of Google Play, but it's
probably worse than F-Droid in terms of privacy (though some users
will probably be okay with it if it helps them have more up-to-date
apps).


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZTxeRAAoJELPy0WV4bWVw5BAP+wSn2bCkW9gqxW0iwHglPYvY
wwGKLE36WCgZQYhl7T8CLQcPvXN1s0GytYv6EowubobFurVeNzx3nTkQ8j0z+WZx
dCAQKLEDcblwvFHyiWv6KeNMozagzFusnsSt5jFCzORCaPy8A6kvqSPIccVuSRNR
gINspgvltoqS5yk6x820GX5IESeSDxPDtV/XCfN7U49iAqkiUK7KQoYEQJGM197r
LS4OpVqUhOYasvwFnToB2rTNOYGF3FbHnan5CRX2A63bLbTRMGu3iv079R92q2lw
jsSGmAV97/kYeb0lcFK3hn+rDBjwgJmHTExSRU9/WI7IOGSCUJy5gS3Cz9JQEhmQ
PzhzaYWMKdxnSYn8J4D0f+pBhdJ06igFNxcr5TkXQker1TYmzPTiuonMvR612rcu
Wljbv3ZuI1Sa2wq+jhcyCeulrY/s987425juolnRiwoRzF6HJU+L70JYjIRkjLlc
v0fFszPSfMcTFg+By2XIQvqe0sMo5aLcXm9Bx9hklUmlK93L4cwLJWflLJN87+4c
R55JV2has26zYW+SD7hr259u8AuKKc/1hRKV+tVIPHNYtKo3Je91itBvyl40hsbp
0UoU/XlM/oggkyfdxXcVsmC/6A+sleP+4CcXxZOiZRt+402l7cOgw7OebBraF04o
VZ+G732BKJLgOfg02+6r
=W9EA
-----END PGP SIGNATURE-----

**Comment by bezcitu** [comment]
@Atavic 

> The issue is about Android OS and not just F-Droid. New versions of the OS are released by a group with Google as the main actor. The users have to wait for their vendors to eventually make the new versions available to update the OS.

Why is this issue related to the F-Droid problem? Yes, Android's update system is not ideal without question, but people can choose custom ROMs to cope with this issue. 

Back to F-Droid: I think it is even worse if people have to install more and more apps to retain control of the security of their devices. These apps could also be outdated and bring new issues with them.

So, we say "Hey, in order to have a privacy-friendly phone you should install F-Droid instead of Google Play but F-Droid offers apps with security vulnerabilties. Therefore, you must install third-party tools like ApkTrack to see if your apps are outdated. Then you have to manually update these apps but maybe you have to reconfigure them afterwards due to other developer signatures. In addition, this whole process can leak information about you and your device (and is not straightforward as well) but originally you installed F-Droid to face this issue."

We go around in circles.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I think the underlying problem here is that there are not any good
options.

* Tell people to use Google Play.  Trusts Google and has privacy issues.
* Tell people to use F-Droid.  Might introduce outdated apps.
* Tell people to use F-Droid with ApkTrack.  Less usable, has privacy
issues that may or may not be as bad as Google Play.
* Tell people that there is no way to be secure on mobile devices and
they shouldn't use mobile devices.  Will probably result in many users
not taking the advice, and instead using even less secure/private
things on Android.
* Give people information about the subtleties of each of the above
options and their tradeoffs and let them make up their own mind.  May
result in information overload and inability to figure out what threat
model applies to a given user.

I don't really like any of the above options, but I tend to lean
toward the last one (but I admit that it's not a good one -- I just
think it's the least bad).  I do understand that PRISM-Break's policy
is usually to make recommendations rather than provide detailed
information about which recommendations should be used when.  I don't
claim to have a great solution here.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZTz+/AAoJELPy0WV4bWVwX2IP/jkrwGWFS86ZwrBN0RsmsK6m
jAivFwBmG2StaLCza+C3mmA7MhgHbN0ALFhJB8UIbeEQ8PXikUmR7UC1Azpxe4M0
apcol7fYghqtQ3T0sZrGFVrSPbME8MBR3OwBMwaMT01LaKiXC9DZ02Gh8VsoWnFv
ZjxiOWGUu2OtFmFjPdApdiEZZAUJ5QX0VmLNJmMjHQbF3903coVoHIhealn3/v+1
yR6nCoVsLKm2jTGFOmeZmBU/SjU0VOl9+S4Hp/mcBFUXxTOEYZiE9R6E3TnYNA5u
lo39/pjAXM2l7XtmqJg4W5lgRNM7ygrOSIZCRoxL+B3tHBTZzVygndYQXWDrukrw
CTG7WSWaCWXOzydyCoGUEN6rvczdb+WT9H4i+pBIC1yJMwppdNxEEOn9j1nnteXP
f641DA07acyGfCFdoNozlV17DQI8k94vp8bVTPKLuUHEujYRqNG+A70AAP4sTk6w
6kyqCzH5OnKAmS+01Usg9BBvIFDcas7WZv41F6Jn9Eja+6sk/+xTQGxFR4B8VNlF
iWJZAbb9k4ztAgdK0fWUqdGVZcifLs71KgnasJOwW5S1T4AHM36XUewWT6WSeEgU
SYdculWXKQztuHetN5829YSOy2R0Ug6OiZ8VKmS217oVlgbx1c/cNbPWP5rAbvdP
4lMlWwCKLwhOCY/MbANt
=xYAD
-----END PGP SIGNATURE-----

**Comment by hasufell** [comment]
> * Tell people that there is no way to be secure on mobile devices and
> they shouldn't use mobile devices.  Will probably result in many users
> not taking the advice, and instead using even less secure/private
> things on Android.

That's the only reasonable option. We should stop pretending to know what people do based on __correct__ advice and then reverse-adjust that advice in order to manipulate users. What the f*ck?

**Comment by Atavic** [comment]
@bezcitu I'd add some text that warns the user to update OS and apps whenever is possible.

**Comment by mimi89999** [comment]
@bezcitu OpenVPN 0.6.73 is now in F-Droid. It is the latest version of OpenVPN. It took some time to update it because we had issues with building it.

**Comment by bezcitu** [comment]
@mimi89999 
Yes, I know, but please note that OpenVPN was only one example. There are many more and AFAIK there is still no prominent security warning when someone tries to install heavily outdated apps like Orweb, IceCat Mobile or Linphone. However, some of these apps seem to have an anti-feature "known vuln" warning on f-droid.org now.

Therefore, it is still risky to install apps from F-Droid and pray that there will be updates quickly when the next CVE is discovered.

**Comment by Zegnat** [comment]
I am not sure if I am pro or contra recommending F-Droid, but I will give my reason for using F-Droid.

I trust the F-Droid project enough that when they say their build reflects a specific repository, that is truly the case. This allows me to take a look at the F-Droid repo for a project and when that code does not include any weirdness I can use their builds instead of having to build an APK myself.

I don’t get this from e.g. Google Play. APK builds on Google Play are not in any way linked back to their source code repositories. For all I know, Google – or even the uploader – has added code into the APK that isn’t in the repository at all. Outside of F-Droid my only other option is to build the APKs myself.

It is not a question of having the latest version of an application, it is a question of having the easiest auditable one.

This is also the glaringly missing alternative from @JeremyRand’s list:

• Build the APK yourself.

There is a reason why we promote open-source software. This is one of them.

**Comment by hasufell** [comment]
> It is not a question of having the latest version of an application, it is a question of having the easiest auditable one.

Not really. Security is not related to free software and only partly to opensource. Even proprietary software can be audited, but not openly by the community.
When we talk about opensource, we talk about __trust__. But when practical security in proprietary services like Google Play outperforms the security in something like F-Droid provably, then trust is not enough anymore. And don't tell me Google doesn't care about security. They do, they just don't care about privacy.

Security __IS__ a matter of having the latest version of an application. Thus, for me... neither F-Droid nor Google Play are reasonable choices.

**Comment by Zegnat** [comment]
> Security **IS** a matter of having the latest version of an application.

This can be true, doesn’t have to be true. Not every version includes security fixes. But I do get your point.

> Thus, for me... neither F-Droid nor Google Play are reasonable choices.

Like I said, “Build the APK yourself.” That’s really the best solution if you want latest version and to match a specific repository. In the same way that some package managers will allow you to always build software yourself rather then rely on pre-build.

Getting people to set-up an Android development environment just to install an app is a hard sell though 😞

**Comment by hasufell** [comment]
> Getting people to set-up an Android development environment just to install an app is a hard sell though

At this point (and many other similar ones) I think the best course of action is just to be honest to the user. We shouldn't list the _"least worst option"_, we should list __recommendable__ options.

**Comment by vanitasvitae** [comment]
I'd prefere that instead of discussing to ditch FDroid, energy would rather be spent on helping out to keep the repos up to date. The folks over at FDroid are doing a great job providing us with (reproducible) builds, which Google soon will no longer do.

**Comment by hasufell** [comment]
> energy would rather be spent on helping out to keep the repos up to date

Prism-break is not an effort to orchestrate opensource collaboration.

> instead of discussing to ditch FDroid

We are here to do exactly that: discuss opensource alternatives to proprietary software/services.

One can feel sorry or offer his help or do whatever else. That doesn't change anything about the current discussion though.

**Comment by tailslover** [comment]
OP can discuss about this on f-droid.org ticket.

IMO there is absolutely NO reason to remove FDroid from prism-break.
I know some developers IRL and we are releasing our Android app EXCLUSIVELY on FDroid only.
Because we dislike Google play. We want more people to use FDroid instead of priprietary service
like Google play.

Sorry for uppercase letter, I'm not yelling. Just wanna promote our view a little bit.
Glory to open source software.

**Comment by tailslover** [comment]
So, if you dislike seeing not-up-to-date apps on FDroid, stop bitching about it and start helping.
That's how open source community grow.

**Comment by hasufell** [comment]
> IMO there is absolutely NO reason to remove FDroid

Then you haven't followed the evidence that FDroid repeatedly ships vulnerable applications, because of technical and possibly organizational problems.

> So, if you dislike seeing not-up-to-date apps on FDroid, stop bitching about it and start helping.

You shouldn't tell people what to do with their free "open source time". And that's not what we do on prism-break.

**Comment by vanitasvitae** [comment]
Still, I'd prefer (sometimes) outdated verifiable software over apparently up to date software which is not reproducible and therefore not verifiable at all.

**Comment by strugee** [comment]
@vanitasvitae you are free to run your devices the way you want, even if it leads to them being pwd. But PRISM Break is not going to recommend something that is known to introduce security vulnerabilities.

Fundamentally I think this is related to #1687. I realize I wrote https://github.com/nylira/prism-break/issues/1687#issuecomment-288127732, but I'm kind of changing my mind a bit since this is the exact type of scenario where I think a high/low system would make sense. In this case it would seem reasonable to me to put F-Droid into the "low" category with a warning about being careful what you install. For the "high" category we'd drop it because of all the issues here.

Also, unrelated: I'd like to make it clear that **suggestions to "just improve F-Droid" are off-topic**. PRISM Break exists to objectively evaluate reality. We have a scope for a reason, which is that people's time is valuable and belongs to _them_, and it's not okay to demand that they contribute to your preferred project. I for one do not have the time to contribute to F-Droid because I already spend all of my time on PRISM Break and several of the projects included in PRISM Break. I know several other people here also have heavy involvements elsewhere. So please don't complain about the fact that instead of _volunteering our spare time for free_, we're stating _facts_ about the reality of F-Droid.

**Comment by 2SI3NX** [comment]
Technically F-Droid is not the problem here.  Whether some apps on there are up to date or not, that is the app's maintainer's problem and the responsibility of the user to choose whether he wants an out-of-date app.  The user has eyes and can make his/her own choice.  There are many apps on F-Droid also which are very much up-to-date.

F-Droid should not be removed, only A warning sign about F-Droid should be stated saying:
"Some apps on F-Droid are not always up-to-date, so best to use in conjunction with apktrack or yalp"

**Comment by hasufell** [comment]
> Technically F-Droid is not the problem here.

When we say F-Droid we mean the ecosystem here, which includes maintainers and the quality of their work. F-Droid is practically a distro and a distro is primarily defined by the work of its maintainers.

> Whether some apps on there are up to date or not, that is the app's maintainer's problem and the responsibility of the user to choose whether he wants an out-of-date app. The user has eyes and can make his/her own choice. There are many apps on F-Droid also which are very much up-to-date.

Not good enough. The user cannot reasonably know whether he is running _vulnerable_ apps. Common linux distros have a vulnerability management system. F-Droid has nothing. Your options are:

- stop using an app if you see a newer version is available, but not on F-Droid, always assuming there is a vulnerability
- use non-F-Droid services/apps to reverse-fix F-Droid. At that point we cannot really speak of a proper solution. And people may as well ditch F-Droid entirely in favor of those tools.

F-Droid is focused on opensource, not on security or privacy.

**Comment by eighthave** [comment]
This is definitely an important issue, and also something hard to effectively communicate.  There are also many pieces of it.  Certainly, getting software updates is important, but it is not the only thing.  And certainly, everyone would be better off if all the apps in F-Droid were kept current.

F-Droid's main focus is on Free Software and privacy, with security being an important part of that.  Check out the "Anti-Features" related to tracking for one user-facing example of F-Droid's privacy focus. We've invested a lot of effort in making F-Droid the most private possible app store, even considering the server as part of the threat.  You can find out more about that topic here:
* https://guardianproject.info/2016/06/02/building-the-most-private-app-store/
* https://archive.fosdem.org/2016/schedule/event/fdroidappstore/

F-Droid is also mostly a volunteer, community-run effort, so things that should happen quickly do not always happen.  This is similar to GNU/Linux distros.  Debian is one of the most trusted OSes out there, it also includes many outdated packages.  Granted the most popular core packages are updated rapidly.

I'd like to highlight another key part of this discussion that was brought up in this thread: most Android devices do not get prompt updates.  In that case, the app vulnerabilities are the least of those users worries.  The most secure app running on Android 5.0 is not secure.  So perhaps the way to frame this is to talk about configurations rather than specific software packages.  Instead of saying "Android is not secure", say "iOS, Google Nexus and Copperhead have a very good track record of getting security updates".  This mirrors how US Dept of Defence certifies things: they require that a specific setup is certified, not the specific software.

**Comment by hasufell** [comment]
> F-Droid is also mostly a volunteer, community-run effort, so things that should happen quickly do not always happen. **This is similar to GNU/Linux distros.**

Not really. Debian backports security patches manually. And common distros often have a dedicated security team and a vulnerability management system that communicates threats directly to the user via e.g. the package manager. You are also ignoring popular rolling-release distros that update pretty much instantly with that statement (and even most release-focused distros have rolling-release "channels" these days).

> most Android devices do not get prompt updates.

Proprietary mobile operating systems are not recommended by prism-break. And that's a different discussion.

**Comment by eighthave** [comment]
Yes, the Debian security team does a good job of keeping the core
updated, but every distro includes many minor packages that the security
team cannot keep up with.   I'm also a Debian Developer, so I'm speaking
from experience.  There is no software distro that is 100% updated.
Even rolling release distros will have less popular packages that are
not frequently updated.  Because a few packages are slow to be updated
does not mean the whole system is worthless.

**Comment by hasufell** [comment]
> Yes, the Debian security team does a good job of keeping the core
> updated, but every distro includes many minor packages that the security
> team cannot keep up with.

That's more or less an assumption. And hardly an argument. F-Droid lacks the very concepts of

- a dedicated security team
- integrated support for telling users about vulnerable packages and how to deal with them (either updating if an update is available or temporarily not using them until there is)
- basic QA and a working build server

> There is no software distro that is 100% updated.

Again: not an argument. There is a very clear difference between a well-update rolling release distro with security features and what F-Droid currently is. It's irrelevant whether there is a 100% updated distro.

**Comment by mimi89999** [comment]
@hasufell
> basic QA and a working build server

This we do have.

**Comment by 2SI3NX** [comment]
Not that this has anything to do with our issue, but F-Droid can apply a policy to all maintainers, that if their app is more than x days old, they will be filtered out of the repos.  Thats one way of controlling app maintainers who neglect to update through F-Droid.  

I have seen countless apps where the app maintainers always have their apps up to date on google play but start to neglect updating through F-Droid repo's.  For eg. Orfox, Orbot.. etc.

**Comment by Hillside502** [comment]
> I have seen countless apps where the app maintainers always have their apps up to date on google play but start to neglect updating through F-Droid repo's. For eg. Orfox, Orbot.. etc.

Precisely!

**Comment by mimi89999** [comment]
There are only 3-4 app maintainers in F-Droid. Not all are active. We have ~1 500 apps. That would make ~500 apps per maintainer. It is impossible to regularly verify every app for updates for am maintainer. Some apps have also build issues (they won't build) or started using proprietary libs at some point or have source missing or missing build instructions. We can't do anything about those apps.

> Thats one way of controlling app maintainers who neglect to update through F-Droid.

@2SI3NX in our case it makes no sense.

**Comment by hasufell** [comment]
@mimi89999 exactly, so there **is** a problem with F-Droid, mainly lack of manpower. We are not here to discuss the future or whatever of the project, we just discuss the current state of it, which is simply that it cannot keep up with app updates. And you seem to confirm this.

**Comment by eighthave** [comment]
This conversation is rapidly getting far away from being useful, so
let's try to bring it back.  Yes, F-Droid could use more help, yes its a
scrappy volunteer-run project, yes, things sometimes do not get updates
as frequently as they should.

F-Droid also provides very valuable privacy features that no one else
does.  For example, you can run your own app repo on S3/github/gitlab or
any webserver, and only access it over Tor.  There are no logins or
accounts, and we have done everything possible to remove identifying
info from the whole network stack.  That specific feature will be
independently audited this year, which will be the second public audit
of F-Droid.

So this scenario is a bit like comparing Android and iOS: for users who
just want to buy a device and not think about it, iOS is clearly the
better choice for privacy and security than Android (and probably all
GNU/Linux distros).  But for those who want to take active measures and
are willing to work a bit, Android-based projects like Copperhead
provide far and away the most secure and private mobile setups.

Copperhead chose F-Droid as its app store because it is the most private
secure way for them.

**Comment by hasufell** [comment]
> This conversation is rapidly getting far away from being useful

You seem to misunderstand the intention of this discussion. It is not about evaluating what F-Droid needs, but what it currently offers.



> Yes, F-Droid could use more help, yes its a
> scrappy volunteer-run project, yes, things sometimes do not get updates
> as frequently as they should.

To the point that it cannot be recommended to people who don't get their own hands "dirty" contributing to the project and being aware of the specific shortcomings etc.

**Comment by eighthave** [comment]
I'm on the same page as you, this discussion should be about what is
currently available.  I'm not saying that people who want to have a
private mobile platform must get involved in maintaining F-Droid.  I am
saying that the most private mobile platform right now is a specific
configuration that includes F-Droid as its only app store, but for most
users it does not provide a large increase in privacy (Google Play will
still be active, Unknown Sources must be turned on, etc).

I am saying that if you really want the most private mobile platform,
then you'll need to buy a Copperhead device.  Copperhead does not have
Google Play nor any non-free software installed, and comes with only the
Copperhead and f-droid.org repos.  That means:

* many apps will not work on it, even if you download and install it via
adb, Yalp, ApkTrack, etc. because they require Google Play Services

* mobile messengers will not receive messages as reliably as with Google
Play devices since there will be no Play Services GCM or Firebase FCM.

* WebRTC will not be usable in browsers, since it requires some
proprietary Google bits to work effectively.

* it will run noticeably slower since some of its hardening makes things
run slower

Another good option that has recently improved quite a bit is getting a
Fairphone and switching the device to Fairphone Open, their free
software ROM.  That is a full ROM gets official updates and works with
the locked bootloader.  There is a prototype for integrating F-Droid
into Fairphone Open as its built-in app store.  If enough people ask for
it, Fairphone will sell devices pre-configured with Fairphone Open.

Another option that is pretty good is setting up LineageOS with F-Droid,
but that's harder to do, especially since you'll have to find a device
that gets prompt updates from LineageOS.  Most devices supported by
LineageOS do not get prompt updates.

That leaves people who do not want to do any configuration.  For those
people, iOS is really the only choice, even when considering desktop
OSes. As much as I hate to say it, it is true.  I've never been an iOS
user, and stopped using OSX 5 years ago.  Yes, Apple has backdoor
possibilities that they might use in the future (or perhaps already).
But the hardware and software is really tight, the updates are prompt
and required, etc.

**Comment by hasufell** [comment]
> I am saying that if you really want the most private mobile platform,
> then you'll need to buy a Copperhead device.

It has a fishy license and is discussed here https://github.com/nylira/prism-break/issues/1524

> Another option that is pretty good is setting up LineageOS with F-Droid

Supposedly uses proprietary drivers and firmware, discussed here https://github.com/nylira/prism-break/issues/1662

> Another good option that has recently improved quite a bit is getting a
> Fairphone and switching the device to Fairphone Open, their free
> software ROM.

Also includes proprietary blobs: https://code.fairphone.com/projects/fp-osos/

> That leaves people who do not want to do any configuration.  For those
> people, iOS is really the only choice, even when considering desktop
> OSes.

Those are specifically not recommended by prism-break and never will be.

**Comment by vanitasvitae** [comment]
Now I'm confused. Do you focus on security, or software freedom?

**Comment by hasufell** [comment]
> Now I'm confused. Do you focus on security, or software freedom?

Check https://github.com/nylira/prism-break#project-inclusion-guidelines

**Comment by yegortimoshenko** [comment]
This project prioritizes privacy, security is important but secondary.

You can have a bulletproof 3 inches thick steel door with all kinds of features that prevent break-in, but what would be the point of that when someone has keys to it.

**Comment by yegortimoshenko** [comment]
F-Droid is the only free option for Android software distribution and they signing process is commendable. As of today, software is rarely stale, and more importantly, if you think that some application is stale, help F-Droid help you, it's free software: https://gitlab.com/fdroid/fdroiddata

**Comment by Hillside502** [comment]
> This project prioritizes privacy, security is important but secondary.

Privacy is nothing without Security.

Security >>> Privacy >>> Liberty

**Comment by Hillside502** [comment]
> As of today, software is rarely stale

F-Droid is riddled with apps where the Google Play version is later.

**Comment by yegortimoshenko** [comment]
In many cases, security is required to maintain privacy, but when there is no privacy, there is nothing to maintain, no matter how secure it is.

**Comment by strugee** [comment]
@yegortimoshenko I've only been using the "Waiting for Objections" label when it seems pretty clear that we've formed a consensus, but I'm not totally sure that there isn't someone who hasn't spoken up. In this case we have clearly not formed a consensus. Also:

> if you think that some application is stale, help F-Droid help you, it's free software: https://gitlab.com/fdroid/fdroiddata

Please read https://github.com/nylira/prism-break/issues/1748#issuecomment-321394309.

I would also like to remind everyone here that the suggestion is removing F-Droid. The suggestion is _not_ "use the Google Play Store instead".

**Comment by strugee** [comment]
(To further clarify, the main intended purpose of the "waiting for objections" label when I created it was to help me keep track of issues that should be closed after a period of inactivity - i.e. tacit agreement - so they didn't fall off my radar into the depths of the issue tracker.)

**Comment by yegortimoshenko** [comment]
@strugee: I've been using this label to mark tickets that need objection.

> Please read https://github.com/nylira/prism-break/issues/1748#issuecomment-321394309.

Sorry, but I disagree. This is not volunteering your spare time for free, this is about cooperatively solving your own problems. Downloading APKs directly doesn't solve anyone's problems.

> But PRISM Break is not going to recommend something that is known to introduce security vulnerabilities.

There is no point in security without privacy, because security is just an instrument to maintain privacy. "Has security vulnerability" is not an on-or-off switch, most software has security vulnerabilities: when older version of software has a vulnerability, it means it has been there all time along and people used it and didn't know about it.

Your point can be stretched to e.g. recommend Windows over Linux because it's more secure in some aspects, or has more apps that are more frequently updated.

Moreover, F-Droid does not ship software with known security vulnerabilities: they hide it into F-Droid archive and mark with KnownVuln anti-feature.

> I would also like to remind everyone here that the suggestion is removing F-Droid. The suggestion is not "use the Google Play Store instead".

There is no other option: directly downloading APKs is much worse because they can't be trusted to correspond to source code, and there is no way to automatically update (which would lead to software being much more stale than it's currently lagging behind).

**Comment by Hillside502** [comment]
>There is no other option ... [to Google Play]

Precisely!

**Comment by yegortimoshenko** [comment]
@strugee Are you sure there is no consensus in the thread? OP post has one upvote and seven downvotes, and after rereading the thread from top to bottom, it seems that majority of people wouldn't want to see F-Droid removed.
