### ISSUE TITLE
The Tor Browser Bundle name is deprecated, it's only Tor Browser

### ISSUE THREAD

**Issue by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [nylira/prism-break#1756]
The Tor Browser Bundle name is deprecated, they used that name when they bundled other things such as Privoxy.

**Comment by strugee** [comment]
https://www.torproject.org/projects/torbrowser.html.en seems to confirm; marking as accepting PRs.

**Comment by vyp** [comment]
So they don't bundle privoxy anymore?

**Comment by bezcitu** [comment]
They deprecated the name long before 2016.

You can see it here: https://blog.torproject.org/category/tags/tor-browser-bundle, all subsequent versions are only tagged tor-browser

And here (October 2014):
https://blog.torproject.org/blog/tor-browser-40-released
> Bug 11193: Change "Tor Browser Bundle" to "Tor Browser"

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N:
> The Tor Browser Bundle name is deprecated, they used that name
> when they bundled other things such as Privoxy.

Looking at Tor's Gitweb [1], it appears that this is incorrect.  Tor
Browser [2] is a Firefox fork ; Tor Browser Bundle [3] is a packaging
script that combines [4] Tor Browser, Tor, and some pluggable
transports (among other things).  The Tor Project's distributed
binaries are Tor Browser Bundle; distributions like Whonix distribute
Tor and Tor Browser separately (Whonix does not use Tor Browser
Bundle; it does use Tor Browser).

[1] https://gitweb.torproject.org/
[2] https://gitweb.torproject.org/tor-browser.git/
[3] https://gitweb.torproject.org/builders/tor-browser-bundle.git/
[4]
https://gitweb.torproject.org/builders/tor-browser-bundle.git/tree/gitia
n/descriptors/linux

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZc8QwAAoJELPy0WV4bWVw9coP/2M9/1u3DYnPkVRWuwhTkdXE
V9w5sdHXxrzy30P0XgRbHSDPgSD2qoyRgbQQ2YGwVG5K5B9Ovx2ycqQrYJDeF8F0
gk2W3qdNQGAb+jJBZLIiARGKzgunIvYiD5QP4wY8Ci8krZzqxxsKSG2cP6/7u1Sp
iDOFXSnkJnvCCpnCYMTnBjEwxgb6mIoL8Fhg9p/wbGPF762RYtT7hzDCpxcQbQ5+
sk2RcmMRwX8yfENUrOvLX9N3wjvW98XrBfxiVTQaTbIHgGyoM1UtvgK1C3EiYbPV
42NQ4Nc2+DGnLm/g6/r7CgAVS7D7LLHGxrSbE3WjFeeVRDQTG9Gjat2YR7SUT19y
t0N4JB8U1tHWEKOyrCN9Ly+Pft5y3brmjSFV5VLV9QtlZhxjBX30/qB3nSRXfKij
os3cDt6JD2ytWlAdQ86VV3wOHrGX7oGLe3oTPxdSUmAWfPC5Y9gVFUeBjjs7qOj9
EByWAYnCwAEBklC0K1lIpgJFzrIdm1WxzJi8s3U0hO5sF1sP/vOisc9dfq7e5JjJ
V2pmO06JBGwAH+RuBMCLO8EFV70CCJ0wN63asIxEIo2PMcPvkbB3vzl0oR6mMQPx
fc00Lf+QXpvkIgMVT5z35oVr/bO0PTk/ku8/pBR7UGfBEv94QIPVIUWdgv3QCM4+
gUXJeNhcVyQY0Y9X/Ycu
=Z7hs
-----END PGP SIGNATURE-----

**Comment by strugee** [comment]
@JetemyRand are you sure those aren't just old repo names? I would tend to pay attention to the user-facing website rather than developer-oriented git repos.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@JeremyRand 
https://bugs.torproject.org/11193

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

AJ Jordan:
> @JetemyRand are you sure those aren't just old repo names? I would
> tend to pay attention to the user-facing website rather than
> developer-oriented git repos.

AFAIK the Whonix developers (and basically anyone who uses or develops
Tor Browser without the bundled Tor) considers the terms to be distinct.

That said -- I don't think it necessarily matters whether "Tor Browser
Bundle" is a thing.  The intended recommendation by PRISM Break,
AFAICT, is to use Tor Browser (the Firefox fork) in combination with
Tor.  Whether this is done via the Tor Browser Bundle depends on the
user's OS -- Whonix users won't be using Tor Browser Bundle, while
mainstream OS users will.  So I think it makes sense for the PRISM
Break recommendation to use the name "Tor Browser", since it more
accurately describes the situation.  (No one distributes Tor Browser
binaries for mainstream OS's, so there's no danger that someone will
download the wrong thing if they're told to get Tor Browser.  There is
a slightly-above-zero chance that someone will download the wrong
thing if they try to get Tor Browser Bundle on Whonix.)

So anyway, I support changing the name on PRISM Break, and the
distinction here is mostly academic.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZc+DKAAoJELPy0WV4bWVwTf4P/3URlLRzT3rHREHO6f9+8owC
3y2tZZBw3VOto4lCCBSs31xU6cijgJufFPdUGkjQqGOIY08WdxeP9guwm3fYKDpk
VNG1Wlus3ZVD//ZsudB3PcHgFLMRWjyCCI2YQ4yqD9wYZafNyAI2ySPAOS7nNxSs
Xu/CyP6jr7IT6/9Wx7pNkiQitgHCZPvmX1B4JD9OK0K/IJ/HSq7xNctP5rLen0MC
mOEMPXWLosDT+j/n9UhqzVXEkiDkfZ/exKinuGrCjFYVonpvzHoi45pyZW7cfqX3
28zw3IIH8H8POOd78FkCLqeL4sNwgd/4HZsmNB/GDZ+LOPvI51uFnw4wLffBfBkm
hGshB6/LPu8dWi3r1FF2WlN3CvaHRPJ/fcOaZxS6+k7ijjSQqHrdJT0AxivRl987
ObXY9+TNno9Ysne6WbWcuU+LSLeQUS1ymQCWXx7w89MtJyhZ+6phASFhsT8UOr/d
LzVwc4r8/2G2MWORzKnq8QM6M6ouHDpoR43ARUueol5t6Ls+WEL4R0qsul8FXdvw
XXqTg2V/sTzSdzbVIwVeCzrIMo4NHM4H9rzSvrekz5lAu4XoXVAqhiO9ThhQLwEZ
T3UpFCmDfeafw9WVK0OTYZFkSxj+A/ynrVaiHJjOJwpISGRynIRwABMMPYusQvnS
dvkav9tUsEH8frdpUKJn
=yKGS
-----END PGP SIGNATURE-----
