### ISSUE TITLE
Remove the Tor Browser from the recommendations because it's a security catastrophy and puts people at risk

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1760]
And before you laugh at me, here are some leading experts in infosec, cryptography, ... advising against it because of its laughable security:

@dguido [emphasis mine]

> There’s a couple of issues. First off, the network itself can’t be trusted. It’s very easy for random people to set up what are called exit nodes. Those exit nodes are the routers in the Tor network that actually a lot of network traffic passes through.
>
> It’s an opportunity for somebody to sniff that traffic, to modify that traffic. In the past, there’s been many documented cases where this has happened. Almost every time you go looking, it’s easy for researchers to find what are called malicious exit nodes or basically a person that’s monitoring traffic through the Tor network and manipulating it.
>
> It’s span the gamut from state-sponsored attackers, like there’s been a Russia based APT group that was adding malware into people’s downloads. There have been individual hackers that have been sifting through data to find passwords that were going through it and unencrypted network communication.
>
> Even WikiLeaks, when it first started, the original document set that WikiLeaks put on the Internet were documents they collected by running a Tor exit node. The network itself, no matter how you access it, is hostile. You should assume that when you’re sending traffic in the Tor network, that there’s somebody that’s looking at it.
>
> That’s different because I can sit down and I can run a Tor exit node. I can offer to the Tor Foundation, like, “Hey, I have, you know, a box of co-lo and I’d be happy to let you pump like 10 megabits per second of traffic through it. Here’s what you need to hook me up. Go ahead and send some traffic.”
>
> I can do that and I can get access to tens of thousands of people’s network traffic that way. What I can’t do is I can’t call up Verizon and say, “Hey, can you route customer x, y, z’s Web browsing through my machine now?” I would have to break into Verizon to do that.
>
> You actually put yourself at more risk and a greater likelihood that you’re being surveilled by going through Tor than if you just stick on your regular home ISP. That’s the case for most people that are using Tor.
>
> **Then there is a problem of accessing the Tor network. The software that most people use to access the Tor network is the worst, most insecure set of browser components available.** ***I’m talking about the Tor browser bundle. It is an out-of-date version of Firefox that lacks proper exploit mitigation like sandboxing, that has a unique network signature that a network owner can detect.***
>
> **It makes you stick out like a sore thumb.** ***It’s also because it’s out-of-date and because it’s easy to exploit,*** **people do exploit it. If you’re browsing the Internet through the Tor browser, it is easier for people to write exploits that break into your computer when you use that,** ***as compared to using the latest version of Chrome or the latest version of Internet Explorer.***
>
> **Not only that, but it also creates a model culture. Everybody uses the same copy of the Tor browser bundle, means that I only need to write one exploit, instead of writing maybe 10 or more than that.** I know that all the sketchy people on the Internet are using the Tor browser bundle, so I just need one exploit to get them all.

https://georgianpartners.com/the-problem-with-the-tor-network-and-commercial-vpns/

> "Tor Browser is an abomination." All the audits in the world won't fix something that's broken by design. https://news.ycombinator.com/item?id=8468442 

https://twitter.com/dguido/status/523238566294732800

> Read the Tor design doc and ctrl+f for “does not.” Many pushing for use cases that don’t make sense.

https://twitter.com/dguido/status/494571338821279744

> Tor levels the playing ground for bad actors. Anyone can intercept your traffic and no one uses a browser sandbox.

https://twitter.com/dguido/status/844196671747776514

> for a multitude of reasons, it is trivial for network administrators to separate Tor traffic from non-Tor traffic.

https://twitter.com/dguido/status/755102215795273728

> Final thoughts: the Tor Browser Bundle is unable to protect those that need it most. If you rely on it, strongly reconsider your choices.

https://twitter.com/dguido/status/803840526260797440

> Consider the difficulty of running a Tor exit node that injects this exploit into every HTTP session. ¯\_(ツ)_/¯

https://twitter.com/dguido/status/803845309373808640

@thegrugq

He has an article on the Tor Browser Bundle in his medium: https://medium.com/@thegrugq/tor-and-its-discontents-ef5164845908#.6gwjjg57l

>
> [Tor Browser Bundle] collapses state-level targeting of browsers to a small set of Firefox versions; TBB is the most risky browser you can possibly run
>
> — Thomas Ptacek 

@matthew_d_green

> Tor browser
>
> ![](https://pbs.twimg.com/media/C4brIx8WcAEVRZi.jpg)

https://twitter.com/matthew_d_green/status/830609724106276864

@tqbf

> # An extremely commonly held position among experts: Tor Browser is the least safe common browser.
>
> It’s built on Firefox’s design, not Chromes, so it’s inferior at an architectural level. BUT, WORSE:
> 
>  Matthew Green‏ @matthew_d_green Feb 11
>
> Not to mention a slow rewrite/update schedule. Chrome rewrites kill 0days more reliably than @citizenlab.
>
> 
>
> @attractr @bartongellman @matthew_d_green Worse than Safari?
>
> Thomas H. Ptáček‏ @tqbf Feb 13
>
> Yes, far worse.

https://twitter.com/tqbf/status/830511154950766595

"An extremely commonly held position among experts: Tor Browser is the least safe common browser." was even retweeted by @rootkovska

And even their defenses against exploits are utter complete fails, 

@halvarflake's presentation on exploit mitigation,

![](https://pbs.twimg.com/media/DDFE5f_WsAAwEW_.jpg)

Important take-away: "users may choose Tor Browser over better alternatives. Verdict: Near-zero or negative benefit"

# AS Thomas H. Ptáček‏ @tqbf SAID YOU'RE HURTING PEOPLE BY PUSHING THEM TO THE LEAST SECURE BROWSER IN THE MARKET.

NOTE: I'm NOT arguing against using Tor (although @dguido makes very well thought arguments about making own VPN with AWS or DigitalOcean is far better), I'm arguing against using the abomination that is the Tor Browser.

SOLUTION: Recommend Chrome with own made VPN (here's an easy guide that I recommend https://blog.trailofbits.com/2016/12/12/meet-algo-the-vpn-that-works/ using Algo - which is better than Streisand - https://github.com/trailofbits/algo/)

**Comment by bezcitu** [comment]
Just adding some thoughts:
What about Orfox (which is also based on Firefox) and Tails (which uses Tor Browser) then?

Besides, Tor Browser is based on Firefox ESR and regularly updated as soon as Mozilla updates its ESR series. They have a fixed release calendar and publish security fixes in between.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
This reads off like one giant joke, and looking at the proposed "SOLUTION" makes it even more laughable,

> Recommend Chrome with own made VPN

Like how is that even a solution?

I can go on and address each point here but suffice it to say: If you want the *most* secure browser pick Chromium. If you want to browse privately the *only* browser for that is the Tor Browser. You don't have any other choice (Why? No other browser offers the same browser fingerprinting and first party isolation defenses, as [described in their design document](https://www.torproject.org/projects/torbrowser/design/#Implementation). And without both of those, then you're already leaking enough information to make you stand out, no need for an exploit to deanonymize you).

To suggest that the Tor Browser shouldn't be recommended because it doesn't have all the exploit mitigation stuff that Chromium has is no different than saying that Debian shouldn't be recommended because [Windows 10 is superior at the exploit mitigation level](https://fosdem.org/2017/schedule/event/linux_desktop_versus_windows10/attachments/slides/1730/export/events/attachments/linux_desktop_versus_windows10/slides/1730/fosdem_linux_desktop_security.pdf).

---------------------------

Nevertheless I'll try to address some of the misinformation that's being put here,

> You actually put yourself at more risk and a greater likelihood that you’re being surveilled by going through Tor than if you just stick on your regular home ISP.

If I'm an exit node operator then I know that someone visited bigjoke.com, but not who. An ISP knows both that someone visited it, and who that someone is. The situation is entirely different.

> I’m talking about the Tor browser bundle. It is an out-of-date version of Firefox 

The Tor Browser uses the Extended Support Release of Firefox (currently 52, before 45), it gets security updates by Mozilla and the Tor Project delivers new builds of the Tor Browser whenever an update to the ESR is available. How does this qualify as "out-of-date version of Firefox"?

> that lacks proper exploit mitigation like sandboxing,

Content sandboxing has been available for Firefox 52, there's currently a bug that holds them off from enabling in Windows, and they are working to get backport content sandboxing from Firefox 54 for Linux (Source: their 7.0 release blog post).

In any case, with the next ESR (59) content sandboxing will be 100% present at that point, add to that some of the stuff in FF will be rewritten in a memory safe language (Rust).

> that has a unique network signature that a network owner can detect.

If someone want to hide their Tor usage then they use bridges with the many available pluggable transports, both are integrated within the Tor Browser itself. Examples include the meek-amazon PT which makes your Tor traffic look like you're trying to access https://*.cloudfront.net/ (thanks to domain fronting).

> Not only that, but it also creates a model culture. Everybody uses the same copy of the Tor browser bundle, means that I only need to write one exploit, instead of writing maybe 10 or more than that. I know that all the sketchy people on the Internet are using the Tor browser bundle, so I just need one exploit to get them all.

Yeah, and guess how many exploits you need to write to find the IP of someone who uses Chrome? 0, just lookup how the SilkRoad 2 guy got caught.

> He has an article on the Tor Browser Bundle in his medium: https://medium.com/@thegrugq/tor-and-its-discontents-ef5164845908#.6gwjjg57l

Let's look at one of the things he says,

> The conclusion is obvious — Tor Browser Bundle is based on a code base that may have publicly patched Critical or High bugs that are months old. And all the Medium and Low bugs are simply never patched (forever days, as they’re sometimes called.)

Where did this guy get this one from? Here's an ESR release that fixes both Medium ("Intermediate") and Low bugs.

https://www.mozilla.org/en-US/security/advisories/mfsa2017-06/ (Corresponds to this release: https://blog.torproject.org/blog/tor-browser-651-released )

> Firefox is one of the weakest browsers in terms of anti exploitation mitigations, making it less safe to use than alternatives. Tor Browser Bundle is at the tail end of the pipeline of patching (of which it receives only a minimal patch set), making it a risky choice to defeat state level adversaries.

I'm assuming here that the first statement also assumes a "state level adversaries", does he really think that the presence of anti exploitation mitigations is what is going to stop "state level adversaries" from making exploits? Yeah, if they used Chromium that would be harder for them, but the same argument would apply here.

> Threat models that include a Global Passive Adversary, or a capable nation state level adversary,

This is already well known, and applies to all low latency anonymity networks, nothing new.

> or an adversary that doesn’t require an IP address to conduct an investigation, are not well protected by Tor.

I wonder what type of browser can protect from an investigation that doesn't require an IP address?

> An extremely commonly held position among experts: Tor Browser is the least safe common browser.

What if I use the Tor Browser with the Security Slider set to high? Is it still the "least safe common browser" is that case? Also how is Tor Browser any less secure than Firefox ESR when it has so much attack surface disabled?

> https://twitter.com/tqbf/status/830511154950766595

Looking at the thread: "Which means: every well-armed adversary has a stockpile of things to attack TBB with."

But we should assume that if they used Chromium instead then "well-armed" adversaries don't have the capabilities to write exploits for it? 

> And even their defenses against exploits are utter complete fails

Oh really?

> We therefore conclude that selfrando can thwart most real-world exploits. Attackers can only succeed in rare cases where they can disclose the complete heap and data section.
>
> https://people.torproject.org/~gk/misc/Selfrando-Tor-Browser.pdf

Of course SelfRando is no perfect, and has a lot of problems such as memory leaks, but it's better than nothing, and it's very far from being an "utter complete fail".


@hasufell 
What do you mean by compromise there?

**Comment by hasufell** [comment]
> What do you mean by compromise there?

If you control enough entry/exit points, you can gather enough data to analyze the network to a point where you can predict/deanonymize routes connections take. What else would it mean?

**Comment by dguido** [comment]
Hi @C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N 

> This reads off like one giant joke, and looking at the proposed "SOLUTION" makes it even more laughable,

I could say the same about your response.

> If I'm an exit node operator then I know that someone visited bigjoke.com, but not who. An ISP knows both that someone visited it, and who that someone is. The situation is entirely different.

Most people don't realize that using Tor gives random exit node operators the ability to intercept and modify all of their network traffic. Sniffing for more than 2 minutes will give you a positive ID on a person based on things like cookies, POST values, and webpage content. Active manipulation, including insertion of browser exploits or replacing downloads with malware is possible on any unencrypted connection. Considering the Tor network includes typically psuedo-anonymous entities and individuals running exit nodes and attracts the entire universe of both hackers and law enforcement, your network traffic is thousands of times more likely to be actively surveilled on Tor than through your own ISP.

> The Tor Browser uses the Extended Support Release of Firefox (currently 52, before 45), it gets security updates by Mozilla and the Tor Project delivers new builds of the Tor Browser whenever an update to the ESR is available. How does this qualify as "out-of-date version of Firefox"?

The current version of Firefox is 54, not 52, and that is my point. For months, Firefox will receive updates whereas the ESR version will not. Mainline Firefox will get more than bugfixes, it will get new security improvements too. So, thanks for proving my point!

> Content sandboxing has been available for Firefox 52, there's currently a bug that holds them off from enabling in Windows, and they are working to get backport content sandboxing from Firefox 54 for Linux (Source: their 7.0 release blog post).

The Firefox sandbox is only useful for reliability today, not security. It will take years before they tighten it enough to present a real challenge to exploit developers seeking to bypass it. And you just mentioned that platform support for it is not universal and it is clearly a half-baked feature. Clearly, Firefox remains the laggard among all other major browsers.

> In any case, with the next ESR (59) content sandboxing will be 100% present at that point, add to that some of the stuff in FF will be rewritten in a memory safe language (Rust).

No it won't.

> If someone want to hide their Tor usage then they use bridges with the many available pluggable transports, both are integrated within the Tor Browser itself. Examples include the meek-amazon PT which makes your Tor traffic look like you're trying to access https://*.cloudfront.net/ (thanks to domain fronting).

Users do not understand this fact and Tor is not keen to admit it. Many people have been arrested  because the metadata they THEY ARE USING TOR is enough to uniquely identify them. I'm sure Eldo Kim thought he was being safe with Tor, yet: https://www.quora.com/How-did-User-get-caught-for-the-Harvard-bomb-hoax-if-he-used-Guerrilla-Mail-through-Tor

> This is already well known, and applies to all low latency anonymity networks, nothing new.

You are LITERALLY advertising Tor as a solution on the PRISM BREAK website aka as a solution to a global passive adversary. Do you not see something wrong with this?

> Of course SelfRando is no perfect, and has a lot of problems such as memory leaks, but it's better than nothing, and it's very far from being an "utter complete fail".

SelfRando is less than "not perfect." Self-rando is security homeopathy for browser exploits.

**Comment by Atavic** [comment]
> Sorry, GitHub had flagged my account and made it unpublic for a period of time because I use Tor, should be good now.

Duly noted.

> An adversary that provides no more bandwidth than some volunteers do today can deanonymize any given user within three months of regular Tor use with over 50% probability and within six months with over 80% probability.

Source is _Users Get Routed: Traffic Correlation on Tor by Realistic Adversaries_ [(PDF)](https://github.com/torps/torps)

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@Atavic 
That was in 2013, they vastly improved their guard selection algorithms:
https://www.freehaven.net/anonbib/#wpes12-cogs
https://blog.torproject.org/blog/improving-tors-anonymity-changing-guard-parameters which talks about that paper you referenced as well.

(*Totally off-topic pro tip: Additionally, if you're really worried about end-to-end correlation attacks you should setup your own non-exit Tor relay and connect to it, that way one can be sure.*)

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Dan Guido:
>> If I'm an exit node operator then I know that someone visited
>> bigjoke.com, but not who. An ISP knows both that someone visited
>> it, and who that someone is. The situation is entirely
>> different.
> 
> Most people don't realize that using Tor gives random exit node
> operators the ability to intercept and modify all of their network
> traffic. Sniffing for more than 2 minutes will give you a positive
> ID on a person based on things like cookies, POST values, and
> webpage content. Active manipulation, including insertion of
> browser exploits or replacing downloads with malware is possible on
> any unencrypted connection. Considering the Tor network includes
> typically psuedo-anonymous entities and individuals running exit
> nodes and attracts the entire universe of both hackers and law
> enforcement, your network traffic is thousands of times more likely
> to be actively surveilled on Tor than through your own ISP.

The Tor Project is up-front about the fact that unencrypted traffic is
easily read by exit relays.  So what?  Use TLS.  If you're revealing
personally identifiable information over Tor without using TLS, you're
not following the standard advice given by Tor experts -- that's not a
problem with Tor or with Tor Browser.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZc8c7AAoJELPy0WV4bWVwjtgP/3J4TSyjmYYr7ZUBqWDGNbnU
13DD7WtUu3HN4L8gcDfvxeQc6nI5eT4RwxUn5lkGXaRQLD70c/3ygzZzVeC1CWX5
etzN3Kvf9AR31Tr+rjVi4wuj8nksrLNSgDibyNDfiagm+VZMY0nsLCYoOOJ3qk82
qxJYhuJF/dvDkaf7EiXWZN9cu1pXHCww2RCiLU9hzJSVxUaFXQ0gAlS11RC0M9xL
n+Eq0/DdsmDvNmP0bTfdAskBM9CTwGj6ms7ykNBTsHVXw1CwzkikGhLz9ib2N6oB
LdN9YuRRsqMlXbaFPTAKishlyOS+qMihp6XAX0XrecpUI3LNhoxK2tq3qvmLBIQp
TfCIuMss70xR2TguDKA3Vf2lPbSQYPvIHWpGpEl9Jg0u/TTxLTg98nJIMtugWlKx
FdXS78OLe40UB3d34IDnmsZnk5grjOgUvE641k4fioWLygMvpq/2wpnHilg732xQ
nyhH8VZXtlMs8YvzytNqRO0aWWxm58jNa/3ASvFN+BIr5Edzz65eK99XM2q4z31C
xdAAB662D++q8b7b5J1HbY5C5UfcSxKcPEiNMRTcyzUOWVwqdYV7JXCyGEjeBJnX
1mZhKVHW4pHJsI/hj36jOjPrF54wtEGQvL0tGdyj6Qo+70AWuHEOT6GIejxQg5qS
xoAatsEyFXhHuPN5IJyQ
=zc5R
-----END PGP SIGNATURE-----

**Comment by dguido** [comment]
> The Tor Project is up-front about the fact that unencrypted traffic is
easily read by exit relays.  So what?  Use TLS.  If you're revealing
personally identifiable information over Tor without using TLS, you're
not following the standard advice given by Tor experts -- that's not a
problem with Tor or with Tor Browser.

Cool, I'll get right on making sure every website and every network service on the internet is encrypted. :+1:

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@dguido
> Cool, I'll get right on making sure every website and every network service on the internet is encrypted. :+1:

You may be contributing to that, isn't Trail of Bits a "[corporate sponsor](https://georgianpartners.com/the-problem-with-the-tor-network-and-commercial-vpns/)" of Let's Encrypt?

In any case, glad we can at least agree on the Tor+HTTPS (or onion) case!

**Comment by hasufell** [comment]
I feel this issue really doesn't add any new or useful info to the problems we already know exist in Tor. We don't have evidence that the network is _really_ compromised.

If people are concerned about or disappointed by Torbrowser (like I am) they can use Tor with any browser they want and be aware of the potential implications. I strongly disagree with the "same fingerprint for everyone" policy of the Torbrowser developers, but I still feel it isn't useful to add confusing info to the recommendation.

We can second-guess a lot, but we still lack hard evidence. Tor is exceptionally hard here, because no one really knows what different kind of browsers are used in the network, how many nodes are compromised etc... except for the player who potentially has compromised it.

If you find architectural problems and have solutions, report it to the Tor devs. Otherwise take anonymization like it pretty much always is: unproven.

**Comment by anthologist** [comment]
C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N gave generally the best answers imho, I see much confusion in some people posting here. Also someone proved to not understand what's Firefox ESR...
Anyway of course the Tor network is breakable, you are never 100% secure, but there's no "real" alternative other than TorBrowser.
People also don't know that it's not enough to just start it and browse, you need to use it in the right way... do your research.

Suggesting Chrome at the end of the post was hilarious.

**Comment by dguido** [comment]
> If people are concerned about or disappointed by Torbrowser (like I am) they can use Tor with any browser they want and be aware of the potential implications. I strongly disagree with the "same fingerprint for everyone" policy of the Torbrowser developers, but I still feel it isn't useful to add confusing info to the recommendation.

You shouldn't use Tor with ANY browser. Even a single unencrypted request that goes out over your machine has the potential to bite you in the ass. Advanced users know this, but people who download the Tor Browser on recommendation from the Prism Break website don't. Nearly [1 out of every 2](https://www.google.com/transparencyreport/https/metrics/?hl=en) requests that normal users make are unencrypted. This is a real risk and no amount of sponsorship for Let's Encrypt is going to change it any time soon.

Obviously, this is a separate issue from the safety of the Tor network itself. Beyond the unfixable problem of malicious exit nodes that both surveil and modify traffic UNDETECTABLY (it is easy to avoid being caught by the monitoring procedures that the Tor Foundation established), there is a rich history of network attacks against Tor and we are nowhere near the bottom of them. Here's a few more you didn't bring up. You really think this is the end, the Tor network is safe now? Would you risk your well-being on that? I would certainly not.

* Bandwidth weight manipulation: http://www.ieee-security.org/TC/SP2013/papers/4977a080.pdf
* AS traffic correlation: https://www.freehaven.net/anonbib/cache/DBLP:conf/ccs/EdmanS09.pdf
* DNS correlation: https://nymity.ch/tor-dns/

**Comment by hasufell** [comment]
> Nearly 1 out of every 2 requests that normal users make are unencrypted.

Broad and imprecise statement. That's what HTTPS everywhere is for and it has a checkbox "block all unencrypted requests". I don't know if that is pre-enabled in Torbrowser though, but that sounds like a triviality, not something we should discuss Tor/Torbrowser removal over.

> You really think this is the end, the Tor network is safe now? Would you risk your well-being on that? I certainly would not.

No, but until now no one was able to prove the opposite either. And known attacks don't prove that the network is compromised to the point I described earlier. That __is__ hard.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@dguido

> You shouldn't use Tor with ANY browser. Even a single unencrypted request that goes out over your machine has the potential to bite you in the ass.

OK, how about you use Tor with the HTTPS Everywhere option "Block all unencrypted requests" enabled? How about you use Tor with higher security settings such as Medium which blocks - among other things - JS on HTTP websites? 

Also, "bite you" is a strong word here that overestimates the situation.

In any case, I'm glad we at least agree that Tor is pretty good when used with HTTPS (or onion).

> - Bandwidth weight manipulation: http://www.ieee-security.org/TC/SP2013/papers/4977a080.pdf

See [here](https://trac.torproject.org/projects/tor/ticket/9001) and this [proposal](https://gitweb.torproject.org/torspec.git/tree/proposals/247-hs-guard-discovery.txt) which seeks to make that attack non-trivial:

    With this new path selection, we force the adversary to perform a
    Sybil attack and two compromise attacks before succeeding. This is
    an improvement over the current state where the Sybil attack is
    trivial to pull off, and only a single compromise attack is required.

    With this new path selection, an attacker is forced to do a one or
    more node compromise attacks before learning the guard node of a hidden
    service. This increases the uncertainty of the attacker, since
    compromise attacks are costly and potentially detectable, so an
    attacker will have to think twice before beginning a chain of node
    compromise attacks that he might not be able to complete.

Anyway, this is about HS discovery, and we're discussing normal use attacks here.

> - AS traffic correlation: https://www.freehaven.net/anonbib/cache/DBLP:conf/ccs/EdmanS09.pdf

Still not in Tor but there's a Counter-RAPTOR work to help against these attacks https://arxiv.org/pdf/1704.00843.pdf

There's already an implementation FWIW https://github.com/inspire-group/Counter-Raptor-Tor-Client

> - DNS correlation: https://nymity.ch/tor-dns/

"What does our work mean for Tor users? As we outline in [our blog post](https://freedom-to-tinker.com/2016/09/29/the-effect-of-dns-on-tors-anonymity/), we don’t believe that there is any immediate cause for concern. While our attacks work well in simulations, not many entities are in a position to mount them. Besides, they require non-trivial engineering effort to be reliable, and The Tor Project is already working on [improved website fingerprinting defenses](https://gitweb.torproject.org/torspec.git/tree/proposals/254-padding-negotiation.txt)."

And as said by lead dev Nick Mathewson: ["We worked with the authors of this paper, and the attacks should be somewhat mitigated by #19769, implemented in Tor 0.3.0.2-alpha"](https://trac.torproject.org/projects/tor/ticket/20416#comment:2)

**Comment by tailslover** [comment]
What the F are you guys talking about? As a daily Tor user who can't offer open internet due to restrictions I strongly disagree to remove Tor Browser from the list.

**Comment by tailslover** [comment]
Many people use Tor for their daily browsing. Why not close this issue already.

"There's an ad on TV promoting the use of Tor browser!"
https://www.reddit.com/r/privacy/comments/6rxu65/theres_an_ad_on_tv_promoting_the_use_of_tor/

**Comment by tailslover** [comment]
And the OP escaped. LOL.

----
ghost opened this Issue Jul 20, 2017 · 19 comments
Comments
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Notifications

You’re receiving notifications because you commented.
8 participants
ghost commented Jul 20, 2017

**Comment by strugee** [comment]
Given the (technical) discussion here I'm closing this issue. Tor Project is very responsive and is up front about what their threat model does and does not protect against. And while there are _some_ problems with Tor Browser, it still remains the best choice for anonymous browsing because of anti-fingerprinting, etc., plus HTTPS Everywhere being built in which helps to mitigate potentially bad exit nodes.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
So it took more than 25 days to close this issue because some scurity randos weren't aware of the existence of Firefox ESRs and thought that Tor Browser was based on an old security-updates-free Firefox?

**Comment by hasufell** [comment]
Could be faster if you pay us :>
