### ISSUE TITLE
Add Briar (secure, private messenger & more, supporting mesh networks etc..)

### ISSUE THREAD

**Issue by JollyMort** [nylira/prism-break#1768]
Just released to public beta, GPL3 licensed.

https://briarproject.org/news/2017-beta-released-security-audit.html

some Q&A here (that's where I found out about it): https://www.reddit.com/r/netsec/comments/6oo9py/briar_darknet_messenger_releases_beta_passes/

**Comment by kompowiec** [comment]
does exists also [Serval Mesh](http://www.servalproject.org/) which not required create accounts.

**Comment by grote** [comment]
Prism Break is about alternative software that helps you to evade NSA spying though. Briar fits very well in this category since it also hides metadata. Serval Mesh in the other side is not about that.

**Comment by JollyMort** [comment]
As far as I understand, with Briar the "account" you create is local, ie the username is passed along only when you scan each others' secret keys, and the password is there to protect your locally-stored secret key.

The cool part I forgot to mention is that it's communicating exclusively via darknets (Tor for now, I2P planned) and using Bluetooth / Wi-fi to pass messages directly (if in range).

**Comment by mimi89999** [comment]
I can make a PR for that.

**Comment by mimi89999** [comment]
@vyp Can this app be reviewed?

**Comment by vyp** [comment]
@mimi89999 Actually I've been slowly reviewing this since this issue was opened because at first glance it looked quite cool. And so far I've looked at it quite a bit and do like it enough for prism break. :+1: 

The reason I like it compared to all the other options already listed in the IM section is because of it's mesh network support, which I believe would make state level surveillance attempts more difficult (as there's a greater chance the adversary does not have access to the network itself). So if I've understood things correctly, that aligns very well with the goal of prism break. @grote is what I said correct?

I'm not exactly sure, but does anyone know if any of the other projects already listed in the IM section actually have such mesh network support? Because this (and obviously being p2p) is what makes Briar standout for me.

For anyone who wants to make a PR adding it, it should have an `experimental` development stage, since it is still in public beta.

**Comment by mimi89999** [comment]
Ring is DHT based.

**Comment by vyp** [comment]
Yeah I know openDHT is similar in that it creates its own network as well, but for example a cool and potentially useful feature with mesh networking is the potential for internet-less communication even. Or have I confused things?

**Comment by grote** [comment]
DHT in itself doesn't mean mesh networking. Briar can work like mesh, but it is opt-in to not disclose any metadata (and save battery). Also, Briar is probably one of the most secure solutions with a focus on protecting metadata, something that not many others aim to do.

**Comment by mimi89999** [comment]
But Briar is for people with special privacy requirements. It is not for the average user like Conversations (XMPP) or Riot (Matrix)

**Comment by vyp** [comment]
@mimi89999 What do you mean? Do you mean the fact that people have to meet up in person to add each other as contacts first? (again @grote is that correct?) And even so, in my opinion that's completely acceptable given what Briar can provide.

**Comment by grote** [comment]
Yes Briar is for users with special security requirements (and a such perfect for prism break I'd say). So far contacts can only be added in person or via an introduction by existing contacts. This is to prevent MITM attacks and to protect metadata. There's a ticket for adding contacts remotely though.

**Comment by mimi89999** [comment]
I think that this should be added in a notes as some people expect to find easy to use, magic encryption apps like Signal, Wire, Telegram, etc. and then complain that apps listed on prism-break "don't work".

**Comment by vyp** [comment]
@mimi89999 I'd have to disagree sorry, I feel it's worthy of being listed because prism break is about disrupting state level surveillance, and Briar can definitely help with that. Of course, an application needs to be usable to an average user for this because the only way to disrupt state surveillance would be if enough people used it. But I don't think that the in person requirement for adding contacts makes it *that much* unusable to the average user such that it shouldn't be listed. Because well, people regularly meetup in person with each other. :) (And also considering the focus on 'mesh'-like features, I feel that this is sort of expected anyway.) And even then, @grote said there's a ticket for adding contacts remotely. @grote is it [this](https://code.briarproject.org/akwizgran/briar/issues/507)?

**Comment by mimi89999** [comment]
It is not what I mean. I am all for adding Briar and I think that Briar is really great for that, but we should add a note about how Briar works so that people who don't know don't complain that it doesn't work for them...

**Comment by vyp** [comment]
@mimi89999 Oh right.... I agree with that! I thought you meant *only* mentioning it in the notes without actually listing it as a project, my bad! :expressionless:

**Comment by mimi89999** [comment]
I think we can agree that Briar is not for the person who just read about Prism and wants to move from FB Messenger/whatever to something more private. We should clearly say that.

**Comment by hasufell** [comment]
> I think we can agree that Briar is not for the person who just read about Prism and wants to move from FB Messenger/whatever to something more private.

assumption

**Comment by grote** [comment]
> there's a ticket for adding contacts remotely. @grote is it this?

No, it is [this ticket](https://code.briarproject.org/akwizgran/briar/issues/261). As you can see there's already an idea to prevent metadata leakage.
