### ISSUE TITLE
Self-hosted media servers in "Media Publishing" category

### ISSUE THREAD

**Issue by deniss-s** [nylira/prism-break#1783]
Is there a reason why "Media Publishing" category doesn't have many self-hosted servers listed (e. g. Libresonic or Apmpache)? Are these insecure or was just missed?

**Comment by Zegnat** [comment]
things could be missing because of loads of reasons, the leading one being that nobody ever came by to point them out.

Do note though that PRISM Break focusses a lot on replacing proprietary tech, and the Media Publishing category is very much for people who want to publish images, video, etc, so I am not sure what Libresonic and/or Ampache are supposed to replace there?

**Comment by deniss-s** [comment]
These are pretty much alternatives to NextCloud. I'm not saying that NextCloud is bad, but these also can replace such services as Picasa or Vimeo, providing self-hosted solution for images, video and audio.

**Comment by Hillside502** [comment]
Open Source Self-Hosted Libresonic Alternatives - AlternativeTo.net
https://alternativeto.net/software/libresonic/?license=opensource&platform=self-hosted

Open Source Self-Hosted Ampache Alternatives - AlternativeTo.net
https://alternativeto.net/software/ampache/?license=opensource&platform=self-hosted

Open Source Self-Hosted Nextcloud Alternatives - AlternativeTo.net
https://alternativeto.net/software/nextcloud/?license=opensource&platform=self-hosted

Open Source Self-Hosted Vimeo Alternatives - AlternativeTo.net
https://alternativeto.net/software/vimeo/?license=opensource&platform=self-hosted

**Comment by Hillside502** [comment]
No, I was just providing a source for comparing open-source self-hosted multimedia systems.
