### ISSUE TITLE
Garbage recommendation here on github 

### ISSUE THREAD

**Issue by CHEF-KOCH** [nylira/prism-break#1784]
I comment here on most horrible suggestions:

* [Removing Thunderbird](https://github.com/nylira/prism-break/issues/1755) - Thunderbird is open source and there is the ability to patch things, which already got patched. As shown [here](https://bugzilla.mozilla.org/show_bug.cgi?id=14328). Besides this since then internet has changed, there exist extensions, you not need that behind a VPN anyway or the tor extension since you anyway can't ensure that the replicant is really who you think he is. Besides this some workaround are posted in the same thread.

* [Add Canvas blocker](https://github.com/nylira/prism-break/issues/1736) - Why you want to take the risk to install another addon which rises your memory consumtaion for a little more privacy which is very much doubtfull? You can start chrome/chromium with the `--disable-reading-from-canvas` flag. For Firefox you can compile it without it too, or work with about:config. Which covers already the canvas topic very well (not perfectly I do agree).

* [Add Discord](https://github.com/nylira/prism-break/issues/1670) - This is mostly a chat for gamers, the encryption they use only ensure that the communication between you and the server is secured. This means the provider still can read everything. There is no real deal like [WhisperSystems](https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/17094256-implement-whispersystems-encryption-for-voice-and) implemented or a source to [debug things](https://www.reddit.com/r/discordapp/comments/43z4yh/open_source_protocol_encryption_privacy/). Speaking about debugging, discord sends a lot of shit back for debugging, which you can't opt-out because you need to manipulate files and this gets possible overriden by the next update (so no real solution more a workaround). Instead TOX (even if it's till under heavily development) should be used/recommed instead. 

* [Protonmail](https://github.com/nylira/prism-break/issues/1412) - It's trustable there is a source and even an inofficial desktop app. Why the [ticket](https://github.com/nylira/prism-break/issues/1412] was closed and then dublicated [here](https://github.com/nylira/prism-break/issues/1604) & [here](https://github.com/nylira/prism-break/issues/1412) is beyond me cause it should be merged. Point.

* [Brave Browser](https://github.com/nylira/prism-break/issues/1566) - This is a pretty young project and it's only based on Chromium add the end with a button to control 'privacy' which I very very much have doubts that this really helps. I haven't reversed the apk (yet) but it seems HOSTS blocking does the same since there is no cosmetic filtering like uBlock integrated or anything related to uMatrix which prevents really stuff from connecting. I can't recommed it.

* [KeePass](https://github.com/nylira/prism-break/issues/1548) - One year later, why isn't it recommed fro Android. That's by far the best solution. The source is there, the v1 (for Windows/Linux) got audited. I see no problems adding it. There is a [dublicate here](https://github.com/nylira/prism-break/issues/1453).

* [Aptoide](https://github.com/nylira/prism-break/issues/1414) - it's more a place for warez and advertising rather than a app-store. Yalp Store is the real deal here instead cause it even works without Material design to trimm the app size, which I really like.

* [VeraCrypt](https://github.com/nylira/prism-break/issues/1273) - it already got an audit and is secure. Take your ego aside just because there exist CVE (in past) doesn't mean you can absue them, and just ebcause you possible can abuse it not nessarily means you can do it easily without hacking or manipulating other things like the OS or user first.  

* [Cryptomator](https://github.com/nylira/prism-break/issues/1208) - it's okay to use, none ever found a serious hole, you think I'm wrong? Show it.

* [AxCrypt](https://github.com/nylira/prism-break/issues/998) - It should be noticed that the [tool isn't free](https://www.axcrypt.net/pricing/) - besides this it's good to use and it reqular gets updates. 

* [DroidWall](https://github.com/nylira/prism-break/issues/963) - It's dead son! Move to AFWall+ instead or NetGuard (Pro version also avbl.).

* [DNSCrypt.eu](https://github.com/nylira/prism-break/issues/879) - Can be added - why isn't it. If there are doubts feel free to contact me I'm one of the guys behind it.

* [Removing F-Droid](https://github.com/nylira/prism-break/issues/1748) - The app itself is open source and can be trusted. The argument that it shows (maybe) outdated apps are stupid. Cause every app is vulnerable at the end with effort. The thing is if it's really a threat or just a POC without any in wild usage scenario. The Guardian repo is by design not activated so you not get the apps from them (must be optional enabled). I do agree that some apps might be outdated but I see no problem on apps which fully working offline, there is however the option to contact F-Droid or the author of the apps. This not really belongs in here and must be discussed on F-Droid to 'ban' such apps or to add an feature to warn that this app wasn't updated 1+ year. 

* [Security holes on Android password managers](https://github.com/nylira/prism-break/issues/1695) - Oh boy! Once you get root you can grab all files, that's not new. You also can flash a .zip via TWRP to wipe or bypass the lockscreen and of course the integrated password mechanism. There lot of POC's and examples on XDA. The thing is the encryption part. No matter if the database gets stolen or not, when the database is proper encrypted the attacker needs huge effort to crack it or he might give app faster.

* [Remove Tor Browser](https://github.com/nylira/prism-break/issues/1760) - No! Tor browser by default is more secure than the original Firefox browser cause he is based on ESR, uses the tor protocol and comes pre-bundled with some useful extensions. So you really gonna say stop using it and use the more insecure HTTP protocol? You're not in your right mind. Tor and it's browser getting updates regularily and if there are holes they getting fixed asap. `SOLUTION: Recommend Chrome with own made VPN` Shows you have no clue, a VPN is not more secure here, the provider still can spy on you, as shown [here](https://thehackernews.com/2017/08/hotspot-shield-vpn-privacy.html). The thing is that when external components hitting the security topic/aspect it gets difficult. Tor by design since 2016 even doesn't care if one node is compromised, cause it uses a stronger eliptic curve - hoewever the thing is when you send plain text into the network you are always on your own - you blame tor for that?! Shame on you. Real solution is to encryption inbound with I2P. 

* [MeetAlgo](https://blog.trailofbits.com/2016/12/12/meet-algo-the-vpn-that-works/) - Dunno what to say about this, never read more garbage. Trust no commercial VPN's. Show me proof?! Well there [is](https://vpnreport.org) + [here](https://thatoneprivacysite.net/vpn-comparison-chart/). The rest is debugging, and no one found something so far. You thing running you own settings are better? I doubt because 4 eyes are always better than only your own eyes. The problem here is simply that there is no gurantee that you can maintain nessary changes fast enough because you're e.g. sick, in vacation and and and and what if it's still running vulnerable then?! The idea is good but it requires huge effort.  

* There are years old topics still opened here on the issue tracker which I not really understand, if there is no process just close the tickets.

**Comment by vyp** [comment]
https://prism-break.org/ is the site for prism break recommendations. A project being suggested on the issue tracker doesn't mean it's endorsed by prism break.

If you have comments to add about any of these projects, you should add them to each of the issue threads instead of making a separate issue that encompasses all of these concerns. I'm closing this issue because there doesn't some to be any *one* overarching point you're trying to make (about the site as a whole), rather, there's various *specific* points about projects, most of which should really be in those project-specific threads anyway.

For example:

- Thunderbird - This comment should be in the thread.
- Canvas blocker - This comment should be in the thread.
- Discord - That's about adding it to the non-recommended proprietary section.
- Protonmail - Not sure what you mean because #1412 is still open. Duplicate issues are the result of people (anyone) opening them because they haven't looked for or found a previous related issue, not the fault of the repository owner.
- Brave Browser - Isn't even recommended on the site. Comment should be in the thread.
- MeetAlgo - Not even sure where this is coming from, it's not on the site nor mentioned anywhere on the issue tracker. :thinking: 

Et cetera et cetera. I'm not going to go through all of them but hopefully you get the idea. My intention is not to patronize you or anything like that, it looks like you have quite a few informative and helpful comments regarding a lot of projects suggested on the issue tracker, but I think you have a little misunderstanding/confusion about what the purpose of this issue tracker is. So I was just trying to give you some examples to help with that, hope you understand. 😉

**Comment by CHEF-KOCH** [comment]
I was talking about the comments people doing over here and the fact that topics not getting closed even if there years old. Well, you closed my statement now without any reason, instead you want to force me to comment on old posts to make it even more worse and confusing. 

I guess I already linked to every topic and it is definitly here. 

Sorry I give up here, it was worth a try. Unstar and bye. 
CK

**Comment by vyp** [comment]
> I was talking about the comments people doing over here

But wouldn't it be better if you addressed those people directly with your concerns?

> and the fact that topics not getting closed even if there years old.

An issue being years old is not *really* a proper reason to close them in my opinion.

> you closed my statement now without any reason

But I did give a reason, in short it's not an easily actionable sort of item (acting on all these concerns in one thread is impractical), so really if there was no other point being made, then the issue has no reason to stay open. But I could always be wrong so let me know if you felt I misunderstood.

> instead you want to force me to comment on old posts to make it even more worse and confusing.

I don't want to force you to do anything! 😟 But if you're going to go through the effort of making such a post, then it would be much better and more productive for everyone involved if you directed your concerns to the appropriate threads (especially when you've *already found* all the specific relevant threads anyway). That way you have a much higher chance of getting more responses and things getting changed/done, because the people who opened those issues, and everyone who has participated in them, will also get notified. And it's likely that those people will have more knowledge and expertise about the topics they involve themselves in, than just the people who maintain prism-break (it's hard for one person to be deeply knowledgeable about every domain on the site).

And not only that, it's also of course a way to keep concerns and suggestions organized. I'm donating my free time to this project, as well as you by taking the time to voice your concerns, as well as each and every other contributor to the project, and keeping things organized and focused like that saves *everyone* their time.

Could you imagine if all the issues on prism break was instead all just one big thread? That would be so much more confusing and unproductive! And so what I want is for these statements to be where they belong, and having this issue open is not really helping in any way unfortunately. 😔 (And really it's just a matter of copy-pasting your statements into the relevant threads. 🙂)

> Sorry I give up here, it was worth a try. Unstar and bye.

I hope you reconsider given what I said. 😞

**Comment by CHEF-KOCH** [comment]
1) I don't have time to go into each thread one by one. I'm really busy all the day.

2) Yes years old issue tickets are a proper reason cause in meantime a lot of stuff has changed. See entire VeraCrypt story it went from 'Zero to Hero'. (Like Hercules)

3) Just close old and obsolete stuff, and restrict the guidlines here a bit more. Just because there is a new tool popping up doesn't mean anything. It needs analyzed from experts. People in this issue tracker reporting and commenting on things they have no clue about.

4) I spent in my life over 5000+ if not more ours fighting with the community, I can't do this anymore. Especially not explaining basic stuff. I need to pay my bills (like we all need to do). 

I'll might make a bigger pull request once I get time, but at this time I can't recommed the project. Not because the issue tickets or some people here. More because in my point of view security must be up2date ALWAYS and it should stay on the line with leaked documents and possible threats. That is my own phylosophy. I see a lot of things here I can't recommed at all but as said I'll do a pull. 

Cheers,
CK

**Comment by vyp** [comment]
1. I understand, I do! But my point was you've already gone through the issue tracker and found out about the threads. But of course it's fine if you slowly comment wherever you can at your own pace. That's what I try to do as well.
2. Well then the real reason is because things have changed then. There's situations where years-old threads are still relevant to the day, and closing them wouldn't really be right. Sure, it's sad that no one has found the time to resolve a relevant issue that's been open for a long time, but it'd be worse to just close it simply because it couldn't be acted upon. At one point, you have to accept that an issue might stay open for quite a while. While staying open for a long time is definitely undesirable, that's usually a lesser concern than the issue the thread is actually talking about. And personally speaking, I don't have the time to go through all the old threads and update myself on the most up to date information and check if the issue is still relevant. Nevertheless I still try to do this from time to time. For example, check out most of the last 8 or so closed issues [here](https://github.com/nylira/prism-break/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) (at this point in time).
3. Yes I agree with you. But I'm no expert either, so going through what everyone says, and researching it, can take a fair amount of time to come to some conclusion on whether or not a tool may be good to list on prism break. That's why the issue tracker exists, so that people who are more knowledgeable can weigh in to relevant threads with their expertise.
4. Completely understand, sorry if I came across as insensitive. Again, it's 100% cool if you don't want to spend time conversing about all these issues you raised in the project-specific threads, but I've closed this because, for the prism break maintainers, I thought that it would unfortunately only further clutter the issue tracker. But remember of course that doesn't necessarily mean all your concerns are invalid or anything, they're just not in the right place to be fully helpful in my view.

> More because in my point of view security must be up2date ALWAYS and it should stay on the line with leaked documents and possible threats.

Understood and agreed. It's just an unfortunate reality that a lot of us prism break maintainers don't have much time these days to keep up to date with everything that's happening. :/ (But I personally still try to do my best whenever I can.)

> I see a lot of things here I can't recommed at all but as said I'll do a pull.

That would be awesome. :+1: :+1: Remember, if you do find the time to do this, it might also be beneficial for you to read up a bit on the relevant threads that you linked in case anyone mentioned any new information that you didn't know, or in case there were already other reasons for a project's inclusion/exclusion.

**Comment by hasufell** [comment]
> The argument that it shows (maybe) outdated apps are stupid. Cause every app is vulnerable at the end with effort.

I'd call that a stupid argument. Coming up with a 0-day exploit is a completely different thing than trying the latest __public__ vulnerabilities for a given app. If that is your understanding of security, then I don't know what else to talk about.

**Comment by Atavic** [comment]
Regarding Protonmail, there's a comparison with Tutanota and Lavabit in this [gist](https://gist.github.com/CHEF-KOCH/f5c289c8097d6d1699bce3eae0afa0a5). 
Also related:
#1611 
#1204
