### ISSUE TITLE
Add Waterfox

### ISSUE THREAD

**Issue by geplus** [nylira/prism-break#1789]
Hi, 
is some years that I personally don't consider Firefox a secure browser anymore.
The introduction of telemetry, WebRTC,pocket, sponsored tiles, the use of google analytics (https://www.ghacks.net/2017/07/13/privacy-blunder-firefox-getaddons-page-google-analytics/) and the goolgle web search by default in unaceptable for users' privacy.

The privacy oriented, open-source alterantives that I personally trust are:

- Waterfox
https://www.waterfoxproject.org/
https://github.com/MrAlex94/Waterfox

-Pale Moon
https://www.palemoon.org/
https://www.palemoon.org/licensing.shtml
https://www.palemoon.org/redist.shtml (I think Pale Moon's  redistribution license greatly protects the users' privacy)

And please, If you still want Firefox on prism-break, please mention the other privacy issues on the page https://prism-break.org/en/projects/mozilla-firefox/ , expecially  the use of Google Analytics on the about:addons page.

**Comment by strugee** [comment]
Palemoon has already been suggested in #1385.

I'm retitling this bug to be only about Waterfox; please file separate issues for anything else.

**Comment by Atavic** [comment]
:+1: for any firefox fork. Newest firefox versions are killing many addons.

**Comment by yegortimoshenko** [comment]
Waterfox is a soft fork of Firefox, meaning it follows Gecko releases and mostly can be treated as set of patches on top of Firefox. This means it's less likely to go stale than hard forks like Pale Moon.

I agree with all patches except not enforcing signatures on add-ons. I think enforcing Mozilla signature on add-ons and AMO (add-on review) significantly reduces exposure to malicious add-ons (e.g. that inject ads or steal card info), and Firefox add-ons store is pretty good at not censoring stuff (e.g. they allow AdNauseam). This argument is comparable to saying that installing software from distributions is safer than directly from developer's website (or from some other untrusted source).

I should point that this is a major concern: enforcing digital signatures on software is very useful for malware protection. Every distro does this, F-Droid does this, so it's only fair for browser to do that, too.

I have a major problem with the fact that, similarly to #1385, they pretend to have a trademark on Waterfox name and logo, but it isn't registered in US or in UK: https://www.waterfoxproject.org/terms

> You are not granted any trademark rights or licenses to the trademarks of Waterfox Limited or any party, including without limitation the Waterfox name or logo.

* US trademark registry: http://tmsearch.uspto.gov
* UK trademark registry, country of developer's residence: https://trademarks.ipo.gov.uk/ipo-tmtext (limit search to class 9, the one that includes browsers)

However, they do not seem to limit "trademark" usage in any way, or at least I haven't found any source that they do. In this case this is only a latent problem.

---

I think this is not enough to warrant addition, because all patched-out functionality can be tweaked on about:config page. I think it would be more viable to recommend a `prefs.js` file that enforces more privacy-respecting settings, as suggested in https://github.com/nylira/prism-break/issues/1031#issuecomment-83701629.

**Comment by beerisgood** [comment]
Waterfox isnt up2date like Firefox and doesnt include any pros

**Comment by Hillside502** [comment]
"pros"?

**Comment by Atavic** [comment]
That means:

"Doesn't include any advantage against Firefox".

**Comment by yegortimoshenko** [comment]
Only better defaults.

**Comment by yegortimoshenko** [comment]
@Flaganan43: perhaps you're right they should have made it an option. It is an option on all Firefox channels except release, `xpinstall.signatures.required`.
