### ISSUE TITLE
Fix broken security in-a-box Thunderbird setup link

### ISSUE THREAD

**Issue by Daraf-IT** [nylira/prism-break#1794]
In email client section I read "Here is a guide by Security In A Box to encrypting your email with Mozilla Thunderbird, GNU Privacy Guard (GPG), and Enigmail." but link is a 404 error.
Maybe it has to be delete or find same guide in a new site.

**Comment by vyp** [comment]
https://web.archive.org/web/20161219220819/https://securityinabox.org/en/thunderbird_main is an archive.org link, but I'm not sure if archive.org links should be listed on prism break, because they're static and will never be updated or anything. Although to be fair, it's not like most online guides such as this are regularly updated either, so listing an archive.org link probably wouldn't be that different in the end. But in my opinion that's still a weak argument to keep it, so if we can't find a canonical source for this, I'm more inclined to just remove this link unfortunately.

@Daraf-IT thank you for reporting this!

**Comment by vyp** [comment]
Actually I spoke too soon, it's linked directly on the homepage: https://securityinabox.org/

So the new link is <https://securityinabox.org/en/guide/thunderbird/windows/>. So this link simply needs to be updated.
