### ISSUE TITLE
Add https://easycrypt.co for email encryption

### ISSUE THREAD

**Issue by ghere** [nylira/prism-break#1798]

**Comment by hasufell** [comment]
- github: https://github.com/EasyCrypt-co
- concept: https://easycrypt.co/under-the-hood/
- so-called security audit: https://easycrypt.co/wp-content/uploads/ec/EasyCrypt_audit_announcement_r06.pdf

I am not 100% sure if all the server-side code is open. And I find it a bit odd that the concept is not described in a paper. It's not a trivial thing to claim anonymization over e-mail.

**Comment by Hillside502** [comment]
See conversation at:-
https://github.com/privacytoolsIO/privacytools.io/pull/316

**Comment by ghere** [comment]
1. As our site states clearly, the email anonymization functionality is not included in the current version. Neither did we make such claim in our GitHub listing. 

2. Server side code is not open at present time. It is not needed to verify that user password never leaves the user PC, and that no user data ever leaves the use PC unless encrypted by user password, private key or public key of the recipient. Opening client code is 100% sufficient for this.

3. Our technology is fully and openly described in our website, including the not yet implemented anonymization. See https://easycrypt.co/under-the-hood/

4. EasyCrypt servers are not blacklisted by Google. Register at https://easycrypt.cio with a gmail account and see for yourself.

**Comment by hasufell** [comment]
> Server side code is not open at present time. It is not needed to verify that user password never leaves the user PC, and that no user data ever leaves the user PC unless encrypted by user password or public key of the recipient. Opening client code is 100% sufficient for this.

That's a no-go and means we have no way to trust your service if we don't know what runs on your servers, what you do with the data and so on.

**Comment by ghere** [comment]
That's up to you of course but I find the "common wisdom" that opening source code of the server is in ANY way conducive to privacy, to put it mildly, erroneous - and even misleading. If the service provider  opens the server code, what guarantee does the user have that the SP does not change it on the server? Zero. 

Client side code on the other hand can be inspected by the user.

**Comment by hasufell** [comment]
> That's up to you of course but I find the "common wisdom" that opening source code of the server is in ANY way conducive to privacy, to put it mildly, erroneous

Sure that's possible. But when the code is AGPL-3 for example, legal steps can be taken in case that is discovered.

Everything starts with __trust__. There cannot be any trust if the server code is not open. If it is open, it doesn't mean there is 100% trust, but it's a start.

**Comment by ghere** [comment]
I beg to differ. Relying on trust in service providers is a really bad practice.  The only thing you should be telling your readers to TRUST is the fact that service providers will cave in under a subpoena. Service providers (EasyCrypt included) should be recommended ONLY based on hard evidence that the client side code provides.

**Comment by hasufell** [comment]
> Relying on trust in service providers is a really bad practice.

Yes, which is why we prefer decentralized solutions that don't rely on service providers. If we recommend service providers however, we have higher standards than the service provider telling us "oh, we like privacy".

**Comment by Zegnat** [comment]
Did anyone look at how login works? I wish I had the time to look through the code, but I really haven’t had the moment. The following sentence stood out to me in the audit:

> EasyCrypt user password is the most critical piece of information since it
can be used to login into the EasyCrypt account and decrypt any existing emails.

This makes it sound like the user’s password is both 1) submitted to EasyCrypt for authentication and 2) used to decrypt the private key which enables further decryption. But if this is the case, it means EasyCrypt gets access to my password and thus to my private key.

> Relying on trust in service providers is a really bad practice.

There also seems to be a definitive trust factor involved here. Other people’s public keys are provided to the user through EasyCrypt. This means EasyCrypt might be telling me an email came from Bob, but in reality the email came from Eve and EasyCrypt is just using Eve’s public key instead. There is no way for the user to see this, unless I am reading the under-the-hood page wrong.

You are entrusting EasyCrypt to do your key management, and this key management happens on the server outside of the client-side code.

This is where an open-source server-side solution can help. Because I can chose to run that myself. Once again putting me in control of key management. I totally understand why this was left out to make it easier on the user, and that is a fair trade-off, but should be handled as what it is: a trade-off.

**Comment by ghere** [comment]
How EasyCrypt password works is described loud, clear and in detail in the Under the Hood section of our website (go to "How it Works" to get to it). Please read it instead of  "making it sound like..."  EasyCrypt has access to your private key, which it emphatically does not.

**Comment by Hillside502** [comment]
How come?
https://easycrypt.co/ has `HTTP Strict Transport Security (HSTS) with long duration deployed on this server` --- but **not** https://webmail.easycrypt.co/login/

SSL Server Test: easycrypt.co (Powered by Qualys SSL Labs)
https://www.ssllabs.com/ssltest/analyze.html?d=easycrypt.co

SSL Server Test: webmail.easycrypt.co (Powered by Qualys SSL Labs)
https://www.ssllabs.com/ssltest/analyze.html?d=webmail.easycrypt.co

**Comment by vyp** [comment]
@ghere I'm sorry but could you point out where exactly? I'm guessing the key management section, but it doesn't really describe any mechanisms there, just focuses mainly on why it does key management. :confused: I'll admit that I've only had a cursory look at the page though.

But yeah I still think @Zegnat's concerns are sound, cause after all EasyCrypt is storing and managing our keys.

**Comment by Zegnat** [comment]
@ghere:

> How EasyCrypt password works is described loud, clear and in detail in the Under the Hood section of our website (go to "How it Works" to get to it).

Loud, clear and in detail? It leaves several things to be assumed unless someone reads the code. I already admitted I didn’t read the code, that’s why I asked if anyone else had. I will admit I only had a cursory read (again because of time constraint) and would have been perfectly happy if you had refuted some of my statements.

I went to read the section on login again, with more care, and still had to make several assumptions. Here follow my thoughts when I was reading about the login. I am always happy if someone refutes me with facts though, and if anyone wants to point me to the code that handles my concerns that would be even better.

(The following quotes are from the under the hood page.)

> The password is hashed on the client with a user-specific salt and sent over TLS to EasyCrypt webmail server.

Where does the user’s browser get this salt from? I am assuming (because it isn’t specified) that this is somehow based on either the email address or is provided by the EasyCrypt server.

I also don’t know what hashing is being done. As is, this description might describe a truly randomised salt stored by EasyCrypt going together with the user provided password through a high work-factor Argon2 implementation. It could also describe `MD5( password | email )`. That later would almost make it easy to figure out the user’s actual password.

> At the server it is hashed again using bcrypt with a user-specific salt and compared to a stored hash value.

I am assuming that the developers know what they are doing and that this “user-specific salt” is a different one from the one used in the previous step. But am again forced to assume because it isn’t detailed.

> If the comparison is successful, the server sends to the client the user’s private key encrypted by the user’s password, as well as a randomly generated nonce encrypted to the user’s public key. The client decrypts the private key with the password, and sends the decrypted nonce back to the server. If the received nonce matches the original, the server allows the client to access EasyCrypt Webmail.

This is fine. Though hardly detailed. I am hoping that this is protected against brute-force attacks by limiting the amount of nonce guesses. I am also hoping it uses a big nonce to counter against guessing. (A randomly generated nonce can be `a`, it can also be 500 characters. The describing terms do not describe anything.) Hoping because this would be server-side and uncheckable.

**Side note:** Personally I wouldn’t have asked the client to decrypt something, as the decrypted message might be brute-forced. Instead I would have asked the client to sign something: send them their encrypted private key and a short random unique message (your nonce), then have the client sign the message with the private key and send the signature (no need to resend the message, you already have that) back. You can then validate the signature using the public key you already have on file.

**Comment by Atavic** [comment]
>Did anyone look at how login works?

By spelunking [here](https://github.com/EasyCrypt-co/hamlet/blob/master/program/js/publickey.js) I get [**PublicKey.js**](https://github.com/diafygi/publickeyjs)

>This is a simple javascript library that allows you to search for PGP public keys on SKS keyservers and Keybase.

**Comment by ezcdev** [comment]
The source file to which you refer is part of RoundCube source code that's used for Mailvelope compatibility. Our plugin does not use this code and in fact disables functionality, as we have implemented our own key management. Thus this code is not relevant to EasyCrypt Hamlet client.

**Comment by yegortimoshenko** [comment]
Backend is proprietary, source code of free components has not been updated since Jul 5, 2017 which is before this issue has been opened. Closing based on that.

(Besides, service heavily uses Google tracking, fonts, etc.)
