### ISSUE TITLE
Adnauseam - Browser Extension

### ISSUE THREAD

**Issue by rafaelrpinto** [nylira/prism-break#1802]
This is news for me, I'm still wrapping my head around the proposal, but it might be worth looking into. 

Apparently Chrome and Pale Moon blacklisted it. 

> As online advertising becomes ever more ubiquitous and unsanctioned, AdNauseam works to complete the cycle by automating Ad clicks universally and blindly on behalf of its users. Built atop uBlock Origin, AdNauseam quietly clicks on every blocked ad, registering a visit on ad networks' databases. As the collected data gathered shows an omnivorous click-stream, user tracking, targeting and surveillance become futile.

> AdNauseam is a free browser extension designed to obfuscate browsing data and protect users from tracking by advertising networks. At the same time, AdNauseam serves as a means of amplifying users' discontent with advertising networks that disregard privacy and facilitate bulk surveillance agendas.

Site: https://adnauseam.io/
Source: https://github.com/dhowe/AdNauseam
Related paper issued by the author: http://www.aprja.net/surveillance-countermeasures-expressive-privacy-via-obfuscation/

**Comment by Zegnat** [comment]
This seems to follow [TrackMeNot](http://cs.nyu.edu/trackmenot/) (issues #201, #540).

I am not actually sure there is a lot of proof of the effectiveness of these types of plugins. Besides, how is this better than having a strong uBlock filter that will not let your browser connect to ad servers at all? Meaning you make 0 contact with them and cannot inadvertently leak information. By “clicking” all ads (loading all the pages) it is hard to say what information you hand over that could still be used for things.

I am … sceptical.

**Comment by hasufell** [comment]
There is no proof either that not clicking on ads makes you less vulnerable to tracking. Talking about proof in this context is not useful.

Obfuscation is just a different approach compared to minimizing the data you "leak".

**Comment by Zegnat** [comment]
> There is no proof either that not clicking on ads makes you less vulnerable to tracking.

True. However, if you block connections to an ad server there is literally no way for them to track you. Which is why I would recommend having uBlock block the connection rather than run a uBlock fork that specifically connects with all links.

**Comment by hasufell** [comment]
> However, if you block connections to an ad server there is literally no way for them to track you.

Unfortunately, it's not that easy. You'd have to have complete protection against any form of fingerprinting and trust all websites you visit. That's pretty much impossible.

**Comment by Zegnat** [comment]
I am speaking only in the context of AdNauseam. It is built “atop uBlock Origin” and “quietly clicks on every blocked ad”. This means you go from blocking ad companies domains from connecting at all (as blockers like uBlock do) to actively engaging them with your browser.

I don’t have the time to check what it does or doesn’t click on right now, but would be appreciated if someone could look into it. Because if it lets adtech provided javascript run, even just so it can get a link to click on, that means the ad networks are still able to track the pages you have visited. While your clicks are useless to them, they are still given a chance to fingerprint and subsequently track your interests.

This is my main concern. Adtech doesn’t just track by what you click on, they track by what you read and look at. A browser extension that wants to click links will have to let an ad load, thus giving the ad company access to where the user is on the web. An adblocker that does not want to click on links has no reason to allow anything provided by the ad company to load, which doesn’t suffer from this same problem.

**Comment by hasufell** [comment]
> Because if it lets adtech provided javascript run

https://github.com/dhowe/adnauseam/wiki/FAQ#how-does-adnauseam-click-ads

**Comment by Zegnat** [comment]
@hasufell that’s how it clicks, not how it discovers the links to click.

Many (most?) adtech create links either by having javascript run or an iframe load on the page you are visiting. My concern is that AdNauseam would let that happen to be able to discover the links in the first place. While strict blockers will not let such resources load.

**Comment by hasufell** [comment]
Just read the FAQ maybe: https://github.com/dhowe/adnauseam/wiki/FAQ#how-does-adnauseam-block-malicious-ads

**Comment by Atavic** [comment]
@Zegnat Some authors of TrackMeNot are involved.

>By loading all the ads it is hard to say what information you hand over.

From the user side, it's the same as browsing normally. The difference is from the tracking side.

>There is no proof either that not clicking on ads makes you less vulnerable to tracking.

Yes, the point is to give so much info to tracking servers that the database about your interests has no valid results. Adnauseam has the option to make it quiet or aggressive: click-probability, if raised enough, triggers the script detection on google.

Used sparingly, it is just an obfuscation option.

**Comment by Atavic** [comment]
@Zegnat Some authors of TrackMeNot are involved.

>By loading all the ads it is hard to say what information you hand over.

From the user side, it's the same as browsing normally. The difference is from the tracking side.

>There is no proof either that not clicking on ads makes you less vulnerable to tracking.

Yes, the point is to give so much info to tracking servers that the database about your interests has no valid results. Adnauseam has the option to make it quiet or aggressive: click-probability,
if raised enough, triggers the script detection on google.

Used sparingly, it is just an obfuscation option.

**Comment by hasufell** [comment]
Maybe just read the [paper](http://www.aprja.net/surveillance-countermeasures-expressive-privacy-via-obfuscation/)

> AdNauseam, perhaps the most direct descendant of TrackMeNot, is a browser extension designed to obfuscate browsing data and protect users from surveillance and tracking by advertising networks. The plugin works with existing adblockers to block ads on visited pages, but then quietly clicks each ad in the background, polluting user profiles and creating mistrust between advertisers and the networks they pay for clicks. In addition to protecting users, AdNauseam attempts to amplify their discontent with advertising networks and shift the balance of power between the trackers and the tracked. One unique property of AdNauseam is its support for the notion of sousveillance,[3] via its ‘AdVault’ feature, which allows users to explore interactive visualizations of the ads they are served, providing an algorithmic glimpse into their profile as perceived by the advertising networks (Howe et al.).

Clicking on the ads is not _just_ about obfuscation wrt privacy, it's also about breaking the trust between ad provider and their own data. This is a form of economic cyberwarfare, which is exactly what prism-break is about.

**Comment by Atavic** [comment]
As a big seller, company X uses google for advertising. If X sees that the number of clicks coming from google ads has raised, but the selling related to those clicks is zero, X will then ask google for a refund (as happened recently) and next time X and google sign a contract, the price-per-ad will be lowered.

**Comment by Zegnat** [comment]
I didn’t have time for reading the FAQ or the paper, which is why I asked for clarification here in the issue in the first place. My issue isn’t really with clicking ads, it is with allowing adtech to build profiles about you. These profiles are not just based on what you click on, they are also heavily based on what websites you visit and what articles you read. If you load adtech JavaScript on a page, they know you are on that page, they know what you are reading, they can fingerprint your browser and update your personal profile.

That’s why I asked whether AdNauseam was going to let adtech scripts run on websites, allowing third-parties to see what you are looking at. If it did, I would not recommend AdNauseam as an equal to uBlock, as uBlock will not let those scripts load and will not provide adtech with information about what you are looking at.

I am not opposed to the idea of poisoning the profiles that are being created about me. I just don’t find it clearly described how AdNauseam does this. <i>Clicking visible ads while hiding them</i> sounds like a valid “form of economic cyberwarfare”. <i>Running third-party JavaScript so a visible ad can be created and then clicked</i> sounds like you are removing a security feature other adblockers are offering.

Having now read the FAQ and paper (that doesn’t include any information about the tech they want to use to reach their goal) I still haven’t seen a clear answer to this. Only that [you can “Block Malicious Ads”](https://github.com/dhowe/adnauseam/wiki/FAQ#how-does-adnauseam-block-malicious-ads) which includes “beacons, non-visual trackers, and other potentially malicious content”.

Currently this [will block Google Analytics](https://github.com/dhowe/AdNauseam/issues/855) JavaScript from loading. If any of the lists blocks all third-party Google JavaScript, the entire use-case given by @Atavic is moot. Google wouldn’t be allowed to generate ads and AdNauseam has nothing to click. Then you are not clicking the ads on the biggest advertising platform in the world and making AdNauseam only marginally different from every other adblocker under average use.

In short I am against recommending an adblocker that:

1. possibly loads more third-party JavaScript than other blockers, (or, if it doesn’t, will not click the majority of ads I personally come in contact with online because they are JS based)
2. possible allows adtech to create better profiles of what you visit and read online (by virtue of loading adtech resources on said pages).

And the win is that you throw off some click statistics? Click statistics that are often more important to the “innocent” buyers of advertisement than to the adtech companies themselves.

No blocker is infallible, and neither am I, so if someone has a different opinion that’s good. And if someone has actually looked into how the extension handles third-party resources within the pages you visit, I would still love to hear about it. I will not have the time to look through the code or run tests myself within a reasonable timeframe.

**Comment by yegortimoshenko** [comment]
I think this addon would be a valuable addition. It might be worse in terms of overall surveillance protection, but it can be used to devalue advertisement profile that was already built for the user, which user can't directly delete. Thus AdNauseam can be used to effectively "delete" the advertisement profile by filling it with noise.

Additionally, if many people were to start using AdNauseam, advertising industry might reduce its grip on the internet and more content creators might start using alternative funding options. That would reduce amount of tracking for everyone and not just AdNauseam users.
