### ISSUE TITLE
Add hackmd.io

### ISSUE THREAD

**Issue by flapperleenie** [nylira/prism-break#1829]
Real-time collaborative in-browser markdown editor. https://hackmd.io/

**Comment by alerque** [comment]
Why add this?

* Is it open  source?
* Does it have any privacy or security related features that stand above other options?
* What commercial product would this replace?

**Comment by vyp** [comment]
> Is it open source?

It is, https://github.com/hackmdio/hackmd.

> What commercial product would this replace?

It would go into the productivity category.

**Comment by strugee** [comment]
Hmm. This tool looks really nice, but I'm wondering if it's really better than e.g. Etherpad. The Productivity section is bordering on overloaded.

**Comment by flapperleenie** [comment]
It's definitely more usable than Etherpad: supports markdown, comments, FLOWCHARTS <3, slides, ... and does not crash when more than 15 people are online.

**Comment by Hillside502** [comment]
Open Source HackMD Alternatives - AlternativeTo.net
https://alternativeto.net/software/hackmd/?license=opensource

Open Source Etherpad Alternatives - AlternativeTo.net
https://alternativeto.net/software/etherpad-lite/?license=opensource

**Comment by yegortimoshenko** [comment]
Original authors have forked this into a proprietary product:

https://hackmd.io/c/news/https%3A%2F%2Fhackmd.io%2Fs%2FBJCqhRWaW
https://github.com/hackmdio/hackmd/issues/579

This is a hard fork, i.e. changes cannot go from CE to EE. This is due to licensing: EE uses the last MIT-licensed version, and CE is under AGPLv3. From one of the developers:

> According to the license we going to take (AGPL 3.0). We will not directly merge/integrate the community contribution to CE going forward. But this doesn't mean this repo will no longer maintained by us, we'll keep an eye on and might land some fixes when we able to do it.

From CE maintainer:

> HackMD EE as well as HackMD.io are forks. They will move into different directions in future. Right now most of the code is shared. Of course over time there will be changes that make the version incompatible. Then it's probably time to rename it. Right now I would say that it's close enough to stay under the original name.

Currently, recommending one would result in recommending the other. For that reason, I think this should be closed for now and perhaps reconsidered at later date when community edition gets renamed.

I should explicitly note that this is not an "open core" situation. This is a proprietary license-incompatible fork of the codebase.

**Comment by alerque** [comment]
That's a pretty disappointing turn of events, but that's for reporting on it. I agree we should probably hold off on this until some renaming happens, there is evidence the open source version is getting community traction, or maybe both.

**Comment by bumbleblue** [comment]
Thanks for looking into this! I'll forward this to the folks at hackmdio.
