### ISSUE TITLE
Solus Linux as an alternative

### ISSUE THREAD

**Issue by cristianarbe** [nylira/prism-break#1832]
Definitely not an expert on this, but from the point of view of a user concerned about privacy but not so tech-savy, I haven't managed to get any of the distros recommended to work on my laptop (WiFi + GPU issues) and was wondering whether Solus (https://solus-project.com/) would be an option as it works out of the box, it's community driven, not derived from Ubuntu and haven't found any security/privacy issues in the past myself.

I haven't found any issues here about it so I think this hasn't been discussed before. Feel free to close this if someone did.

**Comment by hasufell** [comment]
I find solus interesting, but I don't see them focussing explicitly on privacy or security. Our reasoning was to include distros that either

1. are one of the biggest linux distros out there with strong commitment to free software (manpower + ethics = privacy/security... or so we hope)
2. specifically have technology or concepts applied that increase privacy/security for the end user (e.g. QubesOS or SubgraphOS)

Afais Solus isn't either of those, although it's an interesting distro.

**Comment by hasufell** [comment]
> https://solus-project.com/forums/viewtopic.php?t=1330

I've read the thread, I don't see something significant. Can you be more precise?

> https://solus-project.com/categories/security/

I see news posts from 2016. What do you mean?

> https://www.reddit.com/r/SolusProject/comments/5id8kg/how_solus_team_provides_security_of_their_distro/

I don't see much interesting there either. Debian has https://security-tracker.debian.org/tracker/ and pretty much every big linux distro has a dedicated security team.

Wrt hardening (stack smashing, RELRO, ...) also see https://wiki.debian.org/Hardening and https://wiki.debian.org/ReleaseGoals/SecurityHardeningBuildFlags

**Comment by cristianarbe** [comment]
Just some quick note [from the main dev from Solus](https://www.reddit.com/r/SolusProject/comments/6c50vd/where_can_i_find_the_privacy_policy_for_the_solus/?st=j3gmgab5&sh=5dcf0b87):

> - The server logs are automatically rotated, and are only HTTP access logs like any web server. They're not used for analytics and nuke themselves over time.
> -     We don't collect any data.
> -     We use cookies on some of the websites to make login work. Some third party mechanisms may store their own cookies (such as the antispam measures provided by Google)
> -     No information is collected from your OS
> -     Some applications may have their own in-built telemetry, such as Firefox. This goes to Mozilla and Solus has no involvement in it. You may also turn this off.

**Comment by quantumpacket** [comment]
@hasufell I was just posting the links to this issue as reference for others. Was not pointing out anything in particular.

**Comment by baimafeima** [comment]
Solus user here. While I certainly would want Solus to be featured on prism-break.org, there are a few things I'd like to see in Solus myself:
- `independent security audit` of server infrastructure, packaging procedures, etc. 
- `removal of proprietary googleapis` from main website (don't want IP redirects and slows down the site in censorship-affected regions)
- mitigating the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) to ensure continued operations and `sustainability` for end-users
- a team of external or internal `security advisors` beyond founder and current core team
- a dedicated `libre-kernel` and an `opt-out-of-proprietary-software option` (i.e. box to tick) in the software center settings to only display free software
- a `public endorsement` of at least one privacy-oriented organization or a clear `social contract`, i.e. demonstrated _ethical_ commitment (as of now Solus is more pragmatic than ethical and I'd like to see both)
- a demonstrated commitment of the core team `to actively use privacy-enhancing technologies` wherever possible or active `work with upstream privacy and security projects` to integrate their technologies better
- a commitment to `privacy by design`, i.e. it shall be as accessible as possible for all in order to not leave those most vulnerable who are the least technically-inclined
- [reproducible builds](https://reproducible-builds.org/) of _all_ software packages
- [DNSSEC-secured](https://dev.solus-project.com/T4731) Solus website

That being said, I think Solus is the _best_ independent candidate (e.g. no spin-off like Mint and elementary or community edition like Ubuntu MATE and Ubuntu Budgie) to replace the aging Ubuntu architecture on the desktop and to date represents the most _modern_ and _usable_ approach (read beginner-friendly) for people migrating from proprietary systems such as Windows and macOS. If there is any operating I'd recommend for these users, its Solus without a doubt. For those who want to dig deeper, there's Tails, Whonix, Qubes OS and the like.

**Comment by hasufell** [comment]
> best independent candidate

Why? All I've seen until now are discussions of unimplemented features and "I'd like to have"-lists. I cannot really follow what you guys are getting at. Again, our strategy was to list either __the very big distros with strong free software focus__ or distros that have __actual security/privacy relevant technology__.

Don't underestimate manpower when it comes to distros.

**Comment by strugee** [comment]
Also if this:

> a dedicated libre-kernel and an opt-out-of-proprietary-software option (i.e. box to tick) in the software center settings to only display free software

really doesn't exist, that seems like a disqualifier to me.

**Comment by Atavic** [comment]
I see JonDo, Tails & Whonix. The closest are Qubes, Subgraph OS or Kodachi.

**Comment by strugee** [comment]
> I see JonDo, Tails & Whonix. The closest are Qubes, Subgraph OS or Kodachi.

Huh? What's this about?

**Comment by strugee** [comment]
I also think we've arrived at a consensus. Unless there are any compelling objections I'd like to close this.

**Comment by Atavic** [comment]
>What's this about?

prism-break > gnu-linux > operating-systems (live)

**Comment by strugee** [comment]
Sorry, I still don't follow how that's relevant to the current discussion.
