### ISSUE TITLE
What do you think about Cloudflare?

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#1843]
https://github.com/mozilla-mobile/focus-android/issues/1743

and this add-on?

https://addons.mozilla.org/en-US/firefox/addon/block-cloudflare-mitm-attack/

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
xing reference from similar project: https://github.com/privacytoolsIO/privacytools.io/issues/374

**Comment by Atavic** [comment]
Most has been said on the issue opened by @StopMITMInternational

- site owners use CF as a defense against denial of service attacks

- users don't want to be monitored by CF (a wishful thinking)

Currently CF protects at least two million sites. Try browsing on a VPN and you get captchas (images to click) to confirm you're a human. That's for securing the site, but the implication is that you're definitely fingerprinted with google captcha.

**Comment by anthologist** [comment]
I'm hopeless about what's becoming the internet. Cloudflare is trying to centralize the web, seeing all the traffic before it reaches the website the user called, like a reverse proxy. Meanwhile the user sees that happy green padlock on the url bar, and knows nothing about what's happening.
This is a tragic situation, but not many people care nowadays.
Kudos to that addon author.

**Comment by n8v8R** [comment]
don't you wonder/worry no more, the advocates of privacy and internet freedom actively supporting/sponsoring CF

https://www.robtex.com/dns-lookup/www.mozilla.org
> cname | www.mozilla.org.cdn.cloudflare.net

**Comment by alerque** [comment]
That means almost exactly nothing @n8v8R. Quite a number of projects PRISM-Break links to host on CDNs including CloudFlare. The fact that Mozilla's front end site is behind it brings almost nothing to this duscussion.

Speaking of which what _is_ this issue supposed to be about? CloudFlare is not something PRISM-Break recommends (we don't even have a category for that sort of thing) and we typically advocate for software where you don't have to trust anybody in the middle of your connection. What is this issue even open for? Adding an addon recommendation? I don't see any good reason to list this addon. If your threat model includes CF MITM bugs then get off the public internet and use Tor ... or use something more comprehensive that keeps anything interesting about you out of your browsers hands in the first place.

Blacklisting one CDN (even if it is the 900 pound gorilla of CDNs) just isn't the right approach to any problem. I move we close this issue.

**Comment by n8v8R** [comment]
> Please do your own research before trusting these projects with sensitive information

Consider it part of research and awareness, if you like.

**Comment by strugee** [comment]
Yeah, I'd tend to agree with @alerque. To be honest I'm also not entirely convinced that CloudFlare is a massive problem... I dunno. CDNs have been a thing for a very long time, and lots of services terminate TLS on servers run in Amazon, Google, etc.'s clouds. That seems equally as bad, and I'm not sure how CloudFlare is significantly different.

Regarding Google Captchas specifically:

> Try browsing on a VPN and you get captchas (images to click) to confirm you're a human. That's for securing the site, but the implication is that you're definitely fingerprinted with google captcha.

This isn't a reason to distrust CloudFlare. If you don't want to be fingerprinted by Google's captcha system, what you should do is try to block Google's captcha from loading. Going after CloudFlare because they happen to use a Google captcha seems like a red herring. It's just not logical.

**Comment by strugee** [comment]
Closing basically for the reasons @alerque mentioned. I don't really think there's a reasonable action item here.

**Comment by n8v8R** [comment]
re-Captcha are deployed not just by CF and are perhaps a valid way of protection. 

@strugee > I'm also not entirely convinced that CloudFlare is a massive problem... _I dunno_ ... ...and I'm not sure how CloudFlare is significantly _different_

Just in case you would be interested anyway

The concern is rather about the CF's design of TLS handling, maintaining **TLS session keys** ([on their edge server](https://blog.cloudflare.com/keyless-ssl-the-nitty-gritty-technical-details/)) in between client  browser and content endpoint, acting as MitM broker, which appears different from the mentioned AWS and Google, or other CDN hosts.
Neither of the latters appears either to act as reverse proxy and actively injecting tracking tags into their headers like CF [does](https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-CloudFlare-handle-HTTP-Request-headers-).

It is curious that with the improvements (drastically curtailing MitM) of [TLS 1.3](https://tools.ietf.org/html/draft-ietf-tls-tls13-22) CF is [shy](https://support.cloudflare.com/hc/en-us/articles/227172348) of deploying TLS 1.3 between their edge server and the content endpoint.
> CloudFlare terminates client TLS 1.3 connections at our edge, and does not require you to support TLS 1.3 on your servers. Furthermore, we do not currently support TLS 1.3 from our edge to origins or plan to support this in the immediate future, so the only reason to enable TLS 1.3 on your servers is if you wish to do so for your own purposes.

Another point are CF's free of charge SAN certificates each covering a myriad of (sub)domains hosted on (cdn).cloudflare.net with a single certificate. The SAN certificates and relevant keys are issued to CF and not the content owner.

Users are commonly and blissfully unware that there are only securely connected to CF but not necessarily beyond, or that CF might be reading the encrypted traffic and injecting header tracking tags. There is too quite a number of content owners hosting their content on CF and being unaware of the way their content is being delivered, only seeing that is being delivered and the (green) padlock showing in the browser’s url bar, notwithstanding content for apps where there is no visual indicator about the TLS connections in the background.

Incidently Mozilla is keeping certain content out of CF' reach, like
https://bugzilla.mozilla.org
https://addons.mozilla.org

Why, perhaps it is deemed sensitive/critical and cannot be trusted to CF? 
Or why Github moved from CF, other than commercial considerations?

**Comment by alerque** [comment]
@n8v8R Multiple places in your post are conflating CloudFlare in particular with CDNs in general. Also it's not clear to me that you understand how TLS works. By design you have to have the certificate at the termination point. This is true for any CDN and applies whether the certificate is registered to the CDN provider or the host. In some cases CDN's require hosts to hand over a copy of the certs registered to them for use on the CDN machines. This is arguably worse that CF's preferred method of issuing subdomain certs to CF directly. Also there are technical reasons to keep bug trackers and such off of CDNs, bringing that up is basically FUD. Sure there might be private issues in their tracker and security is _one_ issue, but that is likely not the primary reason those domains are not proxied. 

But I digress. I'm not trying to defend CF here (I don't like some of their practices either and don't think some of their policies are good for the internet long term).

The point here is what does this all mean to PRISM-Break? What is the action point? I maintain that blacklisting one CDN as if that would significantly protect users from PRISM like data collection or dramatically increase their privacy in general isn't a solution we should be promoting. Perhaps an extension that warned users before loading content from _any_ CDN would be something we could consider. I also support the recommendation for [Decentraleyes](https://prism-break.org/en/projects/decentraleyes/) which helps to avoid CDN use loading shared libraries from hosts that might otherwise be on their own hosting platforms.

But what action point are you arguing for in terms of PRISM-Break's site?

**Comment by n8v8R** [comment]
@alerque To my understaning upto and incl. TLS 1.2 MitM (traffic decryption) is possible with the session keys and those are being held by CF, as outlined in their documentation, rather than at the endpoint. It would be also my understanding that with TLS 1.3 MitM will be drastically curtailed and encrypted traffic security hardened.

The primary reason to keep certain content on other hosts is probably speculative for anyone else than the content owner.

There was no action I suggested to take and such was not my intention (I did not open this), just to chime on a question raised > What do you think about Cloudflare?, and as stated above > Consider  it part of research and awareness, if you like

Blacklisting CDN would likely lead to a standstill of the large parts of the internet as it known today. To my reckoning raising awareness (at least with that portion of internet users who cares about such matters) however does not hurt.

From my end I just felt compelled to response but else would rest this subject dormant then.

**Comment by alerque** [comment]
> MitM (traffic decryption) is possible with the session keys and those are being held by CF, as outlined in their documentation, rather than at the endpoint.

CDNs like CloudFlare are not a MitM attack and it's not that they can decrypt traffic. They _ARE_ the endpoint. This is how TLS works, not CF specific — hence why your options are handing over your certificate or having the certificate issued to them directly.

> The primary reason to keep certain content on other hosts is probably speculative

Hence why I suggested your speculation that it was because they didn't trust CloudFlare was FUD given that there are also technical reasons they may have based that choice on.

> There was no action I suggested

Commenting after the issue closure and going on about how bad CF might be made it seem like you were making a case for something to happen. If there is no action point to implement on the PRISM-Break site then I think we're done here for now. This issue tracker isn't for raising awareness, it's for discussing what to put up or take down from the PRISM-Break site.
