### ISSUE TITLE
Add Uruk GNU/Linux and Trisquel GNU/Linux 

### ISSUE THREAD

**Issue by hayderctee** [nylira/prism-break#1856]
I just read  issue #1817 about adding Uruk GNU/Linux:
https://github.com/nylira/prism-break/issues/1817

I'm surprising why you do not add Trisquel or Uruk GNU/Linux !
Trisquel is not Ubuntu ,Trisquel rebuild and clean all Ubuntu packages and use them again to make a "CLEAN" Ubuntu for Free Software users, you can check all the packages in trisquel repo, and it's has it's own repo, like Uruk GNU/Linux.
in the defenetion of PRISM Break project :
 "PRISM Break follows the GNU/FSF definition of Free Software and prefers software licensed under a compatible license but may allow other OSI reviewed licenses."
and Trisquel in the list of GNU Page , Not Debian and that's why: 
https://www.gnu.org/distros/common-distros.html
So, you should remove Debian, not Trisquel or Uruk GNU/Linux!
I think there is a big mistak with Trisquel and Uruk GNU/Linux.

**Comment by strugee** [comment]
Trisquel has been discussed before. Please search the issue tracker for details - the tl;dr is that they appear to reuse Ubuntu binary packages which we don't trust. Also, if you could refrain from filing new issues about topics which already have an issue (and refrain from filling issues with more than one topic), that would be great. Please also search for duplicates - otherwise it makes it super hard to keep track of what's been said about a particular subject and what the status of that subject is.

I'm closing since these topics are asked and answered. Cheers, and thanks for contributing to PRISM Break!
