### ISSUE TITLE
Mozilla will remove individual cookie management in Firefox 60

### ISSUE THREAD

**Issue by geplus** [nylira/prism-break#1886]
https://www.ghacks.net/2018/02/26/mozilla-removes-individual-cookie-management-in-firefox-60/

Another un-feature that decrease the user's privacy.

My personal opinion is that this browser can't be recommended anymore.

**Comment by yegortimoshenko** [comment]
This does not decrease user's privacy in any way. First, one can use [Cookie AutoDelete](https://prism-break.org/en/projects/cookie-autodelete/) to manage cookies, second, one should not rely on eyeballing cookie list for their privacy.

**Comment by strugee** [comment]
Agreed. I mean, come on.

There are extensions for this and the new behavior is based on real user research. If you're trying to delete data a certain site has about you, it'll be more thorough, not less.

I'd like to close this.

**Comment by alerque** [comment]
Third this, vote to close.

**Comment by Zegnat** [comment]
Reading that article – and certain comments that sprung in its wake – just reaffirms my opinion that people do not know what cookies are in the first place. It has been ingrained (through cookie warnings, tracking talk, etc) to the populace that cookies are a Bad Thing™ rather than just one of many ways to manage state.

We as tech-aware folks are obviously to blame for spreading some of this FUD. It is always weird to see said FUD bite back when it is being addressed in what looks like a very good UI change on Mozilla’s part.

The developer, Johann, [puts it nicely](https://www.reddit.com/r/firefox/comments/80bhv7/new_cookie_management_or_lack_of_in_nightly/duumo43/) (citing the same “user research” as @strugee, probably):

> The idea is that while you, fellow smart technologists, will have no issues understanding the differences between cookies, LocalStorage and indexedDB, most users actually don’t and thus they don’t realize that websites use all three to store identifying information (we did user research on this). Thus the spec recommends presenting them together, which we now do.

**Comment by strugee** [comment]
@Zegnat +1, couldn't have said it better myself. FWIW I didn't read the research myself, I was just citing the comment you quoted.
