### ISSUE TITLE
Feature Njalla?

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1900]
Perhaps it would be nice to feature [Njalla](https://njal.la/) as an alternative to conventional domain registrars. It is the only option as far as I know that is guaranteed to not require identification and can be paid anonymously in Bitcoin (through onion service).

They also can encrypt all email sent to customer with a provided public GPG key, and domains can be registered without email at all via XMPP + OTP.

Their site also features [Kopimi symbol](https://en.wikipedia.org/wiki/Piratbyr%C3%A5n#Kopimi) which should be read as public domain dedication.

Dividing services into "proprietary" and "free" would be a stretch, but the same point applies to DNS category.

**Comment by Zegnat** [comment]
Full quote:

> When you purchase a domain name through Njalla, we own it for you. However, the agreement between us grants you full usage rights to the domain. Whenever you want to, you can transfer the ownership to yourself or some other party.

In other words. You pay them to hold and manage your domain name, just so you yourself are never registered as an owner.

You’d be surprised how many domain registrars pull the same trick. This can lead to problems, so much so that [Wikipedia has a “litigation” section on the issue](https://en.wikipedia.org/wiki/Domain_privacy#Litigation). So it is a good idea to read the terms carefully, and to have some sort of trust in your middleman. But if you are looking to keep your name off of the registration, what other choice do you have?

Whether this is good or bad, I am not sure. Whether PRISM Break should get into linking to options for domain and hosting providers is another question.

**Comment by yegortimoshenko** [comment]
> You’d be surprised how many domain registrars pull the same trick.

This is the only registrar that owns the domain, i.e. ICANN sees registrar's company and address in private information escrow, instead of customer's information.

Co-founder of Njalla is Peter Sunde, who is also co-founder of The Pirate Bay, founder of Flattr (the only service that continued to accept donations towards Wikileaks back in the day) and co-founder of IPredator (VPN service and operator of several Tor exit nodes with largest throughput in the whole network). So I don't think trust is misplaced.

While for legal/privacy reasons they have to own domains of their users, in practice it's no different from conventional domain "ownership" (which is hardly ownership but rather rent). Transfers to and from service are supported.

This seems like an important battle to fight, given that currently one can't have their own site without showing ID to someone and entering their official name and address.

There's more value in pushing for federation/decentralization if hosting your own instance doesn't involve proving your identity to the most centralized entity on the internet there is, ICANN

**Comment by Hillside502** [comment]
> conventional domain "ownership" (which is **not ownership but rent**)

Precisely!

**Comment by Zegnat** [comment]
> This is the only registrar that owns the domain, i.e. ICANN sees registrar’s company and address in private information escrow, instead of customer’s information.

(They aren’t a registrar, as far as I can find, but that’s pedantry and of no consequence.) They are not the only one according to the Wikipedia section I linked. One example is NameCheap, as described in [one of the Wikipedia sources (PDF)](https://randazza.files.wordpress.com/2009/05/solid-host-v-namecheap.pdf 'Order denying defendant NameCheap’s motion to dismiss') (emphasis mine):

> In addition to functioning as a registrar, NameCheap offers an anonymity service known as “WhoisGuard,” whereby **NameCheap becomes the registered owner of a domain name** desired by a customer, and licenses the domain name to the customer.

Otherwise, I do agree with basically everything you said. And I have even thought about getting a domain from Njalla myself. I also would trust them more than any randomly picked WHOIS privacy/guard service.

But in the same vein as the decision to stop updating recommended email services, I am not convinced PRISM Break is the right place to look into and verify different domain name registration and hosting services. But maybe other people don’t agree with me. I am looking forward to following this discussion and to someone changing my mind 😄

**Comment by Hillside502** [comment]
> But in the same vein as the decision to stop updating recommended email services

If that is the case, PRISM Break shouldn't be listing Email Services **at all**

**Comment by yegortimoshenko** [comment]
Seemingly, that's not the case anymore, and the service's name suggests that it just hides data from Whois queries, but I can be wrong, there is no public access to that information: https://www.namecheap.com/security/whoisguard.aspx

> But maybe other people don’t agree with me. I am looking forward to following this discussion and to someone changing my mind :smile:

That's rather personal, but I'll try. I've bought a domain at Gandi just a week ago, and they required me to provide ID and certificate of residence:

> From: Gandi Abuse <abuse@support.gandi.net>
> To: yegortimoshenko@riseup.net
> Reply-To: Gandi Abuse <abuse@support.gandi.net>
> Subject: [abuse #8872157] [GANDI] [GANDI-V5] [domain] [dn-buy] hackberryhike.com - yegortimoshenko
> Date: Tue, 27 Feb 2018 11:21:21 +0100
>
> Dear Gandi customer,
> 
> Thank you for your mail.
> 
> Unfortunately, we have not been able to complete your order as requested.
> 
> Note that you will need to start your order over again in order for it to be once more entered into our database.
> 
> So that your order can pass this time, we require :
> - a copy of a legal and valid photo ID (passport, drivers'license, national ID card) for " Yegor Timoshenko " and 
> - a current (less than 3 months) certificate of residence clearly stating the name and address listed in your Gandi account. 
> 
> Please send these documents by responding to this email in PDF or JPG format. 
> 
> Please accept our apologies for the inconvenience.
> 
> Best regards,
> Gandi Abuse team
> http://www.gandi.net/abuse/

I've argued with them for a while, but ended up committing mistake and giving them that data, because I thought I would not find a registrar that ultimately won't require that info from me at some point, and that they donate to various free software projects and use Piwik for tracking and that's better than their competition. 

Despite the fact that I've asked to anonymize Whois data, their Whois entry leaks my name (run `whois hackberryhike.com` and check Registrant Name), meaning they've only hidden my physical address.

If PRISM Break had Njalla listed, I would not have committed that mistake. Similarly, if we were to unlist Riseup, many people would use Gmail and think that there is no better alternative.

Fortunately, in domain registry space, there is an alternative, and it doesn't infringe privacy and meets every criterion that we apply to services I could come up with. Njalla doesn't come up when I search for "privacy domain registrar", and given that PRISM Break is a list of recommendations that re-enforce right to privacy...

**Comment by Hillside502** [comment]
> their Whois entry leaks my name

Depends on the domain name **registry** for the particular gTLD --- **not** the registrar (Gandi).

For example, I bought from Gandi a `.email`domain (Donuts registry) where my name was exposed in WHOIS --- and a `.eu` domain (EURid registry) where my name is hidden.

So, 

> hackberryhike.com

depends on the Verisign registry's policies.

**Comment by yegortimoshenko** [comment]
> Depends on the domain name registry for the particular gTLD --- not the registrar (Gandi).

That is not the case, and has never been the case in .com TLD. I've transferred the domain from AWS Route 53, and they didn't leak my full name. Gandi does.

**Comment by Hillside502** [comment]
Looks like`.com` is treated differently from the newer gTLDs.
