### ISSUE TITLE
Consider Lightbeam

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1911]
Extracted from #1120. Third party visualization/blocking.

Site: https://addons.mozilla.org/en-US/firefox/addon/lightbeam/

**Comment by Atavic** [comment]
> Lightbeam enables you to see the first and third party sites you interact with on the Web.

...but no blocking features.

**Comment by Atavic** [comment]
The blocking option provided pertains to Cookies only.

**Comment by Hillside502** [comment]
Correct name is "Firefox Lightbeam"

**Comment by Hillside502** [comment]
Just be aware that when Firefox Multi-account Containers is installed, Lightbeam only shows data for "No container" tabs.

**Comment by yegortimoshenko** [comment]
Blocking only cookies is problematic and might create a false sense of privacy.

**Comment by strugee** [comment]
Lightbeam doesn't block, it just visualizes. That being said I'm not sure if this belongs on PRISM Break. It's cool but what exactly would we be suggesting users do with it?

**Comment by Hillside502** [comment]
I would suggest that Lightbeam doesn't block anything (cookies or otherwise) per se --- that is not its intention.

But it has a "Tracking Protection" switch, on/off.  This just changes the Preference setting from `Always` to `Only in private windows`

As @strugee said, it visualizes --- that is its **sole** purpose.

IMO, Lightbeam is a (limited, as my comment above) but useful privacy add-on.

**Comment by yegortimoshenko** [comment]
Closing based on that it only visualizes cookies, and not other ways to track, creating false sense of privacy.
