### ISSUE TITLE
Consider Rocket.Chat

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1913]
Mentioned in #1514, extracted from #1472. 

https://rocket.chat/

Self-hosted team communication/collaboration software (like Slack).

**Comment by Hillside502** [comment]
Rocket.Chat Reviews - AlternativeTo.net
https://alternativeto.net/software/rocket-chat/reviews/

**Comment by cyanotex** [comment]
They have a repository here, by the way:
https://github.com/RocketChat/Rocket.Chat

**Comment by seanking2919** [comment]
Definitely like this idea. Plus, it has the option of allowing you to self-host your own chat group.

**Comment by MathiasRenner** [comment]
Why has this been closed? Rocket chat is IMHO a solution that meets the prism break requirements.

**Comment by alerque** [comment]
@MathiasRenner You didn't look around very much. There is only one open issue on this repository explaining that we moved to Gitlab. This is tagged as "moved" because the issue was migrated to Gitlab. The answer to your question is on [the issues on Gitlab](https://gitlab.com/prism-break/prism-break/issues/1913).
