### ISSUE TITLE
Being more up-front about our free software commitment

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1915]
So, I walked away from reading https://twitter.com/CopperheadOS/status/971474392239824896 with a bad taste in my mouth. While we and the CopperheadOS folks clearly disagree on some things (I don't think many people here would claim that Signal on iOS/Windows was more "private", even if it was more "secure") I do feel like we aren't being honest with our users about how we pick things. https://prism-break.org/en/ doesn't even mention free software; the closest it comes to that subject is the word "proprietary". I seem to recall some comment in the issue tracker that said the homepage used to define free software - I can't find it at the moment and that was Before My Time but maybe we should put it back.

I honestly don't have anything actionable at the moment. But I wanted to get the discussion started, because while there are a lot of good reasons we require stuff to be free software, I feel like over time we've drifted above and beyond those reasons since most if not all people here are very involved in the free software movement.

This probably ties in with https://github.com/nylira/prism-break/issues/1723#issuecomment-366044219 too, so cc'ing @alerque.

**Comment by yegortimoshenko** [comment]
I think explaining why we believe free software empowers right to privacy would be a great thing to do. This is a big subject and perhaps warrants a separate page.

**Comment by yegortimoshenko** [comment]
I also think that we should not be bullied into feeling shame for encouraging other people to use free software, even if currently we don't provide an explanation as to why this is the right decision. That would be an improvement, but not a prerequisite. If this list included only proprietary software, no one would ever say that we're imposing values over other people, because apparently we would have no values to impose :-)

**Comment by thestinger** [comment]
Portraying it as bullying when we were the ones needing to defend ourselves from unprovoked slander is a bit rich. Anyone who looks at the thread can see I commented early on saying this:

**Comment by thestinger** [comment]
Portraying it as bullying when we were the ones needing to defend ourselves from unprovoked slander is a bit rich. Anyone who looks at the thread can see I commented early on saying this:

https://github.com/nylira/prism-break/issues/1524#issuecomment-263032993

> If you're making a list of FOSS licensed projects, it shouldn't be included. I am not sure what the point is of fretting over that and criticizing the project for the choice of license. Just close the bug and perhaps work on hardening AOSP if you care about it, or work on developing open hardware / AOSP support for that hardware.

Instead of closing the issue, you spent a lot time making up nonsense and attacking us for no apparent reason beyond a clause in a software license.

> If this list included only proprietary software, no one would ever say that we're imposing values over other people, because apparently we would have no values to impose

Not agreeing with your religious views on software licensing doesn't make someone unethical.

I don't see how a non-commercial clause so that the developers can earn a living for their work by doing commercial licensing is unethical. If someone put a clause in their software license forbidding using it to kill people with drone strikes, that wouldn't be Free Software and couldn't be OSI / FSF approved. You're far from having some kind of objective definition about which software licensing is ethical and you're doing the opposite of making the case for your views on it.

If you want to talk about people without values, how about completely lacking empathy and feeling entitled to having other people's work for free? Instead of being grateful to people that wrote a lot of useful Free Software, you attack them for not giving up the ability to earn income by solely doing that with all of their time. I wouldn't try talking about lack of values after pulling that.

By the way, after how we were treated there we changed the license on 3 repositories to non-commercial usage and I took down several personal Free Software projects. It can go on the list of seemingly endless incidents like this. I have no interest in wasting more of my time making software for people like yourself.

**Comment by thestinger** [comment]
Portraying it as bullying when we were the ones needing to defend ourselves from unprovoked slander is a bit rich. Anyone who looks at the thread can see I commented early on saying this:

https://github.com/nylira/prism-break/issues/1524#issuecomment-263032993

> If you're making a list of FOSS licensed projects, it shouldn't be included. I am not sure what the point is of fretting over that and criticizing the project for the choice of license. Just close the bug and perhaps work on hardening AOSP if you care about it, or work on developing open hardware / AOSP support for that hardware.

Instead of closing the issue, you spent a lot time making up nonsense and attacking us for no apparent reason beyond a clause in a software license. I stuck to factual, accurate responses to inaccurate misinformation and outright lying. I stand by what I posted there.

> If this list included only proprietary software, no one would ever say that we're imposing values over other people, because apparently we would have no values to impose

Not agreeing with your religious views on software licensing doesn't make someone unethical.

I don't see how a non-commercial clause so that the developers can earn a living for their work by doing commercial licensing is unethical. If someone put a clause in their software license forbidding using it to kill people with drone strikes, that wouldn't be Free Software and couldn't be OSI / FSF approved. You're far from having some kind of objective definition about which software licensing is ethical and you're doing the opposite of making the case for your views on it.

If you want to talk about people without values, how about completely lacking empathy and feeling entitled to having other people's work for free? Instead of being grateful to people that wrote a lot of useful Free Software, you attack them for not giving up the ability to earn income by solely doing that with all of their time. I wouldn't try talking about lack of values after pulling that.

By the way, after how we were treated there we changed the license on 3 repositories to non-commercial usage and I took down several personal Free Software projects. It can go on the list of seemingly endless incidents like this. I have no interest in wasting more of my time making software for people like yourself.

**Comment by yegortimoshenko** [comment]
Daniel, I don't like that you've taken this to Twitter in this way. I had no intention attack you, or whatever. It was nice talking with you, and as I wrote you in private, you've changed my stance on patch level. We recommend a lot of stuff [that you recommend](https://copperhead.co/android/docs/usage_guide), there is a huge overlap, so I don't see much use to fight about our dfferent perspectives.

This is not my project, this is community project, and the opinion is mine. You've talked to me, not to everyone else. Some people probably sided with you, even if they haven't participated directly.

Please let's stop this.

**Comment by thestinger** [comment]
> Daniel, I don't like that you've taken this to Twitter in this way.

I don't like when people spread false attacks / misinformation about other people. I happened to be subscribed to that issue so I was able to counter it. That wouldn't usually be the case. I don't see how mentioning it on Twitter makes a difference.

> This is not my project, this is a community project, and the opinion is mine. Some people probably sided with you, even if they haven't participated directly. Please let's stop this.

If you want it to stop, maybe stop accusing other people of not having values or claiming they are bullying you for defenders themselves when you spread misinformation about them. I'm not responding to anyone but you. If you don't want to be a representative of the project you can give up having that role.

> We recommend a lot of stuff that you recommend, there is a huge overlap, and little use to fight about our different perspectives.

Our advice there is based on privacy and security. For messaging, the best option by a huge margin is Signal which you seemingly don't recommend because it's not federated or something like that. There are other options with comparable end-to-end encryption (rather than complete trash like PGP without even forward secrecy) but they don't offer comparable privacy.

**Comment by thestinger** [comment]
> Daniel, I don't like that you've taken this to Twitter in this way.

I don't like when people spread false attacks / misinformation about other people. I happened to be subscribed to that issue so I was able to counter it. That wouldn't usually be the case. I don't see how mentioning it on Twitter makes a difference. We never criticized this project despite being aware of it and having strong differences of opinion until you start attacking us and in a very underhanded / dishonest way at that.

> This is not my project, this is a community project, and the opinion is mine. Some people probably sided with you, even if they haven't participated directly. Please let's stop this.

If you want it to stop, maybe stop accusing other people of not having values or claiming they are bullying you for defenders themselves when you spread misinformation about them. I'm not responding to anyone but you. If you don't want to be a representative of the project you can give up having that role.

> We recommend a lot of stuff that you recommend, there is a huge overlap, and little use to fight about our different perspectives.

Our advice there is based on privacy and security. For messaging, the best option by a huge margin is Signal which you seemingly don't recommend because it's not federated or something like that. There are other options with comparable end-to-end encryption (rather than complete trash like PGP without even forward secrecy) but they don't offer comparable privacy.

**Comment by thestinger** [comment]
> Daniel, I don't like that you've taken this to Twitter in this way.

I don't like when people spread false attacks / misinformation about other people. I happened to be subscribed to that issue so I was able to counter it. That wouldn't usually be the case. I don't see how mentioning it on Twitter makes a difference. We never criticized this project despite being aware of it and having strong differences of opinion until you start attacking us and in a very underhanded / dishonest way at that.

> This is not my project, this is a community project, and the opinion is mine. Some people probably sided with you, even if they haven't participated directly. Please let's stop this.

If you want it to stop, maybe stop accusing other people of not having values or claiming they are bullying you for defending themselves when you spread misinformation about them. I'm not responding to anyone but you. If you don't want to be a representative of the project you can give up having that role.

> We recommend a lot of stuff that you recommend, there is a huge overlap, and little use to fight about our different perspectives.

Our advice there is based on privacy and security. For messaging, the best option by a huge margin is Signal which you seemingly don't recommend because it's not federated or something like that. There are other options with comparable end-to-end encryption (rather than complete trash like PGP without even forward secrecy) but they don't offer comparable privacy.

**Comment by strugee** [comment]
So, I still haven't read the original CopperheadOS thread, but either way this discussion won't be productive. Can we all please agree to keep this issue limited to what I put in the description? I.e. more clearly articulating our views surrounding free software.

**Comment by hasufell** [comment]
> free software

The point is not necessarily free software. That is more of an ethical/technology thing. From a privacy perspective we care primarily about being able to study the source code (know what your program does). If a project has less compatible redistribution rules than what we expect from "free software", I honestly don't care from a *privacy* perspective.

**Comment by Zegnat** [comment]
> But I wanted to get the discussion started, because while there are a lot of good reasons we require stuff to be free software, I feel like over time we've drifted above and beyond those reasons <i>[…]</i>

These days I am no longer even sure if the GNU/FSF definition of Free Software is important for PRISM Break’s goal.

> If a project has less compatible redistribution rules than what we expect from "free software", I honestly don't care from a _privacy_ perspective.

While I agree on the privacy perspective, I seem to recall I have previously argued that the redistribution of software is very important in an effort like PRISM Break’s. And I will make that argument again.

If I am not allowed to put recommended privacy software on some medium (flash memory, optical memory, you name it) and spread it around to vulnerable groups that is a definitive hindrance. Recommending software that can only be gotten from specific official sources (because of redistribution limitations in a licence) makes it easier for e.g. state actors to block those sources.

[Sneaker nets](https://en.wikipedia.org/wiki/Sneaker_net) are real, and some countries may depend on it. (Cuba [comes to mind](https://en.wikipedia.org/wiki/El_Paquete_Semanal).)

The way I see it any recommended software should at least allow anyone:

1. unhindered access to the source code – the only way to see the software only does what it claims to do,
2. the right to run and/or compile the source code – the only way to get around using binaries from untrusted sources,
3. to distribute the source (and binaries where applicable) – the only way to guarantee wide access to software anywhere.

If those things are true, I wouldn’t care about whether the licence is “viral”, whether derivatives are allowed, or whether upstream is accepting outsider patches.

There are still some points that would be missed of course. Without the right to make changes, I couldn’t legally create a translation. Without the right to link binaries, I couldn’t add it within a separate program. These are things that might hinder how easy it is to get people to use the recommended tools. But I am not sure I still want to take a hard stance on those points. As @hasufell says, those do not have to hamper the user’s privacy.

I specifically do not mention points 5 and 6 of [the Open Source Definition](https://opensource.org/osd-annotated) here. Mostly because I feel they should be obvious. The recommended software should be neutral to how it is being used. If you think your specific ideals deserve privacy, but not others’, that’s a slippery slope:

> 5. No Discrimination Against Persons or Groups
> 6. No Discrimination Against Fields of Endeavor

**Comment by hasufell** [comment]
> If I am not allowed to put recommended privacy software on some medium (flash memory, optical memory, you name it) and spread it around to vulnerable groups that is a definitive hindrance. Recommending software that can only be gotten from specific official sources (because of redistribution limitations in a licence) makes it easier for e.g. state actors to block those sources.

That's a two-sided argument. Some software is hard to configure properly (e.g. unbundling of libraries has often caused negative effects on users and source distros do that a lot... and sometimes realize they f*ed up) so having random binaries and maybe proper redistributed stuff floating around may or may not be an advantage. That is really hard to say.

Also note that Tor is not recommended to be downloaded or used from any source except the tor project! And I once packaged the tor browser in gentoo after a lengthy discussion with some Tor people happened about whether that is a good idea or not. The effort to replicate the configuration correctly was tremendous and in the end it was likely still wrong. So we removed that package in the end.

So, while I would *generally* agree that free redistribution is a good thing, it also has a problematic side from a security/privacy perspective.

**Comment by Zegnat** [comment]
> Also note that the Tor browser is not recommended to be downloaded or used from any source except the tor project!

At the same time, I seem to remember reading @ioerror used to “smuggle” copies of Tor to activists in the form of coin-sized SD cards :wink:

> So, while I would _generally_ agree that free redistribution is a good thing, it also has a problematic side from a security/privacy perspective.

There is always going to be a problem with the security of redistribution. Do I trust binaries from the Tor Project website? Maybe not, maybe I will validate them with their signing key after downloading. But surely I can do that same validation if I had gotten the binary on a CD? You will always get stuck in a Web of Trust somewhere. You trust the compiler of the binary, the redistributor of the source, or the redistributor of the signing key.

For the main goal of PRISM Break, to protect people from global surveillance (by state-actors), I would frown upon recommending software where the licence actively stops people from getting it into the hands of fellow marginalised or activist groups.

We shouldn’t recommend the use of alternative redistributions. But if we are discussing licence requirements for included projects I feel it is fair to require those projects to _allow_ unlimited redistribution. Is that a better way to put it?

**Comment by hasufell** [comment]
> require those projects to allow unlimited redistribution

Well, I certainly don't want projects that disallow redistribution altogether. But, as the recent Pale Moon discussion came up... they definitely don't allow "unlimited" redistribution, but it's still possible to redistribute it to activists if you follow the license requirements.

So, is it really about *unlimited* (or maybe: unrestricted?) redistribution?

**Comment by Zegnat** [comment]
> So, is it really about _unlimited_ (or maybe: unrestricted?) redistribution?

Hmm, maybe not. I guess the most important part is that anyone should be allowed to (at minimum) redistribute the project’s source code verbatim by any means. My concern here is with availability, which I think is the crucial factor for PRISM Break.

You may forbid someone to make derivatives or put branding limitations in place such as Firefox/Pale Moon do, but not forbid someone from redistributing whatever you are providing to them yourself. Or limit the ways of redistribution, such as not allowing it to be burned to a CD alongside other things.

Some licences make this very clear (e.g. GPL) and others just grant really broad rights which would also encompass this (e.g. BSD). For other licences I think it would be very clear upon reading them whether they are trying to block you from spreading the software or not.

In the case of Pale Moon, I am not sure I would have an issue with them from this point of view. Them putting limits in place for derivatives and ports does not hinder my ability to take the default Pale Moon source code and binaries for distribution.
