### ISSUE TITLE
Snapchat not present on any proprietary list?

### ISSUE THREAD

**Issue by cyanotex** [nylira/prism-break#1922]
I'm curious if there's any reason for Snapchat's absence on PRISM Break in any proprietary list.

**Comment by yegortimoshenko** [comment]
It is proprietary. Which category do you think it belongs to?

**Comment by Hillside502** [comment]
Google Play lists it as "Social".

Existing possible PRISM Break categories are either/both of:-
`Instant Messaging`
`Social Networks`

Open Source Snapchat Alternatives - AlternativeTo.net
https://alternativeto.net/software/snapchat/?license=opensource

**Comment by cyanotex** [comment]
On Snapchat's Wikipedia article, on Type, it's listed as:

Photo sharing
Instant messaging
Video chat
Multimedia

I think it would fit best on Instant Messaging and Social Networks. Maybe Media Publishing as well? What do you think?

**Comment by yegortimoshenko** [comment]
Snapchat is an oddball service that doesn't have any comparable free alternatives, and some of its crucial functionality relies on being proprietary (like, detecting screenshots). I'm not sure if it should be listed.

**Comment by Hillside502** [comment]
Add `Video & Voice` to my above comment.

**Comment by cyanotex** [comment]
Huh. Well, I think it would be wise not to list it, but I'm not sure. I do agree with you, @yegortimoshenko , it's kind of a service that does multiple things.

**Comment by cyanotex** [comment]
I'm not sure. I mean, if we were to list it, it would kind of be in multiple categories?

**Comment by Hillside502** [comment]
Multiple categories are OK.  For example, Nextcloud is in 8.

**Comment by cyanotex** [comment]
So, it could be listed in multiple categories that are available. That would make the most sense.

**Comment by strugee** [comment]
This certainly should be listed. I would argue that Snapchat is actually even more problematic than some of our existing listings because people think it's "private" due to the disappearance of their messages. But this doesn't reflect reality.

I vote for putting it in both IM and Social Networks. People use it in both these ways.

**Comment by yegortimoshenko** [comment]
On second thought, you are right. It's just that how it presents itself is inherently something that can't be ensured (disappearing messages can always be backed up, photos can be screenshotted, etc.)

**Comment by strugee** [comment]
Right. I did recently see an interesting perspective recently though (which I sadly can't find a link to) that points out that disappearing messages aren't designed to make sure Alice's messages to Mallory disappear; they're designed to make sure that Alice's messages to Bob disappear because Bob is super lazy and wouldn't bother if it wasn't automatic.

But this isn't what Snapchat says it does, and it's still proprietary as hell :P
