### ISSUE TITLE
Remove GPG/PGP for email

### ISSUE THREAD

**Issue by strugee** [nylira/prism-break#1925]
I would like us to consider removing all references to PGP and GPG, because it's my belief that if it weren't so famous and longstanding, we would reject it from the list today. For further clarification, I am talking about PGP in the context of email.

Materials on PGP's suckiness abound, but here's an incomplete list just off the top of my head (in rough order of how terrible they are):

1. PGP leaks metadata like a champion, including the subject line and recipients
2. Outdated crypto, no forward secrecy, big keys
3. Fingerprint verification is really hard to explain
4. Super easy to fuck up _basic_ UX stuff, like e.g. not encrypting to yourself so you can't read your sent mail
5. Most if not all PGP UIs are terrible, it's really easy to accidentally turn off encryption
6. Revocation isn't reliable
7. Even if you do set up refreshes to get revocation you leak your entire social graph to the keyserver, and often keyservers literally speak plaintext so you can sniff this stuff completely passively (unless you use parcimonie but that doesn't come set up by default, _anywhere_ AFAIK, and no one knows about it so it's worthless)
8. There's no real multi-device experience, particularly for your own trust decisions
9. Trust in the Web of Trust is completely broken because you have no idea what security steps _other_ people take, which is a big problem because you're relying on other people's signatures (and therefore security) to compute trust paths; see also https://lists.torproject.org/pipermail/tor-talk/2013-September/030235.html

I could go on and on but I'll stop there. https://blog.cryptographyengineering.com/2014/08/13/whats-matter-with-pgp/ goes into a lot of these points too.

There are better alternatives. I have [tried to teach PGP](https://strugee.net/cryptoparty-seattle/) in the real world and both times it has gone exceedingly poorly to the point where I abandoned it entirely and taught Signal instead. Keysigning parties are a joke; they're _somewhat_ useful in very small contexts/communities like Debian but not at scale.

I will also point out that a lot of these problems can be fixed. But by the time you fix them, you'll end up with a brand-new backwards-incompatible protocol that basically reimplements Signal, only poorly. And some cannot be fixed at all really, like the metadata problem.

**Comment by quantumpacket** [comment]
>  I am talking about PGP in the context of email.

If it's just for email, then I'm 100% in support as it truly is a nightmare to get people to properly use and understand it for that purpose, not to mention its shortfalls.

We've got plenty of real-time chat based alternatives that even my mom knows how to use. :stuck_out_tongue:

**Comment by yegortimoshenko** [comment]
I'm strongly against this. GPG is a valuable tool, not everything has to be Signal. On the contrary, I think we would have accepted it today, because it fills multiple roles that are otherwise absolutely out of reach of any other encryption/signing tool.

In short, GPG provides very strong identity, that is not the case with any other tool.

> 1. PGP leaks metadata like a champion, including the subject line and recipients

It doesn't actually leak anything, except fingerprint of recipient's key (performance optimization, can be disabled via `-R` flag).

It's true that GPG message container can leak anything, but GPG doesn't end at email. It's universal. Which is why it is very important to list.

> 2. Outdated crypto, no forward secrecy, big keys

I use a ed25519 key! So, cutting edge crypto is an option. Keys *are* big. ed25519 keys are somewhat smaller. It's not clear to me what practical issues that might entail when one uses a reasonably sized fingerprint for verification purposes.

Lack of forward secrecy is inherent because it's not an instant messaging specific, it is agnostic to any messaging state, agnostic to any messaging protocol, it only understands signing, verification, encryption, decryption. That makes it very versatile: you can print out a GPG message and send it over snail mail, or just store it somewhere, or put a GPG encrypted file on a thumb drive, you can use it for digital signatures: email, contracts, git...

> 3. Fingerprint verification is really hard to explain

This also applies to Conversations, Riot, most end-to-end encrypted chats ask to compare keys or trust blindly on first use, both approaches are problematic. GPG support either. Also, I don't think it's hard to explain: you can video chat with someone and ask them to show them a printout with a fingerprint, or check it by calling them. Or you can trust blindly.

> Keysigning parties are a joke; they're somewhat useful in very small contexts/communities like Debian but not at scale.

This is cultural problem for the most part. Key parties are definitely not the only valid way to sign keys: it's very valuable to sign keys with low level of trust just when you meet people. This provides better confirmation than Keybase's proofs and tracking.

In terms of key trust, keysigning parties are certainly not a joke. It's just that key parties are the only way to ensure very high level of trust, which people don't usually care about.

> 5. Most if not all PGP UIs are terrible, it's really easy to accidentally turn off encryption

That has never been a criterion: GPG is comparable with Conversations in this regard.

> 8. There's no real multi-device experience, particularly for your own trust decisions

For multiple PCs, syncing `~/.gnupg` facilitates multi-device experience. I don't trust keys to my phone, so I don't know about that, but there's nothing that stops someone from writing Android client that can use `~/.gnupg`.

> 9. Trust in the Web of Trust is completely broken because you have no idea what security steps other people take

This is why web of trust may be strong or weak. The danger of some people making mistakes is reduced by other people also signing the key. Even if there are people who sign bad keys with malicious intent, this concern is offset when more people with deep webs of trust sign the good key and there are paths that lead through them.

Also, if there is some realistic way to strongly confirm someone's identity other than Web of Trust, I would like to know it. I don't think one is even possible, I also think that web of trust is inherently how trust towards strangers works, e.g. the way people identify real Julian Assange from fakes on Twitter is by looking at his followers and checking if they are real people followed by other real people.

Please do not underestimate this aspect: say, for a whistleblower, it's absolutely crucial that they correctly identify their recipient's identity. GPG is the only realistic way to do that with high degree of certainty, because it's the only truly decentralized (not federated, like Keybase) way.

> [...] you leak your entire social graph to the keyserver

Signing key requires an explicit action, so it can be argued it's not a leak at all. WoT aspect can also be ignored entirely, if you wish so. People should not sign each other's keys if they don't want to keep their relationship private. It is possible to trust a key without signing it.

**Comment by yegortimoshenko** [comment]
If you don't like GPG for encryption, please like it for signatures. Also there's [Autocrypt](https://autocrypt.org/).

**Comment by strugee** [comment]
@quantumpacket:

> We've got plenty of real-time chat based alternatives that even my mom knows how to use.

This is the heart of what I'm getting at.

**Comment by strugee** [comment]
@yegortimoshenko okay, so, before I start I want you to really take a long think and make sure you're really considering my arguments. And the reason why I say that is not because I doubt you, but because when I first heard of the idea I'm presenting here ("GPG sucks") I found I had a knee-jerk reaction that immediately dismissed that idea because GPG is so widely known and accepted. Tbh I probably should've said this when I wrote the description, but oh well.

**tl;dr**: yeah sure it's possible to use GPG in a somewhat vaguely private way but it requires a huge amount of arcane knowledge and you have to bend over backwards to do it. And even then it still has problems. Even the length of your comment is making my point for me - you shouldn't have to know that much just to get the thing to work privately.

I also want to point out that your argument that GPG is useful for more than one thing is irrelevant, because we're discussing this only in the context of email - _GPG in email_ leaks metadata like a champion.

> It doesn't actually leak anything, except fingerprint of recipient's key (performance optimization, can be disabled via `-R` flag).

Do we really expect end-users to know this??

> I use a ed25519 key! So, cutting edge crypto is an option.

According to Matt Greene the symmetric primitives used by default are very old, though that post was written a while ago and I would be interested to see if this has changed. But besides, ed25519 keys aren't the default in most places, right? Which makes them useless, because users don't change defaults.

> Lack of forward secrecy is inherent because it's not an instant messaging specific, it is agnostic to any messaging state, agnostic to any messaging protocol, it only understands signing, verification, encryption, decryption.

This is absolutely true. I see this as a deficiency. Just because there's a reasonable explanation for it not having forward secrecy doesn't mean that's acceptable in a modern cryptographic system.

The thing about big key size I mostly just threw in there since the bullet point was already about crypto complaints. It's not super important.

> This also applies to Conversations, Riot, most end-to-end encrypted chats ask to compare keys or trust blindly on first use

Fair enough, moving on...

> In terms of key trust, keysigning parties are certainly not a joke.

They're a joke in terms of practicality. It is also very hard to actually teach people what their purpose is. And your argument that you can sign people's keys without keysigning party-like auditing is just strengthening my point about the web of trust model not being useful. Because if other people that I'm connected with are doing that, now _my_ security is compromised because _someone else_ didn't properly vet keys before signing them.

> That has never been a criterion: GPG is comparable with Conversations in this regard.

Meh. Conversations is more integrated, and it's easier because the UI is structured around contacts instead of threads. Plus, maybe this has changed, but when I last tried PGP with Thunderbird I never felt confident that I understood when the extension would automatically activate the encryption, when it would stay on, etc. Maybe that's just FUD though, I don't know.

> For multiple PCs, syncing `~/.gnupg` facilitates multi-device experience.

Syncing how? Are you uploading your private keys somewhere? What if there's a conflict, how are you supposed to solve that? In any case you shouldn't have to set this up manually. It seriously should Just Work:tm: out of the box.

> The danger of some people making mistakes is reduced by other people also signing the key. Even if there are people who sign bad keys with malicious intent, this concern is offset when more people with deep webs of trust sign the good key and there are paths that lead through them.

This is still assuming that people sign keys _all the time_ which doesn't seem realistic and doesn't match the practice of how GPG is done.

> Even if there are people who sign bad keys with malicious intent, this concern is offset when more people with deep webs of trust sign the good key and there are paths that lead through them.

Is this actually how GnuPG builds trust paths, out of the box, by default? Last I checked it wasn't.

> Please do not underestimate this aspect: say, for a whistleblower, it's absolutely crucial that they correctly identify their recipient's identity. GPG is the only realistic way to do that with high degree of certainty, because it's the only truly decentralized (not federated, like Keybase) way.

To clarify what you're saying here, you're saying, verify their identity _before_ making contact, correct?

> Signing key requires an explicit action, so it can be argued it's not a leak at all.

But this is how you're "supposed" to use GPG. I don't buy that "it can be argued"; we're not here to discuss technicalities, we're here to discuss typical usage.

Besides that though, that wasn't what I was talking about. You leak your social graph every time you `gpg --refresh-keys`.

**Comment by hasufell** [comment]
> PGP leaks metadata like a champion, including the subject line and recipients

PGP is not about hiding metadata.

> Outdated crypto, no forward secrecy, big keys

Not sure what outdated crypto means. That's somewhat unspecific and likely wrong. Also, how would forward secrecy work with PGP?

The rest of your points are mostly about usability issues. Yes, people have to know what PGP is and know roughly how it works in order to use it correctly.

**Comment by strugee** [comment]
> PGP is not about hiding metadata.

I realize this, but just because it works as designed doesn't make it acceptable that it leaks so much metadata. Same with forward secrecy; I understand it doesn't make sense for PGP and I don't care because that doesn't make forward secrecy less important for a communications tool.

> Not sure what outdated crypto means. That's somewhat unspecific and likely wrong.

I'm mostly going off https://blog.cryptographyengineering.com/2014/08/13/whats-matter-with-pgp/, but that post is from a while ago, so I'm not sure. I poked around the GPG repo for a bit to try to figure out the defaults but I can't find the GPG 2 ones, just what seems to be GPG 1.x at https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=g10/keygen.c.

> The rest of your points are mostly about usability issues. Yes, people have to know what PGP is and know roughly how it works in order to use it correctly.

Since when do we not care about usability issues? It's very hard to set up PGP properly. Have you actually tried to teach PGP? It's very difficult.

"Roughly" is also an understatement. You have to know _a lot_ about how it works, otherwise it's very easy to get wrong.

More crypto people leaving PGP, and why: https://blog.filippo.io/giving-up-on-long-term-pgp/, https://moxie.org/blog/gpg-and-me/

**Comment by Atavic** [comment]
>  It's very hard to set up PGP properly.

According to [EFF](https://ssd.eff.org/en/module/how-use-pgp-windows):

**Level:** Beginner-Intermediate
**Time required:** 30-60 minutes

And that's for the complete install of an email client. It is all left on defaults, users have to type a wonderous, strong passphrase and then must pay attention that:

> Your key will expire at a certain time;

Then there's the overwhelming exercise of importing Public Keys from others.

**Comment by hasufell** [comment]
@strugee I can see your points, but... if I compare this with e.g. the F-Droid discussion where we basically kept it for "no proper alternatives" reason, then I can ask the same question here. And... F-Droid wasn't just about usability issues, but more fundamental things.

So, if you remove something for usability reasons, I think we should have (for every given use case) a proper alternative. If we can come up with something like that, why not. But it would almost have to be a guide or a separate section. And... given that PGP is still popular and other people may *require* you to use it in order to talk to them, I'm not sure it should be removed at all. Adding a "note" about the usability issues could be reasonable though.

**Comment by Sigmun** [comment]
> There are better alternatives. I have tried to teach PGP in the real world and both times it has gone exceedingly poorly to the point where I abandoned it entirely and taught Signal instead. 
> I will also point out that a lot of these problems can be fixed. But by the time you fix them, you'll end up with a brand-new backwards-incompatible protocol that basically reimplements Signal, only poorly. 

@strugee Are-you saying that you recommend using Signal instead of GPG emails ?

**Comment by strugee** [comment]
@Atavic I disagree with the EFF, I think it's harder than that. Plus that's not the whole story, there's also ongoing use. What if it breaks? Are you sure you're using it correctly _every time_?

Even if the EFF's estimate _is_ on mark, 30-60 minutes seems like a _lot_ when I can have many of the projects in the IM section set up in 5-10 minutes.

> Then there's the overwhelming exercise of importing Public Keys from others.

Key management should be invisible. Anyone who thinks that most people want to learn how to manage keys is kidding themselves; lots of people can barely pick a password stronger than `password`.

I will repeat for the fourth time: have you tried teaching PGP in the real world? I have. That more than anything else was what convinced me it's not viable.

That is not a rhetorical question, by the way. If anyone _has_ taught PGP and has had a good experience with it, I would be interested in hearing about it.

**Comment by strugee** [comment]
@hasufell hm, that's an interesting comparison. To me lack of forward secrecy _is_ a "fundamental" issue, but I realize it's not quite as convincing as the problems with F-Droid. I'm not sure. My gut feeling is that IM can be a replacement for a lot of email's use cases.

I certainly would be much happier if we added a note to the effect of, "use PGP if you must, but it's really not good and has bad UX and you should prefer other things."

**Comment by strugee** [comment]
@Sigmun with my co-maintainer hat _off_, yeah, absolutely 200%. Signal has its problems but it is much much better overall.

**Comment by Hillside502** [comment]
#1804 seems to be an interesting alternative.

**Comment by Atavic** [comment]
@strugee I don't agree with usabilty issues. *How-Toes* have been around from the very beginning of internet. I understand that my grandma could have issues, but she can ask her nephew about GnuPG.

**Comment by anthologist** [comment]
What some of you don't seem to realize is that in most of cirumstances you can't replace emails with a messagging/phone app. Emails are emails, you usually don't use a messagging app to replace them and most importantly you will not be able to convince people doing it. I'm also thinking about different environments, eg. companies, where emails are mostly used: the only way to secure them is PGP/GPG.
In any case don't even take in cosideration Signal, "its problems" (cit.) should keep you away from that app if you're really concerned about privacy. (let's not speak about it in this issue)

In my honest opinion, if a better alternative is not found, GPG/PGP should stay there.

**Comment by Hillside502** [comment]
> I understand that my grandma could have issues, but she can ask her nephew

What's with the ageism and sexism?

**Comment by Atavic** [comment]
That was an example for the usabilty issues, based on real people: my grandma can't built from source!

**Comment by Zegnat** [comment]
As I have said on the newly created IRC channel (#1920):

> I am not sure if <i>[this]</i> issue is against GPG as much as it is against email though. And as we have seen before, it is really hard to tell people not to use email at all :(

It feels a little like how we also link to Windows software. Some people find themselves unable to switch OS and would instead like to be pointed to tools to secure (in however far this is possible) the thing they are being forced to use. As @anthologist points out, this may also apply to email. People find themselves in places where they find it nearly impossible to switch communication protocol and still want to make the best of it. If this means their subject lines aren’t being encrypted, so be it.

If we aren’t removing everything _email_ on PRISM Break, I don’t think we should be removing GPG as it relates to email either. Unless we can point people to an alternative way to encrypt their email conversations.

I know a few big international companies who (used to) have a policy of using password-encrypted RAR archives – AES encryption applied to the entire archive including file meta data – as email attachments for anything sensitive. But I doubt you are going to make people happy when you ask them to (un)archive plain text emails all the time. At least GPG has extensions for email clients.

Would it be nice if email didn’t leak meta data? Sure! It isn’t GPG’s fault that the protocol itself works that way though. Is forward secrecy awesome to have for back-and-forth discussions? Of course! But has anyone ported a standard that features that to email?

To recap: I don’t think we can remove GPG-for-email without 1) removing email, or 2) replacing it with a better system to protect email.

> I don’t agree with usabilty issues. _How-Toes_ have been around from the very beginning of internet.

And even I can’t point someone to the absolute how-to on GPG. Half the time I still do not know what the most up-to-date and secure advice is vis-à-vis key algo, key length, subkey management, etc.

I’ve often referred to Cabal’s <i>[Creating the perfect GPG keypair](https://alexcabal.com/creating-the-perfect-gpg-keypair/)</i> because it is relatively easy to follow along and does talk about setting up subkeys. But that is from 2013 and written by a self-declared “layperson”. He also writes about how he found it hard to find solid information and best practices around subkeys, often ending up on wiki pages from linux distros. That’s not what I would call a healthy set of how-tos.

(The [Email Self-Defense](https://emailselfdefense.fsf.org/) guide linked to on PRISM Break suffers from the same problem: linking to an unavailable Enigmail wiki under troubleshooting, and linking to Cabal and the Debian wiki under advanced.)

I’d love to see a how-to written in the last year, maybe something that does include information about using ed25519 as @yegortimoshenko seems to do. If anyone has any such guides at their fingertips, I’d say those should be instantly linked to from PRISM Break as long as GPG is a thing on the site.

**Comment by yegortimoshenko** [comment]
@strugee: I understand where you're coming from. If one treats GPG as an encryption tool, it's rather bad at that. But it's several orders of magnitude better at confirming identity prior to when communication takes place, and it's the only viable/meaningful tool for signatures.

PFS presumes ever-changing state, and that is problematic for some contexts. For example, in some cases, you might want to keep a server-side log of XMPP history, in that case using GPG instead of OMEMO is justified. The same applies to deeds, files transferred offline, you just can't apply PFS to that because there's no protocol.

I do think we should add more notes to GPG so that people wouldn't think their metadata is encrypted, would buy a hardware token to make sure that their keys are not compromised, use ed25519 (although RSA is not that bad).

**Comment by yegortimoshenko** [comment]
I would like to summon @JeremyRand to this thread :-)

**Comment by jinformatique** [comment]
I fully agree with @strugee's first post, I understand his viewpoint as I'm coming from the same place.

Some solutions I wanted to share with you:

- Mailpile and Keybase include PGP/GPG at the core. So it's not to the end user to create and maintain is keys.

- Wire over Signal, I prefer Wire. The client is multi-platform and less mobile centered than Signal and you can create and account without mobile number.
- Lavabit : email don’t leak meta data, but it's a paid service. Read below:

>  Radically different from any other encrypted platform, DIME solves security problems others neglect. It's the only automated, federated, encryption standard that works with different service providers while minimizing the leakage of metadata without a centralized authority.
To support the DIME environment, we've created the Dark Mail Access Protocol—DMAP—and Dark Mail Transfer Protocol—DMTP—to replace IMAP. We've presented both protocols to the Internet Engineering Task Force for certification and adoption. 

I agree these solutions are not perfect. But far more better than just using a common email service.

**Comment by Hillside502** [comment]
> Lavabit

US-based and look what happened last time --- wouldn't trust it as far as I could throw it!

Also, no Strict Transport Security (HSTS) on the website and not even HTTP/2:-
https://www.ssllabs.com/ssltest/analyze.html?d=lavabit.com

**Comment by jinformatique** [comment]
Ok then @Hillside502 what secure email service do you currently use with your family?

Right now, I need to recommend one secure email service to a friend who is not very technical, what would you suggest ? He is used to gmail, yahoo. Thanks for your comments.

**Comment by Atavic** [comment]
Protonmail is advertised as secure; but if you look at the connections into your browser when you load its webmail page, the noise tells differently... I'd go out with a friend of mine for a beer and then set up Enigmail + GnuPG + Mozilla Thunderbird for him.

**Comment by jinformatique** [comment]
The only thing is the friend is a girl, she is not into tech, and doesn't live near. And she uses a smartphone also.

**Comment by Hillside502** [comment]
> is a girl, she is not into tech

???

**Comment by jinformatique** [comment]
Yes, for one friend, it's reasonable to go out with him and set him up "Enigmail + GnuPG + Mozilla Thunderbird". But for most of my friends and family, I won't have the opportunity nor the time to do that. I was asking your advice for non-technical people that I cannot go and see all of them to do that.
We are in 2018 and we are still facing this problem. At the end of the day I have to make a decision on what to tell them to choose to keep in touch with me. That's why for now, I go with Protonmail for emails and Wire or Signal for messaging. I agree it's maybe not the best, but prism-break will keep recommending software for more technical advanced users.

**Comment by Zegnat** [comment]
As was brought up in this issue, email itself is extremely hard to secure.

Protonmail and Tutanota specifically were discussed in #1383. Back then I looked into Tutanota more than Protonmail and my conclusion was mostly that it may be fine to use as long as everyone uses Tutanota and you never email outside addresses, as that opened up a whole new box of problems. (Again, related to securing email in general.) With an auditor later weighing in that the entire encryption model used by them left something to be desired, I would not feel comfortable recommending them.

If you have looked into the security offered by Protonmail, I would love it if you could comment on #1383 and see if it is worth recommending them PRISM Break. I never looked into them much. Though I half expect it comes with a similar can-of-worms attached.

At the end of the day I think the important question to ask is whether you need email at all.

Was it really not possible to instruct your friends and family to contact you over Wire or Signal only? You could even use that as a side-channel to share a one-time key that lets them send you an encrypted document over email, in case that is something that happens in your friends circle a lot. Something like WinRARs build-in AES format would have been secure there, so they only need to know how to create a file archive instead of understanding encryption.

**Comment by jinformatique** [comment]
@Zegnat thanks. I know email security is broken because metadata are sent in the clear. Some of my friends use Wire as I asked them, but not all. But using instant messages instead of email is a bit different as there is one channel per contact with many subject discussed in the same thread. Older people are used to emails because, you log in when you decide, you read, and you can receive from one person different emails with different subjects. I'd like to have similar features but with e2e encryption. The closest to this solution is mailpile, but then it's difficult for friends to install.

**Comment by Hillside502** [comment]
> Older people are

What is it with you, @jinformatique with all your sexism, ageism and any other 'isms?

**Comment by jinformatique** [comment]
@Hillside502 hahaha, just a thing I noticed, people over 30 are used to emails, and people under 30 don't use emails anymore. And some uses both. There are all king of variations. So it's not easy to find a good replacement that does all in one to recommend. I don't consider myself sexist.
What is your experience with people and IT, what do you recommend to them?

**Comment by Hillside502** [comment]
> people over 30 are used to emails, and people under 30 don't use emails anymore

You don't give up, do you?

**Comment by hasufell** [comment]
He is clearly speaking about his average personal experience, not generalizing over the entire population or making definite conclusions about sex/gender/whatever. There is no apparent sexism, just calm down already.

**Comment by jinformatique** [comment]
@hasufell thank you, I feel understood.
@Hillside502 I never ever give up. There is so much to do and you are not helping. I like to help people with IT and show them the possibilities, to improve and secure their communications. Maybe you are happy the way things are now with GAFAM and surveillance and privacy. I am not.

**Comment by yegortimoshenko** [comment]
> The only thing is the friend is a girl, she is not into tech, and doesn't live near. And she uses a smartphone also.

I suggest a chat application such as Conversations + OMEMO.

Also, don't discourage someone from learning complex tools because they are a girl. If you teach them, you will likely find that your expectations were wrong :-) For example, my girlfriend uses and loves org-mode, and she is an artist, not a tech person.

**Comment by hasufell** [comment]
> Also, don't discourage someone from learning complex tools because they are a girl!

He said she is not into tech. That's a pretty good reason not to try to teach complex tools.

**Comment by Hillside502** [comment]
> He said she

OMG, what on earth has gender anything to do with this issue?

The fact that @jinformatique gives the sexes and ages of his examples gives the game away entirely!

The quicker that 'isms are consigned to the dustbin of history, the better.

**Comment by hasufell** [comment]
Guys, this is not twitter.

**Comment by quantumpacket** [comment]
http://news.gallup.com/poll/179288/new-era-communication-americans.aspx from 2014 and for US, but the only *significant* difference when it comes to age and text/email use is when you get into senior citizen age. So is the complexity the issue, or is it generational and tech use at a younger age makes it easier to grasp new technologies?

We can split hairs on this debate, but I think we can all agree that added complexity no matter who you are is always going to be a deterrent in the adoption of anything.

**Comment by yegortimoshenko** [comment]
Here is a good write-up on that topic by Mailpile developer, which I wholeheartedly agree with: https://www.mailpile.is/blog/2016-12-13_Too_Cool_for_PGP.html

**Comment by yegortimoshenko** [comment]
@strugee: While I understand your concerns with GPG (which, I agree with @Zegnat, seem to be largely concerns with email generally),  I don't think you will be able to get consensus on outright removal of GPG from site, not in the near- to mid-term future, that is.

If you have any concerns with the way GPG is portrayed on the list, maybe we could resolve and agree upon those instead?

Also, please try out Mailpile. It resolves quite a bit of your concerns with GPG:

* it doesn't leak subject in GPG-encrypted email (see https://github.com/autocrypt/memoryhole)
* it doesn't leak user metadata in general: no operating system in User-Agent, timezone seems to be always +0:00, etc. (I haven't checked EHLO)
* you don't do anything to get a GPG keypair, it is created and handled implicitly, and client makes it very clear when message is signed or encrypted
* it uses TOFU model of trust
* it encourages routing everything through Tor
* it apparently has been endorsed by Moxie Marlinspike: https://news.ycombinator.com/item?id=6245046

**Comment by yegortimoshenko** [comment]
https://lists.gnupg.org/pipermail/gnupg-users/2018-May/060315.html

Mailpile is not directly vulnerable because it doesn't display HTML email by default (it is only available as a per-message or per-recipient option, and can't be enabled globally).

**Comment by yegortimoshenko** [comment]
Reference: https://efail.de/

Ever since Heartbleed security researchers are leveling up their marketing game :-)

**Comment by Zegnat** [comment]
Probably the only image you need:

![Table 4: Exfiltration channels](https://user-images.githubusercontent.com/490579/40020585-b96ce0f4-57c2-11e8-864d-8b13923a5856.jpg)

Which I didn’t immediately spot on the “EFAIL” website, but was [posted on Twitter](https://twitter.com/yrlaNor/status/995982613293780993) and linked to me.

It also looks right that we haven’t been putting too much weight on S/MIME.

**Comment by yegortimoshenko** [comment]
EFF had to write "Thunderbird is vulnerable", not "GPG is vulnerable". I'm rather angry at EFF for spreading FUD about GPG.
