### ISSUE TITLE
Add owncloud

### ISSUE THREAD

**Issue by theScrabi** [nylira/prism-break#1930]
Please add owncloud to [productivity](https://prism-break.org/de/projects/nextcloud/), [password manager](https://prism-break.org/de/subcategories/android-password-managers/), [media puplication](https://prism-break.org/de/subcategories/android-media-publishing/), [file synchronisation](https://prism-break.org/de/subcategories/android-file-storage-sync/), [enterprise suit](https://prism-break.org/de/subcategories/android-enterprise-suite/) and [bookmark sync](https://prism-break.org/de/subcategories/android-bookmark-sync/).

ownCloud is  FLOSS software and a very stable and elaborate alternative to dropbox.

**Comment by Zegnat** [comment]
PRISM Break [switched ownCloud for NextCloud](https://github.com/nylira/prism-break/pull/1702) a year ago. The discussion behind this decision is in #1551. Is there any new and compelling reason to bring ownCloud back again? (I have not been following developments of the product.)

**Comment by theScrabi** [comment]
ownCloud is FLOSS software. Its true that there is a double licesnse for enterprise use.
However this makes the FLOSS version of ownCloud not less open source/free software.
We don't call openSuse not open source just because Suse is an enterprise product,
or we don't call KDE not open source because some parts of qt are proprietary available, don't we ;D

NextCloud and ownCloud are both based on PHP which is not the best language for security, thus a good code quality must be provided, and in the case of ownCloud this applies since they have big custumers that expect secure code. My perception is that the core part of ownCloud is very well maintained, and the apps available in thery market only get to enter when they received a propper code audit/QA.

I'd add both ownCloud and nextcloud the make it fair and provide an objective view over all the solutions that are available ;D

**Comment by yegortimoshenko** [comment]
PRISM Break does not try to encompass all software. Open core products are usually not included, unless there is a good reason to do so. This is a highly opinionated list.

Sorry, this has already been decided in #1551, closing as a duplicate.

**Comment by strugee** [comment]
I would tend to agree. That being said, if anyone can demonstrate strong advantages ownCloud has over Nextcloud, I would be happy to reopen this issue. But I suspect there won't be since there was quite the diaspora when ownCloud got forked.

**Comment by 128432b4117** [comment]
From a user perspective i see i see no strong reason to not (re-)add ownCloud again:

1. it is far from being an "open core product". There are a few enterprise grade apps available in a separate Enterprise Edition (see https://marketplace.owncloud.com/bundles/enterprise_apps) but AFAIK that's all.
2. it has a stable and mature core and is not feature-blown like its counterpart NextCloud. Especially this was the important for me why i had chosen oC over NC.
3. Dropping of oC IMHO shouldn't have been done based on the opinion of a few, even if this is a highly opinionated list.

**Comment by theScrabi** [comment]
> This is a highly opinionated list.

Well I don't want to question your work :D, since I think prism break is a great work, but I think maybe you should consider to discuss certain solutions. I mean everyone has his own opinions about software, it's like vim vs emacs. I think it was awesome if you sew strengths and weaknesses of several projects. Because this way you only favour a few and the rest is ignored.

> it has a stable and mature core and is not feature-blown like its counterpart NextCloud. Especially this was the important for me why i had chosen oC over NC.

This is excaclty the reason I chose oC over NC. oC doesn't do nearly as much as NextCloud, but what it does it does good. Also as I said from a security view this is better since the more plugins you install the more php code from different developers you have, and the higher the chance gets of catching a security issue. ownCloud isn't perfect on that point as well, you may have to feature permisson scopes, or even dockerise every module in order to grad a high level of security, but at least it they review the plugins before offering them. ... which is the reason they don't offer so much.

It's now over one year ago since https://github.com/nylira/prism-break/issues/1551 was opened. Many things can happen in one year. @yegortimoshenko maybe we should consider to open up this discussion once again :)

**Comment by yegortimoshenko** [comment]
@128432b4117:

> it is far from being an "open core product". There are a few enterprise grade apps available in a separate Enterprise Edition (see https://marketplace.owncloud.com/bundles/enterprise_apps) but AFAIK that's all.

I've counted 13, that seems problematic. Also, enterprise is not a grade :-P

> it has a stable and mature core and is not feature-blown like its counterpart NextCloud. Especially this was the important for me why i had chosen oC over NC.

Software having more modules is a sign of its prosperity, not a flaw.

> dropping of oC IMHO shouldn't have been done based on the opinion of a few, even if this is a highly opinionated list.

@alerque, @strugee, @vyp and myself have approved this decision, either directly or implicitly. This is at least a half of active members/contributors to the project.

---

@theScrabi: 

> Because this way you only favour a few and the rest is ignored.

We favor those that align with our values better. Developers using the brand to ship proprietary software is a considerable flaw, which is why we list Nextcloud but not Owncloud.

>  Also as I said from a security view this is better since the more plugins you install the more php code from different developers you have, and the higher the chance gets of catching a security issue.

Programs in PHP are not less secure. That myth comes from the time when there were a lot of underskilled PHP developers shipping code prone to SQL injections, cross-site scripting, and so forth. If anything, request-response model on language level and full state wipe between requests significantly reduce attack surface.

**Comment by 128432b4117** [comment]
> I've counted 13, that seems problematic.

Minus a "theming" and "licene key" which would be 11 against 50 (61 in total at the appstore) :-)

> Software having more modules is a sign of its prosperity, not a flaw.

It might be a (security-)flaw it this contributes to more complexity than people need, but i think this also way out of the scope here :-)

> @alerque, @strugee, @vyp and myself have approved this decision, either directly or implicitly. This is at least a half of active members/contributors to the project.

Ah, sorry. This shouldn't have sounded like that. I just had scrolled to the linked issue #1930 and just have read too many "i don't think", "IIRC" and "better" which sounded way too subjective to me.

> Programs in PHP are not less secure. That myth comes from the time when there were a lot of underskilled PHP developers shipping programs prone to SQL injections, cross-site scripting, and so forth. If anything, request-response model at language level and full state wipe between requests significantly reduce attack surface.

Completely agree with that.

**Comment by strugee** [comment]
> n my opinion it was awesome if you show strengths and weaknesses of several projects. Because the way it is right now you only favour a few projects and the rest is ignored.

To further respond to this/clarify things, I can only speak _definitively_ for myself but I think a lot of us have gotten allergic to adding stuff unless it _really_ has a compelling reason to be on the list. Experience has shown that if this policy isn't enforced pretty aggressively the list tends to balloon over time which reduces the overall quality and brings us more towards being a directory instead of an opinionated list. Less is more; it's often harder to choose the more options you have.

See for example the OS section before #1709 landed, or the IM section now.

**Comment by DeepDiver1975** [comment]
> it is far from being an "open core product". There are a few enterprise grade apps available in a separate Enterprise Edition (see https://marketplace.owncloud.com/bundles/enterprise_apps) but AFAIK that's all.
> 
> I've counted 13, that seems problematic. Also, enterprise is not a grade :-P

@yegortimoshenko you can see the non open licensed apps the same way as Debians contrib and non-free repositories. ownCloud works perfectly without those enterprise apps and are fully optional.

From my pov we are not an open core project - even if others like to push us into this direction.

Just saying .....

**Comment by tboerger** [comment]
@yegortimoshenko than you could also drop projects like Pydio, Gitlab or Wordpress since they are also following an open core model, just my two cents.

**Comment by yegortimoshenko** [comment]
> @yegortimoshenko you can see the non open licensed apps the same way as Debians contrib and non-free repositories.

This is not a valid comparison. A better comparison would be if Debian had implemented proprietary features and pitched them on their website, oriented to corporate customers (like, btrfs snapshot management, or proprietary-only package signature verification).

Debian wants all software to be free, and give freedom to install proprietary software to the user if they wish so. This is the correct compromise. ownCloud purposefully adds to proprietary code.

> @yegortimoshenko than you could also drop projects like Pydio, Gitlab or Wordpress since they are also following an open core model, just my two cents.

I would support removing Gitlab because there's Gogs, I'm not aware that Wordpress is open core, and I don't know anything about Pydio.

**Comment by DeepDiver1975** [comment]
> A better comparison would be if Debian had implemented proprietary features and pitched them on their website, oriented to corporate customers (like, btrfs snapshot management, or proprietary-only package signature verification).

Tell me where we do that? https://owncloud.org/

**Comment by tboerger** [comment]
Gitlab, Pydio and Wordpress are doing all the same, they provide commercial posts, I really don't get why this seems to be so bad only in case of ownCloud while it's licensed opensource.

**Comment by theScrabi** [comment]
> Software having more modules is a sign of its prosperity, not a flaw.

It's a sign of prosperity you are absolutely right, but selecting lesser apps with high quality is not a sign of unprosperousnes.

From my personal point of view I think selecting only a few solutions in order to keep it simple might not be the right model for representing the open source world. FLOSS lives from diversity, it gives you the freedom of choice, and thats awesome :D
Although I don't want to question the fundamentals of this project, and I respect if you want to go this way :)

I hope we could at least give you a little different view on things.

**Comment by yegortimoshenko** [comment]
> Tell me where we do that? https://owncloud.org/

All over [https://owncloud.**com**](https://owncloud.com) :-) 

> Gitlab, Pydio and Wordpress are doing all the same, they provide commercial posts, I really don't get why this seems to be so bad only in case of ownCloud while it's licensed opensource.

I'm aware about GitLab, I've checked Pydio and you're right, I think we should consider removing it too in favor of Nextcloud and/or Syncthing. I couldn't confirm that Wordpress ships any proprietary software, though.

Please understand that shipping proprietary software under the same brand is a criterion on this list, and it's not specific to ownCloud: Seafile, [Alfresco](https://github.com/nylira/prism-break/pull/553#issuecomment-23229554), [Zimbra](https://github.com/nylira/prism-break/issues/586#issuecomment-23493147), [BlueMind](https://github.com/nylira/prism-break/pull/709#issuecomment-27232714), have all been declined due to being open core.

**Comment by tboerger** [comment]
You can see at https://github.com/owncloud/core/blob/master/COPYING is clearly licensed under AGPL, same for the bundled apps. You can add enterprise apps optionally, but the core is definitely free. It's pretty clear explained at https://owncloud.com/owncloud-agplv3-owncloud-commercial-license.

I'm out of this discussion now, but I'm sad that a good listing like this rejects to accept an opensource project that is simply backed by a company to keep this project alive.

**Comment by yegortimoshenko** [comment]
You are being disingenuous. I've acknowledged that your ownCloud is open core product, as in, that core is open :-) The problem is that you're shipping proprietary software under the same brand.

> I'm out of this discussion now, but I'm sad that a good listing like this rejects to accept an opensource project that is simply backed by a company to keep this project alive.

No, I am very happy to see companies backing free software. Your statement presumes that money can only come from proprietary software, and not free software, and that's where we disagree. I think Nextcloud disagrees with you on the same token!

**Comment by 128432b4117** [comment]
@yegortimoshenko Maybe you could add some sort of FAQ to the wiki or the main page which explains why you / the project maintainers thinks that projects like ownCloud doesn't fit into your project goals and why those doesn't help users getting their privacy back just because some minor parts of the project are proprietary.

I think this could help to understand your reasoning behind the decisions made about such inclusion requests.

**Comment by hasufell** [comment]
> thinks that projects like ownCloud doesn't fit into your project goals

I don't know the *exact* reasoning, but the problem with that is probably that users might get used to a "solution" and by time get indirect feature pressure that may drive them into using the proprietary parts as well. And, in addition... the company controls what is proprietary and what is not and might change the boundaries to a point where users have to abandon an established workflow or have to accept that part of it is now proprietary.

However, I find that distinction a bit fuzzy. With gitlab, for example, it's perfectly fine and the developers have demonstrated a lot of open source passion.
I also think we shouldn't try to judge companies or business models too much, but just focus on the technical part, except when there are trust issues involved (e.g. when it's about redistribution channels).

**Comment by DeepDiver1975** [comment]
> Tell me where we do that? https://owncloud.org/
> 
> All over https://owncloud.com :-)

owncloud.com is the company backing the project and has it's own offering (which BTW covers much less features compared to the open source release - only focusing on file sync and share)

this own offering is called the owncloud enterprice editions which uses the agpl licensed server and selected apps which are distributed via the marketplace.

the same marketplace distributes a lot of open source apps developed by various developers for various functionalities.

we are not Open Core! Open Core mean feature-limited and this is not the case with ownCloud.
At least from my understanding.

**Comment by alerque** [comment]
I'm going to stay out of the licensing discussion for now. I have major beefs with open-core style projects too (including ongoing frustration with Gitlab, to which I contribute and have been offered and EE license but can't easily use because I maintain packages for the CE release and kind of need to dog-food my own work). The licensing fiasco would probably be enough to favor NC over OC on this site, but...

The point I want to add here is that NC is inherently a better product. I don't get where the argument about OC being more stable is coming from. Just because there are enterprise clients and a paid support option doesn't make the software better. In this cases the OC side of things move a lot slower to fix bugs, security issue, keep up with new versions of dependencies, etc. than the NC end. I have and still do maintain OC installations since the very early days of the project and the obnoxious bugs that manage to hang on through several release cycles are have been a constant pain point. The update process is also frequently problematic. By contrast NC is much quicker to address issues, and perhaps even too quick to adopt updated dependencies. Other than the PHP version fiasco the upgrade process has also been much less painful over the years.

Given the open source developer momentum is clearly with NC at this point, I don't see any reason at all to point this site's target audience toward OC. Some people might make that choice for themselves of course, but we don't need to recommend it here.
