### ISSUE TITLE
Consider Libremesh

### ISSUE THREAD

**Issue by coreyreichle** [nylira/prism-break#1933]
Commotion appears to be dead at this time.  However!  There is a "replacement":

Libremesh: https://libremesh.org/

It does everything that Commotion does, on more recent firmware (And more harware), it's only lacking in the area of simple iconography.

**Comment by alerque** [comment]
I don't see Commotion listed or even mentioned on PRISM-Break. Am I missing something here?

If this is a proposal to add a new recommendation rather than replace an existing one we'll need quite a bit more information about the project and some reasoning why it should be listed in addition to the other listings in the category.

**Comment by coreyreichle** [comment]
Huh.

Well, commotion was under the Router firmware page when I submitted this...

However, LibreMesh firmware could be an addition in the router OS section, however, not really sure if it's better there, or under the Mesh Network section?

**Comment by coreyreichle** [comment]
And, it looks like it was dropped as part of #1985

**Comment by yegortimoshenko** [comment]
(This has been moved to https://gitlab.com/prism-break/prism-break/issues/1933)
