### ISSUE TITLE
Consider 1.1.1.1

### ISSUE THREAD

**Issue by yegortimoshenko** [nylira/prism-break#1938]
See: https://1.0.0.1, https://1.1.1.1
Privacy policy: https://developers.cloudflare.com/1.1.1.1/commitment-to-privacy/privacy-policy/privacy-policy/

I think we should recommend that in DNS-over-HTTPS mode instead of current DNS server recommendations.

I also think that is what Firefox is going to do in the nearest future (they are going to send all queries through DNS-over-HTTPS to Cloudflare, see https://developers.cloudflare.com/1.1.1.1/commitment-to-privacy/privacy-policy/firefox/).

**Comment by Atavic** [comment]
Cloudflare doing the DNS over HTTPS business? No, thank you.

**Comment by ReK2Fernandez** [comment]
I will never recomend cloudflare over private DNS ever, I do not trust any corporation like cloudflare of anything they put online... screw cloudflare and this corporate assholes priority is money and whatever is free is for a reason.. "see facebook" one good does not take 100 bad

**Comment by yegortimoshenko** [comment]
> So, does this mean that Cloudflare is kosher after all?

Their business model is based on selling CDN and protecting against DDoS, not on selling user data. My guess is they want global DNS stats about IPv6 adoption and DDoS from this.

In comparison, our current recommendation, OpenNIC, doesn't even have a no-logging policy, some queries are filtered, it squats non-ICANN domains that can (and eventually probably will) conflict with ICANN like .geek and .pirate. From technological standpoint, only some OpenNIC resolvers support DNSCrypt, and none seem to support DNS-over-HTTPS, which is the current recommendation by DNSCrypt developer.

**Comment by Hillside502** [comment]
> DNS over HTTPS (DoH) is an **experimental** protocol
https://en.wikipedia.org/wiki/DNS_over_HTTPS

As interesting as it is, should we be even thinking of recommending it?

**Comment by yegortimoshenko** [comment]
It works well, and there are several good client-side implementations:

* `cloudflared` (https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/)
* DNSCrypt, which we recommend, author of which believes DoH to be the future: https://github.com/jedisct1/dnscrypt-proxy
* Firefox, which we recommend: https://bugzilla.mozilla.org/show_bug.cgi?id=1434852

DoH is being standardized: https://tools.ietf.org/html/draft-ietf-doh-dns-over-https-05

**Comment by yegortimoshenko** [comment]
DoH has also been adopted by Google Public DNS, which is probably the most popular DNS resolver: https://developers.google.com/speed/public-dns/docs/dns-over-https

So doesn't look experimental to me at this point.

**Comment by Flaganan43** [comment]
I do not understand why prism-break recommends using _any_ third-party DNS provider rather than their operating system's _default_ one (if that's what "Microsoft DNS (Default)" means in the list).

If I have understood correctly, default DNS for most of people will be provided by their ISP, which already knows much more of their internet activity anyway, so it won't give it any information he doesn't already have, right ? People may want to use other DNS providers typically to evade censorship, not to reinforce their privacy. Because it does exactly the opposite, giving lots of information about their internet activity to that third-party that wouldn't have had access to it otherwise. External DNS providers smell like the perfect tool of mass surveillance that prism-break is supposed to counter, not recommend !

About the "no-log" privacy policies : we _know_ they can't be trusted, you cannot check that DNS providers don't sell data in your back, especially if it is to the police State which has the power to force them to do so and keep quiet about it. So trusting the words of a US data giant like Cloudflare... I agree that when comparing two otherwise equivalent services, different privacy policies may matter, but here we're comparing giving data to the ISP who already has it anyway, or to some third-party who didn't have it before but promises that he won't look at it...

yegortimoshenko you wrote in issue #1481 about Google DNS :
> By the way, with plain DNS, any party on the route can collect your DNS queries, not just the endpoint, so without DNSCrypt or DNS-over-HTTPS it wouldn't matter whether query is sent to Google or somewhere else, unless you trust all nodes between you and that endpoint, which you shouldn't.

I have a doubt here too, if one uses default DNS provider. Isn't the data sent between you and the ISP DNS endpoint less exposed to extra dangerous thirdparties than if you gave it directly to _Google_, even with DNS-over-HTTPS ?

**Comment by yegortimoshenko** [comment]
That is not correct :-) Without having plain text of DNS queries, ISP has much less metadata that could be used to infer what their users do on the internet:

* sites that have been visited would *typically* not leak, only CDN network that some site that has been visited uses (e.g. Amazon CloudFront, Cloudflare), no subdomain access ever leaked (GitHub Pages, Tumblr, Neocities, etc. all use <name>.example.com domains to host user content).
* not trivial to figure out that DNS is used at all, for traffic inspection purposes there's no difference between that and generic HTTP/2 stream
* impossible to censor, which most of the countries force ISPs to do at this point

With most internet traffic being sent over TLS nowadays, it's becoming harder for ISPs to tell what any particular of their users is doing on the internet. We should enforce the proper position of ISPs, that of being only bandwidth/connectivity providers. Encrypting DNS is an important step towards that goal.

**Comment by yegortimoshenko** [comment]
>> By the way, with plain DNS, any party on the route can collect your DNS queries, not just the endpoint, so without DNSCrypt or DNS-over-HTTPS it wouldn't matter whether query is sent to Google or somewhere else, unless you trust all nodes between you and that endpoint, which you shouldn't.
>
> I have a doubt here too, if one uses default DNS provider. Isn't the data sent between you and the ISP DNS endpoint less exposed to extra dangerous thirdparties than if you gave it directly to Google, even with DNS-over-HTTPS?

With DNS-over-HTTPS, you don't care, there's no data leak except potentially leaking the fact that you use that particular server as your DNS resolver, and even that would only be the case if a) DNS resolver you're using is public, b) you're dealing with an active adversary, c) nothing else is being hosted at resolver's IP address.

**Comment by yegortimoshenko** [comment]
Another big DoH implementation: https://github.com/coredns/coredns

**Comment by Flaganan43** [comment]
> sites that have been visited typically would not leak, even to active adversary; only CDN network used by that site would be revealed (e.g. Amazon CloudFront, Cloudflare), subdomain would also never leak (Bandcamp, GitHub Pages, Neocities, Tumblr, etc. all use <name>.example.com domains to host user content)

> reliably, and without active snooping, even domains that resolve into a dedicated IP address would not be passively leaked, especially if reverse DNS lookup isn't set to a canonical domain, and usually it isn't; there is plausible deniability, it'd be hard to prove that other sites are not being served from that IP address

Interesting, I thought that visited sites were all leaked to the ISP because even with TLS browsing the ISP can see all the target IP addresses and domain names (via certificates and Server Name Indication). Apparently it doesn't help the ISP to see the visited sites, good to know.

> With DNS-over-HTTPS, you don't care, the only potential issue is leaking the fact that you use that particular server as your DNS resolver, and even that would only be the case if a) DNS resolver you're using is public, b) you're dealing with an active adversary, c) nothing else is being hosted at resolver's IP address. Middlemen can't really tell anything more than this.

What I meant is that with clear-text ISP DNS it's possible it's still mostly only the ISP who gets browsing data, while with Cloudflare DoH DNS it's ISP+Cloudflare. But as you explained, in the second case the ISP doesn't get the browsing data, only Cloudflare.


So the remaining questions are, is it really better for privacy to give all my browsing data to Cloudflare, than to give it to my ISP and the snoopers between me and my ISP ?
And, as censorship evasion is another motivation for changing DNS provider, hasn't Cloudflare already proved that it can arbitrarily censor sites too ?

**Comment by yegortimoshenko** [comment]
> Interesting, I thought that visited sites were all leaked to the ISP because even with TLS browsing the ISP can see all the target IP addresses and domain names (via certificates and Server Name Indication). Apparently it doesn't help the ISP to see the visited sites, good to know.

You're right, there is a spec for encrypted SNI (https://tools.ietf.org/html/draft-ietf-tls-sni-encryption-02), but it doesn't seem to be implemented anywhere. I previously thought SNI encryption has been resolved in TLS 1.3, there certainly were plans about that. Unfortunately it hasn't made into the cut. Sorry for misinformation.

Then this turns into a chicken and egg problem. DNS is much easier to log (doesn't require packet inspection) so there is little motivation to implementing encrypted SNI on clients until SNI is the only leakage. But then, we list DNSCrypt anyway, and DoH is no different in this regard.

**Comment by yegortimoshenko** [comment]
> So the remaining questions are, is it really better for privacy to give all my browsing data to Cloudflare, than to give it to my ISP and the snoopers between me and my ISP ?

I certainly do not think that ISPs can be trusted with such data, one of the reasons being that they have direct access to both personal credentials such as ID card, and the traffic.

This issue is not necessarily a praise of Cloudflare and its business practices or trustworthiness, but what is clear is that our current recommendation (OpenNIC) is worse overall than Cloudflare from every imaginable security/privacy angle.

**Comment by Flaganan43** [comment]
> You're right, there is a spec for encrypted SNI (https://tools.ietf.org/html/draft-ietf-tls-sni-encryption-02), but it doesn't seem to be implemented anywhere. I previously thought SNI encryption has been added in TLS 1.3, there certainly were plans to do that. Unfortunately it hasn't made it into the cut. Sorry for misinformation.

If we now agree that ISP see the browsing data whatever the chosen DNS is, I should then reiterate that using any non-default DNS provider (Cloudflare, OpenNIC,...) is a considerable loss of privacy.

Who has the list of visited sites : 
1) With default, ISP DNS : ISP+"anyone else listening on the Internet"
2) With Cloudflare DoH : ISP+"anyone else listening on the Internet"+Cloudflare (just maybe slightly harder to log for ISP and snoopers)
3) With OpenNIC with no DNS encryption : ISP+"anyone else listening on the Internet"+chosen OpenNIC provider

What I mean since the beginning is not necessarily that Cloudflare is worse than OpenNIC, but that both are certainly much worse for privacy than "Microsoft DNS (Default)" and "Apple macOS DNS (Default)" that are in the "bad guys" column of the prism-break list, if those mean ISP DNS. My suggestion is to remove the two "Default" DNS from the bad guys column. And to give a warning note that not using default DNS is actually worse for privacy. Prism-break advice of DNS providers will then still be useful for people who have understood that once they have accepted to sacrifice privacy to evade censorship, they should take this non-default provider rather than this non-default one because it's not as bad.

**Comment by yegortimoshenko** [comment]
Non-encrypted DNS queries to ISP is not a solution, it's perpetuating the problem.

**Comment by Flaganan43** [comment]
> Non-encrypted DNS queries to ISP is not a solution, it's perpetuating the problem.

Encrypted DNS queries to a non default provider is not a solution either, it's making the privacy problem worse.
The real solution might be tools like Tor that proxy DNS requests...

**Comment by yegortimoshenko** [comment]
ISPs do not generally have a privacy policy prohibiting them from collecting logs. DoH/DNSCrypt certainly improves privacy, because it requires much more active adversary and traffic analysis to extract the same data, which is immeasurably more expensive in comparison to DNS logs. Mainly, promoting encrypted DNS would help resolve the SNI issue faster. Encrypted SNI spec is already being worked on.

**Comment by anthologist** [comment]
If Facebook made its own DNS service with its privacy policy saying "we don't collect IP, queries, identifying informations, etc..." would you use it? Me, never.
Please don't even think suggesting a Cloudflare DNS, or Prism Break would really start scratching the bottom of the barrel.

**Comment by Flaganan43** [comment]
> Is there a community-driven DNS service with DoH, without blacklists/filters and with no-logging policy?

Here https://servers.opennic.org/ some of the DNS providers are without blacklists, not logging, and encrypting queries with DNSCrypt. The technical benefits of DoH over DNSCrypt are marginal, it's reliable encryption in both cases, not worth excluding a provider because of that technical difference. But it's true that the difference might become more relevant in usability if it happens that operating systems or browsers implement one and not the other, for example Firefox experimenting with DoH currently.

On the issue of trust, of course an evil corporation centralizing huge amounts of private information like Cloudflare in the land of Prism is not the best bet. But I'm not very comfortable either with organizations like OpenNIC, that look like anyone can anonymously register a DNS server in it for a time and vanish at any time, with no prior reputation check possible, and no risk of reputation damage if anything wrong is done, which in addition you'll probably never know. But maybe I misunderstood how it works.

**Comment by yegortimoshenko** [comment]
OK, I'm convinced that this is not the way to go. I'll open another ticket to make OpenNIC note more thorough.

**Comment by yegortimoshenko** [comment]
Maybe now we could reconsider? https://blog.cloudflare.com/welcome-hidden-resolver/

**Comment by Atavic** [comment]
> Is the hidden resolver secure?

SSL Report: https://www.ssllabs.com/ssltest/analyze.html?d=tor.cloudflare-dns.com

Certificate contains both clearnet and darknet URLs:

> This is possible using the "Alt-Svc" HTTP header

Click on any of the 4 servers on the SSL Report above and you get a warning:
*HTTP Strict Transport Security (HSTS) with long duration deployed on this server*.

There are Problems [here](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet), as cookieless tracking.

Scroll down on the same report page and you see the content of *Alt-Svc* that includes *ma=315360000*: I don't know how much this header could make users glow in the dark.

**Comment by yegortimoshenko** [comment]
I mean, it could as well score an F on SSL report, or use no TLS at all, because it goes over Tor which handles end-to-end encryption.
