### ISSUE TITLE
Remove Ricochet from "Encrypted Instant Messenger"

### ISSUE THREAD

**Issue by ohmynameisrico** [nylira/prism-break#1975]
https://prism-break.org/en/categories/windows/#instant-messaging

https://github.com/ricochet-im/ricochet/issues/579

**Comment by ohmynameisrico** [comment]
https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO/InstantMessaging

Copy start:
---

Software listed here has become depreciated and development has ceased. They are therefore considered unsafe and it is highly recommended to avoid using them. This section is here purely for historical value.

Ricochet IM is an open-source, decentralised instant messenger project that officially ended development in November 2016. Ricochet starts a Tor onion service on the users local system and facilitates communication with other Ricochet users whom are also running their own Ricochet-created Tor onion service, providing End-to-End encryption by never allowing the connection to leave the Tor network.

---
Copy End.

**Comment by strugee** [comment]
So, I too have noticed Ricochet has not had a release in a long time. I would like to look into this.

However we will need something more concrete than this. All I see in the linked issues is FUD and telling people to reread the FUD. For example, a useful question to answer would be: is the Tor shipped with Ricochet really out of date? Or is it fine because it's a Tor LTS release?

**Comment by yegortimoshenko** [comment]
Ricochet ships 0.2.8.9:

```
$ tar jxf ricochet-1.1.4-linux-x86_64.tar.bz2
$ ricochet/tor --version
Tor version 0.2.8.9.
```

See this list of Tor vulnerabilities: https://trac.torproject.org/projects/tor/wiki/TROVE

Ricochet is vulnerable to every vulnerability in the list except the first one. I think we should pull it down ASAP.

**Comment by ohmynameisrico** [comment]
@strugee It's not FUD. And stop saying FUD because I hate that word.
Ricochet is vulnerable.

**Comment by Zegnat** [comment]
> Tor <i>[version 0.2.8.9]</i> bundled with Ricochet is vulnerable to every vulnerability in the list except the first one.

Reading https://github.com/ricochet-im/ricochet/issues/578#issuecomment-393049811 it sounds like packaged versions of Ricochet will actually ship with newer versions of Tor? Or prefer using whatever version of Tor is locally installed?

@yegortimoshenko are you currently at a machine where you can verify that?

> It’s not FUD. And stop saying FUD because I hate that word.

I think what @strugee meant was that any outcry of “Ricochet is vulnerable” is quite literally spreading **F**ear, **U**ncertenty, and **D**oubt when it isn’t immediately followed by a cited source specifying the vulnerability in question. The originally quoted passage from the Tor project does not actually list any vulnerabilities.

We have had discussions here about listing “old” applications several times. The people of the Tor project have decided to consider stale applications “unsafe” and recommend against their use. Which is a fine policy to have, and PRISM Break has applied this same policy at times. Flagging software for (possible) removal based on it having gone stale is welcome. But that is a very different reason from removing something because it is known to be vulnerable or compromised.

In one of the threads you write:

> At least 10+ vulns are found and you still say secure?

But looking at issues filed on the GitHub repo since Jan 2017, I don’t actually see any vulnerabilities mentioned? Am I looking in the wrong place? That would be a pretty severe oversight on our part to leave any project in. If you cannot provide those vulnerabilities and are just making up numbers, how is it not FUD?

**Comment by ilovelinux** [comment]
@Zegnat go-ricochet uses your local Tor version as you can read here: https://github.com/s-rah/go-ricochet#building-an-automated-ricochet-application

**Comment by Zegnat** [comment]
Sometimes I forget the people who aren’t on my exact set up. This was clearly one of those times.

Although I haven’t put the time in to see if any of the listed Tor security issues affect the security of the Ricochet communication protocol itself. The Windows and macOS releases only being available with outdated binaries is a good reason to (at least temporarily) remove the project, I’d say.

At the same time I would see no problem putting it back up again if new packages are released that just update the Tor dependency. Especially since I haven’t seen any other vulnerabilities specific to Ricochet mentioned yet and I do like the idea of the project in leveraging the existing and tested Tor network for anonymity of the users. Looking at other communication applications we list, this at least seems to have a solid idea going for it.

My 2¢, in any case.

**Comment by strugee** [comment]
Is the consensus here that we would relist Ricochet if they fixed the bundled Tor version? That would seem logical to be provided that we got some sort of signal from upstream indicating that they wouldn't let it lapse again.

**Comment by yegortimoshenko** [comment]
I think keeping up with Tor releases (not just once, but constantly) will resolve the immediate problem, but large unmaintained C++ codebase is also rather spooky.
