### ISSUE TITLE
Now that TorMail has been compromised, we need more email alternatives

### ISSUE THREAD

**Issue by chovy** [nylira/prism-break#461]
MyKolab looked good except they require existing email and I think it costs money, could not tell.

**Comment by codekiddy2** [comment]
Hello guys,
I've been searching a lot before deciding to reply here and here are few suggestions/conclusions that I came out with:

According to your comments mykolab seems to be pretty good with privacy and after reading the privacy policy on https://mykolab.com/tos it's obvious that mykolab can give up data to Swiss government due to Swiss law if requested.

I'm not a law-guru but according to http://nomadcapitalist.com/2013/12/15/top-5-best-countries-host-website-data-privacy/
Switzerland is not top country when it comes to privacy, instead Iceland seems to be the best.
So I come up with https://unseen.is/ which claims to protect privacy as well according to https://unseen.is/privacy.html but it also can give up data to government if asked, reason why I think it could be better is that it is completely free unlike mykolab and also because Iceland has more strict privacy laws.
according to website it seems that it's still beta so I don't know how much my statements can be true when it comes to security in general.

Also Iceland is part of NATO while Switzerland isn't which is a minus for unseen since I don't trust countries that are part of the block when it comes to privacy
https://en.wikipedia.org/wiki/Member_states_of_NATO.

BTW fabianlischka (post before mine) noted tutanota.de but I'm not so much sure about germany :/

This is my personal opinion so please don't take it offensive.
I will further investigate about data privacy laws between Iceland and Switzerland only for comparison purposes.

BTW also creating free email accounts based in Switzerland seems to be impossible without giving proofs of residence or additional personal data. that scks.

**Comment by Zegnat** [comment]
In basically every country in the world the State could bring your email provider to court and have them forced to hand over your data. This is just as true for Switzerland as Iceland. If you do not want them to have anything to hand over use a solid encryption system like [GPG](https://prism-break.org/en/protocols/gpg/). I do believe that MyKolab does a good job of [explaining the swiss legal framework](https://mykolab.com/privacy/legal-framework), which Unseen doesn’t seem to do.

I would not put all too much trust in the Nomad Capitalist page. Romania made the list but is actually a country that tried [to implement the EU Data Retention Directive](https://en.wikipedia.org/wiki/Data_Retention_Directive#Romania). Twice. The Netherlands has been known to have provided information to the US global data collection program, but wins over Switzerland? This seems to be based on hosting companies not taking websites offline rather than evidence of them fighting back against wiretaps. Norway, coming in at number 2, is praised for not being part of the EU. That would be great, were it not for the fact that Norway often copies the EU going as far as [implementing the EU Data Retention Directive](https://en.wikipedia.org/wiki/Telecommunications_data_retention#Norway).

Is Iceland comparable in protection to Switzerland? It could be, just that none of the things you have linked really go into it so I cannot make a good judgement on the matter.

Is Unseen comparable to MyKolab? Maybe. I am definitely seeing some cons. MyKolab specifically runs their whole service on an open-source platform that you could also run yourself. As well as giving you the ability to back-up all your data and move away from them. While I didn't seen any mention about the technology Unseen uses.

One thing that scared me was reading this in the Unseen FAQ:

> <i>[…]</i> and premium users can generate and store their own private key.

And free users can’t? Does that mean free users do not get encryption or does Unseen generate their private key for them? The latter is **bad**. The whole idea of a private key (in public key encryption models) is that the user is the only one with access to it. Storing it on your email provider’s server is equal to not using encryption at all, so their practice may even endager their premium users if that’s what they mean. Extremely bad from a cryptography point of view there.

> I will further investigate about data privacy laws between Iceland and Switzerland only for comparison purposes.

Please do! Email is a sore point here as there are so many providers making claims and few of them that can live up to it.

> <i>[…]</i> creating free email accounts based in Switzerland seems to be impossible without giving proofs of residence or additional personal data.

MyKolab is not a free provider, but PRISM Break is less about free (<i>gratis</i>) and more about freedom (<i>libre</i>). Some of the free providers that we do recommend limit their users in another way, e.g. for I/A you have to agree to their politically charged manifesto.

> The http://prxbx.com/email/ website does not list any email providers :confused: do you know why?

Something seems to be broken on their end, we will have to monitor it and possibly remove our link to them. Too bad, as they were doing a good job sorting through a lot of providers.

**Comment by codekiddy2** [comment]
Thank you Zegnat for reply...
I spent some time reading unseen FAQ etc.. and would like to quote you on following:
> I didn't seen any mention about the technology Unseen uses

According to [TERMS OF SERVICE](https://unseen.is/term.html) under DESCRIPTION OF SERVICE
> Unseen uses encryption technology and software running on custom-designed and custom-built > > platforms controlled by Unseen

> One thing that scared me was reading this in the Unseen FAQ:

> […] and premium users can generate and store their own private key.

> And free users can’t? Does that mean free users do not get encryption or does Unseen generate > their > private key for them? The latter is bad.

Yes this is obviously bad, I created an account with them anyway and after completion was presented with dialog saying that I will not be able to **store** my private key on my computer, the point here is that emails are encrypted by them, but I use PGP anyway (as you suggested earlier) with thunderbird and torbirdy connecting via Tor network to them so their limitation by not giving me the right to actually store my private key locally makes no real world sense :confused:  
Anyway I'm nut sure about this since on their FAQ it says this:
> **How does it work?**

> We use a hybrid peer-to-peer and hosted network solution for transmission of encrypted > messages. Messages are encrypted and decrypted by each person sending or receiving a > message. They are never decrypted along the way (we don’t have the key). This is done > automatically and is transparent to the user and our services will appear on the surface to work the > same as the regular free email or chat services.

I do not understand what they mean by "we don't have the key" ? while also limiting local key storege :confused: 

> MyKolab is not a free provider, but PRISM Break is less about free (gratis) and more about > freedom (libre). Some of the free providers that we do recommend limit their users in another way, > e.g. for I/A you have to agree to their politically charged manifesto.

Yes I absolutely understand that, obviously unseen.is has choose to limit their "free" users by not giving them private keys unless you pay :D
I don't know but at least the service is free, and email transport is encrypted.

**Comment by Zegnat** [comment]
Did you see any mention of the technology used to store the private key? Because that sounds like a really, really bad thing to be doing…

**Comment by codekiddy2** [comment]
Zegant,
You are correct, they keep it all secret, I found an [Article](http://cryto.net/~joepie91/blog/2014/04/19/why-you-should-stay-away-from-unseen.is/) that elaborates unseen.is from security aspect more closely.
Thank you!

**Comment by svnpenn** [comment]
http://prxbx.com/email down again

**Comment by pickfire** [comment]
What make it down?

**Comment by kevinSuttle** [comment]
How has Fastmail.fm not been mentioned? 
https://blog.fastmail.com/2013/08/09/fastmail-uses-perfect-forward-secrecy-with-httpstls-connections/

**Comment by svnpenn** [comment]
@kevinSuttle it has

http://prxbx.com/email

**Comment by kevinSuttle** [comment]
Ah, I meant here: https://prism-break.org/en/subcategories/os-x-email-accounts

**Comment by svnpenn** [comment]
@kevinSuttle are you dense? The page I linked has over 20 providers, why would they list them all on the main page?

**Comment by kevinSuttle** [comment]
Who said _all_ of them? And watch your mouth. No need for that.

**Comment by svnpenn** [comment]
@kevinSuttle sorry, but no. You are being an idiot. The page here:

[prism-break.org/en/all/#email-accounts][1]

I layed out exactly as it should be. It has a few prime example, followed by
this link and text:

> For more email providers, take a look at [prxbx.com/email][2]

Also if you notice carefully, the first link I have has this text:

> Free Recommendations

According to the second link Fastmail is not free, so suggesting it for that
page is absurd. Go away.

[1]:http://prism-break.org/en/all/#email-accounts
[2]:http://prxbx.com/email

**Comment by kevinSuttle** [comment]
People like you give open source a bad name. Good luck being a sad little child.

**Comment by pickfire** [comment]
@kevinSuttle, @svnpenn: i'm going to need you to retard your anger level a few notches

**Comment by chovy** [comment]
I read that as `I'm going to need you to retard your angel level...` and was confused. Carry on :)

**Comment by svnpenn** [comment]
Hey @kevinSuttle, fuck yourself!

**Comment by vyp** [comment]
@kevinSuttle Fastmail is mentioned on http://prxbx.com/email/ though (which is mentioned at https://prism-break.org/en/subcategories/os-x-email-accounts/). I suspect it's not recommended on prism break directly because (some) of its servers are located in the US. That isn't necessarily a bad thing, but in practice it means that they're much more easily susceptible to being compromised by the US government. (i.e. See what happened to Lavabit.) I am surprised though to see no other mention of Fastmail on prism break's issue tracker, you're right!

**Comment by Zegnat** [comment]
Email itself is a pretty broken system from a privacy point of view. Too much metadata, too much data travelling in the clear. PRISM Break realises that people cannot go without email just yet, but we would rather not expand the current section.

1. Riseup and A/I are on there not because of their server locations but because of their history fighting for their users. Very few other email providers can claim the same long history of offering activists a way out. This is why these two are included over other providers.
2. Kolab Now is included partly because of their location (they really thought about their options and their website clearly states their do’s/don’t concerning the Swiss law) and partly because they use FOSS software. They even make it easy for you to migrate away from them into your own Kolab installation. And PRISM Break already recommends Kolab.

Linking to http://www.prxbx.com/email/ is a way to give people more choices, and inform them about those choices, without inflating the contents of PRISM Break.

If you know an email provider with either a history supporting activists (like Riseup) or with a set-up for privacy and open-source software (like Kolab Now) then please open a new issue specifically for that service. Otherwise you can assume PRISM Break is not actually the right place for it.

I am closing and locking this issue to stop people from dragging it up again.
