### ISSUE TITLE
Bookmark sync

### ISSUE THREAD

**Issue by DavidStaron** [nylira/prism-break#496]
Hi, maybe it would be useful to add alternatives to Instapaper, X-marks, ReadItLater, etc?

I've been searching one and only found this so far:

http://sourceforge.net/projects/semanticscuttle/

**Comment by GreenLunar** [comment]
Bookie is truly private, is self hosted, has abilities to import Chromium and Mozilla bookmarks, which makes it very good for those who do not want to be DEPENDED on some web browser because no other web browser handles the same bookmarks format.

Bookie has set me free from Mozilla after importing a ~50MB bookmarks file!

**Comment by GreenLunar** [comment]
There is also [SiteBar](http://sitebar.org/), which is one of the seniors bookmark managers in the business.

http://alien.slackbook.org/dokuwiki/doku.php?id=linux:sitebar
http://sourceforge.net/projects/sitebar/
