### ISSUE TITLE
Policy: One Strike and You're Out

### ISSUE THREAD

**Issue by sdelear** [nylira/prism-break#615]
I suggest creating two warning levels as a way to deal with a product that is not known to be compromised but generates some level of suspicion.  The second level, a strike, represents a company that best security practices should dictate that you have nothing to do with.

Warning: This level indicates a less serious security infraction.  All US technology companies pull a warning simply from the danger of the government compelling them to turn over data with a secret court order.  Open Source projects may pull a warning for interfaces with a stricken company/group in some way believed to be innocuous.  Warnings also apply to open source project that has had serious privacy/security issues - and has remedied them in the recent past.  For example: Firefox would be Warning: Google for a. making google search default and b. receiving funding from google.  Any US based company would get labelled, Warning: United States.  While this might not be fair to US tech companies, it is incumbent on them to lobby the government for reform if they want to get off the warning list.

Strike:  You get one strike and then you are out.  Your company will never get off the strike list.  A strike means that we must presume all of your products have been compromised. This means that backdoors may exists which both the NSA and third parties could use.  Best security practices are to have nothing to do with you.  Strikes come through:

A. Deliberately placing malware/spyware in any of your products.

B. Botching implementation of encryption.  No second chance, you either do it right the first time or are considered compromised by the NSA.  The NSA has sought to put backdoors into software.  Once any of your products are compromised, all of your products must be considered compromised.

C. Botching random number generation.  Again no second chances.

D.  Being named as complicit, beyond the requirements of a court order, with government surveillance.

For example Microsoft gets strikes for the fact that it's VPN systems can, apparently, be backdoored, for being complicit with government surveillance and for weakening encryption by making it impossible to copy and paste a passphrase (from a password safe) into GPG/Enigmail.  Microsoft has some many strikes that it is best to conclude that Windows random number generator has been degraded at the behest of the NSA and that their software also includes intentional backdoors.

Apple gets a strike for participating in PRISM.  We don't know everything that they have done, but we must presume that it is on the same level as Microsoft.  Further, they get a strike for degrading encryption in not allowing VPN as a always on option in iOS and defaulting VPN off (making it very easy to lose VPN if your iPad goes into slumber mode for a minute).

Canonical is stricken for putting spyware into Unity.  No second chances, you screw up like that once and you go into the same presumed compromised bucket as Microsoft and Apple.

Interestingly: under this policy Kubuntu and Mint could be listed with a Warning: Canonical flag.

**Comment by yegortimoshenko** [comment]
It seems to be counterproductive to set any more policies at this point. PRISM Break is *very* vigilant, and policy is very ambiguous (would it be applied to Riseup?) and even non-realistic:

> C. Botching random number generation. Again no second chances.

What about Debian PRNG bug? https://www.schneier.com/blog/archives/2008/05/random_number_b.html Clearly, Debian is still probably the distribution that aligns best with goals of this project.

> B. Botching implementation of encryption. No second chance, you either do it right the first time or are considered compromised by the NSA.

This is very vague. Would using a NIST elliptic curves (i.e. not ed25519) constitute this mistake? https://safecurves.cr.yp.to/

Would a bug in encryption-related code (e.g. exploitable off-by-one) constitute this mistake?

Would using CBC mode for symmetric encryption constitute this mistake (i.e. allows to write but not to read)? There are more states than just "compromised" and "not compromised".

All software presumably has bugs, it's just that not all bugs are known. When security-related bugs become known, they are usually fixed with the highest priority. And setting a policy ahead-of-time to remove such fixed software is counter-productive.

I call to label this issue as "waiting for objections" because we seemingly already have very high standards of what gets into the list, and discussion is more flexible than a set-in-stone policy.
