### ISSUE TITLE
Add "Virtualization" category

### ISSUE THREAD

**Issue by sochotnicky** [nylira/prism-break#633]
I believe a lot of people (even on *NIX systems) are stuck with VMWare and similar less-than ideal solutions simply because they don't know there are alternatives. 

First suggestion would be
# proprietary
- VMware
# Free/Open Source
- KVM
- XEN
- DOSBox (for old games maybe?)
- VirtualBox 

I guess some might argue that VirtualBox is open source and while core is, several important features are only available in proprietary extension. Problem might be that above are *NIX (or even Linux) only solutions with exception of VirtualBox so it is "good enough" in this sense if people are stuck on Mac OS or Windows.

Looks reasonable?

**Comment by Atavic** [comment]
[GNS3](https://github.com/GNS3/gns3-gui) Graphical Network Simulator.

**Comment by alerque** [comment]
GNS has seemly nothing to do with this issue @Atavic.

As for a `Virtualization` category I'd be in favor, but I think only point and click solutions that would be direct matches for things like VMware should be considered. More knowledgeable folks know when to apply KVM,  Xen, etc. The group we need to catch is the ones that need VirtualBox. I think we can probably recommend that (with a caveat about the proprietary add-ons module).

**Comment by strugee** [comment]
I would question whether we need a "virtualization" category. Is there any evidence that these contribute to PRISM? In the past we have declined to list e.g. LibreOffice as an alternative to Microsoft Office or Apple iWork (IIRC) because there wasn't a ton of evidence that just running those offline was problematic.

**Comment by strugee** [comment]
See https://github.com/nylira/prism-break/issues/834#issuecomment-32602419

**Comment by alerque** [comment]
@strugee This is an interesting topic and one that might need revisiting. VMWare does have a deeply ingrained habit of "phoning home". It's not quite impossible to keep it running firewalled in a corner, but it's not easy. Given a link to the net it also seems to do a lot more than just check it's license status.

By the same argument it might be time to review our long standing ignoring of office suites as well. When we first started ignoring them it was generally possible to just let them hum along offline. However with recent versions increasingly sharing document and state data to their respective cloud counterparts this argument is becoming less and less valid. The amount of surveillance that could be done on a user if you could watch what their office suite is doing online is pretty significant. The lines between online suites like Google Docs and offline suites like MS Office and iWork are pretty blurry at this point.

I also made this note a couple years back (https://github.com/nylira/prism-break/issues/1155#issuecomment-57899570) for PDF readers. I would repeat it here, that Adobe's reader has so many cloud features turned on by default now it should probably be considered as something we need to provide alternatives for that don't carry the risk of privacy leaks because they don't upload everything you view to a 3rd party server.

Back to VMWare. It's definitely borderline, but I would still support adding a Virtualization category. If people follow our advice on operating systems, a good VM host is likely something they will need to sandbox the risky software they still want to run.
