### ISSUE TITLE
CyanogenMod has recently gone commercial

### ISSUE THREAD

**Issue by istubbs** [nylira/prism-break#654]
Should CyanogenMod still be listed now that they have gone commercial?
https://plus.google.com/106978520009932034644/posts/L8FJkrcahPs
With them now dual-licensing code to allow for closed-source alterations that will not be committed back to the public repository as I read it, CM suddenly seems a lot less secure to me.

**Comment by alerque** [comment]
This issue is obsolete and can be closed, Cyanogen was removed.

**Comment by Francewhoa** [comment]
For those not familiar with what happen with CyanogenMod. CyanogenMod went commercial. In other words, Cyanogen Inc. tried to monetized the open source community project CyanogenMod. Sounds like Cyanogen Inc. were serving money first instead of serving the community first ;) As a result the community forked CyanogenMod to LineageOS at https://github.com/lineageos and http://lineageos.org Which is fully community-owned. And without strings attached to any corporations :) So really free of corporate interference.

On 23 December 2016, Cyanogen Inc. announced that they were shutting down the infrastructure behind CyanogenMod. This was shortly followed by news that the main CyanogenMod project would migrate, renaming itself as "LineageOS". On December 24 2016, Head of Developer Relations and community forum administrator Abhisek Devkota, a Cyanogen "core team" member, wrote that the community had lost its "last remaining advocate" within the company and its voice in Cyanogen Inc. and its software's future. He stated that while "that this most recent action from [Cyanogen Inc.] is definitely a death blow for CyanogenMod", the community had already begun taking the steps needed to fork the project under a new name, and aimed to return to its grassroots origins while retaining professional approaches adopted during the Cyanogen Inc. era. Due to the negative connotations attached to Cyanogen Inc's conduct, as well as the scope for legal dispute, the forked project decided not to use the existing brand names "Cyanogen" or "CyanogenMod", which in any case belonged to the company.

Homepage http://lineageos.org/ 

Read more https://en.wikipedia.org/wiki/LineageOS 

Related post https://web.archive.org/web/20161225144318/https://www.cyanogenmod.org/blog/a-fork-in-the-road

**Comment by alerque** [comment]
@Francewhoa Please don't double post, it just makes more work for those of us monitoring this project and dilutes relevant discussion across multiple locations. As this issue is already resolved, anything relevant to an action point (such as possibly adding Lineage) should stay on the Lineage issue.

**Comment by Francewhoa** [comment]
alerque :) I agree. I tried to remove my duplicate post. But can't find it.
