### ISSUE TITLE
SElinux built by the NSA, used by Fedora (edit: generally Linux)

### ISSUE THREAD

**Issue by Juliu5** [nylira/prism-break#662]
So what are your thoughts about using Fedora, since SElinux is built by the NSA (http://www.nsa.gov/research/selinux/) ?

Don't use Fedora at all, get rid of SElinux (how?), trust that SElinux really improves your security....... ?

cheers

**Comment by geofft** [comment]
@hasufell, I think this analysis is incorrect, but let me know if I am misunderstanding you. I was pointed here by a Reddit thread asking if GPG-signing in git is "broken".

SHA-1 is known to be vulnerable to *collisions* by a somewhat well-equipped attacker (I would not say "easily", but certainly doable by a rich enough attacker, as you say). It is not known to be vulnerable to *preimage attacks*, either in the public literature or in the Snowden leaks. Schneier's blog post is just about collisions; the phrase "preimage attack" doesn't appear.

A collision attack allows one party to generate two messages with the same hash. In an attack scenario, think of someone generating a contract, getting someone else to sign it, and then replacing it with a different contract. Or generating an SSL CSR, getting a CA to sign it, and then substituting a different certificate body to get a forged, valid SSL certificate.

A preimage attack allows one party to generate a message that matches a hash generated by another party. This differs from the collision attack because the attacker isn't allowed to choose a hash or a first message that's convenient to them; they have to come up with a second message for a hash that's already been chosen for them.

To successfully attack git signatures in this scenario, an attacker needs to match some commit object that's already been chosen for them. There's some valid software, the attacker modifies it, and the signature remains valid on the tampered software. This is a preimage attack.

If you try to use a collision attack against git, you're positing a scenario where an attacker is coming up with two git trees/commits with the same hash, signs one, and then later swaps out the commit for the other. You can imagine a scenario where this actually turns into an attack, but in the general case, you have to assume that the attacker is capable of signing one of the commit objects, in which case, why can't they sign the other? There's no actual need for a collision here.

Since there are no known preimage attacks on SHA-1 that have any better runtime than brute force, there isn't a realistic attack on git here, unless you think the hash length is inherently too small (i.e., a security level of 160 is too low). I do concede that it is very sad that there seems to be no plan to move git to SHA-256 (or SHA-3 or BLAKE2 or something) fairly soon. But the continued use of SHA-1 here is not yet a vulnerability, for probably a couple of years, and you might as well gain the security of signed commits in the meantime (unless CVS has signed commits?).

**Comment by hasufell** [comment]
> To successfully attack git signatures in this scenario, an attacker needs to match some commit object that's already been chosen for them.

No, you just attack the blob object and send it as man-in-the-middle, e.g. during a clone.

And yes, with 'easily breakable' I was just referring to collision attack, not preimage attack. Also keep in mind that Bruce Schneier himself said that NSA may not just be ahead of us in terms of resources, but also in terms of maths/theory.
Therefore I don't think it's reasonable to choose SHA-1 for something as widely used as git.

**Comment by geofft** [comment]
> No, you just attack the blob object and send it as man-in-the-middle, e.g. during a clone.

I still don't understand how to use a collision attack here. The blob object already exists with a specific hash listed in the tree object, so you have to use a preimage attack, right?

Anyway, I don't think it's reasonable per se to choose SHA-1 either, but it is in fact pretty secure today, and in particular it is way better than using a VCS that doesn't support signed commits at all. (I'm a bit off-topic for this issue, and I apologize for that; it may be better to continue this discussion [on the Reddit thread](https://www.reddit.com/r/AskNetsec/comments/2qxbm0/is_gpgsigning_in_git_broken/) if you have an account there.)

**Comment by rwzy** [comment]
> Also keep in mind that Bruce Schneier himself said that NSA may not just be ahead of us in terms of resources, but also in terms of maths/theory.

Sort of off topic, but I think this point may just need a bit more emphasis in this current discussion of key length. *I know everyone already knows this,* but in reply to geofft's remark:

> But the continued use of SHA-1 here is not yet a vulnerability, for probably a couple of years

I know he's talking about rsa keys and not hashes, but I still think it has relevance: https://www.youtube.com/watch?v=0SgGMj3Mf88#t=3594

> You are not encrypting for today, I mean you are, but you are also encrypting for 50 years from today.

**Comment by nodiscc** [comment]
@hasufell 

> No, you just attack the blob object and send it as man-in-the-middle, e.g. during a clone.

The blob object hash is referenced in the tree object, whose hash is referenced in the (signed) commit object, so altering only the blob object wouldn't work. My understanding is that you still have to do a preimage attack on the commit object hash.

**Comment by hasufell** [comment]
> The blob object hash is referenced in the tree object, whose hash is referenced in the (signed) commit object, so altering only the blob object wouldn't work. My understanding is that you still have to do a preimage attack on the commit object hash.

Yes exactly, but the point is that although your commit object is signed... you don't even have to care about breaking the signature! You just attack SHA-1 on the blob object level. That's not the purpose of signing yout stuff in git. Therefore, the concept is currently broken.

Whether that is considered a vulnerability today is indeed debatable. But as Linus said himself that SHA-1 is NOT a security feature... something must be miscommunicated/misdesigned here.

**Comment by strugee** [comment]
This discussion is years old and there isn't anything I can see that we should do about the original topic (SELinux). Closing.
