### ISSUE TITLE
zuluCrypt:an alternative linux GUI solution for TRUECRYPT and LUKS volumes

### ISSUE THREAD

**Issue by mhogomchungu** [nylira/prism-break#688]
link: http://code.google.com/p/zulucrypt/

zuluCrypt is a front end to cryptsetup and tcplay and its a tool that make it easy to manage LUKS,PLAIN and TRUECRYPT encrypted volumes through a GUI and a simpler to use CLI interface.

zuluCrypt can manage encrypted volumes residing in regular files,LVM devices,mdraid devices as well as regular block devices and partitions.

**Comment by hasufell** [comment]
yep, get it included

**Comment by Zegnat** [comment]
So if I understand this and a previous discussion right this is only a GUI/CLI shell around long standing encryption libraries? That feels like a no-brainer inclusion to me.

Tougher question: would this replace anything? It would be sweet if PRISM-Break can boil the encryption category down to one solution per platform.

**Comment by hasufell** [comment]
> That feels like a no-brainer inclusion to me.

We include convenient windows software to not alienate people... but we don't tell linux users how to easily make use of cryptsetup/dm-crypt. That's a pretty big miss IMO.

**Comment by hasufell** [comment]
> The biggest grief I have against zulucrypt is that it's not packaged yet for major Linux distros

As I've described in the ubuntu thread. Any form of binaries cannot be trusted. Use a source distro if you have such concerns.

I really think this is not even an argument. Truecrypt wasn't even packaged in debian, yet it was included. I could go on for a LOT of stuff that is recommended on prism-break, but barely packaged in major linux distros.

**Comment by nodiscc** [comment]
> Any form of binaries cannot be trusted. Use a source distro if you have such concerns.

I agree but there are various levels of trust. I trust my distro package maintainers/uploaders to do basic reviews and tests of what they package (+ there is generally a sane delay between a bleeding edge software release and the packaging/wide availability in stable distros, during which vulns/bugs can be found). Don't put inexperienced users in the bad habit to run random scripts from tarballs or master branches (not on Linux plz)

Proper package systems and careful distros _do_  add a decent level of security. They can't prevent malicious compilers and packagers failing at packaging; this topic and can be discussed somewhere else.


> we don't tell linux users how to easily make use of cryptsetup/dm-crypt (which is sort of an advanced thing). That's a pretty big miss IMO.

Yes and I feel the same way for encfs/cryptkeeper (https://github.com/nylira/prism-break/issues/1209)

Installing from a tarball (https://github.com/mhogomchungu/zuluCrypt/releases) is pretty advanced for an average user though. So to make it easy enough it should be packaged. A package system is also more safe; no bumblebee-installer-rm-rf-like bugs in the package.


> a LOT of stuff that is recommended on prism-break, but barely packaged in major linux distros.

I agree this should be fixed (by working on packaging them, and prioritize packaged software in prism-break list).

That said I agree about adding zulucrypt to the list. But it would be even better if packaged. Maybe add a reminder on the GNU/Linux page saying `When using GNU/Linux, try to manage installed software through your package manager. Avoid running unverified software.`

What do you think?

**Comment by hasufell** [comment]
> I agree but there are various levels of trust.

If you don't trust upstream, then your trust on the distributor doesn't change anything.

> Proper package systems and careful distros do add a decent level of security.

I've read the whole build system of zuluCrypt. There are no scripts that can cause harm.

The advantages of packaged software are obvious and everyone here probably knows them. But they shouldn't be a blocker for inclusion. After all... prism-break may even help with software getting pushed in major distros, because users will ask their distributors why it isn't included yet. It's not really prism-breaks job to keep an eye on the ecosystem of packaged software. Distros that don't support much software recommended on prism-break should rather be removed instead of removing or not inclduing an application.

> What do you think?

We lack a guide to a lot of things... and that's what people need. But I'm not sure if that's within the scope of prism-break. And I haven't seen many pull requests for that kind of thing so far.

**Comment by nodiscc** [comment]
> If you don't trust upstream, then your trust on the distributor doesn't change anything.

I trust my distro package maintainers/uploaders to do basic reviews and tests of what they package

I agree with everything else you said.

 * We lack a guide to a lot of things (maybe another git repository with contributed guides in markdown? example https://github.com/nodiscc/notes/blob/gh-pages/admin/pidginotr.md)
 * The advantages of packaged software are obvious and everyone here probably knows them. But they shouldn't be a blocker for inclusion. After all... prism-break may even help with software getting pushed in major distros

**Comment by hasufell** [comment]
> I trust my distro package maintainers/uploaders to do basic reviews and tests of what they package

I'm sorry, but that's a vision, not reality. We don't do code reviews at all. Only OpenBSD guys *claim* to do them since years... yet they didn't see the OpenSSL mess coming either for that long. You need significant resources for code reviews, e.g. a professional code review of the X server took about a whole year for a single person. A packager usually has up to ~200 packages he regularly works on. It is simply impossible to review anything other than e.g. the build system.
What packagers do is:
* test if the package builds
* test if the package runs
* write build scripts
* if he takes his job VERY seriously... he might even verify the upstream tarball signature (even that rarely happens)

Nothing more, really.
