### ISSUE TITLE
prism-break should be completely self-hosted

### ISSUE THREAD

**Issue by hasufell** [nylira/prism-break#767]
that includes this repository

possible solutions include gitlab
http://gitlab.org/

gitlab also allows authentication via github accounts

**Comment by hasufell** [comment]
an interesting newcomer is https://github.com/gogits/gogs ... it's written in Go, VERY easy to deploy and probably 10 times faster than gitlab

it's still missing pull requests, but they are coming https://github.com/gogits/gogs/issues/5

**Comment by nodiscc** [comment]
Another thing to consider is that Github really eases drive-by contributions, because it has a large userbase and gives visibility to this repo. So having a backup plan would be nice in case of outage or something bad happening, but keeping the Gitub project up is IMHO necessary if you want to keep the project active.

http://popcorntime.io/ Github repos were taken down by a DMCA complaint, they moved to Atlassian Stash, but Gitlab or Gogs is also possible. 

Regarding issues, I'd advise doing a backup using something like [github-backup](https://github.com/joeyh/github-backup) (in Debian repos) or a custom script (I did that with [ghi](https://github.com/stephencelis/ghi) and a custom bash script for https://github.com/nodiscc/Shaarli/tree/issues-backup/doc/issues). Be careful because the issues/comments count is rather large on this project and you may hit the API limits.

**Comment by hasufell** [comment]
gogs now has pull request and it is _very_ easy to deploy. There are even docker images which make it even easier to run and update:
https://hub.docker.com/r/gogs/gogs/
https://github.com/gogits/gogs/tree/master/docker
https://github.com/hasufell/docker-gentoo-gogs

So people could still login via github, because of OAuth. The github repo could be kept as a mirror. The only problem is migrating the issue tracker... if that's even possible.

**Comment by hasufell** [comment]
I have a gogs mirror of prism-break here: https://gogs.hasufell.de/hasufell/prism-break

**Comment by alerque** [comment]
@hasufell The issue tracker is kind of the bread and butter of  this project. Not only is it a must-have for keeping a record of discussions around individual apps that are linked to the actual changes on the site, the history is also indispensable and I don't think any proposal to move the code should go forward without a matching clear path forward for the issue tracker (including migration and cross-linking of old issues). As long as issue tracking is being done here, I don't see the harm in having it be the canonical repository as well. We all have mirrors of the code base anyway.

**Comment by hasufell** [comment]
> I don't see the harm in having it be the canonical repository as well

Github is centralized and proprietary. There isn't any harm to _mirror_ prism-break on github for availability. But it is inappropriate to have it as the primary contribution platform. I know quite a lot of people who don't want to use github at all and don't have an account. There's no easy contribution workflow for them.

**Comment by yegortimoshenko** [comment]
Switch to Gogs would be very nice.

**Comment by 2SI3NX** [comment]
Anyone considered trying out hosting on Substratum nodes?   Haven't tried, but maybe its worth a shot since its decentralized.. just an idea.

**Comment by yegortimoshenko** [comment]
Closing in favor of more recent #2011.
