### ISSUE TITLE
Encrypt.to - Email encryption tool 

### ISSUE THREAD

**Issue by wiegelmann** [nylira/prism-break#776]
We open sourced our web based PGP message delivery software for Ruby, PHP and Perl. With https://encrypt.to you can send encrypted messages to PGP users and you can receive encrypted messages from non-PGP users. We are using client side encryption and we can't decrypt the message. By the way, we don't store your message.

Category: Email encryption
Source Code: https://github.com/encrypt-to
Owner: https://github.com/wiegelmann
Demo: https://encrypt.to
MIT License

**Comment by lukateras** [comment]
The service is susceptible to [Evil 32](https://evil32.com).

Example: https://encrypt.to/0x00000000 (find my email in "to" list)

It's trivial to bruteforce 32-bit IDs, I don't think we should list a service that allows making that mistake. And also it's dangerous to fetch keys from a key server without establishing chain of trust with the recipient, even fetching key from someone's site is more secure than a key server.

Besides that, this might have become an "open core" service. Besides that, this [hasn't been updated since August 2017](https://github.com/encrypt-to/encrypt.to).

**Comment by alerque** [comment]
Agreed that this was not viable for other reasons, but please note the "code last updated" since argument here is pretty weak. A lot of small tools work fine and rarely need updating in order to stay secure or usable. It's not impossible to use that as part of an argument, but without actually evaluating more development related factors it's pretty meaningless to just cite that.

**Comment by yegortimoshenko** [comment]
That was a minor part of my argument, I've mostly addressed Evil 32 attack.
