### ISSUE TITLE
What about Hardware section?

### ISSUE THREAD

**Issue by pysiak** [nylira/prism-break#788]
What hardware we know is tainted: Intel Processors? All of them? Is AMD known to cooperated? Wifi Chips? We know for sure at least 4 hard disk manufacturers (wdc, seagate, maxtor, samsung), a couple of computer systems (dell, hp), phones (samsung, iphones), etc..

**Comment by vyp** [comment]
Continuing from #1264, a *possible* starting point could be [h-node](https://h-node.org/hardware/catalogue/en) and [ryf](http://www.fsf.org/resources/hw/endorsement/respects-your-freedom)? (As they are recommended by fsf.) Also see http://www.fsf.org/resources/hw.

Also:

- http://www.gluglug.org.uk/
- https://puri.sm/

This is probably still a small limited list though. And I don't know much about hardware to know if these free software focused hardware stuff is relevant to security (although I would imagine they are, at least compared to most other standard OEM hardware)... thoughts?

**Comment by mastercoms** [comment]
Well we should recommend libreboot or coreboot because those are what make the gluglug and purism free. But, if NSA involvement in computer manufacturing is as widespread as it could possibly be, there would be no point in freeing the software, drivers, or firmware because the hardware would be compromised already.

And Intel would be most definitely compromised if hardware has been compromised by the NSA. Therefore, although these devices have a preinstalled freed BIOS, they still rely on Intel and other manufactuers who may be collaborating with the NSA.

Hnode does not necessarily recommend freedom/NSA-proof devices, but rather devices that would work well with open source software, so I don't feel it gets us anywhere, although having a freedom compatible device, or even a device built around freedom, like the Gluglug or Purism would probably be better than having a normal device.

The best option would be to recommend [open source hardware](https://en.wikipedia.org/wiki/Open-source_computing_hardware), but no real contenders exist.

**Comment by strugee** [comment]
While this is a real problem, it's not within the scope of PRISM Break. See https://github.com/nylira/prism-break/issues/1616#issuecomment-264105662 and the comments following it for a quick discussion on this.
