### ISSUE TITLE
Using the AGPL license?

### ISSUE THREAD

**Issue by ghost** [nylira/prism-break#821]
The project currently uses GPL3. This is a strong license for protecting freedom.
However, the AGPL protects more freedom. So what about using it?
https://www.gnu.org/licenses/agpl.html
https://www.gnu.org/licenses/why-affero-gpl.html

**Comment by hasufell** [comment]
> Is there anywhere I can find exactly what benefits we get from using AGPL over GPL?

It closes the GPL loophole where someone could:
1. fork prism-break
2. make non-trivial changes to the code and turn it into a surveillance service that collects identity and user behavior data
3. not publish the source code he runs on the server, because it's technically not redistribution
4. not actually violate your GPL license

Sure you can argue you won't be able to catch such guys anyway. But you could say the same about GPL. Now you have legal grounds, at least.

> You will also find that some of us will never agree to license anything as AGPL3+ because of the +

Yes, but I agree to AGPL-3.

IMO, we should try to work towards this goal, so:
1. reopen this issue
2. prepare a short text containing the reasoning of the license change
3. make a list of all contributors (via git, should be easy)
4. contact them, providing the reasoning, and ask for permission to change the license

**Comment by vyp** [comment]
I agree with @hasufell , AGPL is preferable due to prism break being hosted on the web (like a web service/software, sure it is a static site but I mean the software to generate the static pages). I'm willing to at least try to get contact from all contributors (although because of the timescale I have to be honest the chances of some contributors not responding at all is quite likely) when I get the time, if @nylira and @Zegnat are okay with it? Right now I don't have time to be doing this though, eta for me to do it would be december or so unfortunately...

Also IANAL but the incompatiblity from GPLv2 to GPLv3 wasn't really about not being afraid to make bigger changes. From my understanding the FSF really did want to avoid the compatibility issues (they had a long public consultation process to try to get feedback and make as much people they could happy), but were basically forced to make all these changes due to new times (of computers/internet/technology). (There's one and a half decades between version 2 and 3, and this one a half decades was at a critical time for the internet too..)

So while version 2 and 3 are incompatible, if it's GPLv2+, and if you're using the software with something of yours that's GPLv3, then to avoid the incompatiblity, you can just choose to use it under version 3 too. So by my understanding (I could be wrong), it's supposed to function as sort of a safety net so that GPL users (i.e. developers who license their software under the GPL using other GPL'd works) don't get bitten by incompatibility. Of course, there's still definitely a huge trust with the FSF here that you don't really know what GPLv4 could bring, I'm not denying that!

Anyway so I'm okay with either AGPLv3+ or just AGPLv3 of course, but personally prefer AGPLv3+. (By the way, I'm not a fan of contributor license agreements though.)

**Comment by nylira** [comment]
I'm okay with this. Go ahead, @vyp

**Comment by hasufell** [comment]
> So while version 2 and 3 are incompatible, if it's GPLv2+, and if you're using the software with something of yours that's GPLv3, then to avoid the incompatiblity, you can just choose to use it under version 3 too.

That's a non-issue. You can dual-license your project, as in `|| ( GPL-2 GPL-3 )` and let the user choose which one he wants to use. A lot of projects do that. Also see https://en.wikipedia.org/wiki/Multi-licensing

**Comment by vyp** [comment]
I don't think you can, if you choose to use a GPL2 only library, your application cannot have a GPL3 option, no?

**Comment by RyDroid** [comment]
@vyp You can not in all cases, like the one you wrote. But there should not be a problem for PRISM Break, as much as I know (but my last contribution is old).

**Comment by hasufell** [comment]
> I don't think you can, if you choose to use a GPL2 only library, your application cannot have a GPL3 option, no?

If you multi-license your project, all license options must be valid and not violate other licenses, obviously. `|| ( GPL-2 GPL-3 )` is literally the same as `GPL-2+` at this time. The only difference is the future.

**Comment by RyDroid** [comment]
@hasufell GPLv2 or GPLv3 is currently the same as GPLv2+. But a project under GPLv2+ can be used by a GPLv2 only or GPLv3 only project. "When software is multi-licensed, recipients can choose the terms under which they want to use or distribute the software." https://en.wikipedia.org/wiki/Multi-licensing

**Comment by hasufell** [comment]
> GPLv2 or GPLv3 is currently the same as GPLv2+. But a project under GPLv2+ can be used by a GPLv2 only or GPLv3 only project.

`|| ( GPL-2 GPL-3 )` can be used by a GPL-2 only or GPL-3 only project.

**Comment by RyDroid** [comment]
@hasufell None. "all license options must be valid and not violate other licenses" could lead to think that a GPLv2 only or GPLv3 only project could not use a project under GPLv2+ or GPLv2+3.

**Comment by lukateras** [comment]
CC0-1.0 would be a much better fit. GPLv3 or AGPLv3 do not protect anything because there's nothing to protect, it's just a static website.

**Comment by RyDroid** [comment]
> GPLv3 or AGPLv3 do not protect anything because there's nothing to protect, it's just a static website.

Even for a static website, there are potential things that could be licensed.

- There is source code (makefile, Travis CI, etc.)
- Text can be under copyright. For example, it is the case for almost all new books and it is even the case for a lot studies (read the end of the story of Aaron Swartz if you are not convinced). We even have the most obvious case in the IT world with Wikipedia.
- It can be seen as a database and there are rights for that in some places (however the licenses of the GNU project do nothing for that). For example, OpenStreetMap uses Open Data Commons Open Database License.

**Comment by yegortimoshenko** [comment]
Most of the value is the list itself, i.e. value judgement, and I don't believe that to be copyrightable. There might be a place and time for copyleft licenses, but there is no value to be made in making this list proprietary or whatever. CC0-1.0 would be way more valuable to us in this context because it'd reaffirm that people can copy anything from it without any fear of persecution.
