### ISSUE TITLE
Add Mageia?

### ISSUE THREAD

**Issue by marcus86** [nylira/prism-break#872]
How about adding Mageia as a recommended OS?

Mageia is a fork of Mandriva Linux created in 2010 that recently had a quick rise in popularity. It's the 4th most popular distribution according to distrowatch.com and I think it's suitable for beginners in contrast to some of the other recommendations.

**Comment by haary** [comment]
I advocate also for the inclusion of Mageia. Since the *buntu based distros are gone [for good reasons](https://github.com/nylira/prism-break/issues/334) there are very few beginner-friendly GNU/Linux distros listed at prism-break. Mageia is. Plus the distinguish clearly between free and non-free software. Mageia  is community driven and as I tested it they reacted quickly regarding security issues.

**Comment by lukateras** [comment]
We've been trying to shrink down the OS category. As far as I know, Mageia doesn't have any advantages in privacy aspect that Debian, Fedora or Qubes do not offer. So, closing.
