### ISSUE TITLE
Add Surespot to iOS/Android Instant Messaging Alternatives

### ISSUE THREAD

**Issue by xaxl** [nylira/prism-break#881]
https://www.surespot.me/

https://missingm.co/2014/02/fighting-dishfire-the-state-of-mobile-cross-platform-encrypted-messaging/

**Comment by juanito003** [comment]
Surespot was a good program for end-to-end chat encryption with iOS users. But on alternative android ROM (cyanogenmod, paranoid android, etc) without Google Play you don't get any notification. It cannot be included in F-Droid because it relies on Google Cloud Messaging (GCM). For more info read:
https://github.com/surespot/android/issues/22
https://github.com/surespot/android/issues/30

It seems the surespot project is dead. Fortunately there is Kontalk making good progress (but without iOS app for now).

**Comment by arno01** [comment]
@juanito003 if it does all the math (end-to-end encryption) on the phone, then it does not matter which channel it uses as transport (be it GCM or whatever). The whole idea of the end-to-end encryption is not how many hops encrypted messages will pass through, but the fact that the communication is kept secret (safe) no matter be it on a public ftp or not.
I do not have Google mail account and using surespot for more than a year without any problem.

**Comment by juanito003** [comment]
Lucky you. Sorry but I was not talking about the end-to-end encryption wich is fine. The fact is that I don't get any notification when I receive a new message from another surespot user. So I have to manually open my surespot everyday to see if I received something. If you get notification, it meens you have the gapps installed even if you don't use it and you have an Android ID. On my phone I don't have an Android ID because I didn't install the gapps and I don't want to. Many others are in the same case as I am and it is not practical.

**Comment by yegortimoshenko** [comment]
Surespot hasn't been updated since March 2017 and still relies on GCM for notifications. I think this should be labeled with "waiting for objections".
