### ISSUE TITLE
Add DAVdroid (Android, CalDAV, CardDAV...)

### ISSUE THREAD

**Issue by Zepmann** [nylira/prism-break#885]
Android does not have support for CalDAV or CardDAV. DAVdroid is an open-source Android application that allows access to CalDAV calendars and CardDAV contact lists in Android through standard Calendar(-based) and Contacts(-based) applications. It is an essential component to connect Android to (for example) an ownCloud or Kolab server, and is therefore software that should be listed on PRISM Break.

Official site:
http://davdroid.bitfire.at/

DAVdroid can be obtained at popular online Android software stores. It is also available for free in F-Droid (linked by the official site):
https://f-droid.org/repository/browse/?fdid=at.bitfire.davdroid
https://f-droid.org/wiki/page/at.bitfire.davdroid

Source code (also linked by the official site):
https://github.com/rfc2822/davdroid

**Comment by Raprp** [comment]
Hello

I'm using DAVdroid with posteo and works fine. I just got a question that maybe some of you guys could help.

If I understood correctly DAVdroid is just a connector so we can use Android's calendar app and syncronize with any servers using CalDAV.

My question is if this Calendar app of Android is open-source and safe. Otherwise I woud be using a proprietaray app with an open source connector.

Instead of using DAVdroid + Android calendar should I get an open-source app calendar app compatible with calDAV.

Cheers,

**Comment by Zepmann** [comment]
After more than a year, DAVdroid is still not included on the PRISM Break site. That's unfortunate.

Raprp, DAVdroid is independent from the used calendar application since it offers its calendar data through an open API. If you run AOSP, you will probably have an open-source calendar application. If you run a stock firmware, chances are that you work with a proprietary calendar application.
