### ISSUE TITLE
TrueCrypt and its forks.

### ISSUE THREAD

**Issue by prodigeni** [nylira/prism-break#995]
https://news.ycombinator.com/item?id=7812133
truecrypt.org => truecrypt.sourceforge.net
https://gist.github.com/anonymous/e5791d5703325b9cf6d1

**Comment by hasufell** [comment]
> and have never stopped using it myself

Using software that is not actively developed anymore is dangerous. The reasons why development has stalled don't matter.

**Comment by BigBroza** [comment]
how is safer to use alternatives that have
-not been audited
-not established to cause major problems to the nsa

truecrypt is open source at any rate and if that feels safer to you, you can use a fork, but to me truecrypt did prove its worth more than anything else and I don't see its usage being compromised anytime soon, if it was that easy it would be already done, long ago

**Comment by hasufell** [comment]
> how is safer to use alternatives that have
> -not been audited at all, or nowhere near the same level of budget

The audit is totally incomplete and not really worth much, because the most important thing has not been audited yet: the crypto algorithms.

From a distributor point of view I'd definitely recommend a non-audited active project over a dead audited one, because projects that don't receive updates anymore cannot be recommended under any circumstance. And there are a lot of non-audited projects that are still pretty secure, because they are exposed, widely used and still get security bug fixes (not only independent, professional 3rd party auditors find security bugs...).

**Comment by Zegnat** [comment]
Currently CipherShed seems to be the most solid fork to have come from TrueCrypt, the latest news posted by TCnext (who I have previously called “The Swiss”) is also all about CipherShed.

Does anyone know how the audit is progressing? I seem to remember they were also going to “audit” the licence? Maybe I haven’t been looking at the right channels, anyone who can fill me in?

I am with @hasufell that we cannot go back to recommending base TrueCrypt if it is an abandoned project. I have before argued that some credit has to be given to the developers when they pull their own tool off the market. Sure this could be fuelled by anything, including governments coming down on them, but all that is speculation. What isn’t speculation is the fact that the original developers have stopped all support for the project.

**Comment by hasufell** [comment]
> truecrypt is open source at any rate and if that feels safer to you, you can use a fork

Truecrypt is NOT opensource according to the definitions of the OSI.
See https://en.wikipedia.org/wiki/TrueCrypt#License_and_source_model

I don't use such software in the first place and have never seen the need for truecrypt (or any of the forks) while there are solutions that are truly free and even part of the linux kernel and are as such well maintained.

**Comment by sedrubal** [comment]
Ok.

But if the cryptocalypse takes place and people find out, that the crypto algorithm that is used by Linux kernel is not secure, we need alternatives.

And I heard of feature of truecrypt, that you can install 2 storage with 2 passphrases, so if you enter one passphrases the other storage can't be found. I think, this is a useful feature that is unique between cryptographic tools.

**Comment by nodiscc** [comment]
A real TrueCrypt alternative should

 * be Free Software
 * be maintained
 * be audited and secure
 * be easy of use (GUI?)
 * support portable file containers out of the box
 * support hidden volumes (optional)
 * be cross-platform (optional)

So far none of the alternatives on prism-break match this description. I personnally use LUKS volumes through a custom shell script (very few users are going to do this).

**Comment by hasufell** [comment]
> But if the cryptocalypse takes place and people find out, that the crypto algorithm that is used by Linux kernel is not secure, we need alternatives.

That's a mathematical problem and will not just affect the linux kernel. We already know that a lot of algorithms are not very safe against e.g. quantum computers. And there are alternatives.

> be easy of use (GUI?)

https://code.google.com/p/zulucrypt/

> So far none of the alternatives on prism-break match this description.

Including TrueCrypt, even while it was still recommended and actively developed.

**Comment by nodiscc** [comment]
> https://code.google.com/p/zulucrypt/

This needs an audit or more widespread use before including it; cryptsetup/LUKS should also be audited (even though I tend to trust it because it has widespread use, is Free Software, and is around for a long time).

It's also not cross platform (encrypting data on proprietary OSes is bad practice, but not totally pointless. Users will need a transition period before switching OSes, see https://github.com/nylira/prism-break/issues/1008 - I agree it needs a clear warning. FreeOTFE used to allow handling LUKS volumes on windows, but it's no longer maintained)

> Including TrueCrypt, even while it was still recommended and actively developed.

True.

**Comment by hasufell** [comment]
> This needs an audit or more widespread use before including it;

It's just a GUI/user interface to cryptsetup which is a tool to access the kernel module dm-crypt which IS widely used.

I'm not saying there should be no dedicated audit for kernel modules, but I generally trust stuff more that is in the kernel with a GPL-2 license and a lot of people looking at it regularly, instead of something developed in closed-fashion with an obscure license.

In addition, prism-break has no policy to only include audited software (and I think that would be a mistake).

**Comment by izmine** [comment]
IsTrueCryptAudited? Yes, right now completed by Mathew Green and his team.

https://opencryptoaudit.org/
http://istruecryptauditedyet.com/
http://blog.cryptographyengineering.com/2015/04/truecrypt-report.html

As far as I can see, the result of their two-phased investigation is: True Crypt v7.1a is not perfect, but secure! Its version for Windows included.

So, isn't it time to change our mind "TrueCrypt currently has security issues and is not recommended"!

**Comment by Zegnat** [comment]
I read this today as well and am still debating wether this means we should start recommending TC again or not, but the security note can be removed :+1:

**Comment by hasufell** [comment]
> True Crypt v7.1a is not perfect, but secure!

err what? Did you read the part about "AES implementation susceptible to cache-timing attacks"?

**Comment by Zegnat** [comment]
> Did you read the part about "AES implementation susceptible to cache-timing attacks"?

I did not, as I have only had the time to read the surrounding media coverage (e.g. [Schneier](https://www.schneier.com/blog/archives/2015/04/truecrypt_secur.html)). Interesting how none of the articles I have seen have highlighted that in the slightest.

**Comment by hasufell** [comment]
In addition, read

> B.3 Program Flow
Much of the review was focused on functions and use of cryptography as individual discrete com-
ponents. The``statemachine' 'governing when these lower-level functions are called, how errors are
handled, and under what circumstances a function may not be called should be reviewed in more
detail. While CS did look for errors of this sort, and did not identify any, the depth of review was
governed by time constraints and merits additional examination.

I'm not sure I'd consider an audit anywhere near complete if it doesn't closely examine the Program Flow.

**Comment by BigBroza** [comment]
hasufell, did you miss the documents establishing that even the NSA could not crack truecrypt?

reminder : http://www.theverge.com/2014/12/28/7458159/encryption-standards-the-nsa-cant-crack-pgp-tor-otr-snowden

ok so if you wouldn't rely on truecrypt, then on what else? based on what? your crusade is a bit suspicious

I am highly disappointed in the prism-break project, something certainly isn't right if a project that was originally supposed to make it harder for the nsa, has been warning users against truecrypt for so long, although it was obviously a ploy from the nsa, and although it is established to be one of a select few softwares that cause difficulty to the nsa

**Comment by Zegnat** [comment]
@BigBroza, I would like to point out that none of this are @hasufell’s words. It is the direct findings of the independent audit.

Page 14 of [the recently released Phase Ⅱ](https://opencryptoaudit.org/reports/TrueCrypt_Phase_II_NCC_OCAP_final.pdf):

> By choosing inputs carefully, an attacker can induce variable timing dependent on secret key material. By measuring these timings and making statistical inferences, they can recover secret keys completely.

I am not a security researching, but the words ‘recover’ and ‘secret keys’ are not something I like to see in a single sentence. The Risk Summary (page 5) puts this vulnerability on a very high risk level, while the ‘sophistication required for an attacker’ is only middle-ish. You can probably assume the NSA has high sophistication, so they would definitely be able to make use of this vulnerability.

If that’s the case, who says the NSA wouldn’t be able to start using this vulnerability to obtain your keys? Or aren’t already doing so?

**Comment by vyp** [comment]
> ok so if you wouldn't rely on truecrypt, then on what else?

> ...something certainly isn't right if a project that was originally supposed to make it harder for the nsa, has been warning users against truecrypt for so long, although it was obviously a ploy from the nsa, and although it is established to be one of a select few softwares that cause difficulty to the nsa

Honestly, my opinion is that we should ***really*** stop pretending that Windows is viable to use whilst persuing this goal of hindering the NSA. If dm-crypt is not a solution because it is not cross platform, then that is complete nonsense. I understand the ["stepping stone theory"](https://en.wikipedia.org/wiki/Gateway_drug_theory) (i.e. using things on proprietary systems is not completely pointless as it may serve to ease the process to switch to a free system), but you cannot stay on Windows forever and proclaim "I'm secure".

Why are you so insistent on something which still has confirmed flaws as hasufell and Zegnat points out? Not only does it have this vulnerability, but I feel the need to reiterate what hasufell said, "who will fix it?". Confirmed flaws + no one to fix out, at least for now. So *you* seem suspicious if anyone really. 

I cannot believe you still trust it and use it. Maybe I'm wrong and you're right and it was some successful ploy by the NSA, but I feel the best course of action at the moment is clearly to treat it as lost. Better safe than sorry.

**Comment by hasufell** [comment]
> Honestly, my opinion is that we should really stop pretending that Windows is viable to use whilst persuing this goal of hindering the NSA.

@vyp 
There is a _huge_ thread here on prism break where I ranted for days about it. But it seems most people disagree. So be it.

> If that’s the case, who says the NSA wouldn’t be able to start using this vulnerability to obtain your keys? Or aren’t already doing so?

@Zegnat 
Yes... and the question remains: who is going to fix it? Which fork is actually properly maintained and so on.

@BigBroza I don't use any sort of disk-encryption, because I think it is useless, unless you are using a laptop abroad. The main attack vector is not to steal your hard drive and decrypt it... it's getting into your pc while you are online and all files are already accessible. But I dare say that dm-crypt is currently a very sensible choice, because it is maintained within the kernel and every code change in the kernel goes through a huge hierarchy of reviewers until it ends up at Linus repo. Sure, that's no guarantee, but developer workflow is an extremely important point when arguing about security/reliability.

**Comment by izmine** [comment]
Besides all (and sometimes too sophisticated) debates about truecrypt and its right now completed OSCP-Audit of v7.1a for Windows (see #995 and diverse „closed“ forks), please let us (also) remember what really counts! 

Some facts about this „Snowden-proven“ piece of disk encryption-software out-on-fire/in-the-wild:

Operation Satyagraha

In July 2008, several TrueCrypt-secured hard drives were seized from Brazilian banker Daniel Dantas, who was suspected of financial crimes. The Brazilian National Institute of Criminology (INC) tried unsuccessfully for five months to obtain access to his files on the TrueCrypt-protected disks. They enlisted the help of the FBI, who used dictionary attacks against Dantas' disks for over 12 months, but were still unable to decrypt them.

United States v. John Doe

In 2012 the United States 11th Circuit Court of Appeals ruled that a John Doe TrueCrypt user could not be compelled to decrypt several of his hard drives. The court's ruling noted that FBI forensic examiners were unable to get past TrueCrypt's encryption (and therefore were unable to access the data) unless Doe either decrypted the drives or gave the FBI the password, and the court then ruled that Doe's Fifth Amendment right to remain silent legally prevented the Government from making him or her do so.

David Miranda

On 18 August 2013 David Miranda, partner of journalist Glenn Greenwald, was detained at London's Heathrow Airport by Metropolitan Police while en route to Rio de Janeiro from Berlin. He was carrying with him an external hard drive said to be containing sensitive documents pertaining to the 2013 global surveillance disclosures sparked by Edward Snowden. Contents of the drive were encrypted by TrueCrypt, which authorities said "renders the material extremely difficult to access." Detective Superintendent Caroline Goode stated the hard drive contained around 60 gigabytes of data, "of which only 20 have been accessed to date." She further stated the process to decode the material was complex and "so far only 75 documents have been reconstructed since the property was initially received."

Guardian contributor Naomi Colvin concluded the statements were misleading, stating that it was possible Goode was not even referring to any actual encrypted material, but rather deleted files reconstructed from unencrypted, unallocated space on the hard drive, or even plaintext documents from Miranda's personal effects. Glenn Greenwald supported this assessment in an interview with Democracy Now!, mentioning that the UK government filed an affidavit asking the court to allow them to retain possession of Miranda's belongings. The grounds for the request were that they could not break the encryption, and were only able to access 75 of the documents that he was carrying, which Greenwald said "most of which were probably ones related to his school work and personal use."

James DeSilva

In February 2014, IT department employee James DeSilva was arrested on charges of sexual exploitation of a minor through the sharing of explicit images over the Internet. His computer, encrypted with TrueCrypt, was seized, and DeSilva refused to reveal the password. Forensics detectives from the Maricopa County Sheriff's Office were unable to gain access to his stored files.


https://en.wikipedia.org/wiki/TrueCrypt

**Comment by hasufell** [comment]
@izmine how does any of the help after the disclosure of high-severity vulnerabilities? You want to recommend software that is both discontinued and **known** to be vulnerable? Those two elements don't play well together. So I ask again: who is going to fix it? Who is _properly_ maintaining that codebase?

**Comment by Zegnat** [comment]
As far as forks go, I had high hopes for CipherShed. They shared their thoughts on the Phase Ⅰ very openly and you can look up exactly who are leading the project. They have been terribly silent as of late though.

A lot of what we are talking about here depends on your personal threat level. Like @hasufell said, you probably do not even need full-disk encryption simply because someone stealing your drives isn’t part of your personal threat model. PRISM Break however deals with the highest threat level possible: a nation-size opponent targeting you specifically.

You are trying to keep your hard drive encrypted when facing an organisation that has been able to cast a dragnet over the entire internet, bringing in all sorts of communications, like the NSA. Or an organisation that has spend 20 years developing tools to wiretap you using firmware, something essential to use any of your hardware, like the Equation Group. These two may even be the same organisation.

I can certainly belief that the local sheriff’s office’s ‘forensics detectives’ were unable to crack AES. Or that the limited time U.K. officials had with Miranda’s hard drives would allow them to do any sort of statistical inference on the secret key.

But if you are a nation-sized player with no concern for time or money, what are the chances the Phase Ⅱ report is the first time you hear about TrueCrypt’s flawed AES implementation? Probably slim. And if you already knew about these flaws, would you already have developed the software needed to automate the timing attacks on TrueCrypt volumes? Probably so. As a website that is trying to stop the such a big opponent from storing a copy of your hard drive and slowly hack away at its protection, should PRISM Break recommend a tool that now has a publicly documented flaw? No.

And there-in lies the real crutch. Sure you can do just as Bruce Schneier and keep using TrueCrypt to protect your data. And you will **probably** be fine. However, PRISM Break should be recommending the many other encryption implementations that do not have known flaws. If dm-crypt is using an AES implementation that is not vulnerable to timing attacks, it is obvious we have to recommend that over TrueCrypt.

**Comment by izmine** [comment]
"how does any of the help after the disclosure of high-severity vulnerabilities?" (hasufell)

CryptAcquireContext may silently fail in unusual scenarios - Cryptography - High
AES implementation susceptible to cache-timing attacks - Cryptography - High 

"should PRISM Break recommend a tool that now has a publicly documented flaw?" (zegnat)

YES! 

(1) It does what it should do.

"I can certainly belief that the local sheriff’s office’s ‘forensics detectives’ were unable to crack AES. Or that the limited time U.K. officials had with Miranda’s hard drives would allow them to do any sort of statistical inference on the secret key."

"Belief" forgot these above examples: 

FBI, "limited"? NSA, "un"limited? Remember: considering TC to be 'catastrophic', the NSA and GHCQ aren't amused. Also remember: an absolute insider-in-exile confirmed they can't crack. 
 
(2) "Not a security researching", but security researchers say:

The cache-timing issue is not a problem unless you're on a server like setting.
https://twitter.com/amp648/status/592067743957921792

Their conclusion in general:

There is no real vulnerability despite the high rating given by the report.
The keyfile mixing issue is the more realistic issue among them all but it has been known for years.
https://veracrypt.codeplex.com/discussions/616471#post1399210

(3) None of the alternatives is more and better audited by scientific experts.

**Comment by izmine** [comment]
"As far as forks go, I had high hopes for CipherShed. 

They shared their thoughts on the Phase ? very openly and you can look up exactly who are leading the project. 
They have been terribly silent as of late though."

(1) Besides that: "very openly ... terribly silent", does "hope" really know "who are leading the CS-project"?

For example:

Jason Pyeron, a member of the project management committee and one of the security developers works for DISA, a government agency. We should do our research on each and every project member.
https://www.reddit.com/r/crypto/comments/2rbpm3/truecrypt_veracrypt_ciphershed_diskcryptor_is/

(2) All open-source solutions are vulnerable to pre-computed digest attacks.
https://veracrypt.codeplex.com/workitem/115

(3) There is no scientific audit by independent experts for all of them.

**Comment by Zegnat** [comment]
> (1) It does what it should do.

… except decrypt and encrypt your data without opening you up for attacks.

> FBI, "limited"? NSA, "un"limited? Remember: considering TC to be 'catastrophic', the NSA and GHCQ aren't amused. Also remember: an absolute insider-in-exile confirmed they can't crack.

I don’t know what their limits are, I just know the examples you gave me and they don’t tell me much. Even if I want to believe in what Snowden says, it is not like he told us about e.g. the Equation Group who may have messed with the hardware currently in your PC. Snowden was a contractor, and within the NSA people are questioning why a contractor would have been able to see as much as he did. We may easily assume there are complete servers full of higher-classified material that Snowden never saw.

But to refute some more of your examples:

* Operation Satyagraha: you say the FBI ‘used dictionary attacks’. The funny thing with dictionaries is that they are useless against good unique passwords. If I have a 200 character truly random password, a year of running dictionaries against it will get you nowhere. This has nothing to do with TrueCrypt however and holds true for any and every encryption implementation.

* United States v. John Doe: remember how these attacks take time? John Doe’s media was confiscated in or after October 2010 and was served to appear (and decrypt) April 7, 2011. That means they were done inspecting his drives and had time to build a case within 6 months. How come this ended so quickly compared to Operation Satyagraha? Because, by their own admission, the scope of the examination was very narrow:
  
  > When pressed by Doe to explain why investigators believed something may be hidden, McCrohan replied, “The scope of my examination didn't go that far.”
  
  Also of note is that the “forensic analysis was able to identify two passwords”. The court document doesn’t really explain this further. It could also mean that they were able to find the passwords for 2 hidden volumes but concluded they were empty or had nothing of value in them. Who is to say they couldn’t find more passwords, given time?
  
  (How do I know all this? Rather than copying Wikipedia I gave a cursory read to [IN RE:  GRAND JURY SUBPOENA DUCES TECUM DATED MARCH 25, 2011 UNITED STATES OF AMERICA, Plaintiff–Appellee, v. JOHN DOE, Defendant–Appellant.](http://caselaw.findlaw.com/us-11th-circuit/1595245.html).)
  
> (2) "Not a security researching", but security researchers say:
> 
> The cache-timing issue is not a problem unless you're on a server like setting.
> https://twitter.com/amp648/status/592067743957921792
> 
> Their conclusion in general:
> 
> There is no real vulnerability despite the high rating given by the report.
> The keyfile mixing issue is the more realistic issue among them all but it has been known for years.
> https://veracrypt.codeplex.com/discussions/616471#post1399210

3 independent researchers from the nccgroup have stated that the cache timing attack has a high risk and only medium sophistication, making it a high severity vulnerability. 1 not-so-independent developer of a TrueCrypt fork then said it wasn’t as high a vulnerability as the report made it seem. Whenever I am asked to make the choice I would probably side with the published report rather than a forum post, but that is just me.

> (3) None of the alternatives is more and better audited by scientific experts.

This I agree with. This is also why CipherShed is telling you to use the now-audited TrueCrypt rather than their fork ’til it comes out of beta. That does not mean PRISM Break should be recommending TrueCrypt though.

As for security people being associated with a government organisation, I wish you good luck trying to find a mathematician that has not at some point received government funding. Believe it or not, governments fund the lionshare of security research because nobody else cares. Even the Tor project is funded that way.

Seeing someone the government trusts with their security work on something for the masses is a plus in my book. As long as other people keep them straight.

Also, I would rather have someone working on my security who I know works for the government than a group of anonymous programmers. But again, that might just be me.

Nothing you have said is really making a case for including anything new on PRISM Break, so I am not sure what we are arguing about, but I hope I have made my personal views clear on the current TrueCrypt-et-al-sphere.

**Comment by hasufell** [comment]
> There is no real vulnerability despite the high rating given by the report.

So they are not going to fix it?

**Comment by izmine** [comment]
"So they are not going to fix it?" (hasufell) In your eyes, if so important just do it! 

Fixing this cache-timing issue would be much appreciated. But...

(1) As security researchers said, there seems to be no REAL need at the moment:
- No real vulnerability DESPITE the high rating given by the report (in general)
- Cache-timing issue is not a problem UNLESS you're on a server like setting (especially)
https://veracrypt.codeplex.com/discussions/616471#post1399210
https://twitter.com/amp648/status/592067743957921792

Therefore, work on other issues has priority.

(2) Your alternative PRISM Break-favorites are vulnerable too.
https://veracrypt.codeplex.com/workitem/115

Maybe you got more detailed information. Are they going to fix their pre-computed digest issue? 

(3) And again, there isn't any scientific audit by independent experts for all of the other disc-encryption solutions! None of its alternatives is more and better audited than TrueCrypt*. 

So, their results and the above both said in mind: 
"You want to recommend software that is both discontinued and known to be vulnerable?" (hasufell) 

Yes, I do recommend! Because TC v7.1a is both mature and stable and up-to-date: "Not perfect, but secure".

At the moment I see hardly any better.




 *) 
done by the most ANONYMOUS (and suspicious) crypto-developers ever, zegnat: "Tesariks" must have been much more conscious than you about: What such a piece of disk-encryption software means to EVERY government and its special services!

(Thx for linking to: http://caselaw.findlaw.com/us-11th-circuit/1595245.html)

**Comment by Zegnat** [comment]
> No real vulnerability DESPITE the high rating given by the report (in general)

What “security researchers” (multiple?) said this? I only see the VeraCrypt developer himself say this and no independent researchers. The three independent researchers that are known to have done an audit flagged this with a high rating.

> Cache-timing issue is not a problem UNLESS you're on a server like setting (especially)

Again, only the VeraCrypt developer has said this. In the forum thread you linked user AndreasAll says “multi-user systems” will be affected, which I belief to include your completely standard Windows installation in an average home.

> Your alternative PRISM Break-favorites are vulnerable too.

Which ones? dm-crypt? DiskCryptor? PRISM Break is not recommending any form of TrueCrypt at the moment.

> And again, there isn't any scientific audit by independent experts for all of the other disc-encryption solutions! None of its alternatives is more and better audited than TrueCrypt*.

[EncFS](https://prism-break.org/en/projects/encfs/) is recommended by PRISM Break and has been audited. This is even flagged on the website with a green label. So saying none have had a publicised audit is simply false.

**Comment by hasufell** [comment]
> In your eyes, if so important just do it!

I will probably never use VeryCrypt or any of the TrueCrypt forks. I don't even use dm-crypt or any other disk-encryption tool. So why should I fix it?

The point was that in order to recommend a TrueCrypt fork it is important to know how upstream behaves and that includes their reaction to the audit.

**Comment by izmine** [comment]
Please, allow one word according to (off-topic) ENCFS and its recommendation:

(1) By the way. 

The only one found, is a one-year-old "paid" security audit of "10 hours".
https://defuse.ca/audits/encfs.htm

Sure, it's not a "joke"? Because, What a contrast to the crowd-funded one-and-half-a-year scientific audit by independent experts around Matthew Green/Kenny Wright!
https://opencryptoaudit.org/

(2) But seriously.

- What about Taylor Hornby's results? At least there ARE 7 SECURITY issues in encfs!

High - Stream Cipher Used to Encrypt Last File Block. Medium - Generating Block IV by XORing Block Number - MACs Not Compared in Constant Time - 64-bit MACs - Editing Configuration File Disables MACs. Low - Same Key Used for Encryption and Authenticatin - File Holes are Not Authenticated.

Furthermore, there are 4 POTENTIAL problems mentioned in the paper.

- What about Hornby's conclusion? encfs is NOT up to speed with modern cryptography practices! 

It ignores many STANDARD best-practices in cryptography. Several previously KNOWN vulnerabilities have been reported, which have NOT been completely fixed.
It IS NOT safe if the adversary has the opportunity to see two or more snapshots of the ciphertext at different times.
It attempts to protect files from malicious modification, BUT there are SERIOUS problems with this feature.

(3) In FACT, also according to user-space encrypted file systems is to repeat:

"Your alternative PRISM Break-favourites are vulnerable too." 

So, wonder why PRISM Break does recommend encfs. Will you guys really continue recommending it seriously? While bashing a well-done piece of crypto-software for vulnerabilities under quite NON-REALISTIC circumstances at the same time!

**Comment by izmine** [comment]
(1) "EncFS is recommended by PRISM Break. EncFS has been audited. This is even flagged on the website with a green label." (zegnat)

Don't COMPARE DIFFERENT kind of solutions! 

If doing so  wrong nevertheless, at least it would be nice to mention clearly that container-based crypto is  much stronger by concept than file-system solutions (f.e. metadata-problems*).

(2) "So saying none have had a publiced audit is simply false." (zegnat)

No, it is not "simply false"! 

As you can see easily...

"There isn't any scientific audit by independent experts for all of the other disc-encryption [!] solutions! None of its [!] alternatives is more and better audited than TrueCrypt" (izmine)

http://www.ssi.gouv.fr/IMG/qualification/2009-08-17_2088_sgdn_anssi_sr.pdf
https://www.privacy-cd.org/downloads/truecrypt_7.0a-analysis-en.pdf
https://madiba.encs.concordia.ca/~x_decarn/truecrypt-binaries-analysis/
http://seclists.org/fulldisclosure/2013/Oct/245
http://istruecryptauditedyet.com/
https://opencryptoaudit.org/

In so far, it's absolutely right to say what I say:

"Their results and the above both [1+2 in former post] said in mind, TC v7.1a is both mature and stable and up-to-date: 'Not perfect, but secure'. At the moment I see hardly any better." (izmine)

(3) What's really wrong, is your citation! 

And that's not nice changing what is said and meant obviously. Here and now we are discussing the DISCS-AND-PARTITIONS-encryption tool TrueCrypt! Therefore could and should it be compared with its alternatives of same kind of crypto, for example freeOTFE**, VeraCrypt, CipherShed or so but nothing else. The same according to an user-space encrypted file system like encFS! It could and should be compared with the PRISM Break-recommended never audited eCryptfs***.



*)
http://www.7-zip.org/
http://sourceforge.net/projects/sevenzip/?source=navbar

Maybe an alternative, because the 7z FORMAT of open source-software 7-ZIP solves this issue of the off-topic encfs-tool:
It provides the option to encrypt 7z archive headers and filenames, encrypts with the AES algorithm with a 256-bit key, generates the key from a user-supplied passphrase using an algorithm based on the SHA-256 hash function. The SHA-256 is executed 218 (262144) times which causes a significant delay on slow PCs before compression or extraction starts. This technique is called key stretching and is used to make a brute-force search for the passphrase more difficult. Current GPU-based, and custom hardware attacks limit the effectiveness of this particular method of key stretching, so it is still important to choose a strong password. The 7z format.

**)
https://web.archive.org/web/20130531062457/http://freeotfe.org/
http://sourceforge.net/projects/freeotfe.mirror/
https://github.com/t-d-k/doxbox

freeOTFE offers a portable mode, eliminating the need to install to the computer. There is also freeOTFE Explorer, a system which allows freeOTFE volumes to be accessed without installing software, and on computers where no administrator rights are available. Supporting numerous hash (including SHA-512, RIPEMD-320, Tiger) and encryption algorithms (Including AES, Twofish, and Serpent) in several modes (CBC, LRW, AND XTS), providing a much greater level of flexibility than a number of other OTFE systems. Support for encryped Linux volumes (Cryptoloop "losetup," dm-crypt, and LUKS).

***) 
https://www.schneier.com/blog/archives/2014/03/an_open_letter_.html
http://www.theregister.co.uk/2014/03/25/bruce_schneier_sneers_at_ibms_nsa_denials/

This IBM-developed and -maintained (off-topic) crypto-tool isn't audited ever.

But it is to believe much harder, that PRISM Break really does and/or wants to continue recommending a tool like ECRYPTFS seriously.

**Comment by Zegnat** [comment]
This will be my last reply on this to hopefully make my stance on both TrueCrypt and its forks clear, and to address some of @izmine’s points. Note that PRISM Break is a community project and my thoughts are in no way indicative of what will and will not end up on the website. Everyone is free to create a pull request for whatever software they want to recommend and make a case for it. If they can gain traction within the community chances are it will be merged in.

Regarding TrueCrypt:

Thank you for the link to [the Ubuntu Privacy Remix Team’s audit of TrueCrypt](https://www.privacy-cd.org/downloads/truecrypt_7.0a-analysis-en.pdf). I had not seen it before. Even so this only means we now have a second audit of TrueCrypt, and an older version at that.

In a previous discussion I made clear that I was against adding software on PRISM Break that was abandoned by their development team. This still holds true for me, even when talking about TrueCrypt. That leaves one of the many forks.

As far as I know none of the forks have been audited. So that part of the discussion goes out the window. It becomes a debate of what fork is the best, gets the best support, and if it should be included.

The TrueCrypt licence has still not been reviewed by [the #IsTrueCryptAuditedYet project](http://istruecryptauditedyet.com) which is an issue for PRISM Break. We have previously excluded solutions that were public-source rather than open-source, and we would have to apply the same ruling to TrueCrypt. This is also a potential problem for forks, I previously found a problem with VeraCrypt where it wasn’t complying with the licence by still including the name TrueCrypt in certain files.

In fact a problem also noticed by the Ubuntu Privacy Remix Team (p. 7), emphasis mine:

> But the own regulations of the TrueCrypt foundation are also incompatible with the GNU General Public License (GPL). This situation complicates the legal status of the TrueCrypt sources. **A continuation by others in case the TrueCrypt Foundation ceases to maintain TrueCrypt or the development of a spinoff product would be very problematic not to say illicit.**

You read that right: “illicit”, forbidden by law.

Not to mention how TrueCrypt itself was based on E4M and might itself be infringing on some copyrights there. (I kid you not, this is one of the points on the Roadmap for CipherShed to fix.)

I feel much better telling people to use any of the dm-crypt LUKS tutorials linked to on PRISM Break than pointing them at TrueCrypt. If they have no choice but to use a portable encryption solution with the possibility of plausible deniability through hidden volumes, I might tell them to try out TrueCrypt. I will also tell them other people in the security community are using it (e.g. Schneier) and that it has been audited. But I will never use it myself or actively recommend it.

Personally I belief there are just too many pitfalls with TrueCrypt, not to mention @hasufell’s legitimate concern about who will be fixing the issues that are being brought up now.

Regarding EncFS:

I am not comparing EncFS and TrueCrypt on a feature-to-feature basis, only as far as both having had published audits and both wanting to encrypt your files. Mostly I wanted to point out that PRISM Break does include publicly audited encryption software. Wether you belief this audit is enough is up to you. All the points made in the audit are accessible in [EncFS’ issue list](https://github.com/vgough/encfs/issues) on the GitHub project and can be discussed there. They are very open about fixing all of the points.

> What a contrast to the crowd-funded one-and-half-a-year scientific audit by independent experts around Matthew Green/Kenny Wright!

So you do respect an audit when it is paid for by several people, but when one man wants to make software more secure and pays for 20 hours of fulltime work by a security researcher you call it a joke?

Igor Sviridov paid Defuse Security for 20 hours of work, [10 hours on EncFS](https://defuse.ca/audits/encfs.htm) and [10 hours on eCryptfs](https://defuse.ca/audits/ecryptfs.htm). Taylor Hornby did this work and published the results. This sounds like a security audit to me.

And what “one-and-half-a-year” are you talking about? The Phase Ⅱ audit took more like a month to a month and a half. When Matthew Green posted [an update on his blog](http://blog.cryptographyengineering.com/2015/02/another-update-on-truecrypt-audit.html) mid-February only a few weeks had passed since contracting the NCC Group with an open starting date, and the final report was finished mid-March.

And what about Hornby’s results? We have included a summary of his conclusion on the PRISM Break website. We felt alright with keeping it as a recommendation because the audit found “EncFS is probably safe as long as the adversary only gets one copy of the ciphertext”. That is reasonable for the number one reason to use encryption: protection in case of hardware theft.

If you have made a different conclusion from reading the audit and checking up on EncFS’ current development, please open a new issue and make your case for having it removed.

**Comment by izmine** [comment]
CipherShed's Compul wrote (April 2015):

"They [4 vulnerabilities found: 1 low - 1 medium - 2 high] do NOT seem to pose a great threat immediately, but are nonetheless ISSUES that will be resolved in CipherShed; first and foremost the AES issue, I would presume, which currently seems more annoying than one may think." https://forum.ciphershed.org/viewtopic.php?f=5&t=80

@hasufell@zegnat: One more vote to cool down and relax a little bit, imho.

**Comment by Atavic** [comment]
I suggest [Gostcrypt](http://www.gostcrypt.org/)
